### ISSUE TITLE
Fetched result is not logged when using collect(), only with fetch()

### ISSUE THREAD

**Issue by ChristofferKarlsson** [jOOQ/jOOQ#10019]
### Expected behavior and actual behavior:
I have enabled DEBUG logging, but the "Fetched result" and "Fetched row(s)" debug messages are not printed.

This doesn't print anything (not the best example, but it shows what I mean):
```
         dsl.selectFrom(TABLE1)
                .where(...)
                .collect(Collectors.toList());
```
But this do print:
```
         dsl.selectFrom(TABLE1)
                .where(...)
                .fetch()
                .stream()
                .collect(Collectors.toList());
```

It seem that the code here doesn't execute when using `collect`: https://github.com/jOOQ/jOOQ/blob/master/jOOQ/src/main/java/org/jooq/tools/LoggerListener.java#L144-L154

### Versions:

- jOOQ: 3.12.4
- Java: 8
- Database (include vendor): Postgres
- OS: Arch Linux
- JDBC Driver (include name if inofficial driver):

**Comment by lukaseder** [comment]
Thank you very much for your report.

Nice catch. There are a few methods which do not pass through the `ExecuteListener::resultStart()` and `resultEnd()` lifecycles, namely all of those that are based on `Cursor::iterator`, which also includes `ResultQuery::fetchStream()` (but not `fetch().stream()`, which fetches the stream eagerly).

There isn't really any meaningful result that is being fetched here as `Cursor::iterator` based executions fetch record by record from the JDBC driver, so each record is in an individual result.

I suspect that our `CursorIterator::hasNext` method needs to check if we've already entered a `ExecuteListener::resultStart` event, and if not, wrap the next record in such a result. We should do this for consistency reasons, because we already do it in `Cursor::fetch`.

A separate question is whether the `LoggerListener` should buffer the first five of these records, and log those instead of each `Result` that is encountered. However, this would mean that logging would be delayed until the 5th record, which could cause confusion when debugging a custom `Collector`...

**Comment by lukaseder** [comment]
Will increase the priority for this as we will continue to embrace `collect()` as a way to map data, especially as internals are re-written to use `collect()` rather than individual loop implementations (https://github.com/jOOQ/jOOQ/issues/9288)

**Comment by lukaseder** [comment]
In a related task, we'll offer a new `Settings` that allows for enforcing the intermediary `Result` collection to be created irrespective of the mode of execution: https://github.com/jOOQ/jOOQ/issues/11892, so `ExecuteListener` implementations will always be able to access this result.
