### ISSUE TITLE
Provide an DSL.ifnull method returning TableField

### ISSUE THREAD

**Issue by Andavin** [jOOQ/jOOQ#10020]
jOOQ Version: 3.13.1 Open Source

Recently, I came onto an issue with building a name field where one column might be null and to move onto a fallback option.

However, when using ifnull it returns a generic `Field<String>` rather than `TableField<Table, String>` despite the fact that I am passing in two `TableField` objects from the same table.

So I thought I'd request an additional method that returns a `TableField` if both objects passed in are from the same table or, barring that, maybe a reason why this isn't implemented already.

**Comment by lukaseder** [comment]
Thanks a lot for your suggestion.

Superficially, this sounds like a useful thing to do, just like in many cases, it would be useful to produce a `TableField` for a `CAST(table_field AS data_type)` expression, and many other expressions where this seems "reasonable".

But it is not for a few reasons:

- We cannot just do this for `ifnull`. We would have to do this for almost every one of these functions, including at least `coerce()`, `convert()`, `cast()`, `coalesce()`, `isnull()`, `nvl()`, `ifnull()`, `nvl2()`, `nullif()`, `iif()`, and possibly even `decode()` and `case_()`, and a few others, including window functions, such as `firstValue()`, `lastValue()`, `nthValue()`, `lead()`, `lag()`, and more. So, the change is significant
- There are actually additional candidates where we could be clever, including `field(Select)`, which wraps a scalar subquery, which might project only a `TableField`, so effectively, the scalar subquery seems to be the same thing as that `TableField`. This will never end, there are too many candidates for such an improvement, as scalar subqueries can be nested infinitely.

But despite my reservations given that this would bloat the API significantly, I also think it's simply wrong. All of these functions produce a column expression. The fact that the column expression is based on any number of `TableField` is irrelevant, because what you're getting back from the method call is not a `TableField`, but an *expression*. A `TableField` is a column expression that is *guaranteed* to be from a `Table` (currently mostly from generated tables), so you can call `TableField.getTable()` on it, and even get a reference to the schema and catalog. What would you get if you called `ifnull(TAB1.COL, TAB2.COL).getTable()`? You wouldn't know. jOOQ wouldn't know. The query has to be executed first, and on each row, the result of this `getTable()` operation would be different. This doesn't make sense.

There are some special cases where transforming an expression differently, if it is based uniquely on `TableField` components, makes sense. Optimisers do this all the time. Here's an example where the Oracle optimiser prefers `NVL()` over the equivalent `COALESCE()` *in some cases*: https://connor-mcdonald.com/2018/02/13/nvl-vs-coalesce. But this is not the same thing as providing users with some sort of API based on the components of the expression. The only reasonable thing to do here is to let you get a hold of the expression type, which is `Field`. Not `TableField`.

In any case, this looks like a case of an [XYProblem](http://xyproblem.info/). I think I made it clear that the requested feature cannot be added, but I believe you had a much more viable problem that you tried to solve at first, which I'm more than happy to discuss.

**Comment by Andavin** [comment]
I appreciate your explanation in this. I didn't fully grasp the scope of changes that may need to be made especially for something so relatively trivial that wouldn't have a huge benefit.

To be clear, which may already be understood from my original post, I was meaning a method such as:
```
<R extends Record, V> TableField<R, V> ifnull(TableField<R, V> field1, TableField<R, V> field2)
```
so that the generics are enforced as much as possible.

On the other hand, I definitely see your point. My specific situation came on from me debugging a table alias on a field after it had been wrapped in an ifnull/nvl and finding that `t.field(ifnull(field1, field2))` simply returns null which I incorrectly expected it to alias the internal fields `ifnull(t.field1, t.field2)` for the SQL. It instead simply excluded them; giving me a `Record6` missing the last two values and an extremely odd, hard to debug `ClassCastException`.

My original post would most likely not have helped the situation mentioned above, however, my intent would be to basically allow the internal Nvl object to handle aliases better or at least explicitly throw an exception for this use case if possible.

I have no idea if something along these lines is even possible since, I have very little knowledge of the inner workings of jOOQ. However, this issue is closed, but I do appreciate any further insight you may have on this specific situation.

**Comment by lukaseder** [comment]
> To be clear, which may already be understood from my original post, I was meaning a method such as

Yes, that's what I thought. I also explored the possibility of not binding to a common `R` type for both fields, in case of which the `getTable()` method on the resulting field would make no sense.

If both arguments had the same `R` type binding, the method would be of *very* limited usefulness. Compare that to the significant increase of API surface caused by the many methods that would need to be overloaded for consistency. The cost / benefit is prohibitive.

> My specific situation came on from me debugging a

I'm not sure if I understand. Can you show a code example?

**Comment by Andavin** [comment]
I apologize for the late reply. I didn't see your response here until now. Basically, in the specific situation, I wanted a general fallback for certain fields using ifnull/coalesce.

Specifically:
```
Users u = USERS.as("u");
Users g = USERS.as("g");
Result<Record6<Integer, String, Long, Integer, String, Long>> memberResult = context.select(
    GROUP_MEMBERS.USER_ID,
    u.field(platform.getNameField()), // getNameField returning something like ifnull(NAME, OTHERNAME)
    GROUP_MEMBERS.EXPIRATION,
    GROUP_MEMBERS.GRANTER_ID,
    g.field(platform.getNameField()),
    GROUP_MEMBERS.TIMESTAMP
).from(...)
 .join(u).on(...)
 .join(g).on(...)
 .fetch()
```
When iterating over the result, however, we get unexpected behavior:
```
for (Record6<Integer, String, Long, Integer, String, Long> membersRecord : memberResult) {
    long expiration = membersRecord.value3(); // ClassCastException - cannot cast Integer to Long
}
```
This, I found out, is because the two fields above that are `u.field(ifnull(...))` simply return null. Once fetched, then, we get a `Record6<Integer, String, Long, Integer, String, Long>` with both of the `String` values missing altogether and the values in front of them moved back.

So, when I get `record.value2()` it's actually returning `record.value3()` and `record.value3()` returns `record.value4()` etc.

In my opinion, there should be at least an exception thrown somewhere in here to let me know that I can't use `table.field(ifnull(...))`.

What I did that ended up fixing it was just passed the aliased table to `platform.getFieldName(u)` which then built the ifnull/coalesce using `table.field(...)` on each internal field to the function.

**Comment by lukaseder** [comment]
Thanks for documenting this issue. This is unfortunate. In a future version, we might fix the `field` method to throw an exception rather than returning `null`.

But I'm not quite sure how that's related to this entire issue...?

**Comment by Andavin** [comment]
It's actually an unrelated issue that I stumbled upon and ended up making this suggestion issue before realizing I had a problem with the code in the first place.

Should I make a separate issue with the documentation above so that it can be under a proper title/category?

**Comment by lukaseder** [comment]
We already have issues for better fail-fast strategies...
