### ISSUE TITLE
is there any tool to convert sql to jooq code?

### ISSUE THREAD

**Issue by wmxj** [jOOQ/jOOQ#10087]
like this: 
sql 'select count(distinct name) from table '
to
dsl.selectDistinct............

**Comment by lukaseder** [comment]
Thanks for your message. There is no such tool yet. We might add the required infrastructure eventually (e.g. a `SQLDialect.JOOQ` dialect: #6277), but it's a lot of work, especially making this user friendly. A third party parser vendor once implemented such a utility. It had almost no traction at all, which is why we stopped the effort at the time.
