### ISSUE TITLE
Support pgjdbc-ng driver

### ISSUE THREAD

**Issue by ben-manes** [jOOQ/jOOQ#10092]
The `pgjdbc-ng` provides nice improvements over the official driver, such as event-based NOTIFY support. However there are compatibility problems with jOOQ when using, likely the driver's fault (e.g. https://github.com/impossibl/pgjdbc-ng/issues/486). Adding support in your test matrix would help find these issues and provide some confidence for those of us who would like to evaluate adopting it.

**Comment by lukaseder** [comment]
Thanks for your suggestion.

I personally tend to not endorse alternative drivers. Especially when the official driver is open source, I wonder what value is created by re-implementing everything rather than contributing e.g. the improved `NOTIFY` support to the official driver: https://github.com/pgjdbc/pgjdbc/issues/1655. I still remember the many sqljdbc vs jtds hassles from back in the days when the official Microsoft driver was indeed insufficient in many ways (which is luckily no longer the case), it was a *mess*. Two popular drivers was a very bad thing, not a good thing.

Before we move forward with such support, I'd like to:

1) See significant traction for this alternative driver (there is almost none on the jOOQ issue tracker, over the past years: https://github.com/jOOQ/jOOQ/search?q=pgjdbc-ng&type=Issues)
2) See *very* good reasons for users to prefer it over the official one, especially in a jOOQ context (jOOQ hides most of JDBC), more than just this `NOTIFY` support, which indeed could be improved in the official driver.

Keeping in mind that PostgreSQL has *a lot* of edge cases with respect to things like casting data types, serialising data types, etc. Adding the pgjdbc-ng driver to our test matrix might expose *a lot* of problems like the one you've mentioned (e.g. #6547).

If there is more popular interest (see above 1 and 2), or someone can sponsor our efforts financially, then I might run the test suites and report issues to pgjdbc-ng, like the one you've reported above.

**Comment by lukaseder** [comment]
A non-representative poll on Twitter confirms my reservations:
https://twitter.com/lukaseder/status/1252502442639601664

I haven't heard a success story yet, only pain and suffering :)

**Comment by ben-manes** [comment]
haha, thanks.

My interest was because I needed to use advisory locks with notify and the official driver's support is poor. It seemed awkward to use both drivers, but as you said the new one is not yet robust. It works fine using both drivers, so this isn't a blocker for me or anything. My ask was merely to give the author a thorough list of incompatibilities to help his project mature, since I'm sure his own testing misses a lot of edge tests that will be slow to discover if waiting for user feedback.

**Comment by kdubb** [comment]
@lukaseder I am the author... so wonder no more 😉

The driver was created as a patch against the official driver but due to the large amount of changes to truly implement the JDBC 4.2 specification and my changes were frowned upon. We discussed them at length and saw no way forward other than forking the project, which then became a clean room implementation. This was 7 or 8 years ago, but I've kept up to date on things and I believe it's still a very large amount of work and at this point some of the features of our driver have specifically been rejected in the official project.

As our project moved forward our main goal was to provide a driver that followed the specification as closely as possible and provided all the advanced features that PostgreSQL while the official driver focused on backward compatibility and framework appeasement.

#### the major reasons

* Composite types via `SQLData`, `SQLInput` and `SQLOutput`

  The official driver requires a homegrown solution of parsing PostgreSQL's text representation of a composite type; JOOQ does a bit of this for you so I know you are familiar.  Our driver implement these features correctly.

  This was the driving motivation for the original patch and then the driver's development itself, and 10 years on, using composite types and arrays (and mixing the two) requires everybody to handroll a solution. It is a major missing piece of the official driver and for an advanced server like PostgreSQL that supports all these fantastic features it seems odd.

* Asynchronous Notifications

  As many have pointed out our driver is asynchronous and therefore provides asynchronous notifications from PostgreSQL and it's quite nice. **Note** that the _problems_ with Netty only really appear on local connections (which people tend to performance test with). After an extensive investigation we found that in real world scenarios this difference is nearly completely erased when using a remote server and wholly gone when used in a cloud/kubernetes environment. Although, removing this perceived overhead would be nice and we have reached out to see if a fix is available but nothing as of yet; although early tests with fibers looks very promising!

* Binary Types

  PostgreSQL supports transferring data binary and text for (almost) all of the system types and then for composite types, arrays, etc. and this was another major reason for our building the driver. Our driver is "binary first" and falls back to text only when necessary; this includes when we are handling composites and arrays.

  Interestingly, this was a bone of contention when I discussed patching the original driver but in the years since we started the official driver has brought in a lot of support for transferring types in binary. Unless you are using large composite types and arrays this is probably not a huge difference at this point.

* Date/Time

  The official driver makes concessions to older libraries (like the way it reports `timetz` and `timestamptz`). Our driver favors spec. conformance and so reports the types exactly as they appear and match the specification.
* * As an aside the official driver implements date/time types with a lot of hand rolled conversions around `java.sql` types, we rewrote everything using Java 8 time types and "it just works" with no custom conversion code. This is an example of changes that probably _should_ go into the official driver but are not welcome. 


#### merging/donating

One point I'd like to make clear is that I've discussed with the official driver's lead, on a number of occasions, donating our driver to the foundation.  The thought being that the two drivers could be maintained or, more ideally, with the added community support people could effect a merge of the two drivers and have a single compliant driver.  It's not something they have ever seem interested in.

At this point we have a driver that works really well, provides a lot of extra features and that we really like, therefore we use it. Attempting some type of merge at this point, without the help of the broader community, would take more time that I have to donate and no other maintainers seem interested.

#### in closing

Your project JOOQ is great (seriously.. great work!) and I have attempted to use it on a couple of occasions but we ran into issues with differences between the official driver and our driver which led us to reverting to other frameworks. Having support for our driver would be great to have!

**Comment by lukaseder** [comment]
Thanks a lot for joining and sharing your insight, @kdubb. It's good to have this as a reference for the future.

The regrettable path of every fork that gets "forced" into independence by maintainer disagreement :)

I completely agree that pgjdbc should implement `SQLData`, `SQLInput`, and `SQLOutput`. This would remove quite a few bugs in jOOQ (probably introduce new ones, too) and help reduce complexity for everyone as you mentioned, regardless if they're using jOOQ or JDBC directly. It looks like there's some traction in this area: https://github.com/pgjdbc/pgjdbc/pull/1378, https://github.com/pgjdbc/pgjdbc/issues/641

I'd say the other things are minor. If async notifications is something someone needs, then yes, clearly, the pgjdbc driver is not sufficient. But that could surely have been implemented in a slim proprietary API, without the full JDBC feature set piggy backed onto it :)

An async-capable driver will be requested by many people in the near future, when Loom is ready, so I'm positive that there will be investments in this area. Sure, maybe not quickly enough for some.

> Your project JOOQ is great (seriously.. great work!) and I have attempted to use it on a couple of occasions but we ran into issues with differences between the official driver and our driver which led us to reverting to other frameworks. Having support for our driver would be great to have!

Thanks for your nice words. But well, this is not encouraging, if even you didn't get jOOQ to work for you on your own driver. I don't remember you having gotten in touch at that point?

Your arguments about effort are just as valid for jOOQ. Supporting another driver and making things work, and keeping things working also in the future, is effort. In our case, running a business on top of jOOQ, this would have to be done either in the commercial distributions (I currently don't see a big market for this, compared to e.g. supporting Google BigQuery, first), or via a project paid by a few interested parties.

In general, I rest my case. I don't think two popular competing JDBC drivers are a good thing for any database, see my jtds example (where I think the alternative was *much more* justified than here). I don't know why the maintainers of pgjdbc weren't excited about your contributions, but given that some people are currently working on `SQLData` and Loom is coming, it seems that the major pain points you've solved will be addressed eventually.

So, perhaps, a "good things will come to those who wait" strategy is the best one here, for jOOQ. A strategy which I'm hoping will also spare me investing more time in supporting R2DBC, to show another example of a "fork" that in my opinion will raise more questions than solve problems. I'm definitely glad ADBA has been stopped.

**Comment by lukaseder** [comment]
I don't think there's much value in keeping this issue open. The officially endorsed driver is pgjdbc. The complexity of supporting it, and now also supporting r2dbc-postgres shows that additional driver support will be prohibitive, unless of course, there's a sponsored project, which I'm currently not seeing.
