### ISSUE TITLE
the mistake that No database selected appears when dslContext.resultQuery(sql)

### ISSUE THREAD

**Issue by houshuo521** [jOOQ/jOOQ#10102]
```java
String sql = String.format("select * from workorder where workorder.id in ");
 sql=sql+idString;
 resultQuery = dslContext.resultQuery(sql).fetchInto(Workorder.class);
```

mistake :
> "jOOQ; uncategorized SQLException for SQL [select * from workorder where workorder.id in ('1')]; SQL state [3D000]; error code [1046]; No database selected; nested exception is java.sql.SQLException: No database selected",

**Comment by houshuo521** [comment]
<jooq.version>3.10.5</jooq.version>

**Comment by houshuo521** [comment]
dslContext.selectFrom(WORKORDER).where(WORKORDER.ID.eq(id)).fetchOneInto(Workorder.class);
but this run  normally！

**Comment by lukaseder** [comment]
Thank you very much for your report. A few things:

1. Please be wary of SQL injection risks.

You should *never* need to concatenate strings with jOOQ. Please don't do this:

```java
String sql = String.format("select * from workorder where workorder.id in ");
 sql=sql+idString;
```

There's always a better way, see: https://blog.jooq.org/2020/03/04/never-concatenate-strings-with-jooq/

2. Your actual problem

The error you're getting is that you seem to be using MySQL and have not initialised your JDBC connection with a default database, e.g. in the JDBC connection URL, or with a `USE database_name` statement. jOOQ, by default, always fully qualifies your generated tables, which is why your second query using jOOQ generated code works.

I hope this helps
