### ISSUE TITLE
dsl.countDistinct(FieldAlias) should not be allowed [PostgreSQL dialect]

### ISSUE THREAD

**Issue by MatusiakMichal** [jOOQ/jOOQ#10119]
### Your question:
with such java code :
(VIEW constant is generated by jooq and it represents view in my database called lets say a_view)
```java
public static final Field<OffsetDateTime> TIMESTAMP_TRUNCATED_TO_DATE = trunc(VIEW.EVENT_TIMESTAMP, DatePart.DAY).as("date");

DSL.select(countDistinct(TIMESTAMP_TRUNCATED_TO_DATE)).from(VIEW);
```
jooq generates following query which does not work:
```sql
select count(distinct "date")
from a_view;
```

I wonder why jooq does not inline the alias to full function so the working sql would look like this:
```sql
select count(distinct date_trunc('day',a_view.event_timestamp))
from a_view;
```
### Versions:
- jOOQ:3.12.3
- Java: 11
- Database (include vendor): PostgreSQL 11.5
- OS: does not matter
- JDBC Driver (include name if inofficial driver):          
            <dependency>
                <groupId>org.postgresql</groupId>
                <artifactId>postgresql</artifactId>
                <version>42.2.8</version>
            </dependency>

**Comment by lukaseder** [comment]
Thank you very much for your message. We will enhance the manual with some examples about this, as this is a recurring question: https://github.com/jOOQ/jOOQ/issues/10120

Think about it logically. Yes, it's tempting to work with only one `Field` reference that "magically" does the right thing depending on context. And it already does. The `Field` alias produces its declaration when placed immediately in `SELECT` (because that's how it reads naturally: `FIELD.as("ALIAS")`). Otherwise, it produces only the alias, because alias declarations are impossible outside of `SELECT`.

You may be tempted to think that it does not make sense to generate `"date"` in the `SELECT` clause, where it is not yet defined. But what about `ORDER BY`? It is totally possible to `ORDER BY count(DISTINCT "date")`. In fact, if you use a `UNION` or some other set operation, only the `"date"` alias may be well defined, not the expression.

Some RDBMS would also allow you to use that expression in `HAVING`. What if you *wanted* this behaviour, e.g. because your expression is non-deterministic? It would be difficult to force jOOQ to generate it. You'd have to create a new, separate `field(name("date"))` just for that - very inconvenient.

In your case, on the other hand, you can just assign the expression you *already have* to a variable or member, and use that instead:

```java
public static final Field<OffsetDateTime> DATE = trunc(VIEW.EVENT_TIMESTAMP, DatePart.DAY);
public static final Field<OffsetDateTime> DATE_ALIASED = DATE.as("date");
```

And now, you'd reference `DATE` where you want the expression and `DATE_ALIASED` where you want the alis.

**Comment by MatusiakMichal** [comment]
Well, thank you Lukas for this clarification. Appreciate it:)
