### ISSUE TITLE
Add support for Postgres 12 materialized CTEs

### ISSUE THREAD

**Issue by JamesGuthrie** [jOOQ/jOOQ#10128]
### Use case:

With the release of Postgres 12, postgres automatically inlines CTEs. This removes the CTE optimisation fence, which is great! Sometimes, however, you want to write a query which enforces the optimisation fence. For this use case, postgres added new syntax to force the materialisation of a CTE.

The following two examples have the same behaviour:

Postgres <12:
```
WITH my_cte AS (..)
SELECT * FROM my_cte;
```
Postgres 12+:
```
WITH my_cte AS MATERIALIZED (..)
SELECT * FROM my_cte;
```
(see postgres documentation on with queries: https://www.postgresql.org/docs/12/queries-with.html)

### Possible solution you'd like to see:

I don't know anything about how other database vendors surface this behaviour, so I'm not sure how helpful my suggestion is, but I will make one anyway: 

I would like to suggest the addition of `DSLContext.withMaterialized()`, which can be used to ensure materialization of the CTE on postgres connections.

### Possible workarounds:

Not aware of any.

### Versions:

- jOOQ: 3.12.4
- Java: 14
- Database (include vendor): Postgres 12

**Comment by lukaseder** [comment]
Thanks for your suggestion.

I was aware of this feature in PostgreSQL but didn't want to support it so far. It is surprising that PostgreSQL chose to implement a keyword based hint mechanism *in this particular case*, when otherwise, they are very much against hinting queries, like MySQL, Oracle, SQL Server.

Given that the DSL API for CTEs is already quite big with many overloads and a lot of type safety, I prefer not to rush this addition. It is relatively easy to implement a quick `ExecuteListener` that patches the generated SQL using a regular expression, appending the `MATERIALIZED` keyword.

**Comment by tomdcc** [comment]
Just popping up to vote for this.

>  It is surprising that PostgreSQL chose to implement a keyword based hint mechanism in this particular case

They did so because before PG 12 CTEs were _always_ materialized, but the planner has other options from PG 12, and this may be a regression for many users as they had previously recommended CTEs as a way to force a particular plan.

We just hit that case for a particular query - the planner isn't materializing our CTE anymore and is guessing the wrong way. And we can't add the appropriate keyword in jOOQ directly.

I think I can work around this using the form `dslContext.resultQuery("WITH {0} AS MATERIALIZED ({1}) {2}")` in the meantime, but support in the DSL would be nice.

**Comment by lukaseder** [comment]
Looking into this now.

**Comment by lukaseder** [comment]
We can support the clause also in other dialects, e.g. in Oracle:

- `AS MATERIALIZED` produces a `/*+ MATERIALIZE */` hint
- `AS NOT MATERIALIZED` produces a `/*+ INLINE */` hint

**Comment by JamesGuthrie** [comment]
@lukaseder Thank you very much for providing this implementation, I look forward to testing it in the future. Using jOOQ is always a pleasure, thank you for the work that you do.

**Comment by lukaseder** [comment]
You're welcome :)

**Comment by tomdcc** [comment]
Thanks very much @lukaseder !
