### ISSUE TITLE
UPSERT with already binded data

### ISSUE THREAD

**Issue by MikePryadko** [jOOQ/jOOQ#10218]
Postgres (`EXCLUDED.field_name`):
```sql
INSERT INTO
	some_table (field_1, field_2)
VALUES
	(values_1),
	(values_2),
	(values_n),
ON CONFLICT
	(key_name)
DO UPDATE SET
	field2 = EXCLUDED.field2;
```
MySQL (`VALUES(field_name)`):
```sql
INSERT INTO
	some_table (field_1, field_2)
VALUES
	(values_1),
	(values_2),
	(values_n),
ON DUPLICATE KEY UPDATE
	field2 = VALUES(field2);
```
jOOQ (`???what should I use???`)
```java
DSLContext create = DSL.using("some_config_url");
create.batch(create
	.insertInto(TABLE_NAME)
	.columns(TABLE_NAME.FIELD1, TABLE_NAME.FIELD2)
	.values(null, null)
	.onConflictOnConstraint(key_name)
	.doUpdate()
	.set(TABLE_NAME.FIELD2, _???_))
.bind(REAL_VALUES_1)
.bind(REAL_VALUES_2)
.bind(REAL_VALUES_n)
.execute();
```
What should I write in `_???_` to say to jOOQ "hey man, just take data from row you can't insert!"?
I think it should be special method like `setNull(Field<T> field)` just with *data_from_values* instead of `null`

P.S. Is `batch`+`bind` better than multiple `values()`? I have `List` with 100+ objects and I need to extract some fields like this (`MyData` is more complex than table in DB):
```java
@Autowire
private DSLContext dsl;

public void insertAndUpdate(List<MyData> data, AnotherType smth) {
    var query = dsl.insertInto(table_name).columns(columns_names);
    for (MyData item : data) {
        query.values(item.getField1, item.getField2, smth);
    }
    query.execute;
}
```
Sorry, but your documentation is poor(((

**Comment by lukaseder** [comment]
Thanks for your report.

We have a `VALUES()` clause in `MySQLDSL`: https://github.com/jOOQ/jOOQ/issues/2134. The `EXCLUDED` pseudo table is not yet supported out of the box. See #5214 

You can always very easily roll your own with the plain SQL templating feature, which is very useful for these edge case, vendor specific features: https://www.jooq.org/doc/latest/manual/sql-building/plain-sql-templating

> P.S. Is batch+bind better than multiple values()? I have List with 100+ objects and I need to extract some fields like this (MyData is more complex than table in DB):

I think that would be an excellent question for Stack Overflow. It depends on many things, which aren't necessarily related to jOOQ

> Sorry, but your documentation is poor(((

How can we improve?

**Comment by MikePryadko** [comment]
@lukaseder thanks for answer!
> We have a VALUES() clause in MySQLDSL

That's cool, but I use Postgres(
> See #5214

Looks like there is no clear answer... `TABLE.as("excluded")`? `DSL.unquotedName()`? `new MyTable(DSL.name("EXCLUDED"), null)`? `rename(String)`? `DSLContext.mergeInto()`?
> You can always very easily roll your own with the plain SQL

Ok, how? your link did not describe it :disappointed: IMHO
> I think that would be an excellent question for Stack Overflow. It depends on many things, which aren't necessarily related to jOOQ

The [manual](https://www.jooq.org/doc/3.13/manual/sql-execution/batch-execution/) states quite specifically. But somewhere in another issues I've seen using `.record()` method (or someting  simiar) :neutral_face: JDBC have only one way to do that job, so jOOQ also should have only one way - right?
> How can we improve?

For the first, javadoc must be comprehensive (like Oracle's one)
For the second, jOOQ AFAIK is a wrapper around JDBC, so docs should show two things:
1. how JDBC's functionality submitted in jOOQ;
2. in which cases jOOQ is "better" than plain JDBC.

I hope it would be useful for you and jOOQ project :relieved:

**Comment by lukaseder** [comment]
That manual page explains the concept of [plain SQL templating](https://www.jooq.org/doc/latest/manual/sql-building/plain-sql-templating/). How to translate the concept to individual cases can't be documented in this manual, because there are many many of these cases...

I'm always happy to provide specific examples upon request. For example, in this case, this could work:

```java
Field<?> excludedFieldName = DSL.field(
  "excluded.{0}",
  SOME_TABLE.FIELD_NAME.getDataType(),
  SOME_TABLE.FIELD_NAME.getUnqualifiedName()
);
```

> JDBC have only one way to do that job, so jOOQ also should have only one way - right?

JDBC does not have only one way to do this job. You can write (ignoring resource management for brevity):

```java
Statement s = c.createStatement();

// Insert several records in a single static statement
s.executeUpdate("insert into t (a, b) values (1, 2), (3, 4)");

// Insert several records in multiple static statements
s.executeUpdate("insert into t (a, b) values (1, 2)");
s.executeUpdate("insert into t (a, b) values (3, 4)");

// Batching several static statements
s.addBatch("insert into t (a, b) values (1, 2)");
s.addBatch("insert into t (a, b) values (3, 4)");
s.executeBatch();

// Insert several records in a single prepared statement
PreparedStatement ps = c.prepareStatement("insert into t (a, b) values (?, ?), (?, ?)");
ps.setInt(1, 1);
ps.setInt(2, 2);
ps.setInt(3, 3);
ps.setInt(4, 4);
ps.executeUpdate();

// Insert several records in a multiple prepared statements (...)

// Insert several records in a single batched prepared statement, one record per statement
PreparedStatement ps = c.prepareStatement("insert into t (a, b) values (?, ?)");
ps.setInt(1, 1);
ps.setInt(2, 2);
ps.addBatch();
ps.setInt(1, 3);
ps.setInt(2, 4);
ps.addBatch();
ps.executeBatch();

// There are more...
```

The manual page that you've linked already shows that JDBC has two ways of batching. Having only one way to do things is the wrong approach in terms of performance. All database products differ in how they optimise processing large data sets. In the past, I've identified (at least) three areas where large scale insertions can profit from being chunked into smaller pieces:

- The "bulk" size (how many rows are inserted *per statement*)
- The "batch" size (how many statments are sent to the server *per TCP/IP roundtrip*)
- The "commit" size (how many database interactions are committed as a single transaction, optimising UNDO/REDO logs)

jOOQ supports ~25 RDBMS, and they're all different. We cannot give a general hint on best practices, and at the same time, do not want to limit users in their choice of what's best for them.

In the case of batch operations, the two types of submitting a batch corresponds to the two types of submitting a batch in JDBC (many binds per prepared statement, or many static statements per roundtrip). JDBC is completely SQL agnostic, so the "bulk size" approach is transparent to JDBC, but it's something you might have done manually with JDBC as well. The difference here is that the jOOQ API offers bulk sizes explicitly by calling that `values()` method several times.

And, of course, you can combine the "batch size" and "bulk size" approaches.

> For the first, javadoc must be comprehensive (like Oracle's one)

Which particular javadoc do you mean? Are you comparing individual classes' javadoc, or is this a general feeling?

> For the second, jOOQ AFAIK is a wrapper around JDBC, so docs should show two things:

I'm trying to think about how this could be considered... The way how jOOQ translates to JDBC is discussed a few times across the manual and Javadoc. Perhaps there's room for adding another page that discusses this more specifically, or we could improve this page (did you find this one?): https://www.jooq.org/doc/latest/manual/sql-execution/comparison-with-jdbc/

But I'm not quite sure what your expectation is here. Yes, jOOQ is a wrapper around JDBC and in general, the strategy is that there are no suprises in jOOQ. If someone is fluent with JDBC, they should be fluent with jOOQ immediately.

The batch API has been a source of confusion in the past, we're aware of its usability issues: https://github.com/jOOQ/jOOQ/issues/5753, but don't have an answer yet. Documentation doesn't seem to be the answer in this area, a better API might be.

> in which cases jOOQ is "better" than plain JDBC.

It seems to me that you're questioning jOOQ *in general* based on this *particular* experience with the batch API. Please, don't 😀. jOOQ's core value proposition is clear. It's a type safe, embedded DSL that allows for writing SQL statements that the Java compiler understands. This has numerous benefits. When those benefits outweigh the "cost" of translating native SQL to jOOQ (and they always do when you have dynamic SQL, or large database schemas, large teams, etc.), then people tend to use jOOQ for most queries, and fall back to JDBC only occasionally.

We wouldn't document those cases when JDBC is "better", because those are simply missing features, and we'd love to hear about those, so we can improve in those areas. Our goal is for JDBC to never be "better" than jOOQ, which is why you would get a more nuanced opinion here elsewhere, from third parties.
