### ISSUE TITLE
JPADatabase should allow some customizations

### ISSUE THREAD

**Issue by tkalmar** [jOOQ/jOOQ#10228]
### Use case:

We have an project with JPA entities. For some of our queries we like to use jooq. We have an postgresql database and our unit tests are running against an h2 database in `;MODE=PostgreSQL;`
This is needed to use UUIDs as native Usertype.
When generating code with jooq we encountered the problem that this setup is not well supported.
So for code generation to work H2 should be started in the same mode with an alternative hibernate dialect.

### Possible solution you'd like to see:

Let JPADatabase be more customizable to set the jdbc-Connnection and HibernateDialect to use from configuration.

### Possible workarounds:
Reimplement JPA-Database with alternative Hibernate-Dialect and modified connection-string

### Versions:

- jOOQ: 3.13.2
- Java: openjdk 11.0.7 2020-04-14
- Database (include vendor): H2 / PostgreSQL
- OS: Windows 10
- JDBC Driver (include name if inofficial driver): org.h2.Driver

**Comment by tkalmar** [comment]
I can submit an PR which makes the dialect and additional connection Parameters configurable via properties.

**Comment by lukaseder** [comment]
Thank you very much for your suggestion.

The fact that we're currently using H2 behind the scenes is not something that we'd like to document or maintain - so a new feature that allows for specifying H2 specific parameters is not desireable. For example, in the near future, we're hoping to intercept the DDL produced by Hibernate in the `JPADatabase`, and interpret it, rather than execute it.

I suspect that your suggested workaround *"Reimplement JPA-Database with alternative Hibernate-Dialect and modified connection-string"* is the best way forward right now.

**Comment by lukaseder** [comment]
I'm closing this for now. There are better improvements on the roadmap that would address these problems, including: https://github.com/jOOQ/jOOQ/issues/6551 (connecting to a testcontainers managed database), https://github.com/jOOQ/jOOQ/issues/7034 (interpreting Hibernate's generated DDL)
