### ISSUE TITLE
Batch Insert; keeping default values

### ISSUE THREAD

**Issue by cfstras** [jOOQ/jOOQ#10405]
### Your question:

The [documentation of `BatchBindStep.bind(Object[]...)`](https://www.jooq.org/javadoc/latest/org.jooq/org/jooq/BatchBindStep.html#bind(java.lang.Object...)) states
> "Unmatched" bind values will be left unmodified:

Which leads me to believe that I can create a query with defaulting the end values, e.g. something of the following is possible:

```java
var batch = dsl.batch(
  dsl.insertInto(FLOWERS, FLOWERS.NAME, FLOWERS.OWNER)
    .values(null, "Frank")
);
flowerService.getAllNames().forEach((String name) -> batch.bind(name));
batch.execute();
```

However, this just leads to the PostgreSQL error:
> org.postgresql.util.PSQLException: No value specified for parameter 2.

How is this statement supposed to be interpreted?

### Versions:

- jOOQ: 3.11.9
- Java: 11
- Database (include vendor): PostgreSQL 10
- OS: Mac
- JDBC Driver (include name if inofficial driver): org.postgresql:postgresql:42.2.5

**Comment by lukaseder** [comment]
Thanks a lot for your question. This doesn't sound very clear indeed. I'll have to dig into the implementation to see what this specification was supposed to mean, and how it matches actual behaviour.

Will get back in touch ASAP.

**Comment by lukaseder** [comment]
What this means is that if you don't have the same length for every bind array, then the value of the previous bind array will be re-used, just like when using JDBC's batch API. For example:

```sql
INSERT INTO t (a, b, c) VALUES (?, ?, ?)
```

And then, binding:

```java
Object[][] = {
  { 1, "a", "b" },
  { 2 },
  { 3, "c" }
};
```

This will have the same effect as binding this:

```java
Object[][] = {
  { 1, "a", "b" },
  { 2, "a", "b" },
  { 3, "c", "b" }
};
```

I'm not sure of the historic reason to apply this behaviour, rather than e.g. setting `null` or the init value of the type, instead... Generally, it's not recommended to omit a bind value at a specific position.

I hope this helps.

**Comment by cfstras** [comment]
Thanks, that makes sense.
