### ISSUE TITLE
ImmutablePOJOMapperWithParameterNames no longer injects default values for unmapped primitive arguments

### ISSUE THREAD

**Issue by hubick** [jOOQ/jOOQ#10425]
I'm attempting to inject a jOOQ Record into a POJO having a constructor annotated with `@ConstructorProperties`, which accepts several primitive `boolean` parameters.

Previously, if the Record didn't contain a field for a given parameter name, jOOQ would default to supplying `false` for that parameter. (I don't know if it also supplied `0` for `int` params?)

In 3.13.3, jOOQ now attempts to invoke the constructor with a `null` value for any arguments not found in the Record, which throws an `InvalidArgumentException`.

I'm guessing this is likely a regression as part of the fix done for #10267.

**Comment by lukaseder** [comment]
Thanks a lot for your report. That's an important regressions, indeed. The init values should be passed to constructor arguments, if they're absent.

I don't think there's a simple workaround for this:

- All the queries would have to be adapted to provide the values explicitly
- A custom `RecordMapper` could work
- `DefaultRecordMapper` could be patched

I'll look into this ASAP and will hopefully be able to publish a 3.13.4 patch release this week. In the meantime, I recommend staying on 3.13.2.

**Comment by lukaseder** [comment]
Hmm, not sure if this is a regression caused by #10267, or rather a pre-existing problem exposed by it. The problem is that we produce an uninitialised array in `DefaultRecordMapper.ImmutablePOJOMapper.mapNonnested()`:

https://github.com/jOOQ/jOOQ/blob/253e828e547880efd93448dbb8db1c643a655635/jOOQ/src/main/java/org/jooq/impl/DefaultRecordMapper.java#L975-L982

This array has to be initialised with the init value of each respective type.

**Comment by lukaseder** [comment]
Fixed for jOOQ 3.14.0. Backport scheduled for 3.13.4 (#10431).

Thanks again for your report!

**Comment by lukaseder** [comment]
The fix has been released in 3.13.4, which is available from our website already (https://www.jooq.org/download/versions), and from Maven Central soon
