### ISSUE TITLE
Query object manipulation

### ISSUE THREAD

**Issue by luca91** [jOOQ/jOOQ#10443]
Hi,

some months ago I asked for Query object parsing and manipulation feature in jOOQ([#9198]), e.g. to get all the SELECT Field objects, and I was told to wait for the version 3.13, where a new API for this purpose would have been implemented.  Recently, I checked the release history and I cannot find such a feature in the 3.13 notes nor in the documentation. Has this been postponed to future releases?

Thanks,
Luca

### Versions:

- jOOQ: 3.13.3
- Java: SDK 8
- Database (include vendor): PostgreSQL
- OS: Ubuntu 20.04
- JDBC Driver (include name if inofficial driver): JDBC4

**Comment by lukaseder** [comment]
Thanks for your message.

Unfortunately, the project got delayed as the task is much more complex than we had thought. Offering a public query object model API could be done relatively easily on its own, but in order to get it right, we have to review a lot of things including the way how we currently hand-roll the DSL API, the parser, etc.

We will deliver this functionality eventually, but a promise cannot be made (and should not have been made), because of the significance of this change.

**Comment by luca91** [comment]
Thanks for your answer and for your explanation. 

What do you suggest, then, to reproduce Query object manipulation as some parts of SPI are deprecated?

**Comment by lukaseder** [comment]
I'm sorry, we simply don't have an answer to this yet. We don't have any public API, and current versions are not designed for this set of use-cases, although you can achieve results using reflection, as you've mentioned in #9198.

This is as good as it gets with jOOQ 3.13 and the upcoming 3.14.

**Comment by luca91** [comment]
Ok, thanks for your advise. We will probably use SPI for the moment as it is much cleaner and has high-performance than reflection.

**Comment by lukaseder** [comment]
> We will probably use SPI for the moment as it is much cleaner and has high-performance than reflection.

In that context: Rest assured we will not remove anything from existing `VisitListener` functionality before we have a replacement!

**Comment by luca91** [comment]
That's good to hear. Thanks for the clarification!
