### ISSUE TITLE
Support parsing additional standard interval literals

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#10453]
The parser should be able to parse additional standard interval literals, as supported e.g. by H2:

```sql
INTERVAL '1' YEAR
INTERVAL '1-1' YEAR TO MONTH

INTERVAL '1' MONTH

INTERVAL '1' DAY
INTERVAL '1 00' DAY TO HOUR
INTERVAL '1 00:00' DAY TO MINUTE
INTERVAL '1 00:00:00' DAY TO SECOND

INTERVAL '00' HOUR
INTERVAL '00:00' HOUR TO MINUTE
INTERVAL '00:00:00' HOUR TO SECOND

INTERVAL '00' MINUTE
INTERVAL '00:00' MINUTE TO SECOND

INTERVAL '00' SECOND
```

**Comment by katzyn** [comment]
@lukaseder
`DayToSecond.valueOf(Double.parseDouble(string) * 1000.0)` doesn't looks like the correct solution for H2, because in H2 `INTERVAL SECOND(18, 9)` data type can hold values up to `INTERVAL '999999999999999999.999999999' SECOND`. For example, `Double.parseDouble("10000000.000000001")` is `10000000.000000002`. Rounding issues may hypothetically cause problems even for some small numbers with fractional part, because there is no exact representation of 0.1 in `double` and `float` data types.

**Comment by katzyn** [comment]
Also `INTERVAL -'1' YEAR`, `INTERVAL +'1' YEAR`, and even `INTERVAL - '-1' YEAR` etc. are valid Standard-compliant literals too.

**Comment by lukaseder** [comment]
Thanks, @katzyn. See, every time I touch these intervals, I feel like Hal, fixing a light bulb: https://www.youtube.com/watch?v=AbSehcT19u0.

- Regarding doubles: Yes that's not nice, but to fix this, a few refactorings would be needed. It could be done, but we can still do this later (or not at all, depending on actual user requirements).
- Regarding the esoteric interval syntax: I will definitely wait for someone actually needing this syntax.

**Comment by lukaseder** [comment]
I've created separate issues: #10457, #10458
