### ISSUE TITLE
Question regarding support for older SQLDialects (Postgres)

### ISSUE THREAD

**Issue by filpano** [jOOQ/jOOQ#10465]
Hi,

we were using jOOQ Open Source edition with Postgres. We have a use case where a `JSONB` column would be the best fit for our needs.

To be able to generate the fitting code, we updated to jOOQ `3.13.4`, which does support `JSONB` columns. However, I noticed that support for Postgres 9.5 has been removed from jOOQ open-source as of `3.12.0`. 

Unfortunately, budgetary decisions take its time and would take a while even if we could make our case for the dozen or so Pro Licenses that we would require - similarly, RDBMS version updates are not done quickly.

Until such a time where we could either update to a Pro License - or update our RDBMS, would there be any issues with using `SQLDialect.POSTGRES` against a Postgres 9.5 installation (instead of the Pro Edition-only `SQLDialect.POSTGRES_9_5`)? Are there known issues/limitations? Running our integration tests (which use an embedded Postgres 9.5) does not seem to point to any _obvious_ issues. Does this mean that I would have to go through the entire codebase and note if _any_ jOOQ method that we call has an explicit `SQLDialect.POSTGRES_9_5` to be safe?

Edit: Going back to the release notes (which I did read prior to updating :) ), I saw the following:

> Starting from jOOQ `3.12`, formal support for older RDBMS dialect versions in the runtime libraries is reserved to the jOOQ Professional and Enterprise Editions. The jOOQ Open Source Edition will ship with support for the latest version of an RDBMS dialect, only. The code generator is not affected by this change.

This does explain this behaviour, though I think it may have been useful to include a list of "deprecated" Dialects that this affects.

### Versions:

- jOOQ: `3.13.4`
- Java: `1.8.0_201`
- Database: Postgres 9.5
- OS: Debian Jessie
- JDBC Driver: `org.postgresql:postgresql:42.2.2`

**Comment by filpano** [comment]
Seems like our more in-depth test cases did manage to find some incompatibilities. Some of our classes reference `UpdatableRecordImpl`  (to support some complex inheritance cases), which by itself is not a good idea and discouraged even in `3.11.1` (the previous version we were on). Currently I'm seeing quite a lot of `Field (cast XXX as timestamp with time zone) is not in Rows (XXX, XXY, XXZ)` errors, which are probably not trivial to solve.

**Comment by lukaseder** [comment]
Thank you very much for your message, @filpano.

It is definitely possible to use the jOOQ Open Source Edition 3.13 and later on PostgreSQL 9.5, although, over time, there will be more and more edge cases that may not work optimally. We have a task to document these (known) limitations better in the future: https://github.com/jOOQ/jOOQ/issues/9367. They are not too many, which is why this hasn't been a high priority yet. Some examples:

- There are many features that have been added in a PG version X without any similar functionality that existed before X. The jOOQ API may include support for these features, and the commercial Javadoc documents this, for example https://www.jooq.org/javadoc/latest/org.jooq/org/jooq/impl/DSL.html#groupsUnboundedPreceding() is supported starting from `SQLDialect.POSTGRES_11`. This shouldn't affect you, because you don't have the feature on PG 9.5 anyway, although, you might of course accidentally try to use it. With integration testing against 9.5 on your side, this should not be an issue, though.
- Rarely, PostgreSQL decides to make a backwards incompatible change. For example, starting in PostgreSQL 10, `UPDATE` queries now require a `ROW()` constructor, instead of just the parentheses `()`, when updating more than one row using a subquery, see #6763. Regrettably, prior to PG 10, the `ROW()` constructor wasn't supported at all, so this kind of statement will not work correctly for you in the jOOQ Open Source Edition.
- Some newer PostgreSQL features are replacements for historic features, such as `IDENTITY` columns which replace `SERIAL` columns. If you're using jOOQ to generate DDL statements containing `IDENTITY` columns, those may not work on PostgreSQL 9.5, because the syntax was not yet supported, see e.g. #6659. You can continue to use `SERIAL`, as jOOQ will continue to support the old feature, but it will generate DDL using the new feature. The same is true e.g. for the `FILTER` clause, whose support was added in PostgreSQL 9.4 (so, generated SQL would not work on 9.3)

There aren't too many of these examples in the runtime library, but only the commercial editions, which officially support the older PG versions, are integration tested by us on those versions.

As you've noted from the release notes, we try not to break any older version usage in the code generator, whose meta data queries are more critical. We try to make sure the jOOQ Open Source Edition code generator works on all supported PostgreSQL versions, and frequently fix bugs in case it doesn't. So far, there hasn't been a case where code generation queries couldn't be made to run on older PG versions as well (e.g. we discover dynamically if an `information_schema` column exists in your database and change the query in function of that).

> This does explain this behaviour, though I think it may have been useful to include a list of "deprecated" Dialects that this affects.

Yes, a matrix of jOOQ edition E, distribution D, version X.Y.Z supports RDBMS version A.B.C would indeed be helpful, and will be implemented via #9367

> Currently I'm seeing quite a lot of `Field (cast XXX as timestamp with time zone) is not in Rows (XXX, XXY, XXZ)` errors, which are probably not trivial to solve.

Would you mind creating a separate issue with some details? I don't think there's anything that shouldn't work for you in this area, so that might be a bug.

**Comment by lukaseder** [comment]
We have now added a version support matrix to our website, to better document which jOOQ versions and editions work with what RDBMS versions: https://www.jooq.org/download/support-matrix
