### ISSUE TITLE
DAOImpl file has a few shortcomings about insert function

### ISSUE THREAD

**Issue by CIT-worker** [jOOQ/jOOQ#10492]
The insert method doesn't return auto increment id,bug on line 92 of Daoimpl file it returns.I hope you can modify to add a heterogeneous method to the insert method.i'm poor english i feel so sorry.thanks.i'm a fans for jooq Russia.

**Comment by lukaseder** [comment]
Thanks for your message, and for your nice words.

Line 92 of `DAOImpl.java` is empty:
https://github.com/jOOQ/jOOQ/blob/version-3.13.4/jOOQ/src/main/java/org/jooq/impl/DAOImpl.java#L92

But rather than discussing specific lines, would you mind showing an example that helps reproduce the case you have in mind?  We have a template for creating new bugs, with some ideas on what would be helpful, including an "MCVE": https://github.com/jOOQ/jOOQ/issues/new/choose

`DAO` is capable of returning generated IDs under some conditions, including: 1) mutable POJOs are used, 2) the relevant settings are enabled, 3) an identity is present in your table (and jOOQ knows about it) 4) the RDBMS and JDBC driver can handle it and jOOQ supports them.

**Comment by CIT-worker** [comment]
I am very sorry for my rude requests, I know these can be achieved through inheritance, but my students need to implement these functions in reverse engineering methods, this is just a small suggestion for the use of role adaptation in the project , I once again apologize for my unreasonable request.

**Comment by lukaseder** [comment]
There's no implication of any rudeness, no worries.

But I simply don't know what doesn't work for you or what you're expecting here. Do you want to try again? Can you show what exactly your expectation was (in code), and why it doesn't work for you?

**Comment by lukaseder** [comment]
Closing this for now - the question wasn't clear to me. Will be happy to help in case clarification is available.
