### ISSUE TITLE
record.into(MyPojo.class) does not work on joined queries unless chain through .into(MyPojoRecord.class)

### ISSUE THREAD

**Issue by ericdriggs** [jOOQ/jOOQ#10552]
Acceptance criteria:
* either change Record `record.into` behavior to work for pojo classes when query contains joined columns  OR document the need to go through records for joined queries

### Expected behavior and actual behavior:
**Expected:**
`record.into(Repo.class);`
should work even select joins multiple tables 

**Actual:**
`org.jooq.exception.MappingException: No matching constructor found on type class com.ericdriggs.reportcard.db.tables.pojos.Repo for row type 
  "reportcard"."repo"."repo_id", 
  "reportcard"."repo"."repo_name", 
  "reportcard"."repo"."org_fk", 
  "reportcard"."org"."org_id", 
  "reportcard"."org"."org_name"
	at org.jooq.impl.DefaultRecordMapper.init(DefaultRecordMapper.java:505)
	at org.jooq.impl.DefaultRecordMapper.<init>(DefaultRecordMapper.java:332)
	at org.jooq.impl.DefaultRecordMapper.<init>(DefaultRecordMapper.java:323)
	at org.jooq.impl.DefaultRecordMapperProvider$1.apply(DefaultRecordMapperProvider.java:86)
	at org.jooq.impl.DefaultRecordMapperProvider$1.apply(DefaultRecordMapperProvider.java:83)
	at org.jooq.impl.Tools$Cache.run(Tools.java:3203)
	at org.jooq.impl.DefaultRecordMapperProvider.provide(DefaultRecordMapperProvider.java:83)
	at org.jooq.impl.AbstractRecord.into(AbstractRecord.java:731)
	at com.ericdriggs.reportcard.ReportCardService.getRepoFromRecord(ReportCardService.java:79)`

**Workaround:**
`record.into(RepoRecord.class).into(Repo.class);`

### Steps to reproduce the problem (if possible, create an MCVE: 

Does not work
```
public Repo getRepoFromRecord(String org, String repo) {
    Record record = dsl.
        select().from(REPO).leftJoin(ORG)
        .on(REPO.ORG_FK.eq(ORG.ORG_ID))
        .where(ORG.ORG_NAME.eq(org))
        .and(REPO.REPO_NAME.eq(repo))
        .fetchOne();
    return record.into(Repo.class);
}
```

Works
```
public Repo getRepoFromRepoRecord(String org, String repo) {
    Record record = dsl.
        select().from(REPO).leftJoin(ORG)
        .on(REPO.ORG_FK.eq(ORG.ORG_ID))
        .where(ORG.ORG_NAME.eq(org))
        .and(REPO.REPO_NAME.eq(repo))
        .fetchOne();
     return record.into(RepoRecord.class).into(Repo.class);
 }
```
### Versions:

- jOOQ: '3.13.4'
- Java: 11
- Database (include vendor):  mysql 'Version 8.0.17' (running embedded on com.wix:wix-embedded-mysql:4.6.1 )
- OS: OSX
- JDBC Driver (include name if inofficial driver): com.mysql.cj.jdbc.Driver

**Comment by lukaseder** [comment]
Thanks for your request. What does your `Repo` class look like?

**Comment by ericdriggs** [comment]
Only fails with immutable pojos. When pojos are generated mutably, test passes.
Here's a link to a branch with immutable pojos:
https://github.com/ericdriggs/reportcard/tree/jooq-insert-pojo

**POJO**
https://github.com/ericdriggs/reportcard/blob/jooq-insert-pojo/src/generated/java/com/ericdriggs/reportcard/db/tables/pojos/Repo.java

**Failing Test Case**
https://github.com/ericdriggs/reportcard/blob/jooq-insert-pojo/src/test/java/com/ericdriggs/reportcard/db/RepoJoinedInsertTest.java

**Query**
https://github.com/ericdriggs/reportcard/blob/jooq-insert-pojo/src/main/java/com/ericdriggs/reportcard/ReportCardService.java#L79

**Comment by lukaseder** [comment]
There are a few ways to make this work, out of the box:

- You can enable parameter names in your Java compiler and turn on ` Settings.mapConstructorParameterNames`
- You can add a `@ConstructorProperties` annotation to your constructor
- You explicitly project only the columns you need (this is recommended anyway, to avoid excess TCP/IP traffic). Alternatively, use a `leftSemiJoin()` in your particular case (or an `IN` or `EXISTS` predicate), or an implicit join using e.g. `REPO.org().ORG_NAME.eq(org)`

Other than that, jOOQ cannot really "guess" what the right thing to do here is for you. The default behaviour is to find a constructor whose argument number matches the number of columns in your query.

You might be expecting jOOQ to just match column 1 to parameter 1, column 2 to parameter 2, etc, and just ignore any missing and/or excess source values. This might work in some cases, but in other cases where you might have more than one constructor (and you do), it would lead to new, more difficult to debug and design edge cases where users would expect constructor A to be called, but B is called instead, with incomplete data.

The situation is different when you first map a generic `Record` type to a `TableRecord` type (because the `TableRecord` references actual `TableField` instances, which can be compared with the data from your source `Record`). And then, since you designed your `Repo` class to have as many columns as the `RepoRecord`, there's a match.

Note the entire behaviour is documented in [`DefaultRecordMapper`](https://www.jooq.org/javadoc/latest/org.jooq/org/jooq/impl/DefaultRecordMapper.html)

I hope this helps

**Comment by lukaseder** [comment]
> Note the entire behaviour is documented in [`DefaultRecordMapper`](https://www.jooq.org/javadoc/latest/org.jooq/org/jooq/impl/DefaultRecordMapper.html)

Not entirely. The mapping of `Record` into a `Class<? extends TableRecord>` is not yet documented, it seems: #10558

**Comment by lukaseder** [comment]
... I think the real confusion here is the fact that the `Repo` class is a generated class with a 1:1 correspondence to a table. It seems logical that the mapping should be automatic as well. Alas, jOOQ doesn't know (i.e. "forgets") that the POJO type was generated from a table. It might as well be hand-written, and completely independent of any table meta data.

There might be some way to identify "special" POJOs that were generated by jOOQ, without adding a dependency on jOOQ types (which is the point of jOOQ's POJOs)

**Comment by lukaseder** [comment]
> When pojos are generated mutably, test passes.

For the record, the situation is quite different there. With getters and setters available, we can map values by name. This is not the case for constructors...

**Comment by lukaseder** [comment]
One option to fix this would be to enable generating `@ConstructorProperties`: https://github.com/jOOQ/jOOQ/issues/5698

I'm not sure if we would be turning this on by default, because:

- The annotation is the only thing we depend on from the `java.desktop` module, which is a huge dependency in side of JDK, which we'd like to be able to remove: #7585
- The default behaviour has been to map by column index, not name. Changing the default would be backwards incompatible.
