### ISSUE TITLE
Why is fetchInto returning List<T> instead of a more specific type such as (ArrayList<Worker>)?

### ISSUE THREAD

**Issue by Mosrod** [jOOQ/jOOQ#10556]
### Your question: 
I am having trouble understanding why the following snippet returns a List\<T> type. I have specified the class I would like it to return in the method, but it is returning a generic type (List\<T>) instead of a more specific type that I would prefer. I have found a workaround to this by casting the generic type into my preferred type.

Here is the generated-src structure:
![image](https://user-images.githubusercontent.com/18247709/91677270-3c2fef80-eb10-11ea-8ef3-a0cb8737d09a.png)

Here is the database structure:
![image](https://user-images.githubusercontent.com/18247709/91677299-49e57500-eb10-11ea-8382-d3a8638ddde6.png)

Here is the snippet that I am using:
`create.selectFrom(Worker.WORKER).fetchInto(limehrm.tables.pojos.Worker.class);`

The above snippet would return List<T>, but casting it to ArrayList<Worker> solves my issue:
![image](https://user-images.githubusercontent.com/18247709/91677674-6635e180-eb11-11ea-8297-1f418abc1828.png)

`(ArrayList<limehrm.tables.pojos.Worker>) create.selectFrom(Worker.WORKER).fetchInto(limehrm.tables.pojos.Worker.class);`

Also, inofficial is not an official English word, so it would be great if you could substitute inofficial for unofficial in the issue templates :).

Edit:
Here is the code generation script:
```
org.jooq.meta.jaxb.Configuration configuration = new org.jooq.meta.jaxb.Configuration()
            .withJdbc(new Jdbc()
                    .withDriver(db.driver as String)
                    .withUrl(db.url as String)
                    .withUser(db.user as String)
                    .withPassword(db.password as String)
            )
            .withGenerator(new Generator()
                    .withDatabase(new Database()
                            .withName(db.jooqDbImpl as String)
                            .withIncludes(".*")
                            .withExcludes("")
                            .withInputSchema(db.schema as String)
                    )
                    .withGenerate(new Generate()
                            .withImmutablePojos(true)
                            .withRecords(true)
                    )
                    .withTarget(new Target()
                            .withPackageName(db.packageName as String)
                            .withDirectory(genpath.toString())
                    )
            )

    GenerationTool.generate(configuration);
```
I'm also getting a plethora of errors (seems like warnings since code runs fine) in the generated code.
![image](https://user-images.githubusercontent.com/18247709/91681332-27f1ef80-eb1c-11ea-9575-1aa2c9449137.png)
![image](https://user-images.githubusercontent.com/18247709/91681358-3a6c2900-eb1c-11ea-9d2f-05e2c4c674bf.png)
![image](https://user-images.githubusercontent.com/18247709/91681384-4ce66280-eb1c-11ea-8dfe-d70752ce8db3.png)

Before asking your question, please check out the FAQ too: https://www.jooq.org/faq

### Versions:

jOOQ: 3.13.4
Java: 14
Database (include vendor): Postgres 12.4
OS: Windows
JDBC Driver (include name if inofficial driver): org.postgresql.Driver

**Comment by lukaseder** [comment]
Thank you very much for your request. There are two questions here:

> I have specified the class I would like it to return in the method, but it is returning a generic type (List<T>) instead of a more specific type that I would prefer. I have found a workaround to this by casting the generic type into my preferred type.

In general, Java APIs tend to *never* return a specific implementation of a collection type, but return the relevant interface instead. This isn't specific to jOOQ. You will be hard-pressed to find any API that returns an implementation type (class) rather than a specification type (interface). Look at the various `List.of()` methods. They return `List`, not some specific implementation. The designers of this API may want to change the implementation in the future.

For example, we might decide to return an alternative `List` implementation instead of the one you're seeing right now, such as `java.util.Arrays.ArrayList` (from `Arrays.asList()`), or some jOOQ-internal `List` implementation that is not an `ArrayList`. For example, `org.jooq.Result` extends `java.util.List` for convenience and better interoperability. But there's nothing to gain from also letting it extend `ArrayList` explicitly.

You haven't stated why this is your "preferred type". Do you want to further modify the resulting list? The standard idiom here would be to wrap the results in your own local variable:

```java
ArrayList<Worker> list = new ArrayList<>(query.fetchInto(Worker.class));
```

> I'm also getting a plethora of errors (seems like warnings since code runs fine) in the generated code.

These seem to be false positives. I cannot reproduce any such errors or warnings with javac, Eclipse, or IntelliJ. The Java language feature used here is covariant return types, which has been introduced in Java 5. I don't know why your IntelliJ configuration thinks that there's anything wrong with that code.

So, I'd say, something is ill configured in your IntelliJ instance, or you found a bug in IntelliJ

**Comment by Mosrod** [comment]
Thank you so much for your response.
Sorry about the confusing wording of the question and it seems like this is an issue with Intellij (https://youtrack.jetbrains.com/issue/IDEA-169456) giving out random and confusing errors.

![PertinentEvergreen17](https://user-images.githubusercontent.com/18247709/91736018-17249680-eb7b-11ea-9c90-894db642a894.png)

If I ignore this error, everything compiles and runs fine, so it is not an issue with jOOQ.

To finally solve this, I have deleted the .idea folder and switched JDK versions a couple of times (from 14.2 to 1.8 to 14.2) and the issue now seemed to have disappeared (no more errors in generated-src or in my program).

Thank you for your reply,
Nathan
