### ISSUE TITLE
mysql field convert java attr

### ISSUE THREAD

**Issue by lizhehong** [jOOQ/jOOQ#10746]
mysql filed type :bit(11)
java attr type :enum

how to conf pom to convert to java enum

ex:
00000000010  -> wx
00000000001 -> qq
00000000011-> wx\qq
.....

Thank you

**Comment by lukaseder** [comment]
Thank you very much for your question.

The way to do these kinds of things in jOOQ is by means of custom data type conversion, see:
https://www.jooq.org/doc/latest/manual/sql-execution/fetching/data-type-conversion/

an `org.jooq.Converter` can be written for any pair of data types, and can then be attached to generated code:
https://www.jooq.org/doc/latest/manual/code-generation/custom-data-types/

We currently don't correctly support the MySQL `BIT` type. We treat it as a `BOOLEAN` type, when in fact, it is a `BitSet` as you've shown (see https://github.com/jOOQ/jOOQ/issues/10323). This means that in order to bind it to something else, you need to use a data type binding in addition to the converter, which allows you to fix the behaviour in jOOQ and correctly read / write the `BIT` type:
https://www.jooq.org/doc/latest/manual/code-generation/custom-data-type-bindings/

I hope this helps
