### ISSUE TITLE
NULL clause on H2's columns should not be produced

### ISSUE THREAD

**Issue by katzyn** [jOOQ/jOOQ#10819]
The translate tool converts
```SQL
CREATE TABLE TEST(ID INT PRIMARY KEY, VAL INT);
```
from unspecified dialect to
```SQL
create table TEST (
  ID int null,
  VAL int null,
  primary key (ID)
)
```
for H2 dialect.

Non-standard `NULL` clause is deprecated in upcoming H2 2.0, because it doesn't have any meaning any more and it usually doesn't have any meaning in released versions of H2. There was a special case with `NOT NULL` domains, but such domains aren't accepted by current H2 at all. If you support them, there is a reason for `null` constraint here until H2 2.0 will be released for domain data types only, if you don't support such domains I don't see any good reasons.

Also `ID int null` with `primary key (ID)` seems to be wrong, but some DBMS, including the H2, don't care and assume `NOT NULL` anyway.

Some other targets are also affected, for example, `ID` with `null` is generated for Oracle and Sybase, but for SQL Server `ID` is generated with `not null` as expected.

**Comment by lukaseder** [comment]
Thanks for the pointer, @katzyn. jOOQ generates the `NULL` clause to be explicit about the default, because some RDBMS (e.g. Sybase) are `NOT NULL` by default (which is the more reasonable default, IMO), so as to standardise things across RDBMS, jOOQ picks the most popular behaviour.

Also, generating `NULL` everywhere makes things explicit, even if it's not necessary in most dialects. Likewise, not having a nullability clause for a `PRIMARY KEY` column may mean implicit `NOT NULL` in some dialects (whereas in others, its forbidden), so that's another reason to make it explicit. Personally, I've always liked to make it explicit, even if it's just for "code gardening reasons", e.g.

```sql
CREATE TABLE t (
  a INT NOT NULL,
  b INT     NULL
);
```

That's just a stylistic discussion, of course, but people like bike shedding.

Historically, there were fewer means to distinguish between dialect specific behaviour in these areas. For jOOQ 3.15, I'm adding more stuff like this (see e.g. #10811). It would make sense to add a setting defining whether the implicit `NULL` clause should be made explicit.

Having said so, if I can still influence this decision of yours, I would really not change that in H2. Yes, it's not necessarily a useful clause, but many clauses aren't. It's akin to disallowing the standard `RANGE` clause in window functions, such as `RANGE BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING` when it has no effect (e.g. in the absence of `ORDER BY`). Or, akin to marking methods `public` (or even `abstract`) in Java interfaces. What do you gain by no longer supporting it? What do your users lose? Especially in terms of backwards compatibility, which I know, is not your top priority. I think that changing this yields a less than favourable frustration/benefit ratio, especially to users who are not using jOOQ (which will generate the right SQL for them), but who are using H2 to test their PostgreSQL databases.

**Comment by lukaseder** [comment]
I'll implement this via #10937. I think that one of the main things that should  be addressed is to not modify the nullability of what is being parsed in https://www.jooq.org/translate, and to do that, we'll introduce a new setting that allows for specifying whether the current behaviour should be maintained, or the new behaviour should be assumed.

This isn't H2 specific. Once H2 drops support for an explicit `NULL` clause, we can change the behaviour of `DataType.nullable(true)` types to not generate the clause, but a lot more value can be achieved immediately by making things configurable and allowing the `Nullablity.DEFAULT` value to be maintained between parser and renderer.

I'll leave this issue open for later, should you come to the decision (which I still recommend you don't), to eventually drop support for the syntax.

**Comment by lukaseder** [comment]
Curiously, `Tools.NO_SUPPORT_NULL` already lists Derby, Firebird, and HSQLDB, which don't support the explicit `NULL` clause, so that's where we'd fix this issue here.
