### ISSUE TITLE
Stop using information_schema.table_constraints in PostgresDatabase

### ISSUE THREAD

**Issue by jaromor** [jOOQ/jOOQ#10824]
### Expected behavior

A Java class extending UpdatableRecordImpl<MyRecord> is generated

### Actual behavior

A Java class extending TableRecordImpl<MyRecord> is generated

### Steps to reproduce the problem

generator configuration:

```
generator() {
	database() {
		name('org.jooq.meta.postgres.PostgresDatabase')
		schemata() {
			schema() {
				inputSchema('fetch')
			}
		}
	}
	target() {
		packageName('net.company.project.db')
		directory("$projectDir/src/main/java")
	}
}
```

[the DDL is in the attachment](https://github.com/jOOQ/jOOQ/files/5465068/DDL.zip)

Verifying that the generator db-user "ro" can see the PK column:
![image](https://user-images.githubusercontent.com/40000923/97704849-6885cf00-1ab3-11eb-943b-a2c42b1479be.png)

### Versions

- jOOQ: 3.13.4
- Java: openjdk-14.0.2-1
- Database (include vendor): Postgres 11.7 (AWS RDS)
- OS: Ubuntu 18.04
- JDBC Driver (include name if inofficial driver): 42.2.6

**Comment by lukaseder** [comment]
Thanks a lot for your report and for the DDL example. I'll try to reproduce this and see why the constraint information isn't visible to this user.

**Comment by lukaseder** [comment]
For the record, the `information_schema` query to get primary key information looks something like this:

```sql
select
  information_schema.key_column_usage.table_catalog,
  information_schema.key_column_usage.table_schema,
  information_schema.key_column_usage.table_name,
  information_schema.key_column_usage.constraint_name,
  information_schema.key_column_usage.column_name,
  information_schema.key_column_usage.ordinal_position
from
  (information_schema.key_column_usage
left outer join information_schema.table_constraints as alias_99043051 on
  (information_schema.key_column_usage.constraint_catalog = alias_99043051.constraint_catalog
  and information_schema.key_column_usage.constraint_schema = alias_99043051.constraint_schema
  and information_schema.key_column_usage.constraint_name = alias_99043051.constraint_name))
where
  (alias_99043051.constraint_type = 'PRIMARY KEY'
  and alias_99043051.table_schema in ('fetch'))
order by
  information_schema.key_column_usage.table_schema asc,
  information_schema.key_column_usage.table_name asc,
  information_schema.key_column_usage.constraint_name asc,
  information_schema.key_column_usage.ordinal_position asc
```

**Comment by lukaseder** [comment]
So, in our integration tests, applying your grants leads to the following issues:

- Enums are not sorted correctly (see https://github.com/jOOQ/jOOQ/issues/10821)
- System indexes are no longer excluded (because we don't know the constraints, see this issue here)
- The constraints are missing. While the `key_column_usage` view can be queried, the `table_constraints` view cannot.
- Sequences are missing
- Some data types for table valued functions seem to be missing as well

The reason why `table_constraints` is empty is documented here:
https://github.com/postgres/postgres/blob/78c887679d7632c1211f85eb95723f3226bf1b46/src/backend/catalog/information_schema.sql#L1756-L1759

```sql
          AND (pg_has_role(r.relowner, 'USAGE')
               -- SELECT privilege omitted, per SQL standard
               OR has_table_privilege(r.oid, 'INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER')
               OR has_any_column_privilege(r.oid, 'INSERT, UPDATE, REFERENCES') )
```

That's insane! I didn't know that, but I can confirm the SQL standard (ISO/IEC AWI 9075-11) excludes constraints from being listed with `SELECT` grant only in `table_constraints`, but not in `key_column_usage`.

Well, we don't *have to* query `table_constraints`. We can query the underlying `pg_class` table as well - we already do on numerous occasions.

Will fix this for 3.15.0 and 3.14.2

**Comment by lukaseder** [comment]
In the meantime, the workaround would be to either (temporarily) add more grants to your `ro` user, or to use a different user for code generation, or to set up your database e.g. in testcontainers for code generation and use the `postgres` user there...

**Comment by lukaseder** [comment]
The `information_schema.referential_constraints` view also cannot be used, but we're already avoiding it because of #3520

**Comment by lukaseder** [comment]
Hah, the new queries also fix a bug in the CockroachDB code generation, where we generated too many columns per key, probably due to some cartesian product!

**Comment by lukaseder** [comment]
Fixed for jOOQ 3.15.0 and 3.14.2 (#10862).

Thanks again for your report!

**Comment by dsvensson** [comment]
Might this be the reason why I don't get any `Keys.java` any longer?

**Comment by lukaseder** [comment]
@dsvensson see https://github.com/jOOQ/jOOQ/issues/10902
