### ISSUE TITLE
Jooq records serialization

### ISSUE THREAD

**Issue by krzysztof-osiecki** [jOOQ/jOOQ#10838]
### Your question:

In version 3.14 method converterOrFail was introduced (comparing to 3.12.3) in class Tools, this method is called when attempting to get value from AbstractRecord. To get converter and then converted value the following line is used:

```java
Converter<T, U> result = configuration(configuration).converterProvider().provide(tType, uType);
```

where configuration object is taken from said record.
In the DefaultConfiguration implementation converterProvider object is transient, which means that if we hold Record in something that is serialized, and then deserialize it back, then methods that are trying to get value wont work, because converterProvider will be resolved to null.

My question is if this is an expected behavior, because we should not keep and serialize record objects or is it something that just slipped unnoticed and we can expect this to change?

### Versions:

- jOOQ: 3.14.0
- Java: 10
- Database (include vendor): Postgresql
- OS: CentOS
- JDBC Driver (include name if inofficial driver): 42.2.11

**Comment by krzysztof-osiecki** [comment]
Reading more into the code 
`        Converter<T, U> result = configuration(configuration).converterProvider().provide(tType, uType);

        if (result == null)
            result = CTX.configuration().converterProvider().provide(tType, uType);

        return result;`

It seems like there is some expectations of not finding Converter in configuration provider, with the following if, however method fails in the case i am describing with NPE in the first line.

**Comment by lukaseder** [comment]
Thank you very much for your message.

> In the DefaultConfiguration implementation converterProvider object is transient, which means that if we hold Record in something that is serialized, and then deserialize it back, then methods that are trying to get value wont work, because converterProvider will be resolved to null.

That's not how you should read it. The `transient` modifier is there to allow for non-serialisable `ConverterProvider` and `Converter` instances to be used without producing exceptions. Look at the magic `DefaultConfiguration::writeObject` and `DefaultConfiguration::readObject` methods to see how serialisation is being attempted.

However, the bug here is that `DefaultConverterProvider` should be `Serializable`: https://github.com/jOOQ/jOOQ/issues/10839

> My question is if this is an expected behavior, because we should not keep and serialize record objects or is it something that just slipped unnoticed and we can expect this to change?

You should never "keep" serialized record objects, see:
https://www.jooq.org/doc/latest/manual/sql-building/queryparts/serializability/

You can, however, serialize record objects between servers that use the same jOOQ version, e.g. using RMI or something similar. However, we might remove serializability in the (far away) future, as it is not the best way to transfer state over the wire. A better approach is to use a record's native XML/JSON formatting capability.

> It seems like there is some expectations of not finding Converter in configuration provider, with the following 'if', however method fails in the case i am describing with NPE in the first line.

The `Converter` may be `null` for any pair of types, but the `ConverterProvider` should not be `null`.

**Comment by lukaseder** [comment]
https://github.com/jOOQ/jOOQ/issues/10839 is fixed for 3.15.0 and 3.14.2. Thanks again for bringing this to our attention!

**Comment by krzysztof-osiecki** [comment]
@lukaseder out of pure curiosity i checked other providers in configuration object isn't the same (not being serializable) also true for DefaultCharsetProvider and DefaultUnwrapperProvider ?
Or is it already done in higher version than the one i'm looking at (3.14.0)?

**Comment by lukaseder** [comment]
> Same for the DefaultVersionProvider, DefaultMetaProvider, DefaultTransactionProvider and DefaultConnectionProvider, those however seem to me like it might be deliberate.

I know you'd notice these as well :)

You should see these flaws as a sign of:

1) It has always been brittle (all of Java serializability has always been)
2) There will be more issues
3) You'll probably find a better way to export/import your records
4) While we could fix each these things, no one has encountered them in many many years, meaning hardly anyone uses the feature, meaning, we should invest our time elsewhere, which is another good reason to remove the feature eventually

**Comment by krzysztof-osiecki** [comment]
Thx for all the responses :)
