### ISSUE TITLE
Unboxing may produce NPE warning in intellij when using count(*)

### ISSUE THREAD

**Issue by oshai** [jOOQ/jOOQ#10831]
### Expected behavior
No warning
### Actual behavior
Unboxing may produce NPE warning in intellij
### Steps to reproduce the problem
Code like in stackoverflow [question](https://stackoverflow.com/a/19676187/411965):
```
int count = 
DSL.using(configuration)
   .select(DSL.count())
   .from(Table)
   .fetchOne(0, int.class);
```
When the generated code has nullable annotations intellij yields the above warning.

The relevant gradle configuration is:
```
generate {
                generatedAnnotation = true
                nullableAnnotation = true
                nullableAnnotationType = 'javax.annotation.Nullable'
            }
```

### Versions
- nu.studer.jooq: 4.2
- jOOQ: 3.14

**Comment by lukaseder** [comment]
Thank you very much for your report.

In jOOQ 3.14, we've annotated most of our API with Jetbrains `@Nullable` and `@NotNull` annotations (https://github.com/jOOQ/jOOQ/issues/6244). All of these `fetchOne()` methods can produce:

- `NULL` records because they don't find any
- `NULL` values in a record

Yes indeed, in your case, it's impossible to get a `null` value, so this is probably a false positive, but it's hard to see how that could be prevented without removing all the annotations again. Also, just a slight modification of the query, and the value would indeed be nullable. As an alternative, in your particular case, you could just use `ctx.fetchCount(Table)`.

Adding these annotations to an existing API was a trade-off. There will be false positives. When working with Java, it is possible to turn off these warnings and introspections, as a workaround. Also, we're collecting these cases and assess on a case-by-case basis whether perhaps in this particular case, we'll revert to not annotating the API: https://github.com/jOOQ/jOOQ/issues/10832

I will leave this issue open to make a more informed decision based on more user feedback. Compared to another case (https://github.com/jOOQ/jOOQ/issues/10774), where the nullability was almost never applicable, in this case here, the non-nullability almost never applies, so I'm not sure yet if we should really handle this.

**Comment by oshai** [comment]
Thanks I understand the tradeoffs.
fetchCount sounds better in term of the api signature and I might have used it if not that warning: `Beware, though, that this renders a nested select like this:...`

**Comment by lukaseder** [comment]
@oshai It doesn't in your *particular* example :)

**Comment by oshai** [comment]
oh I see now, I missed that in the answer, so I will change.

**Comment by lukaseder** [comment]
I don't think this can be fixed for this particular example using `int.class`. Once Valhalla ships, I'm hoping `int.class` translates to `Class<int>` and the `fetchOne()` method thus produces a primitive, which IntelliJ knows about.

Until then, that's just a false positive we'll have to live with.
