### ISSUE TITLE
Group by chaining possibility

### ISSUE THREAD

**Issue by neonNS1** [jOOQ/jOOQ#10933]
### Problem
In many cases we want to select all fields from different entities. Of course we can manually make a collection of fields we need and send it to `select()` method, or we can use `vararg` version of `select()` method and write all needed fields right in call point, but this doesn't seems like the best solutions because we can just chain select() methods and get a beautiful code like this without excess collections or loooooong list of vararg arguments:
```java
.select(TABLE_A.fields())
.select(TABLE_B.fields())
```
So the problem appears when i want to add some aggregate function and  use group by on the same fields like this:
```java
.select(TABLE_A.fields())
.select(TABLE_B.fields())
.select(DSL.count(<some_field>))
.<some_other_query_statements>
.groupBy(TABLE_A.fields())
.groupBy(TABLE_B.fields()) // compile error
```
The point is `groupBy()` return `SelectHavingStep` implementation that just doesn't have another `groupBy()` method, so our beautiful chaining here is impossible and we need to create a collection to send it to `groupBy()`method. I can obviously re-use this collection in the select method, but it will be excess object, probably created somewhere outside our request builder, and this block of code will not be so good to read after that.

### Possible solution
The possible suggested solution is to return `SelectGroupByStep` from `groupBy()` method instead of `SelectHavingStep`. It will not brake anything because `SelectGroupByStep` is a direct extender of `SelectHavingStep` interface and adds only `groupBy()` methods, but It will allow us to do `groupBy()` chaining (as i understand, the only implementation of this method in `SelectImpl` already allow this feature because its just adds new fields to list of group by statements)

### Actual versions:
- jOOQ: 3.13.4

**Comment by lukaseder** [comment]
Thanks for your suggestion.

I personally regret having allowed consecutive calls to `select()`. The use-case there is more popular because it happens more often to dynamically add several seemingly independent sets of columns. You have a use-case where it seems reasonable to do the same thing with `groupBy()`, but that's very rare. And then, someone will want to have the same for `having()`, `orderBy()`, and all the others. And then, someone will want to have these things on DML statements, like `UPDATE`, or on window function specifications, to add several sets of columns to a `PARTITION BY` clause, and it never ends.

When, in fact, you could just use e.g. `Stream` or jOOλ to quickly concatenate two sets, such as:

```java
.select(Seq.of(TABLE_A.fields()).concat(TABLE_B.fields()).concat(count()).toList())
.<some_other_query_statements>
.groupBy(Seq.of(TABLE_A.fields()).concat(TABLE_B.fields()))
```

Again, I really regret having done this for `select()` (might even be a deprecation candidate in the future), and I highly recommend using collection APIs outside of jOOQ to create such dynamic lists of things.
