### ISSUE TITLE
jOOQ/Java output dialect for /translate

### ISSUE THREAD

**Issue by axelfontaine** [jOOQ/jOOQ#10961]
### Use case:

For certain more complicated queries, it isn't always obvious how to translate them from SQL to Java code using jOOQ.

### Possible solution you'd like to see:

`https://www.jooq.org/translate/` could offer `jOOQ/Java` as a new output dialect that would produces jOOQ code corresponding to the input sql.

### Possible workarounds:

StackOverflow, Google, JavaDoc and jOOQ manual search.

**Comment by lukaseder** [comment]
Thanks for your suggestion. See: https://github.com/jOOQ/jOOQ/issues/6277

**Comment by lukaseder** [comment]
However, prior to implementing #6277, perhaps there's a lower hanging fruit. An advanced tutorial to help translate complex queries? Did you have any specific things in mind?

**Comment by axelfontaine** [comment]
Here is one I am currently struggling with for example:

```
SELECT id,
       synthetic,
       activity,
       start_timezone_offset,
       finish_utc      as gap_start_time,
       next_start_time as gap_end_time,
       finish          as gap_start,
       next_start      as gap_end
FROM (
         SELECT *,
                lead(start_utc) OVER (PARTITION BY trip_id ORDER BY start_utc) as next_start_time,
                lead(start) OVER (PARTITION BY trip_id ORDER BY start_utc)     as next_start
         FROM track
         ORDER BY start_utc
     ) s
WHERE finish_utc < next_start_time
  and trip_id = 1
```

The table alias with the nested select always trips me up.

**Comment by lukaseder** [comment]
Thanks for sharing that example. I was sure it was either about CTEs or derived tables, the two things that seem tricky to get right with jOOQ.

I take the blame here as, again, this is mostly a documentation problem. Most queries can be translated 1:1, but not CTE or derived tables, because your `Table` s might need to be declared up front, not embedded in your outer query. (If we already supported the `QUALIFY` emulation, then you wouldn't need a derived table: https://github.com/jOOQ/jOOQ/issues/5810).

Before I document this, here's a head start for you:

- Declare `s` up front, using `table(select(...).form(...).orderBy(...)).as("s")`
- Dereference `TRACK` columns using `s.field(TRACK.ID)`, for example.
- Dereference all the other columns using their names, e.g. `s.field("next_start_time")`

> I am happy to take the blame as I mostly think and experiment in SQL and not in jOOQ/Java

To me, this hints at:

1) Your query being static
2) And thus a good candidate for a view

Why not just write a view and query that with jOOQ?

> but still I think there is real value in being able to auto-convert queries that were developed and tested ad-hoc in a DB tool directly into pasteable Java (or Kotlin) code.

No one argues against this. But it's such a big project, I'd like to do everything possible to fix the low hanging fruit first, which is documentation.

The attempt that was taken with the third party sql2jooq library was so sobering (*zero* feedback. And *zero* complaints when I removed it), that I have to say, this won't be a priority.
