### ISSUE TITLE
Feedback about manual section date-function

### ISSUE THREAD

**Issue by theBoxi** [jOOQ/jOOQ#10976]
Im not able to extract a Date (without time) from a OffsetDateTime to do some calculations in my query:

```
dsl.selectFrom(CARD_STATUS)
            .where(CARD_STATUS.USER_ID.eq(user.id.id))
            .and(DSL.date(CARD_STATUS.LAST_LEARNED).add(CARD_STATUS.NEXTIN_DAYS).lessOrEqual(DSL.currentDate()))
            .fetch(this::mapRecord)
            .toSet()
```

where LAST_LEARND is a TIMESTAMP WITH TIME ZONE

compiler message:
```
None of the following functions can be called with the arguments supplied: 
public open fun date(p0: java.util.Date!): Field<java.sql.Date!> defined in org.jooq.impl.DSL
public open fun date(p0: String!): Field<java.sql.Date!> defined in org.jooq.impl.DSL
public open fun date(p0: Field<out java.util.Date!>!): Field<java.sql.Date!> defined in org.jooq.impl.DSL
```

in sql (Postgres) this is posible by 
```
select * from card_status where user_id = '?' and date(last_learned + interval '?' day) <= currentDate;
```

is there an other method to do that, or is this missing?

**Comment by lukaseder** [comment]
Thanks for your message.

The method would be `DSL.localDate()`, but it expects a `Field<LocalDate>` rather than a `Field<? extends Temporal>`. We'll fix that: https://github.com/jOOQ/jOOQ/issues/10977

If I'm not mistaken, you can just use `CARD_STATUS.LAST_LEARNED.cast(SQLDataType.LOCALDATE)` instead, or `DSL.trunc(CARD_STATUS.LAST_LEARNED, DatePart.DAY)` (which corresponds to PostgreSQL `date_trunc`)

Or, of course, plain SQL templating as always when something in jOOQ is missing or not working:
https://www.jooq.org/doc/latest/manual/sql-building/plain-sql-templating/

I hope this helps
