### ISSUE TITLE
Public API to traverse a Query's AST

### ISSUE THREAD

**Issue by lalithsuresh** [jOOQ/jOOQ#10994]
### Use case:

Hi @lukaseder,

Apologies for the lengthy backstory on this one, but perhaps it'll be easier for you to help if you had the complete picture. :)

I have a use case where I'm making an incremental engine appear like an SQL database. 

I'm using JOOQ's `MockDataProvider` API to intercept SQL queries (selects, inserts, deletes and updates), validate the queries, and redirect them to the incremental engine using its APIs. You can see the work in progress here:  https://github.com/vmware/differential-datalog/blob/master/sql/src/main/java/com/vmware/ddlog/DDlogJooqProvider.java

My problem: once I receive an SQL query via `MockDataProvider.execute()`, I need to parse the SQL strings and "visit" the different nodes of the AST to construct the inputs to the incremental engine. I've been using Presto's Parser API thus far, but unfortunately, it's a strange dialect of SQL, and I just realized they don't support `UPDATE` statements. I'm therefore looking for a way to achieve this (preferably) using JOOQ's APIs.

I was hoping to do something like this:

```
final Queries parse = dslContext.parser().parse(ctx.sql());
// somehow traverse the tree represented by "Queries"
```

It seems like there isn't a public visitor API in JOOQ, but I do see the `VisitListener` API. Unfortunately, the documentation has examples of what kind of SQL transformations one can do with the `VisitListener` API, but no code examples on how to use it (https://www.jooq.org/javadoc/latest/org.jooq/org/jooq/VisitListener.html). 

I also see some mention of setting up the `VisitListener` via the DSLContext's configuration, but it's still not clear to me how I should pass an instance of a `VisitListener` to a configuration: https://stackoverflow.com/questions/53696181/get-table-column-metadata-from-jooq-parser-result

Any pointers? Thanks a bunch!

### Possible solution you'd like to see:

Improve the `VisitListener` API documentation with more examples.

Pointers and guidelines on how to parse and traverse an SQL AST using JOOQ.

### Possible workarounds:

Like before, go out of JOOQ again to parse and walk the SQL query (and try something like JSQLParser instead of Presto).

### Versions:

- jOOQ: 3.13.1
- Java: 12.0.1
- Database (include vendor): NA
- OS: NA
- JDBC Driver (include name if inofficial driver): NA

**Comment by lukaseder** [comment]
Thank you very much for your message.

jOOQ's parser was created with this kind of use-case in mind for the long run. For the short run (current implementation since jOOQ 3.9 - 3.14), it mainly serves jOOQ internally for a variety of use-cases, mostly to be able to parse DDL statements, e.g. for the `DDLDatabase` (https://www.jooq.org/doc/latest/manual/code-generation/codegen-ddl), but also for other reasons.

We are thinking about re-designing our expression tree model to allow for it to be publicly accessible. This is a big project, which we will definitely tackle, but given that public API will live forever, we need to get it right.

The project is being tracked here:
https://github.com/jOOQ/jOOQ/projects/2

You can get quite far with the `VisitListener`, but we don't want to put much effort into documenting it further, because you don't get access to the currently internal expression tree model anyway. Perhaps it will be good enough, nonetheless? There's an example of how you could achieve implementing client side row-level security using a `VisitListener` here:
https://blog.jooq.org/2015/06/17/implementing-client-side-row-level-security-with-jooq

I hope this helps
