### ISSUE TITLE
one to many left join, hot to remove null values child with elegant code

### ISSUE THREAD

**Issue by SimpleIto** [jOOQ/jOOQ#10996]
#### select org list with users
```java
// Org, User are generated pojo class
class OrgWithUsers extends Org{
  private List<User> users;
}

// use:
var record =  create.select()
    .from(ORG)
      .leftJoin(USER).on(USER.ORG_ID.eq(ORG.ID))
    .fetchGroups(ORG);

return record.entrySet().stream().map((e) -> {
     var org = e.getKey().into(OrgWithUsers.class);
     org.setUsers(e.getValue().into(User.class));
     return org;
}).collect(Collectors.toList());
```
#### jooq query print log:
id(org)|name|id(user)|name|...
-|-|-|-|-
3|OZ|{null}|{null}|{null}|...
#### result: 
```
{
  "id": 3,
  "name": "OZ",
  "users": [
    {
      "id": null,
      "name": null,
      ...
    }
}]
```

### expected result:
```
[{
  id: 3,
  "name": "OZ",
  "users": null
}]
```
i'm not sure it's a usage problem or Result#into feature or something else
is there some way except foreach result and judgment record like`record.get(USER.ID) != null` ?
ask for help, Thanks

### Versions:
- jOOQ: 3.14.3
- Java: 11
- Database (include vendor): mysql
- JDBC Driver (include name if inofficial driver): mysql-connector-java:8.0.22

**Comment by lukaseder** [comment]
Thank you very much for your request.

To achieve what you want in your specific case, just add a filter to your `org.setUsers()` call, filtering by primary key, and you're set:

```java
org.setUsers(e.getValue().into(User.class).stream().filter(u -> u.getId() != null).collect(toList()));
```

Note, however: a left join does not nest a collection, it denormalises it. If you have more than one join, or a tree structure (one parent with two children), then you will get a lot of duplication, and even cartesian products, which you cannot resolve this way anymore.

Much better, do it with SQL directly, because that way, you can nest to arbitrary levels, and even trees. For example:

```java
JSON result =
ctx.select(jsonArrayAgg(jsonObject(
       key("id").value(ORG.ID),
       key("name").value(ORG.NAME),
       key("users").value(
         select(jsonArrayAgg(jsonObject(
           key("id").value(USER.ID),
           key("name").value(USER.NAME)
         )))
         .from(USER)
         .where(USER.ORG_ID.eq(ORG.ID))
       )
     ))
     .from(ORG)
     .fetchSingle()
     .value1();
```

Since you seem to want to get JSON as a result format, this works out of the box. If you want your `OrgWithUsers` class as a result, you can still use gson or Jackson to map the JSON format back to your POJO structure. This also works out of the box if you:

- Have gson or Jackson on your classpath
- Call `fetchSingleInto(OrgWithUsers.class)` on your JSON structure

If you're licensed, then the SQL Server style `FOR JSON` syntax might be able to make this even easier for you, for certain cases:
https://www.jooq.org/doc/latest/manual/sql-building/sql-statements/select-statement/for-clause/

For more information, see this article here:
https://blog.jooq.org/2020/10/09/nesting-collections-with-jooq-3-14s-sql-xml-or-sql-json-support/

**Comment by SaiUttej100** [comment]
Then how to set an empty array "[ ]" instead of "null"

> Thank you very much for your request.
> 
> To achieve what you want in your specific case, just add a filter to your `org.setUsers()` call, filtering by primary key, and you're set:
> 
> ```java
> org.setUsers(e.getValue().into(User.class).stream().filter(u -> u.getId() != null).collect(toList()));
> ```
> 
> Note, however: a left join does not nest a collection, it denormalises it. If you have more than one join, or a tree structure (one parent with two children), then you will get a lot of duplication, and even cartesian products, which you cannot resolve this way anymore.
> 
> Much better, do it with SQL directly, because that way, you can nest to arbitrary levels, and even trees. For example:
> 
> ```java
> JSON result =
> ctx.select(jsonArrayAgg(jsonObject(
>        key("id").value(ORG.ID),
>        key("name").value(ORG.NAME),
>        key("users").value(
>          select(jsonArrayAgg(jsonObject(
>            key("id").value(USER.ID),
>            key("name").value(USER.NAME)
>          )))
>          .from(USER)
>          .where(USER.ORG_ID.eq(ORG.ID))
>        )
>      ))
>      .from(ORG)
>      .fetchSingle()
>      .value1();
> ```
> 
> Since you seem to want to get JSON as a result format, this works out of the box. If you want your `OrgWithUsers` class as a result, you can still use gson or Jackson to map the JSON format back to your POJO structure. This also works out of the box if you:
> 
> * Have gson or Jackson on your classpath
> * Call `fetchSingleInto(OrgWithUsers.class)` on your JSON structure
> 
> If you're licensed, then the SQL Server style `FOR JSON` syntax might be able to make this even easier for you, for certain cases: https://www.jooq.org/doc/latest/manual/sql-building/sql-statements/select-statement/for-clause/
> 
> For more information, see this article here: https://blog.jooq.org/2020/10/09/nesting-collections-with-jooq-3-14s-sql-xml-or-sql-json-support/

**Comment by lukaseder** [comment]
You can use `coalesce(nullableExpression, jsonArray())`. See also discussion here about nullability of aggregate functions in SQL: https://github.com/jOOQ/jOOQ/issues/11994
