### ISSUE TITLE
No-op for seek

### ISSUE THREAD

**Issue by will421** [jOOQ/jOOQ#11007]
Hi,
I'm a recent user of JOOQ.

I try to create a request that use SEEK in a while loop.
Is there a way to no-op seek for the first iteration (as I don't have values for seek yet) ?

Thanks

**Comment by lukaseder** [comment]
Thanks for your message. There are numerous API elements that could profit from "no op" arguments, the way we support `DSL.noCondition()`, for example. With `Condition` things are much simpler because a "no op" usually has the same sematics as `TRUE`. With other types, such as `Field` things seem a bit more difficult. See also this discussion here:
https://github.com/jOOQ/jOOQ/issues/9635

If you're using Kotlin, then you can use `apply`: https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/apply.html, a thorough, language wide approach to adding no-op capable API interactions to the entire language.

In Java, you can do the same with a static method, but it will not be as elegant of course. If your `SEEK` clause operates on numbers, you can use the relevant type's `MIN_VALUE` as a "no op" value.

Or, you can assign the `SelectSeekStep[N]` type to a local variable and operate on that.

I hope this helps.
