### ISSUE TITLE
Type-safe plain SQL queries

### ISSUE THREAD

**Issue by axelfontaine** [jOOQ/jOOQ#11049]
This is a follow up to #10961 and #8192 inspired by [SQLDelight](https://cashapp.github.io/sqldelight/).

In order to avoid the issue presented in #10961 (tedious search for the correct SQL to jOOQ translation), I would like to propose to leverage the existing pieces of jOOQ to achive a SQLDelight-like feature set.

Starting from a file with named queries with optional placeholders (like SQLDelight's `.sq` files), the jOOQ generator could leverage the jOOQ parser to validate these queries against jOOQ meta and use jOOQ forcedTypes to produce a Java/Kotlin/Scala interface to call these queries. This will no doubt have a lot of similarities with jOOQ's support for stored procedures and Oracle packages.

This would yield the following picture:
`[.sq file] -> (parsing & validation against jOOQ meta) -> (code gen using forcedTypes) -> [Java/Kotlin/Scala interfaces]`
effectively combining all of jOOQ's type-safety goodness with plain SQL (and all the tooling support that is available for that like completion with IntelliJ, ...).

This in turn could open the door for splitting out the query building from jOOQ main distribution. It could then be used standalone (for users who just want to render SQL), or together with the existing runtime infrastructure like today. This in turn would help with addressing part of the concerns for #8192.

**Comment by lukaseder** [comment]
Thanks Axel.

This has been discussed a few times in the past, and we have a set of issues preparing for something like that in the private issue tracker.

There are numerous interesting applications of offering parsed, static SQL based APIs, including type safe DAO and DTO types and methods from static queries. In fact, we already offer this to some extent to Scala developers in the form of macros (I don't think anyone is using it, it was never really advertised either).

While technically, this can be achieved with relatively moderate efforts, it will turn jOOQ into an entirely different product, or even two products. Helping users understand when to use which approach might turn into a problem, as can be seen with numerous competing products that offer 4-5 different approaches to do the same thing. This is already the case with the existing DAOs and I fear it will get worse if we add this feature.

**At the same time, you can already do *everything* you're suggesting here by just using views and table valued functions!**

I.e. just make some very minor adaptations to your workflow and boom:

` [ .sql file ] -> (database parses and validates it against its own meta data) -> (code gen using forcedTypes) -> [Java/Kotlin/Scala interfaces]`

I'm closing this particular issue because it is not really actionable on its own. jOOQ will offer something like this in the future, the idea is compelling, but it is a lot of work in terms of product design, and you can already achieve it by using views and table valued functions.

**Comment by lukaseder** [comment]
What this all boils down to is to support "virtual views", i.e. views that are not stored in the database catalog, but known only to jOOQ. Perhaps, without getting distracted by what SQLDelight did, and without questioning jOOQ's approach and paradigm to writing dynamic SQL via a internal SQL DSL, we could offer virtual views in a way that makes them available at code generation time and at runtime...

I'll think about this a bit more.

**Comment by lukaseder** [comment]
I like the sound of synthetic views: https://github.com/jOOQ/jOOQ/issues/11054. Those can be useful independent of their application (this issue here being one future possibility)

**Comment by lukaseder** [comment]
Well, this synthetic views and synthetic table valued functions feature is coming along really nicely (#11054). This will be the low level infrastructure for a feature like the one you're suggesting here, which will offer just one more step on top of #11054: To be able to map some input SQL to some generated DAO API (and POJOs for the result).

**Comment by lukaseder** [comment]
I'm formalising this idea as its own issue, which I will be updating: #11071

**Comment by lukaseder** [comment]
What have you done, @axelfontaine 😁

This idea sent me off to some epic ["Hal fixing a lightbulb"](https://www.youtube.com/watch?v=AbSehcT19u0) journey, including the need for propagating nullability throughout the API so generated Kotlin DAOs can leverage this information for their parameters (https://github.com/jOOQ/jOOQ/issues/11070) as well as properly propagating other type information throughout the API (https://github.com/jOOQ/jOOQ/issues/11061), and all the various parser improvements that are prerequisite to this!

Joking aside, this is a great driver for a *much* improved parser and DSL in general...

**Comment by axelfontaine** [comment]
@lukaseder I am very glad this little spark lit such a bonfire of small but very valuable improvements 😀

**Comment by lukaseder** [comment]
> small

😂😶

I feel like I'm about to rewrite all of jOOQ's internals...
