### ISSUE TITLE
batchUpdate performs slower 

### ISSUE THREAD

**Issue by pavan2017** [jOOQ/jOOQ#11068]
I am using jooq 3.14.4 version and this is in continuation to https://stackoverflow.com/questions/62870572/how-to-batch-update-using-jooq/62879490
I tried updating records using UpdatableRecord and Bind Variables. method using bind variables performs much better .
Example for BatchUpdate is 

```
`ctx.batchUpdate(balances
   .stream()
   .map(b -> { 
       var r = new BalanceRecord();
       r.setAmount(b.getAmount());
       r.setId(b.getId());
       r.changed(BALANCE.ID, false); 
       return r;
   })
   .collect(toList()))
   .execute();`
```

Example for Bind Variables
```
`var balanceUpdate = dslContext.batch(
                dslContext.update(BALANCE)
                .set(BALANCE.BALANCE, (BigDecimal) null)            
                .where(BALANCE.ID.eq((String) null)));
        balances.forEach(balance -> {
            balanceUpdate.bind(
                    balance.getAmount()
                    balance.Id);
        });
        int[] execute = balanceUpdate.execute();`
```

I faced same issue with batchInsert as well but that is reported here https://github.com/jOOQ/jOOQ/issues/4533. I tried loader API mentioned in the thread but loader api doesnt work well for me. i refactored code using batchInsert to batch using bind variables and it works very good.

**Comment by lukaseder** [comment]
Thanks a lot for your report, and for documenting this here. I think that any performance issue you've encountered with the `batchUpdate(UpdatableRecord...)` API is the same as https://github.com/jOOQ/jOOQ/issues/4533, as you've mentioned. The underlying logic is the same.

On your stack overflow question, I was not sure if this was about jOOQ's SQL generation or some lag with the server that might have been produced otherwise.

I'll look into https://github.com/jOOQ/jOOQ/issues/4533 now - it should have been fixed a long time ago! Will close this as a duplicate of https://github.com/jOOQ/jOOQ/issues/4533
