### ISSUE TITLE
The generation strategy of foreign key method names in table class

### ISSUE THREAD

**Issue by ooknight** [jOOQ/jOOQ#11113]
The name of the foreign key method in the table class is always the table name
For example:
```sql
CREATE TABLE t_role (
    id   BIGINT  NOT NULL PRIMARY KEY,
    name VARCHAR NOT NULL
);

CREATE TABLE t_user (
    id      BIGINT  NOT NULL PRIMARY KEY,
    name    VARCHAR NOT NULL,
    role_id BIGINT  NOT NULL REFERENCES t_role
);
``` 
```java
public Role tRole() {
    return new Role(this, Keys.USER_FK_ROLE);
}
```
Hope to generate a method named **"role()",** not **"tRole()"**.
Can it be generated according to the tables or fields strategy, or add a strategy to it separately

**Comment by lukaseder** [comment]
Thank you very much for your message.

The default behaviour of the `DefaultGeneratorStrategy` is to name this method

- after the parent table if there is only one outbound foreign key from child table to parent table
- after the foreign key name, otherwise

You can override this behaviour using a programmatic generator strategy, by overriding the `GeneratorStrategy::getJavaMethodName` for `ForeignKeyDefinition`:
https://www.jooq.org/doc/latest/manual/code-generation/codegen-generatorstrategy/

A configurative approach using matcher strategies is on the roadmap: https://github.com/jOOQ/jOOQ/issues/7150

Hope this helps.
