### ISSUE TITLE
feat(dsl): provide a DSL.value(v, converter) method to simplify usage of custom converter with state

### ISSUE THREAD

**Issue by davinkevin** [jOOQ/jOOQ#11146]
### Use case:

I have to implement a converter, but this converter requires a state (a cypher/decypher key). If I configure JOOQ generator to use this converter, it works but I have to initialize the key through `static` method. 

In jooq, a record field has the method `Record#get(Field<T> field, Converter<? super T, ? extends U> converter)` but the equivalent doesn't exist on the `DSL.value`. 

So, if I want to convert a value for usage in JOOQ DSL, I have to use the `to` method from the converter like this: 

```
val v = DSL.value(emailConverter.to(email))
```

So, there is no parity between `DSL#value` and `Record#get` to use a converter. 

### Possible solution you'd like to see:

Having access to a method `DSL.value(T v, Converter<T, U> c)` could be a good solution to provide idiomatic solution for both cases.

### Possible workarounds:

I use the converter "as-is", but I mix up the `to` and the `from` method. 

Another solution would be to use the comment posted here: https://stackoverflow.com/a/36388734

But this require to create a specific type, and we still need to use the converter on the Record so this just change the problem, doesn't seem to fix it. 

### Versions:

- jOOQ: 3.14 and others…
- Java: 11 and others…
- Database (include vendor): PG 9-12
- OS: MacOS 
- JDBC Driver (include name if inofficial driver): Official one…

**Comment by lukaseder** [comment]
Thank you very much for your request.

What are you trying to do? Can you show a more complete example of where you'd like to wrap your value in a `Param`?

**Comment by davinkevin** [comment]
Sorry, I should have provide a better example. Here it is: 

```kotlin
val secret = "secret"
val myConverter = ComplexConverter(secret)

val convertedValue = myConverter.to(x)
val results = query.select(TABLE.FIELD1, TABLE.FIELD2, TABLE.FIELD3)
         .from(TABLE)
         .where(TABLE.FIELD3.gt(x))
         .fetch( MyObject(it[TABLE.FIELD1], it[TABLE.FIELD2], it.get(TABLE.FIELD3, myConverter)))
```

And what I wish I could do is: 

```kotlin
val secret = "secret"
val myConverter = ComplexConverter(secret)

val results = query.select(TABLE.FIELD1, TABLE.FIELD2, TABLE.FIELD3)
         .from(TABLE)
         .where(TABLE.FIELD3.gt(DSL.value(x, myConverter)))
         .fetch( MyObject(it[TABLE.FIELD1], it[TABLE.FIELD2], it.get(TABLE.FIELD3, myConverter)))
```

**Comment by lukaseder** [comment]
But why is the converter not attached to your field, using code generation?

The `Record.get(Field, Converter)` method is very old and predates a lot of data type conversion features, including the `Binding` type, for example. The approach chosen at the time doesn't scale. We can't possibly have a consistent API when overloading everything with a `Converter` for convenience. The `Record.get(Field, Class)` overload is kinda OK, because there are good use-cases for quick and dirty conversions e.g. from `int` to `String`, or whatever. But once you have a `Converter<T, U>` you probably want a `DataType<U>` anyway, and a `Field<U>`, so using the `Converter` directly in jOOQ API is unlikely...

Unless I'm missing a use-case here?

**Comment by davinkevin** [comment]
Because the converter can't be initialized by itsefl with empty parameter constructor. In my case, I have to provide my `cypher key` to be able to use it. 

What do you propose for this case of converter usage ?

I didn't find any solution to use the `DataType<X>` in the `Record#get` method too… maybe I've missed it.

**Comment by lukaseder** [comment]
A quick solution for this would be to create an alternative field reference for this:

```java
val field3 = field(TABLE.FIELD3.getQualifiedName(), TABLE.FIELD3.getDataType().asConvertedDataType(myConverter));
```

Now, use that instead of the original field:

```kotlin
query.select(TABLE.FIELD1, TABLE.FIELD2, field3)
         .from(TABLE)
         .where(field3.gt(x))
         .fetch( MyObject(it[TABLE.FIELD1], it[TABLE.FIELD2], it[field3]))
```

That's what I meant: It's almost always better to attach a converter to a `Field<?>` and use it indirectly via that field, rather than having to remember all the time that a `Field<T>` should really be a `Field<U>`.

The idea of being able to inject stuff into the converter isn't new. It should be possible, yes. See also: https://github.com/jOOQ/jOOQ/issues/5266. As a workaround, you could pass around your secret in `ThreadLocal` variables. Not nice, but does the job for an edge case.

I really don't think we should put the `Converter` type onto more API. This isn't just about `DSL.value()` (in case of which it really doesn't add a lot of ... value). We'd have to attach it to *a lot* of other API, too. Mostly for cases like yours where there's a *much* better solution, namely to attach it to a globally available `Field`.

Again, with the addition of the `Binding` type, `Converter` lost much of its usefulness, because in many of these cases, the big question is how to bind a custom type to the SQL string and JDBC API, and converter can't do that.

I'm closing this as won't fix. There are workarounds, and the thing that you *really* need is to be able to inject your secret into the converter somehow. This should be addressed eventually, via #5266

**Comment by davinkevin** [comment]
I understand the main purpose of your answer. I will try the proposed solution even if I'm not a huge fan of it, because it is not very IoC friendly. In our case, we are using Spring/Guice/Dagger/OtherIoC lib to inject our converter into our repository… which is straightforward. 

The solution using ThreadLocal isn't a solution in our case, we are using reactor, so we don't even know in which thread the code will be executed. 

Thank you for your time and answers 👍

**Comment by lukaseder** [comment]
> I will try the proposed solution even if I'm not a huge fan of it, because it is not very IoC friendly. In our case, we are using Spring/Guice/Dagger/OtherIoC lib to inject our converter into our repository… which is straightforward.

Sure, so to extend to my suggestion, why don't you inject a container of converted columns into your repository as well?

```java
class AllConvertedColumns<T, U> {
  final Field<U> field3;
  // ... more here
  AllConvertedColumns(Converter<T, U> myConverter) {
    field3 = field(TABLE.FIELD3.getQualifiedName(), TABLE.FIELD3.getDataType().asConvertedDataType(myConverter));
    // ... more here
  }
}
```

Again, I'm suggesting workarounds, which are (IMO) quite viable for the time being, until there's an OOTB solution for #5266.

I've closed this issue because it is about a suggested API change (`DSL.value(v, converter)`), which has nothing to do with your *actual* problem. I'm quite sure you do *not* want to remember having to pass around this converter instance *everywhere* in *every query* and on *every predicate* and projection and function call, etc. etc. etc., where `FIELD3` is involved, even if it appears to be quite a low hanging fruit to you right now. Better attach it to `FIELD3` once and for all.

I do recognise that your *actual* problem, namely to make generated code more DI friendly, should be addressed. It will be, with #5266
