### ISSUE TITLE
FILTER or OVER clause does not work on JSON_ARRAYAGG() or JSON_OBJECTAGG() functions in H2, MySQL, and PostgreSQL style dialects

### ISSUE THREAD

**Issue by billonalex** [jOOQ/jOOQ#11238]
### Expected behavior

I would like to use a filterWhere() method on a DSL.jsonbArrayAgg() method.

```java
DSL.field(DSL.jsonbArrayAgg(_activites.field("json")).filterWhere(_activites.field("est_principal")).isTrue()).as("principal")
```

should return

```sql
jsonb_agg(_activites.json) filter (
	where _activites.est_principal is true
)
```

### Actual behavior

The code compiles and runs just fine, but the output SQL is missing the FILTER part.

```java
DSL.field(DSL.jsonbArrayAgg(_activites.field("json")).filterWhere(_activites.field("est_principal")).isTrue()).as("principal")
``` 

returns

```sql
jsonb_agg(_activites.json)
``` 

### Versions

- jOOQ: 3.14.3
- Java: 11
- Database (include vendor): PostgreSQL 12
- OS: Ubuntu 20.04.1 LTS
- JDBC Driver (include name if inofficial driver):

**Comment by lukaseder** [comment]
Thanks a lot for your report. I'll look into this soon.

**Comment by lukaseder** [comment]
Thanks, @baev. What you were looking for is this:
https://github.com/jOOQ/jOOQ/issues/1729

The workaround is to use plain SQL templating, as always:
https://www.jooq.org/doc/latest/manual/sql-building/plain-sql-templating

You shouldn't rely on undocumented internals. They can break at any time, including with the next patch release upgrade. Specifically, the fact that `DSL.function()` managed to somehow generate all those `AggregateFunction` semantics in the past was not well designed. Any arbitrary change to those internals could have broken your assumptions. Better get in touch for feature requests :)

I'll see that #1729 gets higher priority.

**Comment by lukaseder** [comment]
Looking into this now.

If I remember correctly, I believe the difficulty here was in the fact that `FILTER` cannot be emulated easily in `JSON_ARRAYAGG()` with the usual approach of turning things into `NULL`, because removing `NULL` may conflict with the `NULL ON NULL` semantics (e.g. in Oracle).

This shouldn't prevent `FILTER` from being supported natively in PostgreSQL, of course.

The `@Support` annotation on `filterWhere()` is wrong for these cases, which are more difficult to document / annotate, but I guess we'll live with that.

**Comment by lukaseder** [comment]
Related issue: Parsing these clauses: https://github.com/jOOQ/jOOQ/issues/11474

**Comment by lukaseder** [comment]
This issue will also fix the lack of support for `OVER` in `JSON_ARRAYAGG()` and the lack of support for `FILTER` in `JSON_OBJECTAGG()` (which supports `OVER`)

**Comment by baev** [comment]
the another point was that using `.filterWhere` compiles and run without any notice even it's not supported. I kinda expect JOOQ to fail in runtime when unsupported statement is called

**Comment by lukaseder** [comment]
> the another point was that using `.filterWhere` compiles and run without any notice even it's not supported. I kinda expect JOOQ to fail in runtime when unsupported statement is called

This is a common request, and while I perfectly understand it (it might have saved you some time), the question is, should we spend the time collecting all the missing features and throwing meaningful errors, or should we just fix the bugs or implement the features instead, assuming that both tasks generate a similar amount of effort? :)

Notice that

1. We already offer compile time safety for a lot of API via this checker framework or ErrorProne: https://www.jooq.org/doc/latest/manual/tools/checker-framework. Not everything can be covered by this, e.g. `filterWhere()` is a generic method for all `AggregateFunction` and it may be possible that it can't be supported on some. Solving this as a compile time fix would require duplicating a ton of API, i.e. have every aggregate function declare its own syntax. The tradeoff here is definitely in favour of the mostly correct API. But it does work for a lot of other API.
2. In many cases, when you call a method that doesn't actually work in some dialect, we'll generate wrong SQL (e.g. this `FILTER` clause is not supported in Oracle). That will produce an error in the database.
3. Sometimes, there's a bug and we generate syntactically correct but semantically incorrect SQL. In that case, let's just fix the bug instead of documenting it.

I'm aware, from our previous discussions on Twitter, that you don't care about other dialects than PostgreSQL. A PostgreSQL only library would be helpful for you, it would:

1. Prevent needing to use compile time plugins as the checker framework, and give you dialect type safety already in your IDE autocompletion
2. You wouldn't run into case 2)
3. Case 3) (e.g. this issue here) could still happen

We will offer that at some point in the future, by stripping all parts of the API from your distribution, which you don't need. That way, you'd have a `jooq-postgres` library, which only contains the PostgreSQL dialect, or at least only the PostgreSQL compatible API. I think there's an issue for that, but I cannot seem to find it.

**Comment by lukaseder** [comment]
Fixed in jOOQ 3.15.0 and 3.14.8 (#11479).

**Comment by lukaseder** [comment]
I will release 3.14.8 early next week, including this fix

**Comment by lukaseder** [comment]
Will fix this also in other dialects, where possible. E.g. in H2, it can also be supported natively. In MySQL and MariaDB, the `GROUP_CONCAT` emulation needs to be used to emulate `FILTER` as it cannot be emulated with the native JSON aggregate functions, which include nulls in these dialects.

**Comment by lukaseder** [comment]
A Db2 emulation can also be implemented through the same `GROUP_CONCAT` (or `LISTAGG`, respectively) mechanisms, as Db2 doesn't support the aggregate functions.

In Oracle, it's a bit more tricky. We're supporting the functions natively, but `FILTER` emulations would depend on `ABSENT ON NULL`. If `NULL ON NULL` is specified, we might need to introduce a `LISTAGG` emulation also for Oracle

**Comment by lukaseder** [comment]
Hmm, I think we'll need a bit more infrastructure to emulate these things in Db2 and Oracle. Will create a separate issue, so 3.14.8 won't be delayed: #11484
