### ISSUE TITLE
Caching with Redis: Records vs POJOs (and mapping)

### ISSUE THREAD

**Issue by hemju** [jOOQ/jOOQ#11305]
### Your question:

Our repositories return Records (via fetch, fetchOptional, etc.) which are then used by Services/Controller, etc. We are now thinking about adding a cache to some of our repositories via Spring Boot Cacheable notation. By doing so, the actual `UpdatableRecord` (with all the meta-information) would be attempted to store in Redis as JSON (currently, we are using `GenericJackson2JsonRedisSerializer`). Is there a better way to cache results like this? Should we use binary serialization from Java instead of JSON? What is the preferred way here?

My idea is that I would provide our own serializer that would convert Records to POJOs before serializing, so we would only store the data. However, for that, an explicit mapping would help a lot. So is there a way to find the corresponding POJO from a Record and vice versa? E.g. `MyTableRecord` <-> `MyTable`.

Thanks!

### Versions:

- jOOQ: 3.13.3
- Java: 13
- Database (include vendor): PosgreSQL
- OS: Mac

**Comment by lukaseder** [comment]
Thanks a lot for your message.

As of jOOQ 3.x, all jOOQ classes are `Serializable`, which can be helpful for quick-and-dirty serialisation, e.g. when sending jOOQ records over the wire using some old binary protocol based APIs like RMI. I mean, why not.

But since the Java serialisation is broken on many levels, and since we're not actually formally supporting it completely (e.g. making sure different jOOQ versions can compatibly serialise / deserialise stuff, etc.), we might unsupport this feature at some point in the future: https://github.com/jOOQ/jOOQ/issues/2359. You could still use it today, just beware of this possible limitation in the future, and of the fact that at every patch release (not just minor release!), your deserialisation might break just because we move around some attributes internally, and they're now serialised in a different order.

We also support serialising our records to JSON/XML/text format out of the box, using `Record.formatJSON()` and other methods, or `DSLContext.fetchFromJSON()`:
https://www.jooq.org/doc/latest/manual/sql-execution/exporting

Or, you use your generated POJOs, which have no jOOQ dependencies and contain only the actual data. We support out of the box mapping/unmapping via `Record.into(Class)`, and `Record.from(Object)`, governed by the `DefaultRecordMapper`, `DefaultRecordUnmapper`, and overridable via the relevant SPIs:
https://www.jooq.org/doc/latest/manual/sql-execution/fetching/pojos-with-recordmapper-provider

The POJOs are more third-party serialisation friendly than our records, but you could still use Jackson on our records, too, with some tweaks, I guess.

> So is there a way to find the corresponding POJO from a Record and vice versa? E.g. `MyTableRecord` <-> `MyTable`.

There currently isn't, apart from the implicit naming scheme produced by the default generator strategy. You can use that, or implement your own generator strategy, which makes the link between records and pojos more "obvious", or generate custom code for this very easily, e.g. using a custom code section: https://www.jooq.org/doc/latest/manual/code-generation/codegen-custom-code/

**Comment by hemju** [comment]
Danke für die ausführliche Antwort Lukas!

We settled to write our own serializer and convert between POJOs and Records.
