### ISSUE TITLE
context.update(Table) doesn't trigger RecordListener's updateStart

### ISSUE THREAD

**Issue by mzhafez** [jOOQ/jOOQ#11378]
### Expected behavior
Based on documentation here https://www.jooq.org/doc/3.13/manual/sql-execution/crud-with-updatablerecords/crud-record-listener/
Given:
```
public class InsertListener extends DefaultRecordListener {

    @Override
    public void updateStart(RecordContext ctx) {

        // Generate an ID for inserted BOOKs
        if (ctx.record() instanceof BookRecord) {
            BookRecord book = (BookRecord) ctx.record();
            book.setId(IDTools.generate());
        }
    }
}
```

When below is executed:

```
        try (DSLContext dslContext = DSL.using(new DefaultConfiguration().set(connection)
                .set(dialect)
                .set(new DefaultRecordListenerProvider(new InsertListener()))){
            dslContext.update(Tables.BOOK)
                    .set(Tables.Author, "Author name")
                    .where(Tables.BOOK.ID.eq(bookId))
                    .execute();
        } catch (SQLException | DataAccessException e) {
            e.printStackTrace();
        }
```
Then I expect the book's ID to be set to whatever IDTools.generate() generates.
### Actual behavior
updateStart method for RecordListener is not called
### Steps to reproduce the problem

I think the code above sort of outlines the steps to reproduce. If not, let me know and I'll see if I can create a side project to reproduce this issue.

### Versions

- jOOQ: 3.13.5
- Java: 11
- Database (include vendor): mysql
- OS: ubuntu
- JDBC Driver (include name if inofficial driver):

**Comment by mzhafez** [comment]
I've also noticed that if I call the `.update()` method for the `record` that I'm trying to update will call the RecordListener's `updateStart` method just fine.

**Comment by lukaseder** [comment]
Thanks a lot for your message.

The `RecordListener` is the lifecycle event listener for `UpdatableRecord` actions, see also the Javadoc:
https://www.jooq.org/javadoc/latest/org.jooq/org/jooq/RecordListener.html

> A listener for manipulation events on UpdatableRecords

Or the documentation you've linked. It cannot possibly work for bulk DML operations, which perform their updates on *data sets* directly in the database, not row-by-row in the client.

Look at your example:

```java
dslContext.update(Tables.BOOK)
  .set(Tables.Author, "Author name")
  .where(Tables.BOOK.ID.eq(bookId))
  .execute();
```

Assuming you dropped the `WHERE` clause, this would mean we'd have to fetch the entire table into memory, perform the actions you've specified, and store the records again, 1-by-1. Or this query:

```java
dslContext.update(Tables.BOOK)
  .set(Tables.Author, select(T.X).from(T).where(T.Y.eq(BOOK.ID)))
  .execute();
```

Now, not only would we have to fetch the entire table into memory, we'd also have to join the correlated subquery.

This is certainly doable, but is it the right thing to do? It would be very inefficient, and probably not what you had in mind anyway.

What you seem to want is a sort of trigger that fires in the client rather than the server (see our upcoming jOOQ 3.15 `CREATE TRIGGER` support: https://github.com/jOOQ/jOOQ/issues/6956). In your particular case, the trigger does not require access to the `UPDATE`'s `REFERENCING OLD` row, so you might as well implement your functionality using expression tree transformation, using a `VisitListener` (we'll soon offer better transformation support).

I might be able to provide you with other options if you could explain your actual use-case a bit more. I'm not sure if I understand why a primary key needs to be updated with a new, generated ID on *every* update...

**Comment by lukaseder** [comment]
> I might be able to provide you with other options if you could explain your actual use-case a bit more. I'm not sure if I understand why a primary key needs to be updated with a new, generated ID on _every_ update...

Ah, the example was simply adapted from our manual, from insert to update 😀

**Comment by lukaseder** [comment]
I guess we could update the documentation (javadoc and manual) to make sure this is understood.

**Comment by lukaseder** [comment]
Documentation is improved via https://github.com/jOOQ/jOOQ/issues/11379

**Comment by mzhafez** [comment]
Sorry about the confusion. My original example doesn't actually reflect my use case (I was adopting the provided example from the documentation but didn't really want to update the PK). 

Here's my actual use case: I'm trying to add an auditing (accounting) capability to one of services. I'm particularly interested in knowing who has added or updated entries from db tables and when they've done this. After figuring out who has done what; I want to add an entry to another database table to state "who has done what and when". 

Going back to my original snippet, when we do:
```
        try (DSLContext dslContext = DSL.using(new DefaultConfiguration().set(connection)
                .set(dialect)
                .set(new DefaultRecordListenerProvider(new JooqEventListener(bookAuditorRepo,userId)))){
            dslContext.update(Tables.BOOK)
                    .set(Tables.Author, "Author name")
                    .where(Tables.BOOK.ID.eq(bookId))
                    .execute();
        } catch (SQLException | DataAccessException e) {
            e.printStackTrace();
        }
```
And when our record listener is something like:
```
public class BookAuditor extends DefaultRecordListener {

    private BookAuditorRepo bookAuditorRepo;
    private Long userId;

    public BookAuditor(BookAuditorRepo bookAuditorRepo, Long userId) {
        this.bookAuditorRepo = bookAuditorRepo;
        this.userId = userId;
    }

    @Override
    public void updateStart(RecordContext ctx) {

        // Generate an ID for inserted BOOKs
        if (ctx.record() instanceof BookRecord) {
            BookRecord book = (BookRecord) ctx.record();
            bookAuditorRepo.log("update",userId,book);
        }
    }

    @Override
    public void insertStart(RecordContext ctx) {
        if (ctx.record() instanceof BookRecord) {
            BookRecord book = (BookRecord) ctx.record();
            bookAuditorRepo.log("add",userId,book);
        }
    }

}

```

I realize that it is probably for the best if I were to use `.update()` and `.insert()` methods for my record instead. But I was wondering if the above snippets could work or not. I hope that clarifies things a bit more.


Thank you for looking into this.

**Comment by lukaseder** [comment]
I really recommend you use a server side trigger:

- It will fire regardless what application (including DBeaver or DataGrip or some other SQL client) updates your data
- It will fire regardless what JDBC client updates your data (including plain JDBC, Hibernate, jOOQ plain SQL, jOOQ DSL API)
- It will also fire when you use `UpdatableRecord`

Your approach will restrict you to *only* using `UpdatableRecord` if you want trigger data to be consistent. This is exactly what triggers were designed for.

The alternative approach using `VisitListener` would allow you to also intercept jOOQ DSL API calls, or if you plug the jOOQ parser in between, then you could transform all your JDBC based queries. That's not easy to do, but possible. I'd still recommend server side triggers.
