### ISSUE TITLE
NullPointerException when using Enums

### ISSUE THREAD

**Issue by ktconnolly** [jOOQ/jOOQ#11387]
### Expected behavior

No NPE

### Steps to reproduce the problem

```
CREATE TYPE TEST_ENUM AS ENUM ('FOO','BAR');
CREATE TABLE IF NOT EXISTS MY_TABLE
(
    enum_field TEST_ENUM
);
```

The following throws a NullPointerException

```
 create.selectFrom(MY_TABLE)
    .where(MY_TABLE.ENUM_FIELD.eq(TestEnum.BAR))
    .fetch();
```

### Versions

- jOOQ: 3.14.4
- Java: 11 
- Database (include vendor): CockroachDB v20.2.3
- OS: Mac
- JDBC Driver (include name if inofficial driver): spring-jdbc 5.3.3

**Comment by lukaseder** [comment]
Thanks a lot for your report. Very interesting, enum type support are a very recent addition to CockroachDB, which we aren't supporting yet. We'll definitely do this for jOOQ 3.15. They're popular enough in PostgreSQL as well!

**Comment by lukaseder** [comment]
Here's the ticket to track progress of enum type support in CockroachDB: https://github.com/jOOQ/jOOQ/issues/11393. I'll try to reproduce this NPE to make sure it won't happen starting from jOOQ 3.15

**Comment by remekzg** [comment]
I think it's worth mentioning below workaround is not throwing exceptions and works as expected:
```
create.selectFrom(MY_TABLE)
    .where(DSL.condition("MY_TABLE.ENUM_FIELD = 'BAR'"))
    .fetch();

**Comment by lukaseder** [comment]
Sure. Plain SQL templating is always a good workaround.

In the meantime, I think this is the reason why code generation doesn't produce the correct link: https://github.com/cockroachdb/cockroach/issues/60145

I'll work around that CockroachDB bug in jOOQ for now. While the `PG_ENUM` and `PG_TYPE` tables seem to contain the correct data, the `information_schema.columns` table does not, which is why having the separate `SQLDialect.COCKROACHDB` dialect is again useful...

So far, everything's looking good, so enum type support should be ready with the next nightly build from here: https://www.jooq.org/download/versions
