### ISSUE TITLE
Bind variables cause CASE .. WHEN in SELECT DISTINCT + ORDER BY to fail on PostgreSQL

### ISSUE THREAD

**Issue by sgrimm** [jOOQ/jOOQ#11391]
### Expected behavior

The following should execute successfully.

```kotlin
fun demo() {
  val caseExpression = DSL.case_(MYTABLE.MYCOLUMN).mapValues(mapOf("x" to "y"))
  val query = dslContext
      .selectDistinct(caseExpression)
      .from(MYTABLE)
      .orderBy(caseExpression)

  println(query.getSQL(ParamType.INLINED))

  query.fetch()
}
```

### Actual behavior

PostgreSQL rejects the query and returns an error `ERROR: for SELECT DISTINCT, ORDER BY expressions must appear in select list`.

However, if you execute the query with inlined parameters in psql, it works fine.

I assume it's because PostgreSQL can't tell that the bind variables in the SELECT DISTINCT have the same values as the ones in the ORDER BY. Seems like jOOQ needs to inline the values in the two `CASE`s.

Workaround (which produces nicer-looking SQL anyway) is to add `.as()` to the `DSL.case_()` and use the column alias rather than the CASE expression in the ORDER BY clause.

### Versions

- jOOQ: 3.14.4
- Java: 11.0.8
- Database (include vendor): PostgreSQL 12.5
- OS: OS X 10.15.7
- JDBC Driver (include name if inofficial driver): 42.2.18

**Comment by lukaseder** [comment]
Please use `DSL.inline()` to wrap your values `"x"` and `"y"`:

```kotlin
mapOf(inline("x") to inline("y"))
```

Sure, we could try to find all the cases where we'd have to inline things automatically. A similar case is when you attempt to reuse an expression between `GROUP BY` and `SELECT`. There are a few more. But this very hard to do for all the potential edge cases, including using complex correlated subqueries in `GROUP BY` or `DISTINCT`, and it would waste costly CPU cycles for the 99% of queries where this is not an issue, and even then, it might not be the desired behaviour because inlining bind values tends to prevent optimal usage of execution plan caches (not in PostgreSQL, but in most commercial RDBMS), so it would not be the right thing to do anyway.

The right thing to do would then be to do as you suggested: Make sure the case expression is declared only once, and then referenced by name.
