### ISSUE TITLE
Feedback about manual section codegen-database-name

### ISSUE THREAD

**Issue by vignesh380** [jOOQ/jOOQ#11416]
Please include the type of propeties that we can use (Or atleast a link of where we can find the list of properties). Its super hard to know what properties to add here without having a list of it

**Comment by lukaseder** [comment]
Thanks for your message.

The properties relevant to a *specific* database are always documented on that database's page, e.g. the `DDLDatabase`:
https://www.jooq.org/doc/latest/manual/code-generation/codegen-ddl/

It wouldn't make sense to document all the properties on the overview page from which you came here:
https://www.jooq.org/doc/latest/manual/code-generation/codegen-advanced/codegen-config-database/codegen-database-name/

But we can add a remark about the properties being documented on the relevant pages afterwards. Or even remove that part, because it's not relevant to this page.

If you're looking for a documentation of the actual XML content, every manual page links to the XSD where that is documented:
http://www.jooq.org/xsd/jooq-codegen-3.14.0.xsd
