### ISSUE TITLE
POJOs map expect a too much general RecordMapper

### ISSUE THREAD

**Issue by PaoloCifariello** [jOOQ/jOOQ#11550]
### Your question:

Hi all, I am trying to use `RecordMapper` to map my POJOs as follows (Kotlin project):

```
class CatMapper : RecordMapper<CatRecord, CatDTO> {
    override fun map(dbRecord: CatRecord): CatDTO { ... }
}
```

Unfortunately, I am not able to actually use this mapper with the `.map(..)` function on `CatRecord` inherited from https://github.com/jOOQ/jOOQ/blob/fd756190b194bbd303ccb382086e8607e320a1ed/jOOQ/src/main/java/org/jooq/impl/AbstractRecord.java#L913-L916 because it expects a more general `RecordMapper<Record, CatDTO>`.

Am I missing something? Is there another way to do this? 
I would prefer not to make my `CatMapper` more general and then cast the input `dbRecord: Record` to a `CatRecord`

I was wondering why this function is not on https://github.com/jOOQ/jOOQ/blob/fd756190b194bbd303ccb382086e8607e320a1ed/jOOQ/src/main/java/org/jooq/TableRecord.java#L54 where you have access to the type of the record.

Thanks in advance for the help.

### Versions:

- jOOQ: 3.14.4
- Java: 11.0.8 (Kotlin 1.4.21)
- Database (include vendor): -
- OS: -
- JDBC Driver (include name if inofficial driver): -

**Comment by PaoloCifariello** [comment]
I just found https://github.com/jOOQ/jOOQ/issues/2570 marked as **Incompatible change**, so I guess my issue will result in the same answer/label.

**Comment by lukaseder** [comment]
Thanks a lot for your question. Indeed, this is related to https://github.com/jOOQ/jOOQ/issues/2465 and #2570. We can't fix this easily as Java won't allow for a type to introspect itself via generics. Even if `TableRecord` uses a recursive type bound, which would allow this, `TableRecord` can't compatibly override `Record::map` with a "better" parameter type.

But since you're using kotlin, you can work around this rather easily by adding an extension method that captures the generics correctly. Alternatively, your record mapper will work out of the box on a `Result`.
