### ISSUE TITLE
Hibernate HQL / JPQL support

### ISSUE THREAD

**Issue by djmj** [jOOQ/jOOQ#11685]
### Use case:

Hibernate / JPA has its own SQL abstraction query language HQL / JPQL and i mainly decided for Hibernate to retrieve entitys needing less SQL to write.

Still you need some more complex queries and so we can either use the non-intuitive and just cumbersome criteria API or use 
old String concatenation for dynamic HQL queries. 

Criteria API like java lambdas just feel really akward to work with compared to C# Linq / Lambda or jOOQ syntax.

### Possible solution you'd like to see:

HQL and SQL are not that different so it would be great to create HQL query strings with jOOQ to retrieve the String and call hibernate _session.executeQuery(query)_.

**Comment by lukaseder** [comment]
Thanks a lot for your feature request.

Supporting alternative query languages is obviously something that has been considered multiple times in the 13 years of jOOQ's existence, including support for "SQL-esque" NoSQL dialects. It has been rejected for the same reasons every time.

One of jOOQ's strengths is its focus on SQL *and only* SQL. SQL is an ISO standard (which superseded the previous ANSI standard), and the many currently supported dialects are surprisingly standards compliant, overall. This means that a large part of jOOQ's API can be mapped to some dialects, and only few new clauses need to be supported when a new dialect is added.

This is not at all the case with these "SQL-esque" dialects, including HQL. If you want to work with HQL, you accept a few quirks that are not at all SQL. This includes:

- The peculiar interpretation of what "DISTINCT" means, which is distinctly different from SQL's DISTINCT
- The (current) lack of UNION and derived tables
- The fact that it is based on entities and not tables (e.g. identifiers are not SQL identifiers but entity path expressions, which may be quite different, e.g. when using embeddable types, etc.)
- Peculiar rules like the requirement to fetch an entity entirely, an interesting relationship between entities and DTOs (in SQL, there's no distinction)
- Custom entity-graph specific syntax like join fetch
- Hints that are necessary to influence the graph materialisation
- Client side projection expressions that are interleaved with the query for "DTO projections", "map projections", etc. (which in my opinion is a *very* bad idea, and will make supporting unions and derived tables in a language-consistent way in HQL 6 quite difficult, but let's see how they pull that one off)
- Polymorphic queries

While HQL/JPQL mimick SQL, they come with an entire bag of assumptions that are related to Hibernate/JPA being an ORM. These may be useful features in the ORM world, but distractions in jOOQ's pure SQL world. If jOOQ were to start supporting these languages, we'd be spending *a lot* of time with weird edge cases where the two paradigms don't match, and we'd be offering a sloppy solution to a problem that is not worth solving (IMO). Not to mention working around language limitations that are due only to HQL being very simple, and not having been evolved for a long time, see e.g. this lack of basic SQL functionality: https://stackoverflow.com/a/55646690/521799 (it would be *very* easy to fix in HQL. The requirement of having a `FROM` clause on an entity is unnecessary, but yet, I couldn't find any other way. I'm hoping this will be fixed in Hibernate 6).

An alternative route would be that chosen by QueryDSL, a much simpler competitor product of jOOQ that is in "maintenance mode". Just look at how many QueryDSL users get confused by whether they are supposed to run a query with SQL or JPQL. It's a constant source of confusion there on github, mailing list, and stack overflow. If you know what you're doing, and everyone on the team does, as well, then it can offer some value nonetheless, of course. But my point here is that offering such vastly different paradigms under one API is a big risk, especially for beginners. I wouldn't want something like that in jOOQ.

But again, why do it at all? Why not just skip the unnecessary abstraction that is HQL, and run an actual SQL query instead? If you're projecting DTOs, you don't need Hibernate. You can do that with jOOQ directly (and much better). If you're projecting entities, then do this:
https://www.jooq.org/doc/latest/manual/sql-execution/alternative-execution-models/using-jooq-with-jpa/using-jooq-with-jpa-entities

Regarding your specific requirements here:

> i mainly decided for Hibernate to retrieve entitys needing less SQL to write.

I think then, you have come to the wrong place. jOOQ is *best* used when you *want* to write SQL. There's an entire paradigm and programming style, where SQL is embraced, not avoided. And I don't mean for reporting. I mean, for almost everything. It's a stateless, functional-ish, data transformation pipeline-ish paradigm that integrates extremely well with functional programming languages.

There's no judgement here. Both approaches (statefull OO or stateless FP) have their merits. But to give you proper context: a feature request that asks for a huge project based on the assumption that writing SQL is something to avoid won't have high chances of getting prioritised in jOOQ :)

Sure, we have some CRUD utilities as well, like generated table-based (not entity graph based) `DAO` classes and active record style `UpdatableRecord`. CRUD is boring and some tooling is nice. But again, jOOQ is best used in a paradigm where "SQL is good".

> Still you need some more complex queries and so we can either use the non-intuitive and just cumbersome criteria API or use
> old String concatenation for dynamic HQL queries.

Or, you use SQL. Why not just give SQL a try? Why limit yourself to HQL? Hibernate 5's HQL is extremely primitive, even more so than SQL-92 (see the above Stack Overflow link). They're working on adding some more "modern" SQL features to HQL 6, and I'm very curious how that will turn out, because once they start adding this complexity to HQL, supporting the features on all RDBMS will start to become *really* interesting. So far, RDBMS agnosticity was rather trivial in HQL.

But even then, why not just use actual SQL? Because you need the `JOIN FETCH` clause? To give you an example, last week, I've implemented the Teradata `QUALIFY` clause emulation (https://github.com/jOOQ/jOOQ/issues/5810). Native support has been around in jOOQ for a while, but now you can run a query like this:

```sql
SELECT *
FROM office AS o
JOIN employee AS e ON o.office_code = e.office_code
WINDOW w AS (ORDER BY o.office_code, o.city)
QUALIFY dense_rank() OVER w BETWEEN 1 AND 5
```

And translate it to all RDBMS that support window functions, e.g. MariaDB (which doesn't support the `WINDOW` clause yet):

```sql
-- Simplified
SELECT *
FROM (
  SELECT *, dense_rank() OVER (ORDER BY o.office_code, o.city) BETWEEN 1 AND 5 AS w0
  FROM office AS o
  JOIN employee AS e ON o.office_code = e.office_code 
) AS t
WHERE w0
```

This allows for some really cool analytics to become much simpler. And there's a whole world of SQL awesomeness that jOOQ gives you access to.

I really don't want to encourage anyone use HQL when they have jOOQ on their stack. Because there's almost not a single case where using HQL beats using SQL, even when fetching entities, you can just do that with jOOQ and 5 lines of glue code out of the box (again this link):
https://www.jooq.org/doc/latest/manual/sql-execution/alternative-execution-models/using-jooq-with-jpa/using-jooq-with-jpa-entities

The one big innovation HQL has introduced, which are implicit joins, jOOQ has as well.

You might be missing `JOIN FETCH`, which I believe is solving the problem of nesting collections in the wrong way, but that's a fundamental question that cannot be answered easily. The way jOOQ allows you to nest collections (not graphs) is again with SQL:
https://blog.jooq.org/2020/10/09/nesting-collections-with-jooq-3-14s-sql-xml-or-sql-json-support

Because in SQL, everything is always projecting tuples (and nested collections of tuples), not entities, jOOQ's approach is more aligned with how SQL best works. If most of your application is entity based (ideally not because you want to avoid SQL, but because you want to write back the object graph modifications to the database), then yes, jOOQ won't help you here.

> Criteria API like java lambdas just feel really akward to work with compared to C# Linq / Lambda or jOOQ syntax.

I think there's a lot of judgement, here. I mean, you seem to not like to be working in the Java world, coming from C#. I'm not sure what Java's lambdas have to do with HQL here, so this seems like a general frustration with the Java ecosystem projected into a wish for jOOQ to support HQL, because that seems like an escape hatch (?). Though, you wouldn't be using it anytime soon, even if I did implement it, it would take a long time to get right.

jOOQ is about SQL. And if you embrace jOOQ (and thus SQL), you won't even miss LINQ. But if you want jOOQ to be LINQ, then you won't be happy again, because LINQ tries to abstract SQL *a lot* in order to unify its idea of querying behind an API that is implementation-language-agnostic, just like QueryDSL. It can help with simple queries, but as soon as you want to leverage *actual SQL*, it fails (unsurprisingly, LINQ-to-SQL isn't the most popular LINQ implementation). Here's an interesting interview with Ming-Yee Iu, author of JINQ on that subject:
https://blog.jooq.org/2016/04/19/jooq-tuesdays-ming-yee-iu-gives-insight-into-language-integrated-querying/

Now, again, I don't want to judge any technology here, or any preference of style. Everyone has their background and their reasons for preferring X or Y. I just want to make sure the expectations are right. jOOQ *is* SQL and it always will be. It is not something else. And it will not support HQL or any other QL that is not SQL. There are *much* more interesting features on the roadmap that offer much more value than helping people avoid SQL for just a bit longer.

> HQL and SQL are not that different

In my perception, they are quite different.

### So, your options seem to be:

- Stick with the JPA Criteria API (Which does its job. If you just have 2-3 dynamic queries, why not just use that. You can also wrap it in some utilities to make its UX quirks a bit more bearable)
- Use QueryDSL (the risk here is whether it will be maintained in the future)
- Re-think your paradigm and expectations, and embrace jOOQ and SQL in the way they are intended and designed

**Comment by djmj** [comment]
Much thanks for your long reply with explanations.

> If you want to work with HQL, you accept a few quirks that are not at all SQL. This includes:

Thats a true story and i hope they will resolve some things like UNION at least and better create a new keyword like _DISTINCT_ENTITY_ since depending on use case they use SQL DISTINCT or their Entity based DISTINCT.

> I think then, you have come to the wrong place. jOOQ is best used when you want to write SQL. 

I think so too and i just had a look at jOOQ because a friend told me to use it.

> I mean, you seem to not like to be working in the Java world, coming from C#. I'm not sure what Java's lambdas have to do with HQL here,

Because HQL, Criteria are necessary because Java simply "fucked up" lambda from the start since they are not reusable for in-memory or SQL queries. Yes i am frustrated about this cause i am a java main and java makes it just unnecessary complex.

The whole _Criteria_ API (Hibernate or JPA) is just a confession how bad Java lambdas are. C# lambdas map directly to SQL syntax. No strange syntax, unintuitive method chaining or error prone string based syntax like Criteria with _Restrictions.eq("foo.bar.id", 2)_.  

*C#*

This code can be used in-memory or *directly* maps to SQL with Entity Framework.

`list.where(foo => foo.name.equals("test")).Any()`

*Java*

This code is used in-memory and for SQL we have to revert back to Criteria or other frameworks like jOOQ. So much waste of developer time.

`list.stream().anyMatch(foo => foo.name.equals("test"))`

That _anyMatch_ is so unintuitive if you follow SQL syntax. Yes so jOOQ was an idea to *escape* that nightmare. Every Java main should some time with C#, Lambda and EntityFramework and see how 50% of time can be saved.

When Java introduced lambda i thought they were joking honestly. Its the new "Date / Calendar" nightmare in my opinion ... and so i search for escapes because my own enterprise application 9+ years now in development and production is based on java.

**Comment by lukaseder** [comment]
Thanks. Let me know if there's anything actionable (with respect to jOOQ) that I can help you with.

**Comment by djmj** [comment]
If i will use jOOQ in future i will let you know. Also sorry to let you wait for half a year of my reply but i was very busy and wanted to take my time for a response.

**Comment by lukaseder** [comment]
> Also sorry to let you wait for half a year of my reply but i was very busy and wanted to take my time for a response.

Oh, no worries about that. Just, I mean, Java is Java and C# is C# and JPA is JPA and SQL is SQL and jOOQ is jOOQ, and I can't help you with your frustrations about the various status quos, but once you do decide for SQL and jOOQ, I will be able to help 😉
