### ISSUE TITLE
Feedback about manual section xml-table-function

### ISSUE THREAD

**Issue by uhrm** [jOOQ/jOOQ#11723]
Is it possible to use XML namespace aliases in jOOQ's XMLTABLE implementation?

The problem is in Postrges, when the XML document has a namespace defined, it is required to use a namespace alias for the XPath expressions to work. the syntax in Postgres is as follows:

```SQL
select A.REFERENCE, A.NAME, A.ADDRESS
from
  xmltable(
    xmlnamespaces ('https://example.com/namespace' as "M"),
    '/M:ROOT'
    passing ...
    columns
      REFERENCE text path '@REFERENCE',
      NAME text path 'M:NAME',
      ADDRESS text path 'M:ADDRESS'
  ) A
```

It would be quite neat if we could query namespaced XML documents using jOOQ.

**Comment by lukaseder** [comment]
Thanks a lot for your message. We don't support that yet, but it would be very useful indeed. I've created a feature request for this: https://github.com/jOOQ/jOOQ/issues/11727

As a workaround, you could trick jOOQ into generating your `XMLNAMESPACES()` function via plain SQL templating:
https://www.jooq.org/doc/latest/manual/sql-building/plain-sql-templating/

Instead of passing a `Field<String>` for the XPath expression directly, pass a template:

```java
field("xmlnamespaces ({0} as {1}), {2}", VARCHAR, val("https://example.com/namespace"), name("M"), val("/M:ROOT"));
```
