### ISSUE TITLE
Integer type selection

### ISSUE THREAD

**Issue by nicko** [jOOQ/jOOQ#11741]
### Your question:
I'm working with a SQL structure that uses many different sizes of integers and numbers and I'm confused by the selection that jooq makes for those types. In the table in [this question](https://github.com/jOOQ/jOOQ/issues/5736#issuecomment-279001880) it shows that getting an Integer from a NUMERIC SQL is achieved with `NUMERIC(9, 0)`, however the max range of a Java int is 10 digits, not 9. The same goes for Longs (`NUMERIC(18, 0)`) which are 19 digit numbers. 

Am I missing something or will these conversions possibly lose data at the most extreme ends of ints and longs?

### Versions:

- jOOQ: 1.13.6
- Java: 11
- Database (include vendor): Oracle 18c
- OS: MacOS
- JDBC Driver (include name if inofficial driver): Oracle thin

**Comment by lukaseder** [comment]
Thanks for your message.

jOOQ always assumes a database-first paradigm. Your schema will outlive jOOQ (hopefully not), and your jOOQ usage (more likely), or even your Java usage. As such, we need a Java type to represent the `NUMBER(9)` type when you fetch your data. We don't need a SQL type to represent your Java type, though, because the SQL type is what really matters to your schema, not the Java type.

Of course, we could have designed this differently, for the Java type to be more important than the mapped SQL type, and you can still achieve this using forced types, or you can turn off this feature by specifying `<forceIntegerTypesOnZeroScaleDecimals>false</forceIntegerTypesOnZeroScaleDecimals>`. But I think the default we have reflects the most desirable behaviour.
