### ISSUE TITLE
SEEK with GTE instead of GT

### ISSUE THREAD

**Issue by sp00m** [jOOQ/jOOQ#11751]
### Use case:

When doing cursor-based pagination, I'd like to know whether the fetched page has a previous page (GraphQL in mind).

### Possible solution you'd like to see:

One solution could be to allow SEEKing with GTE instead of GT, so that if the requested "after cursor" is the same as the first fetched record's, I know that the fetched page has a previous page. I'd just need to remove the first record from the fetched records manually (so that the "after cursor" is still seen as "excluded").

I know this won't provide a 100% accurate result though, because if the record uniquely matching the "after cursor" is DELETEd, the fetched page might still have a previous page, but it could help to cover some more cases without having to do an extra roundtrip to the database.

### Possible workarounds:

I'm currently implementing this GTE SEEK manually.

**Comment by lukaseder** [comment]
Thank you very much for your suggestion. That is an interesting idea. You couldn't use `LAG()` here, because the `SEEK` clause generates a `WHERE` clause currently, so the order of operations is not correct.

I wonder if that's a bug, actually. Perhaps, seek should only produce `WHERE` predicates in the absence of `GROUP BY`, `HAVING`, `WINDOW`, and `QUALIFY`. I'll have to think about this. If that's a bug, then `LAG()` would work after the fix, and would offer a better solution IMO. If it's not a bug, or acceptable behaviour, then `seekIncluding()` could be added to produce `>=` rather tan `>` semantics.

**Comment by lukaseder** [comment]
Looking into this again. Previous comments hint at this issue adding a bit of complexity, which is never a good sign.

The `SEEK` semantics is clearly defined for navigating to "next" pages as in a timeline. Your described use-case would not be satisfied by introducing the `>=` semantics replacing the current `>` semantics, because the record that you would expect to receive as an indicator of there being a previous page might have been deleted in the meantime.

I think you'll have to implement your semantics using other primitives in jOOQ, including `QUALIFY`.
