### ISSUE TITLE
Code generator creates invalid field definition

### ISSUE THREAD

**Issue by cdalexndr** [jOOQ/jOOQ#11754]
### Expected behavior
No error.

### Actual behavior
```
generated\jooq\tables\Product.java:73: error: no suitable method found for createField(Name,DataType<LocalDateTime>,Product,String,InstantJooqBinding)
    public final TableField<ProductRecord, Instant> LAST_UPDATE = createField(DSL.name("last_update"), org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false), this, "", new InstantJooqBinding());
```

### Steps to reproduce the problem

Using forced type:
```
generationTool {
    jdbc {
        driver = 'org.postgresql.Driver'
        url = 'jdbc:postgresql://localhost:5432/postgres'
        user = 'postgres'
        password = 'postgres'
    }
    generator {
        name = 'org.jooq.codegen.DefaultGenerator'
        strategy {
            name = 'org.jooq.codegen.DefaultGeneratorStrategy'
        }
        generate {
            javaTimeTypes = true
        }
        database {
            name = 'org.jooq.meta.postgres.PostgresDatabase'
            syntheticPrimaryKeys = '.*\\.id'
            schemata {
                schema {
                    inputSchema = prototypeSchema
                    outputSchemaToDefault = true
                }
            }
            forcedTypes {
                forcedType {
                    userType = 'java.time.Instant'
                    binding = 'mypackage.InstantJooqBinding'
                    includeTypes = 'timestamp'
                }
            }
        }
        target {
            packageName = 'jooq'
            directory = Paths.get(projectDir.path, 'src/main/generated').toFile()
        }
        strategy.name = 'org.jooq.codegen.DefaultGeneratorStrategy'
    }
}
```
where `InstantJooqBinding implements Binding<Timestamp, Instant>`.
It generates invalid field definition:
`public final TableField<ProductRecord, Instant> LAST_UPDATE = createField(DSL.name("last_update"), org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false), this, "", new InstantJooqBinding());`

### Versions

- jOOQ: 3.13.4
- Java: 11
- Database (include vendor): Postgres 12
- OS: Win 10
- JDBC Driver (include name if inofficial driver): org.postgresql:postgresql:42.2.15

**Comment by lukaseder** [comment]
Thanks for your message.

You're using the `javaTimeTypes = true` flag. This means you've decided to use JSR 310 (`java.time`) types in your generated code, instead of the `java.sql` types, such as `java.sql.Timestamp`. You can't use a `Binding<Timestamp, Instant>` on a `Field<LocalDateTime>`. Rewrite your binding to be of type `Binding<LocalDateTime, Instant>`. jOOQ couldn't possibly detect this automatically for you, and translate between `Timestamp` and `LocalDateTime`, because the code generator doesn't know the type of your `Binding`

Notice that unless you're doing something very fancy in that binding, you can also just apply a forced type to `<name>INSTANT</name>` in jOOQ.

```
forcedType {
    name = 'INSTANT'
    includeTypes = 'timestamp'
}
```

**Comment by cdalexndr** [comment]
>forcedType {
    name = 'INSTANT'
    includeTypes = 'timestamp'
}

Thank you, that's exactly what I was looking for!
