### ISSUE TITLE
Record.get field cast exception

### ISSUE THREAD

**Issue by cdalexndr** [jOOQ/jOOQ#11828]
### Expected behavior
No error.

### Actual behavior
`cannot cast long to int`

### Steps to reproduce the problem
```
Field<Integer> intField = DSL.countDistinct(...);
Select query = DSL.select(intField)....;
Record r = dsl.fetchOne( query.toString() );
int resInt = r.get(intField); //returns Long instead of Integer
```
Actually, the field type is not checked when retrieving the result field value. An unsafe cast is used to trick the compiler: 
https://github.com/jOOQ/jOOQ/blob/f4d2a16966577736900b196214be1b9e22fa1463/jOOQ/src/main/java/org/jooq/impl/AbstractRecord.java#L326

### Versions

- jOOQ: 3.14.8
- Java: 11
- Database (include vendor): Postgres
- OS: Win10
- JDBC Driver (include name if inofficial driver): postgres

**Comment by lukaseder** [comment]
Thanks a lot for your report. There are a few things to note here:

- A query created with `DSL.select()` is not "attached" to a `Configuration`, so it does not have any dialect information associated with it. That way, you are very lucky if it works on a given dialect at all
- `Query.toString()` works only the way you intend with queries that have a `Configuration` attached. If you can't attach a `Configuration`, you should use `DSLContext.render()` to render a query in the context of a `Configuration`
- Just curious about the use-case: Why do you pass through the plain SQL API when you already construct a type safe query using the DSL?
- The way to "coerce" plain SQL result set types is to use `ResultQuery.coerce()` methods, e.g. `dsl.resultQuery(string).coerce(types).fetchOne()`
- I understand the expectation of the type safe access to `r.get(intField)` here, given that the Java compiler seems to hint at this to work. That issue is already being tracked here: https://github.com/jOOQ/jOOQ/issues/5846

Hence, I'm closing this as a duplicate. The workarounds for the time being are documented above.

**Comment by cdalexndr** [comment]
>     * Just curious about the use-case: Why do you pass through the plain SQL API when you already construct a type safe query using the DSL?

I get 15x speedup if I don't use `PreparedStatement`. I've reported this performance issue to postgres.

**Comment by lukaseder** [comment]
That's weird. Can you link to the issue? I'd love to have a look.

You don't have to work around things the way you do. Just use `Settings.setStatementType(StatementType.STATIC_STATEMENT)`, and jOOQ will stop generating `PreparedStatement` behind the scenes, see: https://www.jooq.org/doc/latest/manual/sql-building/dsl-context/custom-settings/settings-statement-type/

**Comment by cdalexndr** [comment]
> That's weird. Can you link to the issue? I'd love to have a look.

https://github.com/pgjdbc/pgjdbc/issues/2145

**Comment by cdalexndr** [comment]
And here's the postgres mail thread: https://www.postgresql.org/message-id/3f8c88d8a6ef9.d82fa04cf610d%40yahoo.com
