### ISSUE TITLE
Artifacts unavailable from Maven Central

### ISSUE THREAD

**Issue by jonatan-ivanov** [jOOQ/jOOQ#11907]
Depending on `org.jooq:jooq:3.14.+` causes this since today (2021-05-20):

```
Could not resolve all dependencies for configuration ':micrometer-core:testCompileClasspath'.
Problems reading data from Binary store in /private/var/folders/h5/qfnl5tk13r93f9r6kmlcgfs80000gp/T/gradle1253761999290750042.bin offset 1499029 exists? true
Corrupt serialized resolution result. Cannot find selected module (124) for testCompileClasspath -> org.jooq:jooq
```

Rolling back to `3.14.8` fixes the issue.

**Comment by lukaseder** [comment]
Thanks for your report. It seems that sonatype screwed up the deployment. Nothing has been deployed:
https://repo1.maven.org/maven2/org/jooq/jooq/

But the meta data is there:
https://search.maven.org/artifact/org.jooq/jooq/3.14.10/jar

I'll try to deploy it again, otherwise, a 3.14.11 release will be needed.

**Comment by lukaseder** [comment]
I'll just release 3.14.11, that will be simpler

**Comment by jonatan-ivanov** [comment]
Thanks for the fast turnaround! :)
