### ISSUE TITLE
Improvement of code generation w.r.t lint checks

### ISSUE THREAD

**Issue by Karthikeyashastry** [jOOQ/jOOQ#11952]
### Use case:

For the classes generated using codegen functionality, it would be helpful, if these changes are done, so that it would cause lint issues.

For example:
```
/*
 * This file is generated by jOOQ.
 */
package com.sample.jooq;
```
This causes lint problem
- 'package' should be separated from previous statement. [EmptyLineSeparator]

Ideally
```
/*
 * This file is generated by jOOQ.
 */

package com.sample.jooq;
```

Another lint issue being
- First sentence of Javadoc is missing an ending period. [SummaryJavadoc]

It would be helpful if generated javadoc, conforms to lint standards.

### Versions:

- jOOQ: 3.14.9
- Java: 11

**Comment by lukaseder** [comment]
Thanks for your suggestion.

> 'package' should be separated from previous statement. [EmptyLineSeparator]

Can you please make a statement as to why this is important to you, and who thinks this is important? Some third party check style? Why do they insist on this? At first sight, this seems like completely irrelevant busywork, but maybe I'm overlooking something :)

> First sentence of Javadoc is missing an ending period. [SummaryJavadoc]

Same here. Can you please make a strong case in favour of this?

**Comment by lukaseder** [comment]
Without a compelling motivation towards such minor improvements (whose rationale may be available from a lint tool, but I don't know the tool), I'll reject this suggestion.

**Comment by roded** [comment]
Checkstyle would be a relevant lint tool.  Specifically for this case, the EmptyLineSeparator rule: https://checkstyle.sourceforge.io/config_whitespace.html#EmptyLineSeparator

Generally speaking, the issue here isn't why the linting tool cares about this rule (rules can be enabled/disabled as required by a project's conventions), but rather, experiencing less friction when committing jOOQ-generated sources into a repository.

The same result can be also accomplished by configuring Checkstyle to ignore generated source directories, but the solutions are not mutually exclusive.

**Comment by lukaseder** [comment]
> Generally speaking, the issue here isn't why the linting tool cares about this rule

Of course it is! It is *only* about this. They had a choice of activating this pedantic rule by default or not. They chose wrong. Have you considered asking them to turn it off? I still don't understand how anyone could consider this an important thing to spend time on.

It's up to you whether you want to engage in such busywork, but if I were you, I'd just use an auto formatter on all generated code (solving *all* such linting "problems"), or drop this rule.

Think about it this way. How much money would you be willing to pay per year for this feature (A guarantee that this rule won't be violated by jOOQ generated code in the future)?

**Comment by roded** [comment]
@lukaseder I'm not trying to be adversarial, just to provide my related experience.

The rule isn't enabled by default, and we can configure it as per our projects' requirements.

In our case, we're integrating jOOQ into an existing multi-module project and the jOOQ generated sources are causing linting issues. Of course, the project's linting rules can be changed to accommodate the jOOQ generated sources. 

It would be nice though (and just nice to have, this is really not a big issue) if jOOQ allowed configuring the generator to not add that package comment as it does for other comment options. That is all.

jOOQ is really great BTW. Cheers.

**Comment by lukaseder** [comment]
You could override `JavaGenerator::printClassJavadoc` but it wouldn't be much less effort than any of the other obvious and perfectly acceptable workarounds:

- Regex-replace this particular whitespace into the generated code
- Disable this particular rule
- Stop linting third party generated code
- Auto-format third party generated code according to your linting rules
- You could turn off `generate/javadoc` in the code generator configuration

I really have to set a precedent by saying "no" bluntly to this kind of feature request, as there is no end to the wisdoms of various linters' opinions on whitespace. It's by no means a good feature. It adds no value to anyone's code, but creates only busywork for everyone, when there are more interesting and urgent things that should be addressed instead. There's nothing adversarial about this. It's in your own best interest that such feature requests be rejected early on, because that way, much more interesting stuff is prioritised.

Much as I'm rejecting this request, you were ignoring my offer to quote you to pay for this improvement. Because really, *any* price will be too high for this kind of feature, no? That was the implication here?

**Comment by roded** [comment]
That's fine. I completely understand. And appreciate your time discussing this. I only meant to provide the feedback that OP didn't originally. Your last suggested workaround is very useful. I seem to have missed it when reviewing the code generator config.

I can't convince my company to pay for this improvement and that actually strengthens your point.
