### ISSUE TITLE
Manual section about limit-clause contains broken link about Oracle ROWNUM filtering performance

### ISSUE THREAD

**Issue by theHacker** [jOOQ/jOOQ#12106]
Hi,

just read the manual at https://www.jooq.org/doc/3.14/manual/sql-building/sql-statements/select-statement/limit-clause/

The link inside this paragraph
> Side-note: If you're interested in understanding why we chose ROWNUM for Oracle, please refer to this very interesting benchmark, comparing the different approaches of doing pagination in Oracle: http://www.inf.unideb.hu/~gabora/pagination/results.html.

leads to a 404 page.

**Comment by lukaseder** [comment]
Thanks for the pointer. That's too bad, this used to be a very good resource as can be seen here: https://web.archive.org/web/20150715010127/http://www.inf.unideb.hu/~gabora/pagination/results.html

But I guess with `OFFSET .. FETCH` being production ready since at least 12cR2, we can remove that paragraph now.

**Comment by lukaseder** [comment]
Fixed. The manual will be updated in a few hours. Thanks again!
