### ISSUE TITLE
Supports reactive transaction of springframework for R2DBC

### ISSUE THREAD

**Issue by babyfish-ct** [jOOQ/jOOQ#12218]
### Use case:

After read https://www.jooq.org/doc/3.1/manual/sql-execution/fetching/reactive-fetching/, I used JOOQ to create my R2DBC appliction

Spring Framework support "org.springframework.transaction.ReactiveTransactionManager", So the annotation @Transactional can work with both java async methods returns Mono/Flux and suspend method of kotlin corotinues.

Util now, JOOQ has no solution to reuse the connection holden by reactive transaction manager, so the connection to execute the rollbacking and the connection to execute JOOQ are not same, finally nothing is rollbacked.

### Possible solution you'd like to see:

API: Like the "org.jooq.TransactionProvider", please support an new SPI interface "org.jooq.ReactiveTransactionProvider"

Implementation: Implement the some logic like "inConnection" and "inConnectionMany" declared in "org.springframework.data.r2dbc.core.DefaultDatabaseClient"

### Possible workarounds:

Now I use "https://github.com/gofabian/spring-boot-data-r2dbc-jooq" to be the workaround, but it's not a perfect sholution because all the converters that has been implemented by JOOQ must be implemented again by the user.

### Versions:

- jOOQ: 3.15.0
- Kotlin: 1.4(Use suspend method and kotlinx.corotinues)
- Database: Postgres13
- OS: Mac silicon
- R2DBC Driver: io.r2dbc:r2dbc-postgresql

**Comment by lukaseder** [comment]
My intuition here is that jOOQ 3.15 doesn't really lack anything with respect to being able to run queries on an injected R2DBC `io.r2dbc.spi.Connection` or `io.r2dbc.spi.ConnectionFactory`. Once *you* get a hold of that connection, then you can pass that to jOOQ.

You can use Spring Boot to auto configure jOOQ with an R2DBC connection, in case of which jOOQ is completely unaware of how you manage your transactions via spring.

We don't have our own reactive transaction API yet, see https://github.com/jOOQ/jOOQ/issues/11717. But I think that's not what you want here. You want to use Spring's transaction management, and jOOQ should be unaware of it, if you configure things correctly.

Unless I'm missing anything?

**Comment by babyfish-ct** [comment]
Yes, it's possible to get the R2DBC connection holded by spring reactive transaction manager, and execute the SQL generated by JOOQ by the developer himself. This practice skip the execution mechanism of JOOQ, it only uses the JOOQ as a complex SQLBuilder. Actually, the framework "https://github.com/gofabian/spring-boot-data-r2dbc-jooq" does it like this.

But this solution has a bug problem, JOOQ supports powerful data transformations by convertes, such as Enum and Json Serialization. Skipping the execution mechanism means the all the data transformation work must done by the developer himself. This is repetitive work because JOOQ's execution mechanism has implement the data transformation perfectly.

This is snapshot of https://github.com/gofabian/spring-boot-data-r2dbc-jooq, the converter is repetitive work.
![image](https://user-images.githubusercontent.com/15168900/126200793-01a4a154-5264-4619-95d6-455169ab6943.png)

That's why it's very important to let JOOQ itself to support the execution mechanism that can work together with spring reactive transaction manager.

**Comment by lukaseder** [comment]
> Yes, it's possible to get the R2DBC connection held by spring reactive transaction manager, and execute the SQL generated by JOOQ by the developer himself. This practice skip the execution mechanism of JOOQ

jOOQ 3.15 has a `DSL.using(io.r2dbc.spi.Connection)` and related APIs, so that's not what I meant. I meant executing the query with jOOQ, but using an R2DBC Connection that is not managed by jOOQ. It's the exact same thing you can do with JDBC as well. jOOQ isn't opinionated about connection lifecycle management, or transaction management. As soon as you give jOOQ a connction (R2DBC or JDBC), it can work with that.

**Comment by babyfish-ct** [comment]
OK, I'll try

**Comment by babyfish-ct** [comment]
Well, this method can help me to design better high level API than https://github.com/gofabian/spring-boot-data-r2dbc-jooq

Will JOOQ support out-of-the-box method to work with reactive transaction manager automatically in the future?

**Comment by lukaseder** [comment]
> Will JOOQ support out-of-the-box method to work with reactive transaction manager automatically in the future?

It will work the other way round. Once jOOQ has SPIs to override default transaction behaviour based on R2DBC, Spring Boot might pick up the SPI and provide an implementation that delegates to Spring's transaction managers instead.

By design, jOOQ does not know anything about such third parties.

**Comment by cemo** [comment]
@lukaseder 

Please forgive my ignorance. I am trying to be sure about your approach. You mean before running each query I need to access current transaction managed by reactive transaction manager and use it for jOOQ?

Let's say we have a method like:

```
  @Transactional
  public Flux<Record> insert() {
    return Flux.from(db.insertInto(table(name("foo")),
                            field(name("id")))
                .values(120)
                .returning(field(name("id"))));
  }
```

You basically suggest this: ?

```
  @Transactional
  public Flux<Record> insert() {
    Connection connection = getCurrentConnection();
    DSL.using(connection);
    return Flux.from(db.insertInto(table(name("foo")),
                            field(name("id")))
                .values(120)
                .returning(field(name("id"))));
  }
```

Please correct me If I am wrong.

**Comment by lukaseder** [comment]
That is one option, yes. Ideally, of course, you don't have to, because everything is already injected correctly and jOOQ will receive a transactional `db` reference (by virtue of the injected, pre-configured `ConnectionFactory`). But there might be a bug somewhere in Spring or Micronaut, etc. that doesn't wire things correctly to jOOQ.

Sure, you can implement your own `ConnectionFactory` proxy that works around any such potential issue. But perhaps, investigating the root cause and reporting that to the relevant framework vendor might be more effective.

For example, does your `@Transactional` annotation work if you're using R2DBC directly, instead of using jOOQ?

**Comment by cemo** [comment]
Actually I am the one who made this support as well. So if something is missing in integration, I am the root cause :-) 

https://github.com/micronaut-projects/micronaut-sql/pull/545/files

1. This is the branch I am working on. I had created such an instance of `org.jooq.Configuration` and created a `DSLContext`.  I think there is missing glue code somewhere. I would be happy to get your assistance on it. I could not understand how jOOQ will have a` transactional db` reference. What I am right now is getting `ConnectionFactory` and injecting into it. Is there something else I should do there? 

> For example, does your @Transactional annotation work if you're using R2DBC directly, instead of using jOOQ?
There is already support for R2DBC and extensive coverage.

The main part which is responsible for transaction is `io.micronaut.data.r2dbc.operations.DefaultR2dbcRepositoryOperations` 

2. How can jOOQ will know that it is in transaction because the only code I see is `createConnection`. It is like this method needs to be wired up.
3. Should I open another issue for this to conversation?

**Comment by lukaseder** [comment]
> Actually I am the one who made this support as well. So if something is missing in integration, I am the root cause :-)

Aha, I missed that. All the better! :)

> 1\. This is the branch I am working on. I had created such an instance of `org.jooq.Configuration` and created a `DSLContext`.  I think there is missing glue code somewhere. I would be happy to get your assistance on it. I could not understand how jOOQ will have a` transactional db` reference. What I am right now is getting `ConnectionFactory` and injecting into it. Is there something else I should do there?

Any dependency injected transactionality is completely unaware of jOOQ, as much as jOOQ is unaware of such a transaction management system. This is how things work in the JDBC world today, with transactional `DataSource` objects, which hide the transaction semantics from clients working on JDBC `Connection` types, without knowing in what transaction state the connection currently is.

The JDBC `DataSource` typically does that by implementing some thread-bound transaction mechanism, e.g. using `ThreadLocal`. Obviously, that can't work in the reactive world, because nothing ever is thread bound. That's the point. So, you have to use a different approach to store your transaction reference. But from the jOOQ side, this is completely irrelevant. All jOOQ needs to know is a `ConnectionFactory` or a `Connection` (it doesn't really matter to jOOQ)

> 2\. How can jOOQ will know that it is in transaction because the only code I see is `createConnection`. It is like this method needs to be wired up.

jOOQ isn't supposed to know. jOOQ doesn't need to know. That's the beauty of it. If you're using JDBC with Spring or Micronaut *directly*, JDBC clients also don't know about any transactions, nor do they need to know. The whole transactionality is hidden from clients.

> 3\. Should I open another issue for this to conversation?

Not necessarily, because there's nothing that needs to be done on the jOOQ side, so that other issue would also be claosed.

jOOQ will eventually have an R2DBC backed transaction API that allows for using *unmanaged* transactions, just like jOOQ has a JDBC backed transaction API that allows for using *unmanaged* transactions.

But in the world of *managed* transactions, jOOQ *MUST* be oblivious of any transaction state.

**Now back to my question:**

Given that R2DBC is already supported by Micronaut, and managed transactions are already supposed to work there, what's the hold up of injecting a `ConnectionFactory` that proxies such a managed transaction to jOOQ? In other words, how do these examples work?
https://micronaut-projects.github.io/micronaut-r2dbc/1.0.x/guide/#transactionManagement

**Comment by sbuettner** [comment]
Please ignore if its not related but trying to get Spring transactions get to work with JOOQ we are using the following `DSLContext` configuration:
```@Bean
    fun dslContext(connectionFactory: ConnectionFactory): DSLContext =
        DSL.using(
            DefaultConfiguration()
                .set(TransactionAwareConnectionFactoryProxy(connectionFactory))
                .set(SQLDialect.POSTGRES)
                .set(
                    Settings()
                        .withBindOffsetDateTimeType(true)
                        .withBindOffsetTimeType(true)
                )
        ).dsl()
```

and we are seeing the the R2DBC based connectionpool is just working fine when providing new connections but the transactions are not rolled-back properly: 
```
try {
            transactionalOperator.execute { tx ->
                insertData().flatMap {
                    RuntimeException("Hello").toMono<Any>()
                }
            }.blockLast()
        } catch (e: Exception) {
            // TX failed
        }
```

The rollback is issued correctly on the `TransactionalOperator` but the insertData() method is receiving its own (non-transactional) R2DBC connection and the insert is committed. It seems like the reactor context based transaction management doesnt work with the reactive stream based JOOQ implementation.

**Comment by JohannesZick** [comment]
@lukaseder I think I have found the problem here. I was working on Spring, not Micronaut, but I assume the principle is the same.

Reactor has a concept of "context", which would be the analogous concept to thread-local from the old world. This is what signals the presence or absence of a transaction. It's obviously implemented very differently, but it serves the same function.

Unfortunately, there is no such concept in the reactive streams spec. And this is where things break. You need a continuous chain of operations (or subscribers) that pass on the Reactor context. The `ConnectionFactory` might be a Reactor type, and the operations you perform on the results might be too. But the `Subscriber` that jOOQ uses to work with the `Connection` is not context aware. So the `ConnectionFactory` does not get the Reactor context and does not see the transaction.

This is a severe lack in the reactive streams API, it seems, and I have no idea yet how to fix this in jOOQ.

**Comment by lukaseder** [comment]
@sbuettner: Why do you block in a reactive context? That doesn't seem right. It also doesn't seem like the correct way to roll back a transaction. Without having tried this, I'm guessing you should perform rollbacks in a `Flux` operation, e.g. `doOnError()`

**Comment by lukaseder** [comment]
> This is a severe lack in the reactive streams API

I don't think the streams API should be transaction aware

> it seems, and I have no idea yet how to fix this in jOOQ.

... nor should jOOQ be. It's all about the `ConnectionFactory`. You'll find some examples on this page:
https://spring.io/blog/2019/05/16/reactive-transactions-with-spring

(look for `TransactionalOperator`). I'll try to come up with some examples some time soon

**Comment by sbuettner** [comment]
@lukaseder Its a unit test.

**Comment by JohannesZick** [comment]
> I don't think the streams API should be transaction aware

Neither do I. But it should have some concept like the Reactor context. You have to pass around a reference to the transaction. You can do so explicitly, or you can have it implicitly provided. The `ThreadLocal` is how to do it implicitly in the JDBC world. And the Reactor context is how you do it in Reactor land. In R2DBC/Reactive Streams, there is nothing. You have no API to do this in a generic way. The same problem comes up when you want e.g. references to traces for monitoring.

**Comment by cemo** [comment]
I am not expert on this land but when I check micronaut-data project which was implemented for their own repository concept I noticed there was something like others mentioned.

https://github.com/micronaut-projects/micronaut-data/blob/0a3259bc73dc842044c0db8a9c784eaa1910412f/data-tx/src/main/java/io/micronaut/transaction/interceptor/TransactionalInterceptor.java#L144-L149

There is context passed between methods.

https://github.com/micronaut-projects/micronaut-data/blob/de6948dc527cdafb11181770c8b25022cac9dc10/data-r2dbc/src/main/java/io/micronaut/data/r2dbc/operations/DefaultR2dbcRepositoryOperations.java#L324-L335

I did not understand how to get it completed for jOOQ and I could not complete my PR since my knowledge is poor there.

https://github.com/micronaut-projects/micronaut-sql/pull/545

**Comment by cemo** [comment]
> jOOQ 3.15 has a `DSL.using(io.r2dbc.spi.Connection)` and related APIs, so that's not what I meant. I meant executing the query with jOOQ, but using an R2DBC Connection that is not managed by jOOQ. It's the exact same thing you can do with JDBC as well. jOOQ isn't opinionated about connection lifecycle management, or transaction management. As soon as you give jOOQ a connction (R2DBC or JDBC), it can work with that.

@lukaseder I am trying to understand your statements. You basically say that we need to pass connection to jOOQ. But in the interceptor world there is not a direct access to instance fields of the intercepted object. The only thing in the moment of interception is that I have a reference to called method. As others stated we need a contract and implemented in 3rd party libraries. 

I mean as in the example of I shared in my previous message, If you can provide a contract such as attributes on  `context`, we can implement on 3rd party libraries. If this will not work for you, would you please write a pseudocode for me please? Since I am really stuck there and I can not move forward.

**Comment by lukaseder** [comment]
> @lukaseder I am trying to understand your statements.

Well, I'm trying to follow this thread (again), as it mixes Spring and Micronaut, which might be the same, or might not be :) But I think the following holds true in any case:

> You basically say that we need to pass connection to jOOQ. But in the interceptor world there is not a direct access to instance fields of the intercepted object.

Currently, jOOQ *does not care* about your transactions. It expects a transactional `ConnectionFactory` or `Connection`. The question you should ask yourselves is: How would you get transaction support with R2DBC today? Once it's possible to get a transactional R2DBC *"whatever"*, jOOQ can operate on that R2DBC *"whatever"* in a transactional way.

I don't know what an "interceptor" is, nor why jOOQ should worry about that. I'm sorry, I don't understand what you're stuck with, or how I can be of any further help here. Have you considered asking Micronaut maintainers about their opinion?

> If this will not work for you, would you please write a pseudocode for me please? Since I am really stuck there and I can not move forward.

Would you be interested in a commercial support contract? Whom would I send a quote with my hourly rates to? I'd be happy to help you further here.

**Comment by JohannesZick** [comment]
I think that is correct. There is no common interface between libraries that allows for a transaction implementation.

Are there plans to extend the jOOQ transaction API to support R2DBC connections though? It's not what the ticket asks for, I know, but the next best thing. And it seems feasible to me at first glance. Only jOOQ is involved in controlling connection usage, so I don't see major problems.

I don't know the jOOQ codebase very well, but I'd be willing to help out as much as I can.

**Comment by lukaseder** [comment]
> Are there plans to extend the jOOQ transaction API to support R2DBC connections though?

Yes, there's a task in here: https://github.com/jOOQ/jOOQ/issues/11717. However, if using a platform with managed transactions (Spring Boot, Micronaut, Jakarta EE), it's usually best not to use jOOQ's transaction API, but those managed transactions, instead. This is true for JDBC as well as for R2DBC backed jOOQ code.

> I don't know the jOOQ codebase very well, but I'd be willing to help out as much as I can.

This isn't about codebase or implementation, but about API design in the context of existing API and plans for evolving the API. I have it as a high priority for a near-future minor release...

**Comment by JohannesZick** [comment]
Thanks! Since reactive streams is very much about a functional code style, I believe the jOOQ transaction API might be a better fit.

For working with Spring, we ended up at this workaround so far. Maybe it will help someone else too.
```kotlin
class DSLAccess(private val databaseClient: DatabaseClient) {

    private val settings = Settings()
        .withBindOffsetDateTimeType(true)
        .withBindOffsetTimeType(true)

    private fun Connection.dsl() =
        DSL.using(this, SQLDialect.POSTGRES, settings)

    fun <T : Any> withDSLContextMany(block: (DSLContext) -> Publisher<T>): Flux<T> =
        databaseClient.inConnectionMany { con -> block(con.dsl()).toFlux() }

    fun <T : Any> withDSLContext(block: (DSLContext) -> Mono<T>): Mono<T> =
        databaseClient.inConnection { con -> block(con.dsl()) }
}
```
The DatabaseClient allows creation of a transaction aware connection. By wrapping the jOOQ Publishers completely in Reactor, the Context will be passed down and the transaction works as expected.

**Comment by fcabouat** [comment]
Hi,

If anyone is interested with another example : my own flavor with using the factory + wrapping it in a TransactionAwareConnectionFactoryProxy + Kotlin coroutines interop.

I inject this helper in my DAOs/Adapters.

```kotlin
import io.r2dbc.spi.ConnectionFactory
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.emitAll
import kotlinx.coroutines.flow.flow
import kotlinx.coroutines.reactive.asFlow
import kotlinx.coroutines.reactive.awaitFirstOrNull
import kotlinx.coroutines.reactive.awaitSingle
import org.jooq.DSLContext
import org.jooq.Record
import org.jooq.ResultQuery
import org.jooq.RowCountQuery
import org.jooq.SQLDialect
import org.jooq.conf.Settings
import org.jooq.impl.DSL
import org.springframework.r2dbc.connection.TransactionAwareConnectionFactoryProxy

class JooqHelperImpl(connectionFactory: ConnectionFactory) :
    JooqHelper {

    private val transactionAwareConnectionFactoryProxy = TransactionAwareConnectionFactoryProxy(connectionFactory)

    private val settings = Settings()
        .withBindOffsetDateTimeType(true)
        .withBindOffsetTimeType(true)

    private suspend fun jooqDSL(): DSLContext {
        val conn = transactionAwareConnectionFactoryProxy.create().awaitSingle()
        return DSL.using(conn, SQLDialect.POSTGRES, settings)
    }

    override suspend fun jooqExecNoResult(jooqExecQuery: RowCountQuery) {
        jooqDSL().attach(jooqExecQuery)
        jooqExecQuery.awaitFirstOrNull()
    }

    override suspend fun jooqExecRowsCount(jooqExecQuery: RowCountQuery): Int {
        jooqDSL().attach(jooqExecQuery)
        return jooqExecQuery.awaitSingle()
    }

    override suspend fun <T : Record> jooq1(jooqQuery1: ResultQuery<T>): T {
        jooqDSL().attach(jooqQuery1)
        return jooqQuery1.awaitSingle()
    }

    override fun <T : Record> jooqMany(jooqQueryMany: ResultQuery<T>): Flow<T> = flow {
        jooqDSL().attach(jooqQueryMany)
        emitAll(jooqQueryMany.asFlow())
    }
}
```

Regards,

**Comment by k163377** [comment]
Comment for those who are having trouble with `Transactional` not working.
You can get `Transactional` to work by executing a query on a `Connection` managed by `Spring` `TransactionManager` as follows.

```kotlin
import io.r2dbc.spi.ConnectionFactory
import kotlinx.coroutines.reactive.awaitSingle
import kotlinx.coroutines.reactor.awaitSingleOrNull
import org.jooq.generated.tables.records.FooTableRecord
import org.jooq.generated.tables.references.FOO_TABLE
import org.jooq.impl.DSL
import org.springframework.r2dbc.connection.ConnectionHolder
import org.springframework.stereotype.Repository
import org.springframework.transaction.reactive.TransactionSynchronizationManager
import reactor.core.publisher.Mono
import java.lang.RuntimeException

@Repository
class Repository(private val cfi: ConnectionFactory) {
    suspend fun save(value: String): FooTableRecord {
        val holder: ConnectionHolder = TransactionSynchronizationManager.forCurrentTransaction()
            .mapNotNull { it.getResource(cfi) as ConnectionHolder? }
            .awaitSingleOrNull() ?: throw RuntimeException("Transaction does not begin.")

        val ctxt = DSL.using(holder.connection)

        return Mono.from(ctxt.insertInto(FOO_TABLE).values(value).returning())
            .map { it.into(FOO_TABLE) }
            .awaitSingle()!!
    }
}
```

**Comment by ericghara** [comment]
Even though this issue is closed I wanted to close the loop, for others who stumble upon this discussion (as I did).  Milestone 3.17 implemented the reactive transaction API.  For more details about it take a look at [#13502](https://github.com/jOOQ/jOOQ/issues/13502) and Lukas' [blog post](https://blog.jooq.org/nested-transactions-in-jooq/).  While it's not the only way to go, hopefully for most use cases it obviates the need for these workarounds.

**Comment by k163377** [comment]
I felt that some people did not want to control it with annotations, so I added a comment on how to use `TransactionalOperator` (although I feel that [`jOOQ` style](https://blog.jooq.org/nested-transactions-in-jooq/) is more functional in this case).
https://github.com/jOOQ/jOOQ/issues/12218#issuecomment-1213929029
