### ISSUE TITLE
Avoid maven per-execution configuration in manual, if unnecessary

### ISSUE THREAD

**Issue by ylemoigne** [jOOQ/jOOQ#12235]
In 3.15 documentation,

In part `6.29. Running the code generator with Maven`
The configuration is inside the execution block

```
  <executions>
    <execution>
      <id>jooq-codegen</id>
      <phase>generate-sources</phase>
      <goals>
        <goal>generate</goal>
      </goals>
      <configuration>
        ...
      </configuration>
    </execution>
  </executions>
```

In part `6.1. Configuration and setup of the generator`, section `Integrate generation with Maven`
Execution goal do not define the phase `generate-sources`
The `configuration` is defined outside the execution.

I don't know if the difference change anything.
And I don't know which one to use.

**Comment by lukaseder** [comment]
Thanks for your message.

Yeah, huh! I never thought it would matter, really, for the jOOQ documentation. The question is: Do you require a per-execution configuration or a per-plugin one? Or both? I don't think it matters for any of the examples. There are some subtle differences, which I cannot recall.

I'll remove the per-execution configuration to avoid confusion, because we don't document that scenario (where you have multiple executions).

**Comment by lukaseder** [comment]
Will be fixed with the next manual build. Thanks again for your report.
