### ISSUE TITLE
Auto generate primary key ID

### ISSUE THREAD

**Issue by lianbitangjin** [jOOQ/jOOQ#12271]
### Use case:

Hello, jooq author, I am a developer from China. I think in jooq, when I want to insert, I can automatically generate ID for the new data. 
### Possible solution you'd like to see:

The ID generation algorithm can be a distributed ID algorithm, similar to snowflake algorithm or UUID algorithm

### Possible workarounds:

Please describe the possible workarounds you've implemented to work around the lacking functionality.

### Versions:

- jOOQ:
- Java:
- Database (include vendor):
- OS:
- JDBC Driver (include name if inofficial driver):

**Comment by lukaseder** [comment]
Thank you very much for your message.

The best way to achieve this kind of functionality with jOOQ's `UpdatableRecord` API is to implement a `RecordListener`, see:
https://www.jooq.org/doc/latest/manual/sql-execution/crud-with-updatablerecords/crud-record-listener/

A general purpose implementation could be done via a `VisitListener` as well, but it would be much harder to achieve. We currently don't have plans of implementing client side ID generation algorithms. Most jOOQ users use the RDBMS-specific IDENTITY support, and if client side ID generation is required, it's usually not a bad idea to do this in client code, rather than from within jOOQ.
