### ISSUE TITLE
Given a jooq query how do find the tables involved?

### ISSUE THREAD

**Issue by lemmingapex** [jOOQ/jOOQ#12279]
### Given a jooq query how do find the tables involved?

I am currently using a [DefaultExecuteListener](https://github.com/jOOQ/jOOQ/blob/main/jOOQ/src/main/java/org/jooq/impl/DefaultExecuteListener.java) to hook into the jooq query lifecycle. How do I reliably determine if the query is a select statement and what tables (org.jooq.Table) are involved in the select?
```java
@Override
public void executeStart(ExecuteContext context) {
    Set<Table> tables = new HashSet<>();
    if (context.query() != null) {
        context.query(); // How do you check if this is a select statement and retrieve the tables involved?
    }
}
```

### Versions: 

- jOOQ: 3.14.7
- Java: 15.0.1
- Database (include vendor): H2
- OS: macOS

**Comment by lukaseder** [comment]
See my answer to your Stack Overflow question here: https://stackoverflow.com/q/68628584/521799

**Comment by lemmingapex** [comment]
Thank you for your excellent response @lukaseder.  This is very helpful.  I'm going to try my best to explain the true architectural issue we are having on our program and ask how you might solve the problem.

We are utilizing the H2 database for our applications.  Our application relies heavily on H2 database VIEWS. We leverage VIEWS so our application code can be greatly simplified. Performance has greatly suffered by using views instead of tables however. This is primarily due to two reasons.  First, we were utilizing indexes on our tables and now do not get those benefits when querying VIEWS.  Second, each and every query to a VIEW has to execute all sub-SELECTS, JOINs, etc.  Many database engines provide MATERIALIZED VIEWs: this is their solution to significantly improve performance of views. From my understanding, a MATERIALIZED VIEW is more similar to a table (or cached result) and can be indexed.  Unfortunately H2 does not support these yet. [See the H2 issue here](https://github.com/h2database/h2database/issues/3159). We use JOOQ heavily and are considering if we can leverage it to provide a pseudo-materialized views.  This idea primarily falls into the category: "What if your database doesn’t support these things?"
 
I will certainly explain our current approach to you, but I first wanted to get your thoughts.  You are a coding guru and we are looking to your mastery, experience, and knowledge for ideas.  I was wondering how your would approach this need?  Thank you for your time and thoughts.

**Comment by lukaseder** [comment]
I was not aware of views being an impediment to using indexes on the underlying columns in H2. I've obviously been spoiled by Oracle's optimiser in the past, but I don't think most other modern RDBMS suffer from such a problem. Predicates should be pushed down into views, derived tables, etc. That doesn't seem like such a hard SQL transformation.

So, rather than investigating indexes on views or materalising views, which are overengineering this very simple problem, how about looking into alternative RDBMS?

Anyway. Even your second question is not your actual question (see https://xyproblem.info) ;-) because you didn't explain why you need views in the first place, so I'm not convinced that the most efficient way to help you is discuss materialized views. Since you're using jOOQ heavily, you might be able to implement your "application simplification" in a different way.

So, how and why are you using views for "application simplification"?

**Comment by lemmingapex** [comment]
In your stackoverflow answer, can you elaborate on how you would associate invocations of VisitListener with an invocation of ExecuteListener on the same query?   I need the tables involved at execution time.  Thanks.
