### ISSUE TITLE
Remove empty groupBy

### ISSUE THREAD

**Issue by cdalexndr** [jOOQ/jOOQ#12285]
### Expected behavior
No `group by` in query
### Actual behavior
`group by ()`, causing query to fail
### Steps to reproduce the problem

```
dsl.select(...)
...
.groupBy(emptyList())
```

### Versions

- jOOQ: 3.14.8
- Java: 11
- Database (include vendor): Postgres 12.4
- OS: Win 10
- JDBC Driver (include name if inofficial driver):

**Comment by lukaseder** [comment]
Thank you very much for your message. The syntax in question is from ISO/IEC 9075-2:2016(E) 7.13 &lt;group by clause>:

```
<empty grouping set> ::=
  <left paren> <right paren>
```

In SQL:1999, it was still called "grand total". There is no other way in jOOQ to specify a grand total this way, other than passing an explicitly empty list to the `GROUP BY` clause. So, this works by design.

Other clauses have default behaviour that deviates from just ignoring the call, such as e.g. the `SELECT` list, which can never really be empty, so passing an empty list to `SELECT` is the same thing as projecting all the columns (explicitly, or with an `*` if the columns are unknown).
