### ISSUE TITLE
Some stumbling blocks when using jOOQ 3.15 and Kotlin

### ISSUE THREAD

**Issue by strindberg** [jOOQ/jOOQ#12347]
### Expected behavior
This is not so much a bug report as a record of our experiences trying to use the fantastic new mapping possibilities (multiset) of 3.15 in our Kotlin code base. Although it works very well for us, we had some initial problems getting it to work, and perhaps by documenting our experiiences here, the implementation and/or documentation can be improved.

This is our (example) data model:

```sql
CREATE TABLE parent (
    id bigint  NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name     text    NOT NULL,

    PRIMARY KEY (id)
);

CREATE TABLE child (
    id bigint  NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    parent_id bigint NOT NULL,
    name     text    NOT NULL,

    PRIMARY KEY (id),
    FOREIGN KEY (parent_id) references parent (id)
);
```

Our Java model looks like this:

```java
public class Parent {
    private Long id;
    private String name;
    private List<Child> children;
}

public class Child {
    private Long id;
    private String name;
}
```

In Java, the following code works well for the simple case of reading a Parent object from the database:

```java
    Parent getById(Long id) {
        return dsl.select(
                        PARENT.ID,
                        PARENT.NAME,
                        multiset(
                                select(CHILD.ID, CHILD.NAME)
                                        .from(CHILD)
                                        .where(CHILD.PARENT_ID.eq(PARENT.ID))
                        ).as("children")
                )
                .from(PARENT)
                .where(PARENT.ID.eq(id))
                .fetchOne()
                .into(Parent.class);
    }
```

### Actual behavior

Our Kotlin model looks like this:

```kotlin
data class Parent(val id: Long? = null, val name: String, val children: List<Child>)

data class Child(val id: Long? = null, val name: String)
```

In Kotlin, the closest we have come to the Java code to read a Parent class from the database is this:

```kotlin
    fun getById(id: Long): Parent? =
        dsl.select(
            PARENT.ID,
            PARENT.NAME,
            multiset(
                select(CHILD.ID, CHILD.NAME)
                    .from(CHILD).where(CHILD.PARENT_ID.eq(PARENT.ID))
            ).`as`("children").convertFrom(List::class.java) { it.map { s -> Child(s.value1(), s.value2()!!) } },
        )
            .from(PARENT)
            .where(PARENT.ID.eq(id))
            .fetchOne()
            ?.into(Parent::class.java)
```

I will enumerate the attemtps we made to find something as simple as the Java version and why they did not work.

1) 
```kotlin
            multiset(
                select(CHILD.ID, CHILD.NAME)
                    .from(CHILD).where(CHILD.PARENT_ID.eq(PARENT.ID))
            ).`as`("children")
```

This does not work because although "children" becomes a List in the `Parent` object, the child objects are not `Child`, but `Map<String, Any?>`, i.e. the type information is somehow lost.

2)
```kotlin
            multiset(
                select(CHILD.ID, CHILD.NAME)
                    .from(CHILD).where(CHILD.PARENT_ID.eq(PARENT.ID))
            ).`as`("children").convertFrom { it.map { s -> Child(s.value1(), s.value2()!!) } },
```

This does not work because without the explicit argument that the "children" attribute should be a `List`, we get the error:

```
Caused by: org.jooq.exception.DataTypeException: No Converter found for types org.jooq.Converters$UnknownType and java.util.List
	at org.jooq.impl.Tools.converterOrFail(Tools.java:1216)
	at org.jooq.impl.Tools.converterOrFail(Tools.java:1225)
	at org.jooq.impl.AbstractRecord.get(AbstractRecord.java:351)
	at org.jooq.impl.DefaultRecordMapper$ImmutablePOJOMapper.set(DefaultRecordMapper.java:1146)
	at org.jooq.impl.DefaultRecordMapper$ImmutablePOJOMapper.mapNonnested(DefaultRecordMapper.java:1137)
	at org.jooq.impl.DefaultRecordMapper$ImmutablePOJOMapper.map(DefaultRecordMapper.java:1124)
```

3)
```kotlin
            multiset(
                select(CHILD.ID, CHILD.NAME)
                    .from(CHILD).where(CHILD.PARENT_ID.eq(PARENT.ID))
            ).`as`("children").convertFrom(List::class.java) { it.map(mapping(::Child)) },            
        )
```

This does not work, and in fact doesn't even compile, because the `Child` record has its `name` field declared as `var name: String?`, even though the `name` column is declared as non-null.

I have read the discussion in #10212, and I understand the reasons why jOOQ so far has prioritized "correct" over "simple" when it comes to mapping non-nullable columns to nullable Kotlin types. However, I think an example like this clearly shows that in the context of explicit ORM-mapping, the behavior is rather surprising, and might trip up developers who are new to jOOQ.

4)
```kotlin
            multiset(
                select(CHILD.ID, CHILD.NAME)
                    .from(CHILD).where(CHILD.PARENT_ID.eq(PARENT.ID))
            ).`as`("children").convertFrom(List::class.java) { it.map { s -> Child(s.value1(), s.value2()) } },
```

This fails for the same reason as point 3) above: even though `name` is non-nullable in the database, the generated Kotlin record field is nullable.

### Steps to reproduce the problem
Reproduce these problems by generating Kotlin code from the above database definitions, and implement the repository code as given above.

### Versions

- jOOQ: 3.15.1
- Java: 11
- Database (include vendor): Postgres 13
- OS: Mac, Linux
- JDBC Driver (include name if inofficial driver): Postgres jdbc 42.2.23

**Comment by lukaseder** [comment]
Thanks for your report. Coincidentally someone created this stack overflow question just now: https://stackoverflow.com/q/68903323/521799

And it seems to discuss the exact same problem, namely your lack of nullability in your data classes. Can you try this, please:

```kotlin
data class Parent(val id: Long?, val name: String?, val children: List<Child>)
data class Child(val id: Long?, val name: String?)
```

And check which ones of your questions remain open?

> However, I think an example like this clearly shows that in the context of explicit ORM-mapping, the behavior is rather surprising, and might trip up developers who are new to jOOQ.

"clearly" is one of those attributes right next to "just" (as in "just implement XYZ") 😅. If all of this shows one thing "clearly", then it's that no solution will make everyone happy. Just imagine you'd spend 3 hours debugging why on earth you're getting a NPE because of a left join and jOOQ's wrong promise of that left join never producing nulls.

(I keep feeling that using the `JavaGenerator` instead of the `KotlinGenerator` might do the trick, because that `T!` type isn't so bad after all, when using jOOQ)

**Comment by strindberg** [comment]
Making the properties nullable indeed solves the problems 3) and 4), since it was the nullability mismatch that was the issue. This is of course not a solution in our real application, as we then spread the nullability to the whole application, even though we know these properties to be non-null.

Problems 1) and 2) are not affected by the change in nullability.

**Comment by lukaseder** [comment]
> This is of course not a solution in our real application, as we then spread the nullability to the whole application, even though we know these properties to be non-null.

I understand this is the goal here. As of now, there are workarounds, including `PARENT.NAME.convertFrom { it!! }` and others, to turn a `Field<String?>` into a `Field<String>`

**Regarding 1**

I'm not sure what you mean by "type information being lost". You didn't provide it. Why did you expect this to be mapped to `List<Child>`?

Did you mean to write this, instead?

```kotlin
multiset(
    select(CHILD.ID, CHILD.NAME)
    .from(CHILD).where(CHILD.PARENT_ID.eq(PARENT.ID))
).`as`("children").convertFrom { it.map(mapping(::Child)) }
```

**Regarding 2**

The code in 2) works for me, as presented there. You mentioned:

> This does not work because without the explicit argument that the "children" attribute should be a List, we get the error

I don't see what you refer to when you say "attribute should be a list". You use `.convertFrom(List::class.java)` elsewhere, but not in 2).

**Summary**

I think this can be concluded with:

1. There are some improvements to ergonomics in general (not just in kotlin), because as soon as the compiler trips, the error messages are far from helpful. Juggling these types isn't trivial in any language. Hard to say if this can be fixed, but good to keep in mind
2. There's a very popular feature request to improve the nullability experience in kotlin allowing users to ignore the inaccuracies caused by the SQL language in some way. This is all covered in https://github.com/jOOQ/jOOQ/issues/10212

So, I don't think there's any remaining (or actionable) `MULTISET` related issue here.

**Comment by strindberg** [comment]
> **Regarding 1**
> 
> I'm not sure what you mean by "type information being lost". You didn't provide it. Why did you expect this to be mapped to `List<Child>`?

The point of my Java example was that it works in Java: "children" becomes a List of Child with no further mapping. For some reason, it does not work under Kotlin. Look again at the Java example I provided.

> **Regarding 2**
> 
> I don't see what you refer to when you say "attribute should be a list". You use `.convertFrom(List::class.java)` elsewhere, but not in 2).

The problem in 2) was exactly the fact that the extra argument '(List::class.java)' must be provided. Why is that? "children" is a List of Child, why should I have to point this out again?

**Comment by lukaseder** [comment]
Where in 1 does it become a List of Child?

![image](https://user-images.githubusercontent.com/734593/130754563-5a1b48ef-2263-41e5-94a4-02f68f231a61.png)

> The problem in 2) was exactly the fact that the extra argument '(List::class.java)' must be provided. Why is that? "children" is a List of Child, why should I have to point this out again?

I don't know. Why are you doing it? Why not follow the example I provided, instead?

**Comment by lukaseder** [comment]
> > The problem in 2) was exactly the fact that the extra argument '(List::class.java)' must be provided. Why is that? "children" is a List of Child, why should I have to point this out again?
> 
> I don't know. Why are you doing it? Why not follow the example I provided, instead?

I think a few issues are being mixed here... I can't reproduce the stack trace you provided. Somehow, you're using the classic reflection approach here, instead of the new one using reflection free lambdas.

With reflection, thanks to generic type erasure, the runtime will require a few additional type hints. In some cases, the `<U>` type of a `Converter<T, U>` needs to be provided explicitly, see https://github.com/jOOQ/jOOQ/issues/11823. But again, I don't see how this should be relevant here, because the approach using `Records.mapping(::ConstructorReference)` should not be using reflection in the first place.

There might be a bug that caused reflection to be used (happy to review a separate issue, ideally with an MCVE, template here: https://github.com/jOOQ/jOOQ-mcve).

**Comment by strindberg** [comment]
OK, I'll try to isolate what I see into separate issues, and set up the MVCEs.

**Comment by lukaseder** [comment]
> OK, I'll try to isolate what I see into separate issues, and set up the MVCEs.

Thanks a lot, greatly appreciated!
