### ISSUE TITLE
distinctOn + order by desc doesn't work

### ISSUE THREAD

**Issue by thiagosouzacoelho** [jOOQ/jOOQ#12369]
### Expected behavior
```java
Field<?> distinctOn = field("(timestamp at time zone ?)::date", String.class, timezoneId);
Field<?> one = field("timestamp at time zone ?", String.class, timezoneId);
Field<?> two = field("timestamp");

dslContext
                .select(one, two)
                .distinctOn(distinctOn)
                .from(MYTABLE)
                .where(MYTABLE.TIMESTAMP.greaterThan(Timestamp.from(Instant.now())))
                .orderBy(distinctOn.desc())
                .fetch();
```

I want to inverse the order to apply the distinct on. If I try the above code, I get an error: 

> ERROR: SELECT DISTINCT ON expressions must match initial ORDER BY expressions\n  Position: 38"

As we can see above, I'm using the same Field object in the orderBy. If I remove the `desc`, it still doesn't work. If I remove the orderBy completely, it works but in an ascending order, which is not desired.

If instead of `fetch()` I call `getQuery().toString()`, the query returned is valid and I can run it on Postgres. If I pass the String to DSLContext.fetch, the method works.

### Actual behavior

An error.

### Versions

- jOOQ: 3.9.1
- Java: 1.8
- Database (include vendor): PostgreSQL 10.9 (On AWS)
- OS: Linux

**Comment by lukaseder** [comment]
Thank you very much for your request.

This is because of your using a bind variable for the time zone ID. While a bind variable is recognised as a constant value by most RDBMS, two references to the same bind value cannot be identified as the same thing by most SQL parsers, even if in your jOOQ code, they are "clearly" the same expression.

The solution here is to use inline values instead, using `DSL.inline()`:
https://www.jooq.org/doc/latest/manual/sql-building/bind-values/inlined-parameters

This is what you did, implicitly, by calling `toString()` on your query. Specifically:

```java
Field<?> distinctOn = field("(timestamp at time zone {0})::date", String.class, DSL.inline(timezoneId));
```

I hope this helps
