### ISSUE TITLE
Add a constructor to generated table-records to create a record from another similar RecordN<...> object 

### ISSUE THREAD

**Issue by azhurtbayev-klikatech** [jOOQ/jOOQ#12370]
### Use case:

At the moment when we use `dsl.insertInto(table).set(tableRecord).returning()` it returns a native RecordN object (not a table-record). We want to quickly create a table-record out of this RecordN object.
When generated, table-record already has a constructor that takes N fields. But using that constructor doesn't look "nice and clear" (especially when there are more than 5 fields in a record). Adding a new constructor will simplify this case.

**Comment by lukaseder** [comment]
I can see the occasional usefulness of a `Record[N]` subtype to accept `Record[N]` arguments in their constructors, assuming `<recordsImplementingRecordN/>` is active in the code generator.

However, I don't think you need to wait for such a feature:

1. You haven't shown what `table` is. If `table` is a reference to a generated `Table<R>`, then the `returning().fetchOne()` call should produce a record of type `R`, so your generated record
2. Otherwise, you can always call `record.into(table)` to convert any record into that table's `R` record
3. Unless you're doing something additional that you haven't shown, you can just call `tableRecord.insert()`, and get the desired behaviour, too

**Comment by azhurtbayev-klikatech** [comment]
I'm not sure, but probably I have an issue with reactive calls.
I have the following code:
```
Mono.from(
    dsl.insertInto(MY_TABLE)
       .set(record)
       .returning()
)
```
It does successfully compile with correct generic type (Mono<MyTableRecord>), but then I get a ClassCastException during runtime saying cannot cast RecordImpl9 to MyTableRecord.
My guess is that something is not converted in Publisher.subscribe() method.

**Comment by lukaseder** [comment]
Thanks for the info, @azhurtbayev-klikatech. I can reproduce that, that's just a bug: https://github.com/jOOQ/jOOQ/issues/12373

As a workaround, use `returningResult()` instead of `returning()`.

I'm closing this issue here. The issue suggests new API as a solution to what is really just a bug. I don't think the suggested API will be very useful.
