### ISSUE TITLE
Generated Code (PostgreSQL) does not compile

### ISSUE THREAD

**Issue by narc-Ontakac2** [jOOQ/jOOQ#12395]
### Expected behavior
Generated code compiles.

### Actual behavior

```java
@Override
public List<UniqueKey<Test1Record>> getUniqueKeys() {
    return Arrays.asList(Keys.TEST1_F1_KEY);
}
```

gives an error:

> error: method does not override or implement a method from a supertype

### Steps to reproduce the problem

```sql
CREATE TABLE test1 (f1 INT, UNIQUE(f1));
```

### Versions

- jOOQ: 3.15.2
- Java: 16.0.1
- Database (include vendor): PostgreSQL
- OS: Ubuntu 20
- JDBC Driver: 42.1.4'

I worked around by going back to 3.13.6, which simply does not have getUniqueKeys.

**Comment by lukaseder** [comment]
Thanks for your report. Can you please make sure you're using the same jOOQ version to compile your code as you're using to generate the sources? It's a common user error, see also the FAQ: https://www.jooq.org/faq

**Comment by lukaseder** [comment]
`Table.getUniqueKeys()` was added in jOOQ 3.15, for the record: https://github.com/jOOQ/jOOQ/issues/10883

**Comment by narc-Ontakac2** [comment]
I have no idea how an old version could have sneaked in.This was a newly set up project. The only explanation could be that another component brought in its own jOOQ. I will check this on monday.

**Comment by lukaseder** [comment]
Usually, this is because of a managed jOOQ runtime library dependency, such as the one introduced by Spring Boot, which is not affected by your explicit jOOQ code generation Maven or Gradle plugin dependency. Here's an article showing how to override Spring Boot's managed jOOQ version: https://blog.jooq.org/how-to-use-jooqs-commercial-distributions-with-spring-boot

If you're using Maven, `mvn dependency:tree` can help find out whose old jOOQ version your using.

**Comment by narc-Ontakac2** [comment]
I have checked and it is actually spring boot (spring-boot-starter-jooq) that brings in a different version than what I have configured for buildscript. Thanks.
