### ISSUE TITLE
question about Schema diff

### ISSUE THREAD

**Issue by Mattyou777** [jOOQ/jOOQ#12477]
### Your question:

How can I determinate functions changes in schemas? I'm use org.jooq.Meta#migrateTo(org.jooq.Meta) and get diff, but without functions diff. Are you planning this feature, if it's not supported now? 

### Versions:

- jOOQ:3.14.15
- Java:11
- Database (include vendor):PostgreSQL 9.5, 12
- OS:PostgreSQL
- JDBC Driver (include name if inofficial driver):

**Comment by lukaseder** [comment]
Thank you very much for your message. We don't support function and procedure meta data in our API yet. jOOQ 3.15 finally supported DDL on those types of objects (see all the work in https://github.com/jOOQ/jOOQ/projects/7). Meta data is on the roadmap but it might still take a while as there are a lot of prerequisites to get right in order to get a diff:

- Getting a hold of function / procedure source code via all the various meta sources
- Getting a hold of signature information in the absence of source code, or if we can't parse it
- More parse support

There might be more.
