### ISSUE TITLE
Log warning when DSL.val(Object, Class) is being used with an unsupported data type

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#12471]
Users keep running into "regressions" when their code that uses `val(x, UserType.class)` stops working, when in fact it was never really supposed to work, e.g.:
https://stackoverflow.com/q/69368340/521799

We could log a warning if this API usage produces a `DataType` from the internal static data type registry (which might be removed in the future).

Tasks:

- [ ] Log a warning when such a type is being used
- [ ] Possibly deprecate the `Class` API in favour of the `DataType` API? TBD

----
See also: 
- https://github.com/jOOQ/jOOQ/issues/5713
- https://github.com/jOOQ/jOOQ/issues/7473
- https://github.com/jOOQ/jOOQ/issues/12470

**Comment by juriad** [comment]
We actually came across another place we often use `Class` instead of `DataType`: `Table.field(Name, Class)` and `Table.field(String, Class)`. The reasoning is that we don't want to get `Field<?>`, so we provide `Class<T>` to get `Field<T>`. 

```
// compare these two; the first looks safer to me
Field<Integer> abc = table.field("abc", Integer.class);
Field<Integer> abc = (Integer) table.field("abc");
```

The method `Table.field(Name, Class)` does more than a simple check and Java cast; it `coerce`s the field (in `FieldsImpl`), which also does a data type lookup (in `AbstractField`):
```
    public final <Z> Field<Z> coerce(Class<Z> type) {
        return this.coerce(DefaultDataType.getDataType((SQLDialect)null, type));
    }
```

In comparison to `DSL.val(Object, Class)`, here the data type registry should already be populated (the table with such field already exists anyway). I don't think that relying on the internal data type registry is good anywhere.

If a warning is going to be added, we would like to see similar warnings on all methods that accept `Class` as an overload to `DataType`. Maybe pushing it down to  `DefaultDataType.getDataType` could be preferable?

**Comment by lukaseder** [comment]
> If a warning is going to be added, we would like to see similar warnings on all methods that accept `Class` as an overload to `DataType`. Maybe pushing it down to `DefaultDataType.getDataType` could be preferable?

That's what I meant by the way I phrased it

**Comment by lukaseder** [comment]
This has been implemented with https://github.com/jOOQ/jOOQ/issues/15286 and related work
