### ISSUE TITLE
Wrong documentation in section "codegen-database-regex-flags"

### ISSUE THREAD

**Issue by InfoSec812** [jOOQ/jOOQ#12499]
Currently, the note beneath the XML example snippet reads -

> "All the flags available from java.util.regex.Pattern are available **as a whitespace-separated list**."

I just tested using the Maven plugin for 3.15.3 and it did not work unless I used as **comma-separated list**.

With the space-separated list I got the following error:

```
[ERROR] Failed to execute goal org.jooq:jooq-codegen-maven:3.15.3:generate (default) on project openapi-vertx-todo-data-access: Unable to parse configuration of mojo org.jooq:jooq-codegen-maven:3.15.3:generate for parameter regexFlags: Cannot convert 'DOTALL COMMENTS CASE_INSENSITIVE' to Enum: No enum constant org.jooq.meta.jaxb.RegexFlag.DOTALL COMMENTS CASE_INSENSITIVE -> [Help 1]
```

----
See: https://www.jooq.org/doc/latest/manual/code-generation/codegen-advanced/codegen-config-database/codegen-database-regex-flags/

**Comment by lukaseder** [comment]
I've fixed the documentation for now.

I'd rather fix the root cause and turn the `@XmlList` into an ordinary Maven style list eventually, but that's a breaking change with only little value. I'll wait until this pops up again: https://github.com/jOOQ/jOOQ/issues/12606

In any case, it's documented with this and the other issue now. Thanks again for your report!

**Comment by InfoSec812** [comment]
Thanks @lukaseder !!
