### ISSUE TITLE
Mixes camel and snake case when column names contain numbers

### ISSUE THREAD

**Issue by saibotma** [jOOQ/jOOQ#12518]
### Expected behavior

`column_name_1` in database should be generated as `columnName1`.

### Actual behavior
`column_name_1` in database gets generated as `columnName_1`.

### Steps to reproduce the problem
```

jooq {
    version.set(jooqVersion)

    configurations {
        create("main") {
            generateSchemaSourceOnCompilation.set(true)

            jooqConfiguration.apply {
                generator.apply {
                    name = "org.jooq.codegen.KotlinGenerator"
                    database.apply {
                        name = "org.jooq.meta.postgres.PostgresDatabase"
                        inputSchema = "public"
                        includes = ".*"
                    generate.apply {
                        isDeprecated = false
                        isImmutablePojos = true
                        isPojosEqualsAndHashCode = true
                    }
                    strategy.name = "org.jooq.codegen.DefaultGeneratorStrategy"
                }
            }
        }
    }
}
```

### Versions

- jOOQ: 3.15.3
- Java: openjdk 11.0.10 2021-01-19
- Database (include vendor): Postgres 11.5
- OS: MacOS 11.6
- JDBC Driver (include name if inofficial driver): Official Postgres Driver 42.2.24

**Comment by lukaseder** [comment]
Yeah, that looks wrong at first, but it has a reason and history! 😅 Assuming you have `column_name_1` and `column_name1`, how would you distinguish them in generated code?

Maybe it was wrong to just keep the underscore in the first case, and try to disambiguate them with the usual `_` suffix in case there is a conflict. But it's been done this way since pretty much jOOQ 1.x, so that won't be a simple change now that everyone is already using such generated code.

**Comment by saibotma** [comment]
Thanks for the insights. Is there a way around this?

**Comment by lukaseder** [comment]
You can implement your own generator strategy: https://www.jooq.org/doc/latest/manual/code-generation/codegen-generatorstrategy/

**Comment by saibotma** [comment]
Works like a flaw now, thanks!
For anyone having problems with `ClassNotFound` exceptions when configuring a custom strategy in Gradle: https://github.com/etiennestuder/gradle-jooq-plugin/tree/master/example/configure_custom_generator_strategy

**Comment by LimmaPaulus** [comment]
Could you add on option to remove underscores on generation? I really dislike these names and would love to see the underscore disappeared. Default functionality must of course be left as is.

I was able to write a custom generator strategy which removes the underscore. However, I were then unable to unmap POJOs to records with DefaultRecordUnmapper. Unmapper calls StringUtils.toCamelCase(), which contains these lines:

```
                // [#82] - If a word starts with a digit, prevail the
                // underscore to prevent naming clashes
                if (Character.isDigit(word.charAt(0))) {
                    result.append("_");
                }
```

As a workaround I generated JPA annotations, which removed the problem. However, I want no longer to use annotations due to an another problem with them.

**Comment by lukaseder** [comment]
@LimmaPaulus Thank you for your suggestion. It doesn't make sense to add an option to remove underscores, or just this particular type of underscore. That may or may not solve your actual problem, because it sounds quite short-sighted, and might still not cover some edge cases. It would cause a lot of effort in implementing, testing, documenting this, and again, it might still not solve all problems people may have.

At the same time, the `GeneratorStrategy` is such a simple approach to tweaking these things, if they're really important. I tend to think they're not. E.g. why did you have an underscore in your SQL identifier in the first place? Why not just remove that, instead?

**Comment by LimmaPaulus** [comment]
Thank you for your quick response again. I understand your rationale.

> At the same time, the GeneratorStrategy is such a simple approach to tweaking these things, if they're really important.

Yes, but then mapping POJOs to records breaks. Is this bug actually? Because I generated names without underscore for records, too.

> why did you have an underscore in your SQL identifier in the first place? Why not just remove that, instead?

Good question, indeed :grin:. Maybe this is the best solution. Of course it's never simple task to rename columns on production databases, at least before we are using JOOQ everywhere.

**Comment by lukaseder** [comment]
> Yes, but then mapping POJOs to records breaks. Is this bug actually? Because I generated names without underscore for records, too.

No it's not. How could the `DefaultRecordMapper` and `Unmapper` possibly foresee all your various tastes in naming? What if you decide you absolutely need to prefix all numbers in identifiers with `"💪"`. How could we handle that, automatically? jOOQ doesn't know what your generator strategy does, so if you implement one, then you also have to go down the rabbit hole of patching the `RecordMapperProvider` and `RecordUnmapperProvider`. That's the price you pay for disagreeing with the OOTB functionality (this is also a very good reason not to make the `_` configurable, because there's no way we can reasonably test all the possibly configuration flags at runtime).

> Good question, indeed 😁. Maybe this is the best solution. Of course it's never simple task to rename columns on production databases, at least before we are using JOOQ everywhere.

The way I see it, you have 3 options:

- Accept your "fate" of looking at "ugly" `SomeThing_3` identifiers
- Rename `SOME_THING_3` to `SOME_THING3` just because of this issue here, because you cannot acecpt above "fate", but also don't want to go down the above rabbit hole
- Go down the above rabbit hole and implement at least `GeneratorStrategy`, `RecordMapperProvider`, `RecordUnmapperProvider`, and possibly other SPIs, which I can't think of right now.

Personally, I'd pick the first 😅

**Comment by LimmaPaulus** [comment]
I think I will go with the option one at least before I'm able to rename DB columns. Thank you :)
