### ISSUE TITLE
Table column cannot be used as sort field when using implicit join

### ISSUE THREAD

**Issue by strindberg** [jOOQ/jOOQ#12532]
This issue has a MCVE here: https://github.com/strindberg/jOOQ-mcve, branch "jooq_issue_12532".

Consider the followig tables (postgres):

```sql
CREATE TABLE event
(
    id   bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name text   NOT NULL,

    PRIMARY KEY (id)
);

CREATE TABLE attachment
(
    uuid uuid NOT NULL,
    file_name text NOT NULL,

    PRIMARY KEY (uuid)
);

CREATE TABLE event_attachment
(
    event_id        bigint  NOT NULL,
    attachment_uuid uuid    NOT NULL,
    discarded       boolean NOT NULL DEFAULT false,

    PRIMARY KEY (event_id, attachment_uuid),
    FOREIGN KEY (event_id) REFERENCES event (id),
    FOREIGN KEY (attachment_uuid) REFERENCES attachment (uuid)
);
```

And the following Kotlin model:

```kotlin
data class Event(val id: Long? = null, val name: String, val attachments: List<Attachment>)

data class Attachment(val uuid: UUID, val fileName: String, val discarded: Boolean)
```

The following select method does not work:
```kotlin
    fun getEvents(): List<Event> =
        dsl.select(
            EVENT.ID,
            EVENT.NAME,
            multiset(
                select(
                    EVENT_ATTACHMENT.attachment().UUID,
                    EVENT_ATTACHMENT.attachment().FILE_NAME,
                    EVENT_ATTACHMENT.DISCARDED,
                )
                    .from(EVENT_ATTACHMENT)
                    .where(EVENT_ATTACHMENT.EVENT_ID.eq(EVENT.ID))
                    .orderBy(ATTACHMENT.FILE_NAME)
            ).convertFrom { it.map { r -> toAttachment(r) } },
        ).from(EVENT).fetch { toEvent(it) }

    private fun toEvent(r: Record3<Long?, String?, List<Attachment>>) = Event(r.value1()!!, r.value2()!!, r.value3())

    private fun toAttachment(r: Record3<UUID?, String?, Boolean?>) = Attachment(r.value1()!!, r.value2()!!, r.value3()!!)
```

It produces the following error:
```
Caused by: org.postgresql.util.PSQLException: ERROR: invalid reference to FROM-clause entry for table "attachment"
  Hint: Perhaps you meant to reference the table alias "alias_19887341".
```

The problem is that the attachment table has been aliased such that "ATTACHMENT" cannot be used. I don't know if this is an inevitable effect of how it must work, but at least it is a bit surprising to the user: it would feel quite natural to be able to sort on "ATTACHMENT.FILE_NAME" as one could do when not using the implicit join.

### Versions

- jOOQ: 3.15.3

**Comment by lukaseder** [comment]
Thank you very much for your message.

> it would feel quite natural to be able to sort on "ATTACHMENT.FILE_NAME" as one could do when not using the implicit join.

Let's think it through.

```java
select(
    EVENT_ATTACHMENT.attachment().UUID,
    EVENT_ATTACHMENT.attachment().FILE_NAME
)
```

Your usage of `EVENT_ATTACHMENT.attachment()` creates the implicit join behind the scenes. The two identical paths are recognised as being the same thing, and as such, can re-use the same implicit join. To illustrate this, you could assign the path to a local variable first: `var a = EVENT_ATTACHMENT.attachment()`. This `a` acts like a "Java alias" for the table expression, so you could now write:

```java
select(
    a.UUID, // Reference to a
    a.FILE_NAME, // Reference to a
    EVENT_ATTACHMENT.DISCARDED,
)
    .from(EVENT_ATTACHMENT)
    .where(EVENT_ATTACHMENT.EVENT_ID.eq(EVENT.ID))
    .orderBy(a.FILE_NAME) // Reference to a
```

This feels right. Now, you're saying, ordering by `EVENT_ATTACHMENT.FILE_NAME` should work, too. Then, by consequence, so should this:

```java
select(
    a.UUID,
    ATTACHMENT.FILE_NAME, // "natural" usage of the actual table name
    EVENT_ATTACHMENT.DISCARDED,
)
    .from(EVENT_ATTACHMENT)
    .where(EVENT_ATTACHMENT.EVENT_ID.eq(EVENT.ID))
    .orderBy(a.FILE_NAME)
```

But you didn't suggest this, because it doesn't feel right to use the path `a` for one column but not for the other in the projection. It somehow felt less not-right to suggest this for `SELECT` vs `ORDER BY`

If we take this a step further, this should work, too, according to your suggestion:

```java
var a = ATTACHMENT.as("a"); // Actual aliasing
select(
    a.UUID,
    ATTACHMENT.FILE_NAME // Use the unaliased table
)
    .from(a) // Use the aliased table
```

But this clearly doesn't make any sense. This query aliased the table `ATTACHMENT` to be called `a`. The original table reference is no longer in scope, and it mustn't be, because you could self join the tables:

```java
    .from(a, ATTACHMENT)
```

Now, would this suddenly want the reference `ATTACHMENT.FILE_NAME`, which used to refer to `a.FILE_NAME` "for convenience", to reference the fully qualified  `ATTACHMENT.FILE_NAME` again? Better not! There is no difference between this logic and the implicit join one. The current behaviour of jOOQ is the only reasonable one if this feature should scale to queries of arbitrary complexity.

You probably expected there shouldn't be any auto-generated alias for the implicit join path, but if there wasn't, how would we disambiguate two distinct paths that lead to the same target table? For example:

```java
select(
    CUSTOMER.address().CITY,
    STORE.address().CITY
)
```

Clearly, there must be two distinct references to `ADDRESS` in the generated implicit join expression. What would `ADDRESS.CITY` mean in such a query? We could argue that your convenience works (single reference to `ADDRESS` doesn't *necessarily* need aliasing) until it doesn't (second reference to `ADDRESS` requires disambiguation). But it seems *much* preferrable to not disclose the generated alias as something you could ever use as a user, keeping it an implementation detail, requiring you to either:

- Fully qualify the implicit join path every time (directly, or via local variable as shown above)
- Alias the implicit join path explicitly, and use the aliased table instead to dereference columns

So, this works as designed, and while you may have preferred your suggested behaviour in 1-2 queries, you will be glad this isn't the way it works in many other queries. It's just like SQL's own way of allowing unqualified column references (e.g. `SELECT a FROM t, u`, where `a` could mean `t.a` or `u.a` as long as it's not ambiguous). Unqualified column references seem like a convenient quick win for the (*very*) simple query, but they're always a pain and a mistake when you have at least one join.

Hope this makes sense?
