### ISSUE TITLE
Postgre dialect don't use LIMIT

### ISSUE THREAD

**Issue by foxpluto** [jOOQ/jOOQ#12628]
I think I found a bug in the way Jooq call a Postgres Database using `LIMIT` SQL statement. 

I have this super easy Test:
```java
    @Test
    public void test02() throws Exception {
        Connection connection = DriverManager.getConnection(DB_URL, USER, PASS);
        DSLContext context = DSL.using(connection, SQLDialect.POSTGRES);
        int result = context.select(EVENTS.eventId)
                            .from(EVENTS)
                            .limit(1)
                            .execute();
        assertEquals(1, result);
    }
```
In the DEBUG log I read: 
```
[DEBUG] 09:20:05.418 org.jooq.tools.LoggerListener.debug() - -> with bind values      : select "doc"."events"."data_block['eventId']" from "doc"."events" fetch next 1 rows only
```
According to the documentation written here: [select-statement limit-clause](https://www.jooq.org/doc/latest/manual/sql-building/sql-statements/select-statement/limit-clause/) the Jooq code should use the `LIMIT` statement which is supported by Postgres and not the `fetch next` 

The database I am using is Crate DB which is compatible with Postgres bitecode but doesn't support  `fetch next`.

Using H2 as Dialect the call is correct as indicated in the documentation:
```
[DEBUG] 09:25:59.553 org.jooq.tools.LoggerListener.debug() - -> with bind values      : select "doc"."events"."data_block['eventId']" from "doc"."events" limit 1
```

Could you fix the use of `LIMIT` even for Postgres?  

### Versions

- jOOQ: 3.15.4
- Java: 11
- Database (include vendor): Postgre 13
- OS: Linux Centos 7.4
- JDBC Driver (include name if inofficial driver): org.postgresql:postgresql:42.3.0

**Comment by lukaseder** [comment]
Thanks a lot for your message. The standard SQL `FETCH` syntax has been understood by PostgreSQL since version 8.4. https://www.postgresql.org/docs/8.4/sql-select.html

Starting from jOOQ 3.15, we've added support for PostgreSQL 13 and the new `WITH TIES` support, see https://github.com/jOOQ/jOOQ/issues/10645. It would have been too complicated to maintain `LIMIT` for `ROWS ONLY` semantics and `FETCH` for `WITH TIES` semantics, so we just always generate the standard SQL syntax.

See also:
https://github.com/jOOQ/jOOQ/issues/12114#issuecomment-875461372

I understand that this is something that CrateDB doesn't support, so the correct way to fix this in jOOQ would be to implement formal CrateDB support: https://github.com/jOOQ/jOOQ/issues/12629. It's certainly not a bug in our PostgreSQL dialect. You'll run into other, similar limitations, which are all not bugs in jOOQ, but derive from the fact that you're using an unsupported dialect.

While formal CrateDB support would certainly be interesting for you (and these folks: https://stackoverflow.com/q/69872101/521799, is that also you?), I think that in this particular case, you'll get fastest results by having CrateDB implement the SQL:2008 standard syntax: https://github.com/crate/crate/issues/11540

In the meantime, we'll definitely update the manual, since we're no longer generating `LIMIT` in PostgreSQL.
