### ISSUE TITLE
Move XSDs from jOOQ and jOOQ-meta to subpackages to avoid split xsd packages

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#12633]
The upcoming modularisation of `jOOQ-meta` and `jOOQ-codegen` (https://github.com/jOOQ/jOOQ/issues/10149) produces a split "package" of a resource directory `/xsd`, which is present in both `jooq` and `jooq-meta`. This can lead to the following exception if someone depends on both modules from a module:

> java.lang.LayerInstantiationException: Package xsd in both module org.jooq.meta and module org.jooq

We must thus move these resources into subpackages, which is an incompatible change.

**Comment by lukaseder** [comment]
Note: This was a problem before `jOOQ-meta` was modularised, but only appeared in our tests now. We must not publish to the `xsd` package, which we don't own!

**Comment by lukaseder** [comment]
Fixed for jOOQ 3.16.0. This will possibly be backported to 3.15, as it can cause arbitrary issues in user builds if another module has the same accidental publication of an `xsd` package.

**Comment by lukaseder** [comment]
I won't backport this issue.

1. No one has reported it yet
2. There are probably workarounds in the module system
3. In the worst case, users can remove the XSD from the jar file
4. The regression risk of people no longer able to load the XSD from the classpath when upgrading a patch release is too high.

**Comment by perlun** [comment]
> The regression risk of people no longer able to load the XSD from the classpath when upgrading a patch release is too high.

Affirmative, thanks for not backporting this, it's definitely a breaking change that would have caused issues for people. :+1: I just figured out (after scratching my head for a significant time) that this is the root cause for the NPE that made me submit this PR: https://github.com/etiennestuder/gradle-jooq-plugin/pull/205

The problem is with the assumption in this method; it blindly presumes that the XSD file is located in the top-level `xsd` package: https://github.com/etiennestuder/gradle-jooq-plugin/blob/b6fc46ff64abc77ec37408fc7cb116ee7b760b78/src/main/groovy/nu/studer/gradle/jooq/JooqGenerate.java#L242-L255

This means that the `gradle-jooq-plugin` is currently broken with 3.16.0 and upwards. I'll see if I can get a PR submitted (to the plugin repo) which fixes this early next week.

**Comment by perlun** [comment]
I guess the proper way here would be to rely on `org.jooq.Constants#CP_CODEGEN` instead of constructing the XSD resource path ourselves, in the plugin. This got added in jOOQ in 3.12.0 (https://github.com/jOOQ/jOOQ/issues/9070) so it means the Gradle plugin would break backwards compatibility to older jOOQ versions, but it's probably the least bad option anyway AFAICT.

(Side note: is there a table/webpage somewhere about supported jOOQ versions from your end, i.e. _upstream supported_?)

**Comment by lukaseder** [comment]
Thanks for digging this up, @perlun. Yes indeed, the `CP_CODEGEN` constant is the one that should be used here. Since @etiennestuder's plugin is already using reflection to discover these constants, I think there's a backwards compatible way to discover whether the `CP_CODEGEN` value is present, and use it only then:
https://github.com/etiennestuder/gradle-jooq-plugin/blob/b6fc46ff64abc77ec37408fc7cb116ee7b760b78/src/main/groovy/nu/studer/gradle/jooq/JooqGenerate.java#L257-L265

**Comment by perlun** [comment]
@lukaseder Thanks, good suggestions. :+1: Don't know if you have review rights in this repository :sweat_smile: but feel free to give https://github.com/etiennestuder/gradle-jooq-plugin/pull/206 a look regardless. It uses the approach you suggested. Not yet gotten it to work on jOOQ 3.16 but we're getting there, one step at a time...

**Comment by lukaseder** [comment]
> Don't know if you have review rights in this repository 😅

I don't

**Comment by perlun** [comment]
OK, too bad. I emailed Etienne though and he'll get to these PRs eventually.

**Comment by lukaseder** [comment]
> OK, too bad but good to know. 👍

There's a bit of history between jOOQ and this third party plugin contribution. In summary, I have ignored gradle for too long, leaving a gap related to those more complex gradle integration use-cases you've mentioned here: https://github.com/etiennestuder/gradle-jooq-plugin/issues/204#issuecomment-1026138810

Etienne, who works for Gradle Inc., has implemented his plugin as a third party contribution, as an individual in his free time (in his own namespace, not Gradle's). As such, while state-of-the-art in terms of gradle integration, it has still been out of the jOOQ development lifecycle loop, which has been a sore spot for jOOQ itself, leading to problems like the one you've seen now. The jOOQ integration tests do not include this plugin.

It's not the first time something like this has popped up. I think there needs to be a better solution for the community. jOOQ should (finally) have an *official* gradle plugin under the jOOQ namespace, and using jOOQ's versioning and release cycle. I've created a new issue for this, to be addressed hopefully in the next minor release 3.17.0: https://github.com/jOOQ/jOOQ/issues/12985

**Comment by lukaseder** [comment]
By the way, @perlun, let me express my thanks for your patience expressed in this issue and various others. Your feedback has been very helpful, both for jOOQ development, as well as for others running into similar issues!

**Comment by perlun** [comment]
> By the way, @perlun, let me express my thanks for your patience expressed in this issue and various others. Your feedback has been very helpful, both for jOOQ development, as well as for others running into similar issues!

Happy to be of help to you and others. :pray: :+1: It's sure been a bit of work on my behalf (paid, luckily), but I'm really happy to hear that we are completely in sync here in that jOOQ/Data Geekery should provide an "official" & great Gradle experience OOTB. Let's continue in the other issue you created (#12985).

**Comment by etiennestuder** [comment]
The very recent [v7.0 of the gradle-jooq-plugin](https://github.com/etiennestuder/gradle-jooq-plugin/releases/tag/v7.0) fixes the situation and is compatible with 3.16.x. People still using jOOQ <=3.15 should continue to use v6.0.1.
