### ISSUE TITLE
Feedback about manual section "multiset-value-constructor"

### ISSUE THREAD

**Issue by larsenqec** [jOOQ/jOOQ#12648]
I am confused about multiset functionality in Informix. The docs say that Informix and Oracle have native support, but can this be accessed via jooq?

----
See: https://www.jooq.org/doc/3.2/manual/sql-building/column-expressions/multiset-value-constructor/

**Comment by lukaseder** [comment]
Thanks a lot for your message. Indeed, jOOQ 3.15 does not yet support a native `MULTISET` binding in either of these dialects. In Oracle, you can use the XML or JSON bindings. In Informix, we don't support `MULTISET` yet.

See the limitations here: https://github.com/jOOQ/jOOQ/issues/12021. Is this something you'd like to see for your own usage?

**Comment by larsenqec** [comment]
Yes, I would love to see support for Informix. After looking at your example implementations for other databases, I was led to the Informix genxml function, which makes me think that jooq could easily implement this without the native MULTISET keyword.

In fact, I tried to to write a manual query doing this with MULTISET and could not get it to work (Their docs are terrible). I have considered using genxml directly, but I would be overjoyed if jooq could use it for XML emulation.

**Comment by lukaseder** [comment]
> I was led to the Informix genxml function

Yes that looks as though it could work, indeed. This seems to work similar to SQL Server's `FOR XML` clause. Let me have a look later this week, I'll update this issue with links to potential feature requests. This looks like something that could fit in 3.16, still (due end of 2021). If I can get this to work, this or next week's snapshot builds might already have the feature.

> In fact, I tried to to write a manual query doing this with MULTISET and could not get it to work (Their docs are terrible)

Yeah, welcome to jOOQ development :) Reverse engineer the *actual* behaviour of an RDBMS until all integration tests pass.

**Comment by lukaseder** [comment]
I remember I had looked into supporting these features in the past, but I gave up because:

1. The functionality is extremely limited
2. Errors are very cryptic, when something goes wrong
3. There's little control over the output format, which would complicate the deserialisation a lot

There's also a `genBSON()` function, which regrettably outputs a MongoDB specific format, rather than just plain JSON.

So, I think in order to support `MULTISET`, the best approach here would be to tackle a native implementation instead, which would be useful also to other dialects, including e.g. BigQuery. I'm hoping to address this in the near future via https://github.com/jOOQ/jOOQ/issues/12021, but I don't think it'll still fit in jOOQ 3.16.
