### ISSUE TITLE
EnumConverter does not work with multivalued fields

### ISSUE THREAD

**Issue by Brictarus** [jOOQ/jOOQ#12650]
Hi, i have tried using EnumConverter with maven codegen plugin on a array columnin Postgres (also known as multivalued column)
For example, let's say this is my table declaration : 
```
CREATE TABLE "token" (
  "id"       integer PRIMARY KEY,
  "text"     text,
  "category" text[]
);
```
When i configure my code generation like this : 
```
<configuration>
  <generator>
	...
	<database>
	  <forcedTypes>
		<forcedType>
		  <userType>com.company.enum.CategoryEnum</userType>
		  <enumConverter>true</enumConverter>
		  <includeExpression>category</includeExpression>
		</forcedType>
	  </forcedTypes>
	</database>
  </generator>
</configuration>
```

I expect to get a field declaration like this in the generated table class : 
```
public final TableField<TStockRecord, CategoryEnum[]> CATEGORY = ...
```

### Actual behavior
The generated field is no more an array, the mapping cannot work
```
public final TableField<TStockRecord, CategoryEnum> CATEGORY = ...
```

### Versions

- jOOQ: 3.15.3
- Java: 11
- Database (include vendor): Postgres
- OS: Window 10

**Comment by lukaseder** [comment]
Thanks for your message.

I can see how your expectation here makes sense. You configured a converter for the base type, so jOOQ should somehow do the "right thing" and correctly apply it to array types, too. (And this is a frequent feature request, which we already have on the roadmap somewhere). However, this isn't how it currently works, there would be a lot of open questions and edge cases with respect to serialisation and deserialisation of such mappings, especially with heavily nested arrays of UDTs containing arrays, etc, so this won't be a priority soon.

Better just implement a custom data type binding: https://www.jooq.org/doc/latest/manual/sql-building/queryparts/custom-bindings/ and bind the array type directly, instead of the component type.

I hope this helps
