### ISSUE TITLE
Null value in column "id" exception for serial id columns.

### ISSUE THREAD

**Issue by segocago** [jOOQ/jOOQ#12784]
### Expected behavior
Do not include auto generated id fields in insert statements generated from reactive inserts.

### Actual behavior

Insertion of records throw "null value in column "id" violates not-null constraint" exception since the insert statements also include id field.

### Steps to reproduce the problem

- We are using generated java POJOS for a simple CRUD application that is using r2dbc to make reactive operations with jooq. However, the below insertInto code is throwing null value exception for id column and i can see that sql insert  into statement has also id field. Since we are using serial id columns, the id column in the pojo is null. I saw several issues that got fixed for non reactive API but it does not seem to work with reactive API.

```
List<MyObjectRecord> objectRecords =
        objectPojos.stream()
                   .map(myObjectPojo -> {
                     return dslContext.newRecord(MYOBJECT, myObjectPojo);                
                     })
                   .collect(toList());

return Flux.from(dslContext.insertInto(MYOBJECT)
                           .columns(MYOBJECT.fields())
                           .valuesOfRecords(objectRecords)
                           .returningResult(MYOBJECT.fields()))
           .map(record -> record.into(MyObjectPojo.class))
```

### Versions

- jOOQ: 3.15.4
- Java: 17
- Database (include vendor): PostgreSQL 11.11
- OS:
- JDBC Driver (include name if inofficial driver): r2dbc

**Comment by lukaseder** [comment]
Thanks a lot for your message.

By default, jOOQ will do exactly as you tell it to. While it may seem a good idea at first to omit some columns from statements, it may have been exactly what you wanted when you write a query like this.

There are, however, a few improvements in jOOQ 3.16 related to "readonly columns":

- https://www.jooq.org/doc/latest/manual/sql-building/column-expressions/readonly-columns/
- https://www.jooq.org/doc/latest/manual/code-generation/codegen-advanced/codegen-config-database/codegen-database-readonly-columns/
- https://www.jooq.org/doc/latest/manual/code-generation/codegen-advanced/codegen-config-database/codegen-database-synthetic-objects/codegen-database-synthetic-readonly-columns/

In those cases, jOOQ will assume you added the readonly column to an explicit statement by accident, or because removing them manually is too cumbersome, so it will transform your SQL statement to not include the readonly columns (including identities) from DML statements.

I hope this helps

**Comment by lukaseder** [comment]
> * I saw several issues that got fixed for non reactive API but it does not seem to work with reactive API.

This problem is not related to how you execute the query, but how the SQL string is generated, which should be the same with both JDBC and R2DBC. If you think there's still a bug (in jOOQ 3.16), related to doing this with R2DBC, please let me know.

**Comment by segocago** [comment]
Thanks Lukas for your fast answer. I have switched to 3.16 as you have suggested and regenerated the classes but i'm still having the same error. We are using below ddl for the table. Do we need to add something else to pk definition for jooq to see it as readOnly column or does jooq regard all serial pk's as readonly?

```
create table myobject (
    id serial not null
        constraint myobject_pkey
            primary key
```

**Comment by lukaseder** [comment]
Which jOOQ edition are you using? Readonly columns are only available to the commercial distributions, see the relevant manual section headers:

<img width="631" alt="image" src="https://user-images.githubusercontent.com/734593/148372003-da01a908-80f6-444e-bed4-31d15b33fb59.png">

If you're using a commercial distribution, you'll have to re-generate your code with your identities configured as "readonly", e.g. using the synthetic readonly columns feature:
https://www.jooq.org/doc/latest/manual/code-generation/codegen-advanced/codegen-config-database/codegen-database-synthetic-objects/codegen-database-synthetic-readonly-columns/

(Because identities usually aren't readonly in many dialects).

If all of this isn't viable, you can still reset your identity column values on each record prior to passing it to the `INSERT` statement.

**Comment by lukaseder** [comment]
To be clear, the problem is this call here:

```java
                           .columns(MYOBJECT.fields())
                           .valuesOfRecords(objectRecords)
```

Where you *explicitly* set all the fields to be inserted, even the ones that aren't "changed" in the `objectRecords` record. You could instead try to set only those that are "changed" in each record...

**Comment by segocago** [comment]
Yeah, i just noticed that read only columns feature does not apply to open-source edition. So if i understand correctly, it is not possible to omit id columns from insert statements for open-source edition users atm. We need to separately write out each column except the identity column while creating insert statement through DslContext. At least this is what we are currently doing but I was hoping to change this logic as there are 30+ columns in some of our entities and specifying each column within .value() and .columns() methods is very open to error.

**Comment by lukaseder** [comment]
If using the commercial edition isn't an option, which does all of this transparently, you can still re-implement the logic yourself using some utilities. You already wrote a utility to stream/map your POJOs to records. Why not add a few lines to check for the relevant meta data?
