### ISSUE TITLE
SQL DSL should allow out-of-order modifications allowing for query extensions to operate on multiple parts of a query

### ISSUE THREAD

**Issue by apatrida** [jOOQ/jOOQ#12789]
### Use case:

Starting with what we CAN do now in Kotlin, versus what is missing below...

In allowing re-use within a team, we take advantage of Kotlin extension functions to make bits of logic into extension functions named to match "human terms" of what the query is doing. This allows high readability:  For example:

```kotlin
    val query = select(
        q.ID, q.STICKY, q.POST_TIME, q.PUBLIC, q.NUM_VOTES,
        q.NUM_ANSWERS, q.NUM_LIKES, q.NUM_FAVORITES, q.LAST_RESPONSE,
    ).from(q)
        .where(
            q.isInCommunity(community)
                .and(q.isNotDeleted())
                .and(q.isNotContactMessage())
                .and(q.isEnabledOrReviewed().or(q.isWrittenBy(viewer)))
                .and(q.isNotWrittenByGuest())
                .and(q.isPublicPost().or(q.isWrittenBy(viewer)))
                .and(q.isAlreadyVisible())
                .onlyWhen(onlyWrittenBy.isNotEmpty()) {
                    and(q.isWrittenByAnyOf(onlyWrittenBy))
                }
                .onlyWhen(ignoreWrittenBy.isNotEmpty()) {
                    and(q.isNotWrittenByAnyOf(ignoreWrittenBy))
                }
                .and(q.isNotMutedBy(viewer)) // semi-join version
                .and(q.isNotWrittenByBlocked()) // use NOT IN clause
        )
```

which is much better to read than (either SQL or JOOQ DSL this conveys confusion, not readability):

```sql
            SELECT q.id AS qid
            FROM questions q JOIN users u ON u.id = q.user_id
                       LEFT JOIN user_permission up ON up.group_id = q.q_group_id AND up.user_id = q.user_id AND up.blocked <> 0
            WHERE
                q.type != 'contact'
                    AND q.class != 'contact'
                    AND q.q_group_id = 456
                    AND q.user_id > 0
                    AND q.post_time <= NOW()
                    AND q.state != 'deleted'
                    AND (q.state IN ('enabled' , 'post_review') OR q.user_id = 123)
                    AND (( q.public > 0 AND q.public < 3) OR q.user_id = 123)
                    AND up.blocked IS NULL -- linked to JOIN above
                    AND q.user_id not in (
                       SELECT muted_id FROM user_mute WHERE user_id = 123 AND expires_at > NOW()
                    )
```

Each of these extensions are fragments of varying complexity but allow a more readable query and for many queries to share logic by name instead of things like `USER_ID.notEqual(inline(UInteger.valueOf(0)))` (which means what?!?) or the more complex:

```kotlin
fun Questions.isNotWrittenByBlocked(): Condition {
    val up = USER_PERMISSION.alias("nwbb") // name not likely to conflict
    return USER_ID.notIn(DSL.select(up.USER_ID).from(up).where(Q_GROUP_ID.eq(up.GROUP_ID).and(up.BLOCKED.equal(inline(1.toByte())))))
}
```

We can also extend the query with joins:

```kotlin
fun Questions.withAuthors(u: Users) = join(u).on(USER_ID.eq(u.ID))

fun Questions.withOptionalUserPermission(up: UserPermission) = leftJoin(up).on(Q_GROUP_ID.eq(up.GROUP_ID).and(USER_ID.eq(up.USER_ID)))
``` 

But what we can't do, and what this feature request is for, there is no way to handle a case where we need to have one extension that can both modify the JOIN and the WHERE clauses at the same time.

```kotlin
fun Questions.withOptionalUserPermission(up: UserPermission) = leftJoin(up).on(Q_GROUP_ID.eq(up.GROUP_ID).and(USER_ID.eq(up.USER_ID)))

fun Questions.withOptionalBlockedUserInfo(up: UserPermission) = withOptionalUserPermission(up).and(up.BLOCKED.notEqual(0))

// and also add to the WHERE clause:     .and(up.BLOCKED.isNull) in WHERE
```

(now, before you say, well, use the `isNotWrittenByBlocked()` function above, it is cool too! but in MySQL 5.7 it performs worse than the JOIN + WHERE version of the same query, and there are are other cases where a join must be used + where clause elements)

### Possible solution you'd like to see:

So the proposal is that there is a way to go back to the join clause later in the DSL to be able to append more there while working in the where clause.  Or in the JOIN part of the DSL, adding to the future WHERE clause before we have gotten to that part of the DSL.  I'm fine with either, it depends on whether you are wanting the user to know the JOIN is there for the data to be used, or if the JOIN is just there to filter data where the extension function might want to be used.

Possible addition to join steps, `withWhereAndCondition` / `withWhereOrCondition` or better named beast:

```
    .from(q)
    .leftJoin(up).on(Q_GROUP_ID.eq(up.GROUP_ID).and(USER_ID.eq(up.USER_ID))).and(up.BLOCKED.notEqual(0))
    .withWhereAndCondition(up.BLOCKED.isNull) // deferred into the Where clause and AND'd on
```

I cannot current write this myself as an extension because everything is package local or private that would need to be used to make this work, and it would be reaching into internals that shouldn't happen.

The problem with this solution is that it can only do basic additions that are AND or OR to the total where clause, but that does provide a lot of coverage over why this would be used and how. 

Other alternative is to add the where condition which has an alias that must be added in manually later or it becomes an error at runtime (like an unbound parameter), but seems icky.

### Possible workarounds:

Two extension functions that you have to remember to use both of, and if you don't, things don't work and you get the wrong data.  Not a safe workaround.

Using the dynamic SQL generator that is mutable, but that means not using a good DSL and rewriting the DSL in Kotlin to avoid that.

### Versions:

- jOOQ: all
- Java: any
- Database (include vendor): all
- OS: all
- JDBC Driver (include name if inofficial driver): all

**Comment by lukaseder** [comment]
SQL has a ton of primitive operators, all of which we strive to support and emulate if not natively supported. This produces a huge API, which works mainly because everything works exactly as expected. There are almost no surprises. This is what users like.

Occasionally, when we can add *a lot* of value, we add new [synthetic SQL clauses](https://www.jooq.org/doc/latest/manual/sql-building/synthetic-sql-clauses/), including:

- Implicit joins (really powerful and versatile)
- Multiset (really powerful and versatile)
- Seek for keyset pagination
- Semi join and anti join (which exist in relational algebra, but not in SQL)

There are others. This is what users also like, as long as we don't overdo it.

What you're suggesting, however, is quite esoteric (i.e. rarely useful), and highly specific (does only one very specific thing, can't be generally reused). What if someone needs a `JOIN`, and then a `GROUP BY`? Or `DISTINCT`, but only if there are 2 additional joins? How many such auxiliary methods will we end up implementing? How do we merge your predicate with other predicates (you hint at using `AND` or `OR`, but this can become arbitrarily complex)

I think you can see where I'm trying to go with this. *Especially* if you're already using kotlin or some other language with extension methods, you can probably pull it off on your end, and write your *own* jOOQ.

In this particular case, you can probably pull it off with your existing approach, e.g. by accessing the very old `SelectQuery` model API from your extension method and patch the `WHERE` clause into the mutable, internal representation like this (kotlin syntax off the top of my head, might not compile):

```kotlin
fun SelectOnConditionStep<R : Record>.withWhereAndCondition(c: Condition): SelectOnConditionStep<R> {
    this.getQuery().addCondition(c)
    return this
}
```

You could even leverage the knowledge that even the DSL API for queries is mutable, like this:


```kotlin
fun SelectOnConditionStep<R : Record>.withWhereAndCondition(c: Condition): SelectOnConditionStep<R> {
    this.where(c)
    return this
}
```

I hope this helps

**Comment by lukaseder** [comment]
> Great, thanks for the notes, I didn't notice the mutable query was accessible from the normal DSL via `getQuery`, so yes, I can patch the query as you mention. Great!

Yeah, that single method is hidden in the vastness of the jOOQ API 😅

> Note, the approach I suggest in this ticket maybe would make a good blog post about using Kotlin to create re-usable query fragments and human-readable queries.

Do you blog?
