### ISSUE TITLE
r2dbc and executing blocking method

### ISSUE THREAD

**Issue by cemo** [jOOQ/jOOQ#12873]
### Your question:

I am trying to add necessary glue codes  and tests for declarative way of transactions to Micronaut. So far I added some basic codes and when I try to add 

```
        Flux.just(db.execute("CREATE TABLE IF NOT EXISTS foo(id INTEGER);"))
            .doOnNext(System.out::println)
            .subscribe();
```
error:

`Attempt to execute a blocking method (e.g. Query.execute() or ResultQuery.fetch()) when only an R2BDC ConnectionFactory was configured`

I think this error is little suspicious for me. The blog post is mentioning that

> Starting from this DSLContext, you can build your queries as always, but instead of calling the usual blocking execute() or fetch() methods, you’ll just wrap the query in a Flux, for example. Assuming you ran the jOOQ code generator on your H2 INFORMATION_SCHEMA, you can now write:

This is maybe my misunderstanding but I wanted to ask your help to complete the PR. :)

Here is the branch: https://github.com/micronaut-projects/micronaut-sql/pull/545

### Versions:

- jOOQ: 3.17.1
- Java: 17
- Database (include vendor): h2

**Comment by cemo** [comment]
Most of the jOOQ methods are already `Publisher`. Execute is returning integer and it is impossible to detect that it is in async context. For those who hits similar problem:

```
  Flux.from(db.createTableIfNotExists("foo")
                    .column("id", INTEGER))
            .doOnNext(System.out::println)
            .subscribe();
```
Use something like this.

**Comment by cemo** [comment]
@lukaseder How can I run a simple query `INSERT INTO foo(id) VALUES (0)` like this?. Maybe we can describe a better explanation on error in case such a config and executing blocking calls.  

I mean  instead of this:

`Attempt to execute a blocking method (e.g. Query.execute() or ResultQuery.fetch()) when only an R2BDC ConnectionFactory was configured`

I mean here we may write maybe proper ways in the error.

**Comment by lukaseder** [comment]
Thanks for your messages. First off, I think there's some room for improvement with the blocking API in jOOQ, which could be annotated with the new `org.jetbrains.annotations.Blocking` annotation (see: 
https://github.com/jOOQ/jOOQ/issues/12875) to help prevent accidental usage via static code analysis in IDEs and possibly with a jOOQ-provided checker (see: https://github.com/jOOQ/jOOQ/issues/12876).

I agree, the error message could help provide more info on how to do things correctly. I've created another feature request for this: https://github.com/jOOQ/jOOQ/issues/12877

**Comment by lukaseder** [comment]
> @lukaseder How can I run a simple query `INSERT INTO foo(id) VALUES (0)` like this?. Maybe we can describe a better explanation on error in case such a config and executing blocking calls.

Not sure if there are any remaining open questions here? How's the `INSERT` query different from the `CREATE TABLE` query, for you?

**Comment by lukaseder** [comment]
The annotation will be quite useful: https://github.com/jOOQ/jOOQ/issues/12875#issuecomment-1014304854

![image](https://user-images.githubusercontent.com/734593/149742425-9cb0c31f-8027-4795-a82c-9b0495921ba6.png)

I'll blog about this, too.

**Comment by cemo** [comment]
> How's the INSERT query different from the CREATE TABLE query, for you?

For prototyping or someone who is already new to jOOQ internals it would be very convenient to just write plain SQL as blocking. I think it also makes sense to have a non-blocking counterpart of the api as much as possible.

**Comment by lukaseder** [comment]
> For prototyping or someone who is already new to jOOQ internals it would be very convenient to just write plain SQL as blocking

I'm not convinced that it should be possible to "conveniently" block on the various `execute()` methods, but backed on an R2DBC connection. That's only 5% deliberate convenience, and 95% by accident, a very poor tradeoff. Even for "prototypes", there are more questions and problems caused by this quick-and-dirty blocking (where do you block? Within a flux? Within an otherwise non-blocking method returning a flux? What does this mean for your transactions (which already don't yet work, see the other discussion))?

All knowing that this blocking can be *very* easily achieved using `Mono.from(query).block()` or `Flux.from(query).collectList().block()`, and also knowing that if this kind of ad-hoc blocking is done frequently, then perhaps the whole non-blocking approach wasn't the right choice for your system (or, you can use JDBC for those parts).

But if you still think that convenience worth it, you can create a new feature request, and we'll collect the votes and discussions there, from other users.

> I think it also makes sense to have a non-blocking counterpart of the api as much as possible.

Most of the existing blocking execution API had been implemented in "Java 6 times", when we didn't have the functional primitives that we have now since Java 8. Most methods (e.g. `fetchMap()`) are obsolete and better represented by a collector, e.g. via `query.collect(toMap(...))`. Gradually, we'll start replacing, deprecating, and removing all this existing convenience API, moving towards a more composable, functional API.

While some additional convenience could be added for the async API (which produces `CompletionStages`), I don't think anything is needed *at all* for the reactive API. The reactive streams `Publisher` SPI is all you'll ever need, and the processing is completely moved to your reactive streams library of your choice, e.g. reactor, which already has all the `map`, `flatMap`, `collect` and all sorts of utilities. jOOQ doesn't need to repeat those.
