### ISSUE TITLE
Work around H2 issue 3398 which hangs the process when using FINAL TABLE (MERGE ...)

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#12925]
H2 2.1.210 has a significant regression, which hangs the JVM process through some infinite loop:

- https://github.com/h2database/h2database/issues/3391
- https://github.com/h2database/h2database/issues/3398

Until a fix is released, we need to work around this regression. A workaround that jOOQ can do is documented here: https://github.com/h2database/h2database/issues/3398#issuecomment-1019859349

We'll avoid identical prepared statements when using `FINAL TABLE (MERGE ...)` by introducing a random value, e.g. `UUID.randomUUID()` in a generated SQL comment.

Given that we have another urgent reason to release 3.16.3 soon (CVE-2022-23221), this will be patched right away.

**Comment by lukaseder** [comment]
Fixed in jOOQ 3.17.0 and 3.16.3 (https://github.com/jOOQ/jOOQ/issues/12926)

**Comment by katzyn** [comment]
@lukaseder
This workaround may reduce performance because it effectively breaks possibility to reuse a query from the cache. The workaround is only needed for 2.1.210, older (2.0.206 and below) and newer (2.1.212, 2.1.214) versions aren't affected.

H2 2.1.210 isn't expected to be used these days, its users need to upgrade it to the latest available release in 2.1 series of releases. You may have own reasons to support 2.1.210 in jOOQ, but maybe this workaround can be applied only for that particular release of H2?
