### ISSUE TITLE
jOOQ incorrectly consider a field named rownum as using a pro edition feature

### ISSUE THREAD

**Issue by victornoel** [jOOQ/jOOQ#12950]
### Expected behavior

I can parse and execute the following query with Postgresql dialec:
```sql
SELECT * FROM (SELECT field, row_number() OVER (ORDER BY field) as rownum FROM T1) WHERE rownum = 1
```

### Actual behavior

I get an exception telling this:
```
Feature only supported in pro edition: [274:76] ... rownum [*]= 1
```
(the line/row number are incorrect because I simplified the query :).

### Versions

- jOOQ: 3.14.15, 3.15.4, 3.16.2
- Java: 11
- Database (include vendor): Postgresql

**Comment by victornoel** [comment]
@lukaseder do you think there is any chance to have it backported to 3.15 maybe? :)

**Comment by lukaseder** [comment]
Thanks for your report.

We're currently supporting `ROWNUM` in the Oracle sense for any input dialect, even if that dialect doesn't natively support it (e.g. at least H2 and Oracle support it, probably a few others).

The question is whether we should:

- Change that behaviour (incompatibly) and support `ROWNUM` in the parser only where it is natively supported
- Try to disambiguate `ROWNUM` via meta lookups and keep the status quo if it can't be found
- Keep the status quo, accepting that what would normally work on PostgreSQL doesn't work in our parser

Since this touches on strategic decisions of the parser, I can't jump to a conclusion here yet. The simple workaround would be to avoid the `ROWNUM` alias.

> @lukaseder do you think there is any chance to have it backported to 3.15 maybe? :)

Given that there doesn't seem a backwards compatible way to do this, I doubt a backport is a good idea, as that is not unlikely to break someone else's assumptions.

**Comment by lukaseder** [comment]
There's obviously another solution to this:

- Keep the status quo, but don't enable the `ROWNUM` transformation and don't reject the syntax in the OSS edition parser.

That one could be backported, if it's the one that's chosen.

**Comment by victornoel** [comment]
ok, thank you for the explanation :)

**Comment by lukaseder** [comment]
I'm still not sure about what the best solution would be here, as this is quite strategic to the parser design - not with respect to commercial-only features, but with respect to reserved keywords, expected dialect specific functionality, etc.

Given that you're requesting a backport, I'm assuming the obvious workaround isn't viable to you? What are you using jOOQ's parser for, specifically? (The more I understand, the better I can decide on how to fix this).

**Comment by victornoel** [comment]
@lukaseder the obvious workaround is indeed applicable, but since the app is parsing arbitrary SQL from the users, we don't easily control that they don't use the `numrow` keyword (well be could rename it on the fly maybe with a regexp… not sure how good an idea this is :P).
Once they face an error, we can tell them, but having a fix directly in jOOQ will save time to everybody :)

**Comment by lukaseder** [comment]
What about all the other keywords / special identifiers? What if they call their column `CURRENT_DATE`, for example, which jOOQ translates to something else, depending on the dialect? What's your general strategy here?

**Comment by lukaseder** [comment]
> What we do exactly is the following, i.e., we want to parse SQL to ensure it's correct before sending it to the db

Well, the parser doesn't guarantee that the *input* SQL will be correct when you send it to the database. It will try to make sure the *output* SQL will work on your target database, though. I feel that's not what you're doing though?

For example, the parser will accept `INSERT .. ON DUPLICATE KEY UPDATE` from MySQL, even if you're using PostgreSQL only. jOOQ (not the parser) will then try to translate that to `INSERT .. ON CONFLICT`, in case you configure the right schema meta data.

> (we could directly use jOOQ to execute it, but we don't, for multiple reasons I'm not 100% clear about :):

You're missing out on a ton of great stuff!

> So if I understand correctly, if a SQL query contains `CURRENT_DATE` as a field, we will get an exception in the OSS version? Or will it simply be transformed to the target dialect?

It will be transformed to the target dialect.

> Or maybe we get the exception only if the reserved keyword is one of the commercial-only dialect?

The point of this exception is to make sure OSS users understand the value of an upgrade to the commercial dialect, so it's a marketing feature. In most cases, this affects commercial-only functions (such as spatial functions), or syntax (such as procedural extensions), i.e. stuff that otherwise wouldn't work either in the OSS edition, failing with a more generic parser exception.

In rare cases, this affects pseudo columns like `ROWNUM`, which the parser should probably still accept and ignore (i.e. treat as ordinary column reference), because it could be an ordinary column reference, as in your case.

In any case, I think I understand your use-case now, and I guess this will help make the right decision about how to fix this bug here, even if I think you're not using jOOQ with the right assumptions in mind. You're now writing "jOOQ-correct" SQL, not "PostgreSQL-correct" SQL. If that's viable to you, then I don't think that this is really a bug for you. You shouldn't use the "jOOQ-ambiguous" `ROWNUM` identifier.

**Comment by lukaseder** [comment]
> So yes, that would be the nice solution from our point of view, like this we don't have to handle that situation ourselves.

OK, but I guess that for now, you will have to. This still needs much more thought, I don't want to rush strategic changes like this (and still can't promise backports). Given that there is potential for other, similar issues, you'll have to do some manual handling anyway.

> Alternatively, could we specify somewhere to jOOQ that we want to parse PostgreSQL-correct SQL?

I don't think that makes sense for jOOQ's parser. jOOQ's parser also supports all other types of jOOQ-SQL, including synthetic syntax, see this grammar for details:
https://www.jooq.org/doc/latest/manual/sql-building/sql-parser/sql-parser-grammar/

It has SPIs to enhance the grammar on various levels (you could actually use that as a workaround for issues like this one here):
https://www.jooq.org/doc/latest/manual/sql-building/sql-parser/sql-parser-listener/

jOOQ creates a "union" of all vendor specific grammars, not an intersection, see also: https://github.com/jOOQ/jOOQ/issues/12803

The main purpose of the parser is to parse everything that can be parsed by the actual dialect, "and more." Primary use-cases are:

- Parse DDL and reverse engineer the model
- Translate between dialects https://www.jooq.org/translate
- Run diagnostics on JDBC based SQL
- Enrich SQL with useful features, in case users use jOOQ-SQL as their primary dialect, and run that on multiple RDBMS

It would be very hard to revert to parsing the exact syntax of various vendors, rejecting what the vendors reject. Most vendors don't even document their grammars formally.

If you want to parse exact PostgreSQL, why not just generate an ANTLR parser based on its grammar?

**Comment by victornoel** [comment]
> OK, but I guess that for now, you will have to. This still needs much more thought, I don't want to rush strategic changes like this (and still can't promise backports). Given that there is potential for other, similar issues, you'll have to do some manual handling anyway.

Yes of course, I wanted to say that ideally, if this is considered and fixed like this, then we will use it. Until then I'm exploring other ways, including handling the situation ourselves, and also to improve my understanding of what is possible.

Thanks for all the other ideas, this is very useful. If we either do something elegant with these, I will share it here so that other can know about it!

**Comment by lukaseder** [comment]
I've been revisiting this issue here and I still can't think of a solution that works in isolation. Of course, we could patch the parser for this *particular* issue to disappear, but nothing would guarantee:

- That it wouldn't pop up again in a slightly different form
- Something similar could happen with a different expression, e.g. `LEVEL`, which is another Oracle pseudo column. Or, while you may appreciate that jOOQ can parse `GENERATE_SERIES()`, a non-PostgreSQL user may expect something different.

Our parser parses the "jOOQ dialect", not strictly the PostgreSQL dialect. We do have a `Settings.parseDialect` setting to help disambiguate things, but it doesn't by any means guarantee strictness. It would be useful to have such strictness at least as an opt in flag (see https://github.com/jOOQ/jOOQ/issues/8826), but so far, the parser hasn't been designed for such purposes. It has been designed to understand *most* SQL and be able to transform it for any purpose.

Once `Settings.parserInputStrictness` (https://github.com/jOOQ/jOOQ/issues/8826) is available, then this issue will go away automatically. Until then, I think this can't really be fixed reasonably.
