### ISSUE TITLE
Multiset too many columns cause query to fail

### ISSUE THREAD

**Issue by Walti91** [jOOQ/jOOQ#12988]
I have a one (Author) to many (Books) relationship between two database tables and I am trying to fetch data from the Author table while also loading all corresponding entries in the Books table via a multiset. The books table is rather big with about 30 columns. If I try to fetch all the data in the Books table the query fails, however if I only select a small subset of the columns it works. I couldn't find anything if this was a known limitation and decided to open this issue.

This is the code I use for the query.
```
var books = multiset(dsl.select(BOOKS.fields()).from(BOOKS).where(BOOKS.AUTHOR_ID.eq(AUTHORS.ID))).convertFrom(record -> record.into(BooksRecord.class));

var mapper = record -> new AuthorWithBooks(record.into(AuthorsRecord.class), record.get(books));

var result = dsl.select(AUTHORS.fields()).select(books).from(AUTHORS).where(AUTHORS.ID.in(authorIds)).fetch(recordMapper);
```

### Expected behavior
A list of authors with all their books.

### Actual behavior
A Runtime exception
```
java.lang.RuntimeException: Error while reading field: multiset(...)
```

### Steps to reproduce the problem
- Create two database tables which have a one to many relationship. The table which represents the many end, in my case the Books, needs to be rather large for the error to occur as explained.
- Try fetching the data of Books table via a multiset as shown in the code above.

### Versions

- jOOQ: 3.15.3
- Java: 17.0.0.35.1-amzn
- Database (include vendor): postgresql 14.1 (brew)
- OS: MacOS 12.0.1
- JDBC Driver (include name if inofficial driver): org.postgresql 42.3.1

**Comment by lukaseder** [comment]
Thanks for your report. There shouldn't be any such limitation of course, and I don't think a specific number of columns is the actual problem here. Before I try to "blindly" reproduce any issue, can you please give a bit more information on how to reproduce it?

1. Are these the exact queries you wrote, or simplifications?
2. What's the complete exception stack trace? (What particular line causes the problem?)
3. What are the table definitions of `AUTHOR` and `BOOK` (`CREATE TABLE`..., I'm mostly interested in specific data types you're using)

**Comment by lukaseder** [comment]
Also:

4. Given that we've fixed a ton of `MULTISET` related bugs, does the problem persist with jOOQ 3.15.7 or 3.16.3?

**Comment by Walti91** [comment]
Thanks for the quick response. A update to version 3.16.3 fixed the problem.

**Comment by lukaseder** [comment]
Thanks a lot. I'm glad I suggested the upgrade, and that it works now, for you :)
