### ISSUE TITLE
org.jooq.Geometry improvements

### ISSUE THREAD

**Issue by gpor0** [jOOQ/jOOQ#13041]
### Use case:

Jooq 3.16 brings new useful Spacial support which brings `org.jooq.Geometry` class which responsibility is:
- to hold the spacial data
- to provide ORM mapping (using special Class) between database types (per each RDBMS) and Java object model.

It looks like automatic conversion is (currently) supported only in commercial versions of Jooq so additional development is needed to implement GeometryBinding for your specific RDBMS. This is simply the decision for authors to give us the solution for non-commercial use.

Another issue is that `org.jooq.Geometry` accepts spacial data only as String therefore transformation between Strings and byte arrays is painful and non performant. For example if you use own implementation of [https://github.com/simplegeo/jts](JTS) you end up with having complicated mapping from and to persistence as presented in workarounds.

### Possible solution you'd like to see:

I don't have insights at the moment into how this is handled by other RDBMS but I believe it would be best to change `org.jooq.Geometry` class in a way to contain byte array instead of String.

It would be very nice to have a possibility to include some spacial transformations into the `org.jooq.Geometry` itself e.g. `org.jooq.Geometry.createPoint(longitude, latitude)` which outputs WKB data in byte array which is then stored into RDBMS without needing external libraries for conversion.

### Possible workarounds:

```
1. I need to create JTS object in my business logic since I have all the support (spacial operations) in the provided library.
2. I set the value if type JTS into the Record and execute insert to the database
3. Geometry binding needs to output WKB which has type of byte[]
4. Array of bytes must be transformed to `org.jooq.Geometry` String using base64 encoding
5. Geometry Binding needs to decode base64 encoded string back to byte array and pass it down to RDBMS as BINARY.
 ```

### Versions:

- jOOQ: 3.16
- Java: 11
- Database (include vendor): MariaDB 10.5

**Comment by lukaseder** [comment]
Thanks a lot for your report and for your patience. You have a lot of valid points, some of which are already in this list of planned improvements, others not yet: https://github.com/jOOQ/jOOQ/issues/12736


> It looks like automatic conversion is (currently) supported only in commercial versions of Jooq so additional development is needed to implement GeometryBinding for your specific RDBMS. This is simply the decision for authors to give us the solution for non-commercial use.

As also explained in my Stack Overflow answer here (https://stackoverflow.com/a/71054362/521799), this is an unfortunate fact whenever we add support for a new data type out of the box in `SQLDataType`. While before the support, a `Binding<Object, U>` had worked, now a `Binding<Geometry, U>` is required.

A feature request exists to make `Binding` more independent of `Converter`:

- https://github.com/jOOQ/jOOQ/issues/4819

While a `Binding` may choose to implement no `Converter` at all (only the `Class<T>` and `Class<U>` literals are required, not the conversion functions), this isn't clear from the docs or API design, so an upgrade appears difficult. Especially confusing when the `Geometry` type is involved, which you understandably don't want to use (and in fact, don't have to, in the `Binding` implementation).

I've also created a feature request to be able to opt out of the individual jOOQ-specific data types, i.e. to allow for pretending jOOQ doesn't yet know `GEOMETRY` (or `JSON`, `XML`, etc.)

- https://github.com/jOOQ/jOOQ/issues/13143

I think that latter issue would have been great to have when you upgraded to jOOQ 3.16. It will definitely be helpful in the future, as we plan to add support for more types.

> Another issue is that `org.jooq.Geometry` accepts spacial data only as String therefore transformation between Strings and byte arrays is painful and non performant. For example if you use own implementation of [https://github.com/simplegeo/jts](JTS) you end up with having complicated mapping from and to persistence as presented in workarounds.

Yes, that's true if you want to use the `Geometry` type and the new API. The task list has a bullet to add support for a `byte[]` WKB representation of a geometry:

- https://github.com/jOOQ/jOOQ/issues/12736

There's also a task that aims for offering out of the box support for third party libraries, mostly JTS:

- https://github.com/jOOQ/jOOQ/issues/12738

Obviously, that's something most people want, but it wasn't possible to implement this in jOOQ 3.16 without delaying the project indefinitely. People have been waiting and upvoting https://github.com/jOOQ/jOOQ/issues/982 for a long time, so, like many projects in jOOQ (e.g. also the parser), this is now an "MVP", which will be improved continually.

> I don't have insights at the moment into how this is handled by other RDBMS but I believe it would be best to change `org.jooq.Geometry` class in a way to contain byte array instead of String.

I don't think a change is the ideal approach. You'd be surprised how many dialects default to a string representation (not just for this type. In PostgreSQL, even UDTs are serialised in some string format, regrettably). Then, there's Oracle which serialises an entirely different, internal representation that is neither WKB nor WKT, nor does it support everything that WKB or WKT support. A `String` based implementation was the right choice at first. Of course, this will be improved eventually. 

> It would be very nice to have a possibility to include some spacial transformations into the `org.jooq.Geometry` itself e.g. `org.jooq.Geometry.createPoint(longitude, latitude)` which outputs WKB data in byte array which is then stored into RDBMS without needing external libraries for conversion.

I've thought about this, but where would we stop? How would you combine such geometries without parsing the internal representation again? Or should we implement a full fledged model, instead? Just as with JSON or XML, a low level representation seemed optimal at first. After all, this is what JDBC drivers offer as well: Low level representations.

I'm closing this issue here as most suggestions are already addressed in the big task list #12736. If the out of the box support isn't ready for you, then I suggest working around it by updating your bindings. It's a few minutes of work, but you'll see that everything will work with `Binding<Geometry, U>` as it did with `Binding<Object, U>`, and you can completely ignore the fact that the `Geometry` type is involved.

**Comment by lukaseder** [comment]
https://github.com/jOOQ/jOOQ/issues/13143 has been implemented for jOOQ 3.17.0 and 3.16.5. The latter should be released this week. This will allow for opting out of recognising the `GEOMETRY` and `GEOGRAPHY` types in the code generator, treating them as `SQLDataType.OTHER`, as before.

**Comment by lukaseder** [comment]
The documentation for this new feature is here: https://www.jooq.org/doc/latest/manual/code-generation/codegen-advanced/codegen-config-generate/codegen-generate-extended-types/

**Comment by lukaseder** [comment]
I've also updated my answer on Stack Overflow: https://stackoverflow.com/a/71054362/521799
