### ISSUE TITLE
Empty DSL array cast issues

### ISSUE THREAD

**Issue by juriad** [jOOQ/jOOQ#13046]
### Your question:

This is rather a remark because I don't know what the solution should look like.

Imagine a table with a single column of type `UUID[]`:
```
ctx.createTableIfNotExists("a").column("b", SQLDataType.UUID.getArrayDataType()).execute();
```

Then this query fails:
```
ctx.insertInto(DSL.table("a"))
                .values((Object) new UUID[0])
                .values(DSL.array())
                .values(DSL.val(new UUID[0], SQLDataType.UUID.getArrayDataType()))
                .execute();
```
with:
```
org.jooq.exception.DataAccessException: SQL [insert into a values (?::uuid[]), (array[]::int[]), (?::uuid[])]; ERROR: column "b" is of type uuid[] but expression is of type integer[]
  Hint: You will need to rewrite or cast the expression.
  Position: 37
```

That also suggests us the workaround; the first and third option works; the first one is not universal though because many places require a field (`DSL.select(new UUID[])`does not work).

I hit this issue because our arrays have dynamic lengths, and they are sometimes empty (ancestor ids in trees). I assume that the best option for us is to never use `DSL.array()` but always use `DSL.val()` instead.

https://github.com/jOOQ/jOOQ/blob/main/jOOQ/src/main/java/org/jooq/impl/Array.java#L105
I understand that jOOQ simply cannot do anything better when there is no information (type erasure prevents it). It already tries more than is needed (it works for the common case of int arrays - and without the explicit cast, it would not work there either).

Maybe it would be good to extend the JavaDoc to warn about the empty array/collection case?

### Versions:

- jOOQ: 3.16.4
- Java: 11
- Database (include vendor): Postgres 14
- OS:
- JDBC Driver (include name if inofficial driver):

**Comment by lukaseder** [comment]
Thanks a lot for your message and for your patience.

I'm curious why there was an `::int[]` cast, specifically, and not e.g. a `::text[]` cast, which may have been a bit more generic. Maybe, because of the PostgreSQL error message?

```sql
create table t (v text[])
insert into t values (array[]);
```

Resulting in:

> SQL Error [42P18]: ERROR: cannot determine type of empty array
>  Hint: Explicitly cast to the desired type, for example ARRAY[]::integer[].
>  Position: 23

We might as well not do explicit casts and let the database try to infer the type if it can, though there are a few integration tests that rely on jOOQ being able to "echo" back an empty `Object[]` this way, so perhaps someone has already started relying on this. On the other hand, users would just have to follow the PG error message and write `array().cast(INTEGER.getArrayDataType())`, then.

> Maybe it would be good to extend the JavaDoc to warn about the empty array/collection case?

Maybe, we could document this, but then again, the PG error message already tells you what to do? In my opinion, this occasional lack of type inference capability in PG is a limitation that should mostly be addressed there. I don't see why an empty array of unknown type can't be inserted into a table...

> I assume that the best option for us is to never use `DSL.array()` but always use `DSL.val()` instead.

Well, if you have a bind value, then yes, please use `DSL.val()` (because that will produce a single bind value, rather than N bind values for an `ARRAY[?, ?, ..., ?]` expression). The `DSL.array()` constructor is for creating array literals from other expressions.

**Comment by juriad** [comment]
All clear, thanks for the explanation. I did not realize that `array().cast(INTEGER.getArrayDataType())` is also possible. That provides another working option. As you say, it is best to decide based on whether we want to bind the whole array or not.

In theory, jOOQ could auto-cast empty arrays when the type is known (such as in insert when `columns` contains fields knowing their DataType or when the table knows its columns). Sounds like a lot of conditions need to be satisfied, when testing will find the issue and suggest a fix, as you say. If only the database was able to do that...

If we use the correct array literals:
```
postgres=# create table x (i int[], u uuid[], t text[]);
CREATE TABLE
postgres=# insert into x values ('{}', '{}', '{}');
INSERT 0 1
postgres=# insert into x values (array[], array[], array[]);
ERROR:  cannot determine type of empty array
LINE 1: insert into x values (array[], array[], array[]);
                              ^
HINT:  Explicitly cast to the desired type, for example ARRAY[]::integer[].
```

Postgres has special handling of literals in certain contexts; here I am most interested in INSERT and UPDATE (see value storage in https://www.postgresql.org/docs/current/typeconv-overview.html and https://www.postgresql.org/docs/current/typeconv-query.html). The format looks like this for arrays: https://www.postgresql.org/docs/current/arrays.html#ARRAYS-INPUT and using array constructor: https://www.postgresql.org/docs/current/sql-expressions.html#SQL-SYNTAX-ARRAY-CONSTRUCTORS. The should hopefully explain why `'{}'` works and `array[]` not. 

If jOOQ instead generated '{}' for empty arrays the cast would not be needed in more places. It also works for unions:
```
postgres=# select array[1,2,3] union select '{}';
  array  
---------
 {}
 {1,2,3}
(2 rows)
```

I did not know about this until you mention that Postgres should be able to handle untyped empty arrays.

**Comment by lukaseder** [comment]
> In theory, jOOQ could auto-cast empty arrays when the type is known (such as in insert when `columns` contains fields knowing their DataType or when the table knows its columns)

Yes, but the infrastructure for that isn't available yet, and this hypothetical feature goes far beyond just `INSERT .. VALUES` type inference. E.g. this and many other similar issues would have to work as well: https://github.com/jOOQ/jOOQ/issues/11015

> he format looks like this for arrays: https://www.postgresql.org/docs/current/arrays.html#ARRAYS-INPUT and using array constructor: https://www.postgresql.org/docs/current/sql-expressions.html#SQL-SYNTAX-ARRAY-CONSTRUCTORS. The should hopefully explain why `'{}'` works and `array[]` not.

In principle, it would be possible to generate PG specific array literals, but it seems like an investment with a poor cost/benefit ratio:

- The current syntax is standard SQL, also supported by H2, HSQLDB, and every future RDBMS that chooses to implement the standard
- It already works apart from a few edge cases like this one
- The PG specific syntax was already hard enough to parse when reading arrays. Generating it would have quite a few edge cases, I suspect, leading to a lot of extra work, when `ARRAY[]` works nicely
- The PG array literal is only an array literal once explicitly or implicitly cast to the inferred array type. Otherwise, it's just a string, so we can't just render `{}` for an empty array. We'd still have to cast it to some array type.

Anyway, it's good to keep in mind in case there's ever an edge case where this trick solves a problem the standard literal cannot solve.
