### ISSUE TITLE
Generate convenience methods for common MULTISET and ROW nestings - Discussion

### ISSUE THREAD

**Issue by alf** [jOOQ/jOOQ#13063]
### Use case:

Currently it’s possible to use fields from related tables using implicit joins in the many to one-direction. Thus the joined table has zero or one rows for each row in the referring table.

With the new multiset-functionality it should be possible to give similar functionality in the one to many-direction.

### Possible solution you'd like to see:

```
dsl.select(
    ALBUM.TITLE,
    ALBUM.tracks(
        TRACK.NUMBER,
        TRACK.TITLE,
        TRACK.LENGTH
    )
).from(ALBUM)
```

**Comment by lukaseder** [comment]
Thanks a lot for your feature request.

Implicit to-many joins are a topic of this issue here: https://github.com/jOOQ/jOOQ/issues/12037. At the time implicit joins were implemented, `MULTISET` has not yet been a thing, so those options haven't been explored yet. I think you're definitely onto something.

In fact, there are also ideas of using ordinary correlated subqueries for implicit join emulations, rather than left/inner joins (at least offer making this configurable), so in that case, the to-many case wouldn't be so much different.

The simplest reasonable implicit to-many join would be:

```java
Field<Result<TrackRecord>> albums = ALBUM.tracks();
```

A 22-fold set of overloads of the form ...

```java
<T1, T2, T3> Field<Result<Record3<T1, T2, T3>>> tracks(
    TableField<TrackRecord, T1> f1,
    TableField<TrackRecord, T2> f2,
    TableField<TrackRecord, T3> f3
);
```

... seems reasonable at first, but it's also quite limited:

- It requires the usual 22 overloads for type safety
- It wouldn't allow for arbitrary expressions (unless we waive the type safety on the column projection that you were suggesting?)
- It doesn't allow for using any other convenient `SELECT` feature, including `DISTINCT`, `WHERE`, `ORDER BY`, `LIMIT`, etc. (while `GROUP BY`, `HAVING`, `UNION` seem less useful, but why not `WINDOW`, `QUALIFY`?)

Of course, any time someone runs into the above limitations, they can revert to manually writing the `MULTISET` and correlating it to the outer query, but there will be a lot of complaints about "ok, but why not just* support at least `LIMIT`, which is important to me".

I've been thinking about this for a while now, but haven't found the right solution yet, and where to draw the line.

Having said so,  I really like your way of thinking here. Keep thinking about this, or suggesting alternatives. I think the general idea is a must have in jOOQ, but the best execution is far from obvious.

**Comment by lukaseder** [comment]
Taking your idea a step further, what has always really annoyed me when writing examples is to project `MULTISET` nested collections of many-to-many relationships. I think there's even more potential in this area. Keeping to your suggested syntax, imagine:

```java
ctx.select(
       ACTOR.FIRST_NAME,
       ACTOR.LAST_NAME,
       ACTOR.film(
           FILM.TITLE,
           FILM.category(CATEGORY.NAME)
       )
   )
   .from(ACTOR)
   .fetch();
```

Observe the nesting. This would be equivalent to the much more verbose, semi-explicit (still using implicit to-one joins):

```java
ctx.select(
       ACTOR.FIRST_NAME,
       ACTOR.LAST_NAME,
       multiset(
           select(
               FILM_ACTOR.film().TITLE,
               multiset(
                   select(FILM_CATEGORY.category().NAME)
                   .from(FILM_CATEGORY)
                   .where(FILM_CATEGORY.FILM_ID.eq(FILM_ACTOR.FILM_ID))
               )
           )
           .from(FILM_ACTOR)
           .where(FILM_ACTOR.ACTOR_ID.eq(ACTOR.ID))
       )
   )
   .from(ACTOR)
   .fetch();
```

Or this completely explicit version:

```java
ctx.select(
       ACTOR.FIRST_NAME,
       ACTOR.LAST_NAME,
       multiset(
           select(
               FILM.TITLE,
               multiset(
                   select(CATEGORY.NAME)
                   .from(FILM_CATEGORY)
                   .join(CATEGORY).on(FILM_CATEGORY.CATEGORY_ID.eq(CATEGORY.CATEGORY_ID))
                   .where(FILM_CATEGORY.FILM_ID.eq(FILM_ACTOR.FILM_ID))
               )
           )
           .from(FILM_ACTOR)
           .join(FILM).on(FILM.FILM_ID.eq(FILM_ACTOR.FILM_ID))
           .where(FILM_ACTOR.ACTOR_ID.eq(ACTOR.ID))
       )
   )
   .from(ACTOR)
   .fetch();
```

The brevity of the implicit many-to-many join example is very compelling

**Comment by lukaseder** [comment]
A caveat of your syntax suggestion:

```java
dsl.select(
    ALBUM.TITLE,
    ALBUM.tracks(
        TRACK.NUMBER,
        TRACK.TITLE,
        TRACK.LENGTH
    )
).from(ALBUM)
```

... is the apparent ambiguity in the presence of another `TRACK` table in scope, such as:

```java
dsl.select(
    ALBUM.TITLE,
    ALBUM.tracks(
        TRACK.NUMBER,
        TRACK.TITLE,
        TRACK.LENGTH
    )
).from(ALBUM, TRACK)
```

Now, it wouldn't be simple to disambiguate between the outer `TRACK` table and the implicit `TRACK` table. Some sort of lambda syntax could help resolve this, e.g.


```java
dsl.select(
    ALBUM.TITLE,
    ALBUM.tracks(track -> row(
        track.NUMBER,
        track.TITLE,
        track.LENGTH
    ))
).from(ALBUM)
```

The price to pay here is that such a syntax would be weird and quite unprecedented.

Clearly, there's still a lot of design work to do.

**Comment by alf** [comment]
I updated my initial suggestion with an expanded version. I believe the potential here is huge, but I agree that it’s best to go slow here.

**Comment by lukaseder** [comment]
> I updated my initial suggestion with an expanded version.

Thanks for the update. Going forward, I think comments will work better than edits. I'd like to comment on your edit now, but it will be confusing when this issue is re-visited...

(The issue will probably be replaced by a more clear issue, once the picture is clearer, and merged with #12037)

**Comment by alf** [comment]
I realized my error in editing my initial message and will replace the edit with a comment.

**Comment by alf** [comment]
For more advanced stuff we’d have to be a bit more creative. The following isn’t quite there yet, but it feels pretty intuitive to me. The missing piece is how we make it into a multiset:

```
dsl.select(
    ALBUM.TITLE,
    ALBUM.tracks(select(
        TRACK.NUMBER,
        TRACK.TITLE,
        TRACK.LENGTH
    )).where(TRACK.LENGTH.lt(5))
).from(ALBUM)
```

The idea is that in addition to the 22-fold set of overloads we’ve already discussed, there can be a `SelectFromStep<R>` overload that returns a `SelectConditionStep<R>`. The details might be off here, but hopefully you get the gist.

As I mentioned, I think the missing part here is that this must be wrapped in a multiset. Since I’m already quite out of my depth with regards to the consequences this idea entails, I’ll leave it here for now.

**Comment by alf** [comment]
I think it is a good idea to prefix the multiset-implicit join with something, as a plural s is too subtle and also not necessarily correct since it assumes English table names.

**Comment by lukaseder** [comment]
Regarding the suggestion here:

```java
dsl.select(
    ALBUM.TITLE,
    ALBUM.tracks(select(
        TRACK.NUMBER,
        TRACK.TITLE,
        TRACK.LENGTH
    )).where(TRACK.LENGTH.lt(5))
).from(ALBUM)
```

In summary, this "simplifies" `from(TRACK).where(TRACK.ALBUM_ID.eq(ALBUM_ID))` to `ALBUM.tracks(...)`, at the cost of:

- opening up the caveat of ambiguous `TRACK` references
- introducing either new DSL for `SELECT` or making unprecedented assumptions about an implicit, correlated `FROM` clause

At this point, I'm not convinced we've gained much. The solution to both the above problems would be:

```java
dsl.select(
    ALBUM.TITLE,
    ALBUM.track(t -> 
        select(
            t.NUMBER,
            t.TITLE,
            t.LENGTH
        )
        .from(t)
        .where(t.LENGTH.lt(5)
    )
).from(ALBUM)
```

Where `track` is aliased with an implicit path alias and it's actually an `InlineDerivedTable`, similar to the existing `TRACK.where(Condition)` API, which could be re-used to correlate the `track` table transparently to the outer query.

Now, we've still gained a little bit (i.e. the auto-correlation), but not *that* much.

> I think it is a good idea to prefix the multiset-implicit join with something, as a plural s is too subtle and also not necessarily correct since it assumes English table names.

Yeah. It's good to be clear about the fact that naming has issues, but this can be decided later on.

**Comment by alf** [comment]
I prefer your lambda-based version, it’s more obvious what’s going on.

**Comment by lukaseder** [comment]
> I prefer your lambda-based version, it’s more obvious what’s going on.

Also, given that it is called *and then* produces the correlated subquery, it doesn't require some complex SQL transformation to implement the implicit stuff.

But again, it's unprecedented in terms of API design, so that's a slippery slope. I'm pretty sure there will be much better solution, eventually.

> For the base case where we don’t need fancy stuff, the original suggestion is pretty good though. 🤩

Yes, it's compelling in simplicity, but it also doesn't scale well in terms of API evolution. For every step taken, other doors of opportunity close as we cannot generate infinite overloads of infinite variants of similar features.

**Comment by lukaseder** [comment]
> > For the base case where we don’t need fancy stuff, the original suggestion is pretty good though. 🤩
> 
> Yes, it's compelling in simplicity, but it also doesn't scale well in terms of API evolution. For every step taken, other doors of opportunity close as we cannot generate infinite overloads of infinite variants of similar features.

To be clear: I'm not rejecting it, I'm just saying that the two suggestions do look mutually exclusive.

Another perspective that is in favour of your original suggestion is that it does remind me of GraphQL: https://graphql.org/learn/queries/

**Comment by alf** [comment]
Let’s leave it to brew. It’ll be awesome when it areives 😎

**Comment by lukaseder** [comment]
After some good nights' sleep on this, it seems clear that the lambda approach, despite being unprecedented, seems to have multiple benefits here:

1. It prevents having to overload the navigational method 22+1 times for all the usual `Record[N]` type safety, which could be quite a problem depending on the schema complexity (e.g. a parent table h having dozens of child tables), and the availability of this feature also for many-to-many relationships
2. If the lambda argument is the aliased table, then we can operate on it e.g. using `Table.where` for simple cases, leading to convenience like the below:

**This:**

```java
dsl.select(
    ALBUM.TITLE,
    ALBUM.track(t -> 
        selectFrom(t)
        .where(t.LENGTH.gt(5))
    )
).from(ALBUM)
```

**Could be simplified to this:**

```java
dsl.select(
    ALBUM.TITLE,
    ALBUM.track(t -> t.where(t.LENGTH.gt(5)))
).from(ALBUM)
```

We already have a `Table::where` clause, which is very useful to produce so-called `InlineDerivedTables` (which needs documentation in the manual: https://github.com/jOOQ/jOOQ/issues/13065)

Such `InlineDerivedTables` could also profit from another, not-yet-implemented convenience: additional projections. In that case, you could write this, to :

```java
dsl.select(
    ALBUM.TITLE,
    ALBUM.track(t -> t
        .select(t.NUMBER, t.TITLE, t.LENGTH)
        .where(t.LENGTH.gt(5))
    )
).from(ALBUM)
```

This would look similar to your original example in terms of being minimal:

```
dsl.select(
    ALBUM.TITLE,
    ALBUM.tracks(select(
        TRACK.NUMBER,
        TRACK.TITLE,
        TRACK.LENGTH
    )).where(TRACK.LENGTH.lt(5))
).from(ALBUM)
```

But takes care of:

- The difficult to define semantics of an implicit `FROM` clause, which correlates the subquery
- The possibly ambiguous `TRACK` table, in case the outer scope also declares such a table

At the same time, the lambda can return any type of table (even a completely unrelated one), and that resulting table will be the `MULTISET` content, so there is no magic in this feature at all, and it's purely code generated sugar.

At the same time, the new `Table.select()` syntax would be generally useful, not just for this feature. It would now be even simpler to quickly generate a derived table for dynamic SQL usage, something that is otherwise quite tedious in jOOQ. I've created a separate feature request for this: https://github.com/jOOQ/jOOQ/issues/13066, an improvement that would take care of further simplification, but can still be implemented later on (it has a few caveats and tricky edge cases where the derived table cannot be inlined).

I think I'll prototype this during this week to see how it feels, and if there's other potential for a lambda accepting API design (previous experiments have been deprecated again: https://github.com/jOOQ/jOOQ/issues/10156)

**Comment by lukaseder** [comment]
Another thing that is related is the idea to be able to nest rows this way, including parent rows from to-one relationships. Take this Stack Overflow question for example:
https://stackoverflow.com/q/71090417/521799

It was requesting a feature like https://github.com/jOOQ/jOOQ/issues/4727, where a `Table<R>` expression can be projected to nest `R`, such as:

```java
Result<Record2<String, AlbumRecord>>
dsl.select(TRACK.TITLE, TRACK.album())
   .from(TRACK)
   .fetch();
```

This is using the classic implicit join syntax, which could also be spelled out explicitly. What if we wanted to project `ALBUM` columns *and* nest the results? We can certainly write:


```java
dsl.select(
        TRACK.TITLE, 
        row(
            TRACK.album().ID,
            TRACK.album().TITLE
        )
   )
   .from(TRACK)
   .fetch();
```

But the new syntax seems compelling for that use-case as well:

```java
dsl.select(
        TRACK.TITLE, 
        TRACK.album(a -> a.select(a.ID, a.TITLE))
   )
   .from(TRACK)
   .fetch();
```

Assuming that both https://github.com/jOOQ/jOOQ/issues/4727 and https://github.com/jOOQ/jOOQ/issues/13066 are available

If we clean up the naming to avoid confusion:

- `CHILD.parent()` produces a `Table<ParentRecord>` expression using the old implicit join feature
- `<O> CHILD.parentRow(Function<? super Table<R>, ? extends TableLike<O>>)` produces a `Row[N]` which extends `SelectField<R>`
- `<O> CHILD.parentMultiset(Function<? super Table<R>, ? extends TableLike<O>>)` produces a `Field<Result<R>>` (we might introduce a `Multiset<R>` subtype of `Field<Result<R>>` in the future, see https://github.com/jOOQ/jOOQ/issues/12031)

**Comment by lukaseder** [comment]
A somewhat related feature request: https://github.com/jOOQ/jOOQ/issues/13067, turning `Field<Result<R>>` expressions into `SelectField<R>` expressions

**Comment by alf** [comment]
Looks very promising. Let me know if you need help testing this.

**Comment by lukaseder** [comment]
> Looks very promising. Let me know if you need help testing this.

Thanks for your offer, that would be great. I'll let you know when something testable is ready.

**Comment by lukaseder** [comment]
Looks like there's another prerequisite that I wrongly assumed was already implemented in order to achieve the (type safe) lambda version: https://github.com/jOOQ/jOOQ/issues/8012

Without this type safety, the lambda version wouldn't be as powerful as it looked in the examples.

**Comment by lukaseder** [comment]
Some interesting special cases that we shouldn't consider with our many-to-many heuristics were shared here:
https://twitter.com/lukaseder/status/1493501341590863875

They include:

- `one-to-many` relationship tables (where a FK has a `UNIQUE` constraint)
- `many-to-many-to-many` relationship tables (where there are more than 2 FKs)
- Accidental relationships (where there is no `UNIQUE` key on the 2 FKs)

**Comment by lukaseder** [comment]
@alf I'm curious about your database design, related to the previous comment. E.g. do all of your relationship tables have `UNIQUE` or `PRIMARY KEY` constraints on their foreign keys? Do you ever have a `one-to-many` relationship table with a `UNIQUE` key on a `FOREIGN KEY`?

**Comment by alf** [comment]
We point jOOQ at a schema consisting of views. We’ve created primary, unique and foreign keys on these views with the “disable novalidate” option set. Most of this is automated based on existing keys on our actual tables.

We do make use of unique keys and foreign keys pointing at these. The reason for this is an unfortunate design where many of our base tables have primary keys that contain sensitive data.

Because of this we also have duplicated fks that represent the same path but are used for different things:

1. Joining using the actual underlying keys
2. Creating external IDs that we can expose to our users. These keys have replaced the secret parts of the keys with a surrogate component instead. 

Hope this makes sense. Feel free to follow up with more questions.

One thing that’s problematic for us with this setup is that the relationships on our views makes it hard to change them. We must drop the keys, change the views and then re-create the keys. Because of this I’m speculating that maybe we’d be better off moving these relationships into the jooq configuration instead of keeping it in the database.

**Comment by lukaseder** [comment]
> We’ve created primary, unique and foreign keys on these views with the “disable novalidate” option set. Most of this is automated based on existing keys on our actual tables.

Oh, interesting, I wasn't aware that jOOQ would pick up constraints on views yet. I guess it doesn't matter to the Oracle dictionary views, whether the constraint is on a view or on a table?

> Because of this I’m speculating that maybe we’d be better off moving these relationships into the jooq configuration instead of keeping it in the database.

Assuming you mean synthetic constraints, then to jOOQ, it makes no difference indeed. But I would imagine that your optimiser would prefer knowing some additional things? Cardinality estimates are usually better with unique constraints, and join elimination also relies on constraints. Though, with `DISABLE NOVALIDATE`, that probably doesn't apply anyway.

**Comment by alf** [comment]
Yes, the constraints are visible in all_constraints etc as if the views were tables.

My gut feeling is that the query planner doesn’t use these keys for anything much. Instead the keys and indexes on the underlying tables will be used for optimizing the queries.

**Comment by lukaseder** [comment]
A few days into implementing this feature, I can say:

- The code generation logic is simple and manageable
- The runtime logic using the lambda is intricate and full of pitfalls

The latter is a concern, but also an opportunity:

- The feature can currently only be reasonably implemented using the new jOOQ 3.16 query object model (`QOM`) transformations. E.g. the `Select` produced by the lambda expression needs to be patched with a correlation predicate and a join expression. If the `Select` already contains joins, or if it aliases the lambda argument table, transformations are necessary. There are probably more such cases.
- This means that we get both greater test coverage, and more dogfooding for the QOM transformations. A few `MULTISET` related bugs have already been addressed:
  - https://github.com/jOOQ/jOOQ/issues/13080
  - https://github.com/jOOQ/jOOQ/issues/13081
  - https://github.com/jOOQ/jOOQ/issues/13082
- Some additional features seem to be required, which are generally very useful, including:
  - https://github.com/jOOQ/jOOQ/issues/8012
  - https://github.com/jOOQ/jOOQ/issues/12031
  - https://github.com/jOOQ/jOOQ/issues/13065
  - https://github.com/jOOQ/jOOQ/issues/12045 (this one would be really great!)

Still, if there's a better syntax that doesn't allow for complete liberty of `select()` creation (which relies on some SQL transformations), but still offers the expected convenience, this feature might still change. Otherwise, it might still be rejected...

**Comment by lukaseder** [comment]
On the flip side, I just added this integration test:

```java
record Author(String firstName, String lastName) {}    
record Book(int id, String title, Author author) {}    
record Language(int id, String cd, List<Book> books) {}

List<Language> r =
ctx.select(
        T_LANGUAGE.ID,
        T_LANGUAGE.CD,
        T_LANGUAGE.tBookMultiset(b -> select(
            b.ID, b.TITLE,
            row(
                b.tAuthor().FIRST_NAME, -- Implicit joins
                b.tAuthor().LAST_NAME
            ).mapping(Author::new) -- Nested row mappings
        ).from(b)).convertFrom(x -> x.map(mapping(Book::new))) -- Multiset mapping
    )
   .from(T_LANGUAGE)
   .orderBy(T_LANGUAGE.ID)
   .fetch(mapping(Language::new)); -- Result mapping
```

And it worked out of the box, all type checked, no reflection, etc!

XML emulation:

```sql
select
  t_language.ID,
  t_language.CD,
  (
    select xmlelement(
      name result,
      xmlagg(xmlelement(
        name record,
        xmlelement(name v0, v0),
        xmlelement(name v1, v1),
        xmlelement(name v2, v2)
      ))
    )
    from (
      select
        t_book.ID as v0,
        t_book.TITLE as v1,
        xmlelement(
          name record,
          xmlelement(name v0, alias_33683684.FIRST_NAME),
          xmlelement(name v1, alias_33683684.LAST_NAME)
        ) as v2
      from (
        t_book
          join t_author as alias_33683684
            on t_book.AUTHOR_ID = alias_33683684.ID
        )
      where t_book.LANGUAGE_ID = t_language.ID
    ) as t
  )
from t_language
order by t_language.ID
```

JSONB emulation:

```
select
  t_language.ID,
  t_language.CD,
  (
    select coalesce(
      jsonb_agg(jsonb_build_array(v0, v1, v2)),
      jsonb_build_array()
    )
    from (
      select
        t_book.ID as v0,
        t_book.TITLE as v1,
        jsonb_build_array(alias_33683684.FIRST_NAME, alias_33683684.LAST_NAME) as v2
      from (
        t_book
          join t_author as alias_33683684
            on t_book.AUTHOR_ID = alias_33683684.ID
        )
      where t_book.LANGUAGE_ID = t_language.ID
    ) as t
  )
from t_language
order by t_language.ID
```

Result:

```
+----+----+--------------------------------------------------+
|  ID|CD  |multiset                                          |
+----+----+--------------------------------------------------+
|   1|en  |[Book[id=1, title=1984, author=Author[firstName...|
|   2|de  |[Book[id=4, title=Brida, author=Author[firstNam...|
|   3|fr  |[]                                                |
|   4|pt  |[Book[id=3, title=O Alquimista, author=Author[f...|
+----+----+--------------------------------------------------+
```

I mean, it's a really convenient feature! 👌

**Comment by alf** [comment]
As long as jOOQ handles the pitfalls of the runtime logic then I’m happy. 🤞
