### ISSUE TITLE
Custom table alias

### ISSUE THREAD

**Issue by esfomeado** [jOOQ/jOOQ#13106]
### Your question:

This example is based on the documentation. Lets say that I having the following custom table.

```
public class BookTable extends CustomTable<BookRecord> {
    public static final BookTable BOOK = new BookTable();

    public final TableField<BookRecord, String> FIRST_NAME = createField(name("FIRST_NAME"), VARCHAR);
    public final TableField<BookRecord, String> UNMATCHED  = createField(name("UNMATCHED"), VARCHAR);
    public final TableField<BookRecord, String> LAST_NAME  = createField(name("LAST_NAME"), VARCHAR);
    public final TableField<BookRecord, Short>  ID         = createField(name("ID"), SMALLINT);
    public final TableField<BookRecord, String> TITLE      = createField(name("TITLE"), VARCHAR);

    protected BookTable() {
        super(name("BOOK"));
    }

    @Override
    public Class<? extends BookRecord> getRecordType() {
        return BookRecord.class;
    }
}

public class BookRecord extends CustomRecord<BookRecord> {
    protected BookRecord() {
        super(BookTable.BOOK);
    }
}
```

Now I want to give another alias to the table so I can use it on a join:
`Table<BookRecord> aliasOfBook = BOOK.asTable("alias");`

That issue is that it returns a `Table` instead of a `BookTable` and if I want to reference some field I have to do this:
`aliasOfBook.field(FIRST_NAME.getName(), String.class)` or some variation of this.

Is there a cleaner way of doing this?

Thanks

### Versions:

- jOOQ: 3.14.14
- Java: Java 8
- Database (include vendor): Postgres 13.4
- OS: Windows 10
- JDBC Driver (include name if unofficial driver): https://mvnrepository.com/artifact/org.postgresql/postgresql/42.2.22

**Comment by lukaseder** [comment]
I'm assuming you have a good reason not to use the code generator to get access to all of this convenience? https://blog.jooq.org/why-you-should-use-jooq-with-code-generation

It also generates typed alias constructors for you. The `CustomTable` doesn't expose those internal constructors from `TableImpl`, so if you want to replicate that part of the code generator behaviour, perhaps better extend the internal `TableImpl` directly, just like the code generated by the code generator?

**Comment by lukaseder** [comment]
> Yes, we have a set of "temporary" tables that we create dynamically that we moved from SQL to Java (jOOQ).

Would it be an option to declare those in SQL nonetheless, and generate code for them? Or are they completely dynamic?

> Is there any plans to expose more of `TableImpl` on `CustomTable`?

There's https://github.com/jOOQ/jOOQ/issues/7444 to (possibly) re-design these things. Alternatively `CustomTable` might work better, too. But ultimately, the question is what value is it really providing? Because it relies on internal API just the same. If `TableImpl` ever changes fundamentally, then `CustomTable` would have to be deprecated / removed as well.

> Is even a good idea to extend `TableImpl`?

There can be breaking changes between minor releases, as it's internal API. But that could be something manageable?

**Comment by esfomeado** [comment]
I guess one possible solution at least for my problem is to expose on the `CustomTable` the constructors from `TableImpl` that create an aliased table.

I think it's a small change on jOOQ side but that it would greatly improve my day to day work.

**Comment by lukaseder** [comment]
> I think it's a small change on jOOQ side but that it would greatly improve my day to day work.

It's a huge change on the jOOQ side, because it would be equivalent to a commitment to backwards compatibility of what is really internal API. Will you like it when we "finally" expose those things that simplify your life, only to then later on break things again? What about other users who don't know your assumptions and context? Will they think, "oh cool, I can use this" only to later on run into this internal API trap?

You're working with internals already, making assumptions about internals, so you might as well patch jOOQ and make the relevant API public for your own use. That would work for you, and wouldn't affect anyone else. Or even simpler, subclass `TableImpl` from within `org.jooq.impl`. If you're not on the module path, you can put any custom content into jOOQ's package. That's a small change. But opening up internal API to the public isn't.

**Comment by esfomeado** [comment]
I see what you mean. I´m using jOOQ for something that honestly was not built with that in mind.

I will look into alternatives.

Thanks for your response.

**Comment by lukaseder** [comment]
Well, you probably want "synthetic views" of some sort, similar to https://github.com/jOOQ/jOOQ/issues/11054
