### ISSUE TITLE
Document pojosEqualsAndHashCode/consider enabling it by default

### ISSUE THREAD

**Issue by perlun** [jOOQ/jOOQ#13136]
### Background

We are currently converting our code from [ORMLite](https://ormlite.com/) to jOOQ. One of the things that I noted (well, my integration tests made me aware of it :grin:) was that jOOQ (immutable) POJOs are not comparable with `Object.equals()` out of the box. This made my AssertJ assertion `assertThat( someListOfPojos ).isEqualTo( otherListOfPojos )` fail, presumably since ORMLite-based objects are equality-comparable by default.

I looked at the generated POJO class and concluded that it didn't implement the `equals()` method which explained the test failure. I tried googling (`jooq equals`) but couldn't find anything obvious. Luckily, I have the jOOQ repo checked out locally, so I looked at the `JavaGenerator` class there and discovered the `pojosEqualsAndHashCode` flag. :tada: 

#### My question

1. Would it make sense to enable `pojosEqualsAndHashCode` by default, or is the feature considered "too unstable"/risky somehow? I personally think that letting the POJOs support `equals()` by default is the "least surprising" option here, but given that no-one else seems to have suggested the same thing in 7,5 years since #3613 got merged, perhaps it's just me. :joy: 

2. If we don't want to make it be enabled by default, I think that adding some docs for it could make sense (or actually, this would make sense regardless of whether we keep or flip the current `false` default). Perhaps on this page? https://www.jooq.org/doc/latest/manual/code-generation/codegen-pojos/

### Versions:

- jOOQ: 3.16.2
- Java: 11.0.13 (dev)
- Database (include vendor): N/A
- OS: Debian GNU/Linux
- JDBC Driver (include name if inofficial driver): N/A

**Comment by lukaseder** [comment]
Thanks for your suggestion. I don't think there's any good reason to keep the default flag value of `false`. Indeed, at the time, there were regression risks because of all the edge cases (array types, etc.), but I think that 10 years later, we can confidently turn this flag on by default. I've created a feature request for this: https://github.com/jOOQ/jOOQ/issues/13137

Regarding documentation, there are a few issues to collect all the not-yet-documented flags like this one and document them in a consolidated fashion.

**Comment by perlun** [comment]
Sounds good, thanks for the fix. :+1:
