### ISSUE TITLE
Confusing (outdated) gradle examples in manual

### ISSUE THREAD

**Issue by nbrugger-tgm** [jOOQ/jOOQ#13171]
The guides of how to use gradle are confusing. Every codesnippet shown in the examples in the *gradle* tab start with
```groovy
myConfigurationName(sourceSets.main) {
  ...
}
```
Which is confusing to me, the recommended jOOQ gradle plugin doesnt support the parameter `sourceSets.main`.

Normally the working structure of this plugin works like this
```groovy
jooq {
    configurations
        main
            generationTool
                generator
                    database
```
But here (https://www.jooq.org/doc/3.16/manual/code-generation/xmlgenerator/) for example `myConfigurationName` is used instead of generationTool` : https://www.jooq.org/doc/3.16/manual/code-generation/xmlgenerator

but when replacing "generationTool" with a custom name i get errors from gradle (with and without the sourceSet):
```
No signature of method: build_xyz.jooq() is applicable for argument types: (build_xyz_run_closure3) values: [build_xyz_run_closure3@158b825c]
```
(replaced hashes with XYZ)

The codegen-gradle page itself doesn't mentions anything about this, is there any relevance to it?

----
See: https://www.jooq.org/doc/3.16/manual/code-generation/codegen-gradle/

**Comment by lukaseder** [comment]
Thank you very much for your feedback. I believe that the current documentation used to be correct at some point in the recommended third party plugin.

The relationship between official jOOQ and that third party plugin is documented here, along with a discussion on how to improve things in general: https://github.com/jOOQ/jOOQ/issues/12985

It is unlikely we'll continue recommending and documenting that plugin, although it will obviously continue to work, and integrate tightly with Gradle. But we'll roll our own, official plugin, which we'll document.

I'll keep this issue here open as a reminder to get documentation right, once https://github.com/jOOQ/jOOQ/issues/12985 is implemented.

**Comment by lukaseder** [comment]
#12985 (still!) hasn't been prioritised yet, so I suspect we can simply update the manual as requested here. Instead of:

```
myConfigurationName(sourceSets.main) {
  ...
}
```

We'll generate

```
generationTool {
}
```
