### ISSUE TITLE
Don't wrap exception thrown from ad-hoc converter

### ISSUE THREAD

**Issue by atollk** [jOOQ/jOOQ#13236]
### Expected behavior
Given the following example code:
```kotlin
val myField = DSL.multiset(/* ... */).convertFrom { throw RuntimeException() }
val myOtherField = DSL.multiset(select(myField).from(someTable))
DSL.select(myOtherField).fetch()
```
This code must somehow fail due to the exception thrown.
I would expect the stacktrace to properly show me that my own code is the cause of the issue.

### Actual behavior
Stacktrace:
```
org.jooq.exception.DataAccessException: SQL [QUERY]; Error while reading field: multiset(
[QUERY]
), at JDBC index: 1
	at org.jooq_3.16.4.POSTGRES.debug(Unknown Source)
	at app//org.jooq.impl.Tools.translate(Tools.java:3089)
	at app//org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:670)
	at app//org.jooq.impl.CursorImpl$CursorIterator.fetchNext(CursorImpl.java:1462)
	at app//org.jooq.impl.CursorImpl$CursorIterator.hasNext(CursorImpl.java:1423)
        ...
```
(this actual stacktrace was produced by reactive fetching, so it might look slightly different with synchronous fetching)

This makes it look like somehow the query is false or JBDC has an issue, even though it's purely a user fault.

### Steps to reproduce the problem

See above.
I can provide an MCVE if needed.

The exception is first caught at https://github.com/jOOQ/jOOQ/blob/main/jOOQ/src/main/java/org/jooq/impl/RecordDelegate.java#L148.
It is then rethrown until https://github.com/jOOQ/jOOQ/blob/main/jOOQ/src/main/java/org/jooq/impl/CursorImpl.java#L1584 repackages, thus hiding the message until you start digging through a chain of "cause"s.

### Versions

-    jOOQ: 3.16.4 Open Source
-    Java: 14
-    Kotlin: 1.5.21
-    Database: Postgres 42.2.16
-    OS: Arch Linux

**Comment by lukaseder** [comment]
Thanks for your feature request. While I understand some of the benefits of your expectations here, they're in contrast with the reason for the current behaviour, namely: #5901. It is not possible to distinguish between a desirable user exception and an internal one (because you could throw a `DataAccessException` yourself, and jOOQ wouldn't know how to distinguish it).

Without very compelling reasons why your desired behaviour is better than the existing one, I don't think we should incompatibly change this behaviour.
