### ISSUE TITLE
DDLDatabase defaultNameCase broken for enum columns

### ISSUE THREAD

**Issue by bannmann** [jOOQ/jOOQ#13309]
### Expected behavior

In the schema below, DDLDatabase should apply `defaultNameCase` to enum types just as it does for table or column names.
```
create type fruit as enum ( 'APPLE', 'PEAR', 'ORANGE' );

create table if not exists test_table
(
    fruits fruit[] not null
);
```

### Actual behavior

While the enum type is created with the correct name (quoted & lowercased), its reference in the table definition is transformed to uppercase and thus not recognized:

```
[INFO] create type "fruit" as enum ('APPLE', 'PEAR', 'ORANGE')
[INFO] Update count: 0          
[INFO] create table if not exists "test_table" (
  "fruits" FRUIT array not null
)
[ERROR] DDLDatabase Error        : Your SQL string could not be parsed or interpreted.
```

I tried switching the table column type from `fruit[]` to `"fruit"[]` so that it matches the transformed `create type` command, but that is transformed into an unquoted lowercase type name which doesn't work either:

```
[INFO] create type "fruit" as enum ('APPLE', 'PEAR', 'ORANGE')
[INFO] Update count: 0          
[INFO] create table if not exists "test_table" (
  "fruits" fruit array not null
)
[ERROR] DDLDatabase Error        : Your SQL string could not be parsed or interpreted.
```

### Steps to reproduce the problem

Use the following code generator settings:
```
<plugin>
    <groupId>org.jooq</groupId>
    <artifactId>jooq-codegen-maven</artifactId>
    <version>${org.jooq.version}</version>
    <dependencies>
        <dependency>
            <groupId>org.jooq</groupId>
            <artifactId>jooq-meta-extensions</artifactId>
            <version>${org.jooq.version}</version>
        </dependency>
    </dependencies>
    <executions>
        <execution>
            <id>jooq-codegen</id>
            <goals>
                <goal>generate</goal>
            </goals>
            <phase>generate-sources</phase>
            <configuration>
                <generator>
                    <database>
                        <name>org.jooq.meta.extensions.ddl.DDLDatabase</name>
                        <properties>
                            <property>
                                <key>scripts</key>
                                <value>${project.basedir}/src/main/db/schema.sql</value>
                            </property>
                            <property>
                                <key>defaultNameCase</key>
                                <value>lower</value>
                            </property>
                            <property>
                                <key>logExecutedQueries</key>
                                <value>true</value>
                            </property>
                        </properties>
                    </database>
                </generator>
            </configuration>
        </execution>
    </executions>
</plugin>
```

I also prepared an MCVE.

### Versions

- jOOQ: 3.16.3
- Java: 11.0.13_8
- Database: none for code generation (PostgreSQL 12 at runtime)
- OS: Windows
- JDBC Driver: none for code generation (org.postgresql:postgresql:42.2.16 at runtime)

**Comment by bannmann** [comment]
Here's the MCVE: https://github.com/bannmann/jOOQ-mcve/tree/52d79b0c78462f47a09fd5742fdc9e00cf4f4529

**Comment by lukaseder** [comment]
Thanks for your report, I'm sorry for the delay. The notification email seems to have gone missing.

I'll look into this right away, now.

**Comment by lukaseder** [comment]
I see, this isn't something we can support currently. The `DDLDatabase`'s current implementation translates all the SQL to H2 and runs it on an actual H2 in-memory database. H2 doesn't currently support enum arrays, see: https://github.com/h2database/h2database/issues/3632

We'll eventually interpret the DDL statements ourselves. We can already do it in `org.jooq.Meta`, but not in `DDLDatabase`, yet, see: https://github.com/jOOQ/jOOQ/issues/7034

Even if we interpret the DDL ourselves in jOOQ, there will always be limitations, so if you're planning on using lots of vendor specific features, using testcontainers will probably be better anyway. You'll likely use testcontainers for your development and integration testing as well, so this might be a good option for multiple reasons, see also: https://blog.jooq.org/using-testcontainers-to-generate-jooq-code/

I'm closing this issue here, because I don't think there's much jOOQ can do for you here.
