### ISSUE TITLE
Feedback about manual section "codegen-generatorstrategy"

### ISSUE THREAD

**Issue by cbrady321** [jOOQ/jOOQ#13300]
On the `Custom generator strategies` page wrt adding a strategy using gradle, there is a lot more to doing this with gradle than is apparent. The main issue is that gradle can't find the user's custom generator class unless it is included in a sub project.  So I think the explanation is misleading.  I would mention this requirement an provide a reference to the example in the gradle codegen project.  https://github.com/etiennestuder/gradle-jooq-plugin/tree/master/example/configure_custom_generator_strategy

Even better would be to extend the generator to support providing a renaming scheme without the use of a java class, but I understand that would be a lot more work.

----
See: https://www.jooq.org/doc/latest/manual/code-generation/codegen-generatorstrategy/

**Comment by lukaseder** [comment]
Thanks a lot for your feedback

> there is a lot more to doing this with gradle than is apparent. The main issue is that gradle can't find the user's custom generator class unless it is included in a sub project

Yes, the class name references a class that must be on the classpath of the code generator, just like other similar elements that are referenced from the code generation configuration like that. It doesn't have to be a subproject. You can also create a library with code generation utilities and reference that as a dependency.

> So I think the explanation is misleading

What's misleading, specifically? In other words, what made you think that it would "just work"?

> Even better would be to extend the generator to support providing a renaming scheme without the use of a java class, but I understand that would be a lot more work.

See https://www.jooq.org/doc/latest/manual/code-generation/codegen-matcherstrategy/

**Comment by cbrady321** [comment]
Happy to offer my comments if it helps.
The misleading part is that the document looks great and has plenty of examples but leaves some key issues up to the users, which I didn't expect.  As a novice-level gradle user I had to experiment to understand the issues and finally read about how gradle handles classpaths and finally found the example project I mentioned.  So you can see that I eventually figured out what to do, but what I wanted to focus on was writing application code.  Overall, the documentation is good.  However, if you want to make jOOQ more accessible to new users I would consider asking someone with no jooq experience and a project in mind that they want to use jOOQ on to read them with a fresh eye.
Best,

**Comment by lukaseder** [comment]
Thanks a lot for following up.

I see. Well, I'd say, this use-case is highly specific, not exactly what I would have expected a new user to do. I'm curious, why did you want to implement a strategy in the first place? As far as new users are concerned, the idea is that everything should already be optimal *by default*, so no power user features like this one are required. But I'm probably missing something.

I can definitely see a hint about class names referencing classes from the classpath, but that manual section can't serve as a tutorial on how to do all that. We'd have to repeat this approach about 10x throughout the manual, and there are tons of ways to implement this in gradle, and at least 2-3 in maven.

I think the main problem is that we don't have our own out of the box gradle plugin (https://github.com/jOOQ/jOOQ/issues/12985). The third party plugin is great and has great examples. But we can't document this third party plugin, because our docs would be outdated all the time, making things worse, not better.

So, the solution is:

- Go through the manual and add a quick "classpath hint" everywhere it applies, as a quick fix
- Eventually implement our own plugin, and then document that

There's also https://github.com/jOOQ/jOOQ/issues/12984 that goes into this direction. The manual is a reference, and thus the wrong place for tutorials, but we should definitely have better and more tutorials.

**Comment by lukaseder** [comment]
The manual improvement related to explaining classpaths will be implemented via https://github.com/jOOQ/jOOQ/issues/13304
