### ISSUE TITLE
REQUIRE_RUNTIME_JOOQ_VERSION check produces compile error with Scala 2.13.8 and jOOQ 3.16.5

### ISSUE THREAD

**Issue by philippjenniunic** [jOOQ/jOOQ#13463]
### Expected behavior
Using the code generator with version 3.16.5 and the runtime library with the same version should produce code that compiles.

### Actual behavior
the compiler throws an error because the val `REQUIRE_RUNTIME_JOOQ_VERSION` is private and not used from any place
--> Scala throws a compilation error.
**But**: to my understanding: the check should throw a compile error **if `Constants.VERSION_3_16` constant does not exist**. This is not the case here.

for the reference: Contants class from jooq-3.16.5:
```
package org.jooq;

public final class Constants {
    //omitted [...]
    public static final String VERSION_3_15 = "3.15";
    public static final String VERSION_3_16 = "3.16";

    private Constants() {
    }
}
```

generated code:
```
object DefaultCatalog {

  /**
   * The reference instance of <code>DEFAULT_CATALOG</code>
   */
  val DEFAULT_CATALOG = new DefaultCatalog
}

/**
 * This class is generated by jOOQ.
 */
class DefaultCatalog extends CatalogImpl("") {

  //code omitted

  /**
   * A reference to the 3.16 minor release of the code generator. If this
   * doesn't compile, it's because the runtime library uses an older minor
   * release, namely: 3.16. You can turn off the generation of this reference by
   * specifying /configuration/generator/generate/jooqVersionReference
   */
  private val REQUIRE_RUNTIME_JOOQ_VERSION = Constants.VERSION_3_16
}
```

this produces the following compilation error:
`/database/generated/DefaultCatalog.scala:43: private val REQUIRE_RUNTIME_JOOQ_VERSION in class DefaultCatalog is never used`

### Steps to reproduce the problem

- `mvn compile` with enabled code generation

### Analysis so far
- check was introduced with https://github.com/jOOQ/jOOQ/issues/12601

### Suggestion for a fix
instead of
`private val REQUIRE_RUNTIME_JOOQ_VERSION = Constants.VERSION_3_16` 
generate
`val REQUIRE_RUNTIME_JOOQ_VERSION = Constants.VERSION_3_16`

If the val is not private, the Scala compiler won't throw an error.

### Workaround
turn off the generation of this reference by specifying /configuration/generator/generate/jooqVersionReference

### Versions

- jOOQ: 3.16.5
- Java: 11
- Database (include vendor): MySQL
- OS: Windows
- JDBC Driver (include name if inofficial driver): MySQL Driver 8.0.28

**Comment by lukaseder** [comment]
Thanks for your report. This issue does not manifest in our integration tests. We're compiling scala code like this:

```xml
<plugin>
    <groupId>net.alchim31.maven</groupId>
    <artifactId>scala-maven-plugin</artifactId>
    <executions>
        <execution>
            <goals>
                <goal>compile</goal>
                <goal>testCompile</goal>
            </goals>
        </execution>
    </executions>

    <configuration>
        <args>-Xcheckinit</args>
    </configuration>
</plugin>
```

This means that you're likely using some linter argument, which may be a bit "aggressive" on jOOQ generated code? I don't agree with this particular linting rule. In IDEs, a warning or inspection can be useful as such code can often be deleted. In this case, it could be deleted, because it has no effect on runtime behaviour. But a compiler mustn't assume such a thing, there might still be some unknown (to the compiler) reflective dependency, or a side-effect that is triggered by the initialisation of such a variable (not in this case, but it could be), which shows that while a linter is allowed to complain, a compiler shouldn't be.

Making the attribute public defeats the idea of this check being transparent. With the flag allowing to remove the check, and the assumption that the linter can be configured to be more lenient, I'm gonig to close this issue as "won't fix"

**Comment by lukaseder** [comment]
(I might reopen if this turns out to be a very popular complaint with this type of linting being active in a lot of setups)

**Comment by philippjenniunic** [comment]
True, the following are enabled:
```
<args>
    <arg>-Xlint</arg>
    <arg>-Xfatal-warnings</arg>
</args>
```


Thanks. I can understand your arguments.

Let's hope, the issue can be of help to other users.

**Comment by lukaseder** [comment]
> Let's hope, the issue can be of help to other users.

It definitely will help. If you think this turns out to be a common issue among jOOQ / scala users, you could also ask and answer a question on Stack Overflow (the practice is explicitly encouraged: https://stackoverflow.blog/2011/07/01/its-ok-to-ask-and-answer-your-own-questions/). You could link to this issue which might produce a few upvotes, in case of which addressing this will be more likely :)
