### ISSUE TITLE
Suggestion: Enable readonly columns on Open Source edition

### ISSUE THREAD

**Issue by LimmaPaulus** [jOOQ/jOOQ#13480]
Hi!

Thank you for creating such a create library and making it open source. I find your dual-licensing model particularly clever. Enabling enterprise databases and more advanced features only in paid licenses nicely gives free access only to individuals and small companies.

However, I was surprised to find that readonly column support cannot be used in the free edition. Our database has quite a many generated columns, and this feature is essential for us. I've already made quite a lot of work for adopting JOOQ, and it was a bit of an unpleasant surprise at that stage to find out that we are still forced to use the paid version.

You of course have full liberty to decide which features are free and which are not. The investment will also definitely pay off for us. However, my point is that readonly columns feel like a mandatory feature in most use cases, and makes it quite hard to use the open source version in any production workload. I'm biased of course but would find it more logical to lock only advanced features from the free license.

**Comment by lukaseder** [comment]
Thanks for your message, @LimmaPaulus.

I understand your situation. You've received tremendous benefit from a large amount of added value that has been given to you for free, thanks to the generous support of our paying customers who have used other RDBMS and other, "more advanced features," which have financed our business, and subsidised the free version, from which you profited.

Now, you're the one who wants to use one of those more advanced features, and this puts you in a situation where you consider becoming one of those paying customers, thanks to whom we can continue offering 95% of jOOQ for free to our users. You're assessing whether this particular feature is "more advanced" enough to warrant that price tag, or if there should be an exception, because this time, unlike before, it affects *you*, not our other, existing paying customers.

Any product with different price plans leads to decisions like yours. "Is this new price plan still for me?" - "Will our cost/benefit ratio still validate continued usage?" We do the same. Github is for free for most, but we've been a paying customer for 3 years, because we want to use tighly integrated private repositories for the commercial distribution. Microsoft Office 365 is much better and more complete than our jooq.org hoster's email service, and includes MS Word and MS Excel licenses. VMWare licenses are totally worth their cost when testing things like Vertica, Teradata. And if Docker ever becomes paid software (for us as a small company), or AtomicJar/testcontainers offers something of value to us, we'll buy it right away. Right now, they don't have such paid features, but they might, soon (I hope).

You said:

> The investment will also definitely pay off for us.

I'm happy to hear you've already made the purchasing decision, then! :)

> my point is that readonly columns feel like a mandatory feature in most use cases

It was obviously a great choice for us to make that a paying feature because of its likely broad usage. If we only charge money for very rare fringe features that no one uses, then no one will pay that money. The highest value features produce the highest possible revenue, meaning that we can run a viable business on them, which helps invest even more in both the commercially licensed and free version in the future. I'm positive that our customers value a healthy supplier with a viable business model.

This is by no means an isolated decision about this particular commercial feature. Other, related features are also available as commercial only features, including:

- jOOQ 3.14: Temporal validity work started (emulation soon): https://github.com/jOOQ/jOOQ/issues/4704
- jOOQ 3.14: Synthetic foreign keys: https://github.com/jOOQ/jOOQ/issues/7155
- jOOQ 3.14: Synthetic unique keys: https://github.com/jOOQ/jOOQ/issues/7860
- jOOQ 3.14: Advanced embeddables: https://github.com/jOOQ/jOOQ/issues/10481 (and other features)
- jOOQ 3.15: Built in SQL transformations: https://github.com/jOOQ/jOOQ/issues/9767
- jOOQ 3.16: Custom query object model transformations: https://github.com/jOOQ/jOOQ/issues/12425
- jOOQ 3.16: Computed columns: https://github.com/jOOQ/jOOQ/issues/6492
- jOOQ 3.16: Readonly columns: https://github.com/jOOQ/jOOQ/issues/9864
- jOOQ 3.16: ROWID colums (which are a special kind of computed column): https://github.com/jOOQ/jOOQ/issues/8388
- jOOQ 3.17: Synthetic columns: https://github.com/jOOQ/jOOQ/issues/4845
- jOOQ 3.17: Column visibility: https://github.com/jOOQ/jOOQ/issues/13432
- jOOQ 3.17: Audit columns: https://github.com/jOOQ/jOOQ/issues/1592
- jOOQ 3.17: Client side computed columns: https://github.com/jOOQ/jOOQ/issues/9879

There are more, smaller features, which are related to these topics, all of which evolve around the automation of the transformation of expressions in SQL. None of these features are mandatory for jOOQ usage, all of them are power user features, yet many of them are very popular, so a lot of people will *want* them, but no one will *require* them.

At the same time, look at the power user features that are open source, and always will be:

- jOOQ 3.14: XML and JSON support (various issues)
- jOOQ 3.14: Kotlin code generation support: https://github.com/jOOQ/jOOQ/issues/6248
- jOOQ 3.14: Embeddable types (various issues)
- jOOQ 3.14: Domain types (various issues)
- jOOQ 3.14: Advanced MERGE statement support: https://github.com/jOOQ/jOOQ/issues/7291
- jOOQ 3.14: UpdatableRecord.merge(): https://github.com/jOOQ/jOOQ/issues/2961
- jOOQ 3.15: Tons of PostgreSQL improvements around the RETURNING clause (various issues, including https://github.com/jOOQ/jOOQ/issues/4474)
- jOOQ 3.15: MULTISET (THE big new feature!): https://github.com/jOOQ/jOOQ/issues/3884
- jOOQ 3.15: Nested records: https://github.com/jOOQ/jOOQ/issues/11812
- jOOQ 3.15: Ad-hoc converters: (Various issues)
- jOOQ 3.15: R2DBC support: https://github.com/jOOQ/jOOQ/issues/11700
- jOOQ 3.16: The new query object model: https://github.com/jOOQ/jOOQ/issues/12425

Where would you draw the line? You're asking for readonly columns to be available for free, but at what price? Would you accept R2DBC support to be commercial? Or the KotlinGenerator? Or UpdatableRecord.merge()? Or even MULTISET, the all powerful way to nest collections in a type safe way with jOOQ? Where's the acceptable "they're paying" vs "we're paying" line for the average jOOQ user?

The strategy here, for us, is that SQL transformation, as a whole, is a commercial power user feature, and readonly columns are a part of that. jOOQ is transforming DML statements to remove "accidental" inclusion of readonly columns in DML. You can always do the same thing manually, if you don't want to upgrade. I'm sure that 80% - 90% of jOOQ's user base can get away with using jOOQ entirely without ever transforming their generated SQL. What they write in jOOQ is what jOOQ generates for them. Compared to that, MULTISET, R2DBC, and the KotlinGenerator all allow jOOQ to engage with a much larger market, so making those features free is strategically useful. Readonly columns, not so much.

> to find out that we are still forced to use the paid version.

But you're not *forced* to use the paid version if you're interested in an advanced feature. You *want* to use the paid version, minus the paid part. The feature itself is completely opt in. The feature didn't exist for a decade now, and it has been added only now in jOOQ 3.16. People had to work around the lack of functionality in the past, and if you're not ready to upgrade, you can continue working around this lack of out of the box functionality. In other words, you can use jOOQ 3.16 just like you used jOOQ 3.15, for free, forever.

> I'm biased of course but would find it more logical to lock only advanced features from the free license.

I hope that with my plea, I've managed to convince you that the more *logical* step here is to make optional, but high value, power user features commercial, in order to maintain a sustainable business, not necessarily low value, fringe features that no one needs, nor features that lead to a bigger market reach?

I'm convinced that you will find great pleasure among the various other existing and future commercial only features, including those awesome client side computed columns that I had mentioned: https://github.com/jOOQ/jOOQ/issues/9879, which are very much related to this topic.

**Comment by LimmaPaulus** [comment]
I really appreciate your thorough and quick answers here :)

I want to emphasize that I wasn't by any means suggesting that you should provide anything by free. This was partly my misunderstanding about your business model and partly just selfish attempt to continue with free version. Your reasoning is perfectly rational. I hope that we will find use also for other commercial features on future.

Just a one more quick question about licensing. Express edition is limited to three developers, but can we buy three Express licenses and one Professional licenses if we have four devs? Currently we have only two, but just in case of future growth.

**Comment by lukaseder** [comment]
The original intent of the Express Edition was to offer a lower price to small customers who wish to work with simpler Oracle XE or SQL Server Express Edition based systems, perhaps for internal applications, studying, etc. It had been introduced long before we started shifting from only RDBMS based towards feature based pricing.

While your suggested usage does not correspond to the original intended usage of the price plan, I don't see why it wouldn't be possible. The main limitations compared to the Professional Edition include:

- Support for only express editions of the commercial database products
- Purchase at most 3 jOOQ Express Edition licenses per customer
- No commercial support

So yes, you can indeed maintain 2 separate subscriptions as you suggested, a first one for your first 3 users, and a second one for users 4-N. I guess it's also a useful additional price plan for purely feature based pricing, when you don't need the extra commercial RDBMS support that is otherwise included in the jOOQ Professional Edition - at least for small companies.
