### ISSUE TITLE
"Applies to" section showing up incorrectly on Chromium

### ISSUE THREAD

**Issue by LimmaPaulus** [jOOQ/jOOQ#13481]
There is some issue on the manual website when using Chromium (version 100.0.4896.127) at least on my Linux machine. Every box in the "Applies to" section is just empty and gray. It take me some time to figure out why readonly columns were not working because this :D

![image](https://user-images.githubusercontent.com/14800398/165035133-d8efad00-ea92-4aac-a441-9420c45fdc02.png)

**Comment by lukaseder** [comment]
Thanks a lot for your report. Those are U+274C and U+2705 characters. I can't easily reproduce this problem on a Linux instance from within VMWare. I wonder why those characters aren't supported by your machine and/or browser?

**Comment by lukaseder** [comment]
The characters have been added in Unicode 6 (2010)...

**Comment by lukaseder** [comment]
Which ones of these display fine for you?

- https://en.wikipedia.org/wiki/X_mark
- https://en.wikipedia.org/wiki/Check_mark

**Comment by LimmaPaulus** [comment]
Yes that's weird. I tried with fresh Manjaro XFCE on VirtualBox with exactly same results

https://manjaro.org/downloads/official/xfce/

X-marks:

![image](https://user-images.githubusercontent.com/14800398/165081002-db123cf1-c9f7-4f67-bb8e-a46d18949a3d.png)

Check marks:

![image](https://user-images.githubusercontent.com/14800398/165081035-acc89711-644a-4401-b7a2-4a04d896c0e0.png)

**Comment by lukaseder** [comment]
Thanks for those screenshots. That's really tough luck! Everything but those two seems to work.

I remember I chose those particular ones because they're coloured on my Windows Machine and also on my mobile phone, and thus stand out:

![image](https://user-images.githubusercontent.com/734593/165085143-f0ab8262-745a-48ef-b365-891d56d06b7c.png)

![image](https://user-images.githubusercontent.com/734593/165085134-989e59b0-4e35-4ea2-9054-7481e3213f0f.png)

It's obviously possible to replace these by svgs... I'll think about it.

**Comment by lukaseder** [comment]
Might still be worth reporting a bug to Manjaro XFCE as well, though.

**Comment by lukaseder** [comment]
Having had another look at this, the clear visual style was the reason I chose those particular characters. They should be supported by all OS's and browsers by now. If they aren't then it's more of an OS / browser bug, IMO.
