### ISSUE TITLE
Improve Documentation for DSLContext.fetchStream() and related methods

### ISSUE THREAD

**Issue by tmsklr** [jOOQ/jOOQ#13525]
### Expected behavior

The documentation of e.g. ResultQuery.fetchStream() includes a very helpful hint: 

> Depending on your JDBC driver's default behaviour, this may load the whole database result into the driver's memory. In order to indicate to the driver that you may not want to fetch all records at once, use fetchSize(int) prior to calling this method.

In my understanding, DSLContext.fetchStream() behaves similarly and should be documented in the same way.
This also applies to fetchLazy and maybe other methods.

### Versions

- jOOQ: 3.15.9

**Comment by lukaseder** [comment]
Thanks for your suggestion.

It's a bit different with `DSLContext::fetchStream` and `DDSLContext::fetchLazy`. Most overloads can't actually do much about this fetchSize, at least not on a per-statement level, because there isn't any such flag to set.

So the amended documentation wouldn't be the same as on `ResultQuery::fetchStream` and `ResultQuery::fetchLazy`, but instead, would point out the problem and recommend using the latter instead, in case this is relevant for users, or to specify `Settings.fetchSize`

**Comment by lukaseder** [comment]
Also, those overloads that accept a `ResultSet` don't need this indication, as the `ResultSet` may have been created entirely elsewhere, so it's not jOOQ's business, then.

**Comment by lukaseder** [comment]
Fixed in jOOQ 3.17.0, 3.16.7 (https://github.com/jOOQ/jOOQ/issues/13526), and 3.15.11 (https://github.com/jOOQ/jOOQ/issues/13527)
