### ISSUE TITLE
Deadlock found when trying to get lock; try restarting transaction

### ISSUE THREAD

**Issue by mshaved** [jOOQ/jOOQ#13548]
We are running two queries one after other and getting deadlock exception. 

First query is inserting records in a batch and second query is updating few records based on some condition. pasting the code snippet for batch Insert query and update query. 
if we remove update query then we do not see any deadlock exception. both statements are synchronous then why do we see deadlock exception ?

 - 1st query : 

```java
protected static <T> void insertBatchSafely(
      DSLContext dslContext,
      Table<?> table,
      Field<?>[] insertFields,
      @NonNull List<T> objects,
      Function<T, Object[]> bindMapper,
      Function<InsertOnDuplicateStep<?>, Query> duplicateHandling) {
    Lists.partition(objects, MAX_BATCH_SIZE)
        .forEach(
            sublist -> {
              InsertOnDuplicateStep<?> insertVals =
                  dslContext
                      .insertInto(table, insertFields)
                      .values(Arrays.stream(insertFields).map(s -> null).toArray());

              Query query =
                  duplicateHandling == null ? insertVals : duplicateHandling.apply(insertVals);

              BatchBindStep insert = dslContext.batch(query);

              for (T object : sublist) {
                insert.bind(bindMapper.apply(object));
              }

              insert.execute();
            });
  }
```

 - 2nd query
 
```java
DSLContext.update(table).execute()
```

### Versions

- jOOQ: 3.13.4
- Java: 11
- Database (include vendor): Mysql (Amazon RDS)
- OS: Mac
- JDBC Driver (include name if inofficial driver):

**Comment by lukaseder** [comment]
Thanks for your message. It appears that at least the `INSERT` queries are running in some transaction, and the `UPDATE` query is running in a different transaction. Since they might both touch the same records, but in a different order, a deadlock may occur.

This isn't a problem that is specific to jOOQ, it may happen in any SQL based application. One possible workaround is to make sure both operations order their statements in the same way, e.g. by `ID`:

- The `INSERT` statements could be ordered in Java, sorting the `objects` by `ID`
- The `UPDATE` statement could have an `ORDER BY` clause added to it, which is supported natively by MySQL, see: https://dev.mysql.com/doc/refman/8.0/en/update.html

**Comment by lukaseder** [comment]
Another workaround is, of course, to run the two statements in the same transaction, if that's a reasonable option in your setup.
