### ISSUE TITLE
Custom strategy with Maven => Class not found

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#1355]
I'm trying to use custom strategy like this in pom.xml : 

```
<strategy>
     <name>com.me.MyStrategy</name>
</strategy>
```

When executed within Eclipse, maven failed with java.lang.ClassNotFoundException: com.me.MyStrategy.
This class comes from my Eclipse Project.
How can i do ?

Marc

**Comment by vojtapol** [comment]
The workaround for this is not acceptable for us. Creating a separate module just for one class adds too much complexity for too little reward. All we need is to prepend every generated table class name with a single letter `'T'` so that when looking for searching for classes it does not clash with domain classes. This has to be an extremely common scenario and Maven is still the most common build system used in the industry.

Can't we just do something like this:
```
<strategy>
    <prefix>T</prefix>
</strategy>
```

I realize this issue is old so if another solution is now available please let me know @lukaseder.

**Comment by lukaseder** [comment]
@vojtapol You could use the `JVMArgsGeneratorStrategy` from jOOQ-codegen, or the matcher strategy configuration:
https://www.jooq.org/doc/latest/manual/code-generation/codegen-matcherstrategy
