### ISSUE TITLE
UpdatableRecord::merge might produce wrong update count if generated keys can't be fetched

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#13574]
A test currently fails when asserting the update count of `UpdatableRecord::merge` to be `1` (it should always be `1`, due to the nature of the operation). However, in Oracle, for example, we can see in the logs:

```
14:01:50,245 DEBUG [LoggingConnection             ] - prepareStatement         : merge into "TEST"."T_AUTHOR" using ((select ? "ID", ? "LAST_NAME" from DUAL)) "t" on ((("TEST"."T_AUTHOR"."ID", 1) = (("t"."ID", 1)) or 1 = 0 or ("TEST"."T_AUTHOR"."LAST_NAME", 1) = (("t"."LAST_NAME", 1)) or 1 = 0)) when matched then update set "TEST"."T_AUTHOR"."ID" = ?, "TEST"."T_AUTHOR"."LAST_NAME" = ? when not matched then insert ("ID", "LAST_NAME") values ("t"."ID", "t"."LAST_NAME")
14:01:50,275 DEBUG [LoggerListener                ] - Affected row(s)          : 1
14:01:50,279 DEBUG [LoggerListener                ] - Fetched result           : +----+
14:01:50,280 DEBUG [LoggerListener                ] -                          : |  ID|
14:01:50,280 DEBUG [LoggerListener                ] -                          : +----+
14:01:50,280 DEBUG [LoggerListener                ] - Fetched row(s)           : 0
```

So, there's a fetched row count of `0` despite the affected row count of `1`.

**Comment by lukaseder** [comment]
Fixed in jOOQ 3.17.

**Comment by lukaseder** [comment]
This change causes a regression in a new jOOQ 3.17 feature when stored client side computed columns are involved (https://github.com/jOOQ/jOOQ/issues/9879).

**Comment by lukaseder** [comment]
The regression is (in parts) due to https://github.com/jOOQ/jOOQ/issues/12868, as it occurs in H2 when using `SELECT * FROM FINAL TABLE (MERGE ..)`, where the qualification of scalar subquery contents is removed, even if those subqueries aren't related to the data change delta table logic.

Luckily, with #9981, it seems we can easily work around this.

**Comment by krzysztof-osiecki** [comment]
@lukaseder hi, i know this ticket is closed however i have some questions to ask about this behavior.
In our case we are building UpdateQuery object with certain conditions and returning clause.
The conditions are set in a way that tells us that if they are not met then we should raise an exception.
We were checking the result of UpdateQuery.execute() to see if any data was changed by query, and throwing our exceptions if the result was 0.
After this change result is not 0 even if query doesn't change any records, so our check fails to recognize the situation.
We found a solution to our case, instead of checking the return value of execute we simply check if the returned records are null or not.
However when looking at the documentation of execute method on Query object it says that for update it is returning:
"the number of updated records" which doesn't seem to be the case now.
Is it expected behavior and a change or some unexpected regression?
