### ISSUE TITLE
Adding option to update column if condition matches

### ISSUE THREAD

**Issue by arne-kroeger** [jOOQ/jOOQ#13585]
### Use case:

As I'm using GraphQL in some projects which also includes partial updates in terms of mutations I would love to have an easy way to optionally update the column based on a separate condition check.

### Possible solution you'd like to see:

As I'm a big fan of the fluent api I would suggest a function like `set( org.jooq.Field<T> field, T value, boolean checkForSet).` This would make the necessary code more readable and simple.

This would make it ease to use it like this:

`context.update(TABLE).set(TABLE.COLUMN, 'ABC').set(TABLE.COLUMN_2, 'XYZ', value.isDefined()).returning();`

If `value` is not defined the update would only update `TABLE.COLUMN`.

### Possible workarounds:

Currently I'm creating a Map which holds the only submitted fields and this is given to the `set(Map<?,?>) `function. 

### Versions:

- jOOQ: 3.15.10
- Java: 17
- Database (include vendor):PostgreSQL 12
- OS: Mac OS
- JDBC Driver (include name if inofficial driver): r2dbc-postgresql

**Comment by lukaseder** [comment]
Thank you very much for your feature request.

This kind of request has been made a few times in the past, including:

- https://github.com/jOOQ/jOOQ/issues/1817
- https://github.com/jOOQ/jOOQ/issues/7723

The requester tends to think in terms of a "simple" itch to scratch, namely that of the `set()` method in your case, not thinking about the hundreds of other API that would have to be adapted as well for consistency reasons, in order to enable this style of API usage. While it seems elegant at first, the effort of maintaining so much API for this use-case is prohibitive, while at the same time, there already exist some primitives for your particular use-case (e.g. passing a `Map<?, ?>` or a `Record`). You could even write this:

```java
.set(TABLE.COLUMN_2, value.isDefined() ? val('XYZ') : TABLE.COLUMN_2)
```

Which isn't the same but may be acceptable? Starting with jOOQ 3.17, we'll have a `noField()` expression, which works similar to the `noCondition()` expression for such purposes: https://github.com/jOOQ/jOOQ/issues/2333

I'll make sure `noField()` can be passed to `UPDATE` statements as well, e.g.


```java
.set(TABLE.COLUMN_2, value.isDefined() ? val('XYZ') : noField())
```
