### ISSUE TITLE
Feedback about manual section "importing"

### ISSUE THREAD

**Issue by ghein-square** [jOOQ/jOOQ#13602]
Hi,

  I'm having a really tough time understanding the csv loading process. Specifically, the table I'm loading into has a varbinary field, but I can not understand how jooq encodes the value in the csv before it is inserted into the table. 

----
See: https://www.jooq.org/doc/latest/manual/sql-execution/importing/

**Comment by lukaseder** [comment]
Thanks a lot for your message. I suspect this is your question, too? https://stackoverflow.com/q/72368051/521799

Like on Stack Overflow, I'm not too clear about what exactly it is you're doing. Can you please provide an example that helps reproduce what you're doing (in code), and what problem you're trying to solve?

I've always found this document useful on Stackoverflow to explain what people who answer questions would love to see in a question:

- https://stackoverflow.com/help/minimal-reproducible-example

We also have a template to create such reproducible examples, in case you think you've run into a bug:

- https://github.com/jOOQ/jOOQ-mcve

I'll be happy to help you further, once I know what specific problems you're running into.

**Comment by lukaseder** [comment]
I think I know what's happening here. If your column is of some `byte[]` type (e.g. `VARBINARY`), then the `Loader` API will attempt to decode base64 encoded binary data, see https://github.com/jOOQ/jOOQ/issues/5858

Among all the binary string representations, this seems to be one of the most popular ones, but it's probably not what you were expecting? You were expecting jOOQ to pass along the `String` directly to the JDBC driver?

A thorough solution for arbitrary string encodings might be implemented in the near future, see: https://github.com/jOOQ/jOOQ/issues/3221

Until then, I think the problem is clear? For now, you should either:

- Place base64 encoded data in your CSV
- Pre-process your CSV and pass the binary data to an `Object[]` or `Record` representation, and load that, instead

I'm closing this as a duplicate of https://github.com/jOOQ/jOOQ/issues/3221, which should help throughly work around the issue. I'll also provide this answer on Stack Overflow
