### ISSUE TITLE
Kotlin DSL extension for building selection clause

### ISSUE THREAD

**Issue by hantsy** [jOOQ/jOOQ#13629]
I would like see some kotlin DSL support for the jooq dslContext.

```kotlin 
jooq{
   select{}
   from {}
   where {}  
}
```

_Originally posted by @hantsy in https://github.com/jOOQ/jOOQ/issues/9335#issuecomment-1143641691_

In spring, there are some Kotlin extensions provided, such as RouterFunctionDsl, BeanDefinitionDsl, etc to declare routers and beans with fluent Kotlin DSL syntax.

The `BeanDefinitionDSl` example looks like this, a complete example: https://github.com/hantsy/spring-kotlin-dsl-sample/blob/master/webflux/src/main/kotlin/com/example/demo/DemoApplication.kt#L44

```kotlin 
beans{
   bean{}
}
```

The `RouterFunctionDsl` example: https://github.com/hantsy/spring-kotlin-dsl-sample/blob/master/webflux/src/main/kotlin/com/example/demo/DemoApplication.kt#L119

```kotlin
//router 
router{
  "/posts".nest{
   }
}
```
And Spring Security Kotlin Dsl example:https://github.com/hantsy/spring-kotlin-dsl-sample/blob/master/webflux/src/main/kotlin/com/example/demo/DemoApplication.kt#L189

```kotlin 
http{
    csrf { ... }
    httpBasic { ... }
    authorizeExchange { ... }
}

```

**Comment by lukaseder** [comment]
So, here are my thoughts:

### Notation

First off, this is just about notation, not about any fundamentally interesting way to design an API. Since you've mentioned Spring examples, Spring has a history of "re-inventing" itself in a, what I would call, "art for art's sake" way. First, we had the XML declarations, then the annotation/convention driven declarations, now the programmatic declarations (using DSL-ish constructs). But it didn't fundamentally change (luckily). It just declared:

- Old way bad
- New way good

To me, this was always a bit troubling as it generated a lot of busywork for users and for maintainers alike, without actually improving anything - at least that's how I see it. I had always been fine with the XML version. Never understood why everyone was so annoyed by it. 

The annotation driven version was in no way better, it was just different, sometimes even a bit more clunky, because annotations can't encode behaviour, only constant, stringly typed data.

You could argue that the new, 100% programmatic approach is more debuggable, but that's just a tooling problem, not strictly an API design problem.

So, the Spring examples are purely about notation

### What could this mean for jOOQ

Looking at your suggestion, there seems to be a desire to apply a DSL notation to queries. Of course, this is possible *in principle*, because after all, when creating jOOQ queries, we're just creating expression trees manually, in code. A simpler example than `select` (which has a ton of clauses and edge cases and weirdness) would be to create a predicate for this SQL:

```sql
(ACTOR.ID = 1 OR ACTOR.ID = 2) AND ACTOR.FIRST_NAME LIKE 'A%'
```

```kotlin
and {
  or {
    eq {
      ACTOR.ID,
      1
    }
    eq {
      ACTOR.ID,
      2
    }
  }
  like {
    ACTOR.FIRST_NAME
    'A%'
  }
}
```

To me, this looks less readable than today's version, which matches the SQL version quite well:

```kotlin
ACTOR.ID.eq(1).or(ACTOR.ID.eq(2)).and(ACTOR.FIRST_NAME.like("A%"))
```

But we could create a 1:1 mapping between a "classic" DSL expression and this kotlin DSL-ish expression. Since jOOQ 3.17, a large part of the DSL API is generated from a meta DSL, so it would be relatively maintainable, as we could simply generate a secondary DSL for kotlin users, binding to the same expression tree behind the scenes.

You could even do that on your end and publish an extension library, because, why not?

### What purpose would this serve?

This is still my big question here. I don't see a single advantage of the alternative notation, given that it's just notation. It wouldn't unlock some feature that hasn't been available, otherwise. But it would be much more verbose, more difficult to understand and debug, and probably producing a few "interesting" edge cases that are harder to implement using this approach.

At the same time, users would have to constantly decide which version they prefer. And as we all know, since the "old" API won't go away, inevitably, users will mix the two styles, e.g.

```kotlin
and {
  or {
    ACTOR.ID.eq(1)
    ACTOR.ID.eq(2)
  }
  ACTOR.FIRST_NAME.like("A%")
}
```

Maybe even accidentally, or incidentally, as two different developers in a team each prefer a different style, and they'd rather fight the fight than agree on it.

In fact, the above example can be achieved (almost) today, using:


```kotlin
// The usual import:
import org.jooq.impl.DSL.*

and(
  or(
    ACTOR.ID.eq(1)
    ACTOR.ID.eq(2)
  )
  ACTOR.FIRST_NAME.like("A%")
)
```

The operators `DSL.and()` and `DSL.or()` have been made available to support using them in stream reductions and other dynamic SQL things. (We could argue that all binary infix operators (e.g. `eq`, `like`, and many others) should have a static prefix version.)

As such, the idiomatic way for jOOQ to turn a SQL-ish DSL that follows the original DSL API design (https://blog.jooq.org/the-java-fluent-api-designer-crash-course/) into an alternative tree construction form would not be to use this kotlin DSL API design (via `T.() -> Unit` notation) but to continue using classic API design, except perhaps offering both infix and prefix operator versions for all infix operators.

Frankly, I've always found this `T.() -> Unit` experiment to be a big mistake in kotlin. It may have been en vogue for a while, but it offers only little benefit over classic APIs, and it will probably be recognised as a prematurely added, and much overused (e.g. by Spring) language feature in hindsight, eventually. To take one of your examples:

https://github.com/hantsy/spring-kotlin-dsl-sample/blob/master/webflux/src/main/kotlin/com/example/demo/DemoApplication.kt#L189

What is the benefit of this:

```kotlin
http {
	csrf { disable() }
	httpBasic { securityContextRepository = WebSessionServerSecurityContextRepository() }
	authorizeExchange {
		authorize("/auth/**", authenticated)
		authorize(pathMatchers(HttpMethod.GET, "/posts/**"), permitAll)
		authorize(pathMatchers(HttpMethod.DELETE, "/posts/**"), hasRole("ADMIN"))
		authorize("/posts/**", authenticated)
		authorize(anyExchange, permitAll)
	}
}
```

Over this:

```kotlin
http (
	csrf ( disable() )
	httpBasic ( securityContextRepository = WebSessionServerSecurityContextRepository() )
	authorizeExchange (
		authorize("/auth/**", authenticated)
		authorize(pathMatchers(HttpMethod.GET, "/posts/**"), permitAll)
		authorize(pathMatchers(HttpMethod.DELETE, "/posts/**"), hasRole("ADMIN"))
		authorize("/posts/**", authenticated)
		authorize(anyExchange, permitAll)
	)
)
```

There is none. Conversely, the latter version is more interoperable between languages, thus produces less maintenance, and I'd even suspect the latter is more composable in terms of creating such a configuration dynamically, e.g. again as a result of a stream reduction.

The latter version can also produce completely immutable expression trees, whereas the former version requires some sort of builder design, where the object that is being built is mutated (the `Unit` gives it away).

### Conclusion

It's always good to take a step back and think outside the box. When kotlin came out, I did experiment with its "DSL capabilities" (the `T.() -> Unit` notation). I rejected it as a bad idea already at the time, and I haven't seen any good arguments in favour of it yet (as opposed to the classic alternatives). It always seemed to be a "because we can" feature, not a "this changes everything feature." To me, this language feature is very close to the original Scala embedded XML feature, which everyone regretted.

Given the amount of effort such an alternative notation would produce:

- For jOOQ users who need to make a choice of usage style
- For jOOQ maintainers who need to ensure everything works perfectly in both worlds

I will reject this idea. There is no win here, only effort.

**Comment by lukaseder** [comment]
> Some functions could be turned into `infix` functions though

That idea has been rejected before:

- https://github.com/jOOQ/jOOQ/issues/6256
- https://github.com/jOOQ/jOOQ/issues/12041

`infix` functions are another "clever" kotlin language feature, which I think should not have been added to the kotlin language. Scala's optional `.` and `()` tokens have produced headaches in Scala for similar reasons. Kotlin restrained such usage to "well designed areas", but the fact that specifying natural operator precedence is not possible should have been a show stopper in my opinion. Specifically, this example: https://github.com/jOOQ/jOOQ/issues/6256#issuecomment-1042107826

You write

```kotlin
T.ID mod 2 equal U.ID mod 2
```

You mean

```kotlin
(T.ID mod 2) equal (U.ID mod 2)
```

But you get

```kotlin
((T.ID mod 2) equal U.ID) mod 2
```

That's really annoying, isn't it?

Besides, some operators aren't binary in SQL (e.g. `BETWEEN` takes 3 operands, `LIKE` has a 2 or 3 operand version, etc.), and those can't be easily mapped to `infix` functions in a coherent way, so while the approach works for some things, it doesn't for others, leading to more cognitive friction when learning the API.

Another great example where jOOQ needs to tread very carefully not to prematurely add features / use language features that will only lead to pain and suffering down the line.

> The spring-kotlin-dsl comparison is not entirely fair/correct imho. Since the `this` scope changes when using extension functions you have much more flexibility as opposed to the normal builder style. No need to create intermediate variables, everything can be done in the block and kept tidy.

Yes, you have more flexibility to add random side effects in the middle of what looks like an expression but really is just a block. For what purpose, though?

In my counter examples, there was no need to create intermediate variables. Everything could be done in a single expression and kept tidy, if you will. But I probably misunderstood your point here. An example would help.

For the record, there had been a few similar ideas around e.g. `UPDATE .. SET` calls, where `SET` looks like something where one would like to profit from syntax "sugar":
https://github.com/jOOQ/jOOQ/issues/6256#issuecomment-628010674

```kotlin
update(T)
.set { id = 1; value = 2 }
.execute()
```

Again. What are we gaining (nothing, IMO)? At what cost (heavy)?

In any case, for such "simple" improvements, people can easily add quick and dirty extension functions themselves, without this having to be part of jOOQ's out-of-the-box experience. That's the blessing (and curse) of extension functions like kotlin's. Everyone gets their own jOOQ, which works differently on a per-developer basis 😅

**Comment by jbotuck** [comment]
> What is the benefit of this:
> 
> ```kotlin
> http {
> 	csrf { disable() }
> 	httpBasic { securityContextRepository = WebSessionServerSecurityContextRepository() }
> 	authorizeExchange {
> 		authorize("/auth/**", authenticated)
> 		authorize(pathMatchers(HttpMethod.GET, "/posts/**"), permitAll)
> 		authorize(pathMatchers(HttpMethod.DELETE, "/posts/**"), hasRole("ADMIN"))
> 		authorize("/posts/**", authenticated)
> 		authorize(anyExchange, permitAll)
> 	}
> }
> ```
> 
> Over this:
> 
> ```kotlin
> http (
> 	csrf ( disable() ),
> 	httpBasic ( securityContextRepository = WebSessionServerSecurityContextRepository() ),
> 	authorizeExchange (
> 		authorize("/auth/**", authenticated),
> 		authorize(pathMatchers(HttpMethod.GET, "/posts/**"), permitAll),
> 		authorize(pathMatchers(HttpMethod.DELETE, "/posts/**"), hasRole("ADMIN")),
> 		authorize("/posts/**", authenticated),
> 		authorize(anyExchange, permitAll)
> 	)
> )
> ```

I think in the former, `csrf` is not some global static import. It can only be called within an http block

**Comment by lukaseder** [comment]
> I think in the former, `csrf` is not some global static import. It can only be called within an http block. This makes the hierarchy clearer than the latter.

It seems convenient, though this can also be easily solved with types. E.g. `http()` can receive a `varargs x: HttpChildElement` types, and then, only some objects are applicable. If auto completion is smart enough to offer only reasonable choices, you get the same user experience.

Moreover, you can write utilities that produce the `HttpChildElement` subtype and compose them completely dynamically, without needing access to this implicit builder context. I'd say, that's more powerful?

So, I still think the language feature doesn't pull its weight.

**Comment by hantsy** [comment]
The `http {}` is written by Kotlin DSL.

The order of all parts in this `{}` are free, and a `{}` accepts a series of settings in it, a fixed order of parameters like a `http()` fun.

**Comment by GavinRay97** [comment]
If you're still interested in this, I wrote a small prototype of a query-builder DSL in Kotlin that uses strings and could have the logic swapped out to use `DSLContext` instead fairly easily:

https://gist.github.com/GavinRay97/c15169a22b102b9b3af49ef3e4ad2208#file-querybuilder-kt-L217-L240

What you write:

```kt
val query = QueryBuilder()
query.apply {
    from("artist")
    join(JoinType.INNER, "album") {
        eq("artist_id", "album.artist_id")
        gt("year", 2000)
    }
    select {
        col("id", "artist_id")
        col("name", "artist_name")
    }
    where {
        exists {
            selectOne()
            from("album")
            where {
                gt("year", 2000)
                not {
                    eq("name", "The Wall")
                    lt("year", 1980)
                }
            }
        }
    }
}
```

What you get:
```sql
SELECT
    id AS artist_id,
    name AS artist_name
FROM
    artist
    INNER JOIN album ON (artist_id = album.artist_id
            AND year > 2000)
WHERE
    EXISTS (
        SELECT
            1
        FROM
            album
        WHERE
            year > 2000
            AND NOT (name = The Wall
                AND year < 1980))
```

**Comment by lukaseder** [comment]
> If you're still interested in this, I wrote a small prototype of a query-builder DSL in Kotlin that uses strings

SQLi says hello 👋

**Comment by GavinRay97** [comment]
You get what you pay for, that's what 45 minutes of prototyping buys you!

**Comment by lukaseder** [comment]
Heh. Most prototypes end up in *someone's* production...
