### ISSUE TITLE
Insert statement with columns listed and values using Records should use only specified columns ignore additional in Record

### ISSUE THREAD

**Issue by apatrida** [jOOQ/jOOQ#13688]
### Use case:

Using INSERT there is no easy way to provide values of rows as Records when you are using a subset of columns within the records.  

```
ctx.insertInto(MyTable).columns(a,b,d).valuesOfRecords(recordListWithAbCd).execute(); // error
```

Record above has fields a,b,c,d but we ask to insert only a,b,d and is disallowed.

### Possible solution you'd like to see:

Allow inserting from a partial record.

### Possible workarounds:

You have to recreate your data into a new record or other type that has only the used fields instead of just having the subset be selected. 

Note `loadData` works differently for this same case (different problem).

### Versions:

- jOOQ: 3.16.6
- Java: 17

**Comment by lukaseder** [comment]
Thanks for your suggestion. I'm assuming that by `// error` and by this being disallowed, you mean a compilation error? When you specify `columns(a, b, c)`, you need to pass `Record3<A, B, C>...` values. This is consistent with the `values()` method, which also requires you to pass 3 values or a value of type `Record3<A, B, C>`

The case of the `Loader` API is different, because there, the input data is of a text format of unknown degree. Yes, there's also a way to load `Record` types using the `Loader` API, but the base type is CSV/JSON (as text) or `Iterable<Object[]>`, i.e. no degree type safety there.

So, we won't change this on the current `INSERT` API. Perhaps, one of the `Rows` collectors could help here?

```java
recordListWithAbcd.stream().collect(Rows.toRowList(
  v -> val(v),
  v -> val(v),
  v -> val(v)
));
```

Yeah, it's a bit boring to write, but might do the trick?

I'll reject this particular issue because we're not going to incompatibly relax the method signature of `valuesOfRecords()`
```
