### ISSUE TITLE
Support parsing H2's CREATE MEMORY TABLE

### ISSUE THREAD

**Issue by grandinj** [jOOQ/jOOQ#13698]
### Use case:

We are using SQL scripts to generate jOOQ classes for a H2 database. 
I would like to use a MEMORY table (in-memory only table).
I believe MySQL has a similar feature.

### Possible solution you'd like to see:

Support in the parser for CREATE MEMORY TABLE

### Possible workarounds:

None so far.

### Versions:

- jOOQ: 3.16.5
- Java: 11
- Database (include vendor): H2 1.4+
- OS: All
- JDBC Driver (include name if inofficial driver): H2 driver

Thanks!

**Comment by lukaseder** [comment]
Thanks for your feature request. Many vendors have many ways of representing such syntaxes. Currently, the myriad DDL flags on table creation, etc. don't scale well with the jOOQ API. We could, of course, parse and ignore such flags, as storage is usually not essential for jOOQ, at least not for the `DDLDatabase` use case. But before doing this particular improvement, I'd like to think more about the general case (we have an issue for that, but I can't find it right now).

On the other hand, you can do that ignoring as well, e.g. by:

- Using the `/* [jooq ignore start] */` and `/* [jooq ignore stop] */` tokens, see: https://www.jooq.org/doc/latest/manual/sql-building/dsl-context/custom-settings/settings-parser/
- By preprocessing your SQL before passing it to the `DDLDatabase`

**Comment by grandinj** [comment]
Thanks, noting that your suggestion works as follows:
    CREATE
      /* [jooq ignore start] */
      MEMORY
      /* [jooq ignore stop] */
    TABLE xxxx

**Comment by lukaseder** [comment]
Yep. Though, you don't strictly need the newlines

**Comment by lukaseder** [comment]
> But before doing this particular improvement, I'd like to think more about the general case (we have an issue for that, but I can't find it right now).

After additional thought, I don't want to support "memory tables" in jOOQ yet. The syntaxes are too different across vendors. E.g. in Oracle, you can "pin a table in memory" using:

```sql
ALTER TABLE t CACHE
```

This will keep the table in the buffer cache. It is also stored on disk, of course, because you don't want to lose the data when the process stops and memory is wiped. In Oracle, this is an optimiser only feature, not a logical feature of the table.

Anyway. Since jOOQ won't support such clauses (yet), we can help you by just parsing the keyword and ignoring it, for now.

**Comment by grandinj** [comment]
Thanks Lukas

**Comment by lukaseder** [comment]
While I'm at it, why not also parse and ignore `CACHED` at the same location
