### ISSUE TITLE
Feedback about manual section "codegen-database-regex-flags"

### ISSUE THREAD

**Issue by jiangtiqiang** [jOOQ/jOOQ#13696]
when muiti team work in many feature branch, but we can't merge it, each branch have their database version in one  database , so when we fresh jooq code,  all code can't run ,  how can we configurationn a particular table to generate code ,and other table code is no change?

----
See: https://www.jooq.org/doc/latest/manual/code-generation/codegen-advanced/codegen-config-database/codegen-database-regex-flags/

**Comment by lukaseder** [comment]
Thanks for your message.

You can't configure code re-generation only for certain tables. You can only include/exclude tables entirely from code generation, which is probably not what you want.

I'm not sure if I can follow the use-case. If you're on a branch A, you'll have a database migration set that includes your column T.A_COLUMN. When merging that onto another branch (including main), you'll merge the database increment that produces the column, as well as the generated code (if you put that under version control). So, everything is fine after the merge, no?

Obviously, this means that each branch needs to work on their own database instance, not on a shared one, otherwise, you can't really avoid messy situations.

Perhaps, use something like https://www.testcontainers.org to generate your code on your branch? Tutorial here: https://blog.jooq.org/using-testcontainers-to-generate-jooq-code/
