### ISSUE TITLE
Customize the generated Constructors in Records

### ISSUE THREAD

**Issue by muehmar** [jOOQ/jOOQ#13788]
We customized the code generation for the Java pojos, i.e. we extended the JavaGenerator and have overwritten some of the methods. We created custom getters where attributes are wrapped into a java.util.Optional if they can be NULL on the database.

Now when upgrading from 3.14.12 to 3.15.4 the generation of the records now include a constructor accepting the corresponding pojo as argument and utilizing all getters to populate the record. This does now no longer compile, as we no longer expose the getters of the attributes which may be NULL on the DB.

What options do we have? I did not see any option to disable the generation of the new constructor.

- We could expose again the getters which return null but I rather prefer a lower jOOQ version than returning back to getters which return null again which defeats the purpoes of this custom getters
- Overwrite the generation of the records, but the only protected method I found are `generateRecord` and `generateUDTRecord` which is the whole generation of the records. Better would be something like `generateRecordConstructor` but this method is private.

Is there a reason why there is no fine-grained control to customize the generation of the records like we have for the pojos? Is there a chance to have more control over the customisation of the record generation in a future jOOQ version? In our case, the possibility overriding the `generateRecordConstructor` would solve our problem. Or is there any other better solution than the two mentioned above?

### Versions:

- jOOQ: Upgrading from 3.14.12 to 3.15.4
- Java: 17

**Comment by lukaseder** [comment]
Thanks a lot for your message. Curiously, that constructor generation cannot be turned off, which is probably a limitation worth fixing. I've created https://github.com/jOOQ/jOOQ/issues/13790

I wonder though, if using `Optional` on getters is a good idea in POJOs in general. You're probably not using `Optional` in the setter either? Nor did you change `Field<T>` to `Field<Optional<T>>`? A lot of jOOQ (including `DefaultRecordMapper`) may implicitly rely on a consistent representation of a field's `T` type throughout the generated code. This may not be the only edge case that you might be running into. Getters and setters have been standardised by JavaBeans for a long time, and such custom tweaks to those conventions are asking for trouble, IMO. Also elsewhere, e.g. in Spring, EL, etc...

My personal opinion on `Optional` is that it's the wrong approach to solving nullability. The kotlin/annotation based approach using `@Nullable` and `@NotNull` annotations seems better in the long run.

Workarounds:

- Rather than patching the jOOQ generated POJOs, why not generate your own, which jOOQ doesn't know about? You can use the `JavaGenerator` APIs to do that relatively easily, I think?
- Patch the code generation to fix the status quo on your end. It's an option, of course, though not one I'd pick as you'll be maintaining this patched version for a while.

> Is there a reason why there is no fine-grained control to customize the generation of the records like we have for the pojos?

As far as turning off the constructor is concerned, I guess this was simply overlooked, see https://github.com/jOOQ/jOOQ/issues/13790

It's a slippery slope. These constructors have benefits also to jOOQ-generated code, not just to your code (not sure about this particular one, but others for sure). So every time something is made configurable, we have to account for that and make all sorts of other generated code aware of this, possibly only after some user who tries to combine N combination flags that weren't tested yet will create a bug...

**Comment by muehmar** [comment]
Thanks for your answer and the opened issue for fixing the generation.

We only customized the getter for optional fields for returning `Optional<T>`. the POJO's are immutable so we have no setter, but the constructor accepts `T` for all fields. We generated a special fluent builder which enforces one to set all required fields (same idea like the builder created here: [SafeBuilder](https://github.com/muehmar/pojo-extension#safebuilder) which calls the constructor).

We added the `@ConstructorProperties` annotation to the constructor and annotated the getters with `@Column` to make jOOQ aware how to map from and to a POJO, where the getters returng `T` for the optional fields can be private. I tried this morning another workaround where the getters of the optional fields returning `T` are public and suffixed with Nullable to make the programmer aware, that this getter should not be used (or may return null) and adjust the GeneratorStrategy to return the suffix getter name for optional properties which seems to work.

But the best approach may actually be as you suggest to create own POJO's as this will make us independent of any further changes in the code generation by jOOQ.

I know the debate concerning null and `Optional` (and also what our Java-Creaters strongly recommend :-)). We made very good experiences with avoiding null at least in the domain of the software. You have to be aware at the boundaries how your libraries or framework is working regardless if you use or avoid null, this includes also immutability. But it probably depends also on what type of software you are working on (and the opinion of course).

Regarding the missing configuration. I probably prefer creating own pojos anyway, I can imagine how difficult it will be to test all combination of the flags so feel free to decide if you really want to increase the possible options by adding a new flag as there may be a better solution to the problem like it is in my case.

**Comment by lukaseder** [comment]
> I tried this morning another workaround where the getters of the optional fields returning `T` are public and suffixed with Nullable to make the programmer aware, that this getter should not be used (or may return null) and adjust the GeneratorStrategy to return the suffix getter name for optional properties which seems to work.

Ah yes, I tried to think of it the other way round, renaming `getXyzOptional()`, but thought that this would be too annoying for your every day work (though it would be more JavaBeans compliant). Your approach obviously works here.

> But it probably depends also on what type of software you are working on (and the opinion of course).

Sure. I see everything from a language and API design perspective, in case of which `Optional` is not a good thing. But obviously, it is a pragmatic means to an end for every day business logic, which is also much more easy to evolve than languages or APIs...

> I can imagine how difficult it will be to test all combination of the flags so feel free to decide if you really want to increase the possible options by adding a new flag as there may be a better solution to the problem like it is in my case.

It will be investigated. There might be other constructors that benefit from being avoided. There are some hairy edge cases when generating interfaces for UDTs and when there are arrays of those UDTs... But yes, it's not a top priority.
