### ISSUE TITLE
Not correctly mapping 'native query' (resultQuery()) fetch result (PostgreSQL integration)

### ISSUE THREAD

**Issue by mgrebnev** [jOOQ/jOOQ#13811]
### Your question:

**Example:**

I have simple table and record generated by jooq-codegen plugin:

```
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RoleTable extends TableImpl<RoleEntity> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>ROLE</code>
     */
    public static final RoleTable ROLE = new RoleTable();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RoleEntity> getRecordType() {
        return RoleEntity.class;
    }

    /**
     * The column <code>ROLE.ID</code>.
     */
    public final TableField<RoleEntity, Integer> ID = createField(DSL.name("ID"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");
    
    ...
    ...
```
Also, i have same table:

```
CREATE TABLE ROLE (
   id serial primay key,
   name varchar not null
);
```

I need execute native query, simple select for getting rows from database:

`DSL.resultQuery("SELECT * FROM role").fetchInto(ROLE);`

I getting result in console 
```
Id  |   name
1   |   TEST_ROLE
```
Important, that columns in lower case
Next, after fetchInto, i have entity with **null** values

BUT, if i try to write query in jooq style:

```
DSL
  .selectFrom(ROLE)
  .fetchInto(RoleRecord.class);
```
i see correctly result with true row data from database and getting in logs
```
ID  |   NAME
1   |   TEST_ROLE
```
See, columns in uppercase - and mapping correctly finally

**What i think?**

**Firstly**
Codegen plugin generate, table, and fields in uppercase - i use LiquibaseDatabase:

part of configuration
```
<database>
    <name>org.jooq.meta.extensions.liquibase.LiquibaseDatabase</name>
    <properties>
        <property>
            <key>sort</key>
            <value>liquibase</value>
        </property>
        <property>
            <key>dialect</key>
            <value>Postgres</value>
        </property>
        <property>
            <key>scripts</key>
            <value>db/changelog/scripts/liquibase_package.xml</value>
        </property>
        <property>
            <key>defaultNameCase</key>
            <value>lower</value>
        </property>
    </properties>
</database>
```
any value in **defaultNameCase** doesn't has correctly result

I think that, uppercase fields relation with not correctly mapping, because result cursor from Postges has fields in lowercase (PostgreSQL default fields in lower), but in codegen any fields in upper. I really don't know, how setting plugin for generated fields and tables in lowercase, even after check plugin code

**Secondly**

If i try to execute query 

`DSL.resultQuery("SELECT id as \"ID\" FROM role").fetchInto(ROLE);`
 
and have correctly result id have value from row, but i don't want write same sql query with quotes in attributes - it's not acceptable for me

**Third**
Settings in any combination provide same result
<img width="586" alt="image" src="https://user-images.githubusercontent.com/26023005/179580187-696a9439-b130-4745-aca4-1273a9c1c6c3.png">

Any ideas how fix it? I was think that easy problem, but i din not find same problem and solutions in issues :(

### Versions:

- jOOQ: 3.16.7
- Java: 11
- Database (include vendor): PostgreSQL
- OS: macOS
- JDBC Driver: PostgreSQL 42.3.3
And use Spring Boot in underhood n my project

Thanks.

**Comment by lukaseder** [comment]
Thanks for your message. A few things to understand here:

- `org.jooq.meta.extensions.liquibase.LiquibaseDatabase` currently uses an H2 simulation behind the scenes: https://blog.jooq.org/how-to-simulate-a-liquibase-migration-using-h2. That's why the generated code uses upper case identifiers
- When you run native SQL with jOOQ, jOOQ won't know the column names in advance. It will have to reverse engineer those from JDBC's `ResultSetMetaData` (lower case in your case, because PostgreSQL). The generated code expects upper case identifiers.
- `Settings` various name case flags don't change your native SQL, which is never modified. You're not parsing your SQL query, you're executing it directly with jOOQ
- `defaultNameCase` is a configuration of the `DDLDatabase`, not the `LiquibaseDatabase`. In the latter case, we execute the liquibase.xml file directly on H2, without parsing / transforming the DDL statements before.

This is a limitation of the `LiquibaseDatabase` and its approach to simplifying the code generation process *at a price*. The price being that the code generation depends on a *simulation* of the database migration, instead of the actual migration itself. With this simulation, for example, you also cannot make use of vendor specific functionality.

A much better approach would be to use testcontainers to generate jOOQ code, if you're running into such limitations: https://blog.jooq.org/using-testcontainers-to-generate-jooq-code

The case sensitivity issue might be addressed in the future for the `LiquibaseDatabase`, though. I can't say when yet.

**Comment by mgrebnev** [comment]
@lukaseder 
Thanks a lot for answer! I try to fix it case in plugin code and getting correctly expected result

<img width="888" alt="image" src="https://user-images.githubusercontent.com/26023005/179975468-a8287ca5-76da-4b00-a3be-babf0b81b9a6.png">

Can i try to create Pull request in this topic?

**Comment by lukaseder** [comment]
Thanks for that. My comment on that workaround here: https://github.com/jOOQ/jOOQ/pull/13815#issuecomment-1191235026
