### ISSUE TITLE
jOOQ requires gradle multi module when codegen with JPA Entity 

### ISSUE THREAD

**Issue by SightStudio** [jOOQ/jOOQ#13824]
Question Summary)
Is There a way to use JPA entity based jOOQ codegen in Gradle Project without using multi module?

----
Hello, I'm tried to use jOOQ as a backup plan in project where JPA is mainly used. (also gradle is used)

So i created sample jOOQ project that

1. jOOQ DSL created by JPA entity 
(Which is reverse engineered by h2 database as documented)

2. project manged by gradle 

here's [the sample project](https://github.com/SightStudio/blog-code/tree/develop/jooq-codegen-with-entity) i created.
here's [codegen-jpa document ](https://www.jooq.org/doc/3.17/manual-single-page/#codegen-jpa)

(by the way, im using  **etiennestuder's gradle plugin**)

| document  | my project |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/50672087/180944903-1bfe58a5-946c-4058-aa75-d9e706b1aef4.png) | ![image](https://user-images.githubusercontent.com/50672087/180946948-a1186528-e2b6-4288-8948-aad4122ad109.png) |

like picture above, it requires separated gradle module that contains jpa entity. 
this forced feature makes difficult applying jooq to exsisting project.

i think this is the problem that etiennestuder's gradle plugin is not offical part of jooq. (not certainty)
(same reason for creating jooq-custom module for JPrefixStrategy, i guess)

https://github.com/jOOQ/jOOQ/issues/12985

i found [similar example project with maven ](https://github.com/jOOQ/jOOQ/tree/main/jOOQ-examples/jOOQ-jpa-example-entities). 

it works fine in same module. i hope gradle version would be easy like this...
is there any way to achieve this? or should i wait for #12985 is complete?

### Versions:

- jOOQ:  3.16.6
- Java: 17
- Database (include vendor): mysql 8.x
- OS: window, mac, linux (all)
- JDBC Driver (include name if unofficial driver):
mysql:mysql-connector-java:8.0.27

**Comment by SightStudio** [comment]
on second thought, this issue is etiennestuder's gradle plugin issue 😢

**Comment by lukaseder** [comment]
You don't *have to* use the `JPADatabase`. You can generate code from any source. I take that in an ideal project, you're using database change management that governs your schema, and your JPA entities are a derived version of that? Or are the entities your "source of truth"?

I understand that how this works is perceived as a minor hassle (and the relevant feature request that might attempt to address this is https://github.com/jOOQ/jOOQ/issues/6945, though, I'm not convinced it's a priority or that it will work well). But think about it this way. Irrespective of how your project is currently working, don't you think that entities *should* be (at least logically) separated in a separate module? What keeps you from doing this? Circular dependencies? But then, you have other problems as well, and aren't using JPA how the authors of JPA intended it...

Or, what's the problem with creating separate modules? Modules are a good thing...?

In any case, unless #6945 is implemented, I don't think there's any other way to do this.

> i think this is the problem that etiennestuder's gradle plugin is not offical part of jooq. (not certainty)

No, it's the same with the official maven plugin from jOOQ. This is by design, and it's a good thing.

> is there any way to achieve this? or should i wait for #12985 is complete?

The official jOOQ gradle plugin won't remove the need for modules in such cases. If you think it through, modular approaches are the cleanest way to achieve this. All other approaches are hacks. Think about it. You want entities to be compiled *before* the jOOQ code is generated, and then compile the jOOQ code *in the same module*? That's messy and against most models of how build systems work. A module has a single compilation phase, not multiple ones.

The #6945 approach of using annotation processing as a phase that precedes compilation is a bit of a hack. It might work around this problem, but it will create new problems (look at all the problems with APT in all other kinds of libraries, it's always a mess).

**Comment by SightStudio** [comment]
thanks for explanation. i really appreciate it.
the reason i tried to found the way using without multi-module was 
that i got huge legacy gradle project (which is not moduled currently) and i want to apply jooq before modularize project.

example project i created was part of that plan.

after reading your advice, i think i would rather modularize project first before applying it.

**Comment by SightStudio** [comment]
thanks for explanation. i really appreciate it.

the reason i tried to found the way using without multi-module was
that i got huge legacy gradle project (which is not moduled currently) and i want to apply jooq before modularize project.
example project i created was part of that plan.

after reading your advice, i think i'd rather modularize our project first before applying jOOQ.

>  You don't have to use the JPADatabase. You can generate code from any source. I take that in an ideal project, you're using database change management that governs your schema, and your JPA entities are a derived version of that? Or are the entities your "source of truth"?

no. we don't have database change management like liquibase currently.
since the project i mentioned using JPA,  so i tried to use JPADatabase.


> Or, what's the problem with creating separate modules? Modules are a good thing...?

i think i hesitate because i'm not familiar with multi-moudule. i should try. thanks...

**Comment by lukaseder** [comment]
Thanks for the feedback.

I'm aware that some legacy systems do not apply these "best practices". In almost all other aspects, jOOQ is very unopinionated about such things (e.g. jOOQ doesn't care if you have foreign keys, or even primary keys. You don't even have to be in 1NF, let alone 3NF to profit from jOOQ. This is very different from JPA, which assumes at least 1NF). But here, it would be very complicated to adapt jOOQ to such "legacy needs" and it might still not work in many cases, given the can of worms that are opened when entities aren't "self contained" but have multiple third party dependencies...

It's great that you see this as an opportunity to improve things. You will profit from modularity also outside of using jOOQ, I'm sure.
