### ISSUE TITLE
Where is the documentation describing how to add settings to mvn xml configuration

### ISSUE THREAD

**Issue by talmdal** [jOOQ/jOOQ#13837]
I'm using the maven code generator and when I try to specify the `renderQuotedNames` setting I get an error message ` Unable to parse configuration of mojo org.jooq:jooq-codegen-maven:3.15.5:generate for parameter renderQuotedNames: Cannot find 'renderQuotedNames' in class org.jooq.meta.jaxb.Generate`

I have been looking in the documentation and can't find anything that documents where this setting goes. I'm currently putting it in the generate element.  

If you could point me to the documentation for specifying the settings in the XML configuration, I would appreciate it.

In addition, is there a setting to specify the quote character use for a database, I would like to override the backticks with double quotes.

Thanks

### Versions:

- jOOQ: 3.15.5
- Java: 11
- Database (include vendor): Amazon Redshift
- OS: Ubuntu 20.04
- JDBC Driver (include name if unofficial driver):com.amazon.redshift.jdbc42.Driver

**Comment by lukaseder** [comment]
Thanks for your message. `Settings.renderQuotedNames` is a runtime configuration, not a code generation configuration. You can find all the XSDs here: https://www.jooq.org/xsd. The XSD is also referenced from the relevant JAXB generated content.

> In addition, is there a setting to specify the quote character use for a database, I would like to override the backticks with double quotes.

We don't offer this configuration independently of the dialect. You might just be using the wrong dialect? For Redshift, please use `SQLDialect.REDSHIFT` and you'll automatically get double quotes, instead of backticks. Backticks are only generated for MySQL style dialects.

**Comment by talmdal** [comment]
Thanks for the quick response
