### ISSUE TITLE
Two columns with same posgresql type varchar[] yield different types after .get(...)

### ISSUE THREAD

**Issue by hadson172** [jOOQ/jOOQ#13848]
### Expected behavior
When using .get in RecordMapper i expect that each of the get returns valid type. 

### Actual behavior
First call return array of string, second returns just a string.

### Steps to reproduce the problem
I have two tables.  Each of them have postgresql array's type varchar[]
First is 
`roles varchar[] not null;`
second
`images varchar[]` (i checked, not null does not have any effect here)

I have RecordMapper which calls:
First:
`record.get("images");`

Second
`record.get("roles");`

I have the following code:
```
        println("Roles = ${record?.get("roles")}")
        println("Roles = ${record?.get("roles")?.javaClass}")
```

The output is 
```
Roles = [Ljava.lang.String;@5a6fff6b
Roles = class [Ljava.lang.String;
```

And
```
            println("Img = ${record.get("images")}")
            println(record.get("images")?.javaClass)
```

And output
```

Img = {}
class org.postgresql.jdbc.PgArray

```

So I went to pgadmin to make a select on metadata of column. These are metadata of those two columns (the rest i null or the same).
Query:
```
SELECT column_name, data_type, dtd_identifier, udt_name
FROM information_schema.columns
WHERE table_name = 'table_1' and column_name = 'roles'
UNION
SELECT column_name, data_type,  dtd_identifier, udt_name
FROM information_schema.columns
WHERE table_name = 'table_2' and column_name = 'images';
```

Output:
![image](https://user-images.githubusercontent.com/8881977/184255297-aa0e1d34-aa8a-41da-b929-ca2d8ce5b979.png)

My question is, why the first one is Array[] and second one is PgArray ? Thanks

### Versions

    jOOQ: 3.16.8
    Java: 11
    Database (include vendor): postgresql 14.2.2
    OS: windows
    JDBC Driver (include name if unofficial driver): official 42.3.6

**Comment by hadson172** [comment]
I think I found problem. The problem is here

```
        create.select(DSL.asterisk())
            .from(table("apartment_ad"))
            .fetch { record ->
                println(record) //record.get("images") is Array<String> type
                null;
            }

        create.select(field("images"))
            .from(table("apartment_ad"))
            .fetch { record ->
                println(record) // record.get("images") is PgArray type
                null;
            }
```
This is quiet big issue and it should be consistent

**Comment by lukaseder** [comment]
Thanks for your report.

Why are you not using jOOQ's code generator? This issue would not appear if you had. See also this article for tons of reasons to use the jOOQ code generator:
https://blog.jooq.org/why-you-should-use-jooq-with-code-generation/

Even if you cannot use it (your schema is dynamic is the only objective reason why you cannot), the reason why you're running into these issues is because you didn't specify any data types for your coulmn references. Use e.g. `field("images", String[].class)` for example, to get a `String[]` data type in your result.

But really. If you can (and you probably can), please use the code generator to do all of these type mappings automatically for you.
