### ISSUE TITLE
onDuplicateKeyIgnore with H2_1_4_197 dialect throws SQL exception

### ISSUE THREAD

**Issue by nikolaychernev** [jOOQ/jOOQ#13860]
Recently we upgraded from **JOOQ OSS 3.11.5** to **JOOQ Pro 3.16.8**. The SQL dialect we used on **3.11.5** was **"H2"** which from my understanding corresponds to **H2 1.4.197**. Since upgrading JOOQ we had to change the SQL dialect to **"H2_1_4_197"** in order to fix SQL exceptions because of our older **H2 1.4.199** we use. However we still get an SQL exception because of the **onDuplicateKeyIgnore** JOOQ function.

### Expected behavior

**onDuplicateKeyIgnore** to generate **INSERT INTO WHERE NOT EXISTS** statement when using **H2_1_4_197** dialect

### Actual behavior

**onDuplicateKeyIgnore** generates **MERGE INTO** statement when using **H2_1_4_197** dialect

### Steps to reproduce the problem

1. Use **"H2_1_4_197"** dialect on **H2 1.4.199** database in **MySQL** mode
2. Execute the following code:

`create.insertInto(Tables.REQUEST_LOG, Tables.REQUEST_LOG.CORRELATION_ID, Tables.REQUEST_LOG.TIME_RECEIVED)`
`.values(correlationId, LocalDateTime.now())`
`.onDuplicateKeyIgnore()`
`.execute();`

3. "**Access database using jOOQ; bad SQL grammar [merge into**" exception is thrown

I believe the problem is in the switch statement at **InsertQueryImpl.java:586** (**JOOQ Pro 3.16.8**)

### Versions

- jOOQ: **Pro 3.16.8**
- Java: **1.8.0_221**
- Database (include vendor): **H2 1.4.199 MySQL mode**
- OS: **Windows 10 21H2**
- JDBC Driver: **org.h2.Driver**

**Comment by nikolaychernev** [comment]
Seems I can't reproduce the issue anymore, probably the was something wrong on my end. Will reopen if I manage to reproduce it again.

**Comment by lukaseder** [comment]
Thanks for your report and the update. I'll be happy to look into it when you can reproduce it. As a general remark, we don't support H2's various "modes", including the MySQL mode. We only support native H2.

Since you're using the MySQL mode in H2, I'm assuming you're using H2 as a test database? While this certainly works to some extent (especially if you're using jOOQ), we generally recommend using https://www.testcontainers.org for testing things directly against the production database product, instead, i.e. against MySQL. Benefits:

- No such test artifacts appear
- You can use all of MySQL's vendor specific features, instead of being limited by the least common denominator between MySQL and H2
