### ISSUE TITLE
Using `DSL.row(subquery.asMultiset("my_alias"))` nested-ly causes query to break unless alias is removed from multiset

### ISSUE THREAD

**Issue by GavinRay97** [jOOQ/jOOQ#13870]
### Expected behavior

The query runs

### Actual behavior

`Unknown column 'rows' in 'field list'`

```sql
Exception in thread "main" org.jooq.exception.DataAccessException: SQL [set @t = @@group_concat_max_len;
set @@group_concat_max_len = 4294967295;
select (
  select coalesce(
    json_merge_preserve(
      '[]',
      concat(
        '[',
        group_concat(json_array(
          json_extract(`v0`, '$'),
          json_extract(`v1`, '$')
        ) separator ','),
        ']'
      )
    ),
    json_array()
  )
  from (
    select
      (
        select json_array(`rows`) as `my_alias`
      ) as `v0`,
      (
        select json_array(`rows`) as `my_alias`
      ) as `v1`
  ) as `t`
) as `my_alias_two.baz`;
set @@group_concat_max_len = @t;]; Unknown column 'rows' in 'field list'
```

### Steps to reproduce the problem

```kt
val conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/db?user=root&password=Password123&allowMultiQueries=true")

val ctx = DSL.using(conn, SQLDialect.MYSQL, Settings().withRenderFormatted(true))

val exampleRowMultisetQuery = DSL.select(
    DSL.row(
        DSL.select(
            DSL.field(DSL.selectOne()),
            DSL.inline("foo")
        ).asMultiset("rows"), // remove "rows" alias to make it work
    ).`as`("my_alias")
)

val nested = DSL.select(
    DSL.row(
        DSL.select(
            exampleRowMultisetQuery.`as`("one"),
            exampleRowMultisetQuery.`as`("two")
        ).asMultiset("baz")
    ).`as`("my_alias_two")
)

val result = ctx.fetch(nested)

val jsonFormat = JSONFormat().format(true).header(false).recordFormat(JSONFormat.RecordFormat.OBJECT)
val jsonResult = result.formatJSON(jsonFormat)
println(jsonResult)
```

Without `"rows"` in the alias, the following output is printed:
```JSON
[
  { "my_alias_two": { "my_alias_two.baz": [
        {
          "one": { "multiset": [
              {
                "select": 1,
                "foo": "foo"
              }
            ] },
          "two": { "multiset": [
              {
                "select": 1,
                "foo": "foo"
              }
            ] }
        }
      ] } }
]
```

I would like to be able to control the output title of each key (IE, `baz` instead of `my_alias_two.baz`) in addition to the query working if possible.

The reason is because I have query results that need to be formatted in a particular way to be returned as an API response and post-processing the records would be difficult code to write and hurt performance.

### Versions

- jOOQ: 3.17.2 Enterprise
- Java: 17
- Database (include vendor): MySQL 8
- OS: Windows 11
- JDBC Driver (include name if unofficial driver):

**Comment by lukaseder** [comment]
Thanks a lot for your report. I'll look into this issue, soon

**Comment by lukaseder** [comment]
Thanks for your patience.

This isn't really related to `MULTISET` or the `asMultiset()` method, but to using aliased columns inside of a `ROW()` expression:

```java
ctx.fetch(select(row(field(select(row(inline(1).as("r1"), inline(1).as("r2")))))));
```

This produces:

```sql
select (select json_array(`r1`, `r2`) as `nested`) as `nested.select`
```

Which exposes the same problem:

```
Caused by: java.sql.SQLSyntaxErrorException: Unknown column 'r1' in 'field list'
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120) ~[mysql-connector-java-8.0.28.jar:8.0.28]
```

However, I'm not sure what the intention would be here? Aliasing an expression is a top level `SELECT` clause feature. What would be the purpose of providing an alias to a nested object in such a structure? Producing well-known JSON keys? But nothing about the `MULTISET` JSON serialisation is "well known," as I've mentioned previously, so that use case doesn't count here.

Is it that the behaviour surprised you, and you expected a different error? But what if the *actual* usage of aliased expressions, namely the *reference* of the alias was the thing that people desired? What if your `"rows"` object originated from a derived table, and you simply wanted to reference it (by using the alias)?

I'm not sure if I'm being clear here, but I think this describes it quite well? Your case isn't different from any other case where someone wants to use `A.as("b")`, and thinks that `A` should be rendered, when in fact, `"b"` is being rendered (correctly!):
https://www.jooq.org/doc/latest/manual/sql-building/queryparts/declaration-vs-reference/

I'm open to further criticism regarding how to clearly document the purpose of aliasing (on various resources). But I think this issue here "works as designed."

**Comment by lukaseder** [comment]
Note, the `"baz"` case is a bit different, because strangely, a different emulation kicks in, in that case.

**Comment by GavinRay97** [comment]
Ahh I see what you mean by:

> Your case isn't different from any other case where someone wants to use A.as("b"), and thinks that A should be rendered, when in fact, "b" is being rendered 

If I am understanding it, does this imply I should move from Multiset functions to explicit JSON object/array functions to build the response shape I want?

**Comment by lukaseder** [comment]
> If I am understanding it, does this imply I should move from Multiset functions to explicit JSON object/array functions to build the response shape I want?

Well, I'm reading between the lines of what you're generally doing. You want to extract JSON from your database. And you're relying on jOOQ's internal formats, trying to tweak jOOQ to produce JSON keys to your likings. But that's always going to break, for the reasons I've mentioned, which are: The formats are internal, and will change without notice, even between patch releases.

So, yes. If your output is JSON, I generally recommend using SQL/JSON. But if you're trying to be vendor agnostic, then there might be some limitations to using SQL/JSON with at least Db2 and SQL Server.

**Comment by lukaseder** [comment]
> Yeah, this is it pretty much 😅
> The Multiset and Row API's are just too easy.

Yes, they are. Though, there's really something fishy about:

- Converting stuff to JSON in the DB
- Mapping stuff back to jOOQ Records in the client
- Converting jOOQ Records back to JSON in the client

It feels... slow :)

Anyway, rather than using `as()`, perhaps you should have `rename()` available. (It's not available yet on all types). The idea behind `rename()` is to change the internal `name`, which is used in headers, like the one you're getting, but without any effect on the generated SQL.

I'll think about this a bit more. It's been requested a few times.

**Comment by lukaseder** [comment]
Yeah, the `rename()` method would be very useful on a variety of `Named` types. It's a challenging task, but it would help solve a lot of use-cases, including yours. I've created a feature request for this: https://github.com/jOOQ/jOOQ/issues/13937

**Comment by lukaseder** [comment]
Btw, thanks a lot for sharing all of these use-cases. That's very helpful. Always interesting to see how people think about jOOQ in ways I hadn't foreseen. While `as()` was the wrong tool here, the idea and approach is definitely valid, and it helped (re-)discover the utility of `rename()`

**Comment by GavinRay97** [comment]
No problem! jOOQ makes my life a helluva a lot easier, so happy to be of use any way I can in exchange 🙂

**Comment by lukaseder** [comment]
I'm glad to hear that!
