### ISSUE TITLE
add comment "// This is a generated file. Not intended for manual editing." at whole auto generated code

### ISSUE THREAD

**Issue by nabedge** [jOOQ/jOOQ#13885]
### Use case:

1. The UI of github.com uses [linguist](https://github.com/github/linguist) for **suppress generated files in diffs**. see the head of linguist readme.
2. The linguist detect that the code is auto-generated or not, by the head of comment "// This is a generated file. Not intended for manual editing." see https://github.com/github/linguist/blob/2aee6a16a6423a3727a69ce5d53c964fae69cd8e/lib/linguist/generated.rb#L574
3. So, if the java code generated by jooq have the comment above, the PullRequest UI on github.com shows jooq generated files indiffs suppressed.
4. PR Reviewer can ignore the auto-genrated code easily !

### Possible solution you'd like to see:

Please add comment "// This is a generated file. Not intended for manual editing." at whole jooq auto generated code.

**Comment by lukaseder** [comment]
Thanks for your feature request.

jOOQ supports generating the JDK `Generated` annotation, see:
https://www.jooq.org/doc/latest/manual/code-generation/codegen-advanced/codegen-config-generate/codegen-generate-annotations/

Also, the default generation target directory is `target/generated-sources/jooq`, which implies contents are generated and shouldn't be edited manually.

IDEs can already pick up these things to deduce that a file is "derived." I don't see the value of adding such a comment. Much rather than reverse engineering some random tool's internal knowledge of thousands of scripts to adapt jOOQ, why not adapt that tool and add some knowledge about jOOQ, instead?

**Comment by nabedge** [comment]
Come to think of it, maybe you are right. :-)
