### ISSUE TITLE
Extend the SQL Dialect with the H2 compatibility mode

### ISSUE THREAD

**Issue by MelleD** [jOOQ/jOOQ#13895]
### Use case:

H2 offers compatibility modes for various databases such as SQL Server or Oracle. However, not all features are always supported immediately. An example is the SET IDENTITY_INSERT which is not supported by H2.
https://docs.microsoft.com/de-de/sql/t-sql/statements/set-identity-insert-transact-sql?view=sql-server-ver16

The problem is, currently there is no chance to figure out with the SQL dialect on which database you are running (H2 SQL Server) etc. 
If there is a way, you could add a workaround to your own code base.

Example:
```
      if ( getDslContext().dialect().equals( SQLDialect.SQLSERVER ) ) {
         final String sql = getDslContext().insertInto( TABLE, TABLE.fields() ).valuesOfRecords(tableRecord ).getSQL( ParamType.INLINED );
         getDslContext().execute( "SET IDENTITY_INSERT " + TABLE.asTable().getName() + " ON " + sql );
      } else {
         getDslContext().executeInsert( tableRecord );
      }

```

This is explicitly not about supporting the complete syntax of H2's compatibility modes, that's impossible!

Discussion see here: 
https://stackoverflow.com/questions/73398506/jooq-bad-sql-grammar-for-new-h2/73400172?noredirect=1#comment129646936_73400172

### Possible solution you'd like to see:

Extend the `SQLDialect` 

    /**
     * The H2 compatibility SQL Server dialect.  The dialect uses the SQL Server dialect internally and does care that the H2 compatibility mode has implemented all features of SQL Server.
     * <p>
     * This dialect is available in commercial jOOQ distributions, only.
     */
    @Pro
    H2_SQL_SERVER("SQLServer", true, true, SQLSERVER)

    @Pro
    H2_ORACLE("ORACLE", true, true, ORACLE)

### Possible workarounds:

Run H2 without compatibility mode 

### Versions:

- jOOQ: 3.16
- Java: 17
- Database (include vendor): Azure SQL and H2 (locally)
- OS: *
- JDBC Driver (include name if unofficial driver): SQL Driver and H2 driver

**Comment by lukaseder** [comment]
Thanks for your feature request.

As promised on the linked Stack Overflow discussion, I still strongly disagree this is a good idea for both jOOQ and/or users. I've explained this more in detail in this blog post here, as users seem to frequently try to make this combination of jOOQ and H2 features work:
https://blog.jooq.org/using-h2-as-a-test-database-product/

In short: H2's compatibility modes were invented when H2 is being used via *JDBC directly*, and the SQL string is native T-SQL. This makes sense to some extent when you're not using jOOQ, and when testcontainers did not yet exist.

But when you're using jOOQ, you're using the jOOQ API, and jOOQ can generate valid T-SQL *and* H2 SQL. All of our integration tests cover this. So, what you call a "possible workaround" is the ideal solution.

I still fail to understand what the point is to use H2 in a compatibility mode when using jOOQ. What benefits are you actually expecting to get out of this, knowing that the compatibility modes are much less well integration tested both by H2 and jOOQ? Both here and on Stack Overflow, you never mentioned why you insist on this approach, rather than what I'd say obviously works much better from a jOOQ perspective.

To give you a little insight into what you're asking here:

- A quick and dirty attempt of trying your combination with jOOQ's integration tests produces 708 test failures!
- The most important failures include:
  - `RETURNING` emulations work entirely differently between SQL Server and H2
  - Functions like `IIF`, `STDEV` aren't supported in H2's SQL Server mode (though jOOQ can very easily emulate them on both dialects!)
  - There are weird errors like `CHARACTER VARYING SIGNUM` not supported, whatever that means
  - Some things are obviously not supported, like `CREATE DATABASE`
  - Some stored procedures like `SP_RENAME` aren't available (though jOOQ would generate the correct H2 SQL for those calls, like renaming indexes, etc.!)
  - Composite DDL is emulated using anonymous T-SQL blocks, none of which is supported by H2, but we can also generate anonymous H2 stored procedures, so it would have worked with native H2!
  - Some failures look like H2 bugs, that manifest only with that compatibility mode
  - Bitwise operations aren't implemented correctly, see https://docs.microsoft.com/en-us/sql/t-sql/language-elements/bitwise-operators-transact-sql?view=sql-server-ver16
  - Recursive SQL emulations produce wrong results, which is likely a bug in H2. That bug isn't exposed when using H2 native.
  - Domains / types don't work correctly (T-SQL calls standard SQL domains "type")
  - Stored procedures and functions and all the other procedural code doesn't work correctly (but it does work on H2 native!)

I'm only at `testC...` so I could enhance this list with probably at least 50 more categories of things not working. I'm not surprised. Again:

- jOOQ is very well integration tested against native T-SQL *and* native H2
- jOOQ is not at all integration tested against what you're expecting here
- It seems that also H2 is not too well tested when it comes to compatibility modes. They can't possibly test all of that. jOOQ could, but that would have a price (see below).
- Look at the number of issues I've found already in H2 native, in the past: https://github.com/h2database/h2database/issues/created_by/lukaseder to give you an idea of how much trouble you're asking for. Now duplicate all of these issues by the number of supported compatibility modes, because I'm sure I'll find dozens of issues for each one of them.

jOOQ could obviously start supporting what you're requesting. It's not impossible. But you can see the amount of effort both on the jOOQ and H2 side. This would have to be a sponsored project. Given that jOOQ works *very well* on both native SQL Server and H2, I really recommend you review your expectation here. But if you insist, I'm open to negotiating a sponsored project, without guaranteed success, because:

- H2 also would have to fix tons of things (probably more), and sponsoring there seems to be more difficult to achieve, as no one seems to be accepting any money.
- This would have to be done for all of H2's compatibility modes, not just SQL Server, so I'd expect the project to be excessively expensive, compared to how simple the alternative is, which already works very well.
- *Every* single future jOOQ and/or T-SQL feature would have to be reported to H2 as a feature request for their compatibility mode, because I'm very sure it doesn't work yet. I mean, if we do it, we do it right. And there's still no high chance of success of getting all of these features in. I mean, where does it stop? E.g. do you expect H2 to implement `FOR JSON` and `FOR XML`? Because that's what's needed if you want to emulate `MULTISET` with T-SQL, rather than with native H2 SQL. I can already tell you that it won't be implemented in H2, but still, jOOQ will have the efforts of managing all the integration test failures one by one, meaning the whole integration is of very poor quality.
- H2 has been very much of a moving target with backwards incompatible changes even between patch releases. I would expect things to be much worse when it comes to the poorly documented compatibility modes. So, sooner rather than later, you'd like an `H2_SQLSERVER_2_1_214` dialect to distinguish between this version of H2 and another one.
- All of this is just because you're using H2 as a test database product, rather than using testcontainers, which brings me back to this blog post: https://blog.jooq.org/using-h2-as-a-test-database-product/
- By the time any of this is implemented, you will have moved towards integration testing your application with testcontainers anyway, so you'd be unlikely to even profit from this 😅

So, again, as I said on Stack Overflow, and as I've shown above, I think you're underestimating the effort for jOOQ, and you're overestimating the value for yourself, which you still haven't stated.

Before I can clearly see and agree with what value you're expecting out of this, I suggest closing this issue here. It's now both on Stack Overflow and here on github, so others can chime in and provide their feedback. It's not impossible I'm overlooking something, but I think you can now see why I'm *very* reluctant to implement support for H2's compatibility modes.
