### ISSUE TITLE
Add DDL support for the CITEXT type

### ISSUE THREAD

**Issue by marshmello275** [jOOQ/jOOQ#13960]
### Expected behavior

Need to create table with CITEXT column in it

### Actual behavior

I tried to create table with CITEXT column. Still getting the same error which reported [here](https://github.com/jOOQ/jOOQ/issues/5934)

ERROR: type "citext" does not exist Position: 83 at org.jooq_3.17.2.POSTGRES.debug(Unknown Source)
Environment: psql (PostgreSQL) 11.16 (Ubuntu 11.16-1.pgdg20.04+1)

### Steps to reproduce the problem
**Code Snippet**

```
String sqlString = "CREATE TABLE module(id SERIAL NOT NULL PRIMARY KEY, name CITEXT NOT NULL UNIQUE);";

DSLContext context = using(new DefaultConfiguration().set(new DataSourceConnectionProvider(ConnectionManager.getDataSource()))
                        .set(SQLDialect.POSTGRES)
                        .set(new Settings().withRenderMapping(new RenderMapping()
                                    .withSchemata(new MappedSchema()
                                                .withInput("referenceSchemaName")
                                                .withOutput("schemaName")))));

context.transaction(configuration -> {context.setSchema("schemaName").execute();
			context.execute(sqlString);
		});
```

### jOOQ Version

3.17.2

### Database product and version

psql (11.16 (Ubuntu 11.16-1.pgdg20.04+1))

### Java Version

1.8.0_312

### OS Version

Operating System: Ubuntu 20.04.4 LTS
Kernel: Linux 5.14.0-1051-oem

### JDBC driver name and version (include name if unofficial driver)

postgres driver - postgresql-42.2.19.jar

**Comment by lukaseder** [comment]
Thanks for your report. The referenced issue https://github.com/jOOQ/jOOQ/issues/5934 was about code generation support for `CITEXT` via out of the box data type bindings and converter. This issue here is different, and not strictly related to  `CITEXT`.

You're setting the search path to *only* `"schemaName"`, when in fact, the `citext` data type is a type located in the `public` schema.

Try this, and it works:

```java
String sqlString = "CREATE TABLE module(id SERIAL NOT NULL PRIMARY KEY, name public.CITEXT NOT NULL UNIQUE);";
```

If you were using PostgreSQL's `set search_path = ...` command natively, you'd set it to `"schemaName", public` not just `"schemaName"`

I hope this helps
