### ISSUE TITLE
API discoverability and wrong imports in the manual

### ISSUE THREAD

**Issue by juriad** [jOOQ/jOOQ#13975]
### The documentation URL

https://www.jooq.org/doc/3.17/manual-single-page/

### Feedback

Out of curiosity, I looked at what imports are used in the manual:
```
wget -p https://www.jooq.org/doc/3.17/manual-single-page/
grep -ro 'import[^ias-].*;' | sort | uniq -c
```

Mainly I was interested in `import static` - to look for constants/static methods that are useful, badly discoverable, and not mentioned in the recent article: https://blog.jooq.org/a-brief-overview-over-the-most-common-jooq-types/ . 
The answer was:
```
import static org.jooq.impl.DSL.*;
import static org.jooq.impl.SQLDataType.*;
import static org.jooq.SQLDialect.*;
import static org.jooq.tools.Convert.convert
```
Some other interesting classes discovered by:
```
grep -ro '[A-Z][a-zA-Z_]*\.[a-z][a-zA-Z_]*[(]' | sort | uniq -c
```
are:
```
Converter.of()
Converter.ofNullable()
CustomCondition.of()
CustomField.of()
Records.* // only mapping is mentioned
Traversers.* // only collecting is mentioned
```
First two are well discoverable; the others not so much (in my opinion).

I also looked through the classes in `org.jooq` package and found these util classes that are not mentioned in the manual:
```
Converters
Functions
Rows
```
A user has a slim chance finding unless they already know about them. Would it be worth extending the article with static methods and where to find them?

While having all imports in hand, I noticed some flaws:
* First example `PostgresJSONGsonBinding` (btw, there are two - one for `Object` and one for `JSON`)
  - `import static org.jooq.tools.Convert.convert;` - used; deprecated
  - `import org.jooq.conf.ParamType;` - missing (asterisk import in a similar example)
  - `import java.util.Objects;` - missing (asterisk import in a similar example)
* Example `PrettyPrinter`
  - `import org.jooq.impl.DSL;` - missing
  - `import org.jooq.tools.StringUtils;` - unused
* Example `AsInDatabaseStrategy`
  - qualified method call `org.jooq.tools.StringUtils.toCamelCase(definition.getOutputName());` - use import instead
  - lots of imports missing
* Example `AfterMigrationTest`
  - `import java.sql.Connection;` - missing
* Example `JSONConverterProvider`
  - `import static org.jooq.impl.DSL.*;` - unused
  - `import com.fasterxml.jackson.databind.ObjectMapper;` - missing
  - `return (T) JSON.valueOf(mapper.writeValueAsString(u));` - compilation error - method does not exist
* `ConvertProvider`'s first example
  - refers in text to `org.jooq.tools.Convert` which is deprecated
  - `import org.jooq.impl.*;` brings in `org.jooq.impl.Convert` that is package private
* The second example with `LOGICAL_XOR`
  - `import static org.jooq.SQLDialect.*;` - unused
  - does not compile, missing `}` to end `switch` and missing `)` to end `derive`
* `MyDSL` first example
  - `import static org.jooq.impl.DSL.*;` - unused
* `MyDSL` second example
  - `import static org.jooq.SQLDialect.*;` - unused
  - `import static org.jooq.impl.DSL.*;` - unused
  - `arg0, arg1` should be `field, format`
* Example of Using ResultSet concurrency with ExecuteListeners
  - `import javax.sql.*;` - unused
  - `import static org.jooq.SQLDialect.*;` - unused
  - `import static org.jooq.impl.DSL.*;` - unused
  - `import org.jooq.exception.DataAccessException;` - missing (in a lot of examples actually)

I did not test every example, just some that caught my eye.

**Comment by lukaseder** [comment]
Thanks for your message.

The imports in the manual are currently generated based on heuristics. The examples will be taken from actual code samples in the future (see  https://github.com/jOOQ/jOOQ/issues/13617), in case of which the imports can be improved explicitly, e.g. using an IDE. But currently, they're a bit fuzzy, and "good enough". This leads to unused imports, of course, because the heuristic for `DSL.*` is that it's almost always used.

So, before https://github.com/jOOQ/jOOQ/issues/13617 is implemented, there's no reasonable way to change this.

Your report mixed a few concerns, I'll try to reply to them here:

> First two are well discoverable; the others not so much (in my opinion).

I'm not sure what you're suggesting here. We can always overdocument things. A lot of these things seem too advanced for a cheat sheet. But perhaps you can re-state your idea with a few more details and why you think things should be improved? I certainly don't think that `Rows` is a type any jOOQ-newbie should know about. I don't know how to make that discoverable for the pros without overwhelming 99% of users who will never need it.

> * used; deprecated

I could address this, but again, the effort of maintaining deprecations in imports is tremendous, and the fix would be automatic once #13617 is implemented, so I prefer not to.

> * `import org.jooq.conf.ParamType;` - missing (asterisk import in a similar example)
> * `import java.util.Objects;` - missing (asterisk import in a similar example)

Indeed, these are missing, but again, I'm willing to live with this little flaw, because there might be others, and we'll never finish this kind of work, unless we address this *thoroughly*, via #13617

> * qualified method call `org.jooq.tools.StringUtils.toCamelCase(definition.getOutputName());` - use import instead

It could be done, sure.

> * `return (T) JSON.valueOf(mapper.writeValueAsString(u));` - compilation error - method does not exist

Which one doesn't?

> * does not compile, missing `}` to end `switch` and missing `)` to end `derive`

Thanks. I've fixed this.

I'll be happy to address individual compilation errors like that last one even before implementing #13617. But keeping in mind that if an import is missing, I wouldn't consider this a compilation error. The whole snippet isn't compilable as is, because the code isn't placed in a class and method anyway. #13617 will ensure that every example can be downloaded from github and compiled / run directly.
