### ISSUE TITLE
add DSL.jsonValue() for non-JSON columns

### ISSUE THREAD

**Issue by martinmuellerrohde** [jOOQ/jOOQ#13991]
### Use case

Even though JSON is supported by many databases, not every DB developer uses JSON as data type for columns.
If other data types are used for columns containing JSON, e.g. longtext, CLOB, ..., then JSON-functions like `DSL.jsonValue(Field<String> json, String path)` will not be accepted.

Unfortunatly a simple `CAST <my-string-column> as JSON` will not be accepted by MariaDB and possibly other databases.

### Use case

Adding more overloadings like

```java
public static JSONValueOnStep<JSON> jsonValue(Field<Strin> json, String path) { ...
```

would help to deal with this.

### Possible workarounds

as long as jOOQ doesn't like String-Columns with DSL.json_value(), we can use plain SQL templating:

```java
Field<String> extractedValueFromJson= DSL.field("json_value({0}, {1})", String.class, MyTable.MY_TABLE.A_STRING_COL, DSL.inline("$.aField"));
``` 

and use extractedValueFromJson inside your jOOQ-statements

### jOOQ Version

jOOQ pro Java11 3.17.4

### Database product and version

MariaDB 10.3.17

### Java Version

java version "11.0.12" 2021-07-20 LTS

### OS Version

Windows 11

### JDBC driver name and version (include name if unofficial driver)

org.mariadb.jdbc:mariadb-java-client:2.7.5

**Comment by lukaseder** [comment]
Thanks for your feature request.

If you're thinking this through, what you're effectively asking for is to remove all type safety from every jOOQ DSL function, etc. because developers might just use `VARCHAR` for any data type. For example, they might use `VARCHAR` to store `INTEGER` values, so you'd like to see `DSL.abs(Field<?>)` and to automatically "do the right thing."

But that would remove half of what jOOQ offers to users: Type safety guarantees. I don't like that idea. Why not just apply data type rewriting to your code generation and hint the code generator that a specific column is a JSON column, in fact?
https://www.jooq.org/doc/latest/manual/code-generation/codegen-advanced/codegen-config-database/codegen-database-forced-types/codegen-database-forced-types-rewrite/

Alternatively, you can do this on an ad-hoc basis. Don't "cast" (as that would affect generated SQL), but "coerce" your String expressions to the JSON type:
https://www.jooq.org/doc/latest/manual/sql-building/column-expressions/datatype-coercions/

I hope this helps

**Comment by theodiefenthal** [comment]
> If you're thinking this through, what you're effectively asking for is to remove all type safety from every jOOQ DSL function, etc. 

I don't think you can compare casting INT from VARCHAR with the problem here. MariaDB explicitly supports passing in a String as well as passing in a JSON into the `json_value` function. (As MariaDB JSON simply is an alias for longtext) In their official example, they even pass in a hardcoded string to that function: https://mariadb.com/kb/en/json_value/ 

So supporting Field<String> on jsonValue would simply mean supporting the method which MariaDB offers in its API.. 

But I also like the approach with coerce with the need to be a bit more explicit in code and showing that one is dealing with JSON in a dedicated string field...

**Comment by lukaseder** [comment]
Try this, in MariaDB:

```sql
select abs('-1');
```

Seriously, where does it end? 😅 Maybe, you think that this is a different case, because you never thought of it. But once we start pretending `String` is really the same thing as some type `X`, then other users will also want to "just" have a "slight" adaptation here and there.

We have to be diligent with such things. Starting to pretend that a `Field<String>` and a `Field<JSON>` can be the same thing is a huge project in jOOQ, not "just" a tiny convenience. Once jOOQ loses the type information that `SQLDataType.JSON` provides jOOQ at runtime, we can no longer be sure what do do with an expression. An ordinary `String` that is used in a JSON context is a JSON string, not a JSON document. E.g. these are not the same:

```sql
select 'null' != '"null"'
select 'false' != '"false"'
select '{}' != '"{}"'
```

How would we be able to distinguish between them, if we lose the type information on a `Field<T>`?

The convenience you're looking for will open a pandora's box of edge cases. Just because *you* know that your column is effectively a JSON document doesn't mean that jOOQ can make such assumptions about arbitrary `Field<String>` values.

Besides, overloading things consistently this way is hard in Java because of type erasure. You can't have:

```java
method(Field<String> f);
method(Field<JSON> f);
```

If we had union types, then the correct type would be possible:

```java
method(Field<String | JSON> f);
```

But we don't. So the only possible way to accept both `Field<T>` types is to use a wildcard:

```java
method(Field<?> f);
```

Which would open up even more edge cases, where other data types are passed in and we'd have to disambiguate things, keeping in mind that no such decision can ever be made in isolation of a single JSON function, it always has to be done with the "bigger picture" in mind, that of all JSON functions, and probably even more non-JSON functions.

All the while you have two very simple tools to do the right thing on your end, namely telling jOOQ that this `Field<String>` is really a `Field<JSON>`, because *you* know that.

> So supporting `Field<String>` on jsonValue would simply mean supporting the method which MariaDB offers in its API..

The fact that apart from PostgreSQL, none of the other vendors have done this the right way is very troubling. Introducing a `JSON` type has been absolutely necessary, just like introducing an `XML` type was necessary. Even Oracle 12c made this mistake (despite having done the right thing for `XML`), which they fixed in 21c (or 19c?), by adding a formal JSON type. Without the JSON type after the fact. The JSON semantics always has to be shoe-horned into the SQL statement, because now, in MariaDB, you never really know whether a string is a string or a json document.

There are tons of super annoying bugs like this, which jOOQ works around:
https://jira.mariadb.org/browse/MDEV-26134

Imagine what this means for MariaDB. The parser has to be super clever all the time to be able to distinguish between strings and strings. And if you make the slightest mistake, boom. You get a string again, when you thought you had a document, e.g. `{"a": "[1, 2]"}` instead of `{"a": [1, 2]}`

But these workarounds only work if jOOQ *knows* the difference between a `Field<String>` and a `Field<JSON>`, so even if MariaDB sometimes can't figure out the difference on its own, at least jOOQ can tweak the SQL to get the right behaviour.

Replicating this big design mistake of many RDBMS in jOOQ would be a big mistake as well. `Field<String>` and `Field<JSON>` are two very distinct things in jOOQ. We mustn't be clever here, but strict.

**Comment by theodiefenthal** [comment]
Thank you for the very detailed explanation. Now I fully agree with you not supporting `Field<String>` :)
