### ISSUE TITLE
Syntactic Sugar: multisetAgg or toSet filtering NULL

### ISSUE THREAD

**Issue by theodiefenthal** [jOOQ/jOOQ#13992]
### Use case

Quite often, the new feature of `multisetAgg` is used along with LEFT JOINs. 

Let's say, I have a `user` as dimension table and fact table `paid_subscriptions`. I want to query a specific user with all of his paid subscriptions and for each subscription do some processing (like sending an email or whatever). 

I would write some JOOQ like this:

```
ctx
                .select(row(
                        USER.ID,
                        USER.USERNAME,
                        multisetAgg(PAIDSUBSCRIPTIONS.SUBNAME).as("subscr").convertFrom(r -> r.intoSet(Record1::value1))
                        ).mapping(MyUserWithSubscriptionPOJO::new)
                )
                .from(USER)
                .leftJoin(PAIDSUBSCRIPTIONS).onKey()
                .where(someCondition)
                .groupBy(USER)
                .fetch(Record1::value1));
```

The problem here is: the `multisetAgg` produces a Set which can contain `null` as element.

I either heve to filter out the `null` subscriptions I don't care about after JOOQ select, or I have to rewrite my query with something like this:
```
multisetAgg(PAIDSUBSCRIPTIONS.SUBNAME).as("subscr").convertFrom(r -> {
                                    final Set<String> res = r.intoSet(Record1::value1);
                                    res.remove(null); // remove possible nulls
                                    return res;
                                })
```

Both don't look too nice in code. 

I wonder if it would make sense to add some syntactic sugar like `multisetAggWONull` or `r.intoNonNullSet` or similar? I often end up with some java8 style stream processing of my left joined collection and first step is to filter out null which is something I forget often :) 

### Possible workarounds

described in the use case. 

### jOOQ Version

JOOQ Professional 3.17.4

### Database product and version

independent

**Comment by lukaseder** [comment]
Thank you very much for your feature request.

You're asking for a few things here:

- `SET` instead of `MULTISET` (will be addressed with #12033)
- Adding `NULL` filtering (is already possible with `FILTER`)
- The implied idea that such `NULL` values could be removed automatically (might be addressed with #13776)

## `SET` instead of `MULTISET`

The SQL standard has some notions of a `SET` as opposed to `MULTISET` or `ARRAY`. For example:

- https://github.com/jOOQ/jOOQ/issues/13795

It isn't as powerful as `MULTISET`, and it doesn't have to be, because usually, just by adding `DISTINCT` you can turn any `MULTISET` into a `SET`. Nevertheless, Informix (possibly the most powerful ORDBMS) does have `SET` data types and constructors:

- `LIST` (`ARRAY`) https://www.ibm.com/docs/en/informix-servers/14.10?topic=types-liste-data-type
- `MULTISET` https://www.ibm.com/docs/en/informix-servers/14.10?topic=types-multisete-data-type
- `SET` https://www.ibm.com/docs/en/informix-servers/14.10?topic=types-sete-data-type

So, we might add support for this in the future, perhaps. I'm not sure yet of its utility, as opposed to using `DISTINCT` with `MULTISET` (already possible) or `MULTISET_AGG` (possible soon):

- https://github.com/jOOQ/jOOQ/issues/12033

## Adding `NULL` filtering

You already have the `FILTER` clause to do this directly in SQL:
https://www.jooq.org/doc/latest/manual/sql-building/column-expressions/aggregate-functions/aggregate-filter/

A native SQL example, as supported by e.g. PostgreSQL:

```sql
select 
  t.a, 
  json_agg(u.c),
  json_agg(u.c) filter (where u.b is not null)
from (values (1), (2)) t (a)
left join (values (2, 'a'),(2, 'b'),(3, 'c'),(3, 'd')) u (b, c) on t.a = u.b
group by t.a
```

Producing:

```
|a  |json_agg  |json_agg  |
|---|----------|----------|
|1  |[null]    |          |
|2  |["a", "b"]|["a", "b"]|
```

So, just write:

```java
multisetAgg(PAIDSUBSCRIPTIONS.SUBNAME).filter(PAIDSUBSCRIPTIONS.ID.isNotNull())
```

## The implied idea that such `NULL` values could be removed automatically

Note, I understand that you'd probably like this to be done automatically. There's a thorough discussion on that subject here: https://github.com/jOOQ/jOOQ/issues/13776. As always, it's a desirable thing that is far from easy to implement consistently.

I'm positive that this will be done eventually, but it's a very big change.

## Conclusion

Given that there's nothing left to do here that isn't already possible (`FILTER`) or will be addressed elsewhere (#13776, #13795), I'm closing this as a duplicate.

**Comment by lukaseder** [comment]
Note, if you have some time: For improved visibility in case others have the same question, I wouldn't mind repeating my answer also on Stack Overflow: https://stackoverflow.com/questions/tagged/jooq

I'm sure it would be useful to others.

**Comment by lukaseder** [comment]
https://github.com/jOOQ/jOOQ/issues/12033 (`MULTISET_AGG(DISTINCT)`) has been implemented for jOOQ 3.18

**Comment by theodiefenthal** [comment]
Thanks as usual. Everyday, there is something to learn. :) I somehow like the `FILTER` clause I wasn't aware of.

**Comment by lukaseder** [comment]
Yeah, it's a SQL standard, too!
