### ISSUE TITLE
Allow dynamic registration of `ExecuteListener`

### ISSUE THREAD

**Issue by scottsteen** [jOOQ/jOOQ#14044]
### Use case

I'm hoping for a way to enable an `ExecuteListener` across _all_ `Configuration` instances, dynamically.

Some context:

We create an instance of `DSLContext` for each one of our repositories. This is constructed _in_ the repository constructor - the constructor only exposes a `DataSource` as a dependency:

```java
public PostgresRepository(DataSource ds) {
  this.dsl = DSL.using(ds, POSTGRES);
}
```

What I'd like to do is set up an `ExecuteListener` that identifies repeated statements. This would be similar to [this blog post](https://blog.jooq.org/using-jooqs-diagnosticsconnection-to-detect-n1-queries/), but with integration into `dsl.select()`. 

Obviously, and as per the blog, I don't want this running in production code, only in the tests. I'd also like this to be enabled without developer involvement - an author would not be able to forget to turn on the detection for their new repository/test.

We've had a fair few instances of N+1 queries. While we try to catch these in review, a hard block or even just automated feedback would be awesome.

### Possible solution

Perhaps the ListenerProviders could be implemented using Java's [ServiceLoader](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/ServiceLoader.html). 

I took the liberty of creating [an example](https://github.com/jOOQ/jOOQ/commit/bfd5ef9491edc5f3d70a6795a55e92ed60b266c0) to help illustrate the desire. It's built for `DiagnosticsListener`, but the idea could be applied to any Listener.

### Possible workarounds

An obvious workaround would be to create a single jOOQ `Configuration` to be used by all repositories. We use a DI framework, so that's achievable. The drawback to this is that we don't use DI in our repository integration tests - we just construct the repository the old fashioned way. As said above, this could lead to test authors forgetting to set up the Configuration correctly. There are mitigations to this, of course - factory methods, etc - but it isn't fool proof.

Also open to any alternatives I've not considered/am unaware of!

### jOOQ Version

jOOQ Community 3.14.16

### Database product and version

PostgreSQL 14.3

### Java Version

openjdk 17

### OS Version

Various Windows/Mac/Linux

### JDBC driver name and version (include name if unofficial driver)

org.postgresql:postgresql:42.3.7

**Comment by scottsteen** [comment]
I was unable to get the `DiagnosticsListener` to work. After putting together a concrete example of our implementation (see [here](https://github.com/scottsteen/jooq-diagnostics-example)), I realise I missed the bit at the bottom of the blog that mentions `DiagnosticDataSource` & `Connection`. I'm not sure how to configure these, do you have any examples? 

> I think the best approach for you here is really to use dependency injection

I did figure this would be the advice 😅 we do indeed use Spring (and some of Boot). It's a bit more invasive than I'd hoped, but I'll move some code around & see what it looks like. It sadly does still leave non-Spring-based-test authors the ability to miss the required set up, but I'm sure that's something we can live with.

> Constructing a different DSLContext in each repository doesn't seem right to me

This is most likely due to our inexperience with `jOOQ`. We opted to keep it as an implementation detail of the repository, instead of exposing this via the constructor's API.

**Comment by lukaseder** [comment]
> I realise I missed the bit at the bottom of the blog that mentions `DiagnosticDataSource` & `Connection`. I'm not sure how to configure these, do you have any examples?

It's just a JDBC `DataSource` / `Connection` that wraps (proxies) the actual `DataSource` / `Connection`. Use that with jOOQ, instead of the actual `DataSource` / `Connection`. I'm not sure what kind of example this needs?

> I did figure this would be the advice 😅 we do indeed use Spring (and some of Boot). It's a bit more invasive than I'd hoped, but I'll move some code around & see what it looks like. It sadly does still leave non-Spring-based-test authors the ability to miss the required set up, but I'm sure that's something we can live with.

All you need to do is replace

```java
public PostgresRepository(DataSource ds) {
  this.dsl = DSL.using(ds, POSTGRES);
}
```

... by this:

```java
public PostgresRepository(Configuration configuration) {
  this.dsl = DSL.using(configuration);
}
```

And every piece of logic (Spring based or not), will automatically have to "inject" the right `Configuration` to the repository. Dependency injection is just a fancy word for constructor parameters... It doesn't matter how you implement it.

> This is most likely due to our inexperience with `jOOQ`. We opted to keep it as an implementation detail of the repository, instead of exposing this via the constructor's API.

Well, the opinionated nature of most DI require to pass things via constructor to the internals of a repository. Constructors are not strictly "API" anymore. Spring also supports "field injection," which is a bit more controversial

```java
@Autowired DSLContext dsl;

public PostgresRepository() {
}
```

It works the same way for Spring, but now you *have to* use Spring to inject the `Configuration` into your repositories.

There are other ways to do these things, too. But since you're using Spring anyway, why not just use the recommended Spring way (possibly also for tests).

**Comment by scottsteen** [comment]
> I'm not sure what kind of example this needs?

The constructor (and class!) of `DiagnosticsDataSource` is package-private.  I'd need to do some work to make this visible to my code, if I'm not mistaken.

It also requires a `Configuration` instance. Again, I could totally be missing something simple, but the cycle seems prevent chaining the `.set()` calls - is this expected? Example:

```java
var configuration = new DefaultConfiguration();
configuration.set(new DiagnosticsDataSource(configuration));
this.dsl = DSL.using(configuration);
```

> why not just use the recommended Spring way (possibly also for tests).

Without going into our code's architecture too much, we decided to design our software as "plain old Java" & apply Spring IoC to that. The alternative being designing software that is wholly dependent on & coupled to Spring.

`jOOQ` was kept as an implementation detail at the start of the project as we were evaluating it. At this point, we're loving the control it gives us over our SQL & therefore software design, so it's probably safe to say the evaluation was a success. This could be a good driver for us to expose `DSLContext/Configuration` as a dependency in our repository constructors. I'm sure we can do something to make our non-Spring tests as easy as possible to set up.

Having read through [7527](https://github.com/jOOQ/jOOQ/issues/7527), I'm really excited to start using some of the ideas you've got planned there.

**Comment by lukaseder** [comment]
I see, the confusion seems to stem around the fact that 2 distinct, nested configurations are needed. So you could do something like:

```java
DataSource ds = new DefaultConfiguration()
    .set(actualDataSource)
    .set(otherStuff)
    .dsl()
    .diagnosticsDataSource();
```

Now, use `ds` instead of `actualDataSource` everywhere. The `configuration` you see above is only to configure the `DiagnosticsDataSource`. You'll create a separate `Configuration` for your jOOQ usage:

```java
DSLContext dsl = DSL.using(new DefaultConfiguration().set(ds).set(otherStuff2));
```

> Having read through [7527](https://github.com/jOOQ/jOOQ/issues/7527), I'm really excited to start using some of the ideas you've got planned there.

Yeah, those are some really interesting things, indeed!

**Comment by scottsteen** [comment]
> I see, the confusion seems to stem around the fact that 2 distinct, nested configurations are needed. So you could do something like:

Awesome, thanks for the tip!

**Comment by lukaseder** [comment]
I've had another review of this issue. There had been 2 things:

- Confusion about diagnostics, which are resolved
- A request about `ExecuteListener` being its own "DI framework," which I rejected, because there's nothing existing DI frameworks can't do here.

The original request was made because production code used one approach of initialising a `Configuration`, while test code used another one. Rather than offering new features in jOOQ not related to jOOQ (i.e. DI), the recommendation is to fix the user configuration setup.

So, there's nothing left to do in this issue.

**Comment by scottsteen** [comment]
Sounds good to me. Thanks for your time reviewing this!

We took your advice & exposed our jOOQ config outside of the repositories.
