### ISSUE TITLE
jsonObjectAgg should allow enum type as key

### ISSUE THREAD

**Issue by JayAhn2** [jOOQ/jOOQ#14050]
### Expected behavior

```
val TYPE: TableField<JFoodCardScoreRecord, FoodCardScoreType?> = createField(DSL.name("type"), SQLDataType.VARCHAR.nullable(false).asEnumDataType(co.sprintapp.api.enums.JFoodCardScoreType::class.java), this, "", EnumConverter<JFoodCardScoreType, FoodCardScoreType>(JFoodCardScoreType::class.java, FoodCardScoreType::class.java))
```
```
       key("scores").value(
          field(
            select(
              jsonObjectAgg(
                score.TYPE, // HERE
                score.AMOUNT
              )
            )
              .from(score)
              .where(score.FOOD_CARD_ID.eq(foodCard.ID))
          )
        ),
```

score.TYPE is a column mapped to enum, so it should be projected to the below.

```
val scores: Map<FoodCardScoreType, Short> = mapOf(),
```

### Actual behavior

jsonObjectAgg takes only `string` type as a key, so I need to call .toString() from enum type as below.

 ```
       key("scores").value(
          field(
            select(
              jsonObjectAgg(
                score.TYPE.toString(), // HERE
                score.AMOUNT
              )
            )
              .from(score)
              .where(score.FOOD_CARD_ID.eq(foodCard.ID))
          )
        ),
``` 

I've got the below error from jsonObjectAgg, if I didn't put `.toString()`
```
None of the following functions can be called with the arguments supplied.
jsonObjectAgg(String!, Field<*>!) defined in org.jooq.impl.DSL
jsonObjectAgg(Field<String!>!, Field<*>!) defined in org.jooq.impl.DSL
```

### Steps to reproduce the problem

You can easily reproduce it by putting enum type as key in jsonObjectAgg.

### jOOQ Version

3.16.5

### Database product and version

Postgres 13

### Java Version

JDK 11

### OS Version

MacOS Monterey 12.3.1

### JDBC driver name and version (include name if unofficial driver)

42.3.3

**Comment by lukaseder** [comment]
Thanks for your feature request. We could indeed relax the type constraints on that function. Specifically, PostgreSQL doesn't seem very opinionated and declares the `any` type for both key and value of the function.

The SQL standard has a different opinion on this:

```
<JSON name> ::=
  <character value expression>
```

The idea that numerous types can be leniently converted to strings, but others cannot is a bit special and ad-hoc in PostgreSQL (as well as many other RDBMS). So, it's not obvious whether the RDBMS is right in auto-converting things to strings. Also, this isn't specific to `JSON_OBJECTAGG()`. If this particular aggregate function were changed, a lot more API would have to be changed as well, which is unlikely.

> jsonObjectAgg takes only `string` type as a key, so I need to call .toString() from enum type as below.

The correct workaround here is not to call `toString()` on the column expression, but `cast(SQLDataType.VARCHAR)`

**Comment by JayAhn2** [comment]
That's right! It should be casted to specific type, not toSting(). Sorry for the wrong description :)

**Comment by lukaseder** [comment]
I've given this a bit more thought. It is the same type of feature request like https://github.com/jOOQ/jOOQ/issues/13991.

There is only really one way to implement your suggestion: By removing type constraints on the function arguments, just like in PostgreSQL, native, turning the function into `jsonObjectAgg(Field<?>, Field<?>)` instead of `jsonObjectAgg(Field<String>, Field<?>)`. This can't be implemented only for `JSON_OBJECTAGG()` but would have to extend at least to all JSON functions (e.g. `JSON_OBJECT()`). And like #13991, it would give a precedent to extend this relaxation also everywhere else where other stringly types can be "reasonably" auto-converted to strings.

This would be useful in occasional cases (where you currently have to `cast()`, or even just `coerce()` or rawtype cast in Java), while removing value from 90% of all the cases, where users value jOOQ's type safety.

Some historic precedents include `CONCAT()`, which is lenient, and I believe this was a mistake. I don't intend to repeat it. The expected `T` type on the function argument is `String`, and if some other type can be auto-converted in some RDBMS, then it's simple to explicitly do that in jOOQ as well. But jOOQ cannot reasonably mimick all the auto-conversions of different RDBMS. For example, the `TIMESTAMP` to `VARCHAR` auto conversion differs in various dialects. Type safety helps make things more explicit.

I'll reject this feature request, just like #13991, establishing precedence for rejection of such type lenience, which I prefer not to creep into jOOQ here and there.

**Comment by JayAhn2** [comment]
@lukaseder Actually casting to String for key doesn't bother me a lot, but just wanted to check whether it is intended or needed to be improved :) Many thanks!

**Comment by lukaseder** [comment]
Makes sense. Thanks for the feedback!
