### ISSUE TITLE
Do I need Enterprise edition with MySQL?

### ISSUE THREAD

**Issue by mahdix** [jOOQ/jOOQ#14123]
### Your question

I get this error when trying to run a query:

```
org.jooq.exception.DataAccessException: SQL transformation Settings.transformInConditionSubqueryWithLimitToDerivedTable required. SQL transformations are a commercial only feature. Please consider upgrading to the jOOQ Professional Edition or jOOQ Enterprise Edition.
```

My DB is MySQL. I thought it is free to use with MySQL.

### jOOQ Version

Open Source 3.16.8

### Database product and version

MySQL 8

### Java Version

openjdk 16

### OS Version

Mac OS

**Comment by lukaseder** [comment]
Thanks a lot for your message. This SQL usage requires a commercial feature in jOOQ, namely transforming an `IN` subquery with `LIMIT` to an equivalent derived table: https://github.com/jOOQ/jOOQ/issues/8521

You don't have to use the commercial editions of jOOQ to work with MySQL, but some SQL transformations are available to the commercial editions only.

If an upgrade is not possible at this point, you can always re-write your query manually to something equivalent.

**Comment by lukaseder** [comment]
I've realised this transformation isn't listed in the manual page about SQL transformations yet:
https://www.jooq.org/doc/latest/manual/sql-building/queryparts/sql-transformation/

Will fix this soon:
https://github.com/jOOQ/jOOQ/issues/14125

**Comment by mahdix** [comment]
Thanks, @lukaseder . My assumption was that as long as I'm using MySQL I can use JooQ in an unlimited way for free (which is what is mentioned in Jooq homepage). It would be more transparent if you mentioned these types of limitations for your users so that they can make decisions with better understanding.

<img width="277" alt="image" src="https://user-images.githubusercontent.com/9294049/199716126-2408be03-6780-4103-8643-e4d8a7cfc24b.png">

**Comment by lukaseder** [comment]
The link "Open Source DB" includes a list of features included in the edition. I guess we could add a second link to the features section? Though, it's just an anchor to a section further down on the same page.

> My assumption was that as long as I'm using MySQL I can use JooQ in an unlimited way for free

I'm not sure what you mean by "unlimited way". There are many bugs and missing features, as well as features also available only to the commercial edition ("limitations").

But even so, you can work around any limitation for free very easily, without a problem.

Note, some time ago, we decided to advertise commercially available features also in the OSS edition, to help you decide when it's time to upgrade. If we hadn't advertised this feature, you'd have simply run into a syntax error, just like when you write this particular query in native MySQL.

> which is what is mentioned in Jooq homepage

The home page doesn't list any price plan information, did you mean the download / pricing page? https://www.jooq.org/download/

> It would be more transparent if you mentioned these types of limitations for your users so that they can make decisions with better understanding.

Well, all of the information you're requesting is on the very page you've made the screenshot on if you scroll further down.

Is there anything specific on that page that you think we could improve?

**Comment by mahdix** [comment]
You're right @lukaseder I did not notice the comparison table further down the download page.

Thanks for the clarification!

**Comment by lukaseder** [comment]
If you have some time, I'd like to learn a bit more about why perhaps this behaviour here has disappointed you?

> Note, some time ago, we decided to advertise commercially available features also in the OSS edition, to help you decide when it's time to upgrade. If we hadn't advertised this feature, you'd have simply run into a syntax error, just like when you write this particular query in native MySQL.

I'd really like to get this right, and better understand where jOOQ might have communicated wrongly, or why your expectations had been the way they were.

This isn't advertised across the entire website, but jOOQ has been trying to move more towards a model where commercial distributions offer power user features than strictly tying the license model to the underlying RDBMS. Some power user features include:

- Advanced SQL transformation
- Procedural language extensions
- Synthetic code generation artifacts
- Advanced embeddable types
- Spatial querying
- Advanced parser usage
- Support for old RDBMS versions

Sales indicate that this is starting to gain momentum (especially as the jOOQ Express Edition has been generating more revenue), though these features need more marketing to validate the alternative business model. Eventually, if the alternative works, perhaps, commercial RDBMS support can be offered for free again, which would greatly help adoption of jOOQ.

A current problem in terms of adoption is that leads have to go through the administrative hassles of sourcing software at their employer, which can take years (!). This isn't about pricing, but about bureaucracy. In that time, they're usually better off with some alternative, even if the alternative isn't as good as jOOQ. But they can't wait years for their bureaucrats to make a purchase, they need jOOQ now.

If there was a free (not necessarily open source) version that supported commercial RDBMS, so they could get started with their work, the lengthy sourcing process would be more bearable. But in order to risk doing this, jOOQ must generate new revenue elsewhere.

So, back to your case, would there have been a better way to communicate the *option* for you to upgrade to a commercial edition to profit from this SQL transformation feature?

**Comment by mahdix** [comment]
(A lot has changed in my code since the time I saw this error so can't remember exact details, but) The app could have shown a more descriptive error, for example including a link to the page that explains why do I need to pay for this even though I'm using an open-source DBMS which (at that time) I assumed JooQ could be used with it without buying a license.

I don't have lots of experience with the "bureaucracy" problem that you mentioned but it seems that it is the biggest challenge for increasing JOOQ's revenue. The question is "What can be done to shorten this time period?" (which I don't have answer for).

**Comment by lukaseder** [comment]
Thanks, @mahdix. That makes sense. I'll think of some landing page explaining the benefits, and alternatives to link to from that error message. Also to make it clear that this upgrade is entirely optional.

**Comment by lukaseder** [comment]
I've given this a bit more thought. In summary, it was a mistake to make this particular emulation part of the commercial only SQL transformation feature set. The commercial transformations are all quite sophisticated and are mainly used:

- To migrate between RDBMS
- To implement custom SQL transformations

This "transformation" here is just one out of many many emulations that jOOQ does. There's no reason why it should be different, e.g. from https://github.com/jOOQ/jOOQ/issues/6583, which has always been offered for free.

jOOQ could have made all of these emulations commercial from the beginning, and then, the expectations would have been clear. Going this direction would still be possible, but isn't a priority right now. As such, having a single transformation of this kind being commercial sets the wrong communicational tone, which is why I'll deprecate this flag and always enable the emulation on MySQL and MariaDB in all jOOQ editions, starting from jOOQ 3.18: https://github.com/jOOQ/jOOQ/issues/14634
