### ISSUE TITLE
multiset with asterisk loses type safety

### ISSUE THREAD

**Issue by NikolayMetchev** [jOOQ/jOOQ#14173]
### Your question

I have a one to many relationship Message -> Attachments
If I use fetchGroups I have type safety 
```
            val result: MutableMap<MessageViewRecord, Result<AttachmentRecord>> = context.select()
                .from(MESSAGE_VIEW)
                .leftJoin(ATTACHMENT)
                .on(MESSAGE_VIEW.ID.eq(ATTACHMENT.MESSAGE_ID))
                .fetchGroups(MESSAGE_VIEW, ATTACHMENT)
```

However not all messages have attachments so fetchGroups is not leftJoin aware. I found an article saying I should be using multiset but with multiset I lose all the type safety and I don't know how to get the list of attachments out of the Result
```
            val result: Result<Record> = tx.context.select(
                MESSAGE_VIEW.asterisk(),
                multiset(
                    selectFrom(ATTACHMENT)
                        .where(ATTACHMENT.MESSAGE_ID.eq(MESSAGE_VIEW.ID))
                ).`as`("attachments")
            ).fetch()

      // how to convert the result above to a MessageViewRecord and a Result<AttachmentRecord> like I have with fetchGroups() ?

```

### jOOQ Version

3.17.4

### Database product and version

postgres 13.4

### Java Version

17

### OS Version

linux/mac

### JDBC driver name and version (include name if unofficial driver)

postgres 42.4.1

**Comment by lukaseder** [comment]
Thanks for your message.

The point of `DSL.asterisk()` and `Table.asterisk()` is to really generate that asterisk in generated SQL. It is rarely really useful, especially because jOOQ will not have any type information available, by design.

What you want to do is to just project the `TableRecord` itself. Starting from jOOQ 3.17, a `Table<R>` is a `SelectField<R>`: https://www.jooq.org/doc/latest/manual/sql-building/table-expressions/tables-as-selectfield/

So, just write:

```kotlin
val result: Result<Record2<MessageViewRecord, Result<AttachmentRecord>>> = tx.context.select(
	MESSAGE_VIEW,
	multiset(
		selectFrom(ATTACHMENT)
			.where(ATTACHMENT.MESSAGE_ID.eq(MESSAGE_VIEW.ID))
	).`as`("attachments")
).fetch()
```

Alternatively, map the nested record types to whatever data class you have available for this query, if applicable.

**Comment by lukaseder** [comment]
Btw, I recommend upgrading to 3.17.5, as there had been a few bug fixes in this area, recently.

**Comment by NikolayMetchev** [comment]
Thank you very much. That has worked.
