### ISSUE TITLE
MANIFEST.MF contains io.r2dbc.spi dependency that might be optional

### ISSUE THREAD

**Issue by ffays** [jOOQ/jOOQ#14189]
### Use case

Reducing the number of mandatory packages that are not needed for a basic use of jOOQ.
For instance, the io.r2dbc.spi package has been added as a required package whereas I believe it can be optional.

### Possible solution

Either one of these two possibilities:
1. Make io.r2dbc.spi package optional
2. Move classes that uses io.r2dbc.spi package in a side library and remove io.r2dbc.spi package requirement as a whole

### Possible workarounds

Make io.r2dbc.spi package optional

### jOOQ Version

jOOQ Express 3.17.5

### Database product and version

No relevant

### Java Version

Java 11

### OS Version

All

### JDBC driver name and version (include name if unofficial driver)

No relevant

**Comment by lukaseder** [comment]
Thanks for your suggestion. I don't think that's an optional dependency? Its types are referenced from `DSL` and `DSLContext` methods.

What problem would this be solving? At what price for everyone who wants to use this package (or considering the trouble upgrading to the version that no longer has the dependency)?

Closing this because:

> * Make io.r2dbc.spi package optional

I don't think this is feasible

> * Move classes that uses io.r2dbc.spi package in a side library and remove io.r2dbc.spi package requirement as a whole

That has been considered at the time R2DBC support was implemented, and rejected.
