### ISSUE TITLE
Backwards incompatibility: in new version, field.cast(String.class) in a query with MYSQL dialect results in casting to char

### ISSUE THREAD

**Issue by oxygenecore** [jOOQ/jOOQ#14446]
### Expected behavior

`field.cast(String.class)` used to render as `cast(field as varchar)` in versions 3.12-3.13.

### Actual behavior

`field.cast(String.class)` is now being rendered as `cast(field as char)` in 3.16.10

### Steps to reproduce the problem

```java
System.out.println(DSL.using("jdbc:h2:mem:ginmon;MODE=MySQL;DB_CLOSE_DELAY=-1;TRACE_LEVEL_FILE=0", MYSQL)
.selectFrom(TABLE1.FIELD1.cast(String.class)).getSQL(ParamType.INLINED));

// this prints out:
//     select cast(`schema`.`table1`.`field1` as char)
```

### jOOQ Version

3.16.10

### Database product and version

H2 2.1.214 in MySQL compatibility mode

### Java Version

openjdk version "11.0.17" 2022-10-18 LTS

### OS Version

macOS 12.6

### JDBC driver name and version (include name if unofficial driver)

com.h2database:h2:2.1.214

**Comment by lukaseder** [comment]
Thanks for your report.

The syntax is correct in MySQL, see: https://dev.mysql.com/doc/refman/8.0/en/cast-functions.html#function_cast. MySQL's data types differ from the cast types. You can try this:

```sql
select cast('a' as varchar(1))
```

It produces:

> SQL Error [1064] [42000]: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'varchar(1))

The problem is that you're using H2 in some non standard mode, which jOOQ doesn't support. If you're using jOOQ, you don't need to put H2 in any MySQL mode. Use H2 in H2 mode and use jOOQ's `SQLDialect.H2`.

Some insights here:
https://blog.jooq.org/using-h2-as-a-test-database-product/

In any case, I think you're probably going to be better off using MySQL directly for your tests, e.g. using Testcontainers. There are only benefits. See also:
https://blog.jooq.org/using-testcontainers-to-generate-jooq-code/

**Comment by oxygenecore** [comment]
For those having similar problem - in my case I was able to resolve the issue by downgrading h2 to version 1.4.200. I guess, version 2 is too backwards incompatible (maybe devs dropped the idea of supporting different DB modes?).

**Comment by lukaseder** [comment]
> in my case I was able to resolve the issue by downgrading h2 to version 1.4.200

I don't think you're choosing the right path here. That's a hack and you will run into other problems. I highly recommend you follow my suggestion above, choosing among:

1. Using H2 with jOOQ's `SQLDialect.H2`
2. Using MySQL only

I have had this kind of support case dozens of times, to the extent of writing an entire blog post to prevent it from appearing again. **jOOQ does not support MySQL's run modes**!

**Comment by oxygenecore** [comment]
Yes, I also expect that my comment about downgrading h2 might not be used as a permanent solution. In my case, I'm just unblocking a build, and then I'm going to decide what to do next :)
