### ISSUE TITLE
Add parser support for bitemporal table queries with system_time and business_time

### ISSUE THREAD

**Issue by mrclth** [jOOQ/jOOQ#14481]
### Use case

In DB2 it is possible to query bitemporal data. A query with system_time and business_time is currently not supported by the JOOQ-Parser.

A simplified query with a WITH-clause could be as follows:
```
WITH cte(col1) as (
SELECT col1 
FROM myBitemporalTable 
FOR system_time as of '0001-01-01 00:00:00' 
FOR business_time as of date('0001-01-01 00:00:00')) 
SELECT * 
FROM cte;
```

The result is: 
`org.jooq.impl.ParserException: Token ')' expected: [1:103] ...e for system_time as of '0001-01-01 00:00:00' for [*]business_time as of date('0001-01-01 00:00:00')) select * from cte`

Or in case without the WITH-Clause the result ist:
`org.jooq.impl.ParserException: Unexpected clause: [1:84] ...e for system_time as of '0001-01-01 00:00:00' for [*]business_time as of date('0001-01-01 00:00:00')`

The parser can parse the queries (with and without the WITH-Clause) if there is only the system_time or the business_time but can not parse the query if there are both of them.

### jOOQ Version

3.17.6

### Database product and version

DB2 v10.5.0.7

### Java Version

11

**Comment by lukaseder** [comment]
Thanks for your report. Indeed, we currently parse only mutually exclusive temporal attributes.

Curious, what will you use the parsed SQL for? Only few other dialects support bitemporal tables, so it's unlikely we can translate the SQL to some other dialect.

**Comment by mrclth** [comment]
Thanks for your fast reply. 

We want to parse custom SQL written by our customer. The usecase is pretty similar to the example in the "Querying bitemporal data" documentation of DB2 (https://www.ibm.com/docs/en/db2/11.5?topic=bt-querying). The history table will only be queried if the FOR SYSTEM_TIME is also specified.

**Comment by lukaseder** [comment]
It turns out this is simply a missing parser feature. The parser can only accept a single `FOR` clause. The `DSL` API can support multiple of these clauses.

The current implementation of the `QOM` API wraps the table reference twice, once per `FOR` clause in lexical order. This may still be changed once the `QOM.PeriodTable` is implemented, see https://github.com/jOOQ/jOOQ/issues/13640. It's probably worth listing all the period specifications in a single place, rather than wrapping them twice.

Also, unlike Db2, we currently don't strictly distinguish period specifications by whether they should model the `SYSTEM_TIME` or `BUSINESS_TIME`, as other RDBMS support naming these periods explicitly. Without access to meta data, the parser wouldn't know which period is which.

I've implemented parser support for the upcoming jOOQ 3.18.0. Let me know if you need anything else in this area.

**Comment by lukaseder** [comment]
(The parser on the website at https://www.jooq.org/translate will be updated soon)

**Comment by lukaseder** [comment]
The 3.18.0-SNAPSHOT version on https://www.jooq.org/translate/ has been updated and can now parse your query.

**Comment by mrclth** [comment]
Thank you for your work on this. I'll give it a try.
