### ISSUE TITLE
Generate POJOs with Default Values

### ISSUE THREAD

**Issue by cemo** [jOOQ/jOOQ#14527]
### Use case

We are using jOOQ codegen to generate entities from database. Database schema sometimes includes sensible defaults such as true or false for boolean fields or sensible default numbers. 

### Possible solution

Can we refactor this part to another another method with relaxed scoped? 

https://github.com/jOOQ/jOOQ/blob/43be53b427d12b88a56e8925d4c276757d8a4ac2/jOOQ-codegen/src/main/java/org/jooq/codegen/JavaGenerator.java#L5170-L5175

### Possible workarounds

Copying class.

### jOOQ Version

3.17.7

### Database product and version

PostgreSQL

### Java Version

19

**Comment by lukaseder** [comment]
Thanks for your suggestion.

If I'm understanding you correctly, you're trying to map:

```sql
CREATE TABLE t (
  c INT DEFAULT 1
);
```

To a POJO of this kind:

```java
class T {
    Integer c = 1;
}
```

This request is based on the wrong assumptions that:

1. SQL defaults are constants
2. SQL defaults can (or should) be evaluated in the client prior to inserting / updating / etc a value in the database

The SQL `DEFAULT` semantics is:

- Apply the expression implicitly, when it an explicit column reference is missing in an `INSERT` statement
- Apply the expression explicitly, when `DEFAULT` or `DEFAULT VALUES` is used with `INSERT`, `UPDATE`, `MERGE`

Specifically, the `UPDATE` or `MERGE` cases have nothing to do with individual records or client side POJOs, there's simply no way jOOQ could predict what will happen on the server side.

Note that similar requests have been made in the past related to constraints (including `CHECK` constraints), which can't be evaluated by jOOQ in the client as the server context is missing.

**Comment by cemo** [comment]
@lukaseder thanks for great introduction especially regarding `check` part.

Most of the SQL default values are including static constants or `now()` at worst. If the entities are already generated by database schema, I see no problem having same value. 

We use a few framework which are generating insert queries by analyzing bean properties. When we need to persist an entity, we already set a value which is already same value of SQL database constant value. Almost all frameworks generating auto insert queries with all fields by default. For example In your example we already need to set c with some value. If I want to set a default value for not set fields, It sets as NULL in query. So there is not easy way to skip not set values to filled by SQL. This problem can not be solved easily because there is an ambiguity between skipping field in generated query or setting null in query. One can want to set NULL a field. 

Shortly we need to set a value. Automatically setting a value from database sounds not bad for me. 

Would you accept a PR relaxing that method and refactoring that part?

**Comment by lukaseder** [comment]
> Most of the SQL default values are including static constants or `now()` at worst.

That is a bold assumption, and the ensuing feature request is a bold conclusion! :)

But jOOQ does not have this luxury. jOOQ must accommodate every weird edge case there ever existed. Users who run into these edge cases often do so inadvertently, because they notice (or don't notice) very subtle bugs. If `now()` is to be interpreted in the client, it will produce the client timestamp (at what time? The POJO creation time? The POJO to `Record` / `Query` mapping time? The transaction start time?), not the server timestamp. There are many things that can go wrong. How would this new default interact with many many other features in jOOQ? The feature matrix is big, and every one of these features is a big risk for existing interactions, as well as future interactions.

In short, a user deciding to implement a workaround for a specific issue is never the same as a library/framework implementing that workaround as a feature. You can do that, being able to assess your own risks. For jOOQ, such features are usually red flags.

> If I want to set a default value for not set fields, It sets as NULL in query. So there is not easy way to skip not set values to filled by SQL.

You can omit the field or set it to SQL `DEFAULT` (jOOQ `DSL.default_()`). I think that's much more robust than anything done in the client. If you're using `UpdatableRecord`, you can reset the field / changed flag prior to `store()`, `insert()`, `update()`, etc. in order to exclude it from the ensuing DML statement.

You don't *have to* use the POJO type. Why not just use the `UpdatableRecord` instead, which can encode the difference between explicit `NULL` (`null` value and `changed = true`) and implicit `DEFAULT` (`null` value and `changed = false`).

Alternatively, if you *need* a POJO type that is independent of jOOQ for architecture reasons, then you can override the `JavaGenerator` and generate your own, which reimplements support for being defaulted. This is a bit of work, but again, it's much simpler for you to do, tailoring things *exactly* to your requirements, rather than changing jOOQ, in case of which 100s of feature interactions need to be considered.

> Would you accept a PR relaxing that method and refactoring that part?

Unlikely.

Such an isolated refactoring, turning very specific internals into public API doesn't sound like a good, robust idea. As a general rule of thumb, the answer to "Can we open up this internal API" is almost always "no". In most cases, it's a clear sign of https://xyproblem.info, there's usually a better way.

We won't be able to change things again in the future, when other features / feature interactions touch on this topic. Also, how would this affect kotlin/scala generation? When should default values be initialised in a POJO? Etc. etc.

## Alternative

The one thing that could be done is encode a property's `DEFAULT` capability in the POJO, i.e.

```sql
CREATE TABLE t (
  c INT DEFAULT 1
);
```

To produce

```java
public class T {
    private Integer c;
    private boolean cIsSet;

    public void setC(Integer c) {
        this.c = c;
        this.cIsSet = true;
    }

    // [...]
}
```

And now, the POJO could communicate to the `UpdatableRecord` if `c == null` means explicit `NULL` or implicit `DEFAULT`. But that's a lot of complicated logic to be implemented in a simple POJO, when in fact, all that logic is already present in the `UpdatableRecord`. If you used the generated `UpdatableRecord` as a data structure, instead of the POJO, I suspect this entire problem would go away?
