### ISSUE TITLE
Add <generatedAnnotationJooqVersion/> option to the code generator

### ISSUE THREAD

**Issue by apatrida** [jOOQ/jOOQ#14534]
### Use case

In order to keep our git history more accurate, yet still retain the idea of `@Generated` code, it would be useful for JOOQ to NOT include its version number in the `@Generated` annotation.

The docs say this must include the fully qualified classname of the generator, and I don't care much about that.  But whatever is there, we need the value to be stable over JOQO versions unless something in the generated code actually changes, then we'll see that in a diff anyways.

So this:

```
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.17.5"
    },
    comments = "This class is generated by jOOQ"
)
```

is a problem, and there should be a generator setting similar to `isGeneratedAnnotationDate` for whether to include this version in the values.

We can exclude date, probably for this very reason, but why not the version?

### Possible solution

`isGeneratedAnnotationJooqVersion` setting

### jOOQ Version

3.17.x

### Database product and version

all

**Comment by lukaseder** [comment]
Thanks for your suggestion. This feature will soon have about 30 flags configuring it 😅 As such a configuration leads to even more tests and possible bugs (in Java, Scala, Kotlin generation), I wonder if we can just remove the information.

After all, jOOQ version generation was implemented in a better way with #12601. Only the minor version is really useful for this purpose, not the patch version. And it doesn't need to be generated on every class, only at a single location (#12601 generates it on the catalog, and it's indeed configurable).

The date was made configurable with https://github.com/jOOQ/jOOQ/issues/10090. It is not the same as the version. The version is relevant in order to assess compatibility of generated code with the runtime library (see above #12601). And it doesn't change as frequently as the date.

But then again, if this stuff bothers users, then why even generate that annotation? What value is there left in it?

> The docs say this must include the fully qualified classname of the generator, and I don't care much about that.

Yeah, that's quite a random requirement. As if a generator is always a single class.

**Comment by apatrida** [comment]
There is value in the annotation as we can trigger other processing off of the classes by having its presence.  But, having the annotation contents change on point versions of JOOQ causes 1000+ files to change when nothing was really affected.

I guess we (us personally) keep `@Generated` as there is not an option for "Add custom X annotation to table", "Add custom Y annotation to record", etc.

**Comment by lukaseder** [comment]
> I guess we (us personally) keep `@Generated` as there is not an option for "Add custom X annotation to table", "Add custom Y annotation to record", etc.

There's the `generateRecordClassJavadoc` extension point, etc.? After calling `super.generateRecordClassJavadoc()`, you can add annotations. I mean, it doesn't feel 100% right, but it also doesn't feel 100% wrong.

**Comment by apatrida** [comment]
I'll check it out, thanks.

**Comment by lukaseder** [comment]
Revisiting this. So, we could justify a change by adhereing to the specification of the annotation

> The value element MUST have the name of the code generator. Thename is the fully qualified name of the code generator.

So, we'll simply generate `value = "org.jooq.codegen.JavaGenerator"` (or `KotlinGenerator`, `ScalaGenerator`, or whatever the generator is, if it's a user-defined one)

That implicitly also removes the version number and makes the generated information more stable.

I don't want to make this configurable as that's too much effort for little value. The little value being that the current information isn't really all that useful.

Given that some folks may rely on the status quo nevertheless, I won't backport this change.

**Comment by lukaseder** [comment]
Hah, oh no. The `SchemaVersionProvider` functionality relies on schema version information being present on that annotation:
https://www.jooq.org/doc/latest/manual/code-generation/codegen-advanced/codegen-config-database/codegen-database-version-providers/

OK, so let's just make it configurable...
