### ISSUE TITLE
Code generator generating wrong order from PostgreSQL

### ISSUE THREAD

**Issue by JWThewes** [jOOQ/jOOQ#14719]
### Expected behavior

I've generated code from an existing PostgreSQL table (psql version 13.3).
When doing a select using the generated Record class I got the error that String can not be casted to Boolean.
After debugging I found that the select statement is generating the wrong ordering of fields.
In my case the query looked like this:

```sql
select 
  "public"."abc"."admin", 
  "public"."abc"."username", 
  "public"."abc"."firstname", 
  "public"."abc"."lastname", 
  "public"."abc"."password" 
from "public"."abc" 
where "public"."abc"."username" = 'admin'
```

This is wrong because "public"."abc"."admin" is the field with index 4 in the Record class (

```java
public final TableField<AbcRecord, Boolean> ADMIN = createField(DSL.name("admin"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field("false", SQLDataType.BOOLEAN)), this, "");
```

I noticed that admin was the first field in the class extending TableImpl. After changing the order of fields and moving the admin field to the end my problem was resolved.

### Actual behavior

Currently the code generator is messing up the order of fields in the Class extending TableImpl.

### Steps to reproduce the problem

For me it is as simple as invoking the jOOQ code generator.

### jOOQ Version

jOOQ 3.17.7

### Database product and version

PostgreSQL 13.3

### Java Version

corretto-17.0.6

### OS Version

macOS 13.2.1

### JDBC driver name and version (include name if unofficial driver)

org.postgresql:postgresql:42.5.1

**Comment by lukaseder** [comment]
Thanks a lot for your report. I'm not aware of such a problem. It would be *very* significant if it was caused by a bug in jOOQ, so we'd have noticed, unless there's something really subtle going on.

May I ask you to provide a complete reproducer for the problem? We have a template that simplifies setting up an environment in PostgreSQL using testcontainers here: https://github.com/jOOQ/jOOQ-mcve

If that takes too much time, I'll still have to be able to reproduce this, so I'd need:

- `CREATE TABLE` definition
- Generation configuration
- The jOOQ code you ran to produce this query

**Comment by JWThewes** [comment]
Is there a possibility to share files privately with you? If yes I can share my Flyway SQL files. My Docker Run config for IntelliJ , the generator config for Maven and of course the code I used to create the query.

**Comment by lukaseder** [comment]
I'm only really interested in this particular table that helps reproduce the problem. You can anonymise the columns if that's significant. However, keep in mind, if the problem cannot be reproduced on my end, then the files won't be really helpful...

**Comment by lukaseder** [comment]
I couldn't reproduce the issue at the time. Will be happy to look into any specific examples reproducing the problem.
