### ISSUE TITLE
field.getConverter() returns the configured converter

### ISSUE THREAD

**Issue by brettkail-wk** [jOOQ/jOOQ#14804]
### Use case

We have introspection logic that iterates our models and classifies fields based on `instanceof CustomConverter`.  That stopped working prior to 3.18.0 because `field.getConverter()` returns `AbstractContextConverter$1` due to #13961.

### Possible solution

Restore the previous behavior of storing the configured converter, and adjust internal jOOQ callers to handle plain `Converter` or `ContextConverter` as needed.

Alternatively, add a default `unwrap` method to `ContextConverter` and implement it in relevant wrappers so that callers can retrieve their underlying converter.

### Possible workarounds

We worked around the issue by directly implementing `ContextConverter`.  That is working fine for us, but it might not work for others.  I'm primarily opening this issue to raise awareness so that an unconditional wrapper isn't added in a future version that we can't workaround.

### jOOQ Version

jOOQ Open Source Edition 3.18.0

### Database product and version

N/A

**Comment by lukaseder** [comment]
Thanks for your report.

A `Field.getConverter()` has never really been guaranteed to be the exact instance that was provided at field construction time. For example, when you combine converters and bindings, they can be chained. Alternatively, you can chain converters yourself, explicitly, or implicitly by calling `Field.convertFrom()` multiple times.

So, even if there has been a change in behaviour indeed, I doubt that it is something that needs to be addressed, because it wasn't documented to work this way, nor should it be expected to. Of course, I understand how this can be a problem for your diagnostics now, so let's try to see what options we have / you have:

> Restore the previous behavior of storing the configured converter, and adjust internal jOOQ callers to handle plain `Converter` or `ContextConverter` as needed.

I don't think this will be possible. The change was complex and there were good reasons to store the wrapping `ContextConverter` eagerly. We shouldn't introduce a new accessor method for internal purposes only, differing from the existing one.

> Alternatively, add a default `unwrap` method to `ContextConverter` and implement it in relevant wrappers so that callers can retrieve their underlying converter.

But what does `unwrap` mean when the converter is chained? This sounds like a quick fix for your immediate problem, but it also raises many new questions about the design and possible intentions for wrapping converters.

> We worked around the issue by directly implementing `ContextConverter`. That is working fine for us, but it might not work for others.

Yes, it works now, because you looked at the implementation and saw that the implementation doesn't re-wrap an existing `ContextConverter`. But there's no guarantee for these things. The main thing a `Converter` must guarantee is that its 4 methods keep behaving the same way, as expected. It doesn't necessarily have an identity that it can expose elsewhere.

So, rather than discussing potential solutions, let's go back at discussing why you're doing this introspection in the first place, and how you could possibly change that, without relying on the type or identity of a `Converter` instance.

**Comment by brettkail-wk** [comment]
First, thank you for the discussion and exploring the options (and for jOOQ itself).  I had no expectation when opening the issue that a change would be made just to solve our niche problem, but I thought it was worth opening in case there was a straightforward fix or in case someone else encountered a similar problem.

> > Restore the previous behavior
>
> I don't think this will be possible.

Ok.

> But what does `unwrap` mean when the converter is chained?

I imagined it could recursively unwrap like [`Wrapper.unwrap(Class)`](https://docs.oracle.com/en/java/javase/17/docs/api/java.sql/java/sql/Wrapper.html#unwrap(java.lang.Class)).

> So, rather than discussing potential solutions, let's go back at discussing why you're doing this introspection in the first place, and how you could possibly change that, without relying on the type or identity of a Converter instance.

Sure, the issue template asked for solutions, so I gave the ideas that came to mind :-).

The primary use case is an `EnumConverter` interface that maps enumerations to integers.  We integrate with a diagnostic API where we describe our "diagnostic models" (effectively tables with columns but not restricted to SQL).  For convenience, we use jOOQ models to populate the diagnostic models and convert jOOQ records to diagnostic result rows, and overall this works well.  The diagnostic fields can have an enum mapping of integer values to labels, which allows a dropdown when filtering in the diagnostic UI, and we use `instanceof EnumConverter` to populate that mapping.

If the `instanceof` stops working some day, we could either maintain our own mapping of field to converter, or we could use `field.getType().getEnumConstants()` and the converter opaquely, which would handle nearly all use cases (and we could maintain a smaller mapping for any special cases).

**Comment by lukaseder** [comment]
> or in case someone else encountered a similar problem.

Yeah, that's always great! Perhaps, to increase visibility, you could also document the change and your workaround on Stack Overflow? https://stackoverflow.com/questions/tagged/jooq

Answering one's own question is explicitly encouraged:
https://stackoverflow.blog/2011/07/01/its-ok-to-ask-and-answer-your-own-questions

> > But what does `unwrap` mean when the converter is chained?
> 
> I imagined it could recursively unwrap like [`Wrapper.unwrap(Class)`](https://docs.oracle.com/en/java/javase/17/docs/api/java.sql/java/sql/Wrapper.html#unwrap(java.lang.Class)).

A `ChainedConverter` contains `N` wrapped converters. Which one to return?

> Sure, the issue template asked for solutions, so I gave the ideas that came to mind :-).

Ah, I see, you're right :) Thanks for the description. Interesting, does the `Converter` provide more information about the specific conversion than the `U` type itself (`Converter::toClass`)? While the converter can be wrapped, the `Class<U>` reference will remain the same. Perhaps that works better?

In any case, I'll close this issue as won't fix. I don't think it will be practical to depend on a specific `Converter` type

**Comment by brettkail-wk** [comment]
> A `ChainedConverter` contains N wrapped converters. Which one to return?

I am not familiar enough with jOOQ, but I think you're suggesting there is no correct answer, so that idea does not work.

> does the `Converter` provide more information about the specific conversion than the `U` type itself (`Converter::toClass`)

`field.getConverter().toType()` seems an indirection for `field.getType()`, so as I was saying, I think `field.getType().getEnumConstants()` would cover most use cases.  For cases where the converter wanted to do something special, we can just duplicate that metadata in the diagnostic mapper.

Thanks again.

**Comment by lukaseder** [comment]
> > A `ChainedConverter` contains N wrapped converters. Which one to return?
> 
> I am not familiar enough with jOOQ, but I think you're suggesting there is no correct answer, so that idea does not work.

Yes :)
