### ISSUE TITLE
Patch release notes not listed on release notes page?

### ISSUE THREAD

**Issue by ardc-shorn** [jOOQ/jOOQ#14809]
### Your question

Our project is currently using `3.17.5`.

When doing a lib version upgrade, it's important to me to browse through the release notes for intervening versions.
But currently https://www.jooq.org/notes seems to show only "minor" releases (i.e `.0` releases like `3.17.0`, `3.18.0`).  I could swear patch releases used to be documented on this page too?

If this is intentional, where do we go to find release notes for patch versions?

### jOOQ Version

3.17.x

### Database product and version

Postgres

**Comment by lukaseder** [comment]
Thanks for your message. The 3.17 release notes can be accessed like this:
https://www.jooq.org/notes/?version=3.17

The link is available from here:
https://www.jooq.org/learn/

![image](https://user-images.githubusercontent.com/734593/225841893-78599150-2032-47ad-8957-60c39c94dbea.png)

All the patch release bug fixes are available also in the latest minor release, which is why they're not listed redundantly again, currently. Tough, there's an issue somewhere to improve this in a more hierarchical way, with collapsed details for each minor release.
