### ISSUE TITLE
After I  import jooq in springboot3, when the springboot run Application main,Project opening speed will be much slower.

### ISSUE THREAD

**Issue by sundayYa** [jOOQ/jOOQ#14880]
### Your question

After I  import jooq in springboot3, when the springboot run Application main,Project opening speed will be much slower.

### jOOQ Version

OSS edition 3.17.2

### Database product and version

mysql8.0.12

### Java Version

17

### OS Version

windows11

### JDBC driver name and version (include name if unofficial driver)

mysql-connector-java:8.0.31

**Comment by lukaseder** [comment]
Thank you very much for your message.

With the information you've given, I can't really be of much help. You say "project opening speed". Does this mean the IDE is slow, or your application starts slowly? In either case, you could profile whatever is being slow and take action based on your profiling results. For example VisualVM is a simple and free profiler to get a first impression of what's taking so much time: https://visualvm.github.io

If you notice something clearly related to jOOQ, I'll be happy to investigate. If it's the IDE or Spring Boot doing too much work, you can either work around whatever the problem is, or report to them.

I hope this helps
