### ISSUE TITLE
Possible performance degradation after updating to 3.17.10

### ISSUE THREAD

**Issue by dimi-nk** [jOOQ/jOOQ#14935]
### Your question

I have yet to find a good way to debug this, and I couldn't find any similar issue listed here, so here goes:

I just updated our project from Spring Boot 2.7.7 to 3.0.5. It's a major change and brings many dependency updates, as expected. After the update, we noticed increased latency on our service and had to roll back the update. For reference:

![image](https://user-images.githubusercontent.com/2273840/231820970-c894c918-c934-4d34-9346-d1fa72001dc1.png)

The vertical dotted green lines are deployments. The first is the update, and the last is the rollback. However, I also noticed the following graph, which is the connection usage data from HikariCP (v5.0.1 after the update). We don't have any jOOQ-specific metrics in place:

![image](https://user-images.githubusercontent.com/2273840/231821324-4a19946d-04c4-45c1-bcfb-23bbb35bec8d.png)

I checked against GCP CloudSQL's insights, and the queries performed roughly the same during that period.

Grafana mean:
![image](https://user-images.githubusercontent.com/2273840/231824465-45ad2918-7726-482f-8f1d-c1fbdc4bfa21.png)

CloudSQL p99:
![image](https://user-images.githubusercontent.com/2273840/231826809-6d795361-f5bd-48d9-8d8f-54c5fe5e424d.png)

I am unsure, but either HikariCP or jOOQ might be causing the extra latency. You've also "reduced" support in v3.17.10 for PostgreSQL 11, so you may have removed some version-specific optimisations, i.e.

```
2023-04-13T17:20:57.465+01:00  WARN 3756 --- [           main] o.j.i.D.logVersionSupport                : Version mismatch         : Database version is older than what dialect POSTGRES supports: 11.17. Consider https://www.jooq.org/download/support-matrix to see what jOOQ version and edition supports which RDBMS versions.
```

I checked Hikari's release notes, but there weren't many changes between the two versions. I am just hoping you might have a clue what the reason might be. As always, I'm thankful for your time and assistance 🙏🏼 

### jOOQ Version

3.17.10

### Database product and version

PostgreSQL 11.17 managed by GCP CloudSQL

### Java Version

openjdk version "17.0.6" 2023-01-17 LTS (Corretto)

### OS Version

MacOS 13.3.1 (22E261)

### JDBC driver name and version (include name if unofficial driver)

org.postgresql.:postgresql:42.5.4

**Comment by lukaseder** [comment]
Thanks for your report.

It's a bit high level so it's hard to say if jOOQ has anything to do with it or not. There was this: https://github.com/jOOQ/jOOQ/issues/14721 but it has been patched to 3.17.9, so that shouldn't cause the most problems anymore in your attempts. Can you drill down into the difference and profile things? Perhaps there's a single bottleneck similar to https://github.com/jOOQ/jOOQ/issues/14721, which could cause most of the additional overhead.

> You've also "reduced" support in v3.17.10 for PostgreSQL 11, so you may have removed some version-specific optimisations, i.e.

jOOQ doesn't do any such "optimisations" on your behalf, that is unlikely to work out well in most cases, as SQL tuning is never simple.

The version support is mostly based on syntax usage. E.g.

- New syntax is used rather than old one, in case it is now available. E.g. `MERGE` can be used in some cases instead of `ON CONFLICT`, starting from jOOQ 3.18 and PostgreSQL 15 support. But that mostly affects functionality, not performance
- New `INFORMATION_SCHEMA` tables and columns can be used by the code generator, which means the code generation queries may stop working on older instances. We try to catch errors in this area to prevent too many regressions, but it's something to look out for.
- Finally, the log message itself has been added to make users aware of potential problems related to version support.

In any case, you haven't noticed any difference in SQL performance, so the problem (if it's jOOQ related) is most likely caused by mapping code, and a bit less likely by SQL rendering code.

**Comment by lukaseder** [comment]
> Our production service is too convoluted to run anything meaningful and compare jOOQ versions.

A comparison might not be necessary if there's something obvious that's being done that hasn't been done before. It's probably related to https://github.com/jOOQ/jOOQ/issues/14721. If there's something obvious, it would appear in most profiling sessions.

**Comment by lukaseder** [comment]
For the record, the root cause for #14721 was https://github.com/jOOQ/jOOQ/issues/12023. That should not have caused a regression on its own, but https://github.com/jOOQ/jOOQ/issues/11682 exposed it. If you can find traces of `JSONB::equals`, `JSONB::hashCode`, or `JSONB::toString` calls in a profiling session, then it would be helpful to get popular call stacks.

**Comment by dimi-nk** [comment]
It turns out it was JSONB, but it was in our codebase. I've implemented a `Binding<JSONB, JsonNode>` and I was using the following code to convert to jackson's `JsonNode`:

```java
mapper.readValue(t.toString(), JsonNode.class)
```

I've changed it to the following, and the profiling shows that part is not a hotspot anymore.

```java
mapper.readValue(t.data(), JsonNode.class)
```

Thanks for the insights. I'll change the title of the issue in case it helps others too.

**Comment by lukaseder** [comment]
Thanks for the hint. Yeah, that's subtle. It could have been even more subtle, e.g. `"" + t`.

Maybe, it's worth adding Javadoc hints about #12023 to `JSONB::equals`, `JSONB::hashCode`, and `JSONB::toString`: 

- https://github.com/jOOQ/jOOQ/issues/14953

In addition to this, it's worth investigating if there's a faster normalisation algorithm. We don't *have to* parse everything into `ArrayList` and `HashMap` representations:

- https://github.com/jOOQ/jOOQ/issues/14954

**Comment by lukaseder** [comment]
> I'll change the title of the issue in case it helps others too.

If you have some time, a great approach to make such issues more visible to others is to ask and answer a question on Stack Overflow:
https://stackoverflow.com/questions/tagged/jooq

Answering one's own question is explicitly encouraged for this reason:
https://stackoverflow.blog/2011/07/01/its-ok-to-ask-and-answer-your-own-questions/
