### ISSUE TITLE
SQL Translation Error

### ISSUE THREAD

**Issue by liulei056** [jOOQ/jOOQ#14976]
### SQL translator incorrectly translates this query:

```sql
update t_user a,t_class b set a.uname = b.c_name where a.id = b.user_id

**Comment by lukaseder** [comment]
Thanks a lot for your report. We currently don't support multi table updates or deletes. I've created a feature request for this:

- https://github.com/jOOQ/jOOQ/issues/14977

Closing this as a duplicate, because it isn't strictly about the translator.

Note, even if we support parsing this syntax for MySQL, it will be hard to translate to other RDBMS in the case where multiple tables are updated. In your case, only `t_user` is being updated, so it should be possible to emulate this in other dialects.
