### ISSUE TITLE
formatJSON() convert value from column with type text[] into string instead of array of string

### ISSUE THREAD

**Issue by DangVuMinhHieu** [jOOQ/jOOQ#15155]
### Your question

Hi team,
I have a table in postgresql with following structure
```
CREATE TABLE books (
    id int,
    name text,
    tags text[]
);
```
Example of records in this table

| id |  name  |        tags       |
|:--:|:------:|:-----------------:|
| 1  | BOOK_A | {Honor, Triller} |
| 2  | BOOK_B | {Comedy}          |

I tried to use formatJSON() to get a JSON format result
```
String json = result.formatJSON(new JSONFormat().header(false))
```

I expect to have a result that looks something like this
```json

    "records": [
        [
            1,
            "BOOK_A",
            ["Honnor, Thriller"]
        ],
        [
            2,
            "BOOK_B",
            ["Comedy"]
        ],
     ]
```

But the result returns in
```json
     "records": [
        [
            1,
            "BOOK_A",
            "{Honnor, Thriller}"
        ],
        [
            2,
            "BOOK_B",
            "{Commedy}"
        ],
      ]
```
Is there any way I can config jooq to auto-convert the query result to the expected format?
More context: My input query will be straightforward like `SELECT id, name, tags from books`

The same question for `json`, `jsonb` column types. Can jooq convert these column types into JSON object in the result

Thank you

### jOOQ Version

JOOQ OpenSource 3.18.4

### Database product and version

PostgreSQL 12.5 (Debian 12.5-1.pgdg100+1) on aarch64-unknown-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit

### Java Version

openjdk 17.0.6 2023-01-17

### OS Version

Ubuntu 22.04.2 LTS

### JDBC driver name and version (include name if unofficial driver)

TBU

**Comment by lukaseder** [comment]
Thanks for your message.

> More context: My input query will be straightforward like `SELECT id, name, tags from books`

Can you please provide the *exact* code you wrote?

**Comment by DangVuMinhHieu** [comment]
Sure @lukaseder 

```java
 List<SelectField> listFields = new ArrayList<SelectField>(){};
    listFields.add(DSL.field("id"));
    listFields.add(DSL.field("name"));
    listFields.add(DSL.field("tags"));

 SelectQuery jooqQuery = connection.getPublicDslContext().
                        select(listFields).
                        from(DSL.table("books")).
                        getQuery();

 return jooqQuery.fetch().formatJSON();
```

the `connection` variable is just an object for db connection ( com.zaxxer.hikari.HikariDataSource) so I won't mention how it initializes

Below is the picture of the result I captured after running query through API on Postman
<img width="654" alt="CleanShot 2023-06-02 at 09 55 19@2x" src="https://github.com/jOOQ/jOOQ/assets/18113539/efb2d2c1-4f52-45ee-94c5-970a0930445f">

**Comment by DangVuMinhHieu** [comment]
@lukaseder 
Just recognize I can use `DSL.field(<column_name>, <class_type>)` make the formatJSON() work as I expected

So i just need to write 

```java
List<SelectField> listFields = new ArrayList<SelectField>(){};
    listFields.add(DSL.field("id"));
    listFields.add(DSL.field("name"));
    listFields.add(DSL.field("tags"), String[].class);

 SelectQuery jooqQuery = connection.getPublicDslContext().
                        select(listFields).
                        from(DSL.table("books")).
                        getQuery();

 return jooqQuery.fetch().formatJSON();
```

And get the expected result

<img width="668" alt="CleanShot 2023-06-02 at 10 21 42@2x" src="https://github.com/jOOQ/jOOQ/assets/18113539/3ef706d8-b70f-46c8-84ff-0952f5417019">

But it would be nice if there are any Jooq configs I can utilize to make Jooq auto-convert the value without specifying the class.

Thanks.

**Comment by lukaseder** [comment]
Thanks for the clarifications. Looking at this pure JDBC example:

```java
try (ResultSet rs = connection.createStatement().executeQuery("select array[1, 2]")) {
    while (rs.next()) {
        println(rs.getMetaData().getColumnType(1));
        println(rs.getObject(1) + ":" + rs.getObject(1).getClass());
        println(Arrays.asList((Object[]) rs.getArray(1).getArray()) + ":" + rs.getArray(1).getArray().getClass());
    }
}
```

I'm getting:

```
2003
{1,2}:class org.postgresql.jdbc.PgArray
[1, 2]:class [Ljava.lang.Integer;
```

Where `2003 == java.sql.Types.ARRAY`. So, indeed, the `MetaDataFieldProvider` could detect the array type here, rather than just reading `ResultSet::getObject` and calling `toString()` on it. There are still some caveats as type information may not be available when:

- An array is `NULL`
- A result set is empty

But we could improve this nonetheless:

- https://github.com/jOOQ/jOOQ/issues/15166

But again, as you've noticed, it's always better to supply types to jOOQ, because the JDBC `ResultSetMetaData` is *very* limited in its capabilities of communicating types, and drivers often aren't too helpful either. For example, you requested JSONB support, but what could jOOQ possibly do?

```java
try (ResultSet rs = connection.createStatement().executeQuery("select '[1,2]'::jsonb")) {
    while (rs.next()) {
        println(rs.getMetaData().getColumnType(1));
        println(rs.getObject(1) + ":" + rs.getObject(1).getClass());
    }
}
```

This produces:

```
1111
[1, 2]:class org.postgresql.util.PGobject
```

Where `1111 == java.sql.Types.OTHER`. So, no useful information from pgjdbc.

You already know the expected type, so best pass it in the form of a `org.jooq.DataType` (e.g. `SQLDataType.VARCHAR.array()`). Passing a `String[].class` works, but again, it is less precise than the `SQLDataType`.

Of course, even better, why not just use code generation? You're missing out on *a ton* if you're not using that core feature of jOOQ, and you'll keep running into issues like this one:
https://blog.jooq.org/why-you-should-use-jooq-with-code-generation/
