### ISSUE TITLE
Deprecate inconsistent DSL.jsonObject(Field...) and DSL.jsonbObject(Field...) overloads

### ISSUE THREAD

**Issue by diamondq** [jOOQ/jOOQ#15196]
### Expected behavior

Prior to 3.18, you could call

```java
DSL.jsonbObject(MY_TABLE.COL1, MY_TABLE.COL2)
```
and it would call
```java
public static JSONObjectNullStep<JSONB> jsonbObject(Field<?>... entries)
```

### Actual behavior

In 3.18, as part of #14263 , a convenience method was added:

```java
public static JSONObjectNullStep<JSONB> jsonbObject(Field<String> key, Field<?> value)
```

This conflicts with the older method.
By default Java will now select the 2 field method since it's more specific than the variable argument array method.

I'm not saying that it's wrong to add the convenience method, but it definitely breaks backward compatibility as the two different methods operate completely differently in terms of the JSON Object that is created.

### Steps to reproduce the problem

As long as you are only passing two fields, and the first one is a Field<String>, then older code no longer works the same.

### jOOQ Version

3.18.4

### Database product and version

PostgresSQL 15

### Java Version

Corretto 17

### OS Version

Linux and Win 11

**Comment by lukaseder** [comment]
Thanks a lot for your report. This is very unfortunate indeed. It hasn't been noticed because we had no test coverage for the `jsonObject(Field<?>...)` method, other than passing an explicit `Field<?>[]`.

I suspect we need additional generic overload tests that make sure there won't be overloads like this, with conflicting semantics.

In the meantime, there are 3 ways to address this:

1. Keep things as they are and accept the incompatibility, clearly noting it in release notes
  - **Pro**: No new incompatible changes introduced
  - **Con**: *Very* inconvenient for many other users
  - **Con**: Overloads should always be equivalent in semantics, just offering convenience, e.g. `select(Field, Field)` and `select(Field...)` do the same thing), so this isn't a situation worth keeping. In particular if the first argument is not a `Field<String>` (but a `Field<Integer>`, for example), then overload resolution will help fall back to the previous API call. This can also be leveraged as a workaround, i.e. to cast the first argument to `(Field<?>)`
2. Remove the methods from https://github.com/jOOQ/jOOQ/issues/14263 again
  - In the next 3.19.0 minor release
    - **Pro**: Incompatible change introduced only in a minor release, not a patch release
    - **Con**: *Very* inconvenient for many other users for quite some time
    - **Con**: Users who rely on the new behaviour of this particular new set of methods will see a regression in the other direction
  - In the next 3.18.5 patch release
    - **Pro**: Lots of users who haven't upgraded to 3.18 yet won't run into this issue
    - **Pro**: Immediate action
    - **Con**: Users who rely on the new behaviour of this particular new set of methods will see a regression in the other direction, in a *patch* release!
3. Deprecate the methods from https://github.com/jOOQ/jOOQ/issues/14263 and remove them later
  - **Pro**: No new incompatible changes introduced
  - **Con**: Inconvenient for many other users
  - **Con**: Might not be detected

None of the option is a clear winner here as we'll have to make a tradeoff between:

- Breaking compatibility again, eventually
- Keeping a very undesirable tradeoff around

There was a precedent in jOOQ 3.9, where it took longer to detect a flaw (API introduced in 3.6, removed again in 3.9):

- https://github.com/jOOQ/jOOQ/issues/5233

I'm inclined towards option 3 (deprecation in 3.18.5) with removal in the next minor release (3.19.0). This would correspond to our stance on backwards compatibility, which deviates a bit from semver (no incompatibilities in patch releases, but in minor releases, they can be OK).

**Comment by lukaseder** [comment]
Unfortunately, the inconsistencies are older: The issue introducing `jsonbObject()` overloads (https://github.com/jOOQ/jOOQ/issues/14263) just added consistency between `jsonbObject()` and `jsonObject()`, and in doing so, copied the same inconsistency from `jsonObject()` to `jsonbObject()`. The latter had these overloads for a long time:

- https://github.com/jOOQ/jOOQ/issues/9932

jOOQ 3.14.0 already had these overloads, which had the API inconsistency but no incompatibilities: https://www.jooq.org/javadoc/3.14.x/org.jooq/org/jooq/impl/DSL.html

![image](https://github.com/jOOQ/jOOQ/assets/734593/5ed7b81c-fe81-4b35-b010-5de2ad255abf)

jOOQ 3.13.0 had a `jsonObject(Field<String> key, Field<?> value)` overload:
https://www.jooq.org/javadoc/3.13.x/org.jooq/org/jooq/impl/DSL.html

![image](https://github.com/jOOQ/jOOQ/assets/734593/e7b4d86b-858e-4eea-8587-7ca87fccb027)

Meaning the `Field<String> key, Field<?> value` overload preceded the `Field<?> entries` overload. The problem was the introduction of `Field<?> entries`, which is a convenience overload for creating a `JSONEntry<?>...` array from `Field::getName -> Field<?>` pairs.

The `jsonObject(Field<?>...)` overload should have been implemented as in MySQL, MariaDB, etc. where alternating key/value arguments are expected: `JSON_OBJECT(key1, value1, key2, value2, ...)`. That implementation would have been consistent with the jOOQ 3.13 API. But we can't change that now.

So, this additional information leads to a fourth option

4. Deprecate the `Field<?>...` overload for removal in a much later version. (And backport the deprecation to 3.16.20, 3.17.14, 3.18.5

This option turns out to be more desirable than the others, because it addresses the original mistake from 3.14

**Comment by lukaseder** [comment]
I haven't found any other cases, though there are many overloads with varargs, that look suspicious at first. Some examples include:

- `DSL.and(Condition...)` vs `DSL.and(Condition, Condition)`
- `DSL.or(Condition...)` vs `DSL.or(Condition, Condition)`

**Comment by diamondq** [comment]
This works for me. It was the silent breakage that was my bigger concern. With a deprecation notice, users should notice the issue during an upgrade (I know I would since I have deprecated usage marked as an error in my projects).

**Comment by lukaseder** [comment]
> With a deprecation notice, users should notice the issue during an upgrade (I know I would since I have deprecated usage marked as an error in my projects).

Yeah, the problem is, the 2 argument method call (the one with the silent breakage) won't be seeing that deprecation. The deprecation is only visible if 1 or 3 or more arguments are passed, or when the first argument isn't `Field<String>`. It's better than nothing, but still not ideal.
