### ISSUE TITLE
Add <genericConverter/> and <genericBinding/> to allow for passing T and U types to custom Converter and Binding instances

### ISSUE THREAD

**Issue by mdaepp** [jOOQ/jOOQ#15212]
### Use case

Our database stores enumerations based on values and not based on literals. These values are not ordinals but arbitrary values. All Java enumerations implement an interface that provides a method to retrieve the enumeration's value.

It's pretty easy to write a corresponding converter based on jOOQ's `EnumConverter`:
```
public class ApplicationXEnumConverter<T, U extends Enum<U> & ApplicationXEnum> extends EnumConverter<T, U> {

  public ApplicationXEnumConverter(Class<T> fromType, Class<U> toType) {
    super(fromType, toType,
        Number.class.isAssignableFrom(wrapper(fromType)) ? u -> convert(u.getValue(), fromType) : u -> convert(u.name(),
            fromType));
  }
}
```

Using it in the code generator requires redundant configuration:
```
                <forcedType>
                  <userType>com.company.applicationx.enums.StatusEnum</userType>
                  <converter>
                    <![CDATA[new org.jooq.impl.ApplicationXEnumConverter<Long, StatusEnum>(Long.class, StatusEnum.class)]]>
                  </converter>
                  <includeExpression>.*\.STATUS</includeExpression>
                </forcedType>
```
One has to explicitely specify the T- and U-types. The U-type is obvious, but for the T-type, one has to know what type will be generated by jOOQ.

It would be nice if both the T- and U-types would be available as variables.

Related issues: #13295 (implementing this enhancement would change the type) and #13787.

### Possible solution

A generic custom converter needs to know the T- and U-types just like jOOQ's `EnumConverter`, `AutoConverter` and the like.

Possible solutions:
1. Introspecting the provided converter and use the constructor with the T- and U-types if available. This solution seems impractical as jOOQ would need access to the converter. Typically, the converters are probably defined in the same project and not yet compiled when jOOQ generates the code (in Maven terms the generate-sources and compile phases) and therefore not available for introspection.
2. Provide T- and U-types as variables (simple String replacement) so that they can be used in inline (and possibly lambda) converters.

In above example, this would look like this:
```
                <forcedType>
                  <userType>com.company.applicationx.enums.StatusEnum</userType>
                  <converter>
                    <![CDATA[new org.jooq.impl.ApplicationXEnumConverter<${tType}, ${uType}>(${tType}.class, ${uType}.class)]]>
                  </converter>
                  <includeExpression>.*\.STATUS</includeExpression>
                </forcedType>
```

Other examples:
```
        <forcedType>
          <userType>java.time.Year</userType>
          <converter>org.jooq.Converter.ofNullable(
            ${tType}.class, ${uType}.class, 
            ${uType}::of, ${uType}::getValue
          )</converter>
          <includeExpression>.*\.YEAR.*</includeExpression>
        </forcedType>
```
```
        <forcedType>
          <userType>java.time.Year</userType>
          <lambdaConverter>
            <from>${uType}::of</from>
            <to>${uType}::getValue</to>
          </lambdaConverter>
          <includeExpression>.*\.YEAR.*</includeExpression>
        </forcedType>
```

It could make sense to expose both type and class as variables:
```
                <forcedType>
                  <userType>com.company.applicationx.enums.StatusEnum</userType>
                  <converter>
                    <![CDATA[new org.jooq.impl.ApplicationXEnumConverter<${tType}, ${uType}>(${tClass}, ${uClass})]]>
                  </converter>
                  <includeExpression>.*\.STATUS</includeExpression>
                </forcedType>
```
3. Provide a new configuration element `<genericConverter />` or an attribute on `<converter generic="true"></converter>` which would imply that the provided fully qualified name is parameterized with `<T, U>` and has a constructor that takes `Class<T>` and `Class<U>` as arguments.
```
<converter>org.jooq.impl.ApplicationXEnumConverter</converter>
```
would generate
```
new org.jooq.impl.ApplicationXEnumConverter()
```
while
```
<genericConverter>org.jooq.impl.ApplicationXEnumConverter</genericConverter>
```
or
```
<converter generic="true">org.jooq.impl.ApplicationXEnumConverter</converter>
```
would generate
```
new org.jooq.impl.ApplicationXEnumConverter<Long, StatusEnum>(Long.class, StatusEnum.class)
```

Solution 3. (with variant `<genericConverter />`) would probably be the easiest one to understand and use.

### Possible workarounds

The workaround is to specify the T- and U-types explicitely as shown above.

### jOOQ Version

jOOQ 3.18.4 trial edition

### Database product and version

Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production

### Java Version

openjdk 17.0.7 2023-04-18

### OS Version

Microsoft Windows [Version 10.0.19045.2965]

### JDBC driver name and version (include name if unofficial driver)

oracle.jdbc.OracleDriver 19.3.0.0.0

**Comment by lukaseder** [comment]
Thank you for your suggestion.

Note that writing some programmatic code generation configuration is always an option:
https://www.jooq.org/doc/latest/manual/code-generation/codegen-programmatic/

Using that approach, you can easily generate your forced types dynamically based on actual (meta) data from your database. You can also generate the XML content programmatically, and use the `<configurationFiles>` flag of the maven plugin:
https://www.jooq.org/doc/latest/manual/code-generation/codegen-maven/

Regarding your specific suggestions:

> 1. Introspecting the provided converter

This would either require that you pre-compile the converter in a code generation dependency and provide a `.class` reference to it to the code generator on the classpath, which isn't impossible, but cumbersome, and erasure would maybe remove some of the desired type information.

Alternatively, jOOQ-codegen would have to compile it itself (in Java, Kotlin, Scala) and draw its conclusions from it. There is similar work for other user-defined implementations of code generation logic:

- https://github.com/jOOQ/jOOQ/issues/15209
- https://github.com/jOOQ/jOOQ/issues/15213

But this is different because it affects runtime code, not code generation code, runtime code being harder to compile because it likely has more dependencies.

At the same time, it isn't clear by what rules any type inference should work. We'd expect a `Converter<T, U>` type reference, yes, but how would it be possible to know exactly where to substitute `T` and `U`? I can see tons of caveats and rules to flesh out, so quite some work. Not impossible, again, but unlikely a priority.

> 2\. Provide T- and U-types as variables (simple String replacement) so that they can be used in inline (and possibly lambda) converters.

Indeed, a mini template language / placeholder syntax is an idea that keeps re-appearing. I always reject it eventually, as e.g. this precedent:

- https://github.com/jOOQ/jOOQ/issues/10506

The problem is simply that such a language is very unlikely to be well designed and intuitive. It will require a lot of maintenance (because users will keep requesing it will do "just" one more little thing) and documentation (it's hard to help users build an intuition of what is really available in what configuration element).

All the while programmatic code generation configuration exists and *greatly* simplifies these use-cases! You can do *anything* you want very easily with an actual programming language, much more easily than with any template "language" that the code generation module would invent.

Note that all of these XML based limitations are mainly caused by the fact that `pom.xml` is such a rigid format. If Maven supported XSLT generated `pom.xml` (esoteric but effective), then dynamic configurations would be much simpler. If you used Gradle and this plugin: https://github.com/etiennestuder/gradle-jooq-plugin, then you'd be writing programmatic configuration already (even if it looks like a DSL).

So, the competitor to each solution idea is always programmatic configuration, which makes these ideas very hard to justify, unless they're *really* compelling.

> It could make sense to expose both type and class as variables:

This kinda shows what I mean. You already provided your first little change request. "Just" add these variables as well. A template language will never be finished or good enough.

At the same time, you don't really need these additional placeholders. Maybe you added them because you thought of the shenanigans of passing generic type variable substitutions (such as `List<String>`, whose `Class` literal must be `(Class<List<String>>) List.class`)?

> Other examples:

Those examples don't pull their weight. A lambdaConverter is usually tied to one very specific converter instantiation. The lambda bodies are probably not very re-usable. It's totally bearable to repeat the types `T` and `U` in such a specific converter. This is a different example from your original one, where the same converter type can indeed be re-used multiple times with multiple (`T`, `U`) pairs.

> Solution 3. (with variant `<genericConverter />`) would probably be the easiest one to understand and use.

Indeed, the precedent for other generic converters has already been made (`EnumConverter`, `AutoConverter`, `XMLtoJAXBConverter`, `JSONtoJacksonConverter`). It's always the same thing eventually. Either `T`, or `U`, or both have to be passed (in a `T`, `U` order). I can see this happening, it's indeed just a flag and a few lines of code generation logic to cover 80% of these cases. I will implement this.

**Comment by lukaseder** [comment]
Probably useful to do this also for `<binding/>`

**Comment by mdaepp** [comment]
Regarding:
> Note that writing some programmatic code generation configuration is always an option:
> https://www.jooq.org/doc/latest/manual/code-generation/codegen-programmatic/
>
> Using that approach, you can easily generate your forced types dynamically based on actual (meta) data from your database. 
> You can also generate the XML content programmatically, and use the <configurationFiles> flag of the maven plugin:
> https://www.jooq.org/doc/latest/manual/code-generation/codegen-maven/
Thanks for mentioning this. That would be an interesting approach indeed. The problem is, that I can't derive the actual enumeration type from the meta data in the DB. The mapping of fields to enum types is documented elsewhere. So I would have to do some sort of mapping somewhere anyway. I'm OK to do the mapping in the XML configuration since everything is I need is already there.

Thanks for the additional insights on the solutions 1. and 2. I totally agree.

Thanks for implementing solution 3! It's nice that implemented the same concept to `<binding/>` as well as I'm sure somebody will find it useful.

The workaround I'm currently going with is to omit `<converter/>` in the XML configuration completely (which essentially results in the application of an `AutoConverter`) and provide a custom implementation of `ConverterProvider` which provides an `ApplicationXEnumConverter` if  `ApplicationXEnum` is assignable from the U-type and otherwise just delegates to `DefaultConverterProvider`. I'll switch to the new solution once 3.19 is released as I like to make the fact that a converter is applied in this case more explicit. Neither of the approaches prevents futher optimizations (such a ensuring that the converter is a singleton) that might be required in the future (i.e. when the enumeration contains a lof og entries or many fields share the same enumeration type). For now, I'm refraining from it because I don't think that it will really become an issue.

One more thing: Currently I have to put my converter in the org.jooq.impl package to be able to use methods from `org.jooq.impl.Convert`. While I understand the reasoning behind #11898, I still think that it would be useful to have access to to `convert(...)`. In implementing `ApplicationXEnumConverter`, I only had to change `u.ordinal()` to `u.getValue()` when extending `EnumConverter`. I like to reuse code that works and is well tested instead of reinventing the wheel ;-)

**Comment by lukaseder** [comment]
> I still think that it would be useful to have access to to `convert(...)`.

You should do this via the `ConverterProvider` SPI (the default implementation in `DefaultConverterProvider`), not the static methods in `Convert`. It is effectively the same, but allows for the overriding you're using already.

> I like to reuse code that works and is well tested instead of reinventing the wheel ;-)

And that's why you should use `ConverterProvider`. If ever "auto conversion" evolves to your disliking (e.g. by supporting a type pair that you didn't expect and which produces a subtle regression), you can prevent that conversion by implementing your own `ConverterProvider` that reverts the new conversion. If you had used `Convert` (static methods), then there's no way of preventing new conversion features you don't want to be introduced into your code.

**Comment by mdaepp** [comment]
OK, I see what you mean. So I'd end up with something like this:
```
public class ApplicationXEnumConverter<T, U extends Enum<U> & ApplicationXEnum> extends EnumConverter<T, U> {
  private static final DefaultConverterProvider CONVERTER_PROVIDER = new DefaultConverterProvider();

  public ApplicationXEnumConverter(Class<T> fromType, Class<U> toType) {
    super(fromType, toType, Number.class.isAssignableFrom(Reflect.wrapper(fromType)) ?
        u -> Objects.requireNonNull(CONVERTER_PROVIDER.provide(fromType, Integer.class)).to(u.getValue()) :
        u -> Objects.requireNonNull(CONVERTER_PROVIDER.provide(fromType, String.class)).to(u.name()));
  }
}
```
Still seems a little odd though ;-)

**Comment by lukaseder** [comment]
Why is it odd?
