### ISSUE TITLE
Support JPQL in the translation tool

### ISSUE THREAD

**Issue by huapii-ben-desmedt** [jOOQ/jOOQ#15223]
JPQL would be useful to add

**Comment by lukaseder** [comment]
Thanks for your suggestion. I'm curious about your use-cases. Why would you want to translate from/to JPQL? To migrate off JPQL to native SQL? (but for that, you can simply extract the SQL from your JPA logs). Or to migrate from SQL to JPQL? (but then, why not just use native SQL?)

In order to support JPQL in our translation tool, we'd have to make a ton of assumptions about your annotated entities, and/or accept users uploading their entities for introspection (e.g. what does an identifier `a.b.c` mean? Is it an embeddable? An implicit join? Something else?)

For the time being, our focus lies elsewhere.
