### ISSUE TITLE
Behaviour of JavaGenerator for custom data types

### ISSUE THREAD

**Issue by matjazs** [jOOQ/jOOQ#15284]
### Your question

We are using custom data types in our project, specifically for PostgreSQL `range` types and the `geometry` type.

We were able to use our custom bindings for our custom types without any issues until introduction of the out-of-the-box support for spatial types (I think this was in version 3.16). After jOOQ 3.16 we resorted to using the java generator only partially, not allowing it to overwrite the generated table field definitions for our custom types.

The issue is with the generated type reference for geometry type, causing invalid generated SQL in certain situations, e.g. when using `cast(org.geolatte.geom.Geometry.class)` function in a jOOQ query. The error and the related SQL query fragment is:
```
...
 and st_within("weather"."weather_locations"."geometry", cast(st_geographyfromtext('srid=...some srid...;polygon((...some coordinates...))') as any)) = ?]; ERROR: syntax error at or near "any"
```

I didn't check explicitly, but I presume that before the change, the cast in the generated SQL was using `geometry` instead of `any`.

The generated Java code before introducing spatial support:

```java
    public final TableField<FieldGeometryRecord, Geometry> GEOMETRY = createField(DSL.name("geometry"), org.jooq.impl.DefaultDataType.getDefaultDataType("\"public\".\"geometry\"").nullable(false), this, "", new PostgresqlGeometryBinding());
```

And after:
```java
    public final TableField<FieldGeometryRecord, Geometry> GEOMETRY = createField(DSL.name("geometry"), SQLDataType.OTHER.nullable(false), this, "", new PostgresqlGeometryBinding());
```

What is also interesting is that for the `range` types, the generator behaviour remained the same between the versions, the latest jOOQ doesn't generate the `OTHER` type, but the PostgreSQL one using `DefaultDataType.getDefaultDataType()`:

```java
    public final TableField<FieldGeometryRecord, Range> EFFECTIVE = createField(DSL.name("effective"), org.jooq.impl.DefaultDataType.getDefaultDataType("\"pg_catalog\".\"tstzrange\""), this, "", new PostgresqlRangeBinding());
```

Our generator configuration fragment:

```xml
        <generate>
            <intervalTypes>false</intervalTypes>
            <spatialTypes>false</spatialTypes>
        </generate>
        <database>
            <name>org.jooq.meta.postgres.PostgresDatabase</name>
            <includes>.*</includes>
            <forcedTypes>
                <forcedType>
                    <userType>com.google.common.collect.Range</userType>
                    <binding>org.example.PostgresqlRangeBinding</binding>
                    <includeTypes>.*range</includeTypes>
                </forcedType>
                <forcedType>
                    <userType>org.geolatte.geom.Geometry</userType>
                    <binding>org.example.PostgresqlGeometryBinding</binding>
                    <includeTypes>geometry</includeTypes>
                </forcedType>
            </forcedTypes>
         </database>
```

Bindings are declared as (I can post the implementations later if required):

```java
public class PostgresqlGeometryBinding extends AbstractBinding<Object, Geometry> {
}

public class PostgresqlRangeBinding<T extends Comparable<T>> extends AbstractBinding<Object, Range<T>> {
}
```

My question is whether this is an expected behaviour and if so, how can one implement the custom binding properly to avoid for example the above casting issue. Also, why would be the custom type for ranges treated differently as for geometry with respect to the generated field's type reference.

### jOOQ Version

jOOQ 3.18.5 Open Source Edition

### Database product and version

PostgreSQL 14.8 (Homebrew) on aarch64-apple-darwin22.4.0, compiled by Apple clang version 14.0.3 (clang-1403.0.22.14.1), 64-bit

### Java Version

openjdk 17.0.7 2023-04-18

### OS Version

macOS 13.4.1

### JDBC driver name and version (include name if unofficial driver)

org.postgresql:postgresql:42.5.4

**Comment by lukaseder** [comment]
Thanks for your message.

> My question is whether this is an expected behaviour 

It's hard to say what you mean by "expected" without seeing a complete reproducer. My guess here is that things happened to work by accident. We don't have any integration tests related to `org.jooq.impl.DefaultDataType.getDefaultDataType()` usage. The data type reference is mostly being generated for documentation purposes. If it is ever used in a cast, then it may or may not work.

The fact that it is now absent with the `GEOMETRY` type is likely due to the type support not being available in the jOOQ Open Source Edition, but you can always cast explicitly in your data type bindings.

> and if so, how can one implement the custom binding properly to avoid for example the above casting issue. 

I think you're referring to this?

> cast(org.geolatte.geom.Geometry.class)

How would jOOQ know what this really means? There's a historic accident that custom converted data types were registered in the internal static type registry, but you cannot rely on this. It can break for a variety of reasons. It might be due to the fact that you used to register your binding for that type with a type that had the complete type name associated with it, but again, that may or may not work depending on the initialisation order of generated code.

A much better type registry will be available eventually:

- https://github.com/jOOQ/jOOQ/issues/5713

Until then, it's usually best not to use `Class<T>` references in your casts, but rather `DataType<T>` references.

> I didn't check explicitly, but I presume that before the change, the cast in the generated SQL was using `geometry` instead of `any`.

The cast to `any` is most likely because of the above. jOOQ doesn't really know what your geolatte `Geometry` type means.

> Also, why would be the custom type for ranges treated differently as for geometry with respect to the generated field's type reference.

The `GEOMETRY` (and `GEOGRAPHY`) types were supported in jOOQ 3.16 for all dialects via new `SQLDataType` instances, with dialect specific rendering, binding, etc.:

- https://github.com/jOOQ/jOOQ/issues/12780

The range types are PostgreSQL specific, and aren't supported as `SQLDataType` instances. They're only offered as bindings / converters:

- https://github.com/jOOQ/jOOQ/issues/2968

**Comment by lukaseder** [comment]
We should really move forward with deprecating / discouraging relevant API:

- https://github.com/jOOQ/jOOQ/issues/15286

This way at least, you'll be made aware of preferring `cast(DataType<Geometry>)` earlier in your case, rather than using `cast(Class<Geometry>)`. It's clearly an API design flaw that should be fixed with #5713 eventually.

**Comment by matjazs** [comment]
Thanks for all the info and clarifications.

The case with `geometry` cast worked in all versions including 3.18 because we were forcefully using the old generated data type in generated Java files: `org.jooq.impl.DefaultDataType.getDefaultDataType("\"public\".\"geometry\"")`. With this declaration and our custom binding combo, the generated SQL query contained the working `as geometry` fragment as opposed to the failing `as any` fragment in both 3.16 and 3.18.

However, I was able to fix the query by using the `DataType<T>` reference as suggested, allowing us to use the generated Java code without modifications.

Thanks again for your help.

**Comment by lukaseder** [comment]
As a workaround, you can also do this somewhere in your application initialisation code:

```java
DefaultDataType.getDefaultDataType("\"public\".\"geometry\"").asConvertedDataType(new PostgresqlGeometryBinding());
```

It will have the same effect of registering the `DataType<Geometry>` in the internal static type registry. At least, this will prevent any regressions in production should you forget one instance of `cast(Geometry.class)`, or any other similar usage, such as plain SQL templates: `field("some_function()", Geometry.class)`

**Comment by matjazs** [comment]
Thanks for the idea. I've fixed all the occurrences but will add the recommended safeguard in case someone else uses the discouraged overload in the future, until the availability of the new type registry implementation.
