### ISSUE TITLE
Does JOOQ support escaping single quote with backslash instead another single quote.

### ISSUE THREAD

**Issue by reluctantDev** [jOOQ/jOOQ#15280]
### Your question

Does JOOQ support escaping single quote with backslash instead of another single quote.

Example:
**Given**
` 
select * from person name = 'l'moron'
`
**to**
`
select * from person name = 'l\'moron'
`
**instead of**
`
select * from person name = 'l''moron'
`

### jOOQ Version

3.11

### Database product and version

MySQL

**Comment by lukaseder** [comment]
There's `Settings.backslashEscaping`, which serves a related purpose (namely the escaping of the backslashes themselves in case they're present in bind values):
https://www.jooq.org/doc/latest/manual/sql-building/dsl-context/custom-settings/settings-backslash-escaping/

But that's not what you want. We don't allow for overriding that, because all dialects we've integration tested these cases with already behave as expected, on a per dialect basis - the only exception being BigQuery, which doesn't support doubling the apostrophe.

**Comment by reluctantDev** [comment]
Thank you @lukaseder 
So just to double check and for my understanding 
There is **no** special handling available to **overriding** the current behavior(`''`) of escaping a single quote(`'`).
It also not planned to be provided.

**Comment by reluctantDev** [comment]
> No, why would there be?

Reason asking is **spark sql** doesn't support double single quotes as valid escaping of single quote.
Instead it expects a backslash before the single quote.
cc: @lukaseder
