### ISSUE TITLE
Meta.ddl() generates "create schema" statement for Oracle

### ISSUE THREAD

**Issue by mgramin** [jOOQ/jOOQ#15298]
### Expected behavior

When I create a new schema (by creating a user with the same name):
```sql
CREATE USER test;
```
I expect that `Meta.ddl()` generates a valid DDL script.

### Actual behavior

However, jOOQ does not export a valid DDL script:
```sql
create schema "TEST"
```

This leads to an error during execution: "ORA-02420: missing schema authorization clause"

### Steps to reproduce the problem

Create a new schema in DB:
```sql
CREATE USER test;
```

Run this code:
```java
        Connection conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe", "system", "mypassword");
        Configuration configuration = new DefaultConfiguration().set(conn).set(SQLDialect.ORACLE);
        Meta meta = using(configuration).meta();

        Arrays.stream(meta.filterSchemas(v -> v.getName().equalsIgnoreCase("test"))
                        .ddl()
                        .queries())
                .map(Object::toString)
                .forEach(System.out::println);
```

Execute the resulting query against a different database:
```sql
create schema "TEST"
```

### jOOQ Version

jOOQ Professional Edition 3.18.4

### Database product and version

Oracle Database 21c Express Edition Release 21.0.0.0.0 - Production

### Java Version

openjdk 17.0.2 2022-01-18

### OS Version

Microsoft Windows [Version 10.0.19044.2846]

### JDBC driver name and version (include name if unofficial driver)

com.oracle.database.jdbc:ojdbc11:23.2.0.0

**Comment by lukaseder** [comment]
Thanks for your report. This is probably related:

- https://github.com/jOOQ/jOOQ/issues/10167

I think we could add this sooner rather than later.

**Comment by lukaseder** [comment]
While support for `CREATE USER` and `DROP USER` commands is certainly interesting as well (with the aspect of authenticating with the user), we can support `CREATE SCHEMA` and `DROP SCHEMA` via so-called "schema-only" accounts in Oracle already before:

- https://github.com/jOOQ/jOOQ/issues/15307

I wouldn't consider this a defect here (which could be backported), but simply a missing feature. In order to omit the `CREATE SCHEMA` commands, you can pass a `DDLFlag` to your schema export. Alternatively, you can transform the resulting `Queries` using `QueryPart::$replace`, and replace all the `QOM.CreateSchema` queries by plain SQL templates implementing #15307's `CREATE USER` semantics, manually, until #15307 ships.

Closing this as a duplicate of https://github.com/jOOQ/jOOQ/issues/15307 (which is more generic. This issue here is mainly about `Meta.ddl()`, but we really want to support the statement everywhere)

**Comment by lukaseder** [comment]
There are funny implications caused by the fact that a "schema only" account in Oracle is still really a `USER` with a whole set of `PRIVILEGES` (or lack thereof). Here's a "fun" example from a failing integration test:
https://github.com/jOOQ/jOOQ/issues/15307#issuecomment-1612770666

It can be solved either with blunt grants (`GRANT ANY PRIVILEGE`), which could cause security risks, or fine grainted grants, which are a PITA, if we want to treat "schema only" accounts as schemas. I'm not sure yet what to do about this. Maybe, you could share some expectations / thoughts?

I'm reluctant to deliver grants eagerly to such "schema only" accounts...

**Comment by lukaseder** [comment]
Another topic is tablespaces. For a schema to be usable, `QUOTA UNLIMITED ON USERS` might be a good default, though probably not what a lot of Oracle users would expect.

Yet another spin-off feature request:

- https://github.com/jOOQ/jOOQ/issues/15308
