### ISSUE TITLE
Why jooq generates sql for OffsetDateTime with casting? And logging mismatched

### ISSUE THREAD

**Issue by ramilS** [jOOQ/jOOQ#15290]
Example project: https://github.com/ramilS/jooq_date_cast_issue

### Query issue

this code 

```java
jooq.selectFrom(table("book"))
    .where(field("date_created").ge(OffsetDateTime.now()))
    .getSQL()
```

will produce `select * from book where date_created >= cast(? as timestamp with time zone)`, but expected `select * from book where date_created >= timestamp with time zone ?`

------------------

### Logging mismatching:

```log
org.jooq.tools.LoggerListener : Executing query : select * from book where date_created >= cast(? as timestamp with time zone)
```

and there is no casting in inlined query
```
org.jooq.tools.LoggerListener: -> with bind values : select * from book where date_created >= timestamp with time zone '2023-06-27 15:23:24.770864+03:00'
```

### jOOQ Version

3.18.4

### Database product and version

Postgres 15-alpine

### Java Version

OpenJDK  Corretto-17.0.3.6.1

### OS Version

Mac

### JDBC driver name and version (include name if unofficial driver)

postgres

**Comment by lukaseder** [comment]
Thanks for your message. `TIMESTAMP WITH TIME ZONE 'xyz'` is a SQL standard timestamp literal, yet there is no syntax `TIMESTAMP WITH TIME ZONE ?` in any RDBMS I'm aware of. The cast is occasionally necessary in various RDBMS because either the JDBC driver or the server cannot infer the bind variable type from the expression or from the bind variable alone.

I hope this explains it?
