### ISSUE TITLE
jsonbSet uses `json_set`

### ISSUE THREAD

**Issue by ia-aalmanza** [jOOQ/jOOQ#15301]
### Expected behavior

I expected `jsonbSet` to use the function `jsonb_set` from [postgress](https://www.postgresql.org/docs/14/functions-json.html)

### Actual behavior

looks like it uses `json_set` instead of `jsonb_set` https://github.com/jOOQ/jOOQ/blob/ba97ea45966c7b0252d28bc892fa1b0e7bcca271/jOOQ/src/main/java/org/jooq/impl/JSONBSet.java#L119

### Steps to reproduce the problem

tried using `jsonbSet` and in the logs I saw that it actually uses `json_set` 

### jOOQ Version

3.18.2

### Database product and version

postgres

**Comment by lukaseder** [comment]
Thanks for your report. The `JSON_SET` function implements the functionality of MySQL's `JSON_SET` function:
https://dev.mysql.com/doc/refman/8.0/en/json-modification-functions.html#function_json-set

Which differs a lot from that of PostgreSQL, mainly by accepting an actual JSON path, rather than this weird `TEXT[]` representation of a "path". We currently can't emulate MySQL's more powerful version on PostgreSQL. See also the comments on this issue:

- https://github.com/jOOQ/jOOQ/issues/13951

If in doubt, please always consider the `@Support` annotation on relevant jOOQ API:
https://www.jooq.org/javadoc/latest/org.jooq/org/jooq/impl/DSL.html#jsonbSet(org.jooq.Field,java.lang.String,java.lang.Object)

As you can see, it doesn't include PostgreSQL:

```java
@Support({MARIADB_10_2,MYSQL_5_7,ORACLE21C,SQLITE,SQLSERVER2016})
```
