### ISSUE TITLE
The best way to auto set audit fields value? like createBy/updateBy

### ISSUE THREAD

**Issue by liu-xinhui** [jOOQ/jOOQ#15320]
#### I have already read the issues and Stack Overflow, found the following solutions:
1. **VisitListener**: This is very complex, and I cannot fully understood its API. Moreover, most of the APIs have been deprecated, I'm not sure if it can achieve the desired functionality.

2. **ExecuteListener**: This is simple, but it cannot access the `Table` object, and it cannot retrieve param value by `field name` because `UpdateQueryImpl` `InsertQueryImpl` is private.

3. **RecordListener**: This solution not works with arbitrary DML operations.

4. **Audit columns**: Cannot be used in the Open Source Edition, but I don't think it can fulfill my requirements. Becase `CURRENT_USER` is the database user, while `createBy` is the website user.

5. **Replacement**: This solution cannot be used in the Open Source Edition.

### jOOQ Version

Open Source Edition 3.18

### Database product and version

mysql:8.0.32

### Java Version

openjdk-17.0.2

### OS Version

all

### JDBC driver name and version (include name if unofficial driver)

com.mysql.cj.jdbc.Driver:8.0.32

**Comment by liu-xinhui** [comment]
I tried to obtain the Table object using reflection. But I am not sure its correct？
``` java
public class JooqExecuteListener implements ExecuteListener {
    private static final String CREATE_BY = "create_by";
    private static final String CREATE_TIME = "create_time";
    private static final String UPDATE_BY = "update_by";
    private static final String UPDATE_TIME = "update_time";


    @Override
    @SuppressWarnings("Duplicates")
    public void start(ExecuteContext ctx) {
        Query query = ctx.query();
        if (query instanceof InsertQuery<?> insertQuery) {
            TableImpl<?> table = ReflectUtil.invoke(query, "table");
            Field<Object> byField = table.field(DSL.field(CREATE_BY));
            if (byField != null) {
                insertQuery.addValue(DSL.field(CREATE_BY, String.class), "lxh");
            }
            Field<Object> timeField = table.field(DSL.field(CREATE_TIME));
            if (timeField != null) {
                insertQuery.addValue(DSL.field(CREATE_TIME, LocalDateTime.class), LocalDateTime.now());
            }
        } else if (query instanceof UpdateQuery<?> updateQuery) {
            TableImpl<?> table = ReflectUtil.invoke(query, "table");
            Field<Object> byField = table.field(DSL.field(UPDATE_BY));
            if (byField != null) {
                updateQuery.addValue(DSL.field(UPDATE_BY, String.class), "lxh");
            }
            Field<Object> timeField = table.field(DSL.field(UPDATE_TIME));
            if (timeField != null) {
                updateQuery.addValue(DSL.field(UPDATE_TIME, LocalDateTime.class), LocalDateTime.now());
            }
        }
    }
}
```

**Comment by lukaseder** [comment]
Thanks a lot for your message.

The best way to use audit fields is by using the audit feature. It can work with both client side (Java based) and server side (SQL based) expressions. If it doesn't suffice, please note it's built on top of the client side computed columns feature, which will certainly be enough even for more complex audit column use-cases:
https://www.jooq.org/doc/dev/manual/code-generation/codegen-advanced/codegen-config-database/codegen-database-forced-types/codegen-database-forced-types-computed/

> I tried to obtain the Table object using reflection. But I am not sure it is correct？

You shouldn't use reflection with jOOQ. I understand you're just trying to make it work without using the commercial editions (though, do ask yourself, how much time have you spent already, and is that time (plus the future maintenance work) not better spent otherwise, than avoiding the jOOQ Express Edition, which is quite reasonably priced!)

If you really want to handle all the hundreds of edge cases yourself that client side computed columns would do for you, otherwise (trust me, there are many!), then I recommend looking into the experimental model API:
https://www.jooq.org/doc/dev/manual/sql-building/model-api/

While the replacement API is also commercial only, you can certainly replace your reflection code by model API usage (just do `query instanceof QOM.Insert i` and then call `i.$accessorMethods()` to patch your query members).

Though again, remember that for a reasonable price, all of this works out of the box!

**Comment by liu-xinhui** [comment]
@lukaseder Got it, thank you very much.
