### ISSUE TITLE
record.field() returns a value when using a qualified name of a column from another table

### ISSUE THREAD

**Issue by eduardolbueno** [jOOQ/jOOQ#15429]
### Expected behavior

record.field() should return null when using a qualified name of a column from another table

### Actual behavior

record.field() returns a value when using a qualified name of a column from another table

### Steps to reproduce the problem

Let's say I have tables ORDER and PAYMENT, and both have a status column. 

When I query an order, if I do `record.field(PAYMENT.STATUS.getQualifiedName())` it returns the actual order status, so it's not matching the actual qualified name.

### jOOQ Version

3.18.4

### Database product and version

PostgreSQL 14.6

### Java Version

17

### OS Version

macOS Ventrua

### JDBC driver name and version (include name if unofficial driver)

org.postgresql:postgresql:42.6.0

**Comment by lukaseder** [comment]
Thanks a lot for your message.

The behaviour is documented here (look for partial match):
https://www.jooq.org/javadoc/latest/org.jooq/org/jooq/Fields.html

There are pros and cons to both approaches: requiring exact matches always, or allowing partial matches. The benefit of allowing partial matches can be, for example, to be able to dereference a generated field from a derived table.

I hope this helps.

**Comment by eduardolbueno** [comment]
If I'm e.g. doing a joined select between the tables then `record.field(PAYMENT.STATUS.getQualifiedName())` matches the correct column.
Isn't this considered flaky behavior? Why do I have to account for something like that when I expect the framework to be consistent? Why does partial matches ignore the table reference? Why does derived tables matter if they must have an alias?

**Comment by lukaseder** [comment]
Derived tables don't have to have an alias in jOOQ, and they're just one of many examples where this approach helps users. Look at the `org.jooq.Fields` type hierarchy. All implementations profit from this.

Again, there are pros and cons to both approaches. The feature has been around since 1.0. It's certainly not a bug, and also not up for debate, given how significant a backwards incompatible change it would be.

You seem to find it terrible. Others complain that it doesn't go far enough (e.g. they would like it to be case insensitive). There's no obvious winner here.

I hope this helps.
