### ISSUE TITLE
DSL.val doesn't work as expected when attempted to convert from custom class into jOOQ class

### ISSUE THREAD

**Issue by Spikhalskiy** [jOOQ/jOOQ#15454]
### Your question

Our project has two custom classes to work with geometry/geography.

```
data class Coordinate(val latitude: Double, val longitude: Double)
data class Polygon(val coordinates: List<Coordinate>)
```

We have two converters, that are registered with jOOQ and generally work correctly.
```
class GeometryPolygonConverter : Converter<Geometry, Polygon>
class GeometryCoordinateConverter : Converter<Geometry, Coordinate>
```

Something like this works fine:
```
fun distanceLimit(location: Coordinate, distanceLimit: Int): Condition {
    val distance = field("ST_Distance(addresses.location, ${DSL.`val`(location, Coordinate::class.java)}, false)", Double::class.java)
    return distance.lt(DSL.`val`(distanceLimit, Double::class.java))
}
```
jOOQ is able to pick up the correct converter and convert Custom Class -> Geometry -> Database Query.

When we want to use geo APIs like `DSL.stContains`, it doesn't support custom user classes, it needs `Spatial`.
So we try to do
```
    fun selectApplicableRegions(location: Coordinate): Condition {
        return DSL.stContains(REGIONS.REGION.cast(Geometry::class.java), DSL.`val`(location, Geometry::class.java))
    }
```
where `REGIONS.REGION` is `TableField<RegionsRecord, Polygon?>`.

But it doesn't work. ``DSL.`val`(location, Geometry::class.java)`` produces an incorrect structure
`Geometry{data="Coordinate(latitude=43.6711452, longitude=-79.404601)"}`. So instead of using our registered custom converter, jOOQ just serializes Coordinate into String and puts it into `Geometry.data` field.

The workaround that we have to use to make it work:

```
    fun selectApplicableRegions(location: Coordinate): Condition {
        return DSL.stContains(REGIONS.REGION.cast(Geometry::class.java), GeometryCoordinateConverter().to(location)!!)
    }
``` 

We would want to not spread jOOQ converters everywhere in code and let jOOQ handle the conversion between jOOQ classes and custom classes using already registered converters, especially when jOOQ successfully does it in other places.

Looks like a bug, but I'm not sure.

### jOOQ Version

3.18.5

### Database product and version

PostgreSQL 15.3

**Comment by lukaseder** [comment]
Thanks for your message.

### A side-note on the usage of `DSL.val(Object, Class)`

The next set of patch releases will include a Javadoc hint about your `DSL.val(Object, Class)` API usage:

> NOTE [#15286]: It is strongly recommended to pass only Class references of types supported by jOOQ internally, i.e. types from SQLDataType. If you're using any custom data types by means of a Converter or Binding, it's better to pass thatconverted DataType reference explicitly to val(Object, DataType).

See also:

- #15286

This doesn't explain the issue you're seeing, but it's good to keep in mind, especially in case you might run into edge cases where your query is run before your type is registered in the internal, static type registry due to some race condition.

### Your actual question:

Regarding your question, there's a big discussion about an alternative API design, where all built-in functions would be `Converter` capable:

- https://github.com/jOOQ/jOOQ/issues/11088

In particular, `stContains()` would accept a `Field<Geometry, ?>` (with `?` being an arbitrary user type), rather than just `Field<Geometry>`. This would be a thorough solution to allowing users to use custom types with build-in functions.

Other than that, you have these options:

- [Plain SQL templating](https://www.jooq.org/doc/latest/manual/sql-building/plain-sql-templating/), where you can build an entire library of functions supporting on your own data types
- Let your data classes implement `org.jooq.Spatial` (might work, I haven't tried this)
- Manually convert data, like you did
- Use `DSL.coerce()` to coerce your custom data type to the `Geometry` type

**Comment by Spikhalskiy** [comment]
@lukaseder Thank you for your answer! It would be great to get a clarification on
`
NOTE [https://github.com/jOOQ/jOOQ/issues/15286]: It is strongly recommended to pass only Class references of types supported by jOOQ internally, i.e. types from SQLDataType. If you're using any custom data types by means of a Converter or Binding, it's better to pass thatconverted DataType reference explicitly to val(Object, DataType).`

It looks like I use this API correctly then... Does it mean we have an actual bug here with the converter not being called?
My Class reference is Geometry, which is `SQLDataType` type and the reference is our custom object.

**Comment by Spikhalskiy** [comment]
`DSL.coerce(location, Geometry::class.java)` works perfectly and gives the semantic and experience I need though.
Maybe more javadoc on `val` about its "conversion" or rather "non conversion" properties would be helpful. + a `@see` link to `coerce` method. Because I didn't discover `coerse` until you pointed it out. I did try to lookup methods with `convert` names though :)

**Comment by lukaseder** [comment]
> This by itself as you pointed doesn't explain the issue, because my Class reference is Geometry, which is `SQLDataType` type and the reference is our custom object that needs to be converted. Which doesn't contradict this note.

I just comment on this usage whenever I see it, so 1) people learn the risk and 2) people can google things where they can learn about the risk.

> Maybe more Javadocs on `val` about its "converting" or rather "non-converting" properties would be helpful. + a `@see` link to `coerce()` method. Because I didn't discover `DSL.coerse()` until you pointed it out. I did try to search for methods with `convert` in names though :)

Well, there's no conversion going on with `coerce()`. It just makes jOOQ pretend that types match, even if they don't. You could also just rawtype cast to `(Field)`, though that has its own drawbacks as rawtypes propagate through Java expressions in a bad way.

Agreed on additional Javadoc on `val()`:
https://github.com/jOOQ/jOOQ/issues/15459

**Comment by lukaseder** [comment]
`DSL.val(Object o, DataType<T> t)` applies `t.convert(o)`. E.g. `val("1", SQLDataType.INTEGER)` does the "obvious" thing.

There's no "obvious" thing (known to jOOQ) when you write ``DSL.`val`(location, Geometry::class.java)``

What you're observing is "accidental" behaviour of the jOOQ auto conversion feature. The last attempt in the auto converter (or also `DefaultConverterProvider`) for any pair of types `(T, U)` is to call a single argument `U(T)` constructor, or a compatible constructor. In this case, `Geometry(String)` is "compatible", because the type of `T` is `Object` (it is an unknown type), and any `Object` can be converted to a `String`. Clearly, not what you intended.

**Comment by Spikhalskiy** [comment]
> There's no "obvious" thing (known to jOOQ) when you write DSL.`val`(location, Geometry::class.java)

Even if there is a registered converter from `location` custom class into Geometry that works fine in other places?

**Comment by lukaseder** [comment]
Why would you want this to work?

The method is static and as such, even if we did implement a generic `(T, U)` type pair converter lookup (which is non-trivial, if we include auto conversion expectations as well as potential `(T, X, U)` paths in case both `(T, X)` and `(X, U)` are available), then there could still be ambiguous `(T, U)` paths which would be registered in random order in the static type registry.

But given that the static type registry might no longer register user defined types in the future, how would you make this work? And why? (I understand you came here from an assumption, and now you want to make the API work in your expected way. But my question is from an API design perspective. Should this work? I don't think it should).

I think that the thing you *really* want to do is use built-in functions with user defined types. Now, you've assumed that some workaround "*should*" work (though I disagree). And now we're debating the workaround. But the real feature we should be debating is https://github.com/jOOQ/jOOQ/issues/11088. All workarounds are equal workarounds, and any additional perceived convenience of a workaround doesn't make it less of a workaround.

The fact that converted types ended up in the static type registry has been a historic accident, that a lot of users started relying upon. We can't simply remove it, of course, but most of all, I really don't want to add features to this non-feature.
