### ISSUE TITLE
Mapping not applied on Strings

### ISSUE THREAD

**Issue by trourance** [jOOQ/jOOQ#15469]
### Expected behavior

Mapping is applied on fields or tables declared using String or name(String).

### Actual behavior

Mapping is not applied when using a constructor with String or name(String) for tables in SelectFromStep.

- That's annoying because it is the only way to bypass those limitations: https://github.com/jOOQ/jOOQ/issues/15437

### Steps to reproduce the problem

Create a `SelectFromStep.from(String sql)` or `SelectFromStep.from(Name name)` and apply a `MappedSchema()`. The generated query doesn't have the output schema for the table declared in `from`.

### jOOQ Version

jOOQ Professional Edition 3.18.2

### Database product and version

CockroachDB 22.9

### Java Version

openjdk version "11.0.16.1"

### OS Version

Linux

### JDBC driver name and version (include name if unofficial driver)

org.postgresql:postgresql:42.6.0

**Comment by lukaseder** [comment]
Thanks a lot for your report.

Can you show an example of a query where you'd expect the schema mapping to work? (Please note that a plain SQL template is completely opaque to jOOQ by design...)

I'm not quite sure what you mean by "the only way to bypass those limitations". There are many workarounds possible, but I'd first like to see more examples of what you're trying, and why you're expecting things to work.

**Comment by trourance** [comment]
I'm using the following code to generate the SQL statement, of course a bit simplified.

```
val fromTable = "$table"
val joinSecondTable = "LEFT MERGE JOIN $secondTable " +
                "ON ${secondTable.ID.eq(table.FK_ID)}"
val joinThirdTable = "LEFT HASH JOIN $thirdTable " +
                "ON ${thirdTable.ID.eq(secondTable.FK_ID)}"
val joinfourthTable = "LEFT HASH JOIN $fourthTable " +
                "ON ${fourthTable.ID.eq(secondTable.ANOTHER_ID)} " +
                "AND ${fourthTable.DELETE_TIME.isNull}"
val fromStep = "$fromTable $joinSecondTable $joinThirdTable $joinfourthTable"

DSLContext.select(
	table.ID,
	table.NAME,
	secondTable.ID,
	secondTable.NAME,
	thirdTable.ID,
	thirdTable.NAME,
	fourthTable.ID,
	fourthTABLE.NAME
	)
	.from(fromStep)
	.fetch()
```

**Comment by lukaseder** [comment]
I see now.

Well, jOOQ doesn't know the contents of your template. How would jOOQ know what exactly in the template constitutes a "table"? jOOQ would have to be able to parse the template content, including any and all vendor specific syntax there is. But you're using plain SQL templating precisely because jOOQ *doesn't* support the syntax of interest, so we're comming full circle.

I'm assuming that the `${...}` syntax is kotlin string interpolation? I *strongly* recommend you don't do this. A rationale is given here:
https://blog.jooq.org/never-concatenate-strings-with-jooq/

While it is not too likely you run into a SQL injection vulnerability if you're only embedding jOOQ query parts, please note that:

- Suddenly you'll embed some other object, which isn't a `QueryPart`,  but user input, and you'll have a SQL injection vulnerability
- `QueryPart.toString()` renders SQL syntax using `SQLDialect.DEFAULT`, not your desired dialect. This may produce arbitrary SQL, which won't work on CockroachDB. Again unlikely for your simple examples, but as soon as you're using something more complex, you won't get the expected syntax.

Instead, why not just use jOOQ's own plain SQL template placeholder syntax?
https://www.jooq.org/doc/latest/manual/sql-building/plain-sql-templating/

This will take care of rendering the correct syntax for your dialect, and it will support schema mapping!

Take this example:

```java
println(ctx.selectFrom("{0}", T_BOOK));
ctx.settings().withRenderMapping(new RenderMapping().withSchemata(
    new MappedSchema().withInput(T_BOOK.getSchema().getName()).withOutput("FOO")
));
println(ctx.selectFrom("{0}", T_BOOK));
```

It prints something like:

```sql
select *
from "public"."t_book"
select *
from "FOO"."t_book"
```

Does this make sense? Let me know if I can be of any further help.

**Comment by trourance** [comment]
It makes a lot of sense. Thanks for the best practices course, btw.
