### ISSUE TITLE
Filter result by value of a nested field in multiselect

### ISSUE THREAD

**Issue by andreas-wirth** [jOOQ/jOOQ#15536]
### Your question

Hi, 
I have a database schema where one Foo record has a set of Bar records associated. 
Now I'm trying to fetch all Foo records that have at least one Bar record, map them to Java objects and paginate that.
Foos that have no Bars should not be included.
I came up with this construct using the multiset operator, however I'm stuck writing the condition:

```
final List<Foo> foos = getDslContext().select(
            FOO.ID,
            multiset(
                  select(
                        BAR.ID)
                        .from( BAR ).where( BAR.FOO_ID.eq( FOO.ID ) ) ) )
            .convertFrom( r -> r.map( mapping( Bar::new ) ) ) )
      .from( FOO ).where( <all Foos that have at least one Bar> )
      .orderBy( FOO.ID.asc() )
      .seek( cursor )
      .limit( limit )
      .fetch( Records.mapping( Foo::new ) );
```

Do you have any suggestion for the condition / other approach to fix this issue?

Thanks in advance!

### jOOQ Version

jOOQ Professional 3.18.4

### Database product and version

Azure SQL / MS SQL Server

**Comment by lukaseder** [comment]
I can totally understand, `MULTISET` is so cool, you would want to use it everywhere 😅

But for your case, perhaps just use plain old `EXISTS`?
https://www.jooq.org/doc/latest/manual/sql-building/conditional-expressions/exists-predicate/

I understand that this will produce the same join twice in some way (once through the `EXISTS` semi join and once through the `MULTISET` correlated subquery). If that turns out to be a performance issue (though it probably isn't), you have at least these options:

- Use an ordinary `INNER JOIN` and deduplicate things manually, "the old way". The `INNER JOIN` will provide you with the "at least one bar" semantics
- Wrap your query including the `MULTISET` in a derived table and implement a predicate on the `MULTISET` from the outer query. The predicate will have to be written in a way that it's `MULTISET` serialisation aware, i.e. you'll have to check the `XML` content.

I can help with specific follow-up questions you might have about the above.

**Comment by lukaseder** [comment]
Why repeat `FOO` in `EXISTS`? You don't need it. Just correlate the subquery:

```java
.from( FOO ).where( exists( selectOne().from( FOO ).where( BAR.FOO_ID.eq( FOO.ID ) ) ) )
```

Note that starting from jOOQ 3.19, there's a new feature called implicit path correlation:
https://www.jooq.org/doc/dev/manual/sql-building/sql-statements/select-statement/implicit-path-correlation/

It will allow you to express this correlation much more simply:

```java
.from( FOO ).where( exists( selectOne().from( FOO.bar() ) ) )
```
