### ISSUE TITLE
Add parser support for functions without parameter names

### ISSUE THREAD

**Issue by jhyot** [jOOQ/jOOQ#15627]
Tested on https://www.jooq.org/translate/

The following DDL leads to an error in jOOQ parser:

```sql
CREATE FUNCTION dup(int) RETURNS TABLE(f1 int, f2 text)
    AS $$ SELECT $1, CAST($1 AS text) || ' is text' $$
    LANGUAGE SQL
```

```
Data type expected: [1:24] CREATE FUNCTION dup(int[*]) RETURNS TABLE(f1 int, f2 text)
    AS $$ SELECT $1, CAST($1 AS text) || ' is t...
```

The example is taken directly from the Postgres manual: https://www.postgresql.org/docs/16/sql-createfunction.html

---

Also when trying to fix the parameter like the parser demands, another error occurs:
```sql
CREATE FUNCTION dup(input int) RETURNS TABLE(f1 int, f2 text)
    AS $$ SELECT $1, CAST($1 AS text) || ' is text' $$
    LANGUAGE SQL;
```

```
Unsigned integer literal expected: [1:46] CREATE FUNCTION dup(input int) RETURNS TABLE([*]f1 int, f2 text)
     AS $$ SELECT $1, CAST($1 AS text) || ' is text' $$
     LANG...
```

**Comment by lukaseder** [comment]
Thanks for your report.

I believe there's already a task somewhere to support unnamed parameters in PostgreSQL (possibly not parser specific). That part can be worked around by giving the parameter a name.

Adding support for table valued functions is already in this list:

- https://github.com/jOOQ/jOOQ/issues/14682

I'll keep this issue open to support unnamed parameters.

**Comment by lukaseder** [comment]
Btw: What's your use-case for using the parser to parse functions?

**Comment by jhyot** [comment]
> Btw: What's your use-case for using the parser to parse functions?

We wanted to use the `DDLDatabase` to generate jOOQ files from the Flyway scripts, and this was the first statement that it failed on.

I don't know if that would be even possible with functions (does H2 support functions?).

**Comment by lukaseder** [comment]
Well, you can ignore unsupported content, knowing that there will always be more unsupported content:
https://www.jooq.org/doc/latest/manual/code-generation/codegen-ddl/#ignoring-unsupported-content

> I don't know if that would be even possible with functions (does H2 support functions?).

Yes, but they work very differently, and there is no support for table valued functions. We will eventually be able to interpret the content parsed by the `DDLDatabase` in order to remove the dependency on H2:

- https://github.com/jOOQ/jOOQ/issues/7034

But that still means we have to be able to parse and represent everything in jOOQ's API

Why not just use testcontainers, instead?
https://blog.jooq.org/using-testcontainers-to-generate-jooq-code/

**Comment by jhyot** [comment]
> Why not just use testcontainers, instead?

Yeah, we have a nice working setup with Docker (without Testcontainers). We just wanted to see if e.g. DDLDatabase would speed up the build. But it doesn't seem worth it.

**Comment by lukaseder** [comment]
Looking into this now. Fun fact, the identifiers `$1` and `"$1"` are not the same thing:

```sql
create function x (int, "$1" int) returns int
as $$
  select "$1" + $1;
$$ language sql
```
