### ISSUE TITLE
Extended Jooq Pojos

### ISSUE THREAD

**Issue by muehmar** [jOOQ/jOOQ#15642]
### Use case

This is more just a question to get your opinion rather than an actual feature request.

We adjusted the generation of the (immutable) Pojos in a way I think is also actually the idea of Jooq:
 * A Pojo cannot be constructed without setting every property which is NOT NULL in the database, this is enforced during compile-time
 * A Pojo can also enforce setting all properties the table contains, this is also enforced during compile time which especially useful when mapping from a domain object.
 * Properties/Columns with a default in the database provide methods to explicitly choose the default
 * Identity columns provide methods to explicitly choose the generated value by the database
 * Nullable columns provide methods to explicitly set no value for this property
 * The getter of nullable properties wraps the value in an optional

I know your opinion about nullability and the optional class so some things might not of high interest for you. But I think some ideas might be interesting. All points except the last one are reached via a special builder pattern: When instantiating a builder, the returned builder class contains only methods for one property. When setting the current property, a new builder class is returned which only contains the setter methods for the next property. This way, one is able to enforce setting certain properties during compile time. Each builder class contains special method depending on the column/property.

E.g. builder for identity columns contains the following methods
```
public Builder id(Long id);

public Builder generatedId();

public Builder idOrGenerated(Optional<Long> id);
```
The builder for default columns provides
```
public Builder name(String name);

public Builder defaultName();

public Builder nameOrDefault(Optional<String> name);
```
And nullable columns
```
public Builder language(String name);

public Builder language(Optional<String> name);

public Builder noLanguage();
```

The Pojos are generated with the Column and ConstructorProperties Annotation to support the mapping back and forth to records generated by jooq.

We created now an internal library to generate these kind of Pojos independent of Jooq, as we already had problems when we adjusted the built in generator by Jooq when the records got copy constructors from the pojos and was not aware of our adjusted getters.

Are these things or ideas interesting for you and we should contribute in one way or the other to Jooq or possibly any other form of separate 'plugin'?

### jOOQ Version

3.17.5

### Database product and version

MariaDB 10.3

**Comment by lukaseder** [comment]
Thanks a lot for your message. This sounds a lot like the ideas expressed here (further down in the issue comments):

- https://github.com/jOOQ/jOOQ/issues/14566

Indeed, there are some benefits to creating ways of ensuring:

- All mandatory values are provided at construction time by `INSERT`
- No mandatory values are ever "unset" to `NULL` by `UPDATE`
- No readonly values are ever changed by `UPDATE`
- No generated values are ever set by `INSERT` or `UPDATE`

There are other properties, too. All the while it must continue to be possible to *partially load* a record for a later update, as we don't ever want to encourage `SELECT *` style querying.

I think that I will prioritise such ideas in a near-future version (e.g. jOOQ 3.20). I don't think that jOOQ will ever go down the rabbit hole of providing a builder implementation. For example, your idea relies on one type per column in the database. This is certainly not something jOOQ would want to offer out of the box. (Imagine 100000 builder types in a large schema of 1000s of tables with 100s of columns each!)

Though, there are precedents for it, sure, e.g.
https://immutables.github.io/immutable.html#staged-builder

As far as builders go, perhaps, the various feature requests requesting better third party annotation support in generated code could be useful. I.e. if a builder approach is desirable, then jOOQ could generate annotations on records / POJOs that users can then customise. This would also prevent any `Optional` bikeshed, for example, such as the one where `Optional` is accepted as an argument, which I wouldn't recommend.

So, to summarise:

- What jOOQ *wants* is a way to better stage data through the `INSERT` / `UPDATE` lifecycles, in order to encode mandatory/optional/readonly column properties in `Record` types (not necessarily POJO types). That would produce one type per *stage* as opposed to one type per *column* (and stage)
- What jOOQ *doesn't want* is express any opinion whatsoever regarding the "ideal" builder style. The only reason builders exist is because the Java language is lacking useful convenience features. Few people write builders in kotlin. This link is probably outdated, but at least for records, withers have been discussed, so *something* is on the radar of the Java spec folks: https://github.com/openjdk/amber-docs/blob/master/eg-drafts/reconstruction-records-and-classes.md


> Are these things or ideas interesting for you and we should contribute in one way or the other to Jooq or possibly any other form of separate 'plugin'?

I don't think such an implementation can make it into jOOQ. It's likely already *very* opinionated. Either it will stay opinionated, making 85% of users unhappy, or it will become configurable, and thus a nightmare to maintain.

But it's nevertheless great that you share your ideas here, so the ideas expressed by @apatrida in #14566 are validated once more, to increase priority of doing *something* in this area.

If you publish this (e.g. on Maven Central), I'll also happily advocate it here and there. You'll get more feedback, and I'll get more feedback as well, which would be great to make the right decisions for the aforementioned improvements.

**Comment by muehmar** [comment]
I'm impressed how fast you react to issues :-)

I know that what we built is heavily opinionated and that we only covered the cases whats useful and possible for our applications and actually I suspected that the answer would go into this direction but I thought I could not do any harm if I share what we have done to get you some feedback what at least some users might help. Thanks for your time anyway!
