### ISSUE TITLE
When generating Kotlin code `.withKotlinNotNullRecordAttributes(true)`, the field definitions on the corresponding generated table implementation are always nullable

### ISSUE THREAD

**Issue by cies** [jOOQ/jOOQ#15776]
### Use case

I know your ideas about `.withKotlinNotNullRecordAttributes(true)` not being perfect, but it works well for many and when it does not fit in a generated record (rarely in the jooq code I work on) we can always use RecordN.

I'm trying to upgrade from the Java generators (with the equally "unsound" `withNullableAnnotation(true)` and             `withNonnullAnnotation(true)` options switched on. Those options also do not add nullability info to the generated table implementation, only to the generated record.

Coming from Java while mostly using it from Kotlin, we ended up using Java's nullable types are "platform types" which kind of hides they are nullable in Kotlin (why this cannot be switch (or even default) to "safe" behavior is a mystery to me). Since I'm now trying to switch to the Kotlin code I thought I may be a good idea to add nullability specification to the table generator of Kotlin (`?` or not), and Java (as @NotNull/@Nullable annotations), and maybe Scala but I'm not aware of the situation there.

Maybe it's a completely nonsensical/not-feasible proposal.

I've tried, btw to implement this in a subclassed generator, but this have proven to be impossible for me as:

1. I cannot find where the actual "?" is added to the type in Kotlin generation of the field generation (which itself happens in `protected void generateUDT(UDTDefinition udt, JavaWriter out)`, and
2. I cannot overwrite `protected void generateUDT(UDTDefinition udt, JavaWriter out)` in a subclass since waaaay too much is private and currently called by super class' implementation of `protected void generateUDT(UDTDefinition udt, JavaWriter out)`.

### Possible solution

Options `withKotlinNotNullTableFieldDefinitions` (for Kotlin) and `withNullableAnnotationInTableFieldDefinitions` +             `withNonnullAnnotationInTableFieldDefinitions` (for Java) that allow putting the type hint already configurably available in generated Records also in table field definitions.

Alternatively extending the scope of the current options could also be possible (the Java generator options, `with*Annotation`, already cover in description the feature I'm requesting).

### Possible workarounds

There could be a override that I'm missing by which I can make *all* Koltin types render with "incorrect but apparently some people like it that way" nullability indication. :)

I can also keep using the Java generator for now.

I can also bite the bullet and ass the `!!` (double whammies) all over our jooq code.

I've not decided, as after just getting to the bottom of this I first wanted to share  my findings here.

But either way I think the "feature" of having Record/TableField types closely follow my database schema, and the benefits of that when using a modern IDE, is what attracts me --and probably many more-- to jOOQ (and Kotlin) in the first place. This feature request --as the unholy features I've already been using-- extends that core feature of your product.

### jOOQ Version

3.18.4 OSS

### Database product and version

MySQL

### Java Version

17

### OS Version

Linux

**Comment by cies** [comment]
If adding type information is possible at all, I wonder if the "ID" (fields with identity `true`) should also be exempt of nullability indicators for generated table definitions, like on Record classes.

**Comment by lukaseder** [comment]
Thanks for your suggestions.

https://github.com/jOOQ/jOOQ/issues/13999 already covers this discussion sufficiently, so I will close this as a duplicate.

Regarding your specific suggestions / workarounds / issues

> * I cannot find where the actual "?" is added to the type in Kotlin generation of the field generation (which itself happens in `protected void generateUDT(UDTDefinition udt, JavaWriter out)`, and

This isn't a pluggable feature in the code generation, so it's scattered across the code base. There simply hasn't been any need to factor it out, yet.

I'm curious why this would be about `generateUDT()` though. UDTs can't enforce non-nullability at all, so their attributes are always nullable.

> * I cannot overwrite `protected void generateUDT(UDTDefinition udt, JavaWriter out)` in a subclass since waaaay too much is private and currently called by super class' implementation of `protected void generateUDT(UDTDefinition udt, JavaWriter out)`.

You cannot override behaviour that has not been designed for overriding.

Knowing that jOOQ's code generator is just a fancy text based template, chances that there will be much more fine grained overriding options in the future are slim, because of the mess that would be created, and the ton of edge cases that would be overlooked.

> Options `withKotlinNotNullTableFieldDefinitions` (for Kotlin) and `withNullableAnnotationInTableFieldDefinitions` + `withNonnullAnnotationInTableFieldDefinitions` (for Java) that allow putting the type hint already configurably available in generated Records also in table field definitions.

See: https://github.com/jOOQ/jOOQ/issues/13999. It's really very unlikely this will ever ship.

> Alternatively extending the scope of the current options could also be possible (the Java generator options, `with*Annotation`, already cover in description the feature I'm requesting).

All of these things would make the code generator ever so complex! Imagine the amount of testing that would have to go into each combination of such flags, to compile something meaningful.

And despite all my warnings about this being wrong in a DSL like jOOQ (see again https://github.com/jOOQ/jOOQ/issues/13999), people would continue requesting "just one more little fix, I know I know this shouldn't but just one more."

> There could be a override that I'm missing by which I can make _all_ Koltin types render with "incorrect but apparently some people like it that way" nullability indication. :)

Define *all*. We'll have 50 flags in no time, and still, nobody would be happy.

People keep saying things like *"incorrect but apparently some people like it that way"* but I've been appeasing kotlin users for a while now, and I can promise you, either you, or someone else will *still* not be happy with whatever we ship here, simply because the problem doesn't have a *sound* solution in kotlin.

The *real* fix would be kotlin-denotable platform types:
https://youtrack.jetbrains.com/issue/KT-56899

The *best* workaround is to use the `JavaGenerator`.

> I can also keep using the Java generator for now.

Yes, why not? Such a pragmatic solution! :)

> I can also bite the bullet and ass the `!!` (double whammies) all over our jooq code.

That obviously sucks, but there's no better option.

> But either way I think the "feature" of having Record/TableField types closely follow my database schema, and the benefits of that when using a modern IDE, is what attracts me --and probably many more-- to jOOQ (and Kotlin) in the first place. This feature request --as the unholy features I've already been using-- extends that core feature of your product.

I can definitely understand that, and as I've said in the issues discussing the record / data class related code generation flags, they're special cases, because they model a 1:1 relationship with the underlying table itself, mostly useful for `CRUD`, in case of which there's a high probability (though not 100%) that the nullability promises are accurate.

This is not at all the case for the DSL in general.

But who knows, perhaps I will be talked into offering generating kotlin code for records and data classes, but Java code for tables and fields. I guess that would be the best way forward to get the best of both worlds. You can probably do this already by configuring 2 separate code generation runs, one for each type of object.

**Comment by cies** [comment]
As usual this for your, @lukaseder , quick and detailed reply. Much appreciated.

I've studied #13999 and, yes, this was a dupe. Strange I did not find it before writing this out.

> I'm curious why this would be about generateUDT() 

Because `generateUDT(UDTDefinition udt, JavaWriter out)` contains this bit of code:

```kotlin
            else if (kotlin)
                out.println("%sval %s: %s<%s, %s> = %s.createField(%s.name(\"%s\"), %s, this, \"%s\"" + converterTemplate(converter) + converterTemplate(binding) + ")",
                    visibility(), attrId, UDTField.class, recordType, attrType, UDTImpl.class, DSL.class, escapeString(attrName), attrTypeRef, escapeString(""), converter, binding);
            else
                out.println("%sstatic final %s<%s, %s> %s = createField(%s.name(\"%s\"), %s, %s, \"%s\"" + converterTemplate(converter) + converterTemplate(binding) + ");",
                    visibility(), UDTField.class, recordType, attrType, attrId, DSL.class, escapeString(attrName), attrTypeRef, udtId, escapeString(""), converter, binding);
```

Which is where the `val ... = createField(...)` statements get generated. I thought this may be a place I can extend the generator, but no luck (as you say: not designed to be extended upon).

> And despite all my warnings about this being wrong in a DSL like jOOQ (see again https://github.com/jOOQ/jOOQ/issues/13999), people would continue requesting "just one more little fix, I know I know this shouldn't but just one more."

:laughing: I was expecting a reaction like this. I agree it's good to keep it simple. And I agree actual correctness is a lofty guideline. I just must say that with the nullability info provided by the Java and Kotlin generators with those unholy options switched on, I much prefer to use it that way. I really want SQLs nullability visible in my IDE 99%+ of the time: it helps me write correct code.

As I understand from #13999, adding nullability info to table field declarations is opening more problems than adding nullability info to the Records. This I could not oversee (being merely a jooq user), hence: thank you for that insight.

> > There could be a override that I'm missing by which I can make all Koltin types render with "incorrect but apparently some people like it that way" nullability indication. :)

> Define all.

For now we just use 'm on Records and table field definitions. So I'd say those are all for me. But someone using POJO's may want them there too, so you are correct --again-- in that all is a slippery slope.

> The real fix would be kotlin-denotable platform types

I read the issue but have no clue what it is actually suggesting.

> The best workaround is to use the JavaGenerator.

And hide nullable types behind behaving-as-non-nullable "platform types" that blow up in my face upon use, at *runtime*? Maybe.

Maybe I use the Kotlin generator and add `!!`s (double whammies) and `?`s all over the code, to at least be honest about nullability.

> But who knows, perhaps I will be talked into offering generating kotlin code for records and data classes, but Java code for tables and fields. I guess that would be the best way forward to get the best of both worlds. You can probably do this already by configuring 2 separate code generation runs, one for each type of object.

All that just to hide the fact that table field definitions are nullable (but are rarely null) behind "platform types"? Not very appealing to me. Also using the generated java code with the nullability annotations gives me pretty much the same results (just without the default constructors, which to me -- a Bean spec hater -- are a horrible thing to begin with).

Thanks for your time. Good to know that I (1) cannot easily override this behavior, (2) you dont think it should be part of jooq, and (3) this is already discussed at length and is apparently more complicated than adding nullability info to Record.

Have a great day!

**Comment by lukaseder** [comment]
> Which is where the `val ... = createField(...)` statements get generated. I thought this may be a place I can extend the generator, but no luck (as you say: not designed to be extended upon).

Unless you're really into fixing UDTs, then as the method name suggests, this is the wrong place.

> > The real fix would be kotlin-denotable platform types
> 
> I read the issue but have no clue what it is actually suggesting.

It is suggesting to make the "platform type" (or whatever it will be called then), denotable in kotlin.

> Maybe I use the Kotlin generator and add `!!`s (double whammies) and `?`s all over the code, to at least be honest about nullability.

You can also try asking the other jOOQ users here: https://groups.google.com/g/jooq-user. Or if you tweet about this, I'll retweet for better reach.
