### ISSUE TITLE
Incorrect order of bound values

### ISSUE THREAD

**Issue by brettaufheber** [jOOQ/jOOQ#15782]
### Expected behavior

Please don't judge me for the strange looking query.

```
String queryRaw = "select ? as type, u.*, g.name as parent_group_name from _User u left outer join _User_Membership_Transitive mu on mu.member_user_id = u.id left outer join _Group g on g.id = mu.parent_group_id where ( lower('cn=myuser,ou=users,dc=crowd') = ? ) and ( u.active is null or u.active or ? = 'false' ) order by u.id";

org.jooq.Query query = DSL.using(connection).parser().parseQuery(queryRaw);

query.bind(1, "a");
query.bind(2, "b");
query.bind(3, true);
```

- The method "query.getBindValues()" should give a list with values in correct order.
- The method "query.getSQL()" should give a correct dialect specific SQL expression.

**Expected result:**

```
select cast(? as varchar) as type, u.*, g.name as parent_group_name from _user as u left outer join _user_membership_transitive as mu on mu.member_user_id = u.id left outer join _group as g on g.id = mu.parent_group_id where (lower('cn=myuser,ou=users,dc=crowd') = cast(? as varchar) and (u.active is null or u.active or cast(? as boolean) = 'false')) order by u.id
```

### Actual behavior

```
String queryRaw = "select ? as type, u.*, g.name as parent_group_name from _User u left outer join _User_Membership_Transitive mu on mu.member_user_id = u.id left outer join _Group g on g.id = mu.parent_group_id where ( lower('cn=myuser,ou=users,dc=crowd') = ? ) and ( u.active is null or u.active or ? = 'false' ) order by u.id";

org.jooq.Query query = DSL.using(connection).parser().parseQuery(queryRaw);

query.bind(1, "a");
query.bind(2, "b");
query.bind(3, true);
```

Same problem here:
```
query.bind("1", "a");
query.bind("2", "b");
query.bind("3", true);
```

The problem is, that parameter 2 and 3 are swapped what becomes obvious by calling "query.getBindValues()" and the method "query.getSQL()" shows the same behavior.

**Unexpected result:**

```
select cast(? as varchar) as type, u.*, g.name as parent_group_name from _user as u left outer join _user_membership_transitive as mu on mu.member_user_id = u.id left outer join _group as g on g.id = mu.parent_group_id where (lower('cn=myuser,ou=users,dc=crowd') = cast(? as boolean) and (u.active is null or u.active or cast(? as varchar) = 'false')) order by u.id
```

As you can see, the 2nd and 3rd cast using the incorrect type based on the wrong order of the parameters.

### Steps to reproduce the problem

I have tried many versions of JOOQ. This error could be in every version. Last version I tested is "3.18.7".

### jOOQ Version

org.jooq:jooq:3.18.7

### Database product and version

psql (PostgreSQL) 14.9 (Ubuntu 14.9-0ubuntu0.22.04.1)

### Java Version

17

### OS Version

Ubuntu 22.04.3 LTS

### JDBC driver name and version (include name if unofficial driver)

org.postgresql:postgresql:42.6.0

**Comment by lukaseder** [comment]
Thanks a lot for your message.

The `Query.bind()` methods may be a bit confusing indeed. Their main purpose is to allow for binding values to plain SQL templates, which are re-used, though even there, it's usually better to pass the bind values directly to the template, rather than binding them to the `Query` later on.

The `bind()` methods *can* be used with other types of queries, but it's often not a good idea because they bind values to the rendered bind value order, not the order of appearance in the expression tree, irrespective if that expression tree is constructed using the DSL or the parser. Not just can this lead to swapping, but also to repetition!

I've described this recently also here:
https://github.com/jOOQ/jOOQ/issues/15575#issuecomment-1715211457

This confusion is happening too often with users, hinting at an API design flaw, which might be addressed in the near future, probably via deprecation of the `bind()` methods. It's not trivial, because the same API design is also implemented for batch statements, where there aren't any other options.

Please note you can pass bind values directly to the parser API, in order to bind them to the placeholders in order of parse appearance:

```java
DSL.using(connection).parser().parseQuery(queryRaw, "a", "b", true)
```

**Comment by lukaseder** [comment]
I've created an issue to better document this on the `bind()` method Javadoc:

- https://github.com/jOOQ/jOOQ/issues/15783

**Comment by lukaseder** [comment]
N.B: I think this would be a useful question / answer also for https://stackoverflow.com/questions/tagged/jooq, for better visibility for other users...
