### ISSUE TITLE
custom classloader for oracle jar, and issue with TIMESTAMPTZ instance creation.

### ISSUE THREAD

**Issue by ravimergu1** [jOOQ/jOOQ#15780]
### Your question
I want to support different Oracle jars in my application. I have one jar in the main classloader, and if any Oracle jar is included, I will use a custom classloader. However, when I use the custom classloader, I encounter an issue with TIMESTAMPTZ. Here, jOOQ is creating TIMESTAMPTZ with the main classloader, but the connection object is with the custom classloader.

How can I create the TIMESTAMPTZ with my custom classloader? Is it possible to create the TIMESTAMPTZ instance with the connection object's classloader?

### jOOQ Version

JooQ 3.17.2

### Database product and version

Oracle

### Java Version

open Jdk 11

### OS Version

Ubuntu 18

### JDBC driver name and version (include name if unofficial driver)

oracle

**Comment by lukaseder** [comment]
Thanks for your message. That's an interesting problem. Why are you using such a custom class loader?

jOOQ used to use reflection to load ojdbc classes in the past, but that's no longer being done. The commercial distributions have a direct (optional) dependency on ojdbc. So, the default class loading mechanism of the JVM is used. If this doesn't trigger your custom classloader, then you likely have a bug in there. I don't think jOOQ needs to adapt and load such types in a specific way required by your very specific setup.

Note that `TIMESTAMPTZ` isn't the only ojdbc type loaded by jOOQ. As of jOOQ 3.19.0, these types are referenced from the sources:

<img width="309" alt="image" src="https://github.com/jOOQ/jOOQ/assets/734593/6c644893-44c4-4649-9e35-0aa93ed01973">

Since I don't think that jOOQ needs to adapt to your setup, I'm not sure what your question is, or how I can be of any further help?

**Comment by ravimergu1** [comment]
is there is any posibility to add a customBinding to jooq instead of using `DefaultBinding.DefaultOffsetDateTimeBinding`? so that may be i will set my own TIMESTAMPTZ.

**Comment by lukaseder** [comment]
Yes, that might help work around the issue.

**Comment by ravimergu1** [comment]
Thanks to know. How can i replace the DefaultBinding.DefaultOffsetDateTimeBinding, with my customBinding?

**Comment by lukaseder** [comment]
I'm assuming you've already checked this out?
https://www.jooq.org/doc/latest/manual/code-generation/codegen-advanced/codegen-config-database/codegen-database-forced-types/codegen-database-forced-types-binding/

What specific questions do you have?
