### ISSUE TITLE
[FR] Add "IS_NULL" to org.jooq.Comparator

### ISSUE THREAD

**Issue by GavinRay97** [jOOQ/jOOQ#15818]
### Use case

```kt
enum class Operator(val opName: String, comparator: org.jooq.Comparator) {
    EQ("eq", org.jooq.Comparator.EQUALS),
    NEQ("neq", org.jooq.Comparator.NOT_EQUALS),
    // ...
    IS_NULL("is_null", org.jooq.Comparator.IS_NULL)
}
```

### jOOQ Version

jOOQ 3.18

### Database product and version

N/A

**Comment by lukaseder** [comment]
Thanks for your suggestion.

All of the operators in that class are binary operators, so it's unlikely we'll suddenly add a unary operator to the list. In any case, the class stems from the early 1.0 days where such internal enums tended to leak to public API without much thought, so it's not likely it will receive too much attention like you're requesting.

Instead of requesting a specific "solution" to a problem that you're probably having, why not discuss the problem? The potential solution space is vast, and this doesn't look like a promising path to choose.
