### ISSUE TITLE
Using jOOQ with maven and other projects

### ISSUE THREAD

**Issue by MelleD** [jOOQ/jOOQ#15827]
### Your question

We are currently using the `org.jooq.pro` variant as a dependency in our Maven projects.
Other open source projects like Shedlock (see https://github.com/lukas-krecan/ShedLock/blob/master/providers/jdbc/shedlock-provider-jooq/pom.xml#L22) use `org.jooq`. Now we have both variants in the classpath.

How should open source projects integrate jOOQ so that there are no conflicts?

I would immediately think of `optional` or `provided` dependencies.

What is your recommendation?

### jOOQ Version

jOOQ Professional 3.18.4

### Database product and version

Azure SQL

**Comment by lukaseder** [comment]
Thanks for your message. That's an interesting question. In my opinion, there should only ever be one instance of jOOQ on the end user's classpath. While the different editions and distributions have different Maven `groupId` values (`org.jooq`, `org.jooq.pro`, `org.jooq.pro-java-8`, etc.), the packages are the same in order to minimise the impact if someone upgrades from the jOOQ Open Source Edition to the commercial ones. The commercial editions are drop-in replacements for the open source one, as APIs are source and binary compatible, at least in the upgrade case.

Your case isn't so much different from the one in Spring Boot, which publishes a compile time dependency on the `org.jooq` groupId. The recommended approach there is to exclude the dependency in user code, and provide your own one, if you want to work with the commercial distribution:
https://blog.jooq.org/how-to-use-jooqs-commercial-distributions-with-spring-boot/

That way, Spring Boot won't notice a thing (because at runtime, all it will see is the `org.jooq` package, not the Maven `groupId`). In short:

```xml
  <dependencies>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-jooq</artifactId>
     
      <!-- Exclude the jOOQ Open Source Edition -->
      <exclusions>
        <exclusion>
          <groupId>org.jooq</groupId>
          <artifactId>jooq</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
   
    <!-- Include a commercial jOOQ distribution -->
    <dependency>
      <groupId>org.jooq.trial</groupId>
      <artifactId>jooq</artifactId>
      <version>${jooq.version}</version>
    </dependency>
  </dependencies>
```

Perhaps, you can document this also in your project at https://github.com/lukas-krecan/ShedLock ?

> I would immediately think of `optional` or `provided` dependencies.

It's certainly not optional (I think?), but you can make it provided, indeed. That's another option, but it would add an additional step to *everyone's* setup, not just to commercial edition users.

**Comment by MelleD** [comment]
Hey @lukaseder 

thanks for the quick answer.

I know the spring boot way, but I have to say I don't like it because you then have to explicitly redefine the dependencies using the exclude in the pom and can no longer take the original from a bom or parent pom.
We have the same issue when we want to use Jetty instead of Tomcat in spring boot.

For this reason I may have considered whether `optional` or `provided` makes more sense. And you can simply set the concrete distribution from “outside”. I guess, the projects just need the right package to compile.

We also "only" use the project (shedlock), but would like to suggest a solution to the problem that would allow us to continue using the bom.

**Comment by lukaseder** [comment]
> We have the same issue when we want to use Jetty instead of Tomcat in spring boot.

I don't think Jetty is a drop-in replacement for Tomcat in the same way as the jOOQ commercial distributions are a drop-in replacement for the jOOQ Open Source Edition?

> And you can simply set the concrete distribution from “outside”.

It's still a hack from the Maven perspective, because you're replacing one `groupId` by another. Perhaps, if you added *both* as `provided` and `optional` (including also all the JDK specific distributions and the trials), you'd have a "clean" setup, though is that really better?

In any case, I can still only see 2 options:

- "Your way," i.e. *everyone* has to explicitly <ins>*add*</ins> a dependency
- "My way," i.e. 98% of jOOQ users can get things to work out of the box, the others have to  <ins>*replace*</ins> a dependency

I always recommend the latter, because it's way less support effort on my side.

**Comment by MelleD** [comment]
> I don't think Jetty is a drop-in replacement for Tomcat in the same way as the jOOQ commercial distributions are a drop-in replacement for the jOOQ Open Source Edition?

Looks similiar
https://docs.spring.io/spring-boot/docs/2.0.6.RELEASE/reference/html/howto-embedded-web-servers.html

```
         <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
            <version>${spring-boot-version}</version>
            <exclusions>
               <exclusion>
                  <groupId>org.springframework.boot</groupId>
                  <artifactId>spring-boot-starter-tomcat</artifactId>
               </exclusion>
            </exclusions>
         </dependency>
         <!-- Use Jetty instead -->
<dependency>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-jetty</artifactId>
</dependency>
```



> It's still a hack from the Maven perspective, because you're replacing one `groupId` by another.

Yes true, the "trick" just work cause of the same packages, but this is the idea of a "provided" dependency, right?

> I always recommend the latter, because it's way less support effort on my side.

Implicit dependencies also have some dangers. But if that's the recommendation, I can live with it.

**Comment by lukaseder** [comment]
> Looks similiar
> https://docs.spring.io/spring-boot/docs/2.0.6.RELEASE/reference/html/howto-embedded-web-servers.html

Well, I didn't mean what Spring Boot recommends doing, but how reasonable it is to do this... :)

> but this is the idea of a "provided" dependency, right?

I don't think jOOQ's case corresponds to the use-cases driving the design of `provided`. With `provided`, it can be reasonably assumed that the dependency is indeed already provided *somehow*, e.g. by an application server, so the depending library doesn't have to include it. See examples here:
https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#dependency-scope

Another reason may be licensing, i.e. when it is not allowed to ship the dependency with the depending library (e.g. some commercial JDBC drivers, or also, jOOQ), then this is also reasonable.

> Implicit dependencies also have some dangers. But if that's the recommendation, I can live with it.

Yes, the main danger is to accidentally pull the wrong dependency if the exclusion is forgotten, which may be detected only at runtime.

**Comment by MelleD** [comment]
> Well, I didn't mean what Spring Boot recommends doing, but how reasonable it is to do this... :)

I think spring boot has decided on this path and will do it that way for all depdencies.

> I don't think jOOQ's case corresponds to the use-cases driving the design of `provided`.

I would say it depends: If you have a fat jar and you deliver servers, there are different opinions.
