### ISSUE TITLE
PostgreSQL collation

### ISSUE THREAD

**Issue by losador** [jOOQ/jOOQ#15868]
### Your question

Hi, i need to add orderBy with collation to my query. I tried to use collate() method like this:
`query.addOrderBy(DSL.upper(stringColumnInfo.getField()).collate("sk-SK-x-icu"));` 
but in result i have my query looks like this:
`order by
  ((UPPER(TEST.TEST.NAME)) collate SK-SK-X-ICU)`
 what is wrong, because colaltion in postgre must be "sk-SK-x-icu".
 
 Also i have tried to use plain sql templates:
 `DSL.field("{0} collate \"{1}\"", field, collation),` 
 but it doesnt worked at all:
 `order by
  UPPER(TEST.TEST.NAME) collate "{1}"`.

Any suggestions?

### jOOQ Version

JOOQ Pro 3.18.7

### Database product and version

PostgreSQL 15

### Java Version

openjdk 20

**Comment by lukaseder** [comment]
Thanks for your message. By default, jOOQ creates a `Name` wrapper around your collation string, so it should be quoted. Maybe, you turned off quoting of identifiers? Your generated query seems to suggest so (`TEST.TEST.NAME` instead of `"TEST"."TEST"."NAME"`). Why did you turn this off?

The `RenderQuotedNames` flag has 4 values:

- `ALWAYS`
- `EXPLICIT_DEFAULT_QUOTED`
- `EXPLICIT_DEFAULT_UNQUOTED`
- `NEVER`

While `ALWAYS` and `NEVER` override all identifier styles, `EXPLICIT` define only how `DSL.name()` will be quoted, not `DSL.unquotedName()` and `DSL.quotedName()`.

So, I guess if you have a good reason to avoid quoting in general, you can enforce quoting here specifically using `DSL.quotedName("sk-SK-x-icu")`.

This works the same way for plain SQL templates. You'd have to pass the `Name` object to the template. You can't put template placeholders in string literals or identifiers.

**Comment by losador** [comment]
@lukaseder DSL.quotedName() worked for me, thank you
