### ISSUE TITLE
Single source of truth - natives in POJOs?

### ISSUE THREAD

**Issue by ryanhamilton** [jOOQ/jOOQ#15867]
### Use case

I have a java web apps that shuffles data between 3 states:

1. JSON - Receive from client.
2. Java - Process object
3. Database - Save object changes
4. JSON - Return updated Object to client.

```
    @Put("/")
    public MutableHttpResponse<User> update(@Body @Valid User user)  {
                       User u = database.get(user...)
                       doSomething(u);
                       return database.store(user);
    }
```
I can't seem to use the JOOQ POJOs nor find any elegant way to convert between all 3.

There's two problems I'm facing:
1. The JOOQ records can't be serialized. (https://github.com/jOOQ/jOOQ/issues/11203) .  So I can't send them back or forth.
2. The POJOs generated by JOOQ don't seem to generate natives e.g. getBoolean rather than isBoolean. So I have to write a lot messier code or find a way to "wrap it" all in one place.

### Option 1 Trying to use JOOQ POJOs
Success, the POJOs can be serialized but the no natives make it awkward.
For simple calls like ``user.isAdmin()``
I instead have to do ``user.getAdmin()==true`` despite the fact in the database it cannot be null.
I can't add ``user.isAdmin()`` as that breaks serialization.

### Option 2 Trying to use records

If you try to use JOOQs serialization or another, you have a different problem. Consider:

```
    @Put("/")
    public MutableHttpResponse<User> update(@Body @Valid User user)  {
```
It takes a user and returns the updated user. I could make it return a string instead but that string has to be entirely automatically reversable to User else the incoming argument back won't work. e.g. it would have to look like this:

```
    @Put("/")
    public MutableHttpResponse<String> update(@Body @Valid String userSt)  {
                    User u = convertFromString(userSt);
		    String s = JsonMapper.builder().addModule(new JavaTimeModule()).build().writeValueAsString(saved.intoMap());
                    return HttpResponse.created(s);
```

I lose all type signalling in the return and arguments, it also becomes very noisey and verbose.

- I understand Spring boot says, heh it's not our job to serialize your specialized format we only do POJOs
- and JOOQS position of heh we are not responsible for serialization only the database+java. Use intoMap().

### Option 3  - Write my own POJOS

With hibernate+jackson my great frustration was that it was java driven yet required me to hand write SQL for migration between table changes. The definition of my apps data was a mix of java _entity_ and _database_, the two could go out of sync. 

To me the beauty of JOOQ was:
1. Single source of truth, the _database_.
2. Type-safety
3. No new concepts to learn. JOOQ basically is SQL. (a stretch but much more true than hibernate).

However without serialization support or asking me to write POJOs to shuffle the data back and forth I don't have a single source of truth. I've shifted to _Database_ + _JSON_ (which may be driven by POJOS I write, therefore back to java). 
I also risk type-safety issues that will only be detected at runtime when conversion fails.

### Possible solution

A. Embrace better POJO generation that can be used for JSON generation and reasonable coding. At least native returns.
B. Type checking of user specified POJOs at compile time to provide type-safety. (this seems more fragile and troublesome than better generation).

### jOOQ Version

jOOQ-3.18.7

### Database product and version

H2

### Java Version

17

### OS Version

Windows

**Comment by lukaseder** [comment]
Thanks for your message.

This doesn't have any actionable feature requests, so I'm moving this to the support request milestone. It's still possible to derive *specific* feature requests in separate issues later, of course.

> 1. The JOOQ records can't be serialized. ([Returning jOOQ Record from Spring Boot @RestController doesn't work as expected #11203](https://github.com/jOOQ/jOOQ/issues/11203)) .  So I can't send them back or forth.

It should be possible to implement a custom serialiser, though? I don't know Spring Boot well enough, but it should be simple to extract all fields generically from all jOOQ records, no?

> 2\. The POJOs generated by JOOQ don't seem to generate natives e.g. getBoolean rather than isBoolean. So I have to write a lot messier code or find a way to "wrap it" all in one place.

I don't know what this is about *specifically*. JavaBeans allows both `getBoolean` and `isBoolean`, if I'm not mistaken. This doesn't seem to be a rabbit hole worth going down in jOOQ, `getBoolean` is fine. It has been for years now. If you think this should be `isBoolean` nonetheless, there are generator strategies to achieve that:

- https://www.jooq.org/doc/latest/manual/code-generation/codegen-generatorstrategy/
- https://www.jooq.org/doc/latest/manual/code-generation/codegen-matcherstrategy/

I don't know what you mean by "natives", though. Do you mean primitives? jOOQ cannot generate primitives for you without running into tons of other rabbit holes as well. It's the same story as with kotlin, only worse (because primitives currently still exist only for a select few types in Java, and they don't work well at all with generics, though that will change with Valhalla). See:

- https://github.com/jOOQ/jOOQ/issues/13999
- https://github.com/jOOQ/jOOQ/issues/74
So, this won't change soon.

> I instead have to do `user.getAdmin()==true` despite the fact in the database it cannot be null.

If you *know* the value won't be `null`, then why not just rely on auto unboxing? In fact, you already do. Your code will NPE in case `user.getAdmin() == null`. Check this out:

```
jshell> Boolean b = null
b ==> null

jshell> b == true
|  Exception java.lang.NullPointerException: Cannot invoke "java.lang.Boolean.booleanValue()" because "REPL.$JShell$11.b" is null
|        at (#2:1)
```

> I lose all type signalling in the return and arguments, it also becomes very noisey and verbose.
> 
> * I understand Spring boot says, heh it's not our job to serialize your specialized format we only do POJOs
> * and JOOQS position of heh we are not responsible for serialization only the database+java. Use intoMap().

Pretty much, yes. It's a good thing that no one tries to repeat the terrible mistakes of early Java, making serialisability a default behaviour out of the box.

Though, I don't really understand what you mean by "signalling," or "noisey and verbose"

> A. Embrace better POJO generation that can be used for JSON generation and reasonable coding. At least native returns.

This is very vague, and thus not actionable.

> B. Type checking of user specified POJOs at compile time to provide type-safety. (this seems more fragile and troublesome than better generation).

This, I simply don't understand, I'm afraid...

**Comment by lukaseder** [comment]
> Is there a post somewhere with the rabbit holes this caused?

It didn't cause rabbit holes, it *would*. This was never implemented. I think I've laid out all of the reasons, including links with in-depth discussions? It's no different from the kotlin case.

> My frustration is that the benefit of JOOQ is type safety generated from database, yet here it is not using the "NOT NULL".

Yeah, but you didn't think this through. Please check out the various discussions linked from the above link. Here it is again: https://github.com/jOOQ/jOOQ/issues/13999. The point of this issue is to give folks like you an entry point to the rabbit hole, so please read it.

Even in kotlin, nullability can't be guaranteed by jOOQ, far less so in Java.

> I'm trying to convert a 1 year long code base and this has been the main stumbling block that prevents me removing most my POJOs. Perhaps I'm wrong as I've only really just started using JOOQ. I will go learn some more.

I think you might have more *specific* feature requests soon. Things are the way they are for good reasons, so it's unlikely that a simple solution has been overlooked on a high level. But small improvements are always possible, or maybe, there's a feature like the generator strategies, that you're simply unaware of.
