### ISSUE TITLE
Implicit path correlation shouldn't generate correlation predicate if correlation isn't in scope

### ISSUE THREAD

**Issue by Spikhalskiy** [jOOQ/jOOQ#15967]
### Expected behavior

We have the following simple jOOQ query that works correctly in jOOQ 3.18.x:

```kotlin
private val deliveries = DELIVERIES.`as`("all_deliveries")
private val deliveryAddresses = deliveries.deliveryAddresses() .`as`("all_delivery_addresses")

transaction.select(*deliveryAddresses.fields()).from(deliveryAddresses).fetchInto(deliveryAddresses)
```

Note: the implicitly joined table is in both `select` and `from` clauses

### Actual behavior

With jOOQ 3.19.0 the following exception fires:

```
12:34:28.457 [DefaultDispatcher-worker-5 @coroutine#35] ERROR PostgresExtensions - Postgres query failed due to uncategorized client error
org.jooq.exception.DataAccessException: SQL [select "all_delivery_addresses"."id", <more all_delivery_addresses clumns> from "company"."delivery_addresses" as "all_delivery_addresses" where "all_deliveries"."delivery_address_id" = "all_delivery_addresses"."external_id"]; ERROR: missing FROM-clause entry for table "all_deliveries"
```

So the presence of the implicit join in `SELECT` and `FROM` doesn't lead to the source table of the join being added to that FROM clause, while it's referenced in WHERE.

### Workaround for jOOQ 3.19.0:
Both of these queries works:
```kotlin
transaction.select(*deliveryAddresses.fields()).from(deliveryAddresses, deliveries).fetchInto(deliveryAddresses)

transaction.select(*deliveryAddresses.fields()).from(deliveries).fetchInto(deliveryAddresses)
```

### jOOQ Version

3.19.0

### Database product and version

PostgreSQL 15

**Comment by lukaseder** [comment]
Thanks for your report.

This is due to jOOQ 3.19 having added support for explicit path joins and join path correlations:

- https://www.jooq.org/doc/3.19/manual/sql-building/sql-statements/select-statement/explicit-path-join/
- https://www.jooq.org/doc/3.19/manual/sql-building/sql-statements/select-statement/implicit-path-correlation/

The issue here is that there's an assumption that a path has its root declared on some scope level by default. I.e. when you use your query as a subquery, and the outer query declares  `DELIVERIES`, then the rendered SQL makes sense. But to maintain backwards compatibility, the predicate must be omitted if the root isn't declared in the current scope.

Why did you write your query this way? I.e. what's the point of using a path, when you could have just used the `DELIVERY_ADDRESSES` and omitted the `DELIVERIES` table?

**Comment by lukaseder** [comment]
The fix will avoid placing the predicate to a hypothetical outer correlation, if that isn't in scope. But I really do wonder what other kinds of queries you may have written with paths in the `FROM` clause. This was never supported or tested, in the past, until 3.19...

**Comment by lukaseder** [comment]
Fixed in versions:

- 3.20.0
- 3.19.1 (https://github.com/jOOQ/jOOQ/issues/15971)

**Comment by Spikhalskiy** [comment]
@lukaseder Because we want to select delivery addresses for existing deliveries only, not all addresses.
And I understand that it's technically more correct to write `transaction.select(*deliveryAddresses.fields()).from(deliveries).fetchInto(deliveryAddresses)` here because the implicit joint is for use in the select part of the query. But `transaction.select(*deliveryAddresses.fields()).from(deliveryAddresses).fetchInto(deliveryAddresses)` flows and reads better and it worked.

**Comment by lukaseder** [comment]
> flows and reads better and it worked.

But it didn't. Have you checked if your filter actually worked? There's no join being generated, if you completely omit `deliveries`!

**Comment by Spikhalskiy** [comment]
@lukaseder This code has been in production for a long time and is covered by unit tests quite a bit. But maybe it was returning all the delivery addresses and was able to flight under the radar... Let me check.

**Comment by Spikhalskiy** [comment]
@lukaseder Yes, you are right. It's pretty much the same as the selection from the delivery addresses. I didn't realize that, I thought an implicit join in from leads to the generation of a join.

**Comment by lukaseder** [comment]
> Yes, you are right. It's pretty much the same as the selection from the delivery addresses. I thought an implicit join in from leads to the generation of a join, but instead, it leads to having just a target of the implicit join in the clause

Well, the behaviour wasn't defined before 3.19, so it did something "arbitrary." Path references only generate their alias and try to left-join themselves to the path root. But there is not explicit path root in your query, nor was the behaviour of putting paths in the `FROM` clause defined, so that's what you got. In fact, your workaround where you put both in the `FROM` clause: `from(deliveryAddresses, deliveries)` would not have worked in jOOQ 3.18.

> Which can totally be an expected behavior here too.

Well, now, with this issue fixed, the behaviour is defined retroactively. My preference would have been to throw an exception for undefined path roots, but that's way too late to retrofit now, given that people may have written queries like yours since jOOQ 3.11.
