### ISSUE TITLE
Expose cardinality in Path interface

### ISSUE THREAD

**Issue by alf** [jOOQ/jOOQ#16019]
### Use case

I’m generating some documentation from our jOOQ-generated internal library. This documentation is intended for people who configure our GraphQL mapping, so I want to give as much relevant info as possible about what fields and paths are available from a given table.

Informing the user about whether following the path will give `0-1`, `1`, `0-*` or `1-*` would be very nice.

I believe I can figure out much of this by accessing fields in TableImpl, however this isn’t ideal. An official API would be better. 

### jOOQ Version

3.19.1

### Database product and version

Oracle 18 XE

**Comment by lukaseder** [comment]
Thanks for your feature request, @alf. 

There had been some considerations regarding the encoding of the direction of the relationship in types, see "A previous idea was to label the classes `[TableClassName]Path` where `[Direction]` is either `Parent` or `Child`" in:

- https://github.com/jOOQ/jOOQ/issues/15005

Note that we can only know about directions, not cardinalities. I don't think you can derive any implied `0-*` vs `1-*` semantics from SQL's meta data.

Now, the idea was rejected (for now), because it seemed like overengineering at the time, at least if we make this a code generation feature. Making meta data available at runtime (not as types but as simple methods) is different.

But what would you expect from `Path`? A `Path` is only available *after* you've navigated the path, e.g. `BOOK.author()` is a path from book->author. And in fact, it is represented by a subclass of `Author`, so it's more than just the path. It's also the target table. This is because `Path` is more of a `DSL` type than a meta data type, being useful for `join(Path)` calls, which don't require an `ON` clause (that's the only reason why it was introduced! See https://github.com/jOOQ/jOOQ/issues/15005)

But what you're looking for is a way to ask `BOOK` about what paths it has, no? So, why not just use `Table.getReferences()` (to-one paths) and `Table.getKeys()` and then `UniqueKey.getReferences()` (to-many paths)? This information has been available in jOOQ forever. All you have to do now is reverse engineer the name of the path method based on the constraints you discover this way.

So, my intuition here is that you already have all the tools you need for your specific task, via public API. There might be room for improvement, but I don't have a clear picture yet. I don't think what you need belongs on the `Path` type.

**Comment by lukaseder** [comment]
(I've closed this because I don't think it's necessary. But I can reopen if I'm overlooking something)

**Comment by alf** [comment]
I’m fine with your help here. Your pointers give me the public APIs to build what I need. Regarding cardinalities I believe I can come a long way by comparing the foreignKeyFields with unique constraints and nullability.

It probably won’t be perfect, but for my needs it should suffice.

**Comment by lukaseder** [comment]
> Regarding cardinalities I believe I can come a long way by comparing the foreignKeyFields with unique constraints and nullability.

I see, you mean if there's a unique constraint on the foreign key? That would give you the maximum cardinality of `1` on the child entity when navigating from the parent, indeed, though you wouldn't be able to derive a `1-1` relationship from that alone. A parent could still exist without a child, unless you have foreign keys in both directions?

In any case, let me know if you find there's any other meta information or convenience missing. For example, paths aren't currently formally available from meta data outside of generated code. I'd like to offer this auxiliary API in the future:

- https://github.com/jOOQ/jOOQ/issues/15645

I don't have a clear picture of all the requirements yet, so if you have any needs, that would probably help.
