### ISSUE TITLE
Please deprecate `...Into` methods

### ISSUE THREAD

**Issue by oliveryasuna** [jOOQ/jOOQ#16104]
I have seen many developers over the years make the mistake of using `...Into` methods, such as `fetchInto`.

For example:

```java
dsl.select(...).fetchInto(MyPojo.class);
```

I propose that this is a horrible choice.

1. If you change the query without changing the POJO, you can break the code.
2. If you change the POJO without changing every query that uses it, you can break the queries that you did not change. Often, you will not notice this until it is too late.
3. It requires reflection, which is inherently slow.
4. jOOQ has to iterate all constructors and their parameters to find a match. `O(n^2)`.

Personally, I feel that these methods are dangerous for developers and should be deprecated.

**Comment by lukaseder** [comment]
Thank you for your suggestion.

Obviously, we're not going to deprecate, let alone remove, such a central feature of jOOQ "just like that," because someone says "it's horrible." We're not going to impose a "holy war" of statically typed vs dynamically typed languages upon our users now.

While I personally prefer the type safe alternatives as well, and always use that in blog posts, stack overflow answers, demos, etc., a lot of jOOQ users prefer the reflection approach simply because it's more convenient, at the price of type safety.

Now, you're free to impose your preference upon your team by implementing a `RecordMapperProvider` that just fails every time it is invoked:
https://www.jooq.org/doc/latest/manual/sql-execution/fetching/pojos-with-recordmapper-provider/

Or you can use a static code analysis tool and add rules forbidding the use of "bad" API.

> 1. If you change the query without changing the POJO, you can break the code.

Yes that's correct. It's everyone's own personal choice to make.

People work with Spring all the time, annotating their beans, trusting that everything is configured correctly at runtime without any sensible compile time checking as well. A lot of people prefer things to be more explicit and type checked, but not everyone does.

People do the same thing with XML or JSON binding. The documents are inherently type unsafe, and while XSD or JSON schema can help define types, everyone can patch the documents in any way they want.

Even jOOQ is not 100% type safe. The compiler cannot type check the semantics of a query, e.g. this compiles, but is clearly wrong:

```java
ctx.select(BOOK.ID) // BOOK isn't defined in this query
   .from(AUTHOR)
   .fetch();
```

Everything is a tradeoff.

> 2\. If you change the POJO without changing every query that uses it, you can break the queries that you did not change. Often, you will not notice this until it is too late.

Well, again, people choose convenience over type safety, so they are well aware of this tradeoff.

> 3\. It requires reflection, which is inherently slow.

Surely, you've benchmarked this? I cannot confirm any problems of reflection's runtime performance (e.g. `invoke()` calls), but since you seem very certain of this, you probably have data to back up your claim?

> 4\. jOOQ has to iterate all constructors and their parameters to find a match. `O(n^2)`.

jOOQ does this exactly once per `RecordType` / `Class<E>` pair, then stores the result in a cache in the  `Configuration`. Again, you obviously have data to back this claim, so I'm curious about what you can share here. There's always a bug / cache miss worth fixing.

Note that you can't just say `O(n^2)` because there are 2 nested loops. It is unlikely that your POJOs have 100s of constructors, and in a well designed schema, it is also not too likely for a POJO (or query) to have 100s of columns, though I'm willing to accept that there are exceptions for the latter.

In any case, unless there are very obvious flaws as indicated by benchmarks and profiling sessions, I'm willing to bet that these things tend to be immaterial compared to the query execution speed on the RDBMS.
