### ISSUE TITLE
Feedback about manual section "codegen-liquibase"

### ISSUE THREAD

**Issue by oberstrike** [jOOQ/jOOQ#16222]
### The documentation URL

https://www.jooq.org/doc/latest/manual/code-generation/codegen-liquibase/

### Feedback

It works everything like in the docu but when I have a jsonb column in one of my changelogs it fails because it doesnt know that type. I think it uses default the H2 dialect wich doesn't support jsonb as column. How can I set the dialect of the LiquibaseDatabase to postgres? The jdbc driver is set to org.postgresql.Driver. I assume that he gets ignored because jooq first reads the changelogs and fails there.

**Comment by lukaseder** [comment]
Thanks for your message.

The `LiquibaseDatabase` is what it is. A simple "simulation" of your Liquibase migration. The fact that H2 is being used behind the scene is an implementation detail with its limitations. It's just a quick (and "dirty") approach to simple database migrations. As soon as you use any vendor specific features, you're much better off setting up an actual PostgreSQL database yourself. While `LiquibaseDatabase` could offer such things out of the box, we'd never finish adding more and more configuration flags to it

Rather than expecting jOOQ's `LiquibaseDatabase` to do that for you, why not just use the approach documented here:
https://blog.jooq.org/using-testcontainers-to-generate-jooq-code/

The example shows using Flyway, but it will work the same way with Liquibase. It's really quite simple...

**Comment by lukaseder** [comment]
I'll add a remark to the manual about this, since this is a frequent question.

**Comment by oberstrike** [comment]
Thank you for your fast response!
