### ISSUE TITLE
Wrong alias generated when aliased multiset is placed inside of ROW

### ISSUE THREAD

**Issue by mrclrchtr** [jOOQ/jOOQ#16309]
### Your question

Hi,

I am trying to write a query (Kotlin) with which I can get a "container" from the DB. It has "Content" and "Content" has "LevelEvents". So I need to use nested queries. I have built the following. Unfortunately it doesn't work and I don't understand why... is what I have in mind even possible? 

Code:
```kotlin
private fun createSelectAllContainersQuery(containerId: Int): Container {
    return dsl.select(
      CONTAINER.CONTAINER_ID,
      CONTAINER.CONTAINER_TYPE_ID,
      select(
        row(
          CONTENT.CONTENT_ID,
          multiset(
            select(
              CONTENT_LEVEL_EVENT.CONTENT_LEVEL_EVENT_ID,
              CONTENT_LEVEL_EVENT.EVENT_TYPE,
              CONTENT_LEVEL_EVENT.VOLUME,
              CONTENT_LEVEL_EVENT.TIMESTAMP
            ).from(CONTENT_LEVEL_EVENT)
              .where(CONTENT_LEVEL_EVENT.CONTENT_ID.eq(CONTENT.CONTENT_ID))
          ).`as`("levelEvents").convertFrom {
            it.map { record ->
              Content.LevelEvent(
                eventType = checkNotNull(record.value2()),
                volume = checkNotNull(record.value3()),
                timestamp = checkNotNull(record.value4()),
              )
            }
          }.`as`("levelEvents")
        )
      ).from(CONTENT)
        .where(CONTENT.CONTENT_ID.eq(CONTAINER.CONTENT_ID))
        .asField<Content>("content")
    ).from(CONTAINER).where(CONTAINER.CONTAINER_ID.eq(containerId))
      .fetchSingleInto(Container::class.java)
  }
```

Error:
```
PSQLException: ERROR: column "levelEvents" does not exist
```

Thank you very much!

### jOOQ Version

3.19.1

### Database product and version

16.2

### Java Version

21

**Comment by lukaseder** [comment]
Thanks for your message. This is due to your using an aliased `Field` within a `Row` expression. Think about what you want this to mean:

```kotlin
val c = SOME_COLUMN.as("c")
val r = row(c)
val s = select(c, r)
```

In the above example, `c` is used twice:

- in `row(c)`, where the alias is *referenced*
- in `select(c, ..)` where the alias is *declared*

But you seem to have had something entirely different in mind. You probably just wanted to give a name to the `MULTISET` expression, perhaps for debugging purposes, or because you copied the expression from a different query, where you exported the JSON?

In any case, a field alias can only ever be:

- Declared (in `SELECT`)
- Referenced (everywhere else)

You can see the problem when you log the query output. It will generated something like `row("content"."content_id", "levelEvents")

This is also explained here:

- https://www.jooq.org/doc/latest/manual/sql-building/queryparts/declaration-vs-reference/

If in doubt, always try the above trick with assigning expressions to local variables to clarify what they really mean. The fact that you can chain things with `as` doesn't mean that jOOQ can still make sense of what you meant to do.

**Comment by lukaseder** [comment]
(The solution is to remove both `as` calls)

**Comment by mrclrchtr** [comment]
Thank you very much.

Unfortunately, that was not quite the solution.

With your help I changed it to:

```kotlin
return dsl.select(
      CONTAINER.CONTAINER_ID,
      CONTAINER.CONTAINER_TYPE_ID,
      select(
        row(
          CONTENT.CONTENT_ID,
          multiset(
            select(
              CONTENT_LEVEL_EVENT.CONTENT_LEVEL_EVENT_ID,
              CONTENT_LEVEL_EVENT.EVENT_TYPE,
              CONTENT_LEVEL_EVENT.VOLUME,
              CONTENT_LEVEL_EVENT.TIMESTAMP
            ).from(CONTENT_LEVEL_EVENT)
              .where(CONTENT_LEVEL_EVENT.CONTENT_ID.eq(CONTENT.CONTENT_ID))
          ).convertFrom {
            it.map { record ->
              Content.LevelEvent(
                eventType = checkNotNull(record.value2()),
                volume = checkNotNull(record.value3()),
                timestamp = checkNotNull(record.value4()),
              )
            }
          }
        ).convertFrom { record ->
          Content(
            contentId = checkNotNull(record.value1()),
            levelEvents = checkNotNull(record.value5())
          )
        }
      ).from(CONTENT)
        .where(CONTENT.CONTENT_ID.eq(CONTAINER.CONTENT_ID))
        .asField<Content>(),
    ).from(CONTAINER)
      .fetchInto(Container::class.java)
```

It does not fail with any error, but the "Content" is now `null`.

**Comment by lukaseder** [comment]
`Content` could be `null` if your correlated subquery doesn't produce any rows, but since `CONTAINER` to `CONTENT` is a to-one relationship, why even use a correlated subquery? You could move that `row()` to the top level.

Also, `levelEvents = checkNotNull(record.value5())` doesn't look right. You don't project 5 values, so either you simplified the example (introducing compilation errors), or there's something wrong there.

I'll be happy to have a closer look at a complete reproducer. We have a template here to create such reproducers: https://github.com/jOOQ/jOOQ-mcve

**Comment by mrclrchtr** [comment]
Yes, I simplified the example and removed some not relevant fields.

But I just fixed it 🥳:

```kotlin
 return dsl.select(
      CONTAINER.CONTAINER_ID,
      CONTAINER.CONTAINER_TYPE_ID,
      multiset(
        select(
          CONTENT.CONTENT_ID,
          multiset(
            select(
              CONTENT_LEVEL_EVENT.CONTENT_LEVEL_EVENT_ID,
              CONTENT_LEVEL_EVENT.EVENT_TYPE,
              CONTENT_LEVEL_EVENT.VOLUME,
              CONTENT_LEVEL_EVENT.TIMESTAMP
            ).from(CONTENT_LEVEL_EVENT)
              .where(CONTENT_LEVEL_EVENT.CONTENT_ID.eq(CONTENT.CONTENT_ID))
          ).`as`("levelEvents").convertFrom {
            it.map { record ->
              Content.LevelEvent(
                eventType = checkNotNull(record.value2()),
                volume = checkNotNull(record.value3()),
                timestamp = checkNotNull(record.value4()),
              )
            }
          }
        ).from(CONTENT)
          .where(CONTENT.CONTENT_ID.eq(CONTAINER.CONTENT_ID))
      ).`as`("content").convertFrom { record ->
        Content(
          contentId = checkNotNull(record[0].value1()),
          levelEvents = checkNotNull(record[0].value2())
        )
      },
      select(CONTAINER_LOCATION.AREA_ID)
        .from(CONTAINER_LOCATION)
        .where(CONTAINER_LOCATION.CONTAINER_ID.eq(CONTAINER.CONTAINER_ID))
        .asField<Int?>("areaId"),
    ).from(CONTAINER)
     .fetchInto(Container::class.java)
```
This one is working as expected, but I think it's not optimal yet. I will try to use your tips and use row() in the top level.

**Comment by lukaseder** [comment]
Great to hear!
