### ISSUE TITLE
Memory leak in DefaultCacheProvider when large amounts of arbitrary projections are mapped with DefaultRecordMapper

### ISSUE THREAD

**Issue by nkmakinen** [jOOQ/jOOQ#16315]
### Expected behavior

Hello,

I suspect there might be a memory leak in jOOQ when calling a routine with a varying argument value and mapping the result to a custom type.

Here's a sample code it can be reproduced with (this is from my mcve):
```
data class Result(val value: Long)

val argument = Random.nextLong()
val procedure = org.jooq.mcve.kotlin.postgres.routines.references.foo(argument)
val select = ctx().select(procedure)
select.fetchOneInto(Result::class.java)
```

SQL function:
```
CREATE FUNCTION mcve.foo(arg bigint) RETURNS bigint
    RETURN 1::bigint;
```

Everytime that piece of code is ran a new instance of `org.jooq.whatever.routines.Foo` will be created and the GC does not seem to clean them up. However, if `fetchOneInto` is replaced with `fetchOne` the GC cleans up Foo instances. Also, weirdly this issue seems to exist only when calling the routine with a different argument.

### Actual behavior

Expect the GC to clean up the routine instances.

I use JProfiler so here's a screenshot right after running the GC (routine was called ~100 times before this with a different argument):
![Screenshot from 2024-02-20 19-37-24](https://github.com/jOOQ/jOOQ/assets/38182322/b89ddafa-638f-4302-8c5a-887a364f44ac)

### Steps to reproduce the problem

Here's my MCVE (kotlin/postgres): https://github.com/nkmakinen/jOOQ-mcve-mem-leak
The sample code can be found in the file `jOOQ-mcve-kotlin-postgres/src/test/kotlin/org/jooq/mcve/test/kotlin/postgres/KotlinTest.kt`

Let me know if something else is needed. I'll be happy to do some extra testing.

### jOOQ Version

3.19.3 OSS

### Database product and version

PostgreSQL 42.6.0

### Java Version

openjdk version "17.0.9" 2023-10-17

### OS Version

Linux Mint 21.2

### JDBC driver name and version (include name if unofficial driver)

org.postgresql:postgresql:42.6.0

**Comment by lukaseder** [comment]
Thanks for your message. I've attached VisualVM to your MCVE's process and can confirm the allocation counter for this type keeps increasing:

![image](https://github.com/jOOQ/jOOQ/assets/734593/c526bc2d-80d0-4e25-abdf-619f676e20b0)

The reason seems to be the `DefaultCacheProvider`, which simply uses a `ConcurrentHashMap` without bounds to cache `DefaultRecordMapperProvider` behaviour. The assumption here was that `RowType -> Class` pairs would be limited as most `RowType` instances are made from a constant number of expressions based on generated code. But in your MCVE, you're using a random number as an argument to a function, so the cache will always miss.

If you always pass `1L` as an argument, then the leak doesn't manifest in this way. As a workaround, you can supply an alternative `CacheProvider` implementation that uses a `LRUCache` of some sort, or one that doesn't cache things at all.

**Comment by lukaseder** [comment]
I'll use the `LRUCache` that we already have. It will have a fixed size of `8192` for now. Starting from jOOQ 3.20, this size can be adapted:

- https://github.com/jOOQ/jOOQ/issues/16696

Alternatively, users can provide a different `CacheProvider` implementation.
