### ISSUE TITLE
Regression: Gradle plugin thinks it's up to date when it's not

### ISSUE THREAD

**Issue by axelfontaine** [jOOQ/jOOQ#16316]
### Expected behavior

The `jooqCodegen` task should run when the database or the underlying Flyway migrations have changed.

### Actual behavior

The `jooqCodegen` task doesn't run after the Flyway migrations have been updated.

### Steps to reproduce the problem

The following `build.gradle.kts` snippet defines the relationship between various tasks:

```kotlin
val flywayMigrate = tasks.named("flywayMigrate") {
    dependsOn += tasks.named("processResources")
}
val jooqCodegen = tasks.named("jooqCodegen") {
    dependsOn += flywayMigrate
}
tasks.named("compileKotlin") {
    dependsOn += jooqCodegen
}
```

With jOOQ 3.19.3 the `jooqCodegen` task gets reexecuted as expected when Flyway has updated the database.

With jOOQ 3.19.4, this is no longer the case and one must add `outputs.upToDateWhen { false }` to the `jooqCodegen` task configuration for things to work.

This is most likely due to https://github.com/jOOQ/jOOQ/issues/16275

The previous behavior was running the up-to-date check too often and now it is clearly not doing it at all anymore, resulting in the lack of execution altogether.

A perfect fix may not be easy as it involves discovering arbitrary structural DB changes. If no good solution comes up, the  `outputs.upToDateWhen { false }` should probably be documented in the manual as this is a very common scenario.

### jOOQ Version

3.19.4

### Database product and version

PostgreSQL 15.3

### Java Version

openjdk version "21.0.1" 2023-10-17 LTS

### OS Version

Microsoft Windows [Version 10.0.22631.3007]

### JDBC driver name and version (include name if unofficial driver)

org.postgresql:postgresql:42.7.1

**Comment by lukaseder** [comment]
Thanks for your report. This isn't necessarily a "regression," as the previous behaviour was wrong.

The change is indeed due to:

- https://github.com/jOOQ/jOOQ/issues/16275

> The previous behavior was running the up-to-date check too often and now it is clearly not doing it at all anymore, resulting in the lack of execution altogether.
>
> A perfect fix may not be easy as it involves discovering arbitrary structural DB changes. If no good solution comes up, the `outputs.upToDateWhen { false }` should probably be documented in the manual as this is a very common scenario.

I'm mostly interested in perfect fixes, though. Because since I've added gradle support, I've been feeling like this:

![image](https://github.com/jOOQ/jOOQ/assets/734593/25ff933e-0726-4c38-945a-67ba69c48800)

People have many expectations and it all seems caused by the fact that Gradle is much more messy than Maven, which standardises everything.

If you look at what the previously recommended third party plugin does:

https://github.com/etiennestuder/gradle-jooq-plugin/blob/807a4139673df971ed68864cc155f73467723a68/src/main/groovy/nu/studer/gradle/jooq/JooqGenerate.java#L108

It relies on such a weird hack:

```java
allInputsDeclared = objects.property(Boolean.class).convention(Boolean.FALSE);
```

So, what would be an appropriate way to address this situation?

**Comment by lukaseder** [comment]
Looking at the previous implementation, the `DefaultTask.getOutputs()` method that was used is returning a `org.gradle.api.internal.TaskOutputsInternal` type, with "`internal`" hinting at this not being an official approach.

In an ideal world, plugins shouldn't know anything about other plugins and their inputs/outputs, so I imagine that the Gradle folks must have thought of an official way to communicate such things? Ideally, declaring the dependency between the flyway and jOOQ-codegen tasks should suffice? Why doesn't it?

**Comment by lukaseder** [comment]
Agh. OK, I can't wrap my head around whose responsibility it should be to discover these things.

I do recall now why I just always set the flag to `false`, namely because in the case where we don't have any known inputs to the tasks (e.g. database migration being external to the build), then we will simply never know if anything has changed in the database, and thus the safest *default* is to assume outputs are *never* up to date. So I'll restore the following default for now:

```java
getOutputs().upToDateWhen(task -> false);
```

Given how many iterations of trial-and-error of implementing a "correct" gradle plugin I will likely endure over the next few weeks, I think it's safe to mark this feature as experimental still, in the manual.

**Comment by lukaseder** [comment]
The reason why this hasn't been discovered in tests is simply because:

- The tests don't use any migrations but the `DDLDatabase` with inline definition of SQL scripts, which has been implemented for the purpose of code generation testing
- The inputs are static and will never change in tests.

**Comment by lukaseder** [comment]
Fixed (i.e. #16275 reverted) in versions:

- 3.20.0
- 3.19.5 (https://github.com/jOOQ/jOOQ/issues/16317)

**Comment by lukaseder** [comment]
I've labeled this as a "regression" nonetheless, given that people will be encouraged to skip upgrading to 3.19.4 as I'll release 3.19.5 soon.
