### ISSUE TITLE
H2 connection params for code gen 

### ISSUE THREAD

**Issue by gitsby** [jOOQ/jOOQ#16331]
### Your question

Hello,

I have entity with reserved words in H2.
```
@Entity
@Table(name = "KEY_VALUE")
public class DicKey {

  @Id
  @GeneratedValue
  public Integer id;

  @Column(name = "KEY")
  public String key;

  @Column(name = "VALUE")
  public String value;

}
```
During code gen using the `org.jooq.jooq-codegen-gradle` and `org.jooq.meta.extensions.jpa.JPADatabase` following exception is thrown 
`org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "create table KEY_VALUE (id integer not null, [*]KEY varchar(255), value varchar(255), primary key (id))"; expected "identifier"; SQL statement:
create table KEY_VALUE (id integer not null, KEY varchar(255), value varchar(255), primary key (id)) [42001-224]`

Is it possible to add params for H2 connection from plugins(maven/gradle) f.e `MODE`, `NON_KEYWORDS` and etc.
```
Properties info = new Properties();
info.put("user", "sa");
info.put("password", "");
connection = new org.h2.Driver().connect("jdbc:h2:mem:jooq-meta-extensions-" + UUID.randomUUID(), info);
```

Or even better to provide custom connection via config?

### jOOQ Version

3.19.3

### Database product and version

Postgres as target, for code-gen H2

### Java Version

openjdk 21

### OS Version

Windows 11 Pro 23H2

**Comment by lukaseder** [comment]
Thanks for your message.

We don't plan to expose any H2 specifics via the `DDLDatabase` as this is mostly an implementation detail. The more we expose, the more we'll have to support even more H2 specific things. I'd much rather (finally!) tackle improved interpretation support for DDL in the `DDLDatabase`, see:

- https://github.com/jOOQ/jOOQ/issues/7034

But you can probably work around this issue already today:

- Rename the column to something other than `KEY`
- Use an actual database instance to generate code from, instead of `JPADatabase` (see e.g. https://blog.jooq.org/using-testcontainers-to-generate-jooq-code/)
- Copy paste `JPADatabase` and add the flag manually. It's not a huge class, so, such a fork may be acceptable
- Quote the identifier in JPA as well, e.g. `@Column(name = "\"KEY\"")`. After all, this is an issue you might have encountered with JPA itself as well, since jOOQ uses Hibernate to export the entities into H2 behind the scenes.

I hope this helps

**Comment by marcelstoer** [comment]
We were just hit by this as well - for the same reason (wanting to set `NON_KEYWORDS`). Hence, it would have been convenient to configure the connection string for the H2 driver in `AbstractInterpretingDatabase`.

What we ended up doing was to use the `liquibase-maven-plugin` to set up an H2 db like below prior to using it in jOOQ plugin. This is fairly close to the original behavior.

```xml
<plugin>
    <groupId>org.liquibase</groupId>
    <artifactId>liquibase-maven-plugin</artifactId>
    <configuration>
        <driver>org.h2.Driver</driver>
        <url>jdbc:h2:file:${project.build.directory}/generated-h2-db;NON_KEYWORDS=KEY,VALUE</url>
        <username>sa</username>
        <password />
        <changeLogFile>${liquibase.changeLogFile}</changeLogFile>
        <contexts>default</contexts>
    </configuration>
    <executions>
        <execution>
            <phase>generate-sources</phase>
            <goals>
                <goal>update</goal>
            </goals>
        </execution>
    </executions>
</plugin>
<plugin>
    <groupId>org.jooq.pro-java-17</groupId>
    <artifactId>jooq-codegen-maven</artifactId>
    <configuration>
        <jdbc>
            <driver>org.h2.Driver</driver>
            <url>jdbc:h2:file:${project.build.directory}/generated-h2-db;NON_KEYWORDS=KEY,VALUE</url>
            <user>sa</user>
            <password />
        </jdbc>
        <generator>
            <name>org.jooq.codegen.DefaultGenerator</name>
            <strategy>
                <name>org.jooq.codegen.DefaultGeneratorStrategy</name>
            </strategy>
            <database>
                <includes>.*</includes>
                <name>org.jooq.meta.h2.H2Database</name>
                <inputSchema>PUBLIC</inputSchema>
                <excludes>DATABASECHANGELOG|DATABASECHANGELOGLOCK</excludes>
....
```

**Comment by lukaseder** [comment]
> Hence, it would have been convenient to configure the connection string for the H2 driver in AbstractInterpretingDatabase.

The feature request is understood, yet let me re-iterate: *"We don't plan to expose any H2 specifics via the DDLDatabase as this is mostly an implementation detail. The more we expose, the more we'll have to support even more H2 specific things. [...]"*
