### ISSUE TITLE
jOOQ parser parses indexed parameters as named

### ISSUE THREAD

**Issue by michael-simons** [jOOQ/jOOQ#16332]
### Expected behavior

Parsing `INSERT INTO test(name, vorname) VALUES (?, :foo)`  yields two named parameters

### Actual behavior

First parameter should be indexed or ordinal, second one should be named.

### Steps to reproduce the problem

```java
var context = DSL.using(SQLDialect.DEFAULT, settings);
var qom = context.parser().parse("INSERT INTO test(name, vorname) VALUES (?, :foo)");
qom.$queries().$first().getParams().forEach((k, v) -> {
	System.out.println(v.getParamType());
});
```

### jOOQ Version

3.19.3

### Database product and version

n/a

### Java Version

17

### OS Version

macOS

**Comment by lukaseder** [comment]
Thanks a lot for your report. I'll hhave a look at this soon.

What would be a reason for mixing the parameter styles, though?

**Comment by michael-simons** [comment]
My pleasure and thank you!

I mixed the parameters in the example just to make the point clear, but users might do weird things.

In our use case I'd rather have back the proper ordinal value, so that I don't have to try to parse the name back into a number and add one (and also hoping people didn't mix ordinals and named parameters).

**Comment by lukaseder** [comment]
I see. Indeed, all indexed parameters seem to be parsed as named parameters, with their zero based index as name. I don't recall this being the intention here. I believe there's already an issue for this (specific to the translator website: https://www.jooq.org/translate), but I can't seem to find it. But this translation is probably not what people expect:

<img width="695" alt="image" src="https://github.com/jOOQ/jOOQ/assets/734593/247b1d5b-6536-4b59-83ce-1f769c900b41">

Since we already have rendering settings to transform indexed parameters into named parameters and vice versa, I don't think we'll need a flag to maintain the current behaviour in the parser.

Nevertheless, it seems to be an incompatible change so I won't backport the fix.

**Comment by michael-simons** [comment]
I agree!

**Comment by lukaseder** [comment]
Fixed in jOOQ 3.20.0. Thanks again for the report.

**Comment by lukaseder** [comment]
Looks like this needs to be backported after all, after a few fixes around 

- #16456

**Comment by lukaseder** [comment]
Backported to versions:

- 3.19.7 (https://github.com/jOOQ/jOOQ/issues/16474)
- 3.18.14 (https://github.com/jOOQ/jOOQ/issues/16475)
- 3.17.23 (https://github.com/jOOQ/jOOQ/issues/16476)
