### ISSUE TITLE
SQL Server - Problem with implicit DateTime2 casting for DateTime columns

### ISSUE THREAD

**Issue by db2222** [jOOQ/jOOQ#16414]
### Your question

Because of historical reasons all our timestamp columns use ```DateTime``` and not ```DateTime2``` in ```SQL Server```.
Meaning we only have milliseconds (precision of 3) and not nanoseconds (precision of 7).

jOOQ implicitly casts ```DateTime``` to ```DateTime2```.
This seemingly stems from #10146 and was intentional.
See https://github.com/jOOQ/jOOQ/commit/5818a806d2213409f510de241d464da72501d509.

SQL Server however has different behaviour in regards to the casting depending on the compatibility setting.
So the following SQL leads to different results depending on the setting:
```select createdon, cast(createdon as datetime2) from entry```

If it is set to below ```SQL Server 2016 (130)``` then zeroes are added:
```2022-04-28 10:55:32.417``` -> ```2022-04-28 10:55:32.4170000```
```2022-05-09 08:21:50.473``` -> ```2022-05-09 08:21:50.4730000```
```2022-05-09 08:46:23.460``` -> ```2022-05-09 08:46:23.4600000```

However, for level ```SQL Server 2016 (130)``` and above this results in:
```2022-04-28 10:55:32.417``` -> ```2022-04-28 10:55:32.4166667```
```2022-05-09 08:21:50.473``` -> ```2022-05-09 08:21:50.4733333```
```2022-05-09 08:46:23.460``` -> ```2022-05-09 08:46:23.4600000```

So when we do a query like the following we get a wrong result because of the different precision behaviour:
```select().from(Entry).where(Entry.CreatedOn.le(dateTime))```

The effective where part looks like this:
```Entry.CreatedOn <= cast('2022-04-28 10:55:32.417' as datetime2)```

Meaning that it checks with ```2022-04-28 10:55:32.4166667``` which excludes rows that have the value ```2022-04-28 10:55:32.417```.

We can't change the compatibility setting as this is done from our customers themselves. Also a higher compatibility setting is usually better.
As a hotfix we add a millisecond in the code to ensure the check works.

As a general solution we would need to deactivate the ```DateTime2``` casting behaviour. It should be ```DateTime``` for us.
How would be the best way to archieve this?
- Implement a specific manual Binding (https://www.jooq.org/doc/3.13/manual/code-generation/codegen-advanced/codegen-config-database/codegen-database-forced-types/codegen-database-forced-types-binding/ / https://www.jooq.org/doc/3.19/manual/sql-building/queryparts/custom-bindings/)? But how could this be registered for the DSL context and not the code generator (we use our own meta data as we needed to marry jOOQ with our existing logic)? Also I'd rather like to keep existing binding logic for DateTime from jOOQ intact. Basically I would only need to replace 1 line of code (DefaultBinding - DefaultTimestampBinding.sqlInline0 - K_DATETIME2). With a manual binding I would have to re-implement the other code as well and watch out if the jOOQ logic might change in the future and it therefore might make sense to adapt the manual binding.
- Somewhere in the jOOQ code I saw that it's seemingly possible to deactivate the automatic casting. But I would assume this is not a good idea to set it globally if really we only need it specifically for DateTime in SQL Server.
- Manipulate the SQL low-level via ExecuteListener. But this doesn't seem like a good idea (inefficient) even if it works.
- Something completely else I am not aware of?

Or is this maybe a general bug/feature? Should it out-of-the-box be possible to configure the specific behaviour because of the different SQL Server logic depending on the version/compatibility?

Additional infos:
- https://dba.stackexchange.com/questions/204208/sql-server-2016-compatibility-level-and-datetime-2
- https://github.com/microsoft/mssql-jdbc/wiki/Addressing-datetime-to-datetime2-conversion-behavior-change-starting-from-SQL-Server-2016
- https://www.dbdelta.com/sql-server-2016-and-azure-sql-database-v12-breaking-change/

Thank you very much in advance!

### jOOQ Version

3.17.4 Professional

### Database product and version

SQL Server 2016 and higher

**Comment by lukaseder** [comment]
Thanks for your message. The simplest solutions that would replace *all* `datetime2` usages include:

- Patching jOOQ at the right location
- Using reflection to change the value of `K_DATETIME2` (it's currently used only right there)
- Using an `ExecuteListener` that replaces `as datetime2)` by `as datetime)` (with a relatively low but non-zero risk of false positives): https://www.jooq.org/doc/latest/manual/sql-execution/execute-listeners/
- Use your own `DataType<Timestamp>` with your own binding. You can do this by writing `SQLDataType.TIMESTAMP.asConvertedDataType(myBinding)`. This is equivalent to attaching the binding with the code generator, if you're not using code generation. Now you can use the `DataType` everywhere, including e.g. `DSL.field(..., MY_TIMESTAMP)`

Regarding additional questions:

> * Somewhere in the jOOQ code I saw that it's seemingly possible to deactivate the automatic casting. But I would assume this is not a good idea to set it globally if really we only need it specifically for DateTime in SQL Server.

There's `RenderContext.castMode(CastMode.NEVER)`. But it won't affect SQL Server, because 1) SQL Server generally doesn't need bind value auto casts, but 2) it needs a cast for timestamp literals, because there's no such thing as the standard SQL literal `TIMESTAMP '2000-01-01 00:00:00'`, for example.

Also, you're right, there might be other side-effects that are not related to this problem, now or in the future.

> * Manipulate the SQL low-level via ExecuteListener. But this doesn't seem like a good idea (inefficient) even if it works.

It's not terrible? Yes, it costs a bit, but compared to the query execution, the overhead should be negligible. You could cache the input / output SQL pairs if you think (and measure) a significant impact is there.

> Or is this maybe a general bug/feature? Should it out-of-the-box be possible to configure the specific behaviour because of the different SQL Server logic depending on the version/compatibility?

We could think about offering support for `DATETIME` as well. I can't say what the impact would be, at this point. Configurability is always a slippery slope, because each configuration flag interacts with other flags and functionality, and it's hard to predict edge cases, as well as have decent test coverage.

I'll think about this for a bit. There is a task (matching your github handle!) which requests more test coverage, at least:

- https://github.com/jOOQ/jOOQ/issues/2222

I'll look into this and get back to you hopefully next week.
