### ISSUE TITLE
Loader API - loadRecords and using default values in database columns when corresponding input fields in the record have nulls

### ISSUE THREAD

**Issue by rbajek** [jOOQ/jOOQ#16468]
### Your question

I'm using loader API (loadRecords) to insert batches into my database. Please have a look at the following example:

```sql
create table my_test_table(
    id INT NOT NULL,
    name VARCHAR(20) NOT NULL,
    creation_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
```
Using the `loadRecords(record)` like this:

```java
MyTestTableRecord myTestTableRecord = new MyTestTableRecord();
myTestTableRecord.setId(1);
myTestTableRecord.setName("Test");

Stream<MyTestTableRecord> recordStream = Stream.of(myTestTableRecord);

dslContext.loadInto(MY_TEST_TABLE)
                    .bulkAll()
                    .loadRecords(recordStream)
                    .fieldsCorresponding()
                    .execute();
```

JOOQ generates the following insert:

```sql
insert into my_test_table (id,name,creation_time) values (1, 'Test', null);
```
Is it possible to set up JOOQ to not put columns with nulls into the insert statements?
Thanks.

### jOOQ Version

3.14.15

### Database product and version

MySQL 8.0.36

### Java Version

Oracle 17.0.3

### JDBC / R2DBC driver name and version (include name if unofficial driver)

mysql-connector-java:8.0.28

**Comment by lukaseder** [comment]
Thanks for your message and sorry for the delay.

You can specify the fields that you wish to include explicitly using `fields(...)` (instead of `fieldsCorresponding()`). Due to the fact that the `Loader` API is optimised for batches and bulk insertions, you cannot omit the `NULL` values on individual rows (in case you mean for some rows to include the `creation_time` and others to exclude it). I'm assuming, in your case, that you never want to include it, so just replace `fieldsCorresponding()` by `fields(MY_TEST_TABLE.ID, MY_TEST_ABLE.NAME)`
