### ISSUE TITLE
"AND NOT" in WHERE clause not parsed properly

### ISSUE THREAD

**Issue by Mrs-Hudson** [jOOQ/jOOQ#16502]
### Expected behavior

For the where clause
`"current_country = \"france\"   AND NOT (language LIKE \"french\")        ";
`
`{"operator":"AND","conditions":[{"field1":"current_country","field2":"france","comparator":"EQUALS"},{"condition":{"field1":"language","field2":"french","comparator":"NOT LIKE"}}]}
`
(or have NOT as a parent opertator somewhere )

### Actual behavior

`{"operator":"AND","conditions":[{"field1":"current_country","field2":"france","comparator":"EQUALS"},{"condition":{"field1":"language","field2":"french","comparator":"LIKE"}}]}
`

### Steps to reproduce the problem

```

  public static String convertQueryToJson(String query) {

    Gson gson = new GsonBuilder()
        .setPrettyPrinting()
        // Registering a custom serializer for jOOQ Field
        .registerTypeHierarchyAdapter(Field.class, (JsonSerializer<Field<?>>) (field, type, jsonSerializationContext) ->
            new JsonPrimitive(field.getName()))
        .create();

    // Creating a sample jOOQ condition
    Condition condition = DSL.using(SQLDialect.DEFAULT).parser().parseCondition(query);

    return gson.toJson(condition);
  }

  public void testGsonExample() {
       String query = "current_country = \"france\"   AND  (language NOT LIKE \"french\")        ";
    String jsonResult = GsonCompiler.convertQueryToJson(query);
    System.out.println("result issss");
    System.out.println(GsonCompiler.convertToJsonSingleLine(jsonResult));
    System.out.println("converting file output");
  }
```

### jOOQ Version

3.12.0

### Database product and version

DEFAULT

### Java Version

openjdk version "21.0.2" 2024-01-16 LTS

### JDBC / R2DBC driver name and version (include name if unofficial driver)

NA

**Comment by lukaseder** [comment]
Thanks for your report. Please always report issues against the latest versions of jOOQ. We're not maintaining 3.12 anymore. Actively maintained versions are listed here:
https://www.jooq.org/download/versions

With 3.20.0-SNAPSHOT, trying this:

```java
System.out.println(DSL.using(dialect).parser().parseCondition(
    "current_country = 'france' AND NOT (language LIKE 'french')"
));
```

Produces the expected result:

```
(
  current_country = 'france'
  and not (language like 'french')
)
```

I suspect the reason why you're not getting your expected result is because your usage of `Gson` to serialise jOOQ objects into JSON is relying on some jOOQ internals and it's doing something "unexpected," (though I don't know what you'd expect here, realistically).

With the latest versions of jOOQ and its new experimental query object model (QOM) API, it should be possible to create more formal jOOQ expression tree -> JSON mappings:
https://www.jooq.org/doc/latest/manual/sql-building/model-api/

We also have out-of-the-box serialisation as JSON or XML on our roadmap, see:

- https://github.com/jOOQ/jOOQ/issues/15906

**Comment by Mrs-Hudson** [comment]
Thanks @lukaseder , my eventual goal is to convert the SQL query where clause to a custom json like this:
`{"COUNTRY": [{"VALUE": "france", "PREFERENCE": "REQUIRED", "SCOPE":"CURRENT"}], "LANGUAGE": [{"VALUE": "french",  "PREFERENCE": "EXCLUDED"}]}`

Wondering if jooq has the any functionality to help with this

**Comment by lukaseder** [comment]
Not yet, see my comment here:

> We also have out-of-the-box serialisation as JSON or XML on our roadmap, see:
> 
> * [Continue work on public query object model API #15906](https://github.com/jOOQ/jOOQ/issues/15906)

However, your JSON format seems to be more specific to your own needs, so you wouldn't get any out-of-the-box experience anyway, you'd have to do something yourself, along the lines of my other comment here:

> With the latest versions of jOOQ and its new experimental query object model (QOM) API, it should be possible to create more formal jOOQ expression tree -> JSON mappings:
> https://www.jooq.org/doc/latest/manual/sql-building/model-api/
