### ISSUE TITLE
Auto wrap Field arguments to a Routine's Object typed parameter in Field<Object>

### ISSUE THREAD

**Issue by ayush-finix** [jOOQ/jOOQ#16529]
### Expected behavior

I have a query that (simplified) looks like 
```
dsl.select(A.fields())
        .from(A)
        .where(Routines.exist(A.COL, "val").eq(false))
        .fetchInto(TABLE_A.class);
```

A.COL is an hstore column in postgres and we're not using the postgres jooq extensions. Routines.exist is the function bound to the `?` operator for the hstore extension.

I'm not sure this will matter, but we also have a forcedType converter we have attached to A mapping it to a POJO.
```
// object, I assume because we don't use the extensions
Binding<Object, Pojoclass>
...
@Override
  public void sql(BindingSQLContext<Pojoclass> ctx) throws SQLException {

    // Depending on how you generate your SQL, you may need to explicitly distinguish
    // between jOOQ generating bind variables or inlined literals.
    if (ctx.render().paramType() == ParamType.INLINED) {
      ctx.render().visit(DSL.inline(ctx.convert(converter()).value())).sql("::hstore");
    } else {
      ctx.render().sql("?::hstore");
    }
  }

  @Override
  public void register(BindingRegisterContext<Pojoclass> ctx) throws SQLException {
    ctx.statement().registerOutParameter(ctx.index(), Types.VARCHAR);
  }

  @Override
  public void set(BindingSetStatementContext<Pojoclass> ctx) throws SQLException {

    Object value = ctx.convert(converter()).value();
    if (value == null) {
      ctx.statement().setString(ctx.index(), null);
    } else {
      ctx.statement().setString(ctx.index(), Objects.toString(value));
    }
  }

  @Override
  public void set(BindingSetSQLOutputContext<Pojoclass> ctx) throws SQLException {
    throw new SQLFeatureNotSupportedException();
  }

  @Override
  public void get(BindingGetResultSetContext<Pojoclass> ctx) throws SQLException {
    ctx.convert(converter()).value(ctx.resultSet().getString(ctx.index()));
  }

  @Override
  public void get(BindingGetStatementContext<Pojoclass> ctx) throws SQLException {
    ctx.convert(converter()).value(ctx.statement().getString(ctx.index()));
  }

  @Override
  public void get(BindingGetSQLInputContext<Pojoclass> ctx) throws SQLException {
    throw new SQLFeatureNotSupportedException();
  }
```

I would expect the query above to essentially work.

### Actual behavior

I get a SQLDialectNotSupportedException on 3.19.6 and a similar exception with a different message on 3.13.6.

```
SQL [null]; Error while writing value at bind index: 2
Type class org.jooq.impl.TableFieldImpl is not supported in dialect POSTGRES
```
stack trace
```
org.jooq.exception.SQLDialectNotSupportedException: Type interface org.jooq.TableField is not supported in dialect null
	at org.jooq.impl.DefaultDataType.getDataType0(DefaultDataType.java:903)
	at org.jooq.impl.DefaultDataType.getDataType(DefaultDataType.java:835)
	at org.jooq.impl.DefaultDataType.getDataType(DefaultDataType.java:828)
	at org.jooq.impl.AbstractField.coerce(AbstractField.java:318)
```

I notice that toString prints the query as

```
where (
    "public"."exist"('"schema"."a"."col"', 'val') = false
```
where the column name is essentially being treated as a string.

the generated routine seems fine
```
/**
     * @deprecated Unknown data type. Parameter type or return type is unknown.
     * If this is a qualified, user-defined type, it may have been excluded from
     * code generation. If this is a built-in type, you can define an explicit
     * {@link org.jooq.Binding} to specify how this type should be handled.
     * Deprecation can be turned off using {@literal
     * <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @Deprecated
    public static Field<Boolean> exist(
          Object __1
        , String __2
    ) {
        Exist f = new Exist();
        f.set__1(__1);
        f.set__2(__2);

        return f.asField();
    }
```

I'm able to workaround the issue by using raw sql
```
DSL.field("{0}({1},{2})", new Exist().getQualifiedName(), A.COL,
                "val").eq(false)
```

but it seems odd that using the tablefield directly is not supported.

### Steps to reproduce the problem

some sql to set up a db
```
CREATE EXTENSION IF NOT EXISTS hstore WITH SCHEMA public;

CREATE TABLE A (
  col hstore
);
```

### jOOQ Version

3.13.6 and 3.19.6 open source edition

### Database product and version

Postgres 15

### Java Version

21 open jdk

### JDBC / R2DBC driver name and version (include name if unofficial driver)

runtimeOnly 'org.postgresql:postgresql:42.2.5'

**Comment by lukaseder** [comment]
Thanks for your message.

Please observe that every "SQL usable" routine always produces 3 overloads:

- One accepting a `Configuration` and bind values for standalone execution
- One accepting bind values for embedding in queries
- One accepting expressions for embedding in queries

The one your calling is this one:

```java
    public static Field<Boolean> exist(
          Object __1
        , String __2
    ) {
```

It accepts bind values (not expressions!). A `TableField` is an expression. In order to call the overload accepting `Field<Object>, Field<String>`, explicitly wrap your bind value in `DSL.val()`, e.g.

```java
Routines.exist(A.COL, DSL.val("val"))
```

See also:

- https://www.jooq.org/doc/latest/manual/sql-building/bind-values/
- https://stackoverflow.com/q/67522537/521799

I hope this helps

**Comment by ayush-finix** [comment]
Works perfectly, sorry for missing the obvious =/.

 Thanks for being everywhere. The library and the support you provide for it is incredible.

**Comment by lukaseder** [comment]
> Works perfectly, sorry for missing the obvious =/

It's not obvious, people fall into this caveat time and again. This is why that linked question is so popular: https://stackoverflow.com/q/67522537/521799. It's just hard to foresee how to help people look for precisely this, and in your case, the fact that one of the argument types is `Object` made it even harder.

In this particular case, I think I could look into the problem a bit more and see if we can either:

- Auto-wire your call to the correct overload. This has been done before with other cases of similar overloads, at least where this makes sense. These are just overloads, and if Java was perfect and offered union types, then we wouldn't have overloads, and could always accept the correctly typed arguments everywhere, even mixes of `T|Field<T>...`
- Improve the error message to help track down the cause of the problem (if the above can't be done)

**Comment by lukaseder** [comment]
> It's just hard to foresee how to help people look for precisely this, and in your case, the fact that one of the argument types is `Object` made it even harder.

How did you google for this problem? Perhaps, I can create a resource that would have showed up in your google searches.

**Comment by ayush-finix** [comment]
> > It's just hard to foresee how to help people look for precisely this, and in your case, the fact that one of the argument types is `Object` made it even harder.
> 
> How did you google for this problem? Perhaps, I can create a resource that would have shown up in your google searches.

I did a lot of various searches. Started with the error message and saw not much useful. Moved on to trying to find something related to routines. Here's a partial history. The duplicates are likely from browser back or middle clicks.
<img width="552" alt="image" src="https://github.com/jOOQ/jOOQ/assets/40772790/e0024111-ecfc-4605-8585-2daa7ebab6dd">

I think one of the easiest wins, for my case, would be to just explicitly list out an example with a warning/caveat here: https://www.jooq.org/doc/latest/manual/sql-execution/stored-procedures/. The examples are all pure bind values and no expressions, and I definitely pored over that page multiple times to see if I missed anything.

Jooq has so much solid documentation and stack overflow support answers that I'm not sure I'm doing a great job conveying how much of a last resort filing this issue was. It's honestly a testament that most things are so intuitive that a few edge things cause such problems. As an unrelated to this issue, but jooq related example, `field.isTrue()` and `field.isFalse()` vs `field.eq(true|false)` have definitely caused confusion among members of the team and would probably be better named as `isTrueLike` and `isFalseLike` or something.

**Comment by lukaseder** [comment]
Thanks a lot for your insight. This is going to be helpful. I'll think about how to improve things from here. The exception message itself is certainly the quickest win.

1. `org.jooq.exception.SQLDialectNotSupportedException: Type interface org.jooq.TableField is not supported in dialect null` is not helpful at all
2. If the type is a jOOQ type (like `TableField`), then it is often due to the wrong overload having been chosen, so that could be a good hint to spell out right there.

> I think one of the easiest wins, for my case, would be to just explicitly list out an example with a warning/caveat here: https://www.jooq.org/doc/latest/manual/sql-execution/stored-procedures/. The examples are all pure bind values and no expressions, and I definitely pored over that page multiple times to see if I missed anything.

It's easy to conclude this from your perspective, but then, *every* manual page would possibly require such a remark, e.g. `UPPER`: https://www.jooq.org/doc/latest/manual/sql-building/column-expressions/string-functions/upper-function/. Users often suggest adding some additional hints like this to the specific page that they were looking at, but a manual that has tons of hints on *every* page is quickly very noisy and unreadable.

Think about it this way. There's a fundamental concept in jOOQ, namely that a hypothetical union type `T|Field<T>` should exist, sometimes even `T|Field<T>|Select<? extends Record1<T>>`. But because union types don't exist in Java, overloading is used as a workaround.

So, would you really want to see this fundamental concept be re-explained on *every* manual page, just because that manual page happens to illustrate how to pass `T` and/or `Field<T>` to a function?

I don't have an easy solution to the problem of explaining the fundamental concept to someone who just wants to know how e.g. routines work without distracting everyone who's already aware of the fundamental concept.

So anyway, I think the best approach here is to follow what I said earlier:

- https://github.com/jOOQ/jOOQ/issues/16529#issuecomment-2036286587

I.e.

- Improve error message (quick win that would have saved you time)
- Try to prevent the error from happening in the first case, for `Object` typed parameters

> As an unrelated to this issue, but jooq related example, `field.isTrue()` and `field.isFalse()` vs `field.eq(true|false)` have definitely caused confusion among members of the team and would probably be better named as `isTrueLike` and `isFalseLike` or something.

Yes, those methods were a mistake, but it would be an incompatible change, so not a priority:

- https://github.com/jOOQ/jOOQ/issues/4153

**Comment by lukaseder** [comment]
> * Try to prevent the error from happening in the first case, for `Object` typed parameters

Seems easy enough to do. We're doing this almost everywhere else internally, e.g. for functions like `DSL.nvl(T, T)` or `DSL.coalesce(T, T...)`, where the same problem can occur accidentally. I.e. internally, we wrap bind values with `org.jooq.impl.Tools.field(T)`, not with `org.jooq.impl.DSL.val(T)`, a utility which has been made for this and similar purposes. For some reason (probably oversight), `AbstractRoutine.set(Parameter<T>, T)` doesn't use `Tools.field()` yet:

```java
    @Override
    public final <Z> void set(Parameter<Z> parameter, Z value) {
        setField(parameter, val(value, parameter.getDataType()));
    }
```

**Comment by lukaseder** [comment]
Fixed in versions:

- 3.20.0
- 3.19.8 (https://github.com/jOOQ/jOOQ/issues/16548)
- 3.18.15 (https://github.com/jOOQ/jOOQ/issues/16549)
- 3.17.24 (https://github.com/jOOQ/jOOQ/issues/16550)
