### ISSUE TITLE
Codegen case sensivity

### ISSUE THREAD

**Issue by Jouda-Hidri** [jOOQ/jOOQ#16570]
### Your question

I upgraded a project from 

- Java 11 -> Java 21, 
- H2 1.4.194 -> 2.2.224
- Flyway 8 -> 10. 

The entities generated in Java, used to be generated with DSL names in lower_case. After upgrade, it became UPPER_CASE. I had to change the setup of H2 to generate tables in lower_case. But I didnt understand what changed in JOOQ code-gen so that I needed to change this config

### jOOQ Version

3.19.3

### Database product and version

H2 2.2.224

### Java Version

openJDK21

**Comment by lukaseder** [comment]
Thanks for your message. I'm assuming this question is also yours?

- https://stackoverflow.com/q/78354054/521799

Can you please show your complete code generation configuration?

**Comment by lukaseder** [comment]
I wonder, is this really a problem caused by jOOQ instead of by your H2 upgrade? I don't see why jOOQ would produce such a change on its own. Does your H2 database produce lower case identifiers when you connect to it (e.g. using Dbeaver) and query the `INFORMATION_SCHEMA.TABLES` and `INFORMATION_SCHEMA.COLUMNS` views?

Please note that rather than using H2 to generate code, why not work with testcontainers and an actual MySQL instance. That would also allow you to use vendor specific features not supported by H2's `mode=MySQL` mode:
https://blog.jooq.org/using-testcontainers-to-generate-jooq-code/

**Comment by Jouda-Hidri** [comment]
Per default H2 tables are uppercase. I had to change the schema from 'PUBLIC' to 'public' in my configuration: the database config was upper_case, it didnt change
