### ISSUE TITLE
SQL Dialect

### ISSUE THREAD

**Issue by ll-xMotionx-ll** [jOOQ/jOOQ#16819]
### Your question

So I am using Java Spring and I am using Jooq. My problem is that my regular db that I use is postgreSQL and the one that I use for integration test is H2 and I am having a problem with the jooq configuration is there a way that I can choose both SQL Dialect one for postgre and one for h2? If there no way can I inject a configuration using the SQL Dialect of H2 to run the integration test and one configuration for my regular db?

### jOOQ Version

3.19.8

### Database product and version

PostgreSQL latest

### Java Version

17

**Comment by lukaseder** [comment]
jOOQ is very unopinionated about how you configure jOOQ. It offers methods like `DSL.using()` for quick configuration setups, or the `DefaultConfiguration()` constructor and then `DefaultConfiguration.set()` calls to specify individual configuration elements.

So, this is more of a Spring Boot question than a jOOQ one. Just because you're using Spring Boot for auto-configuration and Spring for dependency injection doesn't mean you can't occasionally call a constructor with `new`. It's not forbidden in Spring :)

I hope this helps
