### ISSUE TITLE
org.jooq.impl.Alias not Serializable, due to Lambda wrapInParantheses

### ISSUE THREAD

**Issue by ksi-patrick-kainz** [jOOQ/jOOQ#16965]
### Expected behavior

Any given Jooq Query can be serialized. 
According https://github.com/jOOQ/jOOQ/issues/11506 the Serializable feature is scheduled to be removed (I left a comment there why we need this), but its not yet removed.

### Actual behavior

org.jooq.impl.Alias cannot be Serialized because it stores a Lambda expression wrapInParantheses. 

java.io.NotSerializableException: org.jooq.impl.Alias$$Lambda$328/0x00000008011a7050

### Steps to reproduce the problem

Serialize any query with an Alias. 

### jOOQ Version

JOOQ Professional 3.19.8

### Database product and version

Oracle 19c Enterprise

### Java Version

openjdk version "17.0.6" 2023-01-17

### JDBC / R2DBC driver name and version (include name if unofficial driver)

ojdbc10

**Comment by lukaseder** [comment]
Thanks for your report. It appears that we've reduced our serialisation test coverage since https://github.com/jOOQ/jOOQ/issues/11506 was created. This issue is a hint that we should re-increase coverage.

In this particular case, I believe we can do without the lambda. All call sites seem to pass a constant `true` or `false` value, so this particular issue should be an easy fix.

**Comment by lukaseder** [comment]
Ah yes, I think one of the main problems with these tests has been the fact that we might have arbitrary converters / bindings in our tests, that aren't serialisable.

It should be possible today, for these serialisation tests to extract all component `QueryPart` types of a `Query` using `Query.$traverse()` in order to ignore such failures.

**Comment by lukaseder** [comment]
More `QueryPart` types that prevent serialisation:

- [x] `org.jooq.impl.Lazy` (used by `DerivedTable`, for example!)

I'll amend the list

**Comment by lukaseder** [comment]
The fix cannot be backported to jOOQ 3.17, which used to have a dynamic lambda:

```java
    public final Table<R> as(Name alias, Name... fieldAliases) {
        return new TableAlias<>(this, alias, fieldAliases, c -> !NO_SUPPORT_PARENTHESES.contains(c.dialect()));
    }
```

That logic has been refactored in 3.18 with:

- #14409

**Comment by lukaseder** [comment]
Fixed in versions:

- 3.20.0
- 3.19.11 (https://github.com/jOOQ/jOOQ/issues/16966)
- 3.18.18 (https://github.com/jOOQ/jOOQ/issues/16967)

**Comment by ksi-patrick-kainz** [comment]
Thanks for the really fast fix, great customer support :)
