### ISSUE TITLE
Mapping annotations @OneToOne, @OneToMany, @ManyToMany support in Generated POJOS.

### ISSUE THREAD

**Issue by gem-sunder** [jOOQ/jOOQ#16980]
### Your question

We are using jOOQ code Generator to generate spring boot project using database queries. In Generated Pojos we wanted @OneToOne, @OneToMany, @ManyToMany mapping if two table depends upon each other. 
Currently we can't see this feature and not sure if jOOQ provide these mapping.

Also, if the feature is not available yet, is jOOQ planning to add this in upcoming updates?

### jOOQ Version

3.19

### Database product and version

mysql.version=8.0.26 or above

### Java Version

17 or above

### JDBC / R2DBC driver name and version (include name if unofficial driver)

com.mysql.cj.jdbc.Driver

**Comment by SightStudio** [comment]
why do you need that? jOOQ is not ORM.

But I hope there's something that makes it easier to group queries in a nested 1:N relationship (without multiset)

**Comment by lukaseder** [comment]
Thanks for your message, @gem-sunder.

There's no need for jOOQ to copy other API's ideas of how to map things. See these sections of the manual to help understand what jOOQ's take on mapping nested records or collections is:

- https://www.jooq.org/doc/latest/manual/coming-from-jpa/from-jpa-manytoone/
- https://www.jooq.org/doc/latest/manual/coming-from-jpa/from-jpa-onetomany/

Rather than expecting jOOQ to do the exact thing other APIs are doing, think about why jOOQ chose a more SQL-idiomatic path to mapping and embrace it. I'm positive that you'll like this approach more.

> @SightStudio But I hope there's something that makes it easier to group queries in a nested 1:N relationship (without multiset)

I don't know what you mean by this.

**Comment by SightStudio** [comment]
@lukaseder never mind.

My question was perfectly the same as this. [this](https://groups.google.com/g/jooq-user/c/7hfDlmEwfQI/m/JerL_G1HBAAJ) 
and I got my answer from [this](https://groups.google.com/g/jooq-user/c/7hfDlmEwfQI/m/oI3DZ-LXBAAJ)
(use JPA and jOOQ both)


Sorry for my lack of searching skills. :)
