### ISSUE TITLE
Allow WHERE before JOIN to make code more readable

### ISSUE THREAD

**Issue by sparr** [jOOQ/jOOQ#17075]
### Use case

I am writing a query that includes multiple JOIN/ON clauses, each of which has some WHERE conditions. Currently, afaics, I have to put all the WHERE conditions at the end of the code, separate from the JOIN that they are relevant to.

### Possible solution

Allow `.where()` "out of order" for convenience.

```java
select()
.from(T1)
.where(T1.Z.gt(0)) // <-- this is easier to understand here than at the bottom
.join(T2)
.on(T2.X.eq(T1.X))
.where(T2.A.ne(0)) // <-- this is easier to understand here than at the bottom
.join(T3)
.on(T3.Y.eq(T2.Y))
.where(T3.B.eq(0))
```

### Possible workarounds

I currently intersperse comments in the middle of query code to indicate which parts relate to which other parts

### jOOQ Version

jOOQ open source 3.15

### Database product and version

MySQL 5.17.12

### Java Version

openjdk version "17.0.12" 2024-07-16

**Comment by lukaseder** [comment]
Thanks for your suggestion.

What would happen if your `JOIN` was a `LEFT JOIN` instead? What would be the semantics of your query? Here's some background reading on the subject.

- https://blog.jooq.org/a-beginners-guide-to-the-true-order-of-sql-operations/
- https://blog.jooq.org/the-difference-between-sqls-join-on-clause-and-the-where-clause/

But you probably didn't want to suggest what you suggested. You were looking for a way to push down predicates into the table definition (not put them at "random" locations within the `JOIN` tree). You can do that via a feature that we call "inline derived tables":

- https://www.jooq.org/doc/latest/manual/sql-building/table-expressions/inline-derived-tables/

They're derived tables that can be inlined into the surrounding query where this is logically possible, otherwise it's just a derived table.

There have been numerous bug fixes in this area, so I recommend upgrading before using this feature.

**Comment by sparr** [comment]
> What would happen if your JOIN was a LEFT JOIN instead? What would be the semantics of your query?

I would expect the semantics of the query to be the same regardless of `.where()` placement, equivalent to moving them all to [near] the end of the call chain where they have to be put (as `.and`s except the first one) now. This suggestion is intended to be purely convenience/sugar and not provide any new or changed functionality or sql semantics.

**Comment by lukaseder** [comment]
> I would expect the semantics of the query to be the same regardless of `.where()` placement, equivalent to moving them all to [near] the end of the call chain where they have to be put (as `.and`s except the first one) now.

Good point about the `and()` call. What would this do?

```java
select()
.from(T1)
.join(T2)
.on(T2.X.eq(T1.X))
.and(something)    // Clearly ON-AND
.where(T2.A.ne(0)) // 
.and(something)    // Is this ON-AND or WHERE-AND? What if we passed .where(noCondition())?
```

Next, what about `leftJoin().partitionBy()`? Would you want to define the interaction of this clause with other clauses as well?

It's easy to see how only complicates semantics, making it easier to make mistakes, and harder to do the right thing.

In addition to hard to define semantics interactions with less popular keywords, there's an entire discussion to be had if it wouldn't be "more convenient" to "just" throw away all of SQL semantics and implement a more stream-like pipeline. I.e., your original example could also be interpreted as this:

```java
select()
.from(T1)
.where(T1.Z.gt(0))
// Since JOIN after WHERE isn't possible, the "reasonable" thing to do might as well be to wrap
// all the preceding SQL into a derived table and join things to that, instead!
.join(T2)          
.on(T2.X.eq(T1.X))
.where(T2.A.ne(0))
// Same thing again here
.join(T3)
.on(T3.Y.eq(T2.Y))
.where(T3.B.eq(0))
```

So, your query might as well be interpreted as:

```java
SELECT *
FROM (
  SELECT *
  FROM (
    SELECT * FROM T1 WHERE T1.Z > 0
  ) T1
  JOIN T2 ON T2.X = T1.X
  WHERE T2.A != 0
) T2
JOIN T3 ON T3.Y = T2.Y
WHERE T3.B = 0
```

That would be what *I* would expect, if this syntax were feasible, because why would your semantics be better than this? This seems more intuitive, no? If I were to "fix" SQL, this is how I'd do it. (But I won't because I know better, by now 😅)

I still understand what you *actually* want (you don't want what you suggested, you want more convenience). The inline derived tables are precisely that. Otherwise, you can always resort to using the (very old) `SelectQuery` API instead of the DSL API. Just use `DSLContext.selectQuery()`, and you can assemble your query imperatively in any order you like.

But the DSL won't start being clever. Competing APIs have made this mistake, and just look at how many beginners are sending them support requests about queries they don't understand anymore. jOOQ's rule is simple:

- The DSL works *almost exactly* like SQL. This is a feature!
- Any alternative API (the old `SelectQuery` or the new experimental model API) can offer random imperative access to query management

I hope this helps
