### ISSUE TITLE
`DiscouragedStaticTypeRegistryUsage` exception is not thrown even though the static type registry is used with custom types through DSL.field()

### ISSUE THREAD

**Issue by stellingsimon** [jOOQ/jOOQ#17222]
Note: This issue is an offspring of [this comment](https://github.com/jOOQ/jOOQ/issues/15286#issuecomment-2338196636) and the subsequent replies in 

 - #15286 

### Expected behavior

Given `-Dorg.jooq.throw-on-discouraged-static-type-registry-access=true`, a call to `DSL.field(..., MyCustomType::class.java)` should throw a `DiscouragedStaticTypeRegistryUsage`, regardless of whether the static type registry already knows `MyCustomType` or not.

### Actual behavior

 - A call to `DSL.field(..., MyCustomType::class.java)` does not throw a `DiscouragedStaticTypeRegistryUsage` even though `-Dorg.jooq.throw-on-discouraged-static-type-registry-access=true` was set. 
 - Depending on the state of the static type registry, the call either succeeds or fails with an `SQLDialectNotSupportedException`. Since non-obivous actions may lead to a manipulation of the type registry's state, this behavior may come very surprising or be seen as non-deterministic.

### Steps to reproduce the problem

Here's an [MCVE](https://github.com/stellingsimon/jOOQ-mvce-field-using-static-type-registry/blob/main/jOOQ-mcve-java-postgres/src/test/java/org/jooq/mcve/test/java/postgres/JavaTest.java)

### jOOQ Version

jOOQ 3.19.11

### Database product and version

Postgres from the MCVE

**Comment by lukaseder** [comment]
I'm not sure why you're requesting this after my explanation here:
https://github.com/jOOQ/jOOQ/issues/15286#issuecomment-2339838476

The flag `org.jooq.throw-on-discouraged-static-type-registry-access` is undocumented. The comment above it says so. I don't think it's a good idea to start requestaing features off an undocumented flag.

> * Depending on the state of the static type registry, the call either succeeds or fails with an `SQLDialectNotSupportedException`. Since non-obivous actions may lead to a manipulation of the type registry's state, this behavior may come very surprising or be seen as non-deterministic.

Yes, and thus, we're going to remove that registry in the future, but we can't just do this without breaking all sorts of user code.

**Comment by lukaseder** [comment]
Note, there may be another way to improve your situation according to your expectations, but this isn't it.

**Comment by lukaseder** [comment]
I mean, since you're already relying on internals, why not just leverage your knowledge of internals and eagerly static-initialise your entire generated schema in your tests? That way, you'll prevent the case where the user defined type hasn't been placed in the static registry yet.

**Comment by stellingsimon** [comment]
> I'm not sure why you're requesting this after my explanation here: https://github.com/jOOQ/jOOQ/issues/15286#issuecomment-2339838476

Sorry for the misunderstanding. I interpreted the following statement as a request to file a bug:

> If the exception isn't thrown (or logged) in case of a static type registry access, then that would be a bug.

Regarding:
> The flag org.jooq.throw-on-discouraged-static-type-registry-access is undocumented.

Oh, I see. That was news to me. I did a quick search through the source code and still don't know what comment you are referring to, but I'm glad I found out this way :-)

> why not [...] eagerly static-initialise your entire generated schema in your tests?

That will result in green tests with a (sometimes) failing production environment. Instead, we'll eagerly static-initialise the entire generated schema in the **production environment**. This way, we'll avoid any immediate negative consequences, but we won't be able to pinpoint discouraged usages of the static type registry. Since that won't cause immediate trouble, we're fine with this.

Thanks for your efforts!

**Comment by lukaseder** [comment]
> Sorry for the misunderstanding. I interpreted the following statement as a request to file a bug:
> 
> > If the exception isn't thrown (or logged) in case of a static type registry access, then that would be a bug.

Ah, I see :) No what I meant is that if jOOQ ever accesses the static type registry to (successfully!) fetch a user defined type, and then doesn't throw / log this exception, then that would be a bug.

But the `SQLDialectNotSupportedException` is thrown if a type is requested from the static type registry that isn't there. The idea is that someone is trying to access a *built-in* type from the static type registry that a given dialect doesn't support.

Does that make more sense?

> > The flag org.jooq.throw-on-discouraged-static-type-registry-access is undocumented.
> 
> Oh, I see. That was news to me. I did a quick search through the source code and still don't know what comment you are referring to, but I'm glad I found out this way :-)

How did you find the flag? I don't recall mentioning it anywhere, other than in the source code, along with the comment:
https://github.com/jOOQ/jOOQ/blob/d2baa57c5b07485035ed59b3d6c364023db55c37/jOOQ/src/main/java/org/jooq/impl/DefaultDataType.java#L893-L896

I recall mentioning the existence of the flag here:
https://github.com/jOOQ/jOOQ/issues/16425#issuecomment-1988116745

But I explicitly didn't want to mention ("document") the name :) But now that we're discussing it, the flag was added for the same reason you're using it now. To allow for running jOOQ's integration tests with the exception being thrown rather than logged, to increase our own test coverage.

> > why not [...] eagerly static-initialise your entire generated schema in your tests?
> 
> [...] Instead, we'll eagerly static-initialise the entire generated schema in the **production environment**. This way, we'll avoid any immediate negative consequences, but we won't be able to pinpoint discouraged usages of the static type registry. Since that won't cause immediate trouble, we're fine with this.

Ah yes, I was going to suggest that next. I mean, you can still enable the undocumented flag in your tests as an additional safety measure...

**Comment by lukaseder** [comment]
> (FYI: I'm just following up to allow you a deeper understanding of a customer's brain ;-) I do not expect changes to jOOQ at this point. I also trust you to make the right decisions whether or not I understand them, so you don't need to explain any further than you already did :-))

Oh, I very much understand this customer's brain. It has its own XKCD comic 😅
https://xkcd.com/1172

> Note that all of this is independent of whether the flag `org.jooq.throw-on-discouraged-static-type-registry-access` is internal or not.

But it does depend very much on the activation of this flag!

The default behaviour is to continue business as usual as for the last 15 years, which is, we have a static type registry and people deliberately or accidentally use it! There's no exception thrown, currently *unless* you poke at jOOQ's internals. We can't possibly throw this exception by default, or people's applications would crash in production (if they don't test things thoroughly). So, yes. The flag changes everything!

Currently, there's only a warning that is being logged a few times to hint at a future problem. You're essentially asking to solve the future problem already now, but we obviously can't.

jOOQ isn't ready for this change, because a lot of type inference that should work out of the box isn't working yet, see again this comment and its linked issues:
https://github.com/jOOQ/jOOQ/issues/15286#issuecomment-2339838476

Before this type inference works much better, I don't want to change anything, other than log the warning, which is just a warning and not an urgent call for action.

And, for the last 15 years, the exception in case of unknown (to the static registry) types was `SQLDialectNotSupportedException`. There is no other public exception. Except if you poke around in internals, but then you're on your own.

When jOOQ is ready to finally get rid of the static type registry, then these exceptions will be consistent again. Until then, I think the status quo is totally acceptable.
