### ISSUE TITLE
Records.mapping() implementations should handle null records

### ISSUE THREAD

**Issue by Walti91** [jOOQ/jOOQ#17298]
### Expected behavior

a record mapper that is applied to a field via the `convertFrom` method is not called if the query returns no result and therefore the whole subquery simply returns null.

### Actual behavior

the record mapper is called anyway which leads to a null pointer exception.

### Steps to reproduce the problem

i have a simple one to many relationship between discussions and discussion comments and want to fetch the first comment for each discussion via a sub query.

```
var firstComment = DSL.field(dsl.select(DSL.row(DISCUSSION_COMMENTS, USERS))
            .from(DISCUSSION_COMMENTS)
            .join(USERS).on(USERS.ID.eq(DISCUSSION_COMMENTS.USER_ID))
            .where(DISCUSSION_COMMENTS.DISCUSSION_ID.eq(DISCUSSIONS.ID))
            .and(DISCUSSION_COMMENTS.DELETED_AT.isNull())
            .orderBy(DISCUSSION_COMMENTS.CREATED_AT.asc())
            .limit(1))
        .convertFrom(Records.mapping(EditorSidePanelDiscussionCommentInfo::new));
```

```
 var query = dsl.select(DISCUSSIONS, firstComment)
        .from(DISCUSSIONS)
        .where(DISCUSSIONS.WORKSPACE_ID.eq(workspaceId))
        .fetch(Records.mapping(EditorSidePanelDiscussionInfo::map));
```

in the case that a discussion has no comment i get a null pointer exception because the record mapper defined in the convertFrom() is called even if the result is null.

i have found a similar issue https://github.com/jOOQ/jOOQ/issues/12929 that was already fixed and doing the conversion that way would also work. however i think since this behaviour differs from other cases in which record mappers are only called in case the result is not null this should be looked at.

### jOOQ Version

jooq 3.18.11

### Database product and version

PostgresSQL 16.2

### Java Version

openjdk Version 21

### JDBC / R2DBC driver name and version (include name if unofficial driver)

org.postgresql:postgresql:42.6.1

**Comment by lukaseder** [comment]
Thanks for your report.

> because the record mapper defined in the convertFrom() is called even if the result is null.

I should hope so!

Who is jOOQ to judge the semantics of a `null` record produced by user subqueries? What if you *wanted* that value (and translate it to something non-null)? Besides, the fact that your `Field<T>` binds `T` to a `Record2<T1, T2>` is arbitrary. It could just as well be `Integer`, so the `convertFrom()` method really shouldn't have any opinion about things that are being converted.

But your intuition is right that there *is* a bug. It's in the various `Records.mapping()` overloads, which should do the same thing as `Row[N].mapping()`, which you can use as a workaround:

```java
var firstComment = DSL.field(dsl.select(DSL.row(DISCUSSION_COMMENTS, USERS)
                                           .mapping(EditorSidePanelDiscussionCommentInfo::new))
            .from(DISCUSSION_COMMENTS)
            .join(USERS).on(USERS.ID.eq(DISCUSSION_COMMENTS.USER_ID))
            .where(DISCUSSION_COMMENTS.DISCUSSION_ID.eq(DISCUSSIONS.ID))
            .and(DISCUSSION_COMMENTS.DELETED_AT.isNull())
            .orderBy(DISCUSSION_COMMENTS.CREATED_AT.asc())
            .limit(1));
```

I guess the reason this hasn't been reported yet is because almost all docs recommends to use the `row(..).mapping(..)` convenience method, rather than delaying the mapping until later.

**Comment by lukaseder** [comment]
Indeed, #12929 fixed this for `Row[N].mapping()` methods only.

**Comment by lukaseder** [comment]
Fixed in versions:

- 3.20.0
- 3.19.12 (https://github.com/jOOQ/jOOQ/issues/17305)
- 3.18.19 (https://github.com/jOOQ/jOOQ/issues/17306)
- 3.17.28 (https://github.com/jOOQ/jOOQ/issues/17307)

**Comment by Walti91** [comment]
my reasoning for the convertFrom to not use the mapper in case the result is null was that i compared it to a fetchOne with a record mapper, which does exactly that. but these serve different use cases. so i completly agree with you that stripping the caller of the possibility to have extra hanndling for a null value would be wrong. i much prefer the various Records.mapping() methods be null safe instead as well.

```
    @Override
    default <E> E fetchOne(RecordMapper<? super R, E> mapper) {
        R record = fetchOne();
        return record == null ? null : mapper.map(record);
    }
```

Thank you for the quick response and fix

**Comment by lukaseder** [comment]
> my reasoning for the convertFrom to not use the mapper in case the result is null was that i compared it to a fetchOne with a record mapper, which does exactly that

There's a subtle difference between a "converter" (converting a `Field<T>` to a `Field<U>` or vice versa when binding variables) and a "mapper" (mapping a `R` (`Record`) to any `E` type).

> i much prefer the various Records.mapping() methods produce null safe mappers instead as well.

There's more subtlety here. What you've seen in that `fetchOne()` method is a historic decision to guarantee a mapper never receives a `null` record. This makes sense in the context of fetching top level result sets, where indeed a record cannot be `null`, and the only reason why a `Record` reference is `null` in methods like `fetchOne()` is because there is *no* record, not a *null* record. 

That historic assumption was invalidated once nested records and collections were supported. Now, `null` records originating from SQL itself are perfectly possible.

In any case, all of this isn't about `RecordMapper`, but about the convenience methods that are used to destructure a `Record[N]` type using a `Function[N]` (e.g. a constructor reference). Since destructuring cannot operate on `null` records, it makes sense to handle nulls here.

There may be a case made for additional overloads, such as `Records.mapping(Function[N]<TN, ..., U>, Supplier<U>)`, where an additional `ifNull` supplier allows for handling the `null` case:

- https://github.com/jOOQ/jOOQ/issues/17309
