### ISSUE TITLE
How to do bulk lookups efficiently 

### ISSUE THREAD

**Issue by alf** [jOOQ/jOOQ#17308]
### Your question

Until now we’ve used `WHERE (…) IN X` where X is a list of row values. This generates a SQL statement with `X.length` number of bind variables.

This isn’t good for the query cache, so we’d like to change this to something where we ideally only get one bind variable. JSON comes to mind, however I was wondering if jOOQ has some tricks we can use here.

### jOOQ Version

3.19.12-SNAPSHOT

### Database product and version

Oracle 18 XE

**Comment by lukaseder** [comment]
There's this hack for quick fixes:
https://www.jooq.org/doc/latest/manual/sql-building/dsl-context/custom-settings/settings-in-list-padding/

Alternatively, you could use `TABLE` unnesting (`WHERE (..) IN (SELECT a, b FROM TABLE (?))`). Illustration:

```sql
create type o as object (a int, b int);
create type t as table of o;

select (1, 2) in (select a, b from table (t (o (2, 1), o (1, 2))))
```

I've never tried this with `ROW` predicates, but perhaps you can reproduce the benchmark from here on your machines?
https://blog.jooq.org/sql-in-predicate-with-in-list-or-with-array-which-is-faster/

It's not worth it for small in lists (especially because of the bad cardinality estimates), but for large ones, it's definitely worth it.

Alternatively, use temp tables (`WHERE (..) IN (SELECT a, b FROM temp_table)`)

**Comment by alf** [comment]
Just a heads up until https://github.com/jOOQ/jOOQ/issues/17397 gets fixed, the quick fix hack is not safe and should not be used.

**Comment by lukaseder** [comment]
Thanks, @alf. NOte you can implement this hack yourself as well, of course.

**Comment by alf** [comment]
Indeed, but I’d rather spend time implementing a better solution. We reached for the hack as an interim solution. :)
