### ISSUE TITLE
jooq 3.17.x supporting jdbc drivers

### ISSUE THREAD

**Issue by muskaan62** [jOOQ/jOOQ#17426]
### Your question

I just wanted know if there's any possible way or via jooq documentation where we can find what all jdbc driver versions that jooq 3.17.x supports.
The reason of Ask is I observe when we were on 3.9.x and connecting to oracle with ojdbc6 Driver its working but same with 3.17.x is not working and similarly jtds driver 1.3.1 was working with 3.9.x and its failing with 3.17.x mostly with **Abstract Method Error**(because implementation is missing in driver codes)
obviously the issue is resolve with latest drivers..but somehow wanted to know if is there a possible way to get the  jdbc drivers versions which will not compatible with 3.17.x version

### jOOQ Version

3.17.3

### Database product and version

jdbc drivers

### Java Version

11

**Comment by lukaseder** [comment]
jOOQ doesn't maintain a JDBC driver support matrix yet. So far, integration tests have shown that the latest driver version ususally works quite well with all JDKs and all RDBMS versions for most RDBMS.

Of course, if you're running on JDK 11, it is probably better for you to use ojdbc11, not ojdbc6. jOOQ hasn't supported Java 6 in a while, since 3.15, see:

- https://www.jooq.org/download/support-matrix-jdk

An `AbstractMethodError` could appear if you're using a JDBC driver for JDK 6 (JDBC 4.0 or 4.1) but jOOQ expects at least JDBC 4.2 as we've dropped support for JDK 6. Older drivers don't implement the new JDBC 4.2 methods yet. Starting from JDBC 4.2 / JDK 8, default methods have been added to the language preventing this kind of error in most cases, but that wasn't the case in JDK 6 yet.

Regarding jtds, to my understanding, this driver isn't really maintained anymore? The last release on Maven Central was 11 years ago. Why not just use the official drivers by SAP? jOOQ has never been integration tested against jtds. We always support the official drivers only.
