### ISSUE TITLE
Converter<byte[], U> for binary columns doesn't work from within MULTISET expressions

### ISSUE THREAD

**Issue by alf** [jOOQ/jOOQ#17452]
### Expected behavior

Whether or not we're using multiset should not affect the types of my fields.

### Actual behavior

When using multiset the forcedType does not take effect which cause the returned data to be different.

### Steps to reproduce the problem

See https://github.com/jOOQ/jOOQ-mcve/compare/main...alf:jOOQ-mcve:bug/convertion-skipped for details.

It seems that when using multiset (or other functionality that makes jOOQ leverage json-functionality against Oracle) then certain forcedType-configurations does not take effect. Probably because json has different types than Oracle.

### jOOQ Version

3.19.14-SNAPSHOT

### Database product and version

Oracle

### Java Version

OpenJDK 17

**Comment by alf** [comment]
It seems to me that the problem here is related to the fact that our converter implements `Converter<byte[], String>` and thus contains:

```
    @Override
    public Class<byte[]> fromType() {
        return byte[].class;
    }

    @Override
    public Class<String> toType() {
        return String.class;
    }
```

Since jOOQ gets a hex-coded string from the json it skips the converter.

**Comment by lukaseder** [comment]
Thanks a lot for your report. We have generic integration tests for certain pairs of types used in converters (e.g. `Converter<Integer, String>` or `Converter<String, Integer>`), but not systematic tests for all data types as we do otherwise for built in bind variables.

It should be simple to add those tests systematically, e.g. for a `Converter<T, String>` for all built-in types `T`.

**Comment by lukaseder** [comment]
Note:

> Whether or not we're using multiset should not affect the types of my fields.

This is true only if you're using `Converter`. If you're using `Binding`, then the binding logic cannot apply from within `MULTISET` expressions, because `Binding` applies only for direct interactions with JDBC, not any JSON/XML emulations of such nestings.

**Comment by lukaseder** [comment]
So, this is indeed binary data type specific. jOOQ already handles multiple cases of hexadecimal, text, or base64 encoding of binary data from within JSON documents for these dialects:

- CockroachDB
- H2
- MariaDB
- MySQL
- PostgreSQL
- Redshift
- SQLite
- Trino
- YugabyteDB

Oracle should be added to the list. There are a few other binary related `MULTISET` issues in jOOQ, which is why this hasn't been addressed yet. I'll look into those as well in the same go.

**Comment by lukaseder** [comment]
Fixed in versions:

- 3.20.0
- 3.19.14 (https://github.com/jOOQ/jOOQ/issues/17456)
- 3.18.21 (https://github.com/jOOQ/jOOQ/issues/17457)
- 3.17.30 (https://github.com/jOOQ/jOOQ/issues/17458)

**Comment by lukaseder** [comment]
There is a broader topic to be investigated:

- https://github.com/jOOQ/jOOQ/issues/17460

I.e. many internal calls to `Typed.getType()` may be wrong as they're querying for the `Class<U>` type (the user type), when we should query for the built-in `T` or `Class<T>` type in case there's a `Converter`.

**Comment by lukaseder** [comment]
3.19.14, 3.18.21, and 3.17.30 have been released
