### ISSUE TITLE
ContextConverter don't receive correct ConverterContext

### ISSUE THREAD

**Issue by liry** [jOOQ/jOOQ#17451]
### Expected behavior

I'm using JOOQ with Spring Boot and I initialize the Configuration with some data - e.g.:
```
@Bean
DefaultConfigurationCustomizer jooqConfigCustomize() {
    return configuration -> {
        configuration.data("KEY_FOR_DATA", new ExampleDecryptor(key));
    };
}
```
I would expect this configuration data to be present in converter.

### Actual behavior

Default context is used with no data. It's probably caused by the https://github.com/jOOQ/jOOQ/issues/16814 similarly like in the https://github.com/jOOQ/jOOQ/issues/16655.

The problematic usage of the `DataType.convert(Object)` method seems to be in the `AbstractRecord.TransferRecordState#apply`:
```
t.values[targetIndex] = targetType.convert(values[sourceIndex]);
```
The `TransferRecordState` already contains correct context in the `converterContext` field, it's just not being used yet for the conversion.

### Steps to reproduce the problem

```
public class AbcConverter implements ContextConverter<JSONB, Abc> {
    @Override
    public Abc from(JSONB databaseObject, ConverterContext ctx) {
        ...
        ctx.configuration().data("KEY_FOR_DATA");
        ...
    }
```

Not sure if actual query is anyhow useful, but here it is ():
```
            dsl()
                .with(name("numbered")).as(
                        dsl().select(
                                        ENV.asterisk(),
                                        rowNumber()
                                                .over()
                                                .partitionBy(ENV.ID2)
                                                .orderBy(ENV.ID.desc())
                                                .as("row_number")
                                ).from(ENV)
                ).select(field("id"), field("id2"), field("json"))
                .from(name("numbered"))
                .where(field("row_number").eq(1))
                .fetch(EnvRepository::recordMapper);
```
and the mapper:
```
private static Env recordMapper(Record r) {
...
            var rec = r.into(ENV);
...
```

### jOOQ Version

3.19.13

### Database product and version

POSTGRES: 16.4 (Debian 16.4-1.pgdg120+1)

### Java Version

openjdk version "21.0.3" 2024-04-16 LTS

### JDBC / R2DBC driver name and version (include name if unofficial driver)

org.postgresql:postgresql:42.7.3

**Comment by lukaseder** [comment]
In your example query, you're not attaching your converter to your projection anywhere:

```java
.select(field("id"), field("id2"), field("json"))
```

Just because the `Converter` exists *somewhere* doesn't mean it automatically applies anywhere. Why would it?

Instead, write something like this:

```java
.select(field("id"), field("id2"), field("json", SQLDataType.JSON.asConvertedDataType(myConverter)))
```

I understand that you were probably thinking that since the converter is already attached to the objects in your CTE, it might be looked up automatically by jOOQ, but jOOQ doesn't do this for you. It would be wrong to do this because your `field("json")` is a plain SQL template of unknown content (to jOOQ), and it's of type `Field<?>` (where `?` turns out to be `JSONB`) not `Field<Abc>`

A common trick is to use the generated code again as follows:

```java
Env numbered = ENV.rename("numbered");

dsl()
	.with(name("numbered")).as(
		dsl().select(
			ENV.asterisk(),
			rowNumber()
					.over()
					.partitionBy(ENV.ID2)
					.orderBy(ENV.ID.desc())
					.as("row_number")
		).from(ENV)
	)
	// Now the generated types are attached correctly:
	.select(numbered.ID, numbered.ID2, numbered.JSON)
	.from(numbered)
	.where(field("row_number").eq(1))
	.fetch(EnvRepository::recordMapper);
```

Or, you could use the `QUALIFY` clause, which jOOQ can emulate on PostgreSQL (in the commercial distributions):
https://www.jooq.org/doc/latest/manual/sql-building/sql-statements/select-statement/qualify-clause/

```java
dsl()
	.select(ENV.ID, ENV.ID2, ENV.JSON)
	.from(ENV)
	.qualify(rowNumber()
		.over()
		.partitionBy(ENV.ID2)
		.orderBy(ENV.ID.desc()).eq(1))
	.fetch(EnvRepository::recordMapper);
```
