### ISSUE TITLE
DefaultConverterProvider should use JSONB::data instead of JSONB::toString

### ISSUE THREAD

**Issue by loicmathieu** [jOOQ/jOOQ#17497]
### Use case

Currently, when you get a JSBON record to a String like that `record.get("value", String.class)` it uses `Convert.from()` which considers that all types can be converted to a String by using their `toString()` method.

But, the `toString()` method of the JSONB type is known to have performance impact, see #14954.

To overcome that, we can specialize `Convert.from()` to delegate to `JSONB.data()` instead of `JSONB.toString().

You can read https://www.loicmathieu.fr/wordpress/en/informatique/jooq-tip-ne-convertissez-pas-jsonb-en-string/ for some background information on this subject for my precise use case.

### jOOQ Version

Professional Edition 3.19

### Database product and version

Postgres 19

### Java Version

Java 21

**Comment by lukaseder** [comment]
Thanks for your suggestion. That would be one option, though I'm tempted to go even further and revert the normalisation in `toString()`:

- https://github.com/jOOQ/jOOQ/issues/15751

It may not be necessary, as opposed to the normalisation in `equals()` and `hashCode()`.

**Comment by loicmathieu** [comment]
Any solution would work ;)
Of course, if you revert normalization on toString() it would improve performance for more use cases so it's a better solution.

**Comment by lukaseder** [comment]
While I'm still undecided about reverting the `toString()` behaviour (https://github.com/jOOQ/jOOQ/issues/15751), clearly, we should be able to prevent internal calls to the method (which users cannot avoid):

- https://github.com/jOOQ/jOOQ/issues/17578

I'll keep your issue separate, as it isn't really "internal" behaviour, but it definitely makes sense just the same. The `DefaultConverterProvider` doesn't have to work with the normalised `JSONB` document, it can work just the same with the original data (it is actually better, due to all the normalisation bugs, such as numeric precision issues or lack of support for duplicate JSON object keys)

**Comment by lukaseder** [comment]
Given the potential (subtle!) impact this change may have on user code, I'm marking this as a breaking change of behavious, and won't backport this particular change.

The workarounds are documented in your issue description. It is easy to avoid this particular method call, if performance is essential.

Fixed in jOOQ 3.20.0
