### ISSUE TITLE
Missing Generated annotations on nested Path classes

### ISSUE THREAD

**Issue by rpalcolea** [jOOQ/jOOQ#17592]
### Use case

[jOOQ 3.19.0 introduced a @Generated annotation with CLASS or RUNTIME retention for better JaCoCo interop](https://github.com/jOOQ/jOOQ/issues/8617) 

This generates classes such as 

```
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.19.15"
    ],
    comments = "This class is generated by jOOQ"
)
@Suppress("UNCHECKED_CAST")
open class SomeClass(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, SomeRecord>?,
    parentPath: InverseForeignKey<out Record, SomeRecord>?,
    aliased: Table<SomeRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<SomeRecord>() 
// more
```

Which is fantastic and helped a lot. 

However, I noticed that when using path joins, at least the kotlin generator, creates nested open classes, something like this:

```
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.19.15"
    ],
    comments = "This class is generated by jOOQ"
)
@Suppress("UNCHECKED_CAST")
open class SomeClass(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, SomeRecord>?,
    parentPath: InverseForeignKey<out Record, SomeRecord>?,
    aliased: Table<SomeRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<SomeRecord>() {
    // some stuff here
    open class AnotherPath: Another, Path<Another> {
      // nested class code 
   }
}
```

When JaCoCo instruments this code, the nested classes are not ignored by JaCoCo as they are not annotated. 

### Possible solution

Wondering if it makes sense to also annotate these ones out of the box since jOOQ is aware of this while generating them

### Possible workarounds

Today, there are possible workarounds:

* Annotate the classes after they are generated or find extension points
* Modify the generator config to mark `implicitJoinPathTableSubtypes` as `false`: I suspect we really want these ones though

### jOOQ Version

3.19.x

### Database product and version

N/A

### Java Version

17

**Comment by lukaseder** [comment]
Thanks for your suggestion. Will fix this right away.

There isn't really a very important reason to nest these classes as opposed to making them top level, other than the fact that they somehow "belong" to the enclosing class, so there's no reason not to generate annotations on them, specifically because they're just nested, not inner classes, so they're really independent of the outer class.

> * Annotate the classes after they are generated or find extension points

There's currently no extension point in this particular case. The usual "extension point" is to override the `JavaGenerator::printClassAnnotations` method, but that is precisely the one that isn't being called.

> * Modify the generator config to mark `implicitJoinPathTableSubtypes` as `false`: I suspect we really want these ones though

The path methods aren't too important for most queries, other than if you want to make path joins explicit (e.g. for to-many path joins) using the simplified notation:

- https://www.jooq.org/doc/latest/manual/sql-building/sql-statements/select-statement/explicit-path-join/

This is an entirely optional feature. You can still make explicit path joins and add a dummy `ON` clause. The generated paths are purely to tell jOOQ the `join(Path)` method can be used where `ON` is always optional, even for `INNER JOIN` and `OUTER JOIN`.

There may be other, future usages of this feature, but by then, this issue will have been fixed.

**Comment by lukaseder** [comment]
Fixed in versions:

- 3.20.0
- 3.19.16 (https://github.com/jOOQ/jOOQ/issues/17594)
- 3.18.23 (https://github.com/jOOQ/jOOQ/issues/17595)
- 3.17.32 (https://github.com/jOOQ/jOOQ/issues/17596)

**Comment by rpalcolea** [comment]
Thanks for the great context and quick implementation!
