### ISSUE TITLE
Add a new @Internal annotation to annotate API parts that are not supposed to be used

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#2026]
Some internal API needs to be declared as public, because it is shared between artifacts. Some examples are:

- `SchemaImpl`
- `TableImpl`
- `AbstractRoutine`
- `MiniJAXB` (since jOOQ 3.12)
- many more

These APIs should not be used by users. In order to enforce this, we will use a new `@org.jooq.Internal` annotation, which clearly states that such annotated API can change incompatibly between minor releases (and if necessary, although less likely even between patch releases)

**Comment by lukaseder** [comment]
Some of these `@Internal` annotated types / methods can also be annotated with `@Deprecated`, which will further help prevent users from using the types / methods. While this annotation usage is not widely used, it is not against the principles listed in the annotation or in JEP 277 https://openjdk.java.net/jeps/277

The annotation is to discourage users from using a type / method.

The `@Deprecated` annotation may only be added to `@Internal` types intended to be used by jOOQ library code, not by generated code. For example, `TableImpl` may be annotated as `@Internal`, but not as `@Deprecated`

**Comment by knutwannheden** [comment]
One thing I dislike about the `@Deprecated` annotation is that we either (a) end up with many warnings in the code base, (b) have to disable the compiler warning regarding deprecation warnings, or (c) have to add `@SuppressWarnings("deprecation")` annotations all over.

What is unfortunate about (c) is that the annotation either has to be added at the top-level type of the corresponding Java classes or otherwise a warning remains on the import. Using fully qualified class names in the code also works, but not very nice when there are many references.

@lukaseder What's your take on this?

**Comment by lukaseder** [comment]
> (a) end up with many warnings in the code base

Nope

> (b) have to disable the compiler warning regarding deprecation warnings

Nope

> (c) have to add @SuppressWarnings("deprecation") annotations all over.

Yes, that's what I had in mind, and I don't think this is going to be a matter of this happening "all over". How many such suppressions are we talking about?

**Comment by knutwannheden** [comment]
Not sure yet. I would just prefer not adding the annotation at the type level, as it may cover up other deprecations.

**Comment by lukaseder** [comment]
In our current Eclipse settings, we're ignoring these warnings anyway... But we can postpone this change and move it to a separate issue.

**Comment by lukaseder** [comment]
Here is the new issue: https://github.com/jOOQ/jOOQ/issues/8927
