### ISSUE TITLE
Cleanly separate DSL and Model APIs

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#2198]
While the DSL API becomes more and more useful and consistent, the "internal" (or non-DSL) APIs have become fuzzy second-class citizens that are hard to use. Everything in the DSL API is intuitive as the DSL API mimicks SQL itself. The "internal" API has evolved organically. Not all DSL features are represented in the "internal" API, which leads to feature requests like #1492, #2115 .

Instead of hacking around in the "internal" API, the two APIs should be cleanly defined and separated:
- DSL API: The construction of inline SQL
- Model API: The model representation of all QueryParts
#### Properties of the above
- DSL types shall be immutable, where possible
- DSL types have "DSL methods", i.e. no getters / setters, etc. (see also #2115)
- DSL types shall expose Model types through a `model()` method
- Model types shall be mutable
- Model types shall be JavaBeans compliant (setters and getters)
- Model types shall apply the fluent JavaBeans extension (with setters returning this, see also: #8358)
- Model types shall be Serializable, Cloneable (in some way)
- Model types shall expose their component Models ( [select list], [table expression] ) in two modes:
  1. "as-is", i.e. in a manipulable way
  2. "as-will-be-rendered", i.e. in a non-manipulable way

These marker interfaces might be introduced:

``` java
interface DSL<D extends DSL<D, M>, M extends Model> extends QueryPart {
  M model();
}
interface Model extends QueryPart {
}
```

**Comment by rgoldberg** [comment]
When you said "DSL types shall be immutable, where possible", will the implementation of interfaces like `UpdateSetMoreStep` be immutable, or mutable?

It's obviously possible to make them immutable, since you could always just create a new immutable object for each call to methods like `set(...)`, but it would seem to make sense to make such implementations mutable, because they function as builders, and only seem to be able to append additional expressions.  There probably isn't much use for an intermediate `UpdateSetMoreStep`, so why keep creating new objects when the back history of the object is immutable, especially since that might lead to bugs in constructing queries due to people forgetting to always save the results of each call to the “builder”?

Maybe I'm missing something, or maybe you meant to say something like "DSL types shall be immutable at the point in the DSL method chain after which there is no need to modify them for a single jOOQ query run".

If you are planning on keeping certain DSL objects mutable, there should be methods that create an immutable version of the object for any state in which the object can be used to execute a query, so that the query can easily be saved and reused without fear of modification.

In this case, the exposed bind context of the DSL object should be separate from the immutable DSL object.  If an immutable query object represents SQL like:

```
select
    *
from
    t
where
    t.a = 1 and
    t.b = ?
```

while the `t.a = 1` condition could be implemented by jOOQ as a JDBC bind parameter, it shouldn't be exposed for modification.  i.e. any time that a literal value is supplied to the DSL, it should never be able to be overridden.  If a variable bind value is required, a version of `DSL.param(...)` that does not supply a value should be called.

The immutable query’s `execute` method should always require a `BindContext` argument to run, where `BindContext` is a new class unrelated to any existing classes.

To ensure that the correct number & types of values are bound for every call to a query, there should be multiple versions of the method that creates the immutable version of a query object, plus multiple sub-interfaces of `BindContext`

The interfaces should be something like:

```
MutableQuery {
    ImmutableQuery<BindContext00> immutable();

    <T01> ImmutableQuery<BindContext01<DataType<T01>>> immutable(DataType<T01> t01);

    <T01, T02> ImmutableQuery<BindContext01<DataType<T01>, DataType<T02>>> immutable(DataType<T01> t01, DataType<T02> t02);

    ...

    ImmutableQuery<BindContext> immutableUnknownBindings();
}

ImmutableQuery<B extends BindContext> {
    int execute(B b);
}

BindContext {}
BindContext00 extends BindContext {}
BindContext01<T01> extends BindContext {
    T01 param01();
}
BindContext02<T01, T02> extends BindContext {
    T01 param01();
    T02 param02();
}
...
```

Whatever overload of `MutableQuery#immutable(...)` is called will throw an exception if its arguments do not correspond to the types of the bind variables already added to the `MutableQuery`.

If someone wants to forgo future bind count verification, so they can avoid having to pass in all the arguments to `immutable(...)`, they can call `immutableUnknownBindings()`.

Is any of this useful?

**Comment by lukaseder** [comment]
> so why keep creating new objects when the back history of the object is immutable

The current "some things *are* mutable, others *aren't*" situation is what has been causing confusion. We'd like to change that. How we're going to achieve it? That's not yet defined.

> especially since that might lead to bugs in constructing queries due to people forgetting to always save the results of each call to the “builder”?

Currently, there might be bugs because people think that intermediate steps are independent of one another.

> DSL types shall be immutable at the point in the DSL method chain after which there is no need to modify them for a single jOOQ query run

Where *is* that point?

> The immutable query’s execute method should always require a BindContext argument to run, 

We have that already, unless I'm misunderstanding you?

> Is any of this useful?

I don't really see the value (or feasibility) of all this suggested type safety yet. How would you even communicate and propagate the bind parameter type of the whole query from deep down within the AST when you add another predicate? And why? :)

**Comment by lukaseder** [comment]
This can be implemented backwards-compatibly, if we extract the current API in a new compatibility module and delegate all calls to the new API. Here's how this works:

- The new API is in a different namespace, and thus doesn't conflict with the existing API
- The existing API is but a set of interfaces, which will be re-implemented in a mutable way. I.e. users are still allowed to write things like 
```java
SelectFromStep s = ctx.select(...);

s.from(abc);
s.groupBy(xyz);
```
- This mutable legacy API would internally keep references to the new immutable API and delegate execution to the latter.
