### ISSUE TITLE
Support ON DUPLICATE KEY UPDATE in H2

### ISSUE THREAD

**Issue by markshim** [jOOQ/jOOQ#2508]
When using insert into statement with onDuplicateKeyUpdate for H2, it throws SQLDialectNotSupportedException: The ON DUPLICATE KEY UPDATE clause cannot be simulated for H2.

**Comment by amfleming** [comment]
H2 supports this now in its 'MYSQL Compatibility mode' 

HOWEVER it only can tolerate un-qualified column names in its update clause

If you e.g. force JOOQ to use MySQL dialect against an H2 connection the query will get generated but will fail because JOOQ (reasonably?) emits table-prefixed column names in the UPDATE clause which chokes H2

**Comment by lukaseder** [comment]
Interesting, thanks for the feedback, @amfleming. jOOQ (by default) generates exactly what you write. Because all generated tables / columns are qualified by default, this is the case here, too. I suspect that in MySQL, there might be some rare use-cases of table disambiguation.

Perhaps, it would be reasonable to request from H2 to allow for qualified columns as well in this case?

**Comment by tortila** [comment]
@lukaseder I reported the issue in H2 project: https://github.com/h2database/h2database/issues/1027. Are you still planning to fix it in jOOQ to be compatible with unqualified names as well?

**Comment by lukaseder** [comment]
Thanks for the ping, @tortila. This has gotten off my radar. It's simple to emulate this for H2 in MySQL mode. The integration tests are running smoothly if we turn off qualification for column references in the `ON DUPLICATE KEY UPDATE` clause for H2
