### ISSUE TITLE
Add support for inserting custom clauses in a Select statement through .sql(String) or .sql(QueryPart)

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#2541]
Similar to the existing `.hint()` method that allows for adding Oracle-style hints to the beginning of a query, it may be useful to allow for appending Strings and QueryParts to the end of a SQL statement.

This would immediately allow for adding:
- SQL Server `OPTION` clauses #1952
- DB2 isolation-clauses #2537

**Comment by nkoterba** [comment]
Think our use case fits under this issue/enhancement but would such a feature allow us to get a jooq Query object (say from a base Java class) and then add some additional `where` or `select` or "operations" onto it?

In our scenario, we are moving from a HARD delete for business objects in the datastore to a SOFT delete so that we just mark records as *DELETED*.  However, we would like to just add a simple `where` clause that extends all the queries we already have written in our "current" implementation.

For example:

```javascript
org.jooq.Query query = <obtained from base class or current Jooq logic>;

query.sql(new Where Clause QueryPart());
```javascript

The `new Where Clause QueryPart()` would just enforce that RecordState = 'ACTIVE' and then we wouldn't have to update all our Jooq queries throughout the project with this one additional `where` clause.

**Comment by lukaseder** [comment]
I think that this particular feature request here would be about the worst way of transforming a "hard" delete into a "soft" delete :-) The idea here is really just to be able to inject additional comments / clauses at "arbitrary" positions (although "arbitrary" here means that not all positions are reachable, which is why this feature request probably won't make it).

An actual soft delete feature is requested here: #2683.

Adding the `RecordState = 'ACTIVE'` predicate can already be done today via `VisitListener`. Feel free to enquire on the user group to learn more about this feature:
https://groups.google.com/d/forum/jooq-user

**Comment by lukaseder** [comment]
jOOQ expression trees don't really provide any hint about the generated SQL string, so placing comments at specific expression tree locations doesn't make much sense.

Users of the parser would have liked jOOQ to remember comments, and we can do that for in-between-statement comments, but it's very hard to do in general.

If it will be done, it will be done as part of a bigger, parser related issue: https://github.com/jOOQ/jOOQ/issues/13049

Closing this as duplicate of https://github.com/jOOQ/jOOQ/issues/13049
