### ISSUE TITLE
Rename org.jooq.scala package to org.jooq.scalaextensions because of potential collisions with the scala package

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#2684]
According to a jOOQ / Scala user, naming packages "scala" can lead to collisions with the scala package when importing things like

```scala
import org.jooq._
```

A workaround is to write something like

```scala
import org.jooq.{scala => scalajooq, _}
```

In the long run, the package should be renamed, though. It may be sufficient to move it to

```scala
org.jooq.extensions.scala
```

**Comment by lukaseder** [comment]
@er1c: I completely agree with what you said in #5440. However, we shouldn't introduce a backwards incompatibility in a minor release. Is there any reasonable solution that allows for doing this *and* keeping stuff backwards compatible? I'm thinking of subtyping, but will all the imports in client code still work?

Another option would be to just duplicate the class and deprecate the old one

**Comment by er1c** [comment]
I believe it would be a breaking change, but the good news is it would be a *VERY LOUD* breaking change (compile error) that would also be extremely easy to document/fix.  So probably not for 3.8.x but it seems reasonable to move forward in the 3.9.x.  The number of people that use the scala items is probably a lot lower than your java, and it probably helps those guys "unhack" some of their imports in the process.

**Comment by lukaseder** [comment]
Hmm, yeah.

In fact, we cannot keep the original lying around, because it will still produce exactly that issue, so there's no backwards compatible solution here.

I'll need to think about it. From the user experience, I really don't think that such a massive breaking change is acceptable in a minor release.

The reason why the manual uses `import org.jooq._` is simple: At some point (when Scala support was added), the IDE support for auto-importing types was really poor. In Java, this is never a problem and people hardly ever import anything at all, manually. So, perhaps, I'll just fix the manual for now.

**Comment by er1c** [comment]
I tried doing import org.jooq.{..., ..., ..., ...} but the list just became MASSIVE all to just get around importing the "scala" package name.  Renaming works, but you still generate a compiler warning message EVERY TIME IT'S USED: 

I think the "breaking change" would be perfectly acceptable for a 3.9, if you really wanted to push it to 4.0 then fine, but it also hurts Scala adoption because you have people like me that have to chase down "why isn't my scala code working right with jooq, I've imported this library a thousand times before just fine..." :) ... to realize it's this damn import statement :)

**Comment by lukaseder** [comment]
Speaking of which: https://github.com/jOOQ/jOOQ/blob/53e44fac6e71137e64ccf2010853984109141238/jOOQ-scala/src/main/scala/org/jooq/scala/Conversions.scala#L48 ;-)

OK. I'll do this for jOOQ 3.9. It'll be documented as a breaking change in the 3.9 release notes
