### ISSUE TITLE
Add support for client-side column/table encryption

### ISSUE THREAD

**Issue by axelfontaine** [jOOQ/jOOQ#3078]
A possible implementation could work like this:

The type of the column should be BINARY (byte[]).
If a database supports "comment on", check for a column/table comment like JOOQ-ENCRYPTED-BINARY or JOOQ-ENCRYPTED-VARCHAR. This would determine the type of the Java field (byte[] or String). It would also trigger automatic and transparent client-side encryption (byte[] or String -> byte[]) and decryption (byte[] to byte[] or String (encoding is default for table/db/server))

You could then simply pass the key to the DSL.using() call.

The encryption could be implemented with something strong & fast like AES/CBC/PKCS5Padding with a 128, 192 or 256-bit key. (128 is the only key strength that is universally available as part of the core JDK without extensions)

If the database doesn't support "comment on" or the user doesn't want to use that, add an option to customize the code generation.

If the comment is on the table instead of the column, apply the encryption to all BINARY columns.

**Comment by lukaseder** [comment]
I think the current feature set is good enough to implement this via `Converter` or `Binding` SPI.

**Comment by egmanoj** [comment]
> ... and the best way to currently implement that is to define your own custom data type, e.g. `EncryptedString` and provide jOOQ with a `Converter` to automatically convert data:
> http://www.jooq.org/doc/latest/manual/code-generation/custom-data-types/

@lukaseder Planning to something like this in my code, have a related question. How are converters initialised? Specifically, I'd like to inject existing encryption code+key into my converter. Is this possible at all?

**Comment by egmanoj** [comment]
Follow up: is it possible to do this via `Configuration` by any chance?

**Comment by lukaseder** [comment]
> @lukaseder Planning to do something like this in my code, and have a related question. How are converters initialised?

By default, converters that you supply to the `<forcedType><converter/></forcedType>` configuration are initialised with each generated column in the table's constructor. The default constructor of the converter is invoked. Example:

```java
public final TableField<String, UserType> FIELD = 
  createField(DSL.name("CONVERTER"), SQLDataType.VARCHAR(100), this, "", new MyConverter());
```

However, instead of supplying a reference to a converter class, you can also provide the initialisation code directly, for an "inline converter". See example from here: https://www.jooq.org/doc/latest/manual/code-generation/codegen-advanced/codegen-config-database/codegen-database-forced-types/

```xml
          <converter>org.jooq.Converter.ofNullable(
            Integer.class, MyEnum.class, 
            i -&gt; MyEnum.values()[i], MyEnum::ordinal
          )</converter>
```

> Specifically, I'd like to inject existing encryption code+key into my converter. Is this possible at all? 

jOOQ generated classes are not "beans" in any DI sense, but are statically initialised by the class loader. Hence, you cannot easily inject things into the generated classes. But instead of injecting things, you can write lookup logic. If there's a way to look up your DI framework's content statically (e.g. like JNDI offers), then you can replace converter references like the above by converter lookups. You would then have to make sure that the initialisation order is correct, i.e. at the time the jOOQ generated classes are statically initialised, the lookup will be available.

Note that "primitive" means of lookup are always an option, e.g. `ThreadLocal`, if your transaction model is thread bound.

> Follow up: is it possible to do this via `Configuration` by any chance?

The `Converter` SPI doesn't give you access to a `Configuration`, but the `Binding` SPI does:
https://www.jooq.org/doc/latest/manual/code-generation/custom-data-type-bindings

The various types like `BindingSetStatementContext` implement `Scope` which offers `Scope.configuration()`, which might be helpful to you.

**Comment by axelfontaine** [comment]
As we have been revisting this recently, I just want to leave our current implementation here in case it helps anyone.

Encrypted data is stored using AES-256-GCM in columns ending with `_x`. This naming convention is mostly for convenience of the converter mapping as it makes it easy to recognize all encrypted columns with a single pattern.

The data is represented on the JVM using a new `AesGcmEncrypted` type:

```kotlin
import java.security.SecureRandom
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

/**
 * AES-256-GCM encrypted data.
 * The encrypted data is prepended by the random IV used together with the secret key to encrypt it.
 */
@JvmInline
value class AesGcmEncrypted(val byteArray: ByteArray) {
    /**
     * Decrypt using this secret key.
     */
    fun decrypt(secretKey: SecretKey): ByteArray {
        val iv = byteArray.copyOfRange(0, AES_GCM_IV_LENGTH)
        val encrypted = byteArray.copyOfRange(AES_GCM_IV_LENGTH, byteArray.size)

        val cipher = aesGcmCipher()
        cipher.init(Cipher.DECRYPT_MODE, secretKey, aesGcmParameterSpec(iv))
        return cipher.doFinal(encrypted)
    }

    companion object {
        /**
         * Encrypts this clear bytearray with this secret key using AES-GCM with a random IV.
         */
        fun encrypt(secretKey: SecretKey, clear: ByteArray): AesGcmEncrypted {
            val iv = ByteArray(AES_GCM_IV_LENGTH)
            SecureRandom().nextBytes(iv)

            val cipher = aesGcmCipher()
            cipher.init(Cipher.ENCRYPT_MODE, secretKey, aesGcmParameterSpec(iv))
            val encrypted = cipher.doFinal(clear)

            return AesGcmEncrypted(iv + encrypted)
        }

        /**
         * Generates a new AES-256 secret key used for both encryption and decryption.
         */
        fun generateSecretKey(): SecretKey {
            val keyGenerator = KeyGenerator.getInstance("AES")
            keyGenerator.init(256)
            return keyGenerator.generateKey()
        }

        /**
         * AES-GCM should use a 12 byte IV.
         * https://crypto.stackexchange.com/questions/41601/aes-gcm-recommended-iv-size-why-12-bytes
         */
        private const val AES_GCM_IV_LENGTH = 12

        private fun aesGcmParameterSpec(iv: ByteArray) = GCMParameterSpec(128, iv)
        private fun aesGcmCipher(): Cipher = Cipher.getInstance("AES/GCM/NoPadding")
    }
}
```

This new type is converted using a regular jOOQ converter:

```kotlin
import org.jooq.Converter

class AesGcmEncryptedConverter : Converter<ByteArray, AesGcmEncrypted> {
    override fun from(databaseObject: ByteArray): AesGcmEncrypted = AesGcmEncrypted(databaseObject)
    override fun to(userObject: AesGcmEncrypted): ByteArray = userObject.byteArray
    override fun fromType(): Class<ByteArray> = ByteArray::class.java
    override fun toType(): Class<AesGcmEncrypted> = AesGcmEncrypted::class.java
}
```

and the conversion is configured using this forced type definition:
```kotlin
ForcedType()
    .withConverter("AesGcmEncryptedConverter")
    .withUserType("AesGcmEncrypted")
    .withIncludeExpression(".*\\..*_x")
```

The encrypted data is now part of a regular record and remains encrypted until the `decrypt()` method is invoked with the correct secret key.

Hope this helps anyone else encountering the need for client-side encryption with jOOQ.
