### ISSUE TITLE
Add support for PostgreSQL materialized views

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#3254]
PostgreSQL 9.3 has added support for materialized views:
http://www.postgresql.org/docs/9.3/static/sql-creatematerializedview.html

These are currently not supported by jOOQ's code generator yet, as they are not reported from the `information_schema`

----
See also:
- http://postgresql.1045698.n5.nabble.com/Re-Materialized-views-WIP-patch-td5740513i40.html
- http://stackoverflow.com/q/19127561/521799
- https://groups.google.com/forum/#!topic/jooq-user/oKCJRGwFMJo

**Comment by akobiakov** [comment]
As a workaround
```sql
create view some_view as select * from some_materialized_view;
```
works pretty fine for us. However would be really nice to have a way to avoid such a hack.

**Comment by lukaseder** [comment]
Thanks for the workaround. I agree, but if our implementation is hacking around the dictionary views, I would like to avoid implementing it :)

**Comment by lukaseder** [comment]
OK, I've reviewed this query. I think we can ship this feature with jOOQ 3.8

**Comment by akobiakov** [comment]
Great, thanks! We will test this as soon as 3.8.0 is released.

**Comment by lukaseder** [comment]
We're not going to release 3.8 until late Q1 2016. So, if you want to look into this earlier, feel free to build jOOQ-meta on your side.

By the way, I'm curious to learn about the use-case of a PostgreSQL materialized view, given that it doesn't auto-refresh, what's the purpose of it?

**Comment by akobiakov** [comment]
> By the way, I'm curious to learn about the use-case of a PostgreSQL materialized view, given that it doesn't auto-refresh, what's the purpose of it?

We develop a read-only api (basically an [EPG](https://en.wikipedia.org/wiki/Electronic_program_guide)) with a few updates per day and quite a big amount of reads. Once a day we import the data into a normalized database, so broadcasts, channel information, videos, categories and so on are stored in a separate tables. At the same moment we provide a sophisticated way to query this data as "documents", e.g. "give me all the broadcasts for today in Poland with video.genre = 'movie' and only on hd channels". Since, as I said, the data is read-only, it's pointless to join everything to build documents again and again every time a client is querying the API, so we decided to try materialized views. Another benefits is that code becomes much simpler (a row == a document, a query filter == a simple SQL predicate etc) and it's much easier to tune performance of the api queries. That's the use-case.

**Comment by lukaseder** [comment]
OK, I see, thanks for the feedback.

Effectively, though, this could've been done with `CREATE TABLE .. AS SELECT ..` just the same. I'm really curious about why PostgreSQL calls these "materialized views", when they don't auto-refresh.

**Comment by akobiakov** [comment]
I see the following problems with the CTAS (or `truncate` + `select into`) approach:
* it makes a table temporary unavailable, which is problematic when a service is under a considerable workload;
* all the related objects (e.g. indices) are dropped along with the table and should be recreated later;
* CTAS is a much more heavy operation from a disk i/o perspective, if compared with the materialized view refresh, in the cases when only a small piece of the backing data has been changed. Since `refresh materizalized view ... concurrently` [doesn't affect](http://www.postgresql.org/message-id/1388704089.19653.YahooMailNeo@web122305.mail.ne1.yahoo.com) the whole table

**Comment by lukaseder** [comment]
OK, I haven't thought about these things, thanks for the input!
