### ISSUE TITLE
Add code generator configuration to specify a log level threshold

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#3761]
Users may want to decrease the verbosity of jOOQ's code generation logging when using Maven. With standalone code generation setups, this can be achieved easily by configuring slf4j or log4j directly, but apparently, this is a bit harder with Maven (see: http://stackoverflow.com/q/4782089/521799)

----
See also:
- https://twitter.com/noerstad/status/532465105796362240
- http://stackoverflow.com/q/4782089/521799

**Comment by lukaseder** [comment]
We won't make logging configurable for now as the requirements are still a bit unclear - few people have made this request so far.

But it will probably not be a bad idea to decrease the log level of the logged XML from `INFO` to `DEBUG`: #4122

**Comment by RichardBradley** [comment]
+1 from me.

I found that you can work around this for now by using a system property CLI arg:

    mvn  -Dorg.slf4j.simpleLogger.log.org.jooq=WARN test

This isn't a real fix though, as I'd really like to be able to configure the JOOQ generator's log level in my POM, so that all developers and my CI server get the same changes. Adding the above property to the `<properties>` section does not work, presumably because the logger gets initialized before those properties are added to System by Maven.

>  the requirements are still a bit unclear

I'd like to be able to do something like:

```
<plugin>
  <groupId>org.jooq</groupId>
  <artifactId>jooq-codegen-maven</artifactId>
  <configuration>
    <logging>WARN</logging>
    ...
  </configuration>
  ...
</plugin>
```

c.f. similar options on other plugins: http://www.liquibase.org/documentation/maven/generated/update-mojo.html#logging

**Comment by lukaseder** [comment]
Hmm, that's not a bad idea at all. This level (when set to `WARN`) would already prevent `DEBUG` and `INFO` level messages from being sent to the logger. That can be done easily for the next release.

Thanks for the suggestion!

**Comment by lukaseder** [comment]
Changed the issue title, as this isn't specific to using Maven. The configuration also applies to the standalone code generator, and to using Gradle, ant, etc.

**Comment by RichardBradley** [comment]
Thanks!
