### ISSUE TITLE
jOOQ Spring example integration's exception translator may hold on to Connection too long

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#3787]
See also Adam Gent's comment here:
http://www.jooq.org/doc/latest/manual/getting-started/tutorials/jooq-with-spring/#comment-1703789045

> I believe I was one of the first to experiment with Spring and jOOQ transactions and my gist is here https://gist.github.com/agentg... (Sept 2012). There is also a SO post on this. The problem I have over the example project and the Adam Zell's work is that it doesn't take into account is that the spring code that original does transaction exception conversion releases the connection immediately on exception:

> // This note and code below comes from 
// org.springframework.jdbc.core.JdbcTemplate.execute(StatementCallback<t>)
// Release Connection early, to avoid potential connection pool deadlock
// in the case when the exception translator hasn't been initialized yet.
> 
> JdbcUtils.closeStatement(stmt);
stmt = null;
DataSourceUtils.releaseConnection(con, dataSource);
con = null;
ctx.exception(getExceptionTranslator(dataSource).translate("jOOQ", ctx.sql(), ex));

> There really should probably be a maven artifact with the require integration classes so that people aren't cutting and pasting incorrect code.

**Comment by lukaseder** [comment]
I suspect that @agentgt's suggestions are based on a flaw in Spring itself. The comment in `JdbcTemplate` reads:

```java
			// Release Connection early, to avoid potential connection pool deadlock
			// in the case when the exception translator hasn't been initialized yet.
			JdbcUtils.closeStatement(stmt);
			stmt = null;
			DataSourceUtils.releaseConnection(con, getDataSource());
			con = null;
			throw getExceptionTranslator().translate("StatementCallback", getSql(action), ex);
```

This smells extremely fishy and is a sign that Spring's `JdbcTemplate` works around class loading and initialisation issues at the completely wrong spot. We shouldn't let such workarounds leak into jOOQ.

**Comment by azell** [comment]
From my understanding, the first call to SQLErrorCodeSQLExceptionTranslator(DataSource) may result in a Connection being allocated to query the database for error messages.  If the connection pool is empty in theory this could lead to a deadlock.

The original Spring transaction integration code posted above attempts to protect against this scenario by eagerly releasing the connection prior to the call to SQLErrorCodeSQLExceptionTranslator.  My gist (https://gist.github.com/azell/5655888) passes a String instead of a DataSource which according to the Javadocs avoids this problem:

"Create a SQL error code translator for the given database product name. Invoking this constructor will avoid obtaining a Connection from the DataSource to get the metadata."

Of course this has the downside of mapping the jOOQ SQLDialect to the Spring JDBC equivalent string.

**Comment by lukaseder** [comment]
I see, thanks for the clarification. Yes, the jOOQ Spring examples also use the string-based constructor, so this issue should indeed not appear with the official examples

> Of course this has the downside of mapping the jOOQ SQLDialect to the Spring JDBC string equivalent.

Interesting point. Perhaps we could add a method in `SQLDialect` that returns this string. The same could be done for mapping jOOQ dialects to Hibernate dialects...

**Comment by lukaseder** [comment]
- Spring: https://github.com/jOOQ/jOOQ/issues/4252
- Hibernate: https://github.com/jOOQ/jOOQ/issues/4253
