### ISSUE TITLE
Add more sophisticated examples to the manual

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#4083]
See also:
https://twitter.com/67726e/status/567827122544386048

**Comment by 67726e** [comment]
The feature/problem that really spurned the series of tweets was working with `RecordMapper` and mapping from a series of joined tables into POJOs. I'll simplify my scenario, but at the start I would have a schema with matching models like:

```
jobs
  id
  title

applications
  id
  user_id
```

So when I first wrote a query to pull both tables into a DTO using the `RecordMapper` interface, I had something like:

```java
RecordMapper<Record, CandidateDTO> CANDIDATE_DTO_MAPPER = record -> {
    CandidateDTO candidate = new CandidateDTO();

    candidate.setJob(record.into(UserModel.class));
    candidate.setApplication(record.into(ApplicationModel.class));

    return candidate;
}
```

So the problem I ran into was the ambiguous mapping of `jobs.id` and `application.id` - so I'd wind up having `ApplicationModel#id` containing the value of `JobModel#id`. The solution here was to map from the `Record` to the `JobsRecord` and then into the POJO by writing `record.into(JOBS).into(JobModel.class)`.

I definitely commend the quality of the jOOQ documentation, it has good content where one could read it and understand the method behind the madness. I just feel like some of the examples might be a bit *too* light, especially for a less experienced developer who might not be comfortable reading through the source when a question arises, or otherwise wouldn't have the experience to draw on to intuit solutions to a given problem.

I could definitely accept an RTFM response to my issue in particular, after all the manual does implore the reader to explore the Javadoc for the `Record` interface on several occasions, and for the record I wasn't necessarily complaining, just having a little Twitter rant/rave session on what is quickly becoming my favorite Java database tool. I would also volunteer to help add better documentation in the near-future, assuming that is something y'all would like to see in future releases of the jOOQ manual (and it is open to be contributed to), otherwise I was planning on writing some blog entries for issues I ran into while developing with jOOQ and the elegant solutions I was able to achieve.

**Comment by lukaseder** [comment]
Hi @67726e, or should I say, "grn" :-)

Thanks a lot for elaborating. This is indeed very helpful. You (unfortunately) ran into one of the biggest caveats that we currently have in jOOQ. The problem that people run into when they use `JOIN` to collect "nested collections", before de-duplicating them again in a mapper. Sophisticated ORMs like Hibernate don't give users access to actual SQL JOIN because they wouldn't be able to materialise object graphs any more.

We're hoping to solve this in jOOQ 3.6 via the SQL standard way to produce nested collections: #3884 (`MULTISET`).

Regarding the documentation: You're right, the `into(Table<?>)` method is not well documented, even if it is a very useful workaround to the problem that you've experienced. I've created #4086 for this particular issue.

In general, we don't want to eagerly over-document every feature because we're very biased. For us, it's very obvious what needs documentation and what doesn't - but for new users, there is a different perception. This is why we are very happy to hear what the community struggles with most, before we add new sections (the above being totally useful as a section). What we want to avoid is a much too huge manual (the PDF already has 230 pages) that will overwhelm users.

> I could definitely accept an RTFM response to my issue in particular

No, this particular issue isn't really covered in the manual yet. So no link to point you to. Various user-group discussions exist, but rather than searching for them, I'll prefer fixing #4086

> just having a little Twitter rant/rave session

I can totally relate to ranting :)

> what is quickly becoming my favorite Java database tool

Great to hear!

> I would also volunteer to help add better documentation in the near-future

That is also great to hear! The manual license is CC-BY-SA 4.0. We'd like to make the sources available eventually (#3358), mainly for translations. Good idea to do that some time soon.

Ideally, your help would come in the form of pointing us to missing parts (like you did), to your struggles. Every blog post you publish is greatly appreciated as well. We believe that no vendor sells the product that their customers are really buying. Your jOOQ experience is unique and talking about your unique experience is very interesting to us and to the community.

- Lukas from Data Geekery

**Comment by lukaseder** [comment]
@67726e : We've added a section to this manual page:
http://www.jooq.org/doc/3.5/manual/sql-execution/fetching/record-vs-tablerecord/

There's potential for more improvements, so if you have any further ideas, just shoot. We'll be happy to hear them.

**Comment by 67726e** [comment]
More than bare-bones, "Hello, World" level SQL as stated by the original, deleted Twitter rant (I think, it's seven years and far more beers ago). I believe that's gotten far better in the past seven years but, yes, it is subjective and thus hard to define concrete deliverables.

Hopefully one day I'll be back in Java / jOOQ land so I can open another subjective ticket :)
