### ISSUE TITLE
Convenience "map2" method for Scala integration

### ISSUE THREAD

**Issue by nkgm** [jOOQ/jOOQ#4203]
Following discussion on #4169, I've come up with the following implicit to map records in Scala:

```scala
    implicit class ScalaRecord[R <: Record](val rec: R) {
      def map2[O](f: R => O): O = f(rec)
    }
// ...
    dsl.insertInto(EMPLOYEE, fields.jooqCols)
      .values(fields.jooqVals)
      .returning(EMPLOYEE.ID, EMPLOYEE.FIRST_NAME, EMPLOYEE.LAST_NAME)
      .fetchOne map2 {
        // r is inferred to be of type EmployeeRecord now
        r => Employee(r.getId, r.getFirstName, r.getLastName)
      }
// ...
```
Is this merge-worthy?

As an additional point, overloading the original `map` method (and also providing `flatMap`, `filter` etc) would open the way to `Record` being usable in for-comprehensions, but we'd have to override the `Record` base class at codegen time. Is that possible?

**Comment by lukaseder** [comment]
> Is this merge-worthy?

I have very strong objections calling things `map2`. Didn't we learn from Oracle's hideous `VARCHAR2` type? :-)

But I think I see now what you mean. Is the naming `map` really that important? Is there any documentation I can read about that topic?

> As an additional point, overloading the original map method (and also providing flatMap, filter etc) would open the way to Record being usable in for-comprehensions.

Interesting! Could you show a couple of examples?

> but we'd have to override the Record base class at codegen time. Is that possible?

Yes, the new jOOQ 3.6 `ScalaGenerator` (#4021) could emit additional methods in `EmployeeRecord`... What methods would be needed?

**Comment by nkgm** [comment]
Sorry for the long response time - decided to postpone my answer until I come up with a couple of non-trivial examples. Turns out I'm going to need some more time for that, but to keep the ball rolling here's a couple of points:

> I have very strong objections calling things map2. Didn't we learn from Oracle's hideous VARCHAR2 type? :-)

It was a silly name picked in a hurry. The actual name can be whatever sits well with Scala idioms and the jOOQ mentality (although a `map` overload is probably best for reasons explained below).

> Interesting! Could you show a couple of examples?

This is the part I'm still working on :)
You can find a quick roundup on for-comprehensions [here](http://docs.scala-lang.org/tutorials/FAQ/yield.html). I also created this [gist](https://gist.github.com/nkgm/e44e64a09ec09ef14904) (from Martin Odersky's Reactive Programming course). Not particularly relevant to data access, but serves as a good example of how you can compose various types of random generators by combining existing ones using for-comprehensions. I've included the `_desugared` output for further insight.

> Yes, the new jOOQ 3.6 ScalaGenerator (#4021) could emit additional methods in EmployeeRecord... What methods would be needed?

The basic Monad operations required to support all variants of the Scala `for` statement are `map`, `flatMap`, `withFilter` and `foreach`:
```scala
// This statement's return type is whatever `yield` returns
for {
  a <- expression1
  // these will be combined with flatMap
  b <- expression2
} yield expression3 // `yield` expands to `map`

// A `for` without `yield` returns `Unit` and is only used for the side-effects
// `foreach` will be used instead of `map`
for {
  a <- expression1
  // ...
} expression2 // no `yield` expands to `foreach`

// It is also possible to use special `if` statements, which will expand to `withFilter`
for {
  a <- expression1 if (expression2) // expanded to expression1.withFilter(expression2)
  // ...
} yield (expression3)
```
I'm going to play with jOOQ 3.7 see if I can't find some more practical examples and report back. Hope there's still time for 3.7!

**Comment by lukaseder** [comment]
I like the wording on [yield](http://docs.scala-lang.org/tutorials/FAQ/yield.html):

> As this statement will most likely not help anyone who needs help, let’s try again…

About this:

> although a map overload is probably best for reasons explained below

In Java, `map` shouldn't be overloaded, unless the overload takes a `FunctionalInterface` with a different argument arity. Otherwise, using lambdas will be impossible with `map`.

Perhaps, an implicit conversion like your `ScalaRecord` is still feasible, though.

> Hope there's still time for 3.7

Well, priorities may shift with a strong favour for low-hanging fruits!

**Comment by lukaseder** [comment]
I just tried this with Scala, too. A `map` overload would produce the same issues as in Java. It would force you to declare the type of the function argument in order to disambiguate - unless I misunderstood something...

**Comment by nkgm** [comment]
Sounds like bumpy road ahead :)

> In Java, map shouldn't be overloaded, unless the overload takes a FunctionalInterface with a different argument arity. Otherwise, using lambdas will be impossible with map.

I'll have to look into this one. Any recommended references?

> A map overload would produce the same issues as in Java. It would force you to declare the type of the function argument in order to disambiguate

I think you're right. 99% of `map2`'s magic was due to `ScalaRecord` capturing the `Record` subtype for you. Presumably the new `ScalaGenerator` could emit a `map` overload with the correct `Record` subtype (provided all other obstacles are overcome of course).

**Comment by lukaseder** [comment]
>> In Java, map shouldn't be overloaded, unless the overload takes a FunctionalInterface with a different argument arity. Otherwise, using lambdas will be impossible with map.
>
> I'll have to look into this one. Any recommended references?

Here's the article [You Will Regret Applying Overloading with Lambdas!](http://blog.jooq.org/2015/01/29/you-will-regret-applying-overloading-with-lambdas/) from the jOOQ blog :-) It makes reference to an example where JavaFX got it wrong and overloaded a method in a subtype, which makes using lambdas impossible with some JavaFX types.

> Presumably the new ScalaGenerator could emit a map overload with the correct Record subtype (provided all other obstacles are overcome of course).

Hmm, interestingly, this seems to work. There seems to be no ambiguity between

```scala
// Java
<E> Record.map(RecordMapper<Record, E>)

// Scala
EmployeeRecord.map[E](f : EmployeeRecord => E)
```

Without any implicit conversion involved, it looks like the Scala overload is more specific when we pass an anonymous function.

I'm gonna have to talk to @lrytz though, to be sure. Let's hope he's in the office today ;-)

**Comment by lrytz** [comment]
won't make it to the office today :) are you around tomorrow?

i agree we should use overloading only when resolution is easy. an api that forces you to think about overloading resolution is problematic, it's hard. especially when you add functions (variance) to the mix.

why doesn't the ordinary `map` method work for scala's for comprehensions?

**Comment by lukaseder** [comment]
> won't make it to the office today :) are you around tomorrow?

I noticed. :) Probably won't be here tomorrow.

> why doesn't the ordinary map method work for scala's for comprehensions?

Because it accepts a functional interface with an invariant argument type (ancient API flaw in jOOQ):

```java
// Java
interface Record {
    <E> E map(RecordMapper<Record, E> mapper);
}
```

In Java, this *could* be remedied by using recursive generic types:

```java
// Java
interface Record<R extends Record<R>> {
    <E> E map(RecordMapper<? super R, E> mapper);
}
```

But that is opening pandora's box on all of jOOQ's type system (http://blog.jooq.org/2013/06/28/the-dangers-of-correlating-subtype-polymorphism-with-generic-polymorphism/).

I suspect the problem is that @nkgm would like to treat `Record` as a monad, when it isn't a monad. It's a tuple that "unluckily" has a `map` method that it shouldn't have... :)

**Comment by manuelbernhardt** [comment]
It would be great for a overwritten `map` to work - but does that cover the case of `fetchOne` returning `null`? It would be nice (from a Scala perspective) to have a means to somehow fluently get back an `Option` from the API. Though at the moment I don't have any concrete suggestions as to how to achieve this without altering the API.

**Comment by lukaseder** [comment]
@manuelbernhardt: Hmm good point. I think that we could do something like this:

```scala
  implicit class ScalaResultQuery[R <: Record](val q: ResultQuery[R]) {
    def fetchOneOption[R]() = Option(q.fetchOne)
  }
```

Does that make any sense? I've created #4271 to track these ideas...

**Comment by manuelbernhardt** [comment]
@lukaseder yes that could be an option (no pun intended), however my general feeling is that the API may end up with quite a few of those cases which then may be somewhat confusing from a Scala perspective. I have no idea how the DSL is implemented in Java, and I suppose it's already a complex construct, but just an idea - for all of those language-conflicting cases, may it be a solution to introduce a "Language" layer at the bottom of below whatever class hierarchy there may be, and to provide different implementations of those few methods that cause trouble?

In my (simple) mind jOOQ's DSL constructs have an abstract top-class with many things and then sub-classes for the different databases. What I'm proposing as a solution is to introduce two (or later, more, who knows) subclasses at the very bottom of the chain (naming the Java variant exactly as those are called now, and prefixing Scala with, well, `Scala`), and pushing the troublesome cases one level down. Of course I may be completely off with my assumption as to how jOOQ works (I need to take some time and check that out).

I haven't got too much experience with hybrid Java / Scala DSLs but my gut feeling tells me that the whole DSL may feel a lot more idiomatic in Scala if it can get a higher degree of customisation towards the language.

**Comment by lukaseder** [comment]
> however my general feeling is that the API may end up with quite a few of those cases which then may be somewhat confusing from a Scala perspective.

Perhaps, but I will need you to be more specific :-)

> I have no idea how the DSL is implemented in Java, and I suppose it's already a complex construct

The API is rather simple. The implementation can get hairy, though, but you won't see that. All you need to know about the API is wrapped up in this blog post:
http://blog.jooq.org/2012/01/05/the-java-fluent-api-designer-crash-course

> In my (simple) mind jOOQ's DSL constructs have an abstract top-class with many things and then sub-classes for the different databases

Unfortunately (i.e. luckily): No. For the sake of argument, let's focus on `org.jooq.Select`. There is a single implementation of the complete DSL: [`org.jooq.impl.SelectImpl`](https://github.com/jOOQ/jOOQ/blob/master/jOOQ/src/main/java/org/jooq/impl/SelectImpl.java). All of the API itself is specified as a cascading set of interfaces, which are all implemented by this `SelectImpl` class.

Subtyping is a very dangerous tool and it should be used extremely sparingly. I really prefer not to abuse subtyping for the language dimension. The problem is your assumption here:

> *"at the very bottom of the chain"*

There is never a *very bottom* of the chain in subtyping of an API. Once you assume you're at the *very bottom*, you will make mistakes that are extremely hard to correct without breaking backwards-compatibility when you realise, there is another dimension that you'd like to include in your subtype hierarchy.

> I haven't got too much experience with hybrid Java / Scala DSLs but my gut feeling tells me that the whole DSL may feel a lot more idiomatic in Scala if it can get a higher degree of customisation towards the language.

So far, users seem to have been quite happy, give or take a couple of edge-cases mostly related to the usual topics:

- Lack of `Option` support
- Lack of `Int`, `Long`, ... support

Of course, an API completely written in Scala might indeed be more idiomatic, but that would not incur overriding 1-2 types. It would incur re-writing roughly 200 types, which would raise new questions of maintainability. Our integration tests include ~5000 queries against each of the 19 supported RDBMS. We have a keen eye on keeping all of this API backwards-(source-)compatible. If we had a new API in a different language, we'd have to duplicate also all of those tests too.

**Comment by lukaseder** [comment]
There had been a lot of interesting discussion in this context, but I believe that we won't implement something on our side here. We can conclude:

- `map` (and similar) methods should be reserved to monads. Record is not a monad, and thus we will never get `Record.map` right, as the instance cannot reason about its own type
- an implicit `map2` or any kind of "renamed" overload of the existing flawed `map` method is not practical
- we will move on to Java 8, very probably in jOOQ 3.7 (while keeping compatibility with Java 6 in commercial distributions). In a Java-8-ready jOOQ 3.7, we'll implement `fetchOptional()` (#4312), which returns the desired monad, which contains the correct `map()` method.
