### ISSUE TITLE
SQL Azure INT datatype converts to Object instead of Integer when using JDBCDatabase

### ISSUE THREAD

**Issue by rohitlollc** [jOOQ/jOOQ#4223]
I created a temporary test table in SQL Azure using the following statement:

```sql
CREATE TABLE dbo.test_int ( int_column int );
```

Ran the jOOQ code generator and this is the TableField that it generated in the TestInt class.

```java
public final org.jooq.TableField<com.nokia.ndx.db.generated.dbo.tables.records.TestIntRecord, java.lang.Object> INT_COL = createField("int_col", org.jooq.impl.SQLDataType.OTHER, this, "");
```

As you can see, the column with the int type was converted into a TableField with the field type as java.lang.Object instead of java.lang.Integer and the SQLDataType is OTHER instead of INTEGER.

I'm using jOOQ version 3.5.4 and JDBC driver (4.1) from:
https://msdn.microsoft.com/en-us/library/azure/gg715284.aspx
 
I understand that SQL Azure might not be completely supported in the current version of jOOQ but since Microsoft SQL Server is supported, I thought this might just work. Is there something I'm missing here or anything that I need to change?

**Comment by lukaseder** [comment]
Thanks for reporting this. Indeed, SQL Azure is not yet formally and officially supported by jOOQ, although we do have plans to add such support in the future (#659). jOOQ 3.7 is a good candidate.

We're aware of customers who have been using jOOQ also on Azure in the past, with the SQL Server dialect, although this issue is news to us.

Are you currently starting an evaluation of our product? We might be able to provide you with fixes in a jOOQ 3.7 preview release to help you move forward.

In the meantime, you might be able to force the type of the `int_column` to `INTEGER` using data type rewriting:
http://www.jooq.org/doc/latest/manual/code-generation/data-type-rewrites

Another option is to use the `org.jooq.util.jdbc.JDBCDatabase` from jOOQ-meta in the code generator. This meta data source will use JDBC's `DatabaseMetaData` instead of querying the `INFORMATION_SCHEMA`.

**Comment by rohitlollc** [comment]
I was using org.jooq.util.jdbc.JDBCDatabase previously instead of the org.jooq.util.sqlserver.SQLServerDatabase. That change seemed to fix the problem. Marking the issue closed. Thanks for your help.

**Comment by rohitlollc** [comment]
I was using org.jooq.util.jdbc.JDBCDatabase previously instead of the org.jooq.util.sqlserver.SQLServerDatabase. That change seemed to fix the problem. Marking the issue closed. Thanks for your help.

**Comment by rohitlollc** [comment]
I was using org.jooq.util.jdbc.JDBCDatabase previously instead of the org.jooq.util.sqlserver.SQLServerDatabase. That change seemed to fix the problem. Marking the issue closed. Thanks for your help.

**Comment by lukaseder** [comment]
Thanks for the feedback. I think we can still keep it open for investigation. The `JDBCDatabase` should work with SQL Azure nonetheless...

Let us know if you encounter any additional issues with SQL Azure. We're more than happy to help where we can.

**Comment by lukaseder** [comment]
We cannot seem to reproduce this issue...
