### ISSUE TITLE
Add on(Boolean), where(Boolean), having(Boolean), etc.

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#4366]
It wouldn't be inconsistent with existing API if we further overloaded predicate-accepting API, such as:

```java
on(Boolean)
where(Boolean)
having(Boolean)
// etc...
```

We already overload `DSL.condition(Field<Boolean>)` with `DSL.condition(Boolean)`, and the above methods already exist in the form of the following overload:

```java
on(Field<Boolean>)
where(Field<Boolean>)
having(Field<Boolean>)
// etc...
```

----
See also:
https://groups.google.com/forum/#!topic/jooq-user/TuULcWhN_W4

**Comment by stellingsimon** [comment]
This turns out to be a dangerous pitfall for our developers. When using tab completion in your favorite IDE, it is far too easy to get one of the following:

    join(CUSTOMER).on(CUSTOMER.ID.equals(ORDERS.CUSTOMER_ID)) // empty result
    where(CUSTOMER.ID.equals(customerId)) // empty result
    having(count().equals(1)) // empty result

Note the extra `s`. A similar issue is #4731. I am afraid these convenience methods will do more harm than benefit. I recommended our developers to only use the short form `eq` instead to make a `equals` visually more outstanding, but that is a weak fix.

**Comment by lukaseder** [comment]
Thanks for pointing this out. That is indeed very unfortunate. Specifically, because some IDEs seem to put `equals()` on top with auto-completion. The added value of being able to quickly put `true` as a join predicate every now and then doesn't seem to pull the weight of this risk.
