### ISSUE TITLE
Converters should be applicable also for subtypes of their user types

### ISSUE THREAD

**Issue by manuelbernhardt** [jOOQ/jOOQ#4389]
While trying to create a custom converter for the new `javax.money.CurrencyUnit`, we are faced with a problem that seems to be related to inheritance. This is the converter:

``` java

import org.jooq.Converter;
import javax.money.CurrencyUnit;
import javax.money.Monetary;

public class CurrencyUnitConverter implements Converter<String, CurrencyUnit> {

  @Override
  public CurrencyUnit from(String databaseObject) {
    return Monetary.getCurrency(databaseObject);
  }

  @Override
  public String to(CurrencyUnit userObject) {
    return userObject.getCurrencyCode();
  }

  @Override
  public Class<String> fromType() {
    return String.class;
  }

  @Override
  public Class<CurrencyUnit> toType() {
    return CurrencyUnit.class;
  }
}

```

This is the configuration for the code generator:

```
      <customTypes>
        <customType>
          <name>CurrencyUnit</name>
          <type>javax.money.CurrencyUnit</type>
          <converter>com.nexxchange.accounting.jooq.converter.CurrencyUnitConverter</converter>
        </customType>
      </customTypes>
      <forcedTypes>
        <forcedType>
          <name>CurrencyUnit</name>
          <expression>.*\..*CURRENCY$</expression>
        </forcedType>
      </forcedTypes>
```

And here is the problem:

```
org.jooq.exception.SQLDialectNotSupportedException: Type class org.javamoney.moneta.internal.JDKCurrencyAdapter is not supported in dialect DEFAULT
[info]   at org.jooq.impl.DefaultDataType.getDataType(DefaultDataType.java:757)
[info]   at org.jooq.impl.DefaultDataType.getDataType(DefaultDataType.java:704)
[info]   at org.jooq.impl.DSL.getDataType(DSL.java:13585)
[info]   at org.jooq.impl.DSL.val(DSL.java:11979)
[info]   at org.jooq.impl.DSL.value(DSL.java:11784)

```

The `org.javamoney.moneta.internal.JDKCurrencyAdapter` class implements the `javax.money.CurrencyUnit` interface, but this does not seem to be picked up.

We tried [the following approach](https://gist.github.com/manuelbernhardt/531261f954afc4342536) but have yet trouble compiling jOOQ (the test compilation fails, for some reason), so here it is in the meanwhile.

**Comment by ccrichter** [comment]
+1

**Comment by lukaseder** [comment]
As of right now, jOOQ's data type system doesn't really support inheritance. You have to provide the exact type of your data type in your converter...

**Comment by manuelbernhardt** [comment]
Ok, thanks. We'll use a custom wrapper and an implicit conversion in Scala for the time being, since casting the `javax.money.CurrencyUnit` back to `org.javamoney.moneta.internal.JDKCurrencyAdapter` every time does not seem all too appealing (and it may not always work)

**Comment by lukaseder** [comment]
Hmm, I can see how this problem appears in your case. There's an internal data type registry that tries to apply the "most suitable" `DataType` to your bind variable (which you're creating via `DSL.value(T)`). If you could provide an explicit `DataType` instead, this problem wouldn't appear. In Scala, this might be feasible by doing something like¨

```scala
def value[T <: CurrencyUnit](t : T) : Field[T] = DSL.value(t, SQLDataType.VARCHAR.asConvertedDataType(new CurrencyUnitConverter()))
```

**Comment by lukaseder** [comment]
Recent jOOQ releases have started deprecating and discouraging usage of this historic static data type registry, which allowed for re-using converters at random places, even if they're not explicitly attached to a data type. See: https://github.com/jOOQ/jOOQ/issues/9492

To re-iterate, the static type registry was a mistake. Its mechanisms predate the custom data type capabilities, and when custom data types were added, the fact that they leak into this registry was overlooked. https://github.com/jOOQ/jOOQ/issues/9492 can't remove the functionality yet as many people have come to rely on it.

But in any case, jOOQ won't "improve" on this broken feature, so I'm closing this issue here. If you wish to extend the various reflective mapping capabilities, we now have the `ConverterProvider` SPI: https://www.jooq.org/doc/latest/manual/sql-execution/fetching/converter-provider/
