### ISSUE TITLE
Add support for client-side DataType validation

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#4543]
Currently, jOOQ offers no way to validate data types like `VARCHAR(length)`, `NUMBER(precision, scale)`, or `UNSIGNED INTEGER` on the client side. It would be useful to be able to:
- Turn on/off automatic validation when binding variables to such types
- Implement custom validators via a new SPI

One of the main reasons why this doesn't exist yet is the great amount of edge-cases that are perhaps not possible to implement correctly at the client side:
- Correct validation of `DOMAINs` (see #681)
- Correct validation in the presence of triggers
- Correct validation in the case of expressions, such as concatenation, arithmetic, etc

There might still be a low-hanging fruit, though. [As suggested by Ross](https://groups.google.com/forum/#!topic/jooq-user/RNwSKXT8Tts), we could at least add something like `DataType.validate(T)` and `DataType.validateConverted(Object)` (or similar) to run explicit (not automatic) client side data type validation. `Binding` implementors would need to implement validation for their `DataType`

---

See also:
- https://groups.google.com/forum/#!topic/jooq-user/RNwSKXT8Tts
- http://stackoverflow.com/q/32552278/521799

**Comment by rgoldberg** [comment]
You might want to change the argument type for `DataType#validate(T)` from `T` to `Object`, since, e.g., if in MySQL you set a varchar column to a numeric value (in jOOQ, e.g., a `DataType<String>` & an `Integer`, respectively), it will automatically convert the number into a varchar.

If you want to allow people to have compile-time checking for "correct" classes being used with a `DataType<T>`, then you could have two methods:

* `DataType#validateStrict(T)`
* `DataType#validateLenient(Object)`

I prefer the two method approach, since each could be useful in different circumstances.

**Comment by lukaseder** [comment]
Good point. This is similar to `Param.setValue(T)` and `Param.setConverted(Object)`.

**Comment by lukaseder** [comment]
I don't think we should implement this, after all.
