### ISSUE TITLE
DSLContext#batch(Query) silently discards queries

### ISSUE THREAD

**Issue by BrentDouglas** [jOOQ/jOOQ#4554]
This issue is caused by the unfortunate signature clash of the two methods`DSLContext#batch(Query)` and `DSLContext#batch(Query...)`. Attempting to call the second of these with a single argument will result in the query being silently ignored. Calls to `DSLContext#batch(Query)` with no following calls to `BatchBindStep#bind` should be treated as if `DSLContext#batch(Query...)` was called instead.

**Comment by lukaseder** [comment]
Thank you very much for reporting this. Nice catch! I will further comment on the pull request: #4555

**Comment by BrentDouglas** [comment]
NP. I run into it all the time when setting up tests whereas in production code  I think it's probably more likely most people will be calling `#batch(Collection<Query>)`.

**Comment by lukaseder** [comment]
I understand. I suspect that overloading might not have been a good idea here, as the semantics are rather different between the overloads...

**Comment by lukaseder** [comment]
Perfect, this is looking good now. Thanks again for reporting and fixing this!

**Comment by steveash** [comment]
Just to provide a counter-example: I just upgraded our code base to 3.7.3. Previously we had frequently done this idiom:
```java
BatchBindStep step = makePreparedQuery(); // query with nulls for placeholders
for (SomeHolder holder : holders) {
  step.bind(...)
}
step.execute();
```
This had the convenient effect that if the holders list was empty, the execute method would have no "bound" values, so it would execute nothing, and everything would keep going.  This felt good to me -- very null object pattern-esque.  Now it executes the query passing nulls -- and thankfully in many places my schema disallows nulls and blows up.  But this is a legacy schema so I'm having to go through every call site where we use batch statements (which is a lot).

I get the original problem was bad too...but would've preferred not affecting existing working behavior and just made the real fix -- changing the batch name to avoid the overload.

I also see [#4558] which seems like it will make the above looping/batching idiom even more cumbersome to code.  I would argue that since the point of using the prepare+bind pattern is when you  want to reduce the cost of sending multiple dml statements -- this looping+batching should have a simple, easy idiom. Please consider that before implementing 4558.

**Comment by BrentDouglas** [comment]
After looking at this again I don't think I correctly understood this part of the API when I sent  my 'fix' for this. I agree with @steveash's that the usage pattern of `#batch(Query)` from the example makes a lot of sense, I had only really considered the fluent style from the docs. I would vote for reverting #4555.

**Comment by lukaseder** [comment]
Thank you for your comments. I will review this during this week, prior to releasing jOOQ 3.8. That null object pattern is certainly a valid point, and I think we have that for `INSERT`. On the other hand, if the null object is applied accidentally, this will lead to users looking for the reason for a long time. We'll have to choose a tradeoff (but then make it the same for all the API).

What's certainly not good is when a batch without any bind values executes the original statement containing bind value placeholders.

Will keep you updated.

**Comment by lukaseder** [comment]
Related discussion: https://groups.google.com/forum/#!topic/jooq-user/7tsasublxf0
