### ISSUE TITLE
Report a possible race issue

### ISSUE THREAD

**Issue by baigd** [jOOQ/jOOQ#4572]
Hi, Developers of jOOQ/jOOQ,

I am writing to report a race issue on use of ConcurrentHashMap. The issue is reported by our tool in an automatic way. Although manually confirmed, it would be a false positive, given we do not know the specification of the program. We would very appreciate if you could check below for details and confirm with us whether it is a real problem. For more information, please refer to our website: http://sav.sutd.edu.sg/?page_id=2845

File: jOOQ/jOOQ/jOOQ/src/main/java/org/jooq/impl/DefaultConverterProvider.java
Location: Line (117/206/156/158/161/165, 177)
Description: 
The check-then-put operations on "paths" in method "path()" are not guarded by any lock, thus the atomicity cannot be guaranteed. The clear operation in line 117 may interrupt the check-then-put operations, thus lead to error results. The put operation in line 177 may also affect the read/write operations (line 156, 158, 161, 165, 206) in the synchronized blocks. Furthermore, for line 185, even synchronization is required by the program specification, the scope can be reduced for the sake of efficiency.

**Comment by ooxi** [comment]
I don't get the report, the method `path()` is `private` and can thus only be called by `DefaultConverterProvider` and `Graph` (please correct me if I'm wrong).

Since there are [only](https://github.com/jOOQ/jOOQ/blob/de4f7fad125d00752cc576a1146ee47f80a8f434/jOOQ/src/main/java/org/jooq/impl/DefaultConverterProvider.java#L150) [two](https://github.com/jOOQ/jOOQ/blob/de4f7fad125d00752cc576a1146ee47f80a8f434/jOOQ/src/main/java/org/jooq/impl/DefaultConverterProvider.java#L161) calls to `path()` and both [synchronize on `path`](https://github.com/jOOQ/jOOQ/blob/de4f7fad125d00752cc576a1146ee47f80a8f434/jOOQ/src/main/java/org/jooq/impl/DefaultConverterProvider.java#L147) I don't see how [`paths.put`](https://github.com/jOOQ/jOOQ/blob/de4f7fad125d00752cc576a1146ee47f80a8f434/jOOQ/src/main/java/org/jooq/impl/DefaultConverterProvider.java#L177) can interfere with [`paths.clear`](https://github.com/jOOQ/jOOQ/blob/de4f7fad125d00752cc576a1146ee47f80a8f434/jOOQ/src/main/java/org/jooq/impl/DefaultConverterProvider.java#L117).

**Comment by lukaseder** [comment]
Don't worry, @ooxi. This report is spam (Check out what else this user is reporting: https://github.com/baigd)
