### ISSUE TITLE
Support Java 8 constructor parameter reflection in DefaultRecordMapper

### ISSUE THREAD

**Issue by rgoldberg** [jOOQ/jOOQ#4627]
Now that jOOQ 3.7+ requires Java 8, can you add a `RecordMapper` implementation that uses Java 8 constructor parameter reflection via `java.lang.reflect.Executable#getParameters()`?

----
See also:
https://groups.google.com/forum/#!topic/jooq-user/xQOloCcM2-4

**Comment by lukaseder** [comment]
Thanks for your suggestion. Very interesting idea, indeed. This certainly makes sense!

**Comment by eric239** [comment]
My plan is to modify `DefaultRecordMapper.ImmutablePOJOMapperWithConstructorProperties`, renaming it and making it work with either `ConstructorProperties` or `Parameter`. Makes sense?

**Comment by lukaseder** [comment]
Thank you very much for your contribution. The implementation looks reasonable at first, but we must be careful about backwards incompatibilities. Right now, if someone relied on the mapping using the order of parameters, and suddenly, by accident, things are reordered because of typos in similar parameter names, then the result will be different. Example:

```sql
SELECT p2, p1 FROM table
```

Mapping this into:

```java
class MyPojo {
  MyPojo(int p1, int p2) { ... } 
}
```

We'll now get a regression, assuming that the naming was made this way on purpose.

The solution is to introduce a new `Settings.mapConstructorParameterNames` flag to opt in to this feature (we can turn this on by default in the next major release).

Also, I'll refactor your solution to make it Java 6 compatible (we still support that in the commercial distributions), and I might look into supporting also calling a constructor whose number of parameters doesn't match the number of fields, which might make a lot of sense, e.g. when doing:

```sql
SELECT id, first_name, last_name FROM customer
```

And then

```java
class Customer {
  // We don't care about the id
  Customer(String firstName, String lastName) { ... }
}
```

If there is only one constructor, then we can call that one in the presence of parameter names.

So, there are three remaining tasks:

- [ ] Add the new setting
- [ ] Make the code Java 6 compatible
- [ ] Support non-exact matches

I'll do the first two right away. Would you be interested in tackling the third?

**Comment by eric239** [comment]
@lukaseder good points, I can take the third one. Should it (non-exact matches) remain "here" or become a separate issue?

**Comment by lukaseder** [comment]
If by "here", you mean this issue, I'd prefer so, yes.

**Comment by lukaseder** [comment]
@eric239 : Are you still interested in doing this? Otherwise, I would take over...

**Comment by eric239** [comment]
@lukaseder I plan to work on this over Thanksgiving (so as to be done by next week)

**Comment by lukaseder** [comment]
Oh wow, I didn't mean to steal your Holidays :)

**Comment by eric239** [comment]
okay @lukaseder so currently the logic as far as the remaining issue is concerned, is as follows:
- find matching (in terms of parameters number) constructor
- if `mapConstructorParameterNames` (the new setting) is ON, and the parameter annotations are present, use them; otherwise fallback on "dumb" `ImmutablePOJOMapper`

So I'm going to let "exact match" logic fire first, and then make assumption that constructors with number of parameters **greater** than the number of fields are "no good", and pick one with the number of parameters _closest_ (but still smaller than) to the number of field. If there're several candidates (with the same parameters count), the choice will be undeterministic. Any problems with this approach?

**Comment by lukaseder** [comment]
Slight adaptation:

- If there is a "matching" (in terms of parameter number) constructor, pick the *first* encountered (non-deterministic) and match by:
  - name if `mapConstructorParameterNames` is true [ new functionality, you've already implemented this ]
  - index otherwise [ old functionality ]
- If there is not "matching" (in terms of parameter number) constructor and `mapConstructorParameterNames` is true, pick the *first* encountered (non-deterministic) constructor [ new functionality ]

Again, we shouldn't judge the user here. It may be perfectly reasonable for a user to run this query:

```sql
SELECT first_name, last_name FROM person
```

And map that to any of these POJOs:

```java
class PersonA {
  public PersonA(String firstName, String lastName, int age) { .. }
}

class PersonB {
  public PersonB(String firstName) { .. }
}
```

The only thing we might need to consider is the fact that public constructors should be given preference to private ones, when picking "the first". This will be done in a separate task, though: #6868. For now, just ignore constructor visibility.

**Comment by eric239** [comment]
@lukaseder I slightly disagree with **not** giving preference to constructor with _fewer_ arguments. Please correct me if I'm wrong, but in your above example, should the code choose 3-arg constructor, `age` will become `0` (the default configured within JOOQ, not explicitly set by user) and that IMO is potentially confusing (as opposed to picking a constructor with fewer arguments, like the 2nd one in your example, where it's up to the user to initialize other fields explicitly.

That said, I trust you know better and having the kind of undeterminism we're discussing is not a good idea anyhow -- the user should avoid it by correlating their queries to the POJO constructors. So I'll proceed as you suggested.

**Comment by lukaseder** [comment]
There are many things to consider here. First off, your *slight* disagreement is an indication that this discussion might as well be void and we should rather throw an exception in case of ambiguity.

Another argument against yours would be the idea that overloaded constructors are usually used when we would really prefer defaulted parameters in the Java language. So, in my above example that we could rewrite as this:

```java
class PersonA {
  public PersonA(String firstName, String lastName, int age) { .. }
  public PersonA(String firstName) {
    this(firstName, null, 0);
  }
}
```

It would be sensible for a constructor with fewer arguments to call the more specific constructor with sensible defaults (defaults usually being the Java language's initialisation defaults, i.e. `null`, `0`, `0.0`, `false`, etc.)

We already have this kind of behaviour throughout jOOQ in different cases, e.g. when calling `Record.get(0, int.class)`, that will get the value at position `0` from within the record and convert it to a primitive `int`. If the value is `null`, then we'll get `0`, not a NPE.

So, as I perfectly agree that nondeterminism is a bad thing (and the JVM / Java reflection API doesn't make any guarantees *at all* about the order of constructors being returned by a class), I guess reducing the specification to a minimum is more maintainable, rather than trying to be smart about hypothesised requirements...

Do note also that jOOQ 4.0 will do away with a lot of nondeterminism and throw exceptions instead. This will also be a good place. We should already add a setting to change this behaviour in the near future: #6871

**Comment by lukaseder** [comment]
Cool, integration tests are working. Thanks a lot for your help with this! Would you be interested in doing more related tasks? E.g. how about this one? https://github.com/jOOQ/jOOQ/issues/6868
