### ISSUE TITLE
UpdateSetStep, InsertSetMoreStep, &c. should have a common ancestor

### ISSUE THREAD

**Issue by ianp** [jOOQ/jOOQ#4718]
There should be a common ancestor interface for the various set steps, which could take the next step type as a parameter, for example:

```java
// proposed new interface
public interface SetStep<S extends SetStep> {
    <T> S set(Field<T> field, T value);
}

// existing interfaces
public interface UpdateSetStep<R extends Record> extends SetStep<UpdateSetMoreStep> {
    <T> UpdateSetMoreStep<R> set(Field<T> field, T value);
}

public interface InsertSetMoreStep<R extends Record>
        extends InsertOnDuplicateStep<R>, SetStep<InsertSetMoreStep>
{
    <T> InsertSetMoreStep<R> set(Field<T> field, T value);
}
```

This would allow users to have code that works for both insert and update when using the SQL building API directly, at present the only way to do this is to use the Records API which is far less flexible.

**Comment by lukaseder** [comment]
I can see where this requirement comes from, but I prefer not to pursue this idea. The problem is that factoring out similar functionality into common super types is hard to get right, and even harder to maintain. I prefer to wait until jOOQ 4.0 when we cleanly refactor the DSL API and the model API (in case of which you would always be using the model API for these cases)

Note also, you might think that you'll be able to use the new `SetStep` as an intermediary reference type to abstract over `UpdateSetMoreStep` and `InsertSetMoreStep`. That's not true. Given:

```java
public interface SetStep<S extends SetStep<S>> {
    <T> S set(Field<T> field, T value);
}
```

There is actually no meaningful type that you can write down on the left-hand side of an assignment. I.e.

```java
// This is useless because of the wildcard
SetStep<?> set = // insert or update
set.set(field1, value2)
   .set(field2, value2)
   .execute(); // execute() is not available on S, because we don't know S
```

Does this make sense?

I've blogged about the caveats of recursive generics here:
http://blog.jooq.org/2013/06/28/the-dangers-of-correlating-subtype-polymorphism-with-generic-polymorphism

Recursive generics are useful only for *internal* API, i.e. for use *within* the type hierarchy. As soon as they leak the type hierarchy, they become rather useless types...

**Comment by ianp** [comment]
Makes sense, it just makes code dealing with this API a bit copy-pastey. Interesting to hear about jOOQ 4.0 though!

**Comment by lukaseder** [comment]
Yes, I perfectly understand the copy-pastey bit. I'm trying to think how this could be best solved otherwise. Do you have access to a `Record` containing all the changed bits? There's a `set(Record)` method in both `INSERT` and `UPDATE` statements...

**Comment by ianp** [comment]
No, not at the moment. It's not a huge problem for me, there are only a couple of places in my app where I update the DB, and the plan is to reduce this over time.

**Comment by lukaseder** [comment]
OK, I see. Thank you anyway for your feedback. It's good to get a feel about the pain points of the API. Perhaps there is a low-hanging fruit yet to be discovered in this area.
