### ISSUE TITLE
Add internal API to configure indentation of generated code

### ISSUE THREAD

**Issue by hwellmann** [jOOQ/jOOQ#4848]
Tabs are evil. There is no excuse for using them, not even in generated code. 

You may disagree, but even then users should have a choice to configure the code generator to generate code that matches their own coding style.

Unfortunately, this is not possible at the moment, not even by extension, since the methods you'd have to override are final. (`JavaGenerator.newJavaWriter()`, `JavaWriter.print()`).

**Comment by lukaseder** [comment]
Excellent first impression ;-)

Granted, I had thought about this before. It would be nice if such things could be configured. But then again, once we allow for re-configuring tabs vs. spaces, someone else will come and claim

- Curly braces on the same line are evil
- Parameter lists immediately enclosed by parens (no whitespace) are evil
- Exceeding the print margin of 80 characters is evil

Instead of spending lots of time implementing sophisticated formatting rules like the above, how about using a re-formatting tool right after code generation instead? E.g.
http://mvneclipsefmt.sourceforge.net/format-mojo.html

**Comment by hwellmann** [comment]
Nobody should expect anybody else to like their coding conventions - that's not the point...

The question is, how open should a framework be for customization. Final classes or methods just reduce options for users. Any user overriding a framework method is doing so at their own risk. 

In this concrete case, if the said methods were not `final`, deriving `NoTabsJavaGenerator` would be fairly easy and straightforward, compared to finding and configuring a formatter plugin, which will also come with defaults that some users won't like...

The plugin you mentioned is 5 years old and does not exist on Maven Central. The Eclipse formatter was reimplemented for Mars with a number of incompatible changes, so I wouldn't expect that plugin to work out of the box.

**Comment by lukaseder** [comment]
> In this concrete case [...]

I agree in this case. There doesn't seem to be a good reason for `final` for those methods, specifically because the current status quo of the code generator is far from where we'd like it to be e.g. in jOOQ 4.0. I've created an issue to remove those `final` keywords: #4855.

You're right, I suggested an outdated plugin. I can see that now. It was the first one I've found on Google. After some additional research, surprisingly, also forks of that plugin don't really seem to be well maintained. For this particular case, since there isn't a quick win in current versions of jOOQ, another suggestion would be to post-process files using maven/ant, by simply replacing all tabs by spaces after code generation.

**Comment by lukaseder** [comment]
Relevant in this context: :)
http://ukupat.github.io/tabs-or-spaces/

I have added internal API that will help override the tab/spaces behaviour. There will not be any public API / configuration for this (yet), as I prefer to look at such things more thoroughly.

jOOQ 3.8 will replace tabs by 4 spaces by default: #4868
