### ISSUE TITLE
Add support for returning unique constraints from Meta Table<R>.getKeys()

### ISSUE THREAD

**Issue by dazed19** [jOOQ/jOOQ#5179]
Hi

I have defined a primary key and an extra unique index on an H2 database - but when trying to access the details for this via Table<R>.getKeys() only the primary key is returned.

Should this also return the second "index" ?  if no, then is there a way to do that?

I attach a database definition file and a short java sample which prints via jOOQ and H2 meta interfaces.

This prints out (in my environment)

```
> Connection
*** Direct via H2 getMetaData()
Table [PROJECT]
   Index[INDEX_18] unique[true]
       [1] [GROUP_ID]
       [2] [NAME]
   Index[PRIMARY_KEY_18] unique[true]
       [1] [ID]
   Index[PROJECT_IN_GROUP_FK_INDEX_1] unique[false]
       [1] [GROUP_ID]
*** Direct via jOOQ .meta()
TABLE [PROJECT]
    Unique Key Count [1]
    Key 
      [1] [ID]
    Foreign Key Count [1]
    Foreign Key 
      [1] [GROUP_ID]
```

Which shows that the entry for "INDEX_18" is not showing, event though it's unique

[H2UniqueKeysExample.zip](https://github.com/jOOQ/jOOQ/files/198061/H2UniqueKeysExample.zip)

**Comment by lukaseder** [comment]
I suspect that this is because of jOOQ's understanding of a "key", being a "constraint", not an index. Can you confirm that the behaviour will be different if, instead of creating a unique index you create a unique constraint, you'll get the constraint info also from jOOQ meta's keys?

**Comment by dazed19** [comment]
If I remove the "CREATE UNIQUE INDEX" and add

`CREATE TABLE "PUBLIC"."PROJECT" (
      ...
      CONSTRAINT "BY_GROUP_CONSTRAINT" UNIQUE ("GROUP_ID", "NAME")
);`

Then I get 
`*** Direct via H2 getMetaData()
Table [PROJECT]
   Index[BY_GROUP_CONSTRAINT_INDEX_1] unique[true]
       [1] [GROUP_ID]
       [2] [NAME]
   Index[PRIMARY_KEY_18] unique[true]
       [1] [ID]
   Index[PROJECT_IN_GROUP_FK_INDEX_1] unique[false]
       [1] [GROUP_ID]
*** Direct via jOOQ .meta()
TABLE [PROJECT]
    Unique Key Count [1]
    Key 
      [1] [ID]
    Foreign Key Count [1]
    Foreign Key 
      [1] [GROUP_ID]`

So, no - I don't appear to get the non-primary key unique index via that method.

**Comment by lukaseder** [comment]
Hmm, my bad. It appears that this is not implemented. Will fix immediately. The index listing will be fixed separately in #5181

**Comment by lukaseder** [comment]
I won't fix this as a defect (which would be merged to patch releases), as the change of behaviour might be unexpected in some client code.

**Comment by lukaseder** [comment]
Hmm, I remember now why this hasn't yet been implemented. JDBC's `DatabaseMetaData` doesn't offer any means of distinguishing between the `UNIQUE` constraint and the auxiliary index that is used to enforce the constraint. The `getKeys()` method should really return the constraint name, in order to allow users to drop the constraint, for instance.

There are plans of merging jOOQ-meta back into the jOOQ core library, in order to be able to query the dictionary views for these things, when JDBC lacks functionality.

I'll postpone this to the next release in order to fix this more thoroughly

**Comment by dazed19** [comment]
No worries - I'm working round it at the mo - will track these for the future - are there any expected dates for 3.8 and 3.9?

**Comment by lukaseder** [comment]
3.8 is due this month, which is why I postponed :) 3.9 doesn't have any date attached, yet.

**Comment by lukaseder** [comment]
See also: #7105

**Comment by lukaseder** [comment]
Supporting the export of (unique and non-unique) indexes will be reviewed via #5181. This issue will discuss exporting unique constraints.

**Comment by lukaseder** [comment]
Looking into this now in the context of general improvements to `Meta` implementations and DDL interpretation.

**Comment by lukaseder** [comment]
A thorough solution for this would be move the dictionary views from `jOOQ-meta` to `jOOQ` and make that logic more reusable: https://github.com/jOOQ/jOOQ/issues/8655 I'm wary of this, because:

- That's a lot of new public API, which I don't like to maintain backwards compatibly (the generated classes)
- That's a lot of byte code that most people don't need

Maybe, there will be a solution to https://github.com/jOOQ/jOOQ/issues/8655 eventually, but in the meantime, why not just hard-code all the relevant dictionary view tables to query for *unique constraints only* in the core library, and use the `DatabaseMetaData::getIndexInfo` query to load the column information, etc. Seems like a viable compromise.

**Comment by lukaseder** [comment]
OK, so this is what we'll do for now:

- jOOQ-meta will have a new `ResultQueryDatabase` internal API, which is implemented e.g. by `H2Database`, `PostgresDatabase`
- That API provides the `ResultQuery` for all unique keys. It must have a single bind value for the input schema
- We generate a `.properties` file containing the SQL per dialect
- That properties file is used by `MetaImpl` to run the query for all unique contraints

That way, the logic is "shared", and always in sync.

**Comment by lukaseder** [comment]
Support will be added for (list to be enhanced):

- [x] CockroachDB
- [x] H2
- [x] MariaDB
- [x] MemSQL
- [x] MySQL
- [x] PostgreSQL

Reusing this logic was a good decision. It already helped prevent work around this issue again: #5213

**Comment by lukaseder** [comment]
I will continue listing dialect support in https://github.com/jOOQ/jOOQ/issues/10823, which will also collect dialects for whom this will not yet be supported in jOOQ 3.15.
