### ISSUE TITLE
Add support for an ACL VisitListener

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#5197]
Fine-grained grants are not always available to clients of a database, either because the database does not have a security / ACL subsystem, or because the client application cannot, for operational reasons, profit from these features.

In this case, an out-of-the-box ACL `VisitListener` provided by jOOQ would be of great help to prevent access to certain database objects on a client level.

This security feature is not meant to fully replace the database's security and privilege system, but to enhance it. It will always be possible to bypass this security implementation with other `VisitListeners`, or with plain SQL.

**Comment by JamesXNelson** [comment]
This would be great for us.  We have our own abstraction on top of our db connection used to modify certain tables, where we want all writes to go through that abstraction, but for all other tables, use of Jooq is preferred.  Being able to restrict writes to those certain tables via Jooq would be extremely useful for us.

**Comment by lukaseder** [comment]
Thank you very much for your feedback, @JamesXNelson. I'd love to learn more about your use-case. Am I understanding you right that you'd like to implement something like simple `SELECT`, `INSERT`, `UPDATE`, `DELETE` grants inside of jOOQ? What keeps you from doing that in the database? Are those restrictions somehow transaction-bound (rather than user-bound as in most databases)?

Note, to a certain degree, you can already do write restriction today using jOOQ's `VisitListener` SPI. This issue is merely about simplifying the task for users by providing an out-of-the-box implementation. More details here:
https://blog.jooq.org/2015/06/17/implementing-client-side-row-level-security-with-jooq

**Comment by JamesXNelson** [comment]
Ah, sorry; I haven't been keeping up w/ github notifications recently (new parent).

Our use case is that we migrated to sql from a more... no-sql-y environment, and part of that work included an abstraction layer over our various entity groups, which served as a nice abstraction for `SELECT INSERT UPDATE DELETE` crud abstractions.  This abstraction layer also included event firing to other java services (which we want to keep in place).

So, for those tables that need the extra event handling, we do not want someone to just grab a DSL and bypass the abstraction layer.  Triggers don't make a lot of sense, since many call out to other web services instead; I know it could be done, but would rather keep that load out of db if possible.

Most of our DB access does not use this legacy layer anymore, but those that do, function well as-is.  Unless there is a way to get `NOTIFY` to ping java for us, I don't see that changing, and for now, we just use strict code review to prevent mistakes (ick).  Being able to enforce that in Jooq would be a nice load off my mind; no need to pay close attention if the machine can do it for me. :-)

**Comment by JamesXNelson** [comment]
(we use psql, btw.  Knowing your penchant to materialize obscure, effective solutions, I figure the more you know about the problem space, the better)

Thanks for all the great work on Jooq, btw!

**Comment by lukaseder** [comment]
Hey, congrats! That changes everything ;)

Hmm, I actually don't know much more about your use-case now, I'm afraid - at least in the context of an ACL `VisitListener` - are you sure you posted this to the right issue? Because there's another issue talking about NOTIFY. This one is about emulating grants...

**Comment by lukaseder** [comment]
The specific implementation (via `VisitListener`) is debatable. We now have a better way to transform SQL using jOOQ 3.16 `QOM` API traversal methods:
https://www.jooq.org/doc/latest/manual/sql-building/model-api/model-api-traversal/

Other than that, this issue is just a duplicate of: https://github.com/jOOQ/jOOQ/issues/2682
