### ISSUE TITLE
Can not call UPDATE using an WITH UPDATE ... RETURNING clause

### ISSUE THREAD

**Issue by teoincontatto** [jOOQ/jOOQ#5201]
Hi,

It seem that it is not possible to write SQL sentence of this kind using jOOQ:

```
    WITH my_returning_update AS (
        UPDATE my_table
        SET a = a + 1
        FROM other_table
        WHERE b = ?
        RETURNING my_table.a
    )
    UPDATE other_table
    SET b = a
    FROM my_returning_update;

```

This is perfectly correct in PostgreSQL and the workaround I found was to put the SQL code in a function. I had tried translating it with following code:

```
    dsl.with("my_returning_update").as(
        DSL.update(MY_TABLE)
            .set(MY_TABLE.A, MY_TABLE.A.plus(1))
            .from(OTHER_TABLE)
            .where(OTHER_TABLE.B.equal(b)
            .returning(MY_TABLE.A)
        )
        .update(OTHER_TABLE)
        .set(OTHER_TABLE.B, DSL.field("a"))
        .from(DSL.table("my_returning_update"))
```

But `as` actually only accept a `select` as an input. Did I miss something?

**Comment by lukaseder** [comment]
Thank you very much for your feature request. This is a known limitation of the jOOQ API and will be fixed with:

- https://github.com/jOOQ/jOOQ/issues/4474 (Allow to form CTE from plain SQL or from ResultQuery)
- https://github.com/jOOQ/jOOQ/issues/3185 (Let InsertResultStep<R>, UpdateResultStep<R>, DeleteResultStep<R> extend Select<R>)
