### ISSUE TITLE
jOOQ 3.8 cannot select null values for enums

### ISSUE THREAD

**Issue by reardencode** [jOOQ/jOOQ#5232]
Caused by https://github.com/jOOQ/jOOQ/blob/edd0ed3b875d7c68c07ab80504ea75d7078a1b36/jOOQ/src/main/java/org/jooq/impl/DefaultBinding.java#L1895

Why was this changed?  Enums can be null and null is meaningfully different from any of the enum values.

**Comment by lukaseder** [comment]
Thank you very much for reporting. I suspect this is for the PostgreSQL database, right?

The change was implemented in the context of https://github.com/jOOQ/jOOQ/issues/4427, as Scala doesn't really have any enum types.

The reason for this change seems to be abusing `null` as a dummy enum value in order to get a hold of an `EnumType` reference. See: https://github.com/jOOQ/jOOQ/blob/edd0ed3b875d7c68c07ab80504ea75d7078a1b36/jOOQ/src/main/java/org/jooq/impl/DefaultBinding.java#L2247

But obviously, you're right and that practice is unsound. Will look into fixing this ASAP

**Comment by reardencode** [comment]
Yep, PostgreSQL database.

Ah, yes, the change makes sense in that context, could put short circuit `if (literal == null) return null;` in the two callers of `getEnumType()` that deal with input and output values for Postgres.

Thanks!

**Comment by lukaseder** [comment]
The fix is not to abuse `null` ;) One must never use the absence of a signal as a signal. Shame on the 3.8.0 implementation. This is now fixed for 3.9.0 and will be merged to jOOQ 3.8.1 soon.

**Comment by jeli8** [comment]
Hi Lukas,
I had the same issue. quick question: When do you plan to release 3.8.1 with that fix?
It's very important for us.
Thanks you very much!

**Comment by lukaseder** [comment]
@jeli8 : By the end of the week. In the meantime, you can patch your distribution with this fix, directly:
https://github.com/jOOQ/jOOQ/commit/46c6923de253a87c40824035bd38a859a6a95bf2
