### ISSUE TITLE
PostgreSQL SMALLINT function arguments should always be cast explicitly

### ISSUE THREAD

**Issue by jsnowacki** [jOOQ/jOOQ#5264]
I have a function that takes and returns SMALLINT:
```sql
CREATE FUNCTION get_value (_key SMALLINT) RETURNS SMALLINT AS $$
DECLARE
	__value SMALLINT;
BEGIN
	SELECT value INTO __value FROM a_table WHERE key = _key;
	RETURN __value;
END;
$$ LANGUAGE plpgsql;
```
Everything worked well until I did not do anything with the key. When I did I got the error that there is no get_value function with INTEGER type argument after calling the function a follows:
```java
DSL.select(getValue(max(key).add(1)).from(table) ...
```
Since add with number casts value to Integer, which causes the error, I did the following:
```java
DSL.select(getValue(max(key).add(1).cast(Short.class)).from(table) ...
```
but I was still getting the same error with type. I did use the `cast(..., Short.class)` as well with the same result. After the generated query inspection it came out that despite using cast the function always looks like follows:
```sql
"get_value"("_key" := (max("key") + ?))
```
Hence, the cast is not done to the argument. Also the constant is not shown thus I am not sure what happens there.

The workaround is to explicitly add short constant to the key, which preserves the type:
```java
DSL.select(getValue(max(key).add((short)1)).from(table) ...
```
The generated SQL looks as follows:
```sql
"get_value"("_key" := (max("key") + 1))
```
While adding short explicitly is not a massive problem, I am expecting a cast to appear if I do it explicitly in the code.

Thanks a lot for the help.

EDIT: Just to clarify: I'm using jOOQ 3.8.0 and PostgreSQL 9.5; the issue is also present with jOOQ 3.7.3; I haven't tried any other databases.

**Comment by lukaseder** [comment]
I'm sorry for the delay in dealing with this issue.

Thank you very much for your detailed report. Indeed, it looks like some expressions are automatically widened to the `integer` type in PostgreSQL, just like in Java. Without any explicit cast back to `smallint`, PostgreSQL cannot resolve the function call from the argument types. This also happens when you call your `get_value` function using an inlined `integer` variable:

```sql
get_value(1)
```

jOOQ should always generate a SQL cast for `Byte` and `Short` function arguments of stored functions in PostgreSQL.

**Comment by lukaseder** [comment]
The explicit cast is not being passed to the function because the expression being cast (in jOOQ) is still of type `Short`, so the cast is ignored. Expressions are not evaluated for their various types in order to see if type promotion is needed (this wouldn't be possible to model with Java generics). Thus, only the left-hand side of an expression's types is retained. You can work around the current limitation by writing:

```java
val(1).add(max(key)).cast(Short.class)
```

Or, by casting explicitly with plain SQL:

```java
field("cast({0} as smallint)", Short.class, max(key).add(1))
```
