### ISSUE TITLE
Add ability to inject custom instance of ObjectMapper into jooq Binding

### ISSUE THREAD

**Issue by mjburghoffer** [jOOQ/jOOQ#5266]
Right now, in code, I don't see any way to non-statically inject an instance of an `ObjectMapper` into my custom postgres-json-jackson binding.

The generated code looks something like this:

``` java
public final TableField<SchemaRecord, JsonNode> SCHEMA_ = createField("schema", org.jooq.impl.DefaultDataType.getDefaultDataType("jsonb"), this, "", new PostgresJsonJacksonBinding());
```

The interesting parts of the class looks like this:

``` kotlin
@Singleton class PostgresJsonJacksonBinding
@Inject constructor(
    val mapper: ObjectMapper
) : Binding<Any, JsonNode> {
    // for codegen, not for regular use!
    constructor() : this(ObjectMapper())
}
```

Unfortunately, we are using Guice and would like to inject our own instance of `ObjectMapper` (with custom modules, config, etc).  Not to mention, it is highly recommended that your app does not construct an `ObjectMapper` wherever it needs one, as it is an incredibly expensive operation.

Ultimately we will need to create some sort of hacky workaround for this to work at the moment, it would be nice to have support for DI frameworks out of the box, but also to be able to customize bindings with these dependencies.

**Comment by lukaseder** [comment]
Thanks a lot for your feature request. Currently, the code generated by jOOQ makes a lot of strong assumptions about the nature of the generated code, mostly that it is statically initialised by a class loader, which is a concept quite orthogonal to DI. These assumptions are coupled with the runtime, which is why a lot of these parts are not as flexible as some users might desire.

> Not to mention, it is highly recommended that your app does not construct an ObjectMapper wherever it needs one, as it is an incredibly expensive operation.

Of course, your statement is based on *other* assumptions, namely those of assuming that it is a good idea to make constructing a binding an expensive operation (or that DI is good and static initialisation is "hacky" :) ). These assumptions are orthogonal to each other. In our (= the code generator's) opinion, converters and bindings should be stateless and should not incur in heavy initialisation work.

I'm not convinced that, at the current stage, we should rework all of the generated code to be DI-ready. DI is a very fundamental and opinionated concept. We'd first need to establish a lot of advantages that we would gain from going the DI way in generated code. These advantages would span much more than just the initialisation of bindings. In principle, each and every object (catalogs, schemas, tables, fields, sequences, routines, etc.) would need to be injectable rather than statically initialised. That's just not how jOOQ is designed right now.

So, perhaps, there's another solution to your problem that might make this work for you in a much more easy way? What is the reason why you need to pass this `ObjectMapper` to your binding?

**Comment by mjburghoffer** [comment]
Sorry if I came off as opinionated.  The example for accessing postgres' `jsonb` functionality on [jooq's website](http://www.jooq.org/doc/3.8/manual/code-generation/custom-data-type-bindings/) has this bit of code:

```java
            @Override
            public JsonElement from(Object t) {
                return t == null ? JsonNull.INSTANCE : new Gson().fromJson("" + t, JsonElement.class);
            }
```

This code example constructs a `Gson`, which is very similar to constructing a new `ObjectMapper`.  Either way, it seems to be the recommended way for turning arbitrary java objects into jsonb for postgres.  Even if one does not use DI, it would still be useful to have some mechanism for supplying this context to the `Binding` in some way or another.

**Comment by lukaseder** [comment]
> Sorry if I came off as opinionated

I didn't mean to imply that, sorry. DI (as a philosophy, design approach) is opinionated, and jOOQ currently cannot (easily) accommodate that opinion.

Thanks for pointing out that `Gson` example. That's not a good example, we should improve it. I've registered #5273 for this. In this particular case, it's probably sufficient to just create a static `Gson` instance, as the implementation is thread safe (if I'm not mistaken), and the binding is referenced from the static meta model.

> Even if one does not use DI, it would still be useful to have some mechanism for supplying this context to the Binding in some way or another.

Do you have an example use-case in mind where the context is specific to the individual instantiation of a binding?

**Comment by lukaseder** [comment]
See also: https://github.com/jOOQ/jOOQ/issues/11146

**Comment by lukaseder** [comment]
Another example of this use-case is here: https://stackoverflow.com/q/68984062/521799

**Comment by lukaseder** [comment]
Making generated code more DI friendly has been requested a few times, but it's currently not possible without completely re-designing how this works, i.e. the entire schema, which is statically initialised, would have to be initialised dynamically, meaning that identifiers could no longer be static imported.

This is currently out of scope. The main reason why people request this is because their mapper initialisations are too slow, but it's easily possible to bypass that using more static initialisation. DI doesn't *have to* reverse relationships to inject dependencies. Dependencies can also be looked up like in the "old days", e.g. using JNDI or some spring static context lookups...

**Comment by mjburghoffer** [comment]
Thanks for doing such a good job keeping issues up to date!  Ultimately we solved this problem (a very long time ago) doing something like below.  Just make a static reference that is injected before jooq does any querying, and make sure your bindings/converters use said reference.

```kotlin
/**
 * Acts as a reference to the Jackson [ObjectMapper] so that jooq can access it.
 * We cannot "instantiate" jooq, so it needs a static reference to the [ObjectMapper]
 * for use in generated code.  As a result, we want a place to put the configured reference.
 *
 * At startup time, this should be filled in by whatever service is running.
 */
object ObjectMapperJooqReference {
    @set:Inject
    var jooqObjectMapper: ObjectMapper by notNull()
}


abstract class AbstractJacksonConverter<T> : Converter<JSONB, T> {

    protected abstract val toClass: Class<T>
    protected abstract val toType: TypeReference<T>

    protected open val mapper: ObjectMapper
        get() = ObjectMapperJooqReference.jooqObjectMapper

    protected val reader by lazy {
        mapper.readerFor(toType)
    }

    protected val writer by lazy {
        mapper.writerFor(toType)
    }

    override fun from(databaseObject: JSONB?): T? {
        return databaseObject?.let { reader.readValue(it.data()) }
    }

    override fun to(userObject: T?): JSONB? {
        return userObject?.let { JSONB.valueOf(writer.writeValueAsString(it)) }
    }

    final override fun fromType(): Class<JSONB> = JSONB::class.java

    final override fun toType(): Class<T> = toClass
}


abstract class AbstractJacksonBinding<T> : Binding<JSONB, T> {

    abstract override fun converter(): AbstractJacksonConverter<T>

    override fun sql(ctx: BindingSQLContext<T>) {
        ctx.render().visit(DSL.value(ctx.convert(converter()).value())).sql("::jsonb")
    }

    override fun register(ctx: BindingRegisterContext<T>) {
        ctx.statement().registerOutParameter(ctx.index(), Types.VARCHAR)
    }

    override fun set(ctx: BindingSetStatementContext<T>) {
        ctx.statement().setString(
            ctx.index(),
            ctx.convert(converter()).value()?.data()
        )
    }

    override fun get(ctx: BindingGetResultSetContext<T>) {
        val value = ctx.resultSet().getString(ctx.index())?.let(JSONB::valueOf)
        ctx.convert(converter()).value(value)
    }

    override fun get(ctx: BindingGetStatementContext<T>) {
        val value = ctx.statement().getString(ctx.index())?.let(JSONB::valueOf)
        ctx.convert(converter()).value(value)
    }

    override fun set(ctx: BindingSetSQLOutputContext<T>?) {
        throw SQLFeatureNotSupportedException()
    }

    override fun get(ctx: BindingGetSQLInputContext<T>?) {
        throw SQLFeatureNotSupportedException()
    }
}
```
