### ISSUE TITLE
use of truncate with aliased table uses aliased name instead of table name

### ISSUE THREAD

**Issue by klobusnik** [jOOQ/jOOQ#5267]
Jooq 3.5. Postgresql 9.5.
**create.truncate(...tables.Person.PERSON.as("p")).execute()** will create **"truncate table p"**. 
I think it makes sense that even when table is aliased it would result to **"truncate table person"**

**Comment by lukaseder** [comment]
Thank you very much for your suggestion.

I think that it would be unwise to make this change as the expected behaviour of passing an aliased (renamed) table to any statement is for jOOQ to pick up the alias, not the original name, regardless if the table exists. After all, why rename the table to something that is not intentional?
