### ISSUE TITLE
The `mysql`.`proc` table is unavailable. Stored procedures cannot be loaded. Check if you have sufficient grants

### ISSUE THREAD

**Issue by forchr** [jOOQ/jOOQ#5275]
Executing query          : SELECT count(*) FROM PROC
SQL exception            : Exception while executing meta query: Unknown table 'proc' in information_schema

**Comment by lukaseder** [comment]
Thank you very much for your report. The `MySQLDatabase` class from jOOQ-meta runs this query to check if the `Proc` table is available in any given MySQL installation. If it is not for some reason, jOOQ cannot generate any stored procedures for MySQL and a warning is logged.

This is the expected behaviour. Hope this helps,
Lukas
