### ISSUE TITLE
Improve DSLContext / AutoCloseable API

### ISSUE THREAD

**Issue by phile314** [jOOQ/jOOQ#5328]
According to the documentation, the close() method on a DSLContext may or may not close the underlying connection, depending on how the DSLContext was created:

http://www.jooq.org/javadoc/3.8.0/org/jooq/DSLContext.html#close--

However, the ``close()`` method is always present and I can tell from my own experience that it is easy to assume that DSLContext.close() will close the underlying connection. It would be much better if the DSLContext instance returned by ``DSL.using(Connection connection, ....)`` would not implement the AutoCloseable interface. This would make it more obvious that the DSLContext will not close the connection in this case and that one has to take care of this oneself.

**Comment by lukaseder** [comment]
Thank you very much for your feedback, Philipp. This might indeed appear a bit confusing, but it is correct the way it stands right now, specifically because the `AutoCloseable` contract was changed between Java 7 and 8:
https://blog.jooq.org/2015/12/02/a-subtle-autocloseable-contract-change-between-java-7-and-java-8

Since Java 8, it is now allowed for an `AutoCloseable` not to contain any resources that need closing. This is important for `java.util.stream.Stream` to extend `AutoCloseable`, as only very few streams really contain resources.

But even if a `Stream` "contains" a resource (i.e. operates on a resource-based structure), this doesn't mean it's responsible for it. Take `BufferedReader.lines()`, for instance. Calling `close()` on the resulting `Stream<String>` has no effect, because it's not the stream's responsibility to close the reader. Likewise, it's not (always) the `DSLContext`'s responsibility to close your `Connection`. In particular, if you provide `DSLContext` with an *external* resource, then you have to close that resource yourself, e.g.:

```java
// You close the connection
try (Connection connection = ...) {

    // DSLContext is not a resource:
    DSLContext ctx = DSL.using(connection);
}
```

If, however, you let the `DSLContext` create its own connection, then the `DSLContext` will close it again, but you will need to treat the `DSLContext` as a resource:

```java
// DSLContext is a resource
try (DSLContext ctx = DSL.using(url, username, password)) {
    ...
}
```

I hope this clarifies things.

I agree that the Java 8 `AutoCloseable` contract can be a bit confusing, but in any case, I don't think that closeability is a strong enough concept to introduce an entirely new type here (we'd have similar discussions about new types for transactionality, asynchronicity, sql dialects, etc...)

**Comment by phile314** [comment]
I definitely agree that this is not a bug nor violates any contracts. While I do not agree that this should be a Wontfix, your explanation sounds reasonable and I can see that this is not a clear-cut decision.

**Comment by lukaseder** [comment]
> While I do not agree that this should be a Wontfix

We could switch to "works for me" :)

(sorry, couldn't resist). I do agree that this is confusing. The *best* option would be if Java supported first class intersection types to have the API `DSL.using(String, String, String)` return `DSLContext & AutoCloseable`. A lot of JDK API would then implement this pattern, rather than making the relevant type itself extend/implement `AutoCloseable` (e.g. `Stream & AutoCloseable`). Unfortunately, this is not the case, so the only other possible fix is the undesireable nominal subtyping for each and every combination of types that might make sense at some point.

Of course, if you see any other solution, I'm very happy to discuss!

**Comment by phile314** [comment]
That was more wishful thinking than having a concrete proposal on my part ;-)

I don't think there is any other "completely correct" solution than nominal subtyping. One alternative is to make the names sound more dangerous, but it's hard to come up with good names. E.g. ``usingUnmanaged`` or ``usingUnsafe``, but I'm not sure thats worth the effort. Any solution to this problem will most likely also break backwards compatibility, which is rather unfortunate.

**Comment by lukaseder** [comment]
> That was more wishful thinking than having a concrete proposal on my part ;-)

I can totally relate to that :)

I agree that renaming the methods is not worth the effort. After all, the fact that `DSL.using(String, String, String)` returns a resource that must be closed is not the main feature or the method, so I think that, as it stands now, the current Javadoc sufficiently establishes the contract.

**Comment by lukaseder** [comment]
I'm re-iterating the justified criticism expressed in this issue via https://github.com/jOOQ/jOOQ/issues/10512, as it is an often recurring problem for new users of the jOOQ API, especially if they use static code analysis or compiler resource leak detection.
