### ISSUE TITLE
Wrong defaults for <tableValuedFunctions/> in jOOQ Open Source Edition

### ISSUE THREAD

**Issue by rpokorny** [jOOQ/jOOQ#5349]
According to various comments that I've seen around the Internet, Table-valued functions are supposed to be exposed as Table classes, and also as functions in Routines.java that take the same parameters as the backing database function.  It appears that this is no longer the case in jOOQ 3.8.  I have created a simple example project to reproduce the issue here: https://github.com/rpokorny/jooq-table-function-bug

If you change the version of jOOQ used, you can see that this issue first appears with jOOQ 3.8.0.  

If this is not a bug, but rather is a deliberate API change, then please update the documentation as I cannot figure out the correct way to use table-valued functions in a FROM clause with jOOQ 3.8.0 and higher.

**Comment by lukaseder** [comment]
Thank you very much for your explanations and report.

There has been a change in 3.8, indeed. There's a flag to turn off that feature (https://github.com/jOOQ/jOOQ/issues/4838), but I suspect that's not it, in your case...

Will investigate this as soon as possible

**Comment by lukaseder** [comment]
Thanks again for your report. This is a regression produced by https://github.com/jOOQ/jOOQ/issues/4825, which appears only in the jOOQ open source edition. jOOQ 3.8 has introduced a new `<tableValuedFunctions/>` flag, which is by default turned on for all databases except Oracle (for backwards compatibility).

Unfortunately, because of the Oracle related check, this logic is shipped only with the commercial distributions.

As a workaround, you can explicitly set the flag in your code generator configuration:

```xml
<configuration>
  <generator>
    <database>
      <tableValuedFunctions>true</tableValuedFunctions>
```
