### ISSUE TITLE
update with NULL value in Jooq v.3.8.2

### ISSUE THREAD

**Issue by sytolk** [jOOQ/jOOQ#5355]
I want to set NULL for EXECUTION column and this works with jooq v.3.7.3
```java
dsl.update(MISSION_USERS).set(MISSION_USERS.EXECUTION, DSL.val(null)).execute();
```
But now I have update to jooq v.3.8.2 and have this error:
```
MissionUsersDAOImpl.java:[169,178] reference to val is ambiguous
[ERROR] both method val(java.time.OffsetDateTime) in org.jooq.impl.DSL and method val(java.util.UUID) in org.jooq.impl.DSL match
```
I can`t write direct NULL value in .set(FIELD,NULL) how can I fix this in new jooq version ?

**Comment by lukaseder** [comment]
Indeed, in jOOQ 3.8, we introduced new overloads for the `val()`, `value()` and `inline()` methods. These overloads help making the right data type choice already at compile time, rather than at runtime. This is at the expense of a slight backwards incompatibility, namely when passing the Java `null` literal to the method, which is now ambiguous.

You can work around this limitation by specifiying the appropriate data type via a cast:

```java
// For example: String
DSL.val((String) null)
```

Note, the same can be done directly on the `set()` method:

```java
.set(MISSION_USERS.EXECUTION, (String) null)
```

I hope this helps

**Comment by sytolk** [comment]
Thanks @lukaseder it`s works

**Comment by kisai** [comment]
what about a long parameter? when I try casting null to long it is a compilation error.

**Comment by lukaseder** [comment]
@kisai Thank you for your message. Would you mind creating a new issue with some more details?

**Comment by eduramiba** [comment]
Would it be possible to add a new method `setNull(Field<T> field)` to `UpdateSetStep`?
Thank you!

**Comment by lukaseder** [comment]
@eduramiba I don't disagree. We could add this: https://github.com/jOOQ/jOOQ/issues/8724

**Comment by eduramiba** [comment]
Great!
