### ISSUE TITLE
Plain SQL batches produce wrong INFO messages about bind value count mismatches

### ISSUE THREAD

**Issue by adrianandrei-ca** [jOOQ/jOOQ#5362]
Create a batchBindStep class with a plain text update statement:

```java
String updateQuery = "UPDATE someTable SET col1 = ? WHERE id = ?";
BatchBindStep batch = dslContext.batch(updateQuery);
batch.bind("none", 123);
batch.execute();
```

You will see an INFO message saying:

```
Bind value count         : Batch bind value set 0 has 2 values when 0 values were expected
```

The update goes through but when the batch has hundreds of binds, you have a lot of lines polluting the log.

Regards,
Adrian

**Comment by lukaseder** [comment]
Thank you very much for reporting. I can confirm this. Those messages are wrong and do create a lot of noise.

(In our previous conversation per E-Mail, I must have misunderstood you. I thought the batch wasn't executed correctly. It is, but the logs are full of noise)

**Comment by lukaseder** [comment]
The real issue here is that the plain SQL `DSL.query(String)` method which is used behind the scenes does not create empty dummy `Param` objects, so when binding values to the batch statement, jOOQ cannot check if a matching number of values is given.

A workaround would be to use this instead:

```java
String updateQuery = "UPDATE someTable SET col1 = ? WHERE id = ?";
BatchBindStep batch = dslContext.batch(DSL.query(updateQuery, new Object[] { null, null }));
batch.bind("none", 123);
batch.execute();
```

This would remove those error messages. But it's tedious to write. jOOQ should obviously handle this for you.

**Comment by lukaseder** [comment]
The warning was introduced in https://github.com/jOOQ/jOOQ/issues/4071

**Comment by adrianandrei-ca** [comment]
Cool.
