### ISSUE TITLE
Unnecessary recompilation

### ISSUE THREAD

**Issue by JustAPerson** [jOOQ/jOOQ#5375]
jOOQ always rebuilds all the emitted java files. This causes a huge amount of unnecessary recompilation. jOOQ should avoid overwriting files if the new content would be identical to the existing content.

**Comment by billoneil** [comment]
Is this really an issue? The code generator isn't something that needs to be run very frequently. Only when you change the db schema.

**Comment by lukaseder** [comment]
jOOQ's code generator doesn't overwrite files if they would contain the exact same content, see https://github.com/jOOQ/jOOQ/issues/3756.

Do note that the Maven compiler has a very annoying bug. Have you tried specifying the following?

```xml
                    <!-- When compilers say false, they mean true ...
                         https://issues.apache.org/jira/browse/MCOMPILER-209 -->
                    <useIncrementalCompilation>false</useIncrementalCompilation>
```

@billoneil: Yes, it can be for large schemas, which is why #3756 was implemented.

**Comment by JustAPerson** [comment]
@billoneil, well if you attach it to the `generate-sources` maven phase, it seems to run all the time. But @lukaseder is right, the files actually aren't being updated. That configuration option helps immensely. I apologize for the confusion.

**Comment by lukaseder** [comment]
No worries, glad it helped :)
