### ISSUE TITLE
have a generator flag not to make everything in java public

### ISSUE THREAD

**Issue by simbo1905** [jOOQ/jOOQ#5473]
the generator marks all the tables as public. this means that any arbitrary application code can "see the database" to make queries. if there was a generator flag such that "public" wasn't prefixed to the tables then i could generate into a particular java package and write public code in the same package which exposed a limited public api. with everything generated as public i cannot have the compiler or IDE enforce the hiding of the data model to the upper layers of the app and have to resort to build plugins to validate that arbitrary gui code isn't using the jooq generated code rather than going the service layer.

**Comment by lukaseder** [comment]
That's an interesting idea. Of course, it would require that all artefacts are generated in the same package, including catalogs, schemas, tables, records, pojos, interfaces, udts, enums. While this is doable with generator strategies, it is probably not very common. Besides, it is unlikely that many applications are built in such a way that also all other data access logic is placed in this single package.

I think that OSGi (today) and Jigsaw (next year) will provide better means of managing acces to public artifacts, including code generated by jOOQ.

I currently don't see how this feature would pull its weight, but perhaps there will be more users in the future requesting it, so I'm not ruling out that we'll consider implementing advanced visibility strategies.

**Comment by lukaseder** [comment]
This feature has been implemented in jOOQ 3.15: https://www.jooq.org/doc/latest/manual/code-generation/codegen-advanced/codegen-config-generate/codegen-generate-visibility-modifier/

It should be possible to combine this with a generator strategy in order to ensure everything is located in the same package to profit from package private access.

Alternatively, since Java 9, a much better solution would be to use modules, and export only the packages that should be exported...
