### ISSUE TITLE
Templating Support for Postgres JSON Path syntax

### ISSUE THREAD

**Issue by nkoterba** [jOOQ/jOOQ#5490]
Postgres' JSON functions and operators (https://www.postgresql.org/docs/9.5/static/functions-json.html) supports getting a JSON field/property at a specified JSON path:

```
'{"a":[1,2,3],"b":[4,5,6]}'::json #>> '{a,2}'
```

We are trying to use `DSL.field` to dynamically construct these "fields" using the basic Jooq Template syntax.

For example, if we have the following Json object stored in a Postgres table called *table* in a column called *details*:
```
{ 
  "resolution": {
     "status" : "PENDING"
  }
}
```

We need to construct the following query to retrieve status values:
```
SELECT "details" #>> '{resolution, status}' FROM "table"
```

Using JOOQ's templating syntax, we hoped we could do (NOTE: TABLE.DETAILS is auto-generated by Jooq and represents the DETAILS column on the TABLE):
```
Field<Object> RESOLUTION__STATUS_FIELD =
		DSL.field("{0} #>> '{{1}}'", Object.class, TABLE.DETAILS, "resolution, status");
```

However, it appears `{{` or the single quote `'` negates or ignores the templating replacement. This is the output: `"table"."details" #>> '{{1}}'`

We tried various other combinations of moving the needed `{` to the replacement value, using `DSL.sql(replace_value)`, etc. but none of these ever produced the correct syntax.

My guess is the templating parsing logic either ignores or treats single `'` as escape characters and then ignores templating or the parsing logic doesn't know how to handle double curly braces: `{{`, etc.

We did succeed in producing the correct syntax with the following:
```
Field<Object> RESOLUTION__STATUS_FIELD =
	DSL.field("{0} #>> {1}", Object.class, 
		TABLE.DETAILS, DSL.sql("'{resolution, status}'"));
```

Since our desired lookup key (e.g. {resolution,status}) is dynamic, this is the final implementation:
```
Field<Object> FIELD_FOR_LOOKUP_KEY =
	DSL.field("{0} #>> {1}", Object.class, 
		TABLE.DETAILS, DSL.sql("'{" + lookupKey + "}'"));
```

Although this works, it isn't textually very easy to follow since the "syntax/format" is spread between the first param to `DSL.field` and then some string concat in the last param to `DSL.field`.

I tried searching documentation for information on how to escape `'` or `{`, but couldn't find anything immediately and the templating parsing logic is rather complex.

**Comment by lukaseder** [comment]
Indeed there are two things here:

1. The templating logic is rather implicit and not well documented. This is because it was rather experimental and useful only for internals in the beginning. Today, it is stable and deserves a section in the manual / formal specification. I have created an issue to fix this: https://github.com/jOOQ/jOOQ/issues/5494
2. The templates do indeed parse your SQL in a simple way, e.g. to ensure that string literals are kept in place. There is no way for jOOQ to tell if inserting `'ABC {0} XYZ'` is really meant as-is, or if that `{0}` is meant as a placeholder. Worse, what if you want to insert `'Are you hungry?'` ? Is the question mark a bind variable or is it part of the string literal? This is why string literals are parsed by the plain SQL templating mechanisms and left untouched. (the same is true for comments, identifiers, JDBC escape sequences, and a few other things, which deserve documentation)

The best solution for you would indeed be:

```java
Field<Object> RESOLUTION__STATUS_FIELD =
    DSL.field("{0} #>> {1}", Object.class, 
        TABLE.DETAILS, DSL.inline("{resolution, status}"));
```

I'd prefer `inline()` here, rather than `sql()`, as it will take care of properly escaping potential `'` characters.

I hope this helps
Lukas

**Comment by nkoterba** [comment]
Lukas -

Thanks for the speedy reply.  Two follow-up comments.

You said:
> This is why string literals are parsed by the plain SQL templating mechanisms and left untouched

So does that mean the following snippet is not pre-processed *at all* by Jooq:
```
{0} #>> '{{1}}'
```

If so, then it sounds like the variable replacement logic for **POSTGRES** is at fault here for not correctly recognizing a replacement parameter in the inner `{}`.

Second, you suggested using `inline()` instead of `sql()` to escape potential `'` characters.  However, the exact syntax that needs to be passed to POSTGRES SQL interpreter is:
```
'{resolution, status}'
```

Are you saying that `inline()` will automatically wrap `'` around `{resolution, status}`?

I think I tried inline and found it was "escaping" or "removing" the `'` which we actually do need (I know POSTGRES SQL syntax can be odd at times).

**Comment by lukaseder** [comment]
> So does that mean the following snippet is not pre-processed at all by Jooq:
> 
> ```
> {0} #>> '{{1}}'
> ```

For the avoidance of doubt: `{0}` is pre-processed, but `'{{1}}` is not (it would be a bug, otherwise). In the meantime, I have updated the manual to specify all the processing logic applied to plain SQL templates:
http://www.jooq.org/doc/latest/manual/sql-building/queryparts/plain-sql-queryparts

> If so, then it sounds like the variable replacement logic for POSTGRES is at fault here for not correctly recognizing a replacement parameter in the inner {}.

Interesting, I wasn't aware of this. Is that supposed to be a PostgreSQL inline array encoding? I had to look up the `#>>` to see what it means:

```sql
SELECT 
  oprname, 
  oprcode || '(' || format_type(oprleft,  NULL::integer) || ', ' 
                 || format_type(oprright, NULL::integer) || ')' AS function
FROM pg_operator 
WHERE oprname = '#>>';
```

So, it corresponds to the `jsonb_extract_path_text` which takes an `text[]` type as the second argument. What do your nested curly braces mean in this context?

> Are you saying that inline() will automatically wrap ' around {resolution, status}?

Yes. `inline()` used on strings produces string literals (including the apostrophes and the quoting of apostrophes inside of the string literal).
