### ISSUE TITLE
Accept CharSequence instead of String

### ISSUE THREAD

**Issue by ooxi** [jOOQ/jOOQ#5506]
Is is possible to accept `CharSequence` instead of `String` for fields of type `Field<String>`? I don't quite see how it would be possible but maybe you have an idea. Otherwise we'll have to use customer converters.

**Comment by lukaseder** [comment]
Thank you very much for your suggestion. I admit having regretted before that jOOQ hard-wires everything to `String` rather than accepting the base type `CharSequence` throughout the API.

Right now, it's indeed hard to estimate how much API needs to break in order to implement such a change. In order to better undestand the need, may I ask you to describe your use-case?

**Comment by ooxi** [comment]
We have tables with columns of type `varchar` or `char` which get generated to fields of type `Field<String>`. Therefore `Field.eq(T)` only accepts `String` where we'd like to compare to `CharSequence`.

I know that we should configure the code generator to produce `Field<ItemCode>` but I thought maybe you know a trick :)

**Comment by lukaseder** [comment]
Oh, I see. Supporting `CharSequence` won't get you very far though. While some input arguments might be more lenient with respect to the data type, all output arguments are not. For instance, `DSL.concat()` might accept `Field<? extends CharSequence>` but it will still return `Field<String>`.

I still think it is a good idea - we're doing similar things with `Field<? extends Number>`, but in your case, you will be much happier registering a converter everywhere. A `Field<ItemCode>` will enforce this data type, rather than just allow it.

**Comment by ooxi** [comment]
Thanks for the input!

**Comment by lukaseder** [comment]
Let's keep it open for now. I'd like to look into the possibility of doing this change at some point.

**Comment by lukaseder** [comment]
This would be such a big change, I doubt it's worth it.
