### ISSUE TITLE
Support overriding code generation <target/> configuration via system properties

### ISSUE THREAD

**Issue by etiennestuder** [jOOQ/jOOQ#5641]
Currently, the target directory is passed in the Configuration/XML. I propose to provide an option when invoking the `GenerationTool` to pass in the target directory, e.g. `--target-directory <dir>`. Possibly also for target package and target encoding.

Reasons:
- _where_ the generated code ends up is orthogonal from _how_ it should be generated
- using the same configuration to generate code to different locations is not well possible right now
- the gradle-jooq-plugin would make use of this
    -- by removing its custom config DSL and instead pointing straight to the jOOQ xml
    -- by still accepting the target directory in the DSL and then invoking the GenerationTool with it

**Comment by lukaseder** [comment]
Thank you very much for your suggestion. In the past, there had been similar suggestions that were hoping to remove the JDBC connection configuration from the XML and allow for that to be passed via CLI arguments and/or system properties.

I've usually rejected these feature requests, because they had often been a bit premature. Sure there are some pains with the status quo, but the pain of maintaining all these possible orthogonal configuration options and how they override each other is just as important (maybe even more, because this stuff tends to be undocumented or poorly documented and not well tested).

An alternative is, of course, for your plugin to simply use XSLT or some other means of patching the user's XML content, and then override XML content with your DSL content. Perhaps, that's the simplest and cleanest approach here. After all, the XML content is just a structured argument, and you're free to create your own structured argument from user source that just happens to be "compatibly structured" in your plugin.

**Comment by etiennestuder** [comment]
Thanks for the feedback, @lukaseder. I will try to come up with a solution that does not depend on the jOOQ changes requested above.

What could work well in jOOQ is to have system property overrides (or cmd line overrides) that follow a naming convention, defined by the structure of the xml schema. This way, the override mechanism could be implemented generically and testing could then also be done generically.

**Comment by lukaseder** [comment]
> that follow a naming convention, defined by the structure of the xml schema.

I had thought about this in the past. But how would you proceed with lists? E.g. with the `<schemata>` or `<forcedTypes>` configurations?

**Comment by lukaseder** [comment]
I'm revisiting this. I'm not entirely opposed to the idea, as I can see its value for quite a few things. But we have to be careful to design a mini-language that is as versatile as the existing XML/JAXB configuration, because it will have to be able to configure everything that is configurable with XML/JAXB (surely, a more minimal solution would work for you, but it wouldn't be maintainable in the long run).

There are several generic options:

### JSP EL:

Since JAXB-generated code is quite JavaBeans compliant, one option would be to use standard JSP EL to specify paths to elements. For instance, in order to configure the `<jdbc/>` element, we could do:

```
java -jar ... org.jooq.util.GenerationTool --jdbc.url=... --jdbc.username=... --jdbc.password=...
```

And for lists:

```
... --generator.database.schemata.schema[0].inputSchema=...
  -- generator.database.schemata.schema[1].inputSchema=...
```

### XPath

Since we're operating on an XML document structure, XPath would be another option, e.g.

```
java -jar ... org.jooq.util.GenerationTool --/jdbc/url=... --/jdbc/username=... --/jdbc/password=...
```

Clearly, this is a bit less idiomatic from a CLI perspective.

Inventing our own language seems a bit short-sighted, because we might run into an issue where the language won't suffice in the future, and it's harder to document.

**Comment by etiennestuder** [comment]
Great to see that it is considered. I would go with JSP EL. I assume more people are familiar with that syntax than with XPath. Whether one of the two is more powerful than the other I cannot judge since I'm not enough of an export on both of them.

**Comment by lukaseder** [comment]
They're probably equally powerful. But before I overengineer this, I'll just wait until it gets more traction :)

**Comment by lukaseder** [comment]
I stumbled upon this issue again, which got postponed because it was inconclusive after our discussion. But the inconclusiveness only affects the parts where I'm not convinced we should offer additional properties (complex nesting of `<forcedTypes/>` and other contents of the `<database/>` or `<generator/>` configuration).

Your original feature request wasn't about that, it was about `<target/>` only. Or in your words:

> * _where_ the generated code ends up is orthogonal from _how_ it should be generated

I don't disagree with this, I just got careful about the potential overengineering of this feature. All of these flags make sense as system properties:

- `jooq.codegen.target.packageName`
- `jooq.codegen.target.directory`
- `jooq.codegen.target.encoding`
- `jooq.codegen.target.locale`
- `jooq.codegen.target.clean`

Just like the ones we already have:
https://www.jooq.org/doc/latest/manual/code-generation/codegen-system-properties/

I'll just implement this, and leave the other parts for the future, if at all.
