### ISSUE TITLE
PostgreSQL RETURNING <col> AS <alias> is not rendered correctly

### ISSUE THREAD

**Issue by BrentDouglas** [jOOQ/jOOQ#5688]
PG 9.5.4, jOOQ 3.8.3

If I call  `.returning(TABLE.COLUMN.as("id"))` jOOQ will render it as `returning "id"` rather than `returning "table"."column" as "id"`

**Comment by lukaseder** [comment]
Thank you very much for your report. I wasn't aware that this is possible, but of course, it makes perfect sense.

**Comment by lukaseder** [comment]
This fix depends on #5622, which is an incompatible change. Unfortunately, this means that we cannot implement this feature without breaking the existing API

**Comment by mjustin** [comment]
Technically, this fix only depends on #5622 when you're already dealing with a concrete instance of Record, and not just Record/RecordImpl, especially since this currently works if you're _not_ aliasing the field (though maybe _that_ is the bug). But yeah, I imagine the general purpose fix (which I suspect is where you would want to spend your time implementing) would depend on the other issue.

**Comment by lukaseder** [comment]
Thanks for your comments, @mjustin. Maybe you're right, the aliasing could be generated nevertheless, and if e.g. plain SQL is used and thus `Record` / `RecordImpl` will be the row type, then this might just work. Will check soon.

**Comment by lukaseder** [comment]
Indeed, the aliasing can (and should) be fixed easily.

With the aliasing fixed, however, I wonder if the breaking change #5622 shouldn't be prioritised for the next minor release 3.11, because it will be even more confusing from a user perspective if something works (aliasing for non-generated tables) and something very similar doesn't work (aliasing for generated tables). It doesn't seem reasonable to have a penalty on using jOOQ with generated code.

The default, argument-less `returning()` method would continue to return `R` as it corresponds to `RETURNING *`. The other methods would now return `Record`, and there will be new `returning()` methods that keep track of record-level type safety, just like the overloaded `select()` methods: #6715

**Comment by lukaseder** [comment]
I will merge this fix downstream to 3.10.2 (#6716) and 3.9.7 (#6717). Even if the mentioned difference in behaviour might be confusing, there are users who use jOOQ for SQL generation only, not for SQL execution. Those users can immediately profit from this fix.
