### ISSUE TITLE
Generate java.math.BigInteger for PostgreSQL NUMERIC(?, 0) types

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#5736]
See:
https://github.com/jOOQ/jOOQ/issues/5589#issuecomment-269106030

**Comment by lukaseder** [comment]
@leoandru: Looking into this issue now (see also #5589). How do you create such a type in PostgreSQL?

**Comment by leoandru** [comment]
Pulling an example from a project I use JOOQ on

```"e164_phone_number"  NUMERIC(15) NOT NULL```
OR
```"e164_phone_number"  NUMERIC(15,0) NOT NULL```

both are effectively the same
Those types are converted to BigDecimal instead of BigInteger in Java.

**Comment by lukaseder** [comment]
I'm sorry, silly me. The `?` was my own wildcard notation that confused me now :P

**Comment by lukaseder** [comment]
OK, just extended the numbers integration test table to this:

```sql
CREATE TABLE t_639_numbers_table (
  ID INT NOT NULL,
  SHORT SMALLINT,
  INTEGER INT,
  LONG BIGINT,
  BYTE_DECIMAL DECIMAL(2, 0),
  SHORT_DECIMAL DECIMAL(4, 0),
  INTEGER_DECIMAL DECIMAL(9, 0),
  LONG_DECIMAL DECIMAL(18, 0),
  BIG_INTEGER DECIMAL(22, 0),
  BIG_DECIMAL DECIMAL(22, 5),
  BYTE_NUMERIC NUMERIC(2, 0),
  BYTE_NUMERIC_NOSCALE NUMERIC(2),
  SHORT_NUMERIC NUMERIC(4, 0),
  SHORT_NUMERIC_NOSCALE NUMERIC(4),
  INTEGER_NUMERIC NUMERIC(9, 0),
  INTEGER_NUMERIC_NOSCALE NUMERIC(9),
  LONG_NUMERIC NUMERIC(18, 0),
  LONG_NUMERIC_NOSCALE NUMERIC(18),
  BIG_INTEGER_NUMERIC NUMERIC(22, 0),
  BIG_INTEGER_NUMERIC_NOSCALE NUMERIC(22),
  BIG_DECIMAL_NUMERIC NUMERIC(22, 5),
  FLOAT REAL,
  DOUBLE DOUBLE PRECISION,

  CONSTRAINT pk_t_639_numbers_table PRIMARY KEY(ID)
);
```

I don't see any problems, all the columns are generated as expected, i.e. `DECIMAL` and `NUMERIC` types without scale but too large for `java.lang.Long` produce `java.math.BigInteger`.

What do you get for your column when you query the `information_schema.columns` table?

**Comment by leoandru** [comment]
OK you are correct. I should have specified the issue more clearly when I noticed the change. The issue is with SQL functions.
`
CREATE  TABLE IF NOT EXISTS "public".device (
  "ESN"                         NUMERIC(15) NOT NULL CHECK ("ESN" >= 0::NUMERIC(15)),
  "SIM"                         NUMERIC(22) NOT NULL CHECK ("SIM" >= 0::NUMERIC(22)),
  "bcs"                         INTEGER CHECK ("bcs"  IS NULL OR ("bcs"  >= 0   AND  "bcs"  <= 3)),
  "bcl"                         INTEGER CHECK ("bcl"  IS NULL OR ("bcl"  >= 0   AND  "bcl"  <= 100)),
  "bVm"                         INTEGER CHECK ("bVm"  IS NULL OR ("bVm"  >= 0   AND  "bVm"  <= 99999999)),
  "mail"                        INTEGER CHECK ("mail" IS NULL OR ("mail"  = 0    OR  "mail"  = 1)),
  "time"                        TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "enabled"                     BOOLEAN NOT NULL DEFAULT TRUE,
  "floating"                    BOOLEAN NOT NULL DEFAULT FALSE,
  "type"                        TEXT,
  "notes"                       TEXT
);

CREATE  UNIQUE INDEX device_ESN_uk ON "public".device ("ESN");
CREATE  UNIQUE INDEX device_SIM_uk ON "public".device ("SIM");

CREATE  OR REPLACE RULE  no_delete_device AS ON DELETE TO "public"."device" DO INSTEAD NOTHING;

CREATE  OR REPLACE FUNCTION device_update (
  p_esn                         NUMERIC(15, 0),
  p_sim                         NUMERIC(22, 0),
  p_bcs                         INTEGER,
  p_bcl                         INTEGER,
  p_bVm                         INTEGER,
  p_mail                        INTEGER)
RETURNS NUMERIC(15, 0)
AS
$$
--    WITH updated AS (
--  UPDATE "public".device
--     SET
--         "bcs"  = COALESCE(p_bcs,   "bcs"),
--         "bcl"  = COALESCE(p_bcl,   "bcl"),
--         "bVm"  = COALESCE(p_bVm,   "bVm"),
--         "mail" = COALESCE(p_mail,  "mail"),
--         "time" = CURRENT_TIMESTAMP
--   WHERE
--         "ESN"  = p_esn
--   RETURNING *)
--   SELECT
--     CASE
--     WHEN "SIM" = p_sim
--     THEN "public".notify_alert(p_sim, p_bcl, p_mail)
--     ELSE "public".notify_admin(p_esn, p_sim)
--      END
--     FROM updated
--    WHERE "enabled" IS TRUE;
  SELECT NULL::NUMERIC(15, 0);
$$ LANGUAGE SQL;
`

`
/*
 * This file is generated by jOOQ.
*/
package com.diana.jooq.routines;


import com.diana.jooq.public;

import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DeviceUpdate extends AbstractRoutine<BigDecimal> {

    private static final long serialVersionUID = 689769948;

    /**
     * The parameter <code>public.device_update.RETURN_VALUE</code>.
     */
    public static final Parameter<BigDecimal> RETURN_VALUE = createParameter("RETURN_VALUE", org.jooq.impl.SQLDataType.NUMERIC, false, false);

    /**
     * The parameter <code>public.device_update.p_esn</code>.
     */
    public static final Parameter<BigDecimal> P_ESN = createParameter("p_esn", org.jooq.impl.SQLDataType.NUMERIC, false, false);

    /**
     * The parameter <code>public.device_update.p_sim</code>.
     */
    public static final Parameter<BigDecimal> P_SIM = createParameter("p_sim", org.jooq.impl.SQLDataType.NUMERIC, false, false);

    /**
     * The parameter <code>public.device_update.p_bcs</code>.
     */
    public static final Parameter<Integer> P_BCS = createParameter("p_bcs", org.jooq.impl.SQLDataType.INTEGER, false, false);

    /**
     * The parameter <code>public.device_update.p_bcl</code>.
     */
    public static final Parameter<Integer> P_BCL = createParameter("p_bcl", org.jooq.impl.SQLDataType.INTEGER, false, false);

    /**
     * The parameter <code>public.device_update.p_bvm</code>.
     */
    public static final Parameter<Integer> P_BVM = createParameter("p_bvm", org.jooq.impl.SQLDataType.INTEGER, false, false);

    /**
     * The parameter <code>public.device_update.p_mail</code>.
     */
    public static final Parameter<Integer> P_MAIL = createParameter("p_mail", org.jooq.impl.SQLDataType.INTEGER, false, false);

    /**
     * Create a new routine call instance
     */
    public DeviceUpdate() {
        super("device_update", public.public, org.jooq.impl.SQLDataType.NUMERIC);

        setReturnParameter(RETURN_VALUE);
        addInParameter(P_ESN);
        addInParameter(P_SIM);
        addInParameter(P_BCS);
        addInParameter(P_BCL);
        addInParameter(P_BVM);
        addInParameter(P_MAIL);
    }

    /**
     * Set the <code>p_esn</code> parameter IN value to the routine
     */
    public void setPEsn(BigDecimal value) {
        setValue(P_ESN, value);
    }

    /**
     * Set the <code>p_esn</code> parameter to the function to be used with a {@link org.jooq.Select} statement
     */
    public void setPEsn(Field<BigDecimal> field) {
        setField(P_ESN, field);
    }

    /**
     * Set the <code>p_sim</code> parameter IN value to the routine
     */
    public void setPSim(BigDecimal value) {
        setValue(P_SIM, value);
    }

    /**
     * Set the <code>p_sim</code> parameter to the function to be used with a {@link org.jooq.Select} statement
     */
    public void setPSim(Field<BigDecimal> field) {
        setField(P_SIM, field);
    }

    /**
     * Set the <code>p_bcs</code> parameter IN value to the routine
     */
    public void setPBcs(Integer value) {
        setValue(P_BCS, value);
    }

    /**
     * Set the <code>p_bcs</code> parameter to the function to be used with a {@link org.jooq.Select} statement
     */
    public void setPBcs(Field<Integer> field) {
        setField(P_BCS, field);
    }

    /**
     * Set the <code>p_bcl</code> parameter IN value to the routine
     */
    public void setPBcl(Integer value) {
        setValue(P_BCL, value);
    }

    /**
     * Set the <code>p_bcl</code> parameter to the function to be used with a {@link org.jooq.Select} statement
     */
    public void setPBcl(Field<Integer> field) {
        setField(P_BCL, field);
    }

    /**
     * Set the <code>p_bvm</code> parameter IN value to the routine
     */
    public void setPBvm(Integer value) {
        setValue(P_BVM, value);
    }

    /**
     * Set the <code>p_bvm</code> parameter to the function to be used with a {@link org.jooq.Select} statement
     */
    public void setPBvm(Field<Integer> field) {
        setField(P_BVM, field);
    }

    /**
     * Set the <code>p_mail</code> parameter IN value to the routine
     */
    public void setPMail(Integer value) {
        setValue(P_MAIL, value);
    }

    /**
     * Set the <code>p_mail</code> parameter to the function to be used with a {@link org.jooq.Select} statement
     */
    public void setPMail(Field<Integer> field) {
        setField(P_MAIL, field);
    }
}

This is in Routines class generated
public static BigDecimal deviceUpdate(Configuration configuration, BigDecimal pEsn, BigDecimal pSim, Integer pBcs, Integer pBcl, Integer pBvm, Integer pMail) {
        DeviceUpdate f = new DeviceUpdate();
        f.setPEsn(pEsn);
        f.setPSim(pSim);
        f.setPBcs(pBcs);
        f.setPBcl(pBcl);
        f.setPBvm(pBvm);
        f.setPMail(pMail);

        f.execute(configuration);
        return f.getReturnValue();
    }`

Is there any reason it would choose to use BigDecimals there ?

**Comment by lukaseder** [comment]
Oh, interesting. Our integration tests don't cover that. The reason is that the precision / scale is not reported in the relevant dictionary view:

```sql
SELECT *
FROM information_schema.parameters
WHERE specific_name LIKE 'device_update%'
```

I also don't see any precision / scale being reported in `pg_proc`:

```sql
SELECT * 
FROM pg_proc
WHERE proname = 'device_update'
```

Will investigate

**Comment by lukaseder** [comment]
It appears not to be possible (or relevant):
http://stackoverflow.com/q/18196590/521799

**Comment by lukaseder** [comment]
Also:
https://postgrespro.com/list/thread-id/1527266

**Comment by lukaseder** [comment]
Closing this as invalid, because we cannot figure out this information (unfortunately). This works like Oracle, then, although, luckily PostgreSQL has formal integer types (unlike Oracle).

The workaround would be to use `<forcedType/>` to apply data type rewriting on individual parameters:
https://www.jooq.org/doc/latest/manual/code-generation/data-type-rewrites

**Comment by leoandru** [comment]
OK, Thank you for taking the time to investigate much appreciated. I'll look into using forced types
