### ISSUE TITLE
Possibility to disable null check in generated getters for certain forcedType-s

### ISSUE THREAD

**Issue by manuelbernhardt** [jOOQ/jOOQ#5792]
I am using a custom type converter for a scala `AnyVal`:

```scala
case class TNodeHandle(h: String) extends AnyVal
```

The getter generated by the code generator has a null check that doesn't work with regards to `AnyVal`:

```scala
    [error] /Users/manu/workspace/vcharge/tnode-registry/app/generated/tables/records/TNodeRecord.scala:105: type mismatch;
    [error]  found   : Null(null)
    [error]  required: models.TNodeHandle
    [error]     if (r == null) null else r.asInstanceOf[TNodeHandle]
    [error]                    ^
    [error] one error found
    [error] (compile:compileIncremental) Compilation failed
```

The generated code is:

```scala
    def getHandle: TNodeHandle = {
      val r = get(3)
      if (r == null) null else r.asInstanceOf[TNodeHandle]
    }
```

I'm thinking that perhaps a sensible place for customising this getter behaviour would be in the definition of the `forcedType`?

**Comment by lukaseder** [comment]
I don't think there's any way to prevent this, really. It is not possible for the code generator to reflect on the type of its applied converters, as they are not on the classpath of the code generator. Even if they were, pretending that a given record type is non-nullable is a "lie", for the usual reasons (outer join, union, etc., which can produce `null` values in "non-nullable" types, see https://blog.jooq.org/2017/07/25/5-things-you-may-not-have-known-about-jooq/#thing1).

This will not be fixed in jOOQ. The workaround suggested here is sufficient: https://github.com/jOOQ/jOOQ/issues/5792#issuecomment-273415746
