### ISSUE TITLE
Plain SQL fetch() methods should return update count in Result

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#5818]
When sending a batch through jOOQ's plain SQL APIs, the `fetch()` methods should return the update count in the resulting `Result` object rather than returning an "empty" (column-less) `Result`

```java
Result<?> result = create().fetch(
    "insert into t_dates (id) values (1);"
  + "select * from t_dates;");
```

The above query returns:

```
+
|
+
```

When it should return:

```
+--------------+
| UPDATE_COUNT |
+--------------+
```

Skipping to returning the `SELECT` query's results is not a good option because:

- For backwards compatibility reasons, we should always return the first result, consistently
- What is the ideal `SELECT` whose results we should return? E.g. what if a batch contains 4 selects?
- There's also `fetchMany()` for fetching the results of the entire batch

The fix will improve on a previous fix: https://github.com/jOOQ/jOOQ/issues/5617

----
See also:
- http://stackoverflow.com/a/41958478/521799
- https://github.com/jOOQ/jOOQ/issues/5617

**Comment by lukaseder** [comment]
Marking this as an "incompatible change", as in rare cases, client code may rely on the current behaviour, which is a `0 x 0` `Result`

**Comment by zhuangdaz** [comment]
I am running into a similar issue where my DB client returns a `null` resultSet at this [line](https://github.com/jOOQ/jOOQ/blob/main/jOOQ/src/main/java/org/jooq/impl/AbstractResultQuery.java#L236) and then a `UPDATE_COUNT` row is inserted but then the cursor is trying to parse this row with the original cols which throws the following exception since there is only one int col from the `UPDATE_COUNT` row:
```
Caused by: java.sql.SQLException: Unknown column index : 2
```

**Comment by zhuangdaz** [comment]
@lukaseder for visibility. 🙇🏼‍♂️
