### ISSUE TITLE
CommonTableExpression lacks generics field accessors

### ISSUE THREAD

**Issue by ciaccia** [jOOQ/jOOQ#5847]
Consider the following code where I define a "generics" CTE:

```java
Row4<Long, String, Boolean, Timestamp>[] consts = (Row4<Long, String, Boolean, Timestamp>[]) new Row4[2];
consts[0] = DSL.row(1L, "Bar", Boolean.TRUE, new Timestamp(10));
consts[1] = DSL.row(2L, "Foo", Boolean.FALSE, new Timestamp(20));
CommonTableExpression<Record4<Long, String, Boolean, Timestamp>> constsCte =
	DSL
	.name("cc")
	.fields("id", "name", "active", "timestamp")
	.as(DSL.selectFrom(DSL.values(consts)));
```

While I can get a "generics" field from the `Row4`, the CTE loses the type information. For example:

```java
Field<Long> rowFieldId = consts[0].field1();
Field<?> cteFieldId = constsCte.field(0);
```

This is somehow annoying when I select data from the CTE, where I have to specify the type for every field:

```java
SelectJoinStep<Record4<Long, String, Boolean, Timestamp>> step =
	dslCtx.with(constsCte)
	.select(constsCte.field("id", Long.class),
		constsCte.field("name", String.class),
		constsCte.field("active", Boolean.class),
		constsCte.field("timestamp", Timestamp.class)
	)
	.from(constsCte);
```

Ideally the `CommonTableExpression` should implement "generics" direct field accessors such as field1(), field2(), field3() etc.

**Comment by lukaseder** [comment]
You mention valid points, and they're not really related to common table expressions only.

What you're asking for essentially boils down to having `Table1<T1>`, `Table2<T1, T2>` etc. types rather than `Table<Record1<T1>>`, `Table<Record2<T1, T2>>` types. This would be the only way to achieve what you want because the Java language does not allow generic types to reflect on any nested generic types (which would require higher-kinded generics, a can of worms I'm not sure the Java language designers will be willing to open). However, we decided against this design early on in jOOQ, because it would greatly sacrifice the API's usability in order to add value to the edge case.

Another example showing how generic types cannot reflect on their generic type parameters: If you have a `List<Optional<String>>`, there's no way the outer `List` can ever "know" that it actually contains `Optional` and thus provide any convenience over its content type.

There is a workaround, however (in your case). Instead of your last assignment, write this:

```java
Select<Record4<Long, String, Boolean, Timestamp>> select =
	dslCtx.with(constsCte)
	.selectFrom(constsCte);
```

This works, because `selectFrom()` is a *generic method*, which allows for some more reflection on generic types than generic types can do themselves.

I hope this helps,
Lukas

**Comment by ciaccia** [comment]
Hallo Lukas, thank you for your answer.

I am aware of Java limitations when working with templates and I also am aware of the `selectFrom` solution. Unfortunately in my case I have to construct a "custom" select combining parts of the CTE with other fields, resulting in the issue above.

Even though I understand the technical difficulties (i.e generating tons of files) of bringing generics field accessors to CTEs, I don't really understand why `Row`,  `Record` and `Table` support it while CTEs don't. You already do this with all the other classes, deciding to not do this with CTE is a _philosophical_ decision rather than a technical one.

**Comment by lukaseder** [comment]
@ciaccia: What do you mean by the fact that `Table` supports this usage?

**Comment by ciaccia** [comment]
Let's assume I have the following table (similar to hardcoded the CTE above)

	create table jooq_dummy
	(
		id bigint PRIMARY KEY,
		name text,
		active text, 
		ts timestamp with time zone
	);

and I generate the stubs. I can then write the following:

	SelectJoinStep<Record1<Long>> step =
		dslCtx
			.select(JooqDummy.ID)
			.from(JooqDummy.JOOQ_DUMMY);

As you see the field ID is "generic" having its own type. I understand the problem is not the same (since JooqDummy class gets generated and is not _templated_). Sorry for the confusion.

**Comment by lukaseder** [comment]
Indeed, the generated tables are a bit different, but there's nothing on the `org.jooq.Table` API (which is the `CommonTableExpression` super type), which allows for type safe access to individual fields.

Don't get me wrong. I completely agree, it would be very nice (and not against philosophy at all) to have more type safety also on `Table` (and thus `CommonTableExpression`). Unfortunately, I don't see how (yet). So, it really *is* a technical discussion.

And, of course, I'm very open to ideas!

**Comment by ciaccia** [comment]
Hallo Lukas,
Maybe without knowing jOOQ's internals I don't see issues you are aware of. Without changing the structure too much, let's consider the following two interfaces:

	public interface CommonTableExpression4<T1,T2,T3,T4> extends CommonTableExpression<Record4<T1,T2,T3,T4>> {
		Field<T1> field1();
		Field<T2> field2();
		Field<T3> field3();
		Field<T4> field4();
	}
and 

	public interface CommonTableExpression4R<T1,T2,T3,T4, R extends Record4<T1,T2,T3,T4>> extends CommonTableExpression<R> {
		Field<T1> field1();
		Field<T2> field2();
		Field<T3> field3();
		Field<T4> field4();
	}

The new interfaces now expose "generics" field accessors:

	CommonTableExpression4<Long,String,Boolean,Timestamp> cte4 = null;
	CommonTableExpression4R<Long,String,Boolean,Timestamp,Record4<Long,String,Boolean,Timestamp>> cte4r = null;

	Field<Long> field1 = cte4.field1();
	Field<String> field2 = cte4.field2();
	Field<Boolean> field3 = cte4.field3();
	Field<Timestamp> field4 = cte4.field4();

	Field<Long> field1r = cte4r.field1();
	Field<String> field2r = cte4r.field2();
	Field<Boolean> field3r = cte4r.field3();
	Field<Timestamp> field4r = cte4r.field4();

I am not saying this is a trivial change (I have lots of experience with _exploding_ generics that propagate through thousands of files), but why could this not be done?

**Comment by lukaseder** [comment]
The `CommonTableExpression4R` type is completely prohibitive in terms of usability :)

Sure, `CommonTableExpression4` (and thus `Table4`) et al were considered in the past, but this is opening a can of worms. Because then, you'll be requesting `Select4` (oh and all the `Select**Step4` types!), `Result4`, `RecordType4` as well and that's when the implications on the generic type system in jOOQ *really* start getting messy,  not to mention the importance of the change.

Oh, and how about:

- `CreateTableAsStep4`
- `CreateViewAsStep4`
- `Cursor4`
- `QuantifiedSelect4`

Just to name a few candidates.

**Comment by lukaseder** [comment]
Time has passed and I haven't seen a good way to bring more type safety to these `RecordType` style types.
