### ISSUE TITLE
<types/> cannot match user-defined types (e.g. PostGIS GEOMETRY)

### ISSUE THREAD

**Issue by 67726e** [jOOQ/jOOQ#5872]
I'm currently working on PostGIS with jOOQ, or at least attempting to. However I am running into a bit of an issue. It would appear that all attempts to match `GEOMETRY(POINT)` types in a `forcedType` are failing. I _can_ cause the correct generation to occur when using `expression` and targeting a specific field.

Are there any configuration or logging modes that would allow me to see just what type jOOQ is "seeing" for a column so I can correct my `types` matcher?

**Comment by 67726e** [comment]
It looks like I am running into the same issue reported in #5363 - jOOQ seems to be matching against the `USER-DEFINED` value, not the actual column type.

**Comment by lukaseder** [comment]
Thanks for reporting. Indeed, currently, jOOQ-meta internals use the data types reported by PostgreSQL's `information_schema.columns` table. This is a delicate area that is not simple to change without the risk of breaking things, which is why this has not been implemented yet.

Indeed, #5363 is related, thanks for linking. The best workaround right now would be to match all columns by name either:

- manually
- programmatically by using the [programmatic code generator configuration](https://www.jooq.org/doc/latest/manual/code-generation/codegen-programmatic/). [Here's an idea how to generate the column name regular expression programmatically](http://stackoverflow.com/a/38951742/521799)

**Comment by lukaseder** [comment]
This is now fixed for jOOQ 3.10 and will be merged to 3.9.4 next week.
