### ISSUE TITLE
jOOQ-checker should provide both checker-framework and ErrorProne checks

### ISSUE THREAD

**Issue by ben-manes** [jOOQ/jOOQ#5899]
ErrorProne is an analyzer similar to the Checker Framework, but perhaps more popular. Unfortunately they can't be used in conjunction since both use custom versions of `javac`. It would be a convenient if `jooq-checker` provided a [plugin](http://errorprone.info/docs/plugins) for it, too.

**Comment by lukaseder** [comment]
Hmm, interesting, so you mean the jOOQ `@Allow` and `@Require` annotations would be interpreted with this alternative plugin instead of the checker framework?

> but perhaps more popular

Can you back this with some data?

**Comment by ben-manes** [comment]
> Can you back this with some data?
Not directly. I have yet to see checker framework in the wild. ErrorProne is used quite a bit, especially by projects that follow Google's and Square's conventions. My Github searches show a lot more usages. But easily biased, as its based on my experiences.

**Comment by lukaseder** [comment]
OK, thanks. I'm wondering because this is really not the most important feature of jOOQ - so investing more time and adding more dependencies might be overkill at this stage.

On the other hand, if you're right, and if the two are compatible, and if ErrorProne also supports IDE tooling / support, I don't mind switching to it. The license is certainly a bit less "risky".

**Comment by lukaseder** [comment]
I have to say, though, that the rather simple manual indicates it is not very mature (yet)...

**Comment by ben-manes** [comment]
I believe error prone started as a fork, to bring academic into practical. Its used in all Google projects and contributed to by the Guava team. But I'm sure they've diverged if that was true.

I'd say the manual of CheckerFramework is a mess. There doesn't need to be a complex manual for something that works and is intuitive.

I'm not asking for switching. I think you could easily support both without much trouble. The main reason being that those checks are nifty, even if non-critical, so it would be nice to have in my builds.

**Comment by lukaseder** [comment]
OK, I'll think about it.

**Comment by lukaseder** [comment]
... this is certainly something to look out for in the future, but right now, I'd prefer to spend time on more pressing issues as the current checker implementations seem to work nicely and there doesn't seem anything we will gain from the change immediately.

**Comment by RichardBradley** [comment]
+1 from me to this request

> >[ErrorProne is] perhaps more popular [than Checker]
>
> Can you back this with some data?

Hard data is difficult to come by here, but I can report that both Checker and ErrorProne have an IntelliJ plugin, and the [Checker plugin](https://plugins.jetbrains.com/plugin/7560-checker-framework-support) is community provided and reports "3688 downloads" and no ratings yet, whereas the [ErrorProne plugin](https://plugins.jetbrains.com/plugin/7349-error-prone-compiler-integration) is written by JetBrains (the authors of IntelliJ itself) and has 56,137 downloads and 5 stars.

Looking on GitHub, [Checker](https://github.com/typetools/checker-framework) has 419 "stars" compared to [ErrorProne](https://github.com/google/error-prone)'s 4199 "stars".

(All stats correct at the time of writing)

> I have to say, though, that the rather simple manual indicates it is not very mature (yet)...

The docs are a little ugly perhaps, but they are extensive and correct. I think the ErrorProne platform is fairly mature and widely used.

(FIndbugs used to the be clear leader in this space, but it has been abandoned since 2015. There is quite a bit of fragmentation left by its absence.)

**Comment by lukaseder** [comment]
Thanks a lot for the feedback, @RichardBradley. Incidentally, I've just recently upgraded our integration tests for the jOOQ-checker module to Java 9-11, and saw that the checker framework doesn't support anything beyond Java 8 - I don't mean that it's not modular yet, but it actually doesn't work on JDK 9+. It's really a shame, because the checker framework was one of the main driving forces behind JSR 308.

Anyway, this is definitely a good moment to think about moving to `ErrorProne`. For the jOOQ-checker user, such a switch might be completely transparent.

**Comment by lukaseder** [comment]
Having said so, what benefit are you getting out of this switch, @RichardBradley ?

**Comment by lukaseder** [comment]
Thanks for the explanation, Richard. Hmm, that does sound like an interesting check, and you should definitely blog about it and/or publish it somewhere :)

But I'm not sure if it is a good contribution at this point. The two existing checks are very obvious and straight forward in their semantics, and good candidates for static analysis. Yours is more of a "lint" than a "check" in terms of: It doesn't look good, but is also not "obviously wrong".

However, I'm definitely curious about how this could be implemented, as I do plan to think about a lint module / diagnostics module more thoroughly in the future.

**Comment by lukaseder** [comment]
Looking into this right now. The existing checkers implement `javax.annotation.processing.Processor`, because that's how the checker framework works. ErrorProne works on a different level with the compiler API. Is there a way to expose an error prone `Matcher` as a `Processor`, easily?

**Comment by lukaseder** [comment]
Alternatively, I could expose the same logic once as a checker and once as a matcher. Users could then decide which one to use...

**Comment by RichardBradley** [comment]
> Is there a way to expose an error prone `Matcher` as a `Processor`, easily?

I don't think so, but I am not an expert on this
See https://stackoverflow.com/questions/50866567/can-checker-framework-be-used-with-error-prone
and https://github.com/typetools/checker-framework/issues/945

> I could expose the same logic once as a checker and once as a matcher. Users could then decide which one to use...

That sounds sensible to me. If I were doing this, I would start by copying the current checks into a Processor, then once that was all working I would refactor by de-duplicating all common code into a shared class.

**Comment by lukaseder** [comment]
> That sounds sensible to me. If I were doing this, I would start by copying the current checks into a Processor, then once that was all working I would refactor by de-duplicating all common code into a shared class.

Not necessary. Both APIs ultimately use the `com.sun.source` API, so it was relatively easy to share logic between the two implementations. The logic can be seen here:
https://github.com/jOOQ/jOOQ/tree/master/jOOQ-checker/src/main/java/org/jooq/checker

Shared logic in 
https://github.com/jOOQ/jOOQ/blob/master/jOOQ-checker/src/main/java/org/jooq/checker/Tools.java

`*Checkers` are used with the checker framework and `*Matchers` are loaded by ErrorProne. I've successfully managed to run the example on Java 8:
https://github.com/jOOQ/jOOQ/tree/master/jOOQ-examples/jOOQ-checker-framework-example

In order to run it, the entirety of jOOQ needs to be built with Java 8 first. I'll figure out how to properly document this later, seems like both frameworks are rather messy with how they support the different JDK versions... That will be done separately: #8326

Thanks for all your help!
