### ISSUE TITLE
jOOQ,spring-boot and aop.

### ISSUE THREAD

**Issue by areguig** [jOOQ/jOOQ#5902]
Hi, 

After a migration to jOOQ in an application with the following stack : 
- Java 8
- Spring-boot 1.5.1
- jOOQ version managed by the boot starter.

I had perf issues on startup, after investigation, i found out it was because of an `aspect` i was using for logging. 
The aspect was here before jOOQ (under queryDSL rules) and was performing well. 

When the aspect is enabled, my application takes more than a minute to start. Disabling the aspect solves the issue. 

i was able to reproduce the issue in the spring-boot example in the jOOQ repository :
[README](https://github.com/areguig/jooq-spring-boot-aop/blob/master/README.md).
[sources](https://github.com/areguig/jooq-spring-boot-aop).

I don't know if i'm not using aop the right way, or it's something else.

**Comment by ypconstante** [comment]
I just solved this same problem. and I think it's a bug with aspectjweaver.
For some reason, the method `couldMatchJoinPointsInType` of `org.aspectj.weaver.internal.tools.PointcutExpressionImpl` return true when using a pointcut with execution, and because of this a check on every method of DefaultDSLContext to check if the pointcut can be applied to the methods.
Using `within` instead of `execution` solves the problem.

**Comment by lukaseder** [comment]
Thanks for your feedback on this issue, @ypconstante. I'm closing this as invalid as it appears not to be a jOOQ problem.

**Comment by areguig** [comment]
oh. sorry i didn't notice the answers before. 
Thank you @ypconstante for the debug :) .

**Comment by zhangdc007** [comment]
but "execution" can not instand by within,the "within" is waek than "execution"
