### ISSUE TITLE
Add support for the Postgres CITEXT type

### ISSUE THREAD

**Issue by lmarchau** [jOOQ/jOOQ#5934]
We use Postgres Citext Type and Field.contains() to simulate ILIKE Postgres operator.
jOOQ does not support CITEXT and cast it into VARCHAR, so this workaround fails.
I could be convenient to have Postgres CITEXT support or this feature #5619 (consitent solution).

Cheers

**Comment by lukaseder** [comment]
Thank you very much for your feature request

> to simulate ILIKE Postgres operator.

Were you aware of `Field.likeIgnoreCase(Field)`, which already translates to PostgreSQL's `ILIKE` operator? This was added in jOOQ 2.4: https://github.com/jOOQ/jOOQ/issues/1423

#5619 is just additional convenience, so you don't have to write those `%` wildcards manually.

It will definitely make sense to support CITEXT eventually, but with jOOQ's current type system, it might be non-trivial to be sure that `CITEXT` columns never get cast to `TEXT` or `VARCHAR` by some internals... We'll look into it, though.

**Comment by lmarchau** [comment]
Thanks for your swift reply.

I use `Field.likeIgnoreCase(T)` workaround to resolve this case without CITEXT but using CITEXT feature with` Field.contains(T) `would be better suited for our code consistency (we use `Field.exists(T)` and CITEXT with success as example) and performance.

**Comment by lukaseder** [comment]
Sure, I understand. I was just listing workarounds for the time being.

**Comment by lukaseder** [comment]
Other dialects may have similar types, e.g. H2 with its `VARCHAR_IGNORECASE` (see #10291)

**Comment by lukaseder** [comment]
jOOQ 3.17.0 will include support for a variety of PG specific data types: #5507 has added support for the PG `HSTORE` type in jOOQ 3.15, and #2092 adds support for the PG `INET` and `CIDR` types in jOOQ 3.17. https://github.com/jOOQ/jOOQ/issues/2968 adds support for a variety of `RANGE` types, so it makes sense to look into `CITEXT` support as well.

The support will be implemented through a data type binding, that auto-registers itself to the code generator, when on the classpath (see https://github.com/jOOQ/jOOQ/issues/10763).

Such a binding will cast all bind variables to `citext` explicitly, e.g. `?::citext` or `?::citext[]` if it's an array. It will not, however, patch the behaviour of a query like this:

```sql
with t (a) as (select 'xY'::citext)
select substring(a, 2), a, a = 'Xy' c1, substring(a, 2) = 'y' c2
from t;
```

The result being:

```
|substring|a  |c1  |c2   |
|---------|---|----|-----|
|Y        |xY |true|false|
```

the `a = 'Xy'` comparison works because both operands are either `citext` or implicitly cast to `citext`. In the case of `substring(a, 2) = 'y'`, however, the comparison doesn't work.

This query:

```sql
select string_agg(data_type::text, ', ' order by ordinal_position)
from information_schema.parameters
where specific_name like 'substring%'
group by specific_name
```

Shows:

```sql
|string_agg             |
|-----------------------|
|bit, integer, integer  |
|bit, integer           |
|bytea, integer, integer|
|bytea, integer         |
|text, text             |
|text, text, text       |
|text, integer, integer |
|text, integer          |
```

There's no overload accepting `citext` nor returning `citext`, so the data type is converted by the function. With code generation support, the type will work with all of jOOQ's `Field<String>` supporting API, but maybe not always as intuitively expected. I guess that's acceptable, as this isn't jOOQ specific but dictated by PostgreSQL.

**Comment by lukaseder** [comment]
Implemented in jOOQ 3.17.0

**Comment by ananddevbrat35** [comment]
@lukaseder What would be release date of JOOQ 3.17.0(Any rough estimate will also work if the date is not decided yet). I have a use case for out of the box CITEXT data type extension for postgres.

**Comment by lukaseder** [comment]
Thanks for your message @ananddevbrat35. I never give any release date estimates, because they're always wrong, and thus never useful. You can use the extension right now off github.

**Comment by marshmello275** [comment]
now jooq 3.17.2 is released. I tried to create table with CITEXT column. Still getting the same error

` ERROR: type "citext" does not exist
  Position: 83
	at org.jooq_3.17.2.POSTGRES.debug(Unknown Source)`

**Comment by lukaseder** [comment]
Thanks for your feedback, @marshmello275. This issue here is closed as the feature has shipped. A comment about a potential bug or support request will not be tracked in the issue tracker, as the issue is already closed.

Please open a new issue with the usual details needed to reproduce any possible problems you've encountered: https://github.com/jOOQ/jOOQ/issues/new/choose
