### ISSUE TITLE
DSL class should not be inside the impl package.

### ISSUE THREAD

**Issue by talios** [jOOQ/jOOQ#5953]
When reworking some of our OSGi imports/exports, we noticed that we were exporting all of `org.jooq.*` and not just the top level public `org.jooq` package. Mainly, this was because we need access to `org.jooq.impl.DSL` as an entry point.

It would be nice if this class was moved/mirrored/delegated by a identical copy at `org.jooq.DSL`, so we can hide direct references to internal jooq classes.

Thoughts?

**Comment by lukaseder** [comment]
Yeah, we considered that when we created the class in version 3.0, but rejected the idea because:

1. There's ambiguity afterwards between the two candidate classes. This is annoying, e.g. when using IDE autocompletion.
2. There are other classes in the `impl` package that are public and need to be referenced from the "outside" from time to time, e.g. `DefaultConfiguration` or all the base classes for generated classes, including `TableImpl`, `AbstractRoutine`, etc.
3. It feels dirty.
4. In Java 9, we might finally get this right by leveraging the new module system. We could make more things public, but not export them from jOOQ. That would probably be cleaner, but still a long way away from the current version.
5. One more option would be to only have an `org.jooq` package and move everything from `impl` in there. That's still an option perhaps for jOOQ 4.0.

Unfortunately, right now, we're stuck to the current design, which is a workaround for Java not having a module system.
