### ISSUE TITLE
Wrong mapped values while joining tables.

### ISSUE THREAD

**Issue by piotrowy** [jOOQ/jOOQ#5958]
I develop some web application using jooq to persisting and reading data from/to db. When I run following query in sql:

```sql
select * 
from oksa.runner_area_group 
left join oksa.runner_area_group_runner_area 
  on oksa.runner_area_group_runner_area.runner_area_group_id=oksa.runner_area_group.id
where oksa.runner_area_group_runner_area.runner_area_id=1;
```

I reaceived following data. 

![image](https://cloud.githubusercontent.com/assets/7810642/23762745/5acb117a-04f7-11e7-9a72-4577e2b8c7a6.png)

I did it inside my code and jooq can not map values into object correctly. It takes creation date from 
RUNNER_AREA_GROUP_RUNNER_AREA table and puts it into RunnerAreaGroup object while it should take creation date from RUNNER_AREA_GROUP. 

```java
public List<RunnerAreaGroup> findAllGroupsByRunnerAreaId(Integer id) {
        return jooq.select(RUNNER_AREA_GROUP.NAME, RUNNER_AREA_GROUP.STATUS, RUNNER_AREA_GROUP.)
            .from(RUNNER_AREA_GROUP)
            .leftJoin(RUNNER_AREA_GROUP_RUNNER_AREA)
.on(RUNNER_AREA_GROUP_RUNNER_AREA.RUNNER_AREA_GROUP_ID.eq(RUNNER_AREA_GROUP.ID))
            .where(RUNNER_AREA_GROUP_RUNNER_AREA.RUNNER_AREA_ID.eq(id))
            .fetchInto(RunnerAreaGroup.class);
}
```

My question and issue is why jooq doesn't look at prefixes?

**Comment by lukaseder** [comment]
I'm assuming that `RunnerAreaGroup` is not a record class but a POJO class. Then, the rationale is simple:

1) You're using a JPA annotated POJO class, then that's a bug. I cannot seem to find the issue (I'm sure we registered that already). So, I've created a new one for the time being: https://github.com/jOOQ/jOOQ/issues/5961
2) You're using a simple POJO class, then that's the expected behaviour according to the [`DefaultRecordMapper`](https://www.jooq.org/javadoc/latest/org/jooq/impl/DefaultRecordMapper.html) specification. There's no way one or the other duplicate column name could be clearly identified as "the right one".

Of course, from what I you've posted, I wonder why you need the left join in the first place. Wouldn't this query be more like what you need?

```java
jooq.select(RUNNER_AREA_GROUP.NAME, ...)
    .from(RUNNER_AREA_GROUP)
    .where(RUNNER_AREA_GROUP.ID.in(
        select(RUNNER_AREA_GROUP_RUNNER_AREA.RUNNER_AREA_GROUP_ID)
       .from(RUNNER_AREA_GROUP_RUNNER_AREA)
       .where(RUNNER_AREA_GROUP_RUNNER_AREA.RUNNER_AREA_ID.eq(id))
    ))
    .fetchInto(RunnerAreaGroup.class);
```

**Comment by lukaseder** [comment]
Note, another workaround would be to use `into(Table)` as an intermediate step:

```java
public List<RunnerAreaGroup> findAllGroupsByRunnerAreaId(Integer id) {
        return jooq.select(RUNNER_AREA_GROUP.NAME, RUNNER_AREA_GROUP.STATUS, RUNNER_AREA_GROUP.)
            .from(RUNNER_AREA_GROUP)
            .leftJoin(RUNNER_AREA_GROUP_RUNNER_AREA)
.on(RUNNER_AREA_GROUP_RUNNER_AREA.RUNNER_AREA_GROUP_ID.eq(RUNNER_AREA_GROUP.ID))
            .where(RUNNER_AREA_GROUP_RUNNER_AREA.RUNNER_AREA_ID.eq(id))
            .fetchInto(RUNNER_AREA_GROUP)
            .into(RunnerAreaGroup.class);
}
```

Or, to make sure, you only select `RUNNER_AREA_GROUP` columns, not all columns ([which is a good idea in general](https://blog.jooq.org/2017/03/08/many-sql-performance-problems-stem-from-unnecessary-mandatory-work/))
