### ISSUE TITLE
Do not throw UnsupportedOperationException in DefaultResultSet etc

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#5971]
As commented by user @jezovuk here (https://github.com/jOOQ/jOOQ/issues/24#issuecomment-286802262)

> It seems that now that jOOQ is baselined on Java 8 (open source edition at least) getObject() methods from JDBC41ResultSet (and similar JDBC 4.1-specific methods elsewhere) could actually be implemented to delegate to wrapped JDBC objects (as was originally the case) instead of throwing UnsupportedOperationException. Am I missing something or are those UnsupportedOperationException-s simply left-overs from Java 6 / JDBC 4.0 support?

**Comment by lukaseder** [comment]
@jezovuk: It certainly makes sense to think about such an improvement. There simply hasn't been any use-case from jOOQ's internals to support these new methods, but users using these types outside of jOOQ could definitely profit from improved interoperability between JDBC 4.0, 4.1, and 4.2.

To better understand your use-case would you mind showing an example why this would be useful to you?

**Comment by jezovuk** [comment]
Hi again. My use case is as follows:
  * I'm trying to map ```java.time.LocalDateTime``` to PostgreSQL ```timestamp (without time zone)```
  * codegen is configured with ```javaTimeTypes = true```, which mostly works ok (except for mappings for PG ```timestamp with time zone``` which result in ```org.jooq.impl.SQLDataType.LOCALDATETIME``` instead of ```org.jooq.impl.SQLDataType.OFFSETDATETIME```, as already noted in #5734)
  * ```org.jooq.impl.DefaultBinding``` handles setting ```LocalDateTime``` values as prepared statement parameters via ```java.sql.PreparedStatement.setTimestamp(int, Timestamp)```. ```LocalDateTime``` is converted to ```java.sql.Timestamp``` using JVM's default time zone (via ```Timestamp.valueOf(LocalDateTime)```). Also, no-calendar variant of ```ps.setTimestamp()``` is used, so no tz info there either. Technically, this is mostly fine, since both LocalDateTime-to-Timestamp conversion and Timestamp-to-PG/SQL-timestamp conversion are done in (same) default tz.
  * However, this way it is not possible to use local-date-time/timestamp values that represent DST gap hour in JVM's default time zone. Conversion to ```java.sql.Timestamp``` will 'move' the value by one hour. Exact use case is having an app working in one default tz (convenient for development etc.) but storing local date times to be interpreted according to various different time zones based on other data (related geographic location etc., with values for different geolocations with different time zones all being stored as plain no-tz timestamps in same database table).
  * There is a similar problem with the opposite-direction conversion (SQL->Java), when getting values from result set (also in ```DefaultBinding```). It relies on ```Timestamp.toLocalDateTime()``` and ```java.sql.ResultSet.getTimestamp(int)```, both of which work in default tz.
  * My initial attempt to solve this was writing a custom binding for ```LocalDateTime``` fields which would rely on ```org.postgresql.jdbc.PgPreparedStatement.setObject(int, Object, int, int)``` and ```org.postgresql.jdbc.PgResultSet.getObject(int, Class<T>)``` . Those two seem (based on source code inspection) to handle ```LocalDateTime``` correctly, without intermediate transformation to/from ```java.sql.Timestamp```.
  * At that point I've been hit by unimplemented methods in ```org.jooq.tools.jdbc.JDBC41ResultSet``` (via ```org.jooq.impl.CursorImpl.CursorResultSet```).
  * Finally, the (at least now) obvious workaround was to avoid using ```set/getObject()``` and instead rely on ```set/getTimestamp()``` methods with explicit time zone for conversions to/from ```java.sql.Timestamp```. Using UTC for all conversions (in custom binding) did the trick. It would be nice to avoid conversions altogether, though. Semantically, using ```java.sql.Timestamp``` at all - which is essentially an instant in time - seems wrong when mapping Local* date/time types to tz-less SQL columns. At least for those datatype/database combinations where more direct mapping is supported at JDBC level.

As for opening the new issue, since I already had the workaround the problem was not that important to me, so I simply commented on an existing issue.

Hope all this makes any sense :)

Marko

**Comment by lukaseder** [comment]
Thanks for your detailed explanation. I see, yes that makes a lot of sense, obviously! Will fix ASAP

**Comment by lukaseder** [comment]
Hmm, in fact, we'll still need the `JDBC41ResultSet` et al. but our hierarchies should also extend a new `JDBC42ResultSet`, which adds the additional methods from JDBC 4.2

**Comment by jezovuk** [comment]
That was mighty quick! Thanks.
