### ISSUE TITLE
HSQLDB using DSL#name(String ...), DSL#field(Field) produces malformed SQL

### ISSUE THREAD

**Issue by rtomsick** [jOOQ/jOOQ#5985]
Description
---

I am attempting to write what -- as far as the documentation would indicate -- is a valid query for a simple join of two tables in an HSQLDB database.  However, the rendered SQL produced is invalid [in so far as HSQLDB is concerned.]

Steps to reproduce
---

Execute the following query:

```java
ctx.selectFrom(TABLE.join(EXT_USER_TABLE)
		.on(DSL.field(DSL.name("users", "id"), UUID.class)
			.eq(DSL.field(DSL.name("external_users", "id"), UUID.class))))
	.where(DSL.field(DSL.name("users", "id")).eq("foo_bar"))
```

In the above example TABLE and EXT_USER_TABLE are static constants defined via `DSL#table(String)`

Expected outcome
---

SQL similar to the following:

```sql
SELECT * 
FROM users 
JOIN external_users
ON users.id = external_users.id
WHERE users.id = 'foo_bar'
```

Actual outcome
---

```sql
SELECT * 
FROM users 
JOIN external_users
ON "users"."id" = "external_users"."id"
WHERE "users"."id" = 'foo_bar'
```

This fails, as HSQLDB doesn't seem to understand the quoted names.

Suggested resolution
---

Since the `DSLContext` knows the SQL dialect, shouldn't it automatically render qualified names into something that the underlying DB can accept?

Actually, I only would up facing this since using `TABLE.field(String)` in the above sample code produces a `NullPointerException`.  This seems wrong to me, since the documentation leads one to believe that it would produce a qualified field name.  (It certainly has all of the information it would need to do so!)  I'm happy to split this out into a separate issue if that would help.

Environment
---

jOOQ - 3.9.1
HSQLDB - 2.3.4
Java - 1.8

Thanks!

**Comment by rtomsick** [comment]
I believe this can be worked around with `renderNameStyle`, but given that the behavior is clearly database-specific shouldn't this be automatic?

**Comment by lukaseder** [comment]
Thanks for reporting. Indeed, `RenderNameStyle` is the correct way to control the rendering of `org.jooq.Name` references. Note: There's a feature request to separate the upper/lower case feature from the quoting feature: https://github.com/jOOQ/jOOQ/issues/5909

With all the different implementations per database (case-sensitive by default, case-insensitive/lower case by default, case-insensitive/upper case by default), it would be unwise for jOOQ to "automatically" change the case of a query object that a user specifies. jOOQ by default will:

- Render the case that it receives (e.g. from the code generator as reported by the database, or through user `QueryParts` like you did, through `DSL.name()`)
- Quote all identifiers as `RenderNameStyle.QUOTED` is the default

Note, there's a difference between passing a `String` to a method like `DSL.table()` or a `Name`. The `String` version is part of the plain SQL API (you can use any SQL expression there). Since you define the string version, jOOQ will never add any quotes or adapt the case. The `Name` version only allows identifiers, which are affected by the `RenderNameStyle` flag.

**Comment by rtomsick** [comment]
OK, great.  I guess I assumed that since jOOQ was doing the quoting/casing stuff on `#field(Name)` that it would also do so for `#field(String)` since that's what seemed most intuitive to me.  On second thought though, the existing API makes good sense since you don't want jOOQ to do the classic ORM anti-pattern of "fixing" the user's attempts to write raw SQL.

Thanks!

**Comment by lukaseder** [comment]
> that it would also do so for #field(String) since that's what seemed most intuitive to me. 

I perfectly understand! It looks this way at first, because the initial thought when seeing `field(String)` is: This is for putting column names inside, and many people use this method in this way.

There had been discussions on the jOOQ mailing list about the defaults being the wrong way round, i.e. it might be better to have:

- `String` API for identifiers (and optionally wrapping them in `org.jooq.Name`)
- `SQL` API for plain SQL stuff (there's also an `org.jooq.SQL` type for that)

The main benefit is that this alternative approach would also not result in potential SQL injection risks due to possible string concatenation. But it's a historic thing, and sometimes, being able to write:

```java
where("some_field = some_function('a', 'b')"
```

... is just really useful. Right now, we cannot change this anymore.
