### ISSUE TITLE
HSQLDB - Record#get([...]) rendering issues

### ISSUE THREAD

**Issue by rtomsick** [jOOQ/jOOQ#5986]
I've run into several cases which I believe to be API bugs when using jOOQ against an HSQLDB.

I'll start with what I'd like to write (and what I'd suppose I could write having read the documentation):

```java
final Table<?> FOO_TBL = DSL.table("foos");

this.ctx.selectFrom(FOO_TBL.join(BAR_TBL)
			.on(/*omitted*/)
.fetchOne(r -> new Foo(r.get(FOO_TBL.field("id"))));
```

This fails on `FOO_TBL.field("id")` with a NullPointerException.  I would expect that statement to render to `foos.id` or similar, as all the information needed to do so is there.

Moving on, I next tried:

```java
final Table<?> FOO_TBL = DSL.table("foos");

this.ctx.selectFrom(FOO_TBL.join(BAR_TBL)
			.on(/*omitted*/)
.fetchOne(r -> new Foo(r.get(DSL.field("foos", "id"))));
```

This fails with an `IllegalArgumentException`, telling me that the `Field ("foos"."id") is not contained in Row ("PUBLIC"."FOOS"."ID")`

This is technically true, as HSQLDB seems to uppercase identifiers by default, but uses quoted identifiers verbatim.  Still, the combination of quoting and uppercasing (or not) in the resulting error was a bit of a head-scratcher...

OK, so what if I try this?

```java
final Table<?> FOO_TBL = DSL.table("foos");

this.ctx.selectFrom(FOO_TBL.join(BAR_TBL)
			.on(/*omitted*/)
.fetchOne(r -> new Foo(r.get(DSL.field(DSL.name("foos", "id"))));
```

Same result as `DSL.field("foos", "id"))`

Next, I tried working around it by doing the following:

```java
final Table<?> FOO_TBL = DSL.table("foos");

this.ctx.selectFrom(FOO_TBL.join(BAR_TBL)
			.on(/*omitted*/)
.fetchOne(r -> new Foo(r.get(DSL.field("foos.id")));
```

No quotes in the resulting identifier this time, but alas it still fails:

`Field (foos.id) is not contained in Row ("PUBLIC"."FOOS"."ID")`

Finally, the nuclear (and non-portable option):

```java
final Table<?> FOO_TBL = DSL.table("foos");

this.ctx.selectFrom(FOO_TBL.join(BAR_TBL)
			.on(/*omitted*/)
.fetchOne(r -> new Foo(r.get(DSL.field(DSL.name("FOOS", "ID"))));
```

That works.  But needless to say, it's not really a solution since it's pretty HSQLDB-specific.

---

So that's where I'm at.  I'm kind of at a loss here since the quoting/casing issues seem to be both extremely frustrating to figure out and the sort of thing that I assumed jOOQ would abstract away.  I *know* that the information necessary to do some of the abstraction is available in these cases.

If there's anything I can do to help resolve this, please let me know!

**Comment by rtomsick** [comment]
As a follow-up to this, I tried H2.  Similarly odd behavior.

It looks like perhaps Record#get([...]) and friends aren't honoring `renderNameStyle` in this case?

**Comment by rtomsick** [comment]
Second follow-up: I'm almost certain that's what's happening.  When I put H2 into case-sensitive mode, all is well (well... as well as it can be when trying to write something that can use either H2 or Postgres in the same codepaths...)

**Comment by lukaseder** [comment]
Hmm, there are several misunderstandings here:

### Getting a field from a plain SQL table

You're creating a plain SQL table:

```java
final Table<?> FOO_TBL = DSL.table("foos");
```

This table has no column / type information, so it doesn't know about its `"id"` column:

```java
FOO_TBL.field("id") == null
```

We could certainly debate if the `Table.field(String)` method shouldn't care about whether the field actually exists (or whether it is known). In a broader sense, we would be debating whether this method is part of the DSL API (in favour of your suggestion) or part of the record type hierarchy (in favour of the status quo). Changing that would be quite a breaking change as users will currently assume that this returns `null` if the field is unavailable.

In any case, you've reported another issue where you were using the `DSL.name()` method, which is the correct approach here, or just use `r.get("ID")` for simplicity.

### NullPointerException

Can you post a stack trace? Because there shouldn't be any NPE. The exception you should be getting is this one:

```
java.lang.IllegalArgumentException: Field (null) is not contained in Row (...)
	at org.jooq.impl.Tools.indexOrFail(Tools.java:1326)
	at org.jooq.impl.AbstractRecord.get(AbstractRecord.java:230)
```

### Case sensitivity

This can indeed be confusing, especially because the SQL generation allows for overriding the `RenderNameStyle` but when fetching a field from a record, there's currently no way to do that in a case insensitive manner. There's a feature request to improve this: https://github.com/jOOQ/jOOQ/issues/2656

### Constructing field references

In one example, you called `DSL.field("foos", "id")`. Note: The only applicable method in this case is the `DSL.field(String, Object...)` method, where `"id"` would be considered a bind variable for the `"foos"` plain SQL expression. That wouldn't work here. The correct approach would be to use `DSL.name("FOOS", "ID")`

### Using upper case ("nuclear")

In fact, the majority of databases is case-insensitive / upper case by default. The exception being PostgreSQL, one of the few databases that is case-insensitive / lower case by default. So, the working solution would actually be the best choice here. But if you're using plain SQL, you will inevitably face the case-sensitivity question sooner or later, if you want to support several databases. With jOOQ or without jOOQ (you'd have the same issues with JDBC).

This problem is just much harder to tackle with plain SQL than with the code generator, and certainly, if there's room for improvement (such as #2656), we'll be very happy to look into it.

> So that's where I'm at. I'm kind of at a loss here since the quoting/casing issues seem to be both extremely frustrating to figure out and the sort of thing that I assumed jOOQ would abstract away. I know that the information necessary to do some of the abstraction is available in these cases.

Yes, I'm sorry this has been so frustrating for you thus far. It *is* a frustrating topic because every database is different, and as soon as you're using plain SQL in jOOQ, you're on your own again. Specifically, the `DSL.table(String)` and `DSL.field(String)` methods are *plain SQL* API methods (which might be a bit unintuitive), in case of which jOOQ has no knowledge of the names / identifiers you send to the database, or the things that come back from the database.

It is probably a good thing that jOOQ doesn't abstract these things away when using plain SQL, because users want to be in control of the upper/lower casing.

But again, there's always room for improvement.

**Comment by rtomsick** [comment]
> In one example, you called DSL.field("foos", "id").

This was a mistake in my sample code.  I do know that isn't supposed to work.

> NullPointerException

I can post a stack trace, but I'm afraid it doesn't help much due to where the deref happens.

When I walk through line by line, it shows to my call to `FOO_TBL.field(String, Class<?>)` returning `null`.  

More specifically:

```java

final Table<?> TBL = DSL.table("test");
final Table<?> FOO_TBL = DSL.table(DSL.name("test"));

/* all the following will be null */

Field<?> w = FOO_TBL.field("id");
Field<?> x = FOO_TBL.field("id", String.class);
Field<?> y = FOO_TBL.field(DSL.name("id"));
Field<?> z = FOO_TBL.field(DSL.name("id"), String.class);
Field<?> a = TBL.field("id");
Field<?> b = TBL.field("id", String.class);
Field<?> c = TBL.field(DSL.name("id"));
Field<?> d = TBL.field(DSL.name("id"), String.class);

```

To me this seems to imply that Table#field(...) is basically not supposed to be used like this.  Is that correct? 

If that's the case, then might I propose a bug to document this since as it stands the JavaDoc provides no indication that one cannot use the API in this manner (and, in fact, does not mention that these may even return `null` at all)?

> [excellent explanation snipped]

Thanks for taking the time to reply.  I eventually managed to work around it.  And yes, #2656 would be of great help since I think part of my confusion stemmed from the idea that jOOQ did case abstraction for the query, but not when handling the results.

jOOQ really is a wonderful product, even if dolts like me do occasionally get confused by the API. :smile:

**Comment by lukaseder** [comment]
> To me this seems to imply that Table#field(...) is basically not supposed to be used like this. Is that correct?

Yes, you cannot use `Table.field()` on a `Table` that is constructed this way, because it doesn't contain any field references (unlike a `TableImpl` from generated code). This should clearly be better documented. I've created a feature request for this: https://github.com/jOOQ/jOOQ/issues/5988

> (and, in fact, does not mention that these may even return null at all)?

Yeah, you're right. I'm sure there's some *other* `field(String)` API somewhere that documents this, but this doesn't help if `Table.field(String)` doesn't.

Thank *you* for taking the time to document these flaws! Clearly, there's room for improvement in the plain SQL API!
