### ISSUE TITLE
Add Javadoc to DSL.table(String) and Table.field(String) explaining the lack of field references in plain SQL tables

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#5988]
Users may expect this to work:

```java
Table<?> table = DSL.table("MY_TABLE");
Field<?> field = table.field("ID");
```

i.e. they might expect `field` to be the same as `DSL.field(DSL.name("MY_TABLE", "ID"))`, but that's not the case. `field` is `null`, because the plain SQL table doesn't know anything about its fields.

This should be better documented.

----
See also: https://github.com/jOOQ/jOOQ/issues/5986#issuecomment-288110676

**Comment by rtomsick** [comment]
Out of curiosity, is there any reason why it couldn't produce a field reference?  I mean, it would still be the caller's responsibility to make sure that it corresponded to something that existed (as opposed to codegen, which naturally you can trust to only support existing fields), but it seems like it should be doable without breaking the API, right (at least for `Table#field(Name)`) -- since right now it will always produce `null` it's not like there's an existing caller that's depending on the current behavior...

**Comment by lukaseder** [comment]
Sure. #1 reason: Backwards compatibility. This is expected to return null since 3 major releases.

> it's not like there's an existing caller that's depending on the current behavior...

That is an extremely brave assumption ;) After 8 years of maintaining a widely used API, I beg to differ! Here's a trivial example:

```java
public static boolean containsField(Table<?> table, Name name) {
    return table.field(name) != null;
}
```

**Comment by rtomsick** [comment]
Ah.  Backwards compatibility, the bane of API designers. 

I knew I was being optimistic. :smile:

**Comment by lukaseder** [comment]
I was optimistic, too. At some point. And then came version 1.0
