### ISSUE TITLE
Add newline configuration to code generator

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#6234]
Users should be able to override the default newline `\n` character, e.g. with `\r\n`

**Comment by regrog** [comment]
Any news about this?
I'm working in a cross-platform environment and I have problems in Git with JOOQ generated files.

Thanks

**Comment by lukaseder** [comment]
Implemented in jOOQ 3.12 along with #8138 (configuration of indentation characters)

**Comment by regrog** [comment]
Great!

Could not the separator be the default platform?
` private String               newlineString = System.lineSeparator();`
instead of
` private String               newlineString = "\n";`

Thanks

**Comment by lukaseder** [comment]
Thanks for your suggestion, @regrog. I don't think it's a good idea to change the default behaviour. Perhaps we could add an additional setting, but what is really the use case of using the platform newline character? Because if different developers will work on different platforms, they will generate conflicts, e.g. if git is not configured properly, or if some other VCS is used.

**Comment by regrog** [comment]
I'm interested in this issue because of that. I'm developing with other people with different platform (linux and windows mainly).
We have problems sharing jooq autogenerated files because in windows those file have LF as line separator but cloning the git repo, they start with CRLF.
After regenerating the files, all (but only) the line separators seems to be changes in windows and all clients have `autocrlf = true`
Do you have any tips about this?

**Comment by lukaseder** [comment]
Thanks for sharing your use case, @regrog. I'm not convinced that this is strictly a jOOQ problem, although of course, with the new flag, you can now create platform specific configurations yourself, by using e.g. Maven properties.

However, git has solved this as well. Here is an example document that explains how it works:
https://help.github.com/articles/dealing-with-line-endings/

Hope this helps
