### ISSUE TITLE
Automatic update of dates

### ISSUE THREAD

**Issue by Sytten** [jOOQ/jOOQ#6250]
Hi,
I know this question has been asked before (https://github.com/jOOQ/jOOQ/issues/1592), but my case might be a bit different so that's why I'm opening a ticket.
I would like to be able to add creation and update dates that are updated automatically for every object that has those columns.
From what I have read online, it seemed to be possible with a RecordListener with something like this:
```
public class DateUpdateListener extends DefaultRecordListener {

  private static final String CREATED_DATE_FIELD = "created_date";
  private static final String UPDATED_DATE_FIELD = "updated_date";

  @Override
  public void insertStart(RecordContext context) {
    Stream.of(context.record().fields()).forEach(field -> {
      if (field.getName().equals(CREATED_DATE_FIELD)) {
        context.record().set(field.cast(Timestamp.class), Timestamp.from(Instant.now())); //This give a NPE but you get the idea
      } else if (field.getName().equals(UPDATED_DATE_FIELD)) {
        context.record().set(field.cast(Timestamp.class), Timestamp.from(Instant.now()));
      }
    });
  }

  @Override
  public void updateStart(RecordContext context) {
    Stream.of(context.record().fields()).forEach(field -> {
      if (field.getName().equals(UPDATED_DATE_FIELD)) {
        context.record().set(field.cast(Timestamp.class), Timestamp.from(Instant.now())); //NPE too here, need to fix this
      }
    });
  }
}
```

The listener is called when I do something like:
```
myRecord.store();
```

But I use mostly this syntax:
```
myContext.insertInto(MERCHANT).set(myRecord).onDuplicateKeyUpdate().set(myRecord).execute();
```
And this doesn't call the RecordListener and this is my problem.
If you have any other solution I would greatly appreciate.
Thanks!

**Comment by lukaseder** [comment]
Thank you very much for your report. Regarding the NPE:

```java
context.record().set(field.cast(Timestamp.class), Timestamp.from(Instant.now())); //This give a NPE but you get the idea
```

The reason is that the record doesn't contain the field expression `field.cast(Timestamp.class)`, e.g. if a `Record` has a field `X`, that doesn't mean it also contains a `CAST(X AS TIMESTAMP)` field. Does that make sense?

Indeed, when you use explicit `INSERT`, `UPDATE`, or `DELETE` statements, the `RecordListener` is not affected. This is by design. I understand your expectation with a simple statement like the one you've shown, but the `set(Record)` methods are mere convenience and do not interfere with the record lifecycle that is exposed by the `RecordListener`. In particular, jOOQ doesn't have a way to *know* whether the database executes an `INSERT` or an `UPDATE` on this statement.

I hope this helps.

**Comment by Sytten** [comment]
So basically there is no way to use the RecordListener here.
Do we have another option for automatic dates?

**Comment by lukaseder** [comment]
Yes: Triggers / `DEFAULT` clauses, etc!
