### ISSUE TITLE
Jooq dependent subquery on full outer join

### ISSUE THREAD

**Issue by maxsap** [jOOQ/jOOQ#6272]
Hello,

I wanted to create a query that is adding an additional subquery on a full outer join.
The query that I am trying to achieve is the following:

```sql
SELECT *
FROM User usr
  FULL OUTER JOIN blockReason AS br
    ON (br.user_id = usr.id) AND (br.id = (SELECT "r1"."id"
                                                                      FROM blockReason AS "r1"
                                                                      WHERE "r1"."id" = usr."id"
                                                                      ORDER BY "r1"."created_at" DESC
                                                                      LIMIT 1))
```

I am trying to achieve this using the following code:

```java
    dslContext
            .select(WAVY_USER.ID, WAVY_USER.FIRST_NAME, WAVY_USER.LAST_NAME, WAVY_USER.BIRTH_DATE, WAVY_USER.EMAIL_ADDRESS, WAVY_USER.TYPE, WAVY_USER.AVATAR_URL)
            .select(KLARNA_DECISION.ID.as("klarnaDecisionID"), KLARNA_DECISION.DECISION_TYPE, KLARNA_DECISION.DECISION, KLARNA_DECISION.DECIDED_AT)
            .select(KYC_ATTEMPT.ID.as("kycAttemptID"), KYC_ATTEMPT.VERIFICATION_STATUS, KYC_ATTEMPT.FACE_MATCH_PERCENTAGE)
            .from(WAVY_USER)
            .fullOuterJoin(BLOCK_RESULT_AUDIT).on(BLOCK_RESULT_AUDIT.as("bra").USER_ID.eq(WAVY_USER.ID).and(BLOCK_RESULT_AUDIT.as("bra").ID.eq(subselect)));
```

The output of this one is:

```sql
SELECT
  *
FROM user
  FULL OUTER JOIN blockReason br
    ON (br.user_id = user.id AND br.id = (SELECT r1.id
                                                                      FROM blockReason AS r1
                                                                      WHERE r1.id = user.id
                                                                      ORDER BY r1.created_at DESC
                                                                      LIMIT ?))
```

Please note that this is adding an additional parenthesis on the ON clause that is not what I would expect.

Is this an issue in the query translation?
Can I somehow achieve this or do I have to fallback to plain SQL?

Cheers,
Maximos

**Comment by lukaseder** [comment]
Thank you very much for your enquiry. The rationale of jOOQ adding sometimes unnecessary parentheses is the gazillion ways of combining things in jOOQ's rather powerful expression tree (including combinations of boolean types with predicates, and functions, analytic functions, vendor-specific expressions, or simply plain SQL) that we simply decided to wrap everything in parentheses to stay on the safe side.

Do note that the parentheses are correct and don't have any impact on the query. They might merely bother you for stylistic reasons. In that case, yes, you might need to resort to using plain SQL. There's no way to easily remove the parentheses otherwise.
