### ISSUE TITLE
Generated oracle functions are throwing exceptions after upgrading to jooq 3.9.3

### ISSUE THREAD

**Issue by DiabolusExMachina** [jOOQ/jOOQ#6334]
Hi, 

functions with a boolean result that were generated with jooq 3.9.1 are throwing exceptions when executed after upgrading to jooq 3.9.3. 

> Caused by: org.springframework.jdbc.BadSqlGrammarException: jOOQ; bad SQL grammar [{ ? = call "SCHEMA"."PACKAGE"."SOMEFUNCTIONN"(?) }]; nested exception is java.sql.SQLException: ORA-06550: Zeile 1, Spalte 14:
PLS-00382: expression is of wrong type
ORA-06550: Zeile 1, Spalte 7:
PL/SQL: Statement ignored

I think the problem is releated to:  #5948 

We commit the generated sources in git. Because of that we did not regenerate after upgrading jooq. So we were executing a function generated with jooq 3.9.1 with jooq.3.9.3 in the classpath

Is this supposed to work or do we have to regenerate every time we update jooq?

**Comment by lukaseder** [comment]
> Is this supposed to work or do we have to regenerate every time we update jooq?

Usually, patch releases do not introduce new API, but in the case of #5948, we had to introduce additional internal API that generated code relies upon, in order to be able to distinguish between:

- `BOOLEAN` data type rewrites
- `PL/SQL BOOLEAN` types

So in general, it's not a bad idea to generate the sources with the runtime version you're using. Let me know if this helps.

**Comment by lukaseder** [comment]
I'm closing this for now as I suspect that the problem was caused because code was not re-generated. Please, feel free to reopen if needed.
