### ISSUE TITLE
Change in PostgreSQL enum generation between 3.8.* and 3.9.*

### ISSUE THREAD

**Issue by martinlau** [jOOQ/jOOQ#6367]
In 3.8.7 an enum defined in postgres via:

```sql
CREATE TYPE test_status AS ENUM ('ACTIVE', 'SUSPENDED');
CREATE TABLE test (status test_status NOT NULL);
```

Resulted in the table field definition (via jooq-codegen-maven):

```java
public final TableField<TestRecord, TestStatus> STATUS = createField("status", org.jooq.util.postgres.PostgresDataType.VARCHAR.asEnumDataType(example.jooq.enums.TestStatus.class), this, "");
```

The same configuration using 3.9.[0..3] codegen gives:

```java
public final TableField<TestRecord, Object> STATUS = createField("status", org.jooq.impl.DefaultDataType.getDefaultDataType("USER-DEFINED"), this, "");
```

(Note: change of type from TableField's field type from Status to Object and associated paraphernalia in createField())

The enum is generated, just not used. Am I missing something in my config, or is this a regression?

**Comment by martinlau** [comment]
Appears to also be related to using a non-default schema. If I base codegen on the 'public' schema things work as expected, if I use a different schema, the above occurs.

**Comment by martinlau** [comment]
Seems to be related to a discrepency in naming between what's passed to `org.jooq.util.AbstractDatabase#getDefinition(java.util.List<D>, org.jooq.Name, boolean)`.

The passed in Name (second param) has a qualifiedNamePart the equivalent of:

```java
String[2]{"public", "test_status"}
```

While definition.getQualifiedNamePart() is the equivalent of:
```java
String[1]{"test_status"}
```

And so not being picked up as an enum in org.jooq.util.JavaGenerator#getType in the code:

```java
        // Check for ENUM types
        else if (db.getEnum(schema, u) != null) {
            type = getStrategy().getFullJavaClassName(db.getEnum(schema, u));
        }
```

Hypothesising: may be related to 4659e83f09f224d39aee95254016e0c40bcd61cc - in particular https://github.com/jOOQ/jOOQ/commit/4659e83f09f224d39aee95254016e0c40bcd61cc#diff-140547837bd66e471db3fcf783f91167L117 where the DefaultDataTypeDefinition's UserType's name was changed from `record.get(COLUMNS.UDT_NAME)` to `name(record.get(COLUMNS.UDT_SCHEMA), record.get(COLUMNS.UDT_NAME))` requiring an  equivalent change somewhere else.

**Comment by lukaseder** [comment]
Thank you very much for your detailed analysis. However, I cannot reproduce this with jOOQ 3.9.3 (or 3.10-SNAPSHOT). The column is generated correctly:

```java
    public final TableField<TestRecord, TestStatus> STATUS = createField("status", org.jooq.util.postgres.PostgresDataType.VARCHAR.asEnumDataType(org.jooq.test.postgres.generatedclasses.public_.enums.TestStatus.class), this, "");
```

What PostgreSQL version are you using?

**Comment by martinlau** [comment]
Ok, we've just had a near head explosion through "it's entirely reproducible for me, I'll throw together a sample project" to "wait, it works reliably there, WTF!@#"

However, looks like it only happens with:

```xml
<outputSchemaToDefault>true</outputSchemaToDefault>
```

(which makes a bit of sense with the hypothesis above about it being related to the UserType / name / schema change)

https://github.com/martinlau/jooq-6367/ shows the error with different postgres versions running out of docker.

**Comment by lukaseder** [comment]
Oh wow, thank you very much for persisting, that looks like a rather hard to track down issue. I'll look into this tomorrow.

**Comment by lukaseder** [comment]
OK, perfect. I can reproduce this now. Will investigate.

Thanks again for your detailed analysis and help!

**Comment by lukaseder** [comment]
Hmm, while the change you've mentioned might have certainly triggered the regression, I think the previous implementation was just obstructing the real issue here, which I believe is the application of "default" catalogs and schemas to the input name as well as the output name:

![image](https://user-images.githubusercontent.com/734593/27961564-6f8f9e6e-632f-11e7-8cba-3f89b1d365d1.png)

It should only be applied to the output name. I'll have to evaluate the impact of changing this...

**Comment by lukaseder** [comment]
Indeed, the current implementation is quite wrong. Additional issues that could be caused by `<outputSchemaToDefault>true</outputSchemaToDefault`:

- Qualified name matching in `<include/>` and `<exclude/>` and other configuration elements doesn't work
- Qualified name matching in `<forcedTypes/>` doesn't work
- Logging is incomplete
- `XMLDatabase` routine parameters aren't generated correctly

There are no regressions I can see when deleting the erroneous code, so this is an easy fix.

Thanks again!

**Comment by lukaseder** [comment]
The fix will be performed with another issue, which covers the real problem (wrong return value from `Definition.getQualifiedName()`), not the side-effect documented here (Enums aren't linked correctly): https://github.com/jOOQ/jOOQ/issues/6395

**Comment by lukaseder** [comment]
#6395 will be merged to jOOQ 3.9.4 and 3.8.8

**Comment by martinlau** [comment]
Great, thanks!

**Comment by babbaj** [comment]
still getting trolled by this

**Comment by knutwannheden** [comment]
@babbaj Thanks for reaching out. As this issue was closed some time ago, we would be interested in the scenario where this is causing you problems. Can you give us some more details and maybe even an MVCE so we can reproduce the problem?

**Comment by babbaj** [comment]
@knutwannheden 
https://github.com/babbaj/jooq_broken_enum
Just run `./gradlew generateTestJooqSchemaSource` and the broken code will be in `build/generated-src/jooq/test/test/sql/tables/History.java`

**Comment by knutwannheden** [comment]
@babbaj Thank you very much for getting back to us with a reproducible example. As it turns out this is caused by the related issue #7917, which we plan to fix in the upcoming release.

As a workaround you might be able to add a forced type to your `build.gradle` file:

```groovy
forcedType {
	userType = 'test.sql.enums.Status'
	enumConverter = true
	includeExpression = 'HISTORY\\.STATUS'
}
```

Let me know if this works for you.

**Comment by lukaseder** [comment]
I'm not convinced that the case shown by @babbaj in https://github.com/jOOQ/jOOQ/issues/6367#issuecomment-573365483 is really strictly related to this issue. In the MCVE by @babbaj, `DDLDatabase` is being used, and what @knutwannheden meant by us planning to fix #7917 in the upcoming release is that we're hoping to address some issues caused by us currently using H2 behind the scenes in `DDLDatabase` (no actual promise yet).

But this is all unrelated to the original issue, which is not using `DDLDatabase` but an actual PostgreSQL connection.

**Comment by alexvas** [comment]
Still have an issue with enums generation in Postgress 11. Here is a reproducible example:
https://github.com/alexvas/jooqbug
jOOQ version is 3.14.3

**Comment by lukaseder** [comment]
@alexvas Well, you turned off the generation of user defined types, no?

```
isUdts = false
```

**Comment by alexvas** [comment]
@lukaseder  my fault, sorry. The `isUdts = true` fixes enum code generation.
