### ISSUE TITLE
Add support for DROP TEMPORARY TABLE

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#6371]
Some databases support this syntax explicitly, e.g. MySQL. Even if the keyword `TEMPORARY` is usually not needed, it may help users who discover the jOOQ API not to get confused by this.

----
See also:
https://www.jooq.org/doc/latest/manual/sql-building/ddl-statements/drop-statement/#comment-3397392667

**Comment by rajveerappan** [comment]
Unfortunately I don't have a trivial example to share for repro but it seems like in the context of concurrent access it does end up mattering whether you do `DROP TABLE temp` or `DROP TEMPORARY TABLE temp` with MySQL. `DROP TEMPORARY TABLE` correctly immediately drops the temp table whereas `DROP TABLE` doesn't seem to properly discard the table immediately.

**Comment by knutwannheden** [comment]
Thank you for the feedback.

Let's see what the MySQL manual (https://dev.mysql.com/doc/refman/8.0/en/drop-table.html) has to say on this:

> The TEMPORARY keyword has the following effects:
>
> * The statement drops only TEMPORARY tables.
> * The statement does not cause an implicit commit.
> * No access rights are checked. A TEMPORARY table is visible only with the session that created it, so no check is necessary.
> 
> Including the TEMPORARY keyword is a good way to prevent accidentally dropping non-TEMPORARY tables.

Since the current 3.12 implementation does not render the `TEMPORARY` keyword when using `DSL#dropTemporaryTable()` or `DSLContext#dropTemporaryTable()`, I will now reopen this issue so that we can reconsider this decision.

**Comment by knutwannheden** [comment]
Since the issue was already part of the 3.11 release (for some reason I thought this was 3.12), I will close this issue again and open a new issue instead.
