### ISSUE TITLE
LoaderLoadStep should support getSQL()

### ISSUE THREAD

**Issue by ghulands** [jOOQ/jOOQ#6398]
I use jooq for sql generation only as I use an asynchronous database api. For bulk inserts of data, the loader api is recommended, but it also requires the jdbc connection to be set on the DSLContext for doing the actual insert.

It would be great if the LoaderLoadStep supported the getSQL() methods that are available on the Select, Insert, etc interfaces so that i can just feed the generated sql into the async db connection.

**Comment by lukaseder** [comment]
Thank you very much for your suggestion. That's a very interesting thought. I suspect that your problem shouldn't be solved with `getSQL()` directly, but perhaps we should be able to intercept the queries being executed, e.g. with something similar to an `ExecuteListener`.

One workaround could be to use a `MockConnection` in order to intercept all generated SQL on a lower JDBC level. Let me know if this helps.

**Comment by lukaseder** [comment]
Reviewing this in the context of a few other loader improvements.

`getSQL()` implies the presence of a single SQL statement. The `Loader` API is not a `Query`, it is much more an execution abstraction, which abstracts over bulk, batch, and commit sizes. The semantics of `getSQL()` would be difficult to define - the most reasonable one would just create a statement batch (with `;` separated SQL statements), but that would be a first in jOOQ's API. Imagine someone requesting a similar thing be done for the transaction API, where a transaction wrapper would produce the transaction's SQL string. Not unreasonable as a concept, but perhaps re-using `getSQL()` is the wrong approach.

I think that in the future, we might be able to model execution pipelines like the loader API in a different way, such that they can be serialised on alternative execution models, including reactive ones (see e.g. https://github.com/jOOQ/jOOQ/issues/6298), but that would not be loader specific, it would be much more thorough.

I'm closing this as won't fix, because I don't think the introduced complexity pulls the weight of doing this only for the loader API specifically.
