### ISSUE TITLE
More typesafe DECODE()

### ISSUE THREAD

**Issue by McNetic** [jOOQ/jOOQ#6460]
When using `DECODE()`, I get:
```java
Field<String> f = decode("a", "b", "c", "d"); // OK
Field<String> g = decode("a", "b", "c", val("d")); // OK
h = decode("a", "b", val("c"), "d"); // also Field<String> ?
```
As you can guess, h is not `Field<String>`, but rather `Field<Param<String>>` (or `Field<Field<String>>`, if I use a function instead of `val()`).

I am aware this is a limitation or feature of java generics, but it would be very nice to be able to specify the correct type for `DECODE()` calls. I'm not exactly sure how this should be specified, however.

Or is there a different way to work around the issue aside from something like this:
```java
Field<String> i = decode("a", "impossible value", "String", "b", val("c"), "d");
```

**Comment by lukaseder** [comment]
Indeed, Java's generics do not allow for specifying sophisticated type constraints on generic types. We could, of course, generate many more `decode()` methods, e.g. up to 20 type safe arguments or so, before resorting to the varargs "catch all" argument.

But the inferred type of your `decode` call could always be just `Object` or something like `Serializable & Comparable<?>`, so the type safety is often a lie (unless there's an assignment as you did). This is in fact a similar issue as #5340.

In your particular case, I guess there's no problem really, because by default, all strings are wrapped in `val()`, so the `val()` call isn't really necessary. Maybe, you had a more complex, real-world use-case in mind?

**Comment by McNetic** [comment]
Yes, I used `val()` just to produce the simplest example. Hence the reference to using a function instead. I have in fact nested decode() calls :-). The "problem" arises when I have to assign the resulting record field (which requires a cast then).

**Comment by lukaseder** [comment]
Oh indeed, nested decode() calls are more interesting! Well, you can always enforce the generic type binding like this:

```java
DSL.<String, String>decode(...)
```

**Comment by McNetic** [comment]
And the title is a bit misleading, my request is not so much about type safety but more about type consistency. 
Thinking more about it, I found there is a simple solution:
```
Field<String> f = decode(val("a"), val("b"), decode([...]), val("d"))
```
I have `Field` parameters for all arguments but the second in my real world example, anyways. It's just the top level `decode()` that has to get all `Field` parameters, and everything is fine. Maybe there is not really a need for more API ;-). Thank you very much.

**Comment by lukaseder** [comment]
Aha, I see - yes of course. Your solution is the way to go forward. I should've seen this yesterday...
