### ISSUE TITLE
Codegen error with Java 9: java.lang.NoClassDefFoundError: javax/xml/bind/ValidationEventHandler

### ISSUE THREAD

**Issue by Neverminder** [jOOQ/jOOQ#6650]
### Expected behavior and actual behavior:

Code generator produces an error when using Java 9:

```
[info] Running org.jooq.util.GenerationTool
[error] (run-main-0) java.lang.NoClassDefFoundError: javax/xml/bind/ValidationEventHandler
```

### Steps to reproduce the problem:

Run code generator

### Versions:

- jOOQ: 3.10.0
- Java: 9
- Database (include vendor): Postgresql 9.6
- JDBC Driver (include name if inofficial driver): Postgresql JDBC 42.1.4

**Comment by lukaseder** [comment]
Thank you very much for your report. This is a known issue and is due to the fact that JAXB is no longer on the default module path of JDK 9. It can be added explicitly using the `--add-modules java.xml.bind` flag. E.g. in Maven:

> set MAVEN_OPTS=%MAVEN_OPTS% --add-modules java.xml.bind

This is also documented here:
https://github.com/jOOQ/jOOQ/issues/6477#issuecomment-319490219

**Comment by bbarin** [comment]
Hey I fixed this putting as a dependency within the JOOQ's plugin section

**Comment by lukaseder** [comment]
@bbarin Yes, if you want to use explicit dependencies in Maven, then you have to add all the transitive dependencies as well. I think it's only JAXB and `javax.activation`

**Comment by bbarin** [comment]
@lukaseder I think would be useful if JOOQ plugin would accept something like `<argLine>` like the maven compiler plugin as MAVEN_OPTS makes more difficult to have a repeatable build, no?

**Comment by lukaseder** [comment]
That's an interesting idea, it had never occurred to me that the code generator plugin could spawn a new process in order to run the code generation. Currently, it runs in the Maven plugin process, so this `<argLine>` suggestion won't work.

I've created a new feature request for this: #6665. Right now, I don't think that this single use-case is worth adding this feature, but who knows, perhaps other use-cases will show up eventually.
