### ISSUE TITLE
Select with offset and limit is worng in Firebird database 

### ISSUE THREAD

**Issue by betonetotbo** [jOOQ/jOOQ#6719]
### Expected behavior and actual behavior:

The resulting SQL must be: 
`select first 10 skip 4 MY_FIELD from MY_TABLE` 

Instead of 
`select MY_FIELD from MY_TABLE limit 10 offset 4`

### Steps to reproduce the problem:
- Create a table MY_TABLE with field MY_FIELD as Integer
- Select with offset and limit: `dslContext.select().from(MyTable.MY_TABLE).offset(4).limit(10).fetch();`
- Got error: `SQL error code = -104 Token unknown - line 1, column X ?] with root cause`

### Versions:

- jOOQ: 3.10.1
- Java: 1.8
- Database (include vendor): Firebird 2.5.7 x64
- JDBC Driver (include name if inofficial driver): jaybird-jdk8 2.2.13

**Comment by lukaseder** [comment]
Thank you very much for your report. jOOQ generates a `ROWS .. TO ..` clause for Firebird. The reason for the issue here is probably that your `dslContext` is not correctly initialised with the `SQLDialect.FIREBIRD` dialect family (or its versions 2.5 or 3.0).

If this doesn't resolve your issue, feel free to reopen this and we'll look into it more in detail.
