### ISSUE TITLE
Document that DDLDatabase, XMLDatabase, JPADatabase require an additional dependency

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#6866]
These databases are located in the jooq-meta-extensions module. We should document this dependency in the manual:
https://www.jooq.org/doc/latest/manual/code-generation/codegen-ddl/#comment-3635452023

**Comment by tkaiser** [comment]
i'm running into this and can't get the described workaround to work, I tried to add the jooq-meta-extensions to the buildscript/dependencies part but i'm still getting `java.lang.ClassNotFoundException: org.jooq.util.ddl.DDLDatabase`

````
buildscript {	
	repositories {
		mavenCentral()
		maven {
	    	url "https://plugins.gradle.org/m2/"
	    }
	    jcenter()
	}
	dependencies {	
		classpath("org.jooq:jooq-meta-extensions:3.10.2")
	}
}`

The dependency itself is getting resolved properly fwiw. Any help would be greatly appreciated.

**Comment by lukaseder** [comment]
@tkaiser : Can you add the dependency to Gradle? Also, are you using the https://github.com/etiennestuder/gradle-jooq-plugin? Maybe a question there might help?

**Comment by tkaiser** [comment]
yep if i add it to the regular dependencies i get it right there 
![image](https://user-images.githubusercontent.com/8970774/34150057-85abb8f0-e4a7-11e7-92e1-489689ad5278.png)

I am using the gradle-jooq-plugin, my config block looks like this
```
jooq {
    version = '3.10.2'
    edition = 'OSS'
    sample(sourceSets.main) {
        generator {
            database {
                name = 'org.jooq.util.ddl.DDLDatabase'
                properties {
                    property {
                        key = 'scripts'
                        value = 'src/main/resources/db/migration'
                    }
                }
            }
            target {
                packageName = 'com.foo.package'
            }
        }
    }
}
```

**Comment by lukaseder** [comment]
This has been an often discussed issue on the plugin issue tracker, e.g. https://github.com/etiennestuder/gradle-jooq-plugin/issues/34

I'm sure the dependencies are simply configured on the wrong place...

**Comment by tkaiser** [comment]
correct, that did the trick! the dependency should have gone into `jooqRuntime`. imo it's not possible to solve this from the regular docs though, or without lots of trial and error.

 thanks much for the speedy response!

**Comment by lukaseder** [comment]
Yes I absolutely agree this should be documented somewhere! Thanks for following up.

**Comment by rossetti** [comment]
I cannot tell from the documentation where this dependency is supposed to go.  Is the dependency supposed to be in the 3rd party gradle plugin?  Or can the dependency be specified in the normal gradle build dependencies? And, what exactly is the dependency?  Thanks!

**Comment by lukaseder** [comment]
@rossetti : What manual pages have you been looking at where you found this information to be missing?

**Comment by rossetti** [comment]
I am looking at the 3.10 manual, section 6.24 pages 277-278.  I am using the programmatic configuration.  Apparently, I need to somehow add a dependency to get access to org.jooq.util.ddl.DDLDatabase

I guess I don’t know how to do that.  I am not currently using the jooq gradle plugin.

But, I am using gradle as my build, where I have:


dependencies {
    // https://mvnrepository.com/artifact/org.jooq/jooq
    compile group: 'org.jooq', name: 'jooq', version: '3.10.4'
    // https://mvnrepository.com/artifact/org.jooq/jooq-meta
    compile group: 'org.jooq', name: 'jooq-meta', version: '3.10.4'
    // https://mvnrepository.com/artifact/org.jooq/jooq-codegen
    compile group: 'org.jooq', name: 'jooq-codegen', version: ‘3.10.4'

}


org.jooq.util.jaxb.Configuration configuration = new org.jooq.util.jaxb.Configuration();

configuration.withGenerator(new Generator()
                .withDatabase(
                        new org.jooq.util.jaxb.Database()
                        .withName("org.jooq.util.ddl.DDLDatabase")
                        .withIncludes(".*")
                        .withExcludes("")
                        .withProperties(new Property()
                                        .withKey("scripts")
                                        .withValue("src/main/resources/database.sql")))
                .withTarget(new Target().withPackageName(packageName).withDirectory(pkgDirName))
                .withGenerate(new Generate()
                        .withIndexes(true)
                        .withLinks(true)));

GenerationTool tool = new GenerationTool();
tool.run(configuration);

Exception in thread "main" java.lang.ClassNotFoundException: org.jooq.util.ddl.DDLDatabase
at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
at org.jooq.util.GenerationTool.loadClass(GenerationTool.java:704)
at org.jooq.util.GenerationTool.run(GenerationTool.java:305)
at dbutil.TestCodeGeneration.jooqCodeGeneration(TestCodeGeneration.java:76)
at dbutil.TestCodeGeneration.main(TestCodeGeneration.java:21)



On Jun 28, 2018, at 4:06 PM, Lukas Eder <notifications@github.com<mailto:notifications@github.com>> wrote:


@rossetti<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_rossetti&d=DwMCaQ&c=7ypwAowFJ8v-mw8AB-SdSueVQgSDL4HiiSaLK01W8HA&r=C96S0tW3jDYiCJXmsFDkgGY0LpiUY-1hylfP31kcNUc&m=7Lz9-Vk8mcpm2531f510nKkxt_kJJ_Vuy-kLRJiylcA&s=QAbJkwIvEXA7-dqDuDAVrsi1orksjNcRpfBNEfTxbMw&e=> : What manual pages have you been looking at where you found this information to be missing?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_jOOQ_jOOQ_issues_6866-23issuecomment-2D401173447&d=DwMCaQ&c=7ypwAowFJ8v-mw8AB-SdSueVQgSDL4HiiSaLK01W8HA&r=C96S0tW3jDYiCJXmsFDkgGY0LpiUY-1hylfP31kcNUc&m=7Lz9-Vk8mcpm2531f510nKkxt_kJJ_Vuy-kLRJiylcA&s=pwHjchGXgYfGJSnDqbv8x1QfsMES9zxaLnY1YLRgezk&e=>, or mute the thread<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AAESVtkmgYzgMUm0PdcIO5tyqQb-5FIPXMks5uBUVjgaJpZM4QtEUy&d=DwMCaQ&c=7ypwAowFJ8v-mw8AB-SdSueVQgSDL4HiiSaLK01W8HA&r=C96S0tW3jDYiCJXmsFDkgGY0LpiUY-1hylfP31kcNUc&m=7Lz9-Vk8mcpm2531f510nKkxt_kJJ_Vuy-kLRJiylcA&s=xgp_WKscbwH0tWaN9LNKowfg0aSzDB2ufqeZVTa5qbg&e=>.


-----------------------------------------------------
Manuel D. Rossetti, Ph.D., P.E.
Professor and Associate Department Head
Director, Center for Excellence in Logistics and Distribution<http://www.celdi.ineg.uark.edu/>
University of Arkansas
Department of Industrial Engineering
4207 Bell Engineering Center
Fayetteville, AR 72701
Phone: (479) 575-6756
Fax: (479) 575-8431
email: rossetti@uark.edu<mailto:rossetti@uark.edu>
www: www.uark.edu/~rossetti<http://www.uark.edu/~rossetti>

[cid:F66FDC2F-06E1-4D7B-A942-F64F5482F483@uark.edu]

CELDi is a university-based enterprise providing innovative solutions for logistics and distribution excellence with our member organizations.

**Comment by rossetti** [comment]
I am looking at the 3.10 manual, section 6.24 pages 277-278.  I am using the programmatic configuration.  Apparently, I need to somehow add a dependency to get access to org.jooq.util.ddl.DDLDatabase

I guess I don’t know how to do that.  I am not currently using the jooq gradle plugin.

But, I am using gradle as my build, where I have:


dependencies {
    // https://mvnrepository.com/artifact/org.jooq/jooq
    compile group: 'org.jooq', name: 'jooq', version: '3.10.4'
    // https://mvnrepository.com/artifact/org.jooq/jooq-meta
    compile group: 'org.jooq', name: 'jooq-meta', version: '3.10.4'
    // https://mvnrepository.com/artifact/org.jooq/jooq-codegen
    compile group: 'org.jooq', name: 'jooq-codegen', version: ‘3.10.4'

}


org.jooq.util.jaxb.Configuration configuration = new org.jooq.util.jaxb.Configuration();

configuration.withGenerator(new Generator()
                .withDatabase(
                        new org.jooq.util.jaxb.Database()
                        .withName("org.jooq.util.ddl.DDLDatabase")
                        .withIncludes(".*")
                        .withExcludes("")
                        .withProperties(new Property()
                                        .withKey("scripts")
                                        .withValue("src/main/resources/database.sql")))
                .withTarget(new Target().withPackageName(packageName).withDirectory(pkgDirName))
                .withGenerate(new Generate()
                        .withIndexes(true)
                        .withLinks(true)));

GenerationTool tool = new GenerationTool();
tool.run(configuration);

Exception in thread "main" java.lang.ClassNotFoundException: org.jooq.util.ddl.DDLDatabase
at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
at org.jooq.util.GenerationTool.loadClass(GenerationTool.java:704)
at org.jooq.util.GenerationTool.run(GenerationTool.java:305)
at dbutil.TestCodeGeneration.jooqCodeGeneration(TestCodeGeneration.java:76)
at dbutil.TestCodeGeneration.main(TestCodeGeneration.java:21)

**Comment by rossetti** [comment]
It looks like you have to add:

    runtime group: 'org.jooq', name: 'jooq-meta-extensions', version: '3.10.4'

to your dependency.  That got me past the class not found error.  I believe that this should be clearer in the manual.

**Comment by lukaseder** [comment]
Oh, I see. Thanks for the pointer. Yes, clearly, that section should contain additional dependency information. Looks like this was forgotten...
