### ISSUE TITLE
ResultQuery.fetchGroups() should auto-convert key and value types to argument types

### ISSUE THREAD

**Issue by rtomsick** [jOOQ/jOOQ#6916]
### Steps to reproduce the problem:

Given the following example code:

```java
Map<Integer, List<String> example = 
	this.ctx.selectFrom(N_TABLE)
		.where(field(name("id__entries"), Integer.class).in(ids))
		.fetchGroups(field(name("id__entries"), Integer.class), 
				field(name("name"), String.class));
```

where `N_TABLE` is a table with the given schema:

```sql
CREATE TABLE "non_proprietary_names" (
	"id__entries"		BIGINT NOT NULL,
	"name"			VARCHAR(512) NOT NULL,

	FOREIGN KEY ("id__entries") REFERENCES "entries" ("id")
);
```

### Expected behavior

`example` is a `Map` implementation with keys of type `Integer`

### Actual behavior:

`example` is a `Map` implementation with keys of type `Long`.

### Discussion/resolution

The impact of this is that **calls to `Map#get(Object)` and `Map#containsKey(Object)` with `Integer` arguments do not work**, and calls to the same with `Long` arguments (although possible) do not seem to make sense (at first glance).

This is both difficult to track down and completely non-obvious.  That, coupled with the fact that the resulting map violates the expectations set by the type bounds (meaning that the caller would have to deliberately ignore the declared bounds in order to retrieve anything from the map) makes me believe this is a rather significant issue.

While it can certainly be argued that the caller is partially at fault for specifying that the field type is `Integer` when the underlying schema declares the column as `BIGINT`, the current outcome is extremely undesirable.  Obviously the type safety won't save the caller here since the `K` and `V` types are erased (plus it's `Map#get(Object)`, not `Map#get(K)`...), but since `Field` retains a class reference jOOQ can certainly detect the mismatch between what the caller is asking for and what the preferred (i.e. corresponding to the schema) type would be.

One resolution (that would be consistent with jOOQ's behavior elsewhere) would be to ensure compatibility between the type specified by the `Field` and that required by the result.  This would at least make the failure obvious.

### Versions:

jOOQ: 3.10.2
Java: 1.8+
Database (include vendor): HSQLDB

**Comment by lukaseder** [comment]
Thanks for your report. That's definitely not what would be expected from the API usage, which isn't wrong given that you're correctly referencing the columns by name. This is probably caused by the same flaw as #5846 - although it might not be an exact duplicate.

The workaround is to always provide an explicit `select()` clause to prevent jOOQ's "guessing" the appropriate data type when using plain SQL. I.e. this will work:

```java
Field<Integer> idEntries = field(name("id__entries"), Integer.class);
Field<String> name = field(name("name"), String.class);

Map<Integer, List<String> example = 
	this.ctx.select(idEntries, name)
		.from(N_TABLE)
		.where(idEntries.in(ids))
		.fetchGroups(idEntries, name);
```

**Comment by rtomsick** [comment]
So the type SQL->Java inference doesn't happen in `#fetch(...)` but rather based on the `#select(...)` fields (if any)?

Hmm... that makes sense, although I must admit that I had no idea that it worked that way until now!

I appreciate the prompt response; I'll try to explicitly specify columns until this gets fixed.

Thanks for all your work on jOOQ!

**Comment by lukaseder** [comment]
The point is that normally, if you're using the code generator, then the column types are available through the `FROM` clause because the table that you're passing to the `FROM` clause contains the generated column references (including potentially your own converters / bindings, etc).

When you're not using the code generator, it's still possible to write your own tables in a way that jOOQ can discover column types *prior* to executing the query, but if your `N_TABLE` is constructed using `table(name("n_table"))`, then jOOQ doesn't have any such information and needs to discover the types from JDBC's `ResultSetMetaData`.

Later on, then, all the `fetch()` methods will execute `fetchLazy()` behind the scenes, and transform the result to the types you're looking for *after* fetching the records. There are some feature requests related to #6739 which aim for changing this to allow for bypassing the intermediate record but instead fetch directly into the target data structure. But those changes are delicate as they might break some assumptions around the `RecordListener` SPI.

> I'll try to explicitly specify columns until this gets fixed.

You should *always* explicitly specify columns, except if you

- Really need all of them
- Intend to store the record back to the database using an `UpdatableRecord` (which isn't available if you're not using the code generator)

`SELECT *` is bad. I really need to blog about this once more :-)

**Comment by rtomsick** [comment]
> but if your N_TABLE is constructed using table(name("n_table")), then jOOQ doesn't have any such information and needs to discover the types from JDBC's ResultSetMetaData.

Ah, I think that's where I didn't understand jOOQ's inner workings.  I assumed that the inference was happening elsewhere, not that `Table` was vital to the type determination.

> SELECT * is bad. I really need to blog about this once more :-)

I know.  :)  I only do `#selectFrom()` (aka `SELECT *`) in cases where I *do* really need all of the columns.  This was one such case.

Number #6739 looks great!  I'll keep an eye on that, thanks.

**Comment by lukaseder** [comment]
This is the same issue as https://github.com/jOOQ/jOOQ/issues/5846
