### ISSUE TITLE
Allow Maven plugin to succeed in absence of valid DB connection if schema is up to date

### ISSUE THREAD

**Issue by jdimeo** [jOOQ/jOOQ#6971]
Since I am on a client's VPN, I can't connect to the test database against which the JOOQ code gen maven plugin is configured. I want to re-package my code via `mvn package`, but JOOQ fails because it can't connect to the database, even though it wouldn't actually do anything because I've hard-coded my schema version provider to `1`. Can the plugin be configured such that it only fails if the schema is *not* up to date and *then* it fails to connect to the database?

Forgive me if this is a duplicate- I tried searching but this kind of thing was hard to search for.

**Comment by lukaseder** [comment]
Thank you very much for your suggestion. Indeed, there should probably be a flag that allows for ignoring failures. Other Maven plugins have similar flags to keep the build from breaking in such cases. This is particularly useful if you don't generate your code into `target/` subdirectories, but keep them under version control.

The suggested approach with the schema version provider won't work because without a database connection, we don't know what schemas there are now. For instance, some schemas might have been removed, others might have been added. The code generator invokes your schema version provider once per *actual* schema, not per *previously generated* schema.

A workaround could be to use the plugin's `skip` flag in the configuration (available only in the Maven plugin): https://www.jooq.org/doc/latest/manual/code-generation/codegen-maven

Another workaround might be to use XML (or JPA, DDL) as your meta data source:

- https://www.jooq.org/doc/latest/manual/code-generation/codegen-jpa/
- https://www.jooq.org/doc/latest/manual/code-generation/codegen-xml/
- https://www.jooq.org/doc/latest/manual/code-generation/codegen-ddl/

Anyway, we should definitely have an "ignore errors" flag of some sort.

**Comment by jdimeo** [comment]
All of your workarounds you suggested are great- I especially like the fact that we can use DDL now - that's huge for me since I already was maintaining DDL, which I had to keep in sync with the live DB which I had to keep in sync with JOOQ- I love the fact that we can now have it all checked in to version control and be internally consistent in the absence of the "live" DB or internet connection. Thank you!

**Comment by lukaseder** [comment]
> I especially like the fact that we can use DDL now - that's huge for me since I already was maintaining DDL, which I had to keep in sync with the live DB which I had to keep in sync with JOOQ

Cool! Any feedback you can provide on features that might be missing in the parser would be greatly appreciated!

**Comment by knutwannheden** [comment]
With jOOQ 3.12 it will be possible to specify an `onError` property when running the jOOQ Maven plugin. It accepts the values FAIL (default), LOG, and SILENT and is used to control the generator's behavior on exceptions encountered during the generation process.

**Comment by lukaseder** [comment]
The newly introduced flag also needs to be applied to `AbstractDatabase`
