### ISSUE TITLE
Pre-Cache Objects returned from DSLContext.meta()

### ISSUE THREAD

**Issue by apjoseph** [jOOQ/jOOQ#6998]
Objects returned from `DSLContext.meta()` such as tables are currently connection dependent. For example, table.getPrimaryKey() performs a dynamic database query instead of returning a pre-determined value. This precludes the use of metadata objects outside of the connection initially passed to `DSLContext` which is extremely limiting if you intend to pre-cache metadata on application startup and use with multiple connections.  It would be ideal to have a `cache()` method for these classes to avoid this issue.

**Comment by lukaseder** [comment]
Caching is rather difficult, because of how it requires cache invalidation mechanisms to be set up. Each DDL statement executed through jOOQ would need to invalidate such a cache (and it's probably not possible to listen to non-jOOQ DDL changes).

Instead, perhaps you can export your meta information to XML content through [`DSLContext.informationSchema(Catalog)`](https://www.jooq.org/javadoc/latest/org/jooq/DSLContext.html#informationSchema-org.jooq.Catalog-), and then import it again many times through [`DSLContext.meta(InformationSchema)`](https://www.jooq.org/javadoc/latest/org/jooq/DSLContext.html#meta-org.jooq.util.xml.jaxb.InformationSchema-)

I think this approach will suit your requirements just as well (or even better) than a cache.

**Comment by lukaseder** [comment]
In jOOQ 3.14, we've introduced a new `Meta.snapshot()` method for this purpose: #10280
