### ISSUE TITLE
DDLDatabase uses BigDecimal instead of ULong for BIGINT UNSIGNED

### ISSUE THREAD

**Issue by anuraaga** [jOOQ/jOOQ#7024]
For a column of type BIGINT UNSIGNED, e.g. `id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,`, DDLDatabase results in generated code using `BigDecimal` while the normal MySQL code generator uses `ULong`, which is preferred since it's unsigned.

JOOQ 3.10.3

**Comment by anuraaga** [comment]
Went through my DDL and gradually whittled away until code generated and found the last few differences there, so have no more bugs to report, I think the codegen would be identical to MySQL for my schema afterwards. DDLDatabase is very exciting :)

**Comment by lukaseder** [comment]
Thanks again for all the feedback!

> DDLDatabase is very exciting :)

I'm glad to hear that! Let us know if you find any other issues.

I will look into this soon.

**Comment by lukaseder** [comment]
Thanks again for the report. I can reproduce this.

**Comment by lukaseder** [comment]
I've added a feature request to evaluate if we can simulate the DDL rather than execute it on an H2 database: #7034.

Another solution (quick fix) would be to partially simulate the DDL, trying to intercept all types like `UNSIGNED` or `ENUM` types and to programmatically generate `<forcedType/>` configurations for them.

Since this would need to be done through partial simulation, it's definitely worth thinking about going "all in" on full simulation.

**Comment by lukaseder** [comment]
I've also requested the feature at H2: https://github.com/h2database/h2database/issues/739

**Comment by lukaseder** [comment]
Closing as a duplicate of #7034
