### ISSUE TITLE
Add ResultQuery.fetchOneGroup(), fetchOptionalGroup(), fetchSingleGroup()

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#7208]
It might be useful for some users to have additional "overloads" of the `ResultQuery.fetchGroups()` and `Result.intoGroups()` functionality for cases where exactly (or at most) one group is expected. The result type would not be `Map<K, List<V>>` but `Entry<K, List<V>>`.

A `TooManyRowsException` (or a new exception) would be thrown if more than a single group is encountered.

----
See also:
https://groups.google.com/forum/#!topic/jooq-user/iGsEhmqjf7w

**Comment by lukaseder** [comment]
The cost / benefit ratio of this feature still needs to be re-assessed. These feature might be easier to compose with a set of Java 8 `Collector` types rather than built-in `fetchXYZ()` methods

**Comment by Diagoras** [comment]
@lukaseder I'm interested in working on this and even have a preliminary branch with some changes. Still, you've got a point that this _hugely_ bloats your API since we have to duplicate every `fetchGroups` method with at least three variants (one for nullable 0/1 results, one for Optional 0/1 results, and one for guaranteed single result).

You still interested in seeing that implementation? Or would custom `Collector`s provided to end users be your preference? Something like `fetchGroups(Field.FOO).collect(GroupCollectors.justOne())` or something.

**Comment by jasonab** [comment]
As the person who suggested this, I don't have a preference around the two solutions. My main goal is to avoid fake map iterations where I want the single key I know is in there.

**Comment by lukaseder** [comment]
Let's not rush this...

**Comment by lukaseder** [comment]
Closing this as a duplicate of #9288. We're going to implement more `Collector` based convenience around the collection, aggregation, and transformation of results. This will produce much better results than adding all this "convenience" API. Some convenience is definitely justified, but at some point, the various desireable combinations of API can only be achieved using a more composable set of tools, which `Collector` are perfect for.
