### ISSUE TITLE
Emulate ON DUPLICATE KEY { UPDATE | IGNORE } for PostgreSQL 9.4 and earlier

### ISSUE THREAD

**Issue by Diagoras** [jOOQ/jOOQ#7250]
### Expected behavior and actual behavior:

Expected: When using dialect POSTGRES_9_3, JOOQ will emulate an upsert query with a transactional UPDATE followed by an INSERT if no rows are updated.

Actual: JOOQ generates a 9.5+ `on conflict ("{primary_key}") do update` statement that isn't valid to use with Postgres 9.3

### Steps to reproduce the problem:

Set up a Postgres 9.3 database. Run an insert query that's configured with `onDuplicateKeyUpdate`. You should get a syntax exception.

### Versions:

- jOOQ: 3.10.5
- Java: 1.8.0_152
- Database (include vendor): Postgres 9.3
- OS: macOS Sierra, version 10.12.6
- JDBC Driver (include name if inofficial driver): Postgresql JDBC driver, version 42.2.1

**Comment by Diagoras** [comment]
This issue is similar to https://github.com/jOOQ/jOOQ/issues/2508 and https://github.com/jOOQ/jOOQ/issues/6494, FWIW.

**Comment by lukaseder** [comment]
Thanks for your report. Indeed, this could be done now, since we support the infrastructure required to run anonymous blocks in PostgreSQL: (E.g. #6474).

The block that would be generated would look like this:

```sql
DO $$
BEGIN
  UPDATE x SET b = b + 1 WHERE a = 1;

  IF (NOT FOUND) THEN
    INSERT INTO x VALUES (1, 1);
  END IF;
END; 
$$
```

This works fine until you add a `RETURNING` clause, of course. In case of which the emulation gets a bit more complicated (see: https://stackoverflow.com/a/27005650/521799).

We'll implement one step at a time. Upgrading the server would help, too, of course ;-)

**Comment by lukaseder** [comment]
I'm rejecting this. PostgreSQL 9.3 is no longer supported by PostgreSQL:
https://www.postgresql.org/support/versioning/

We're now at version 15. I understand that some derived products may be based on such old PG versions, but given that PostgreSQL 15 now even has `MERGE`, I'd rather focus on the newer versions.
