### ISSUE TITLE
When using the DDLDatabase to read schema allow setting the MODE for H2

### ISSUE THREAD

**Issue by vojtapol** [jOOQ/jOOQ#7259]
### Expected behavior and actual behavior:
My schema script is written so that it can be loaded by an H2 database with `MODE=MySQL`. I would like to be able to provide connection parameters such as `MODE` to the H2 database that is intermittently used when generating code from schema files.

Currently I can not provide any parameters except `script` and `encoding`.

### Versions:

- jOOQ: 3.10.5
- Java: 1.8
- Database (include vendor): H2 (MODE=MySQL)

**Comment by lukaseder** [comment]
Thanks for reporting. This has been brought up a few times in the past, and usually, there had been a better solution (or bug fix) for the *actual* problem. What's the reason why you'd like to be able to configure this?

**Comment by vojtapol** [comment]
My current codebase uses raw SQL with no abstraction. In test, I use H2 as an in-memory database and have to set the mode to `MySQL` so that it can accept my raw queries. I am in the process of migrating the project to jOOQ.

To allow for continuous integration and because I do not want to commit generated source code, I decided to use the DDLDatabase to generate code. My database schema is spread out over 50 files managed by Flyway. It is currently not supported to execute multiple schema scripts. So the only other choice is to use my test `schema.sql` which is made to pass into H2 with MySQL mode.

What I will probably do is that I will give up on MySQL mode completely and rewrite the test `schema.sql` to pure H2 dialect. My tests will be failing until the migration to jOOQ is done but when it's done my queries will be database-agnostic. Does this make sense?

**Comment by lukaseder** [comment]
> I do not want to commit generated source code

Why? :-)

> It is currently not supported to execute multiple schema scripts

It will be in jOOQ 3.11: https://github.com/jOOQ/jOOQ/issues/6261

> Does this make sense?

No :) The jOOQ parser can parse any dialect, including H2 and/or MySQL. It will then translate the DDL to H2 for the H2 in-memory database used to reverse engineer your incremental DDL script.

So, you don't really have to specify a MySQL mode to that H2 database. In fact, ideally, you shouldn't even know about the fact that the `DDLDatabase` uses an H2 database behind the scenes, as that might be replaced in the future.

Is there something specific that's currently not working for you?

**Comment by vojtapol** [comment]
> Why? :-)

I am trying to minimize the number of "sources of truth" in the project. If something *can* be generated from something that already is committed than I don't see a reason to also commit it.

> It will be in jOOQ 3.11: #6261

Awesome

> Is there something specific that's currently not working for you?

Yes, the script that can be loaded by H2 in MySQL mode failed. I just assumed that it's because the MySQL mode is not *fully* MySQL, it is a weird hybrid (e.g. you can't use back quotes). I would not expect jOOQ to be able to parse such a weird hybrid dialect.

In any case, I have now dropped the MySQL mode completely as I won't need it for my tests anymore. 

> that might be replaced in the future.

In that case my suggestion to support setting the `MODE` should not be implemented. Thank you for your time.

**Comment by lukaseder** [comment]
OK, thanks for following up. Please, do let us know of any parser issues that you may run into. We're very keen on fixing those!

**Comment by pabiagioli** [comment]
@lukaseder 
IMO the implementation of DDLDatabase is ok but has the caveat of H2 DB syntax compatibility.

The fact that you don't want to support the compatibility mode for H2 with MySQL raises a question about how reliable is `DDLDatabase` in the first place, unless you are planning to support parsing SQL with some kind of SQLDialect like you have in your current DSL.

I'm not sure how likely it is for a team to choose an `in-memory DB` instead of a full RDBMS server instance like Oracle, MySQL, PostgreSQL, etc, but I want to think that it's pretty much obvious.

It would be great if JOOQ's DDLDatabase supported a `SQLDialect` parameter that allowed us to choose our SQL Scripts syntax correctly before deep diving into H2 or something else.

Cheers

**Comment by lukaseder** [comment]
@pabiagioli I completely agree that there's a caveat of current H2 DB syntax compatibility. It would be much better to interpret the parsed SQL rather than run it on an existing product that has only partial support for certain DDL features.

On the other hand, interpreting also means we have to parse more SQL, so there is definitely going to be parts that are "work in progress". The `DDLDatabase` will simply *never* be as reliable as running your vendor specific DDL on your actual target RDBMS, just like it will *never* be good enough to develop and test your application on your non-target RDBMS.

The same questions would arise if we *did* pass the dialect to the H2 database as a mode. Because also H2 is limited in terms of what kinds of SQL they can parse and interpret. This limitation in the third party library is one of the reasons I'm really not too keen to support this third party feature officially.

If this is critical to your team, then don't use the `DDLDatabase`. It has been designed with an 80/20 mindset where DDL is relatively vendor agnostic.

So, while there will be a parameter to specify the `DDLDatabase` input dialect (because the jOOQ parser will need it to make some parsing decisions), it will not necessarily be used to pass to H2, as we're not willing to support and integration test H2's various "modes", given that the ultimate solution to `DDLDatabase` problems is interpretation of parsed DDL, not passing the translated DDL to some undisclosed in-memory database.

Having said so, most of the logic resides in the parser. The `DDLDatabase` is only a few lines of code. You can copy it and implement your own very easily.
