### ISSUE TITLE
Support Kotlin metadata in DefaultRecordMapper

### ISSUE THREAD

**Issue by vojtapol** [jOOQ/jOOQ#7324]
Currently, `DefaultRecordMapper` supports many different mapping strategies including `@ConstructionProperties`. 

In Kotlin, it is common to define immutable data classes like so:

```kotlin
data class Person(val name: String, val age: Int)
```

This, when compiled, generates something that would be represented in Java like so:
```java
@Metadata(
   // note how property names are stored as metadata and can be accessed at runtime
   d2 = {"vojtapol/packing/Person;", "", "name", "", "age", "", "(Ljava/lang/String;I)V", "getAge", "()I", "getName", "()Ljava/lang/String;", "component1", "component2", "copy", "equals", "", "other", "hashCode", "toString", "production sources for module packing"}
)
public final class Person {
   @NotNull
   private final String name;
   private final int age;

   @NotNull
   public final String getName() {
      return this.name;
   }

   public final int getAge() {
      return this.age;
   }

   public Person(@NotNull String name, int age) {
      Intrinsics.checkParameterIsNotNull(name, "name");
      super();
      this.name = name;
      this.age = age;
   }

   // ommitted some convenience methods
}
```

As you know, when we tell `DefaultRecordMapper` to map a record into `Person` it will use the constructor and map it if the number of parameters in the constructor exactly matches the record. This is not ideal as it is very error-prone. If the parameters are all the same type and their order is altered (or the database column order is altered) the mapper will map the type incorrectly and no warning is logged. 

To mitigate this I propose leveraging Kotlin's `@Metadata` to match parameter names. Similarly to what is currently done with `@ConstructorProperties`. This would make using jOOQ from Kotlin's data classes seamless and no annotations would be required.

From Java, this could be done using the `kotlin-reflect` library like so:

```java
Person p = new Person("vojtapol", 4);
Class<? extends Person> type = p.getClass();
KClass<? extends Person> kotlinClass = JvmClassMappingKt.getKotlinClass(type);
Collection<? extends KProperty1<? extends Person, ?>> properties = KClasses.getDeclaredMemberProperties(kotlinClass);
```

Where `properties` now contain a list of a person's properties including their names.

I would be willing to help out or contribute via PR if necessary.

**Comment by lukaseder** [comment]
Thank you very much for your suggestion. From what I can tell, this `Metadata` annotation isn't documented (https://stackoverflow.com/q/36816521/521799), so we shouldn't read it directly. Meta-
reflecting on `kotlin-reflect` might indeed be a solution, but do note that jOOQ 3.11 will support JDK 8 parameter reflection to use parameter name meta data if it is present: #4627.

Does this suffice, in your case?

Otherwise, a PR that reflects on the `kotlin-reflect` API is certainly very welcome.

**Comment by vojtapol** [comment]
Thanks, Lukas.

Metadata are stored as protobuf encoded blobs which is undocumented but the reflection API is all you need and that is documented and supported just like Kotlin's stdlib. See here:
https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.reflect.full/declared-member-properties.html

Although JDK 8 parameter reflection would indeed solve this I think it would be nice to have a separate solution for Kotlin for those who do not enable the `-parameters` compiler flag.

I will work on a PR and we can discuss the solution.

**Comment by lukaseder** [comment]
@stangls : Thank you for your message. Would you mind creating a new issue, perhaps with an example to help reproduce the problem?

**Comment by lukaseder** [comment]
Reviewing this in the context of #10194. The current implementation does not work if a Kotlin (data) class has defaulted parameters:

```kotlin
data class T(
      val i: Int? = null
    , val j: String? = null
)
```

This is because the byte code for the above data class contains a default constructor. I'm not sure why it is needed, perhaps as a call site performance / byte code optimisation when no arguments are passed?

In any case, the `DefaultRecordMapper` assumption that the presence of the no-args constructor implies mutability is wrong.

**Comment by pschichtel** [comment]
This seems to cause issues, when field names and constructor parameter names in kotlin classes do not align. We just hit an issue, where jOOQ was able to map a Record12, which doesn't have aliases for all fields, to an immutable Java POJO, but was not able to do the same with a basically equivalent kotlin data class. We are working a lot with custom types, so the "parameters are all the same type and their order is altered" problem is already mitigate in our codebase for the most part.

**Comment by lukaseder** [comment]
@pschichtel Thanks for your message. Makes sense, both index based and name based mapping algorithms have their pros and cons. I believe that the majority of Kotlin users will prefer the name based one, which is why I think this is a good default. You can turn off this feature using `Settings.mapConstructorParameterNamesInKotlin`, by the way.

But it might also make sense to allow custom composition of the built in record mappers, to pick only the functionality you desire, and register that as a `Configuration.recordMapperProvider()`. I've created a feature request for this, to make the existing implementations public for reuse: https://github.com/jOOQ/jOOQ/issues/10348

**Comment by pschichtel** [comment]
> You can turn off this feature using `Settings.mapConstructorParameterNamesInKotlin`, by the way.

Thanks for that hint and the great follow-up.
