### ISSUE TITLE
Suggestion: change DataAccessException to a checked Exception, not a RuntimeException

### ISSUE THREAD

**Issue by ryanwa** [jOOQ/jOOQ#7366]
### Expected behavior and actual behavior:
org.jooq.DataAccessException inherits from Runtime Exception. This is an unchecked exception. However, one can reasonably expect the caller to handle these types of exception.

I propose that DataAccessException be a checked exception, based on the following guidance from Oracle: https://docs.oracle.com/javase/tutorial/essential/exceptions/runtime.html

> Here's the bottom line guideline: If a client can reasonably be expected to recover from an exception, make it a checked exception. If a client cannot do anything to recover from the exception, make it an unchecked exception.

I believe DataAccessException can be recoverable, and thus falls into the first category. 

### Steps to reproduce the problem:
Design suggestion.

### Versions:

- jOOQ: 3.10.0
- Java: 1.8
- Database (include vendor): MySQL
- OS: Linux
- JDBC Driver (include name if inofficial driver): mysql-connector-java

**Comment by lukaseder** [comment]
Thank you for your very interesting suggestion. I would not have expected anyone to prefer checked exceptions for these things anymore, these days :-)

While some database exceptions are indeed recoverable and might be suitable candidates for checked exceptions (e.g. constraint violations), most people in the Java community will agree that checked exceptions have been a mistake.

One of the main reasons for throwing `DataAccessException` instead of passing on the (mostly) underlying `SQLException` is precisely the fact that we do not want to throw any checked exception.

While YMMV, we're definitely not going to implement this change.

**Comment by brunoborges** [comment]
But I want to try/catch my exceptions!! :P

**Comment by jbaruch** [comment]
@brunoborges well, you're out of luck. Everyone knows there is no way to catch an unchecked exception. That's why it's called "unchecked".

**Comment by brunoborges** [comment]
Damn it... I need to update my Sun Certified Java Programmer for Java SE 11

**Comment by lukaseder** [comment]
Disregarding the two trolls above ;-) ... I will revise my opinion on unchecked exceptions a bit, at least the part where I claimed that "most people in the Java community" agree on the topic. A quick and somewhat representative poll proved otherwise:
https://twitter.com/lukaseder/status/979788483429568517

Nevertheless, the JDK and other libraries are moving away from checked exceptions. In my opinion, still rightfully so. We cannot re-introduce them to jOOQ, if maybe not for general agreement on their usefulness, then definitely not for backwards compatibility reasons. Making `DataAccessException` checked would break every single line of jOOQ user code out there.
