### ISSUE TITLE
Inlining queries return by JOOQ with trailing slash throw parsing exception due to escaping

### ISSUE THREAD

**Issue by venks61176** [jOOQ/jOOQ#7448]
### Expected behavior and actual behavior:

We are using CrateDB which uses Postgres protocol/dialcet but conflict keywords for upserts are 
similar to Mysql.
So we are using JOOQ as query builder and trying to render the query after modifying clause keywords to resemble mysql.

```java
String query = ctx
   .update(AUTHOR)
   .set(author)
   .where(AUTHOR.ID.eq(author.getId()))
   .getSQL(ParamType.INLINED);
we run the same query with JOOQ
ctx.batch(sql).execute();
```

Now the query execution will fail, if the author name is set with trailing slash

```venkit@test.com$\\$$'`\```

Directly using record.update() it will succeed. But we need to modify the query for upserts 
before using them.  The prepared statement cannot be used in this case as the values are different for incoming list.

### Steps to reproduce the problem:
1) construct a query with \  at the end for one of the values
2) get string and execute it on JOOQ Context
3) The problem goes away if we use JDBC statement with setEscaping(false)

```
update "ven"."author" set "name" = 'venkit@test.com$\\$$''`\' where "ven"."author"."id" = 1275200111
java.lang.ArrayIndexOutOfBoundsException
        at org.jooq_3.10.6.POSTGRES_9_5.debug(Unknown Source)
        at java.lang.System.arraycopy(Native Method)
        at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:597)
        at java.lang.StringBuilder.append(StringBuilder.java:190)
        at io.crate.shade.org.postgresql.core.Parser.parseSql(Parser.java:1029)
        at io.crate.shade.org.postgresql.core.Parser.replaceProcessing(Parser.java:975)
        at io.crate.shade.org.postgresql.core.CachedQueryCreateAction.create(CachedQueryCreateAction.java:44
```

It happens with both Crate and Postgres driver. 
### Versions:

- jOOQ:3.10.6
- Java:1.8
- Database (include vendor):Crate DB and Postgress
- OS:Mac and Linux
- JDBC Driver (include name if inofficial driver):Postgres driver and Crate driver

```xml
    <dependency>
      <groupId>org.postgresql</groupId>
      <artifactId>postgresql</artifactId>
      <version>42.2.2</version>
    </dependency>

  <dependency>
    <groupId>io.crate</groupId>
    <artifactId>crate-jdbc</artifactId>
    <version>2.3.0</version>
  </dependency>
```

**Comment by lukaseder** [comment]
Thanks for your report. This script works fine for me on PostgreSQL JDBC:

```java
try (Connection cn = new org.postgresql.Driver().connect(url, properties);
     Statement s = cn.createStatement()) {

    s.execute("DROP TABLE IF EXISTS x");
    s.execute("CREATE TABLE x (v text)");
    s.execute("INSERT INTO x DEFAULT VALUES");
    s.execute("UPDATE x SET v = 'venkit@test.com$\\\\$$''`\\'");
    try (ResultSet rs = s.executeQuery("SELECT * FROM x")) {
        while (rs.next())
            System.out.println(rs.getString(1));
    }
    s.execute("DROP TABLE IF EXISTS x");
}
```

Note:

1. We don't support crate io
2. Their JDBC driver `io.crate:crate-jdbc:2.3.0` is not available from Maven Central, so I won't be able to verify this easily
3. There may be databases out there who thought it was a good idea to support non-standard escape sequences inside of standard SQL string literals. It is never a good idea for precisely this reason. Few tools out there are ready for backslash escaped sequences inside of string literals. jOOQ can handle it (mainly for MySQL), by specifying the `Settings.backslashEscaping` flag, but beware that this is really not a good idea - especially in PostgreSQL, which doesn't recognised backslash escaped sequences. The best idea is to turn off this feature in Crate IO, or even to request they remove the feature entirely because it's such a bad idea!
