### ISSUE TITLE
When I use Jooq Entreprise with Sybase ASE it's detect my as Sybase SQL Anywhere

### ISSUE THREAD

**Issue by pom75** [jOOQ/jOOQ#7566]
### Expected behavior and actual behavior:
When I use Jooq with Sybase ASE it's detect my as Sybase SQL Anywhere

### Steps to reproduce the problem (include example code if possible):
Use Jooq for Sybase ASE with jConnect driver

There is 2 driver for Sybase ASE : jTDS JDBC Driver ( :jtds:sybase:) and jConnect for JDBC (:sybase:Tds:)
jConnect support is missing in "**jOOQ/src/main/java/org/jooq/tools/jdbc/JDBCUtils.java**"

### Versions:

- jOOQ: 3.11.0 Entreprise
- Java: 1.8.0_131
- Database (include vendor): Sybase ASE
- OS: Windows 7
- JDBC Driver (include name if inofficial driver): 

```
<dependency>
                <groupId>sybase</groupId>
                <artifactId>jconn4</artifactId>
                <version>7.07.21018</version>
            </dependency>
```
### How to fix it :
**jOOQ/src/main/java/org/jooq/tools/jdbc/JDBCUtils.java*
```
 if (url.contains(":jtds:sybase:") || url.contains(":sybase:Tds:") {
                        return SQLDialect.ASE;
```

**Comment by lukaseder** [comment]
jOOQ supports both Sybase flavours: ASE and SQL Anywhere. Unfortunately, the less used SQL Anywhere support was added first, to jOOQ, which is why it is being prioritised in the JDBC / SQL dialect detection. For backwards compatibility reasons, we cannot fix this easily anymore.

For best results, it's always a good idea to explicitly configure the `SQLDialect` in your `Configuration`, e.g. by using `DSL.using(connection, dialect, settings)`

Your suggested improvement of adding support for recognising the `:sybase:Tds:` substring was implemented here: https://github.com/jOOQ/jOOQ/issues/7560
