### ISSUE TITLE
Binary incompatibility between 3.10.0 and 3.11.0 when using "limit"

### ISSUE THREAD

**Issue by victorbr** [jOOQ/jOOQ#7590]
An SQL using `limit` compiled vs. JOOQ 3.10, fails at runtime when run with JOOQ 3.11 with exception
```
java.lang.NoSuchMethodError: org.jooq.SelectConditionStep.limit(I)Lorg/jooq/SelectWithTiesStep;
```
a pseudo code of the SQL in question:
```
dslContext.select(field).from(table).where(condition).limit(5).fetch(mapper);
```
There's no direct usage of `SelectWithTiesStep` interface in the code but the compiled code contains the reference.

Disclaimer - I'm not sure what the binary compatibility promise of jOOQ is so perhaps it's not considered a problem but since it's a rather basic API, people might easily bump into this.

**Comment by lukaseder** [comment]
Thank you very much for your report. jOOQ's stance on backwards compatibility is located here, in the manual:
https://www.jooq.org/doc/latest/manual/getting-started/semantic-versioning

I have just updated it to make sure the part about binary compatibility is made explicit. The DSL is impossible to maintain binary compatible between minor releases. If binary compatibility would be important, it would be very difficult to evolve the DSL. This is due to the nature of how it is implemented:
https://blog.jooq.org/2012/01/05/the-java-fluent-api-designer-crash-course

The particular problem you ran into is especially hard to avoid, because while the JVM allows overloading by method return type (since Java 5), the Java language does not - so, without writing a custom compiler, it wouldn't be possible to maintain the "old" overload of a new covariant return type.

Much more important than binary compatibility is source compatibility, which jOOQ minor releases try to guarantee as much as possible.

I hope this helps
