### ISSUE TITLE
Print row count in LoggerListener for ResultQuery

### ISSUE THREAD

**Issue by arlampin** [jOOQ/jOOQ#7599]
### Expected behavior and actual behavior:
When using e.g LoggerListener or manual `toString()` call on Result, it used to print out something like
`...123 record(s) truncated...`, but in 3.11.x it prints just `...record(s) truncated...`

I believe this was caused by commit ea2da23dac3a50738b47eb01777566b3fd4d0811

### Steps to reproduce the problem (include example code if possible):
Print out Result with some number of rows

### Versions:
- jOOQ: 3.11.1
- Java:
- Database (include vendor):
- OS:
- JDBC Driver (include name if inofficial driver):

**Comment by lukaseder** [comment]
Thanks for your report. Yes indeed, that change was intentional, as the previous behaviour requires knowing the exact size of a `Formattable` subtype. The size is known in `Result`, but not in `Cursor`, and fetching all the rows just to display the size seems excessive.

You have filed this as a bug. What is your expectation towards this removed feature? Do you rely on it?

**Comment by lukaseder** [comment]
OK, I see. I'll check if there is another way to log this information through a different mechanism. The `LoggerListener` has the `size()` information (as opposed to the `Formattable` type), so it can perhaps print another line, just like when an update count is displayed

**Comment by lukaseder** [comment]
Fixed for jOOQ 3.12. Will backport to 3.11.2 through #7604, as this could be seen as a regression for use-cases like yours.
