### ISSUE TITLE
Postgres: incorrect SQL produced for null value if field is constructed by name

### ISSUE THREAD

**Issue by vstepchik** [jOOQ/jOOQ#7670]
### Expected behavior and actual behavior:
I've written a method in abstract DAO class that allows checking if an entity exists by passing a vararg of Kotlin's `Pair<String, Any?>` values that are used to form the `WHERE` clause, and I've found that if I pass `null` as the value, jOOQ produces incorrect query.

```
org.springframework.jdbc.BadSqlGrammarException: jOOQ; bad SQL grammar [select 1 as "one" where exists (select 1 as "one" from "main_schema"."sample" where "uuid_field" = cast(? as varchar))]; nested exception is org.postgresql.util.PSQLException: ERROR: operator does not exist: uuid = character varying
  Hint: No operator matches the given name and argument type(s). You might need to add explicit type casts.
  Position: 98
```

### Steps to reproduce the problem (include example code if possible):
Here's a sample schema:
```sql
CREATE TABLE IF NOT EXISTS ${SCHEMA}.sample (
  id uuid NOT NULL PRIMARY KEY,
  uuid_field uuid
);
```

The code that works:
```kotlin
fun execute() {
    val nullUuid: UUID? = null

    dsl.fetchExists(
        Sample.SAMPLE, Sample.SAMPLE.UUID_FIELD.eq(nullUuid)
    )
}
```

The code that fails:
```kotlin
import org.jooq.impl.DSL.field
import org.jooq.impl.DSL.name
...
fun execute() {
    val nullUuid: UUID? = null

    dsl.fetchExists(
        Sample.SAMPLE, field(name(Sample.SAMPLE.UUID_FIELD.name)).eq(nullUuid)
    )
}
```

### Versions:

- jOOQ: `3.11.2`
- Java: `openjdk 10.0.1 2018-04-17`
- Database (include vendor): `Postgres 10.2`
- OS: `Linux 4.17.5-1-ARCH #1 SMP PREEMPT Sun Jul 8 17:27:31 UTC 2018`
- JDBC Driver (include name if inofficial driver): `postgresql-42.2.2.jar`

**Comment by lukaseder** [comment]
Thank you very much for your report. I don't think jOOQ can do much here. The generic types have been erased at runtime, and you don't provide any type information at all in the plain SQL example, so jOOQ has to "guess" the type of your `null` literal. It cannot *know* that it is a `UUID`. In the first case, it knew because the code generator added the type information to the column reference. You can do, too, of course. E.g. by writing:

```kotlin
field(name(Sample.SAMPLE.UUID_FIELD.name), SQLDataType.UUID).eq(nullUuid)
```

In any case, nothing is ever equal to `null` in SQL, so your query doesn't really do what you probably intend for it to do. You should use `Field.isNull()` instead.
