### ISSUE TITLE
Add convenience methods "getString", "getInt", "getLong" to Record

### ISSUE THREAD

**Issue by grzegorzbor** [jOOQ/jOOQ#7683]
Jdbc's ResultSet has methods getString(colName/index), getInt() etc.

I would expect someting similar from jooq's Record, so that I could write it like:
record.getString("username")
but instead I have to write the long version:
record.get("username", String.class)

Having to type this long-form every time, for every single column in every single query, is frustrating, takes time, and makes code less readable, and is a step back compared to the plain JDBC.
This could be safely added as a default method on the Record interface, so it seems to be a small cost for a framework, because it has no side effects, no dependencies etc; but makes the API much more user friendly. 

I assume, String + Boolean + Integer + Long cover 90% of columns used in practice. Hence, adding four methods: getString, getBool, getInt, getLong would cover most of the cases needed. For all others least-freqently used (Dates, Floats, Bytes, custom types etc) you would still use the long form.

Additionally, I'd love to have another shortcut method: the no-argument get() method, which can be used when query returned exactly one column (and throw exception otherwise). This could be used like this:

int sum = dsl.resultQuery("select sum(spending) from users").fetchOne().getInt();

This could also be implemented as a default method on Record. Basically, it's a shortcut for get(0), but has an advantage that users don't have to think if the index is 0-based or 1-based.

**Comment by lukaseder** [comment]
Thank you very much for your suggestion. There are, in fact, two suggestions in your issue. Let's discuss them separately:

### Adding JDBC style getters to `Record` and `Result`

You mentioned only `Record`, but for consistency reasons, those methods would need to be added to `Result` as well.

If you've followed the recent mails on the [jdbc-spec-discuss](http://mail.openjdk.java.net/pipermail/jdbc-spec-discuss/) mailing list, you might have seen that the big choice of JDBC `ResultSet` methods (as well as `PreparedStatement`, `CallableStatement`, `SQLinput`, `SQLOutput` methods) is generally seen as a maintenance burden for everyone:

- Spec maintainers
- Driver implementors
- Users

The tendency is towards using `Class` references, such as in JDBC 4.2 when support for `java.time` types was added to the PDF spec and the Javadoc, but not really to the `ResultSet` and other APIs through new methods. There are also a variety of other types like `UUID` which are supported by some drivers, but not in the API.

You say:

> I assume, String + Boolean + Integer + Long cover 90% of columns used in practice

But this very assumption is the key flaw in your suggestion, as it is very likely going to be wrong. If we indeed do add these new methods, someone will come along and claim that `Double` is also an important type. Someone else will then like to see `Float` support. Someone else will then like to see an `Integer` / `int` distinction for convenience. And I really don't see why you're assuming that dates aren't going to be in that list of mostly-used-columns. And speaking of dates, would you prefer `java.sql.Date`, `java.util.Date`, `java.util.Calendar`, or `java.time.LocalDate`? :-)

> Having to type this long-form every time, for every single column in every single query, is frustrating, takes time, and makes code less readable, and is a step back compared to the plain JDBC

A step forward would be to start using the code generator. The main use case of using jOOQ is indeed using the code generator where you do not only have the column name generated and type checked, you will also get type information associated with each column automatically, and will never worry about this again.

So, it's really hard to see the advantage of adding such methods, given that:

- It's tons of work to maintain
- It's of limited utility to most users
- It will be incomplete, because someone will come along and ask for support for additional types

### Adding a no-argument `get()` method

You can achieve this by calling `Record.into(Class)`, such as `fetchOne().into(int.class)`. The `DefaultRecordMapper` already supports this use-case.

The arguments why I wouldn't want to see your suggestion added to the API are the same as the previous ones.
