### ISSUE TITLE
OFFSET .. FETCH should not be emulated in Oracle 18c anymore even when projection has duplicate column names

### ISSUE THREAD

**Issue by PhilippSalvisberg** [jOOQ/jOOQ#7721]
#### actual
row_limiting_clause is not used, when column names are not unique
Note: the query result is correct, hence this is not a bug more an enhancement request

#### expected
row_limiting_clause is used, even if column names are not unique (in the outer query block)

#### 1. Environment
according https://www.salvis.com/blog/2018/08/05/view-api-jooq-application/

#### 2. Test case (NOT OK)

```java
@Test
public void duplicateColumnJobId() {
    final ResultQuery<?> query = ctx
            .select(EMPLOYEES_V.EMPLOYEE_ID,
                  EMPLOYEES_V.JOB_ID,
                  JOBS_V.JOB_ID,
                  JOBS_V.JOB_TITLE)
            .from(EMPLOYEES_V)
            .join(JOBS_V).onKey()
            .orderBy(EMPLOYEES_V.SALARY)
            .limit(inline(4)).withTies();
       logger.info("--- duplicateColumnJobId (emulated top n) ---" + "\n\n" + query.getSQL() + "\n");
}
```

Output:

```sql
411  INFO  LimitTest          - --- duplicateColumnJobId (emulated top n) ---

select 
  "v0" "EMPLOYEE_ID", 
  "v1" "JOB_ID", 
  "v2" "JOB_ID", 
  "v3" "JOB_TITLE"
from (
  select 
    "HR"."EMPLOYEES_V"."EMPLOYEE_ID" "v0", 
    "HR"."EMPLOYEES_V"."JOB_ID" "v1", 
    "HR"."JOBS_V"."JOB_ID" "v2", 
    "HR"."JOBS_V"."JOB_TITLE" "v3", 
    rank() over (order by "HR"."EMPLOYEES_V"."SALARY") "rn"
  from "HR"."EMPLOYEES_V"
    join "HR"."JOBS_V"
    on "HR"."EMPLOYEES_V"."JOB_ID" = "HR"."JOBS_V"."JOB_ID"
  order by "HR"."EMPLOYEES_V"."SALARY"
) "x"
where "rn" > 0
and "rn" <= (0 + 4)
order by "rn"
```

#### 3. Test case (OK)

```java
@Test
public void uniqueColumnNames() {
    final ResultQuery<?> query = ctx
            .select(EMPLOYEES_V.EMPLOYEE_ID,
                  EMPLOYEES_V.JOB_ID,
                  JOBS_V.JOB_ID.as("jobs_job_id"),
                  JOBS_V.JOB_TITLE)
            .from(EMPLOYEES_V)
            .join(JOBS_V).onKey()
            .orderBy(EMPLOYEES_V.SALARY)
            .limit(inline(4)).withTies();
      logger.info("--- uniqueColumnNames (native top n) --- \n\n" + query.getSQL() + "\n");
}
```

Output

```sql
397  INFO  LimitTest          - --- uniqueColumnNames (native top n) --- 

select 
  "HR"."EMPLOYEES_V"."EMPLOYEE_ID", 
  "HR"."EMPLOYEES_V"."JOB_ID", 
  "HR"."JOBS_V"."JOB_ID" "jobs_job_id", 
  "HR"."JOBS_V"."JOB_TITLE"
from "HR"."EMPLOYEES_V"
  join "HR"."JOBS_V"
  on "HR"."EMPLOYEES_V"."JOB_ID" = "HR"."JOBS_V"."JOB_ID"
order by "HR"."EMPLOYEES_V"."SALARY"
fetch next 4 rows with ties
```

### Versions:

- jOOQ: 3.11.3
- Java: 1.8.0_161
- Database (include vendor): Oracle Database 18.3.0.0.180717 Enterprise Edition
- OS: macOS 10.13.6 (client), Oracle Linux 7.5 (server)
- JDBC Driver (include name if inofficial driver): ojdbc8.jar

**Comment by PhilippSalvisberg** [comment]
I do understand the limitation regarding ambiguous column names. I still do not understand why the workaround needs a subquery, when something like this is working as well:

```
  select 
    "HR"."EMPLOYEES_V"."EMPLOYEE_ID" "v0", 
    "HR"."EMPLOYEES_V"."JOB_ID" "v1", 
    "HR"."JOBS_V"."JOB_ID" "v2", 
    "HR"."JOBS_V"."JOB_TITLE" "v3"
  from "HR"."EMPLOYEES_V"
    join "HR"."JOBS_V"
    on "HR"."EMPLOYEES_V"."JOB_ID" = "HR"."JOBS_V"."JOB_ID"
  order by "HR"."EMPLOYEES_V"."SALARY"
  fetch next 4 rows with ties
```

You could even decide to just assign an alias to the ambiguous columns only. And since it's not part of a subquery anymore, there is no need to aliasing the columns anymore in 18.3 (but aliasing is required for in 12.1). However, it works also the way it is. It just causes some minor confusion IMHO.

BTW it was not me intention to exclude the `SALARY` column from the result list in the first place.

**Comment by lukaseder** [comment]
This would not produce the same result as the currently generated jOOQ query. Your assumption is that the result set would be consumed by jOOQ, but it could also be consumed by some other tool, which wouldn't know what `v0` - `v3` mean. A very common use case with jOOQ is that jOOQ is used as a SQL builder only, and then using `Query.getSQL()` and `Query.getBindValues()`, people extract the SQL string and bind values in order to execute them e.g. with JDBC directly. I think you did something similar in your article. It would be very bad if such a query would produce random column names. The expectation is clearly to have duplicate `JOB_ID` column names, and this is currently not supported by Oracle. It is supported by most other databases.

> And since it's not part of a subquery anymore, there is no need to aliasing the columns anymore in 18.3

18.1 still has this limitation: https://docs.oracle.com/en/database/oracle/oracle-database/18/sqlrf/SELECT.html#GUID-CFA006CA-6FF1-4972-821E-6996142A51C6

How do I get to the 18.3 documentation?

> It just causes some minor confusion IMHO.

Sure, there's a lot of history in jOOQ's internals... There are many edge cases that need to be worked around by generating some emulation which guarantees correctness. This is crucial especially when running the same query on different database products.

There's a pending feature request to annotate the generated SQL with comments explaining each individual emulation: https://github.com/jOOQ/jOOQ/issues/7372. It's not a high priority, given how much work it would be to implement...

**Comment by PhilippSalvisberg** [comment]
> This would not produce the same result as the currently generated jOOQ query. (...)

Yes, you're right. I haven't seen that JOOQ sets the original columns in the outer query... :-(

> How do I get to the 18.3 documentation?

There is no 18.3 documentation. The latest 18c [documentation](https://docs.oracle.com/en/database/oracle/oracle-database/index.html)  should be in sync with the latest RU (I probably should open a SR). 

I tested the following query as HR user:

```
select 
    "HR"."EMPLOYEES"."EMPLOYEE_ID", 
    "HR"."EMPLOYEES"."JOB_ID", 
    "HR"."JOBS"."JOB_ID", 
    "HR"."JOBS"."JOB_TITLE"
  from "HR"."EMPLOYEES"
    join "HR"."JOBS"
    on "HR"."EMPLOYEES"."JOB_ID" = "HR"."JOBS"."JOB_ID"
  order by "HR"."EMPLOYEES"."SALARY"
  fetch next 4 rows with ties
```

The query fails on 12.1.0.2.180717 with `ORA-00918: column ambiguously defined`.

But works on 12.2.0.1.180717 and 18.3.0.0.180717. Hence, the 12.2 documentation is also wrong.

> It just causes some minor confusion IMHO.

My fault. I simply did not understood the reason for the subquery. Now I do. No confusion anymore. :-)

Thanks, Lukas.

**Comment by lukaseder** [comment]
Thanks a lot for your research and for offering to issue an SR. Indeed, I just tried it (should've done before), and it does work on newer releases. I'll think about it - probably a new `SQLDialect` should be introduced after `ORACLE12C`, which updates the behaviour to the latest version. It's definitely better not to have those derived tables - not only from a readability perspective, but also because there is a second `ORDER BY` clause in the derived table version.

**Comment by lukaseder** [comment]
I'll try to fix this for `SQLDialect.ORACLE18C` and newer dialects
