### ISSUE TITLE
LoggerListener::logMultiline could have protected visibility

### ISSUE THREAD

**Issue by jameshiew** [jOOQ/jOOQ#7845]
### Expected behavior and actual behavior:
Expected:
Inheriting from `LoggerListener` and wanting to override or call certain methods like `logMultiline`

Actual:
`LoggerListener::logMultiline` is `private` rather than `protected`

### Steps to reproduce the problem (include example code if possible):
You have to do things like this in the subclass
```
    @Override
    public void recordEnd(ExecuteContext ctx) {
        if (log.isTraceEnabled() && ctx.record() != null)
            logMultiline("Record fetched", ctx.record().toString(), Level.FINER);
    }

    private void logMultiline(String comment, String message, Level level) {
        ...
    }
```
i.e. copy and paste the whole of `recordEnd` so that it calls your new `logMultiline` method, rather than just being able to `@Override` `logMultiline`.

### Versions:

- jOOQ: 3.11.4
- Java: 10
- Database (include vendor): Postgres
- OS: Ubuntu
- JDBC Driver (include name if inofficial driver):

**Comment by lukaseder** [comment]
Thank you very much for your suggestion.

We have a lot of private / package private methods, just as well as we have a lot of final methods. There's a very good reason for this: Encapsulating implementation allows for keeping the jOOQ API exposure to clients relatively small, and thus jOOQ will be much more maintainable.

What happens if this (granted, seemingly useful) method would be opened up to subclasses? People would start relying on it, and we'd have to maintain it with much more care, and backwards compatibly.

For you, your immediate itch would be scratched (i.e. "just this once"), but many other users would like to have similar things opened up. Ultimately, this would kill maintainability of jOOQ.

A more elaborate explanation of the strategy behind this can be found here:
https://blog.jooq.org/2017/03/20/the-open-closed-principle-is-often-not-what-you-think-it-is/

This is why I have to decline your request. Thanks for your understanding.

**Comment by jameshiew** [comment]
Totally understand, thank you for taking the time to respond and developing this package!
