### ISSUE TITLE
CREATE INDEX IF NOT EXISTS should intercept error code 1913 in SQL Server

### ISSUE THREAD

**Issue by benjamin-lang** [jOOQ/jOOQ#7961]
### Expected behavior and actual behavior:
Precondition:
* index is already existing

Expected:
*  do nothing because index is already existing

Actual:
* sql error while trying to create an existing index

* org.springframework.jdbc.UncategorizedSQLException: jOOQ; uncategorized SQLException for SQL [begin try create index [INDEX_SYNCCREATION_PRIMARYKEY] on [synccreation]([type], [finoffid], [parenttype], [parentfinoffid], [landskapeid]) end try begin catch if error_number() != 2714 throw; end catch]; SQL state [S0001]; error code [1913]; Fehler bei dem Vorgang, weil ein Index oder eine Statistik mit dem Namen "INDEX_SYNCCREATION_PRIMARYKEY" für "synccreation" (Tabelle) bereits vorhanden ist.; nested exception is com.microsoft.sqlserver.jdbc.SQLServerException: Fehler bei dem Vorgang, weil ein Index oder eine Statistik mit dem Namen "INDEX_SYNCCREATION_PRIMARYKEY" für "synccreation" (Tabelle) bereits vorhanden ist.
	at org.jooq_3.11.5.SQLSERVER.debug(Unknown Source) ~[?:?]

* The operation failed because an index or statistics with name 'INDEX_NAME' already exists on table 

### Steps to reproduce the problem (include example code if possible):

Used dslContext.createIndexIfNotExists("INDEX_NAME"), with jooq version 3.9.5 same code did work.

### Versions:

- jOOQ: 3.11.5
- Java: 1.8.0_121
- Database (include vendor):
Microsoft SQL Server 2016 (SP1) (KB3182545) - 13.0.4001.0 (X64) 
	Oct 28 2016 18:17:30 
	Copyright (c) Microsoft Corporation
	Developer Edition (64-bit) on Windows Server 2016 Standard 6.3 <X64> (Build 14393: ) (Hypervisor)
- OS: Windows
- JDBC Driver (include name if inofficial driver):
  <dependency>
      <groupId>com.microsoft.sqlserver</groupId>
      <artifactId>mssql-jdbc</artifactId>
      <version>7.0.0.jre8</version>
    </dependency>

Best Regards
Benjamin

**Comment by lukaseder** [comment]
Thanks a lot for your report. I will try to reproduce this and will get back to this issue ASAP

**Comment by lukaseder** [comment]
Thanks again. I can reproduce this problem. Will investigate under which circumstances it fails and under which circumstances it works.

**Comment by lukaseder** [comment]
Hmm, I'm surprised it worked before with the old jOOQ version. There had been a refactoring but I don't think the behaviour changed substantially. In both versions, we're checking for `error_number() = 2714`, which is the generic error number for *"There is already an object named '%.*ls' in the database."*

See:
https://docs.microsoft.com/en-us/sql/relational-databases/errors-events/database-engine-events-and-errors?view=sql-server-2017

However, there seems to have been a change in behaviour in SQL Server, which I cannot fully track down to an individual difference. I'm now getting error code `1913` on SQL Server 2017. That code corresponds to *"The operation failed because an index or statistics with name '%.*ls' already exists on %S_MSG '%.*ls'."*, but it was there already in SQL Server 2008.

So, I'm not 100% sure if it's a regression. We'll simply catch both error codes, as we do with other statements as well.

**Comment by lukaseder** [comment]
Fixed for jOOQ 3.12. Backports scheduled for 3.11.6 (#7978) and 3.10.9 (#7979)

**Comment by benjamin-lang** [comment]
Thx for the fast feedback and fix  :-)
