### ISSUE TITLE
Oracle Editioning Views are not recognised

### ISSUE THREAD

**Issue by batousik** [jOOQ/jOOQ#7963]
### Expected behavior and actual behavior:

Generate POJOs using existing database connection get 1 view and 1 table. Actual: 2 tables

### Steps to reproduce the problem (include example code if possible):

Start an oracle db, create a table and an Editioning view, run pojo generator, results in two table classes, not a table and a view class

### Versions:

- jOOQ: 3.11.5
- Java: 1.8
- Database (include vendor): Oracle 11.2.0.4.0
- OS: win 7
- JDBC Driver (include name if inofficial driver): com.oracle.ojdbc6:11.2.0.3

**Comment by batousik** [comment]
eg. my current task is to select all tables (not views) where column names match specific regex (and there are views with matching columns) and then update those columns. MYSCHEMA.getTables returns tables+views and I cannot filter out tables. Maybe an object type inside Table class could be a small feature to implement.

What I will do is generate SYS and MYSCHEMA POJOs and then do my select using jOOQ to select required tables.

If this use case is not enough to start development of such "heavy" feature, I guess you should gather more feedback whether people using your product would like to have more freedom working with views etc. 

My opinion is biased since I am an Oracle PL/SQL dev and know little of other dialects.

On the second thoughts you can update parts of your documentation clearly stating that your product and specifically pojo generator doesn't distinguish between object types, since I have personally spent this morning trying to figure out why I cannot generate the View's pojos

Regards,
Bato

**Comment by lukaseder** [comment]
> could be a small feature to implement.

Unfortunately, this is not a small feature. We'll have to get this right for all 25 RDBMS that we currently support, and there is quite a bit of API that is affected. The relevant feature request is here: #2370

Anyway, I'm sure there's a better solution to solve your immediate problem, so let's try to find that. For instance, you could override the `OracleDatabase` class from jOOQ-meta and filter out the objects that you don't need directly in there. You could also use programmatic configuration of your code generator and generate the regular expression for the `<includes>` or `<excludes>` tags based on some `ALL_TABLES` query result

> If this use case is not enough to start development of such "heavy" feature, I guess you should gather more feedback whether people using your product would like to have more freedom working with views etc.

Oh, I'm positive that people would like to see #2370 implemented, but there are many other features that would be welcome as well, and the workarounds are usually more suitable, because the mere flag indicating whether something is a view or not is useful, but often not useful enough. Programmatic code generation configuration is much more powerful, for example.

> On the second thoughts you can update parts of your documentation clearly stating that your product and specifically pojo generator doesn't distinguish between object types, since I have personally spent this morning trying to figure out why I cannot generate the View's pojos

That is probably a good idea. Which section(s) do you think need to be updated / which sections have you been reading?

**Comment by batousik** [comment]
Ive been scrolling the whole 1-pager, would be definitely relevant to add to sections 6, or even better 6.1

**Comment by lukaseder** [comment]
Thanks for the pointer. Perhaps also 6.8: https://www.jooq.org/doc/3.11/manual/code-generation/codegen-tables

I'll think about this. There are quite a few other locations (including also the Javadoc of `org.jooq.Table`) that should probably be updated. I've created a separate issue for this: #7965

**Comment by lukaseder** [comment]
I hope the presented workarounds are sufficient for you right now. If you need any help with e.g. the programmatic code generator configuration, let me know and I'll be very happy to assist.
