### ISSUE TITLE
Caused by: java.sql.SQLException: Can't read dir of '.' (errno: 24 - Too many open files)

### ISSUE THREAD

**Issue by chuanfliu3326562898** [jOOQ/jOOQ#8130]
### Versions:

- jOOQ:
- Java:
- Database (include vendor):
- OS:
- JDBC Driver (include name if inofficial driver):

**Comment by lukaseder** [comment]
Thank you very much for taking the time to get in touch.

The error message that you're seeing could be caused by many things. I'll be very happy to look into this more in detail, but I think we might need just a little bit more help to reproduce this issue on our side. Would you mind filling out the issue template (expected / actual behaviour, steps to reproduce, versions), and anything else you may think is required for us to reporduce this issue?
