### ISSUE TITLE
Add support for PostgreSQL runtime parameters 

### ISSUE THREAD

**Issue by sainthDE** [jOOQ/jOOQ#8136]
PostgreSQL supports [SET-Syntax](https://www.postgresql.org/docs/current/sql-set.html) for changing runtime parameters.

One Example from [a blog post](https://medium.com/@cazzer/designing-the-most-performant-row-level-security-strategy-in-postgres-a06084f31945):

```sql
BEGIN;
SET LOCAL jwt.claims.roles = ‘c94a743e-8ffd-42dc-a237-b1613e111f53,be95031e-76e0–401a-808c-5c7acde292de’;
-- this represents an example query from an interface
SELECT count(*) FROM items;
COMMIT;
```
This sets temporary (for the active transaction) the value of `jwt.claims.roles` to `c94a743e-8ffd-42dc-a237-b1613e111f53,be95031e-76e0–401a-808c-5c7acde292de` to use [RLS](https://www.postgresql.org/docs/current/ddl-rowsecurity.html) with a custom policy.

**Comment by ieugen** [comment]
Hi, 

Is there any chance I can use this with jooq 3.11.x ? 
We are looking into using RLS for multi tenant shared schema (discriminator column).

**Comment by lukaseder** [comment]
@ieugen, it is definitely possible to run custom SQL commands prior to every jOOQ statement (`ExecuteListener`) or jOOQ transaction (`TransactionListener`), or even prior to any JDBC based statement (write your own `DataSource` proxy).

This issue is about offering out-of-the-box support for setting such parameters, but this out-of-the-box feature isn't really needed. It is just convenience on top of existing listener support.

**Comment by lukaseder** [comment]
jOOQ 3.15 added support for `SET LOCAL`, see https://github.com/jOOQ/jOOQ/issues/11252
