### ISSUE TITLE
Oracle JOOQ open source works anyway?

### ISSUE THREAD

**Issue by nbon12** [jOOQ/jOOQ#8218]
### Expected behavior and actual behavior:
I noticed jooq.org says Open Source version is not likely to work with Oracle, However I am able to make queries using JOOQ to an Oracle database, and I am able to specify driver=oracle.jdbc.OracleDriver in the codegen plugin. 
- Why are there 274 mentions of "Oracle" in the [release notes](https://www.jooq.org/notes/?version=3.11)? @lukaseder 
- What can I expect to happen when using Oracle with open source JOOQ? Which part of the code won't work?
- What exactly is "missing" from the open-source version?

### Versions:

- jOOQ: 
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-jooq</artifactId>
    <version>1.3.5.RELEASE</version>
</dependency>
- Java: 1.8.65
- Database (include vendor): Oracle
- OS: Windows
- JDBC Driver (include name if inofficial driver): 
<dependency>
    <groupId>com.oracle</groupId>
    <artifactId>ojdbc6</artifactId>
    <version>11.2.0.3</version>
</dependency>

**Comment by lukaseder** [comment]
Thank you very much for your enquiry

> I noticed jooq.org says Open Source version is not likely to work with Oracle, However I am able to make queries using JOOQ to an Oracle database, and I am able to specify driver=oracle.jdbc.OracleDriver in the codegen plugin.

Yes, you can get "this far" with the Open Source Edition, mostly because the various SQL dialects are very similar, and JDBC is quite a good API. We didn't include any logic that actively prevents using jOOQ with commercial databases. But from 10 years of experience working around an incredible amount of weird vendor specific edge cases, I'm positive that the type of query you can run on Oracle with the jOOQ Open Source Edition is very primitive. Some very simple examples that won't work:

- No support for the `DUAL` table
- No support for Oracle's flavour of `LIMIT .. OFFSET`
- Wrong binding of `DATE` columns
- Many many more. Try nesting unions, joins, CTE and other clauses in various ways.

> Why are there 274 mentions of "Oracle" in the release notes?

The release notes are for all editions together

> What can I expect to happen when using Oracle with open source JOOQ? Which part of the code won't work?

Random parts, and the parts you thought were working will break again in the next release, because we (obviously) don't integration test the jOOQ Open Source Edition with Oracle

> What exactly is "missing" from the open-source version?

All the various driver logic required for jOOQ to work properly on commercial databases. Plus in the future, we'll develop commercial only features, such as the new procedural API (#6475) and many more.

I hope this helps
