### ISSUE TITLE
Documentation references inexistent org.util package

### ISSUE THREAD

**Issue by cowwoc** [jOOQ/jOOQ#8251]
In https://www.jooq.org/doc/3.11/manual-single-page/#codegen-configuration the documentation reads: 

> The database dialect from jooq-meta. Available dialects are named org.util.[database].[database]Database.

I believe that `org.util.` should be replaced by `org.jooq.meta.`

**Comment by lukaseder** [comment]
Thank you very much for pointing this out, and welcome back! :)

You're right of course. We've renamed packages in jooq-meta and jooq-codegen to avoid split packages as part of the work around getting ready for modularity. These specific package references were overlooked because they were wrong in all versions. Historically, it would have been `org.jooq.util`, not `org.util`
