### ISSUE TITLE
TableField.cast does not work as expected in fetch methods 

### ISSUE THREAD

**Issue by ciaccia** [jOOQ/jOOQ#8268]
Consider the following table having two integer columns:

```sql
CREATE TABLE fetch_map_cast (
    id bigserial PRIMARY KEY,
    val bigint
);
INSERT INTO fetch_map_cast(val) VALUES (1), (2), (3);
```

Now I want to create a map whose key is a long containing the `id` column of the table and the value is a string, obtained by casting the second column `val` to string as following:

```java
Map<Long, String> entries = dslCtx
    .selectFrom(FETCH_MAP_CAST)
    .fetchMap(FETCH_MAP_CAST.ID, FETCH_MAP_CAST.VAL.cast(String.class));
```

The above code unfortunately throws an exception:

> Caused by: java.lang.IllegalArgumentException: Field (cast("public"."fetch_map_cast"."val" as varchar)) is not contained in Row ("public"."fetch_map_cast"."id", "public"."fetch_map_cast"."val")

The workaround for this use-case is the following code:
```java
Map<Long, String> entries = dslCtx
    .selectFrom(FETCH_MAP_CAST)
    .fetchMap(FETCH_MAP_CAST.ID, r -> Optional.ofNullable(r.value2()).map(l -> l.toString()).orElse(null));
````
Is this behaviour expected or is something not working as it should?

**Comment by lukaseder** [comment]
Thank you very much for your request. This makes sense and works as designed. Your query and thus your result set contains the following columns:

- `ID`
- `VAL`

However, when you transform your `org.jooq.Result` into a `Map<Long, String>`, you're accessing two different columns:

- `ID`
- `<cast expression>`

The latter column does not exist in the result set, as the error message suggests. The fix is easy:

```java
Map<Long, String> entries = dslCtx
    .select(FETCH_MAP_CAST.ID, FETCH_MAP_CAST.VAL.cast(String.class))
    .from(FETCH_MAP_CAST)
    .fetchMap(FETCH_MAP_CAST.ID, FETCH_MAP_CAST.VAL.cast(String.class));
```

Or, if that's too much redundancy, assign local variables:

```java
var c1 = FETCH_MAP_CAST.ID;
var c2 = FETCH_MAP_CAST.VAL.cast(String.class);
Map<Long, String> entries = dslCtx
    .select(c1, c2)
    .from(FETCH_MAP_CAST)
    .fetchMap(c1, c2);
```

Curiously, a lot of people using jOOQ make the mistake of thinking that `X` and `CAST(X AS type)` are the same thing, but why would they be? Sure, jOOQ could implement some "clever" equality rules, where some expressions are "more equal" than others. But then, what about:

- `X` and `COALESCE(X, 'xyz')`
- `X` and `CASE WHEN X = 1 THEN X ELSE X END`
- many more

They all look "X-ish", but are they really `X`? The only predictable behaviour jOOQ could implement is to treat the expressions as different expressions.

**Comment by ciaccia** [comment]
Thanks @lukaseder for the explanation, I was also aware of the other solution you proposed with the cast in the select part but for whatever reason I decided not to post it... 😣
