### ISSUE TITLE
Routines

### ISSUE THREAD

**Issue by razilevin** [jOOQ/jOOQ#8321]
### Your question:
Does JOOQ support ASE stored procedures that use default values with named parameters and return result sets. I am using the code-gen utility and it seems not to pick up any stored procedures.

ASE 15.7

**Comment by lukaseder** [comment]
Thank you very much for your enquiry, @razilevin. Currently, jOOQ doesn't support Sybase ASE stored procedures out of the box. See also this issue here: #1507

The main reason for this is that Sybase doesn't seem to offer an easy way to access the procedure meta information.

We've been working on a parser in the recent years, which will soon be able to parse procedural logic, in case of which we'll be able to more formally parse ASE procedure signatures, but unfortunately, we're not there yet.

One option is to implement your own `org.jooq.meta.Database` based on the `ASEDatabase`, and provide procedure catalog information manually - but the jOOQ runtime might still not support calling procedures as long as #1507 is not implemented.

I hope this helps
