### ISSUE TITLE
Wrong #fetchInto behaviour

### ISSUE THREAD

**Issue by jsauvain** [jOOQ/jOOQ#8369]
### Expected behavior and actual behavior:
I've got a own pojo with 4 Strings. In a JOOQ Query I join 2 tables resulting in 4 Strings. Those 4 Strings are not being set to the correct field. Even though the names are identical. After debugging I realized the names of the fields are not being used anymore to map the values. It seems like only the order matters. I found this at org.jooq.tools.Convert#convert(Object[] values, Class<?>[] types).
Interesting: On Version 3.10.1 this did not happen

### Versions:

- jOOQ: 3.11.7
- Java: 1.8.8_181
- Database (include vendor): MariaDB
- OS: OSX
- JDBC Driver: MariaDB official

**Comment by lukaseder** [comment]
Thank you very much for your report.

Would you mind showing how this can be reproduced? An MCVE (https://github.com/jOOQ/jOOQ-mcve) would be perfect, but in your case, perhaps, this could also work with just a set of code snippets that includes:

- The DDL for your underlying table
- The jOOQ query and specific `fetchInto()` call
- The POJO class definition you're using here

**Comment by jsauvain** [comment]
Hello Lukas

Thank you for your quick response. Here are the requested information:
DDL:
`CREATE TABLE person (
  ID        BIGINT      NOT NULL PRIMARY KEY AUTO_INCREMENT,
  firstname VARCHAR(20) NOT NULL,
  lastname  VARCHAR(20) NOT NULL,
  email     VARCHAR(40) NOT NULL UNIQUE

);`
`CREATE TABLE participant (
  ID        BIGINT      NOT NULL PRIMARY KEY AUTO_INCREMENT,
  person_fk BIGINT      NOT NULL,
  auth_key  VARCHAR(30) NOT NULL,
  FOREIGN KEY (person_fk) REFERENCES person (ID)
);`
JOOQ query:
`return getContext()
				.select(PERSON.fields())
				.select(PARTICIPANT.AUTH_KEY)
				.from(PARTICIPANT)
				.join(PERSON).on(PARTICIPANT.PERSON_FK.eq(PERSON.ID))
				.fetchInto(PersonAuth.class);`
POJO (using lombok):
`@Value
public class PersonAuth {

	private long id;
	private String authKey;
	private String firstname;
	private String lastname;
	private String email;

}
`

**Comment by jsauvain** [comment]
To easy things up, I either did an mcve example
https://github.com/jsauvain/jOOQ-mcve
Hope this helps :)

**Comment by lukaseder** [comment]
Thanks a lot for your MCVE. I can reproduce it. But I'm not so sure why you expect this to work as it is now. In the absence of any indication about constructor parameter names, jOOQ maps them by index. And the order of selected columns is simply wrong, in this case.

So, if you want to apply constructor parameter names, you have to do any of:

- Use JavaBeans `@ConstructorProperties`
- Use Kotlin
- Turn on `Settings.mapConstructorParameterNames` (this is brittle. You have to make sure those names are available from byte code, which is not really very reliable)

The `DefaultRecordMapper` specification is explained here:
https://www.jooq.org/javadoc/latest/org/jooq/impl/DefaultRecordMapper.html

I understand that Lombok deactivated the generation of `@ConstructorProperties` by default, because this one silly annotation pulls in the entire `java.desktop` module in JDK 9+. In fact, at some point, we will want to remove that module dependency from jOOQ as well: #7585. I really wish the relatively useful JavaBeans stuff was an independent module, but it isn't.

So, with this now documented, I think the appropriate way to move forward for you is to reactivate the generation of `@ConstructorProperties`

**Comment by jsauvain** [comment]
Thank you for your response.
