### ISSUE TITLE
How to DROP INDEX with DDLDatabase

### ISSUE THREAD

**Issue by pabiagioli** [jOOQ/jOOQ#8406]
### Your question:
I have originally a MySQL/MariaDB Database, and Flyway setup for migration scripts. I currently use the same scripts for migrating and generating JOOQ classes.
I noticed H2 has a MySQL compatibility mode that allows DROP INDEX statements, but `DDLDatabase` doesn't allow to put this connection parameter in place.
I read a lot of the bug reports here in GitHub and I would like to know if anyone had this issue before:
https://github.com/jOOQ/jOOQ/issues/7259
https://github.com/jOOQ/jOOQ/issues/7022
https://github.com/jOOQ/jOOQ/issues/7813

Let's say I have the following SQL Scripts:
- V1.0__InitialScript.sql having a set of tables.
- V1.1__AddConstraints.sql to add unique constraints that were specified afterwards
- V1.2__RemoveBadConstraints.sql to remove some constraints that were wrong in the 1.1 design

I'm using `DDLDatabase` to generate JOOQ classes out of the SQL scripts and I tried to keep the SQL code as standard and as cross-vendor as possible. The issue came when I wanted to drop one of the unique constraints. 

- Is there a way that I can keep my FlyWay scripts and keep using them for JOOQ code generation? 
- Is there a workaround for the `DROP INDEX` instruction and the `MODE=MYSQL` url param?

Thanks in advance

### Versions:

- jOOQ: latest stable 3.11
- Java: 1.8.192
- Database (include vendor): MySQL 8.x
- OS: N/A
- JDBC Driver (include name if unofficial driver): MySQL 8 driver

**Comment by pabiagioli** [comment]
Here's the H2 commit where `DROP INDEX` syntax is being supported
https://github.com/h2database/h2database/commit/b8bbe7c12ac08add8df68402dff5b1de18a0ad43

**Comment by lukaseder** [comment]
Thank you very much for your request.

I'm not sure why you need H2's MySQL compatibility mode here. The `DDLDatabase` only uses H2 because it is an easy to use, complete database that can be added as a Java dependency. We're not relying on any of H2's internals, nor would we want to expose H2 to you, the user of the `DDLDatabase`, as a future jOOQ will get rid of H2 and simulate the DDL statements, instead. You've already found a similar issue that explained this in the same way: #7259

Anyway, regarding your specific questions:

- Is there a way that I can keep my FlyWay scripts and keep using them for JOOQ code generation?

Yes, you're probably already doing that.

- Is there a workaround for the DROP INDEX instruction and the MODE=MYSQL url param?

Perhaps, but maybe, you would be better off here if you just showed the DDL that's currently not working and perhaps we can fix that?

I suggest creating a new issue including steps to reproduce the problem you're having, perhaps by providing an MCVE? https://github.com/jOOQ/jOOQ-mcve

Thanks
