### ISSUE TITLE
Add DSL.neg(Field<?>) as an alias for Field.neg()

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#8412]
And possibly `DSL.minus()` as an alias

**Comment by dantonini** [comment]
I would introduce:
- DSL.neg(FIELD) because you have FIELD.neg(), also if I don't like too much
- DSL.minus(FIELD) bacause you have FIELD1.minus(FIELD2) but as unary operator, more expressive in a math context (at least for me)

As remider probably is useful also add some xtend/kotlin extension methods.
Regards

**Comment by lukaseder** [comment]
Thank you for your comments. Yes, all of that was already implied by the title and the short comment in the issue :-)
