### ISSUE TITLE
Records with more than 22 members should generate overrides that return RowN

### ISSUE THREAD

**Issue by angusholder** [jOOQ/jOOQ#8441]
### Use case:

I want to use an over-22-member record in a VALUES clause, and ideally I'd write `DSL.values(record.valuesRow())` but since `DSL.values()` has an overload `RowN` but not `Row` I have to manually cast the result to `RowN` like `DSL.values((RowN)record.valuesRow())`  

### Possible solution you'd like to see:

Records generated with over 22 members should have overrides of the `Row`-returning methods that instead return `RowN`. #6003 would also solve this, but it seems like >22 record types ought to have row overrides just like <=22 record types.

### Possible workarounds:

Please describe the possible workarounds you've implemented to work around the lacking functionality.

### Versions:

- jOOQ: 3.11.9
- Java: 11
- Database (include vendor):
- OS:
- JDBC Driver (include name if inofficial driver):

**Comment by lukaseder** [comment]
Thank you very much for your request. I'm not quite sure I agree with returning `valuesRow():RowN` from arbitrary `Record` types as all the other record subtypes need to covariantly override the `valuesRow()` and that would no longer be possible.

What you seem to suggest is that we also have a `RecordN` type that clearly indicates that we *know* there are more than 22 columns in the record. That type would then reference `RowN` where e.g. `Record3` currently references `Row3`. I've created a separate feature request #8443 for this. The reason why we didn't do this in jOOQ 3.0 is because it would have produced too big of a backwards incompatibility in client code - still a reason why I'm reluctant to go forward with this.

I'm assuming this issue is really the same as #8443, so I'm closing this as a duplicate. Please let me know if you had something else in mind.
