### ISSUE TITLE
jooq not providing feasibility to get status of records loaded when we forcefully intercepting batch execution by stopping mssql service/removing internet connection.

### ISSUE THREAD

**Issue by svatada** [jOOQ/jOOQ#8481]
org.jooq.Batch.execute() is not throwing java.sql.BatchUpdateException when we interrupt the batch execution by stopping db service/removing internet connection. If it throws java.sql.BatchUpdateException then It could make our jobs easy for us to get updatedRowCount by calling getUpdateCounts() on batchUpdateException obj. Expecting this kind of feature in future release.

Stackoverflow discussion link: https://stackoverflow.com/questions/55417305/how-to-find-status-of-records-loaded-when-we-forcefully-intercepting-batch-execu/55450225?noredirect=1#comment97619523_55450225

**Comment by lukaseder** [comment]
Thank you very much for your report. May I ask you to please supply this relevant version information to tracking down the issue?

- jOOQ:
- Database (include vendor):
- JDBC Driver (include name if inofficial driver):

What is currently happening instead of the expected exception? Would the JDBC driver throw an exception in a similar situation?

**Comment by lukaseder** [comment]
Not sure how to reproduce this. Will close as "works for me".

I'll be very happy to look into this again once there is a more information to help reproduce this problem.
