### ISSUE TITLE
How to define table class short version

### ISSUE THREAD

**Issue by raderio** [jOOQ/jOOQ#8487]
We do not want to use code generation, o we want to create classes by our self.
What is the minimum class definition for a table?
Is it possible to be something like
```
object Cities : TableDefinition() {
    val id = integer("id").autoIncrement()
    val name = varchar("name", 50)
}

object Citizens : TableDefinition() {
    val id = varchar("id", 10).primaryKey()
    val name = varchar("name", length = 50)
    val cityId = reference(Cities.id, "city_id").nullable()
}
```
from https://github.com/orangy/squash

**Comment by lukaseder** [comment]
Thank you very much for your request. Interesting, I was not aware of squash by a JetBrains employee, only Exposed, also by JetBrains.

May I ask *why* you do not want to use the code generator?

Historically, jOOQ is a database first API. It derives its schema meta information from an actual database and its available meta data. The ideal way to use jOOQ is by using the code generator as the generator has been tested for over 10 years by many many users.

There have always been use cases for not using the code generator, mostly because the schema is rather dynamic, so code generation does not make a lot of sense. However, if there is a pre existing schema, we do recommend using the code generator.

In that case, you have several options:

- Write the code that would otherwise have been generated by hand, i.e. extend `TableImpl` manually. This is not supported and your code will likely break when upgrading to the next minor release.
- Use `CustomTable` and `CustomField` as shown here: https://www.jooq.org/doc/latest/manual/sql-building/queryparts/custom-queryparts
- Use plain SQL templating as shown here: https://www.jooq.org/doc/latest/manual/sql-building/plain-sql-templating

But I really recommend using the code generator.

**Comment by raderio** [comment]
> May I ask why you do not want to use the code generator?

- When code is generated and it generates something what we do not want, we cannot change it, for example in database can be some columns, but we do not want to use them in some modules
- We want to keep all the code in Git, but in this case every db schema changes will also trigger changes in code which can break a lot of code

We want to start with minimal table definition, and add functionalities when needed, maybe just by implementing some interfaces with default methods or other technics.

**Comment by lukaseder** [comment]
> When code is generated and it generates something what we do not want, we cannot change it, for example in database can be some columns, but we do not want to use them in some modules

You can use `<excludes>` for that, and turn on `<includeExcludeColumns/>`. See:
https://www.jooq.org/doc/latest/manual/code-generation/codegen-advanced/codegen-config-database/codegen-database-includes-excludes

> We want to keep all the code in Git, but in this case every db schema changes will also trigger changes in code which can break a lot of code

I think that's a good thing, isn't it? I mean, why would you want that code not to break, given that it will not run anyway?

Anyway. You can of course do the work of the code generator manually, but I don't think you should. I'm sure it covers most of your requirements with flags like the above.

**Comment by raderio** [comment]
What functionality requires code generation, that can not be replaced by extending a base class?

**Comment by lukaseder** [comment]
@raderio As I said:

> You can of course do the work of the code generator manually
