### ISSUE TITLE
jooq-codegen-maven does not interpret maven path properties correctly.

### ISSUE THREAD

**Issue by TonyNoble** [jOOQ/jOOQ#8510]
### Expected behavior and actual behavior:
pom.xml has the following jdbc url for jooq code generation:
```
<url>jdbc:h2:mem:fe_trigger;INIT=RUNSCRIPT FROM '${basedir}/src/main/resources/CreateDB.sql'</url>
```
Expectation: jooq configuration as follows:
```
<jdbc><driver>org.h2.Driver</driver><url>jdbc:h2:mem:fe_trigger;INIT=RUNSCRIPT FROM 'C:/Users/USERID/devdir/src/main/resources/CreateDB.sql'</url></jdbc>
```

Actual:
```
<jdbc><driver>org.h2.Driver</driver><url>jdbc:h2:mem:fe_trigger;INIT=RUNSCRIPT FROM 'C:\Users\USERID\devdir/src/main/resources/CreateDB.sql'</url></jdbc>
```
This in turn causes the H2 database startup to fail as it interprets '\\' as an escape character.

A workaround is to remove '${basedir}/' and run maven from the base directory, however some IDEs don't allow this and always run `mvn -f ${basedir}/pom.xml` which then fails with a similar FileNotFoundException, as Jooq does not know to prepend the project basedir to the path of the runscript.

### Steps to reproduce the problem (if possible, create an MCVE: https://github.com/jOOQ/jOOQ-mcve):
1. Create a jooq-maven-codegen plugin entry for an in-memory H2 database that references a maven path property in the path of the RUNSCRIPT referenced by the jdbc url.
2. Run 'mvn generate-sources'

### Versions:

- jOOQ: 3.11.10
- Java: 1.8.0_191-b12
- Database (include vendor): H2
- OS: Windows
- JDBC Driver (include name if inofficial driver):

**Comment by lukaseder** [comment]
Thank you very much for your report. `${basedir}` is a maven property, do you think jOOQ can really do anything about that?

**Comment by TonyNoble** [comment]
> 
> 
> Thank you very much for your report. `${basedir}` is a maven property, do you think jOOQ can really do anything about that?

Hi Lukas

Thanks for the response.  I think jOOQ should ideally take platform-specific file separators into account when processing properties reasonably expecting to contain filepaths.  I'm not sure at which point the variable substitution takes place, but other plugins seem to handle the group of maven properties referencing the project structure without issue.  In all honesty, I wasn't sure whether this should be considered a defect against jOOQ, or the H2 database - please let me know if you think this is in the wrong place.

The upshot of the current situation is that I am unable to build a jOOQ-based project in VSCode without dropping to the command line - autobuild doesn't work either.  This seems somewhat less than ideal.

**Comment by lukaseder** [comment]
> Thanks for the response. I think jOOQ should ideally take platform-specific file separators into account when processing properties reasonably expecting to contain filepaths

That's a slippery slope. Perhaps you *wanted* the string to contain a mix of `\` and `/`, and the behaviour would change if we "fixed" this. Also, fixing it where? In the processing of the JDBC URL in jOOQ's code generator? That's a URL, and the meaning of `\` inside of a URL are not as obvious as you seem to expect them to be. I wouldn't want to preprocess such a URL.

H2, perhaps, because it knows about this URL syntax, so possibly, this is a bug in H2?

> please let me know if you think this is in the wrong place.

My intuition says: Yes, this is the wrong place. jOOQ shouldn't know about `${basedir}`, and jOOQ shouldn't know about the contents of the JDBC URL.

H2 should probably be able to handle this path. If not, then maybe this workaround works for you:
https://stackoverflow.com/q/29210045/521799

I'm closing this as "won't fix", as I don't think this is a jOOQ problem.
