### ISSUE TITLE
Add support for LATERAL to MySQL

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#8542]
As of MySQL 8.0.14 (released on 2019-01-21) the `LATERAL` keyword is now suported. See https://dev.mysql.com/doc/relnotes/mysql/8.0/en/news-8-0-14.html#mysqld-8-0-14-sql-syntax and https://dev.mysql.com/doc/refman/8.0/en/lateral-derived-tables.html.

Unsure about status regarding Aurora MySQL and MariaDB.

**Comment by lukaseder** [comment]
Very nice. I had seen discussions about this feature, some months ago. I wasn't aware they had already published it.

We currently do not distinguish between these MySQL patch releases in the jOOQ `SQLDialect`, so this will be made available under `SQLDialect.MYSQL_8_0`. Since there are no emulations for `LATERAL` and `APPLY` right now (except for implementing one through the other), this should merely be a matter updating the right `@Support` annotations and making sure integration tests keep working.

**Comment by knutwannheden** [comment]
AFAICT Aurora MySQL does not yet support MySQL 8.0 features, so for the time being support has only been extended to MySQL 8.0. Also MariaDB does not yet appear to support LATERAL joins.
