### ISSUE TITLE
Support old SQLDialects only in commercial distributions

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#8551]
Maintaining support for old versions of `SQLDialect` becomes more resource intensive as jOOQ grows more mature. This is a value proposition that we want to offer only to paying customers starting with jOOQ 3.12.

For example, the jOOQ Open Source Edition will only contain `SQLDialect.POSTGRES`, while the jOOQ Professional Edition and jOOQ Enterprise Edition will also contain e.g. `SQLDialect.POSTGRES_9_3`.

We already support old Java versions only in commercial distributions. Likewise, Oracle JDK supports only the latest Java version for free through the Java SE.

This model will help us continue supporting old versions of dialects sustainably, and perhaps even add more support for old versions that are currently not supported, in the future.

**Comment by t9t** [comment]
I was upgrading jOOQ in my projects, and saw that the `SQLDialect.POSTGRES_10` that I was using was removed, which lead me to this ticket.

The Javadoc refers to various instances of SQLDialect, which do not exist any more in the open source distribution. That can be a little confusing, as it almost seems like a bug until finding this issue. Perhaps it should contain a notice that support is available in the commercial editions?

Further, it is a black box for me to understand which dialects of which databases are actually supported now. To find out, I would have to check the date when a jOOQ version was released, and then figure out which version of my RDBMS was the latest at that time.

My suggestion is to keep the specific version dialect instance for the only supported version? For example, keep `POSTGRES_11` now because it is the latest. Then when a jOOQ version comes out after PostgreSQL 12 has been released, delete `POSTGRES_11` and add `POSTGRES_12`.

While this would be a breaking change for some (many?) projects each time, at least it makes it abundantly clear that whatever you are using is not supported any more.

**Comment by lukaseder** [comment]
Thank you very much for your feedback, @t9t.

The Javadoc on our website is that of the jOOQ Professional / Enterprise Editions, as those are the most complete Javadocs. We could publish separate Javadocs for the jOOQ Open Source Edition, but the API is only marginally smaller, so I'm not sure if this would really benefit readers. All commercial API is annotated with the `@Pro` annotation, including e.g. [`SQLDialect.POSTGRES_10`](https://www.jooq.org/javadoc/latest/org.jooq/org/jooq/SQLDialect.html#POSTGRES_10), for clarity.

You're right, we should consistently add the *"This dialect is available in commercial jOOQ distributions, only."* comment to all commercial dialects. Some of them do have it, but not all. I have created an issue for this: https://github.com/jOOQ/jOOQ/issues/9266

> My suggestion is to keep the specific version dialect instance for the only supported version? For example, keep POSTGRES_11 now because it is the latest. Then when a jOOQ version comes out after PostgreSQL 12 has been released, delete POSTGRES_11 and add POSTGRES_12.

That's a good suggestion. I agree that this would cause breaking changes many times, so perhaps there's a better option. We'll think about it, but I agree we should definitely address this documentation issue.

**Comment by lukaseder** [comment]
I'm still not a fan of re-introducing some enum literals only for documentation purposes, as this would heavily complicate the implementation without adding substantial value.

Instead, we'll link from the dialect family (the dialect without a version) to the latest version, if applicable, in the Javadoc. That link will be visible in the public Javadoc (on the website).

I've created an issue for this: #9285
