### ISSUE TITLE
SELECT statement by collection and fields

### ISSUE THREAD

**Issue by raderio** [jOOQ/jOOQ#8563]
Currently there are methods for creating select statement by collection
```
public static SelectSelectStep<Record> select(Collection<? extends SelectFieldOrAsterisk> fields)
```
and a lot of methods by fields
```
public static <T1, T2> SelectSelectStep<Record2<T1, T2>> select(SelectField<T1> field1, SelectField<T2> field2)
```
We want to store a sub projection in a variable and to reuse it in different queries, or the fields can be added in the list by some conditions.

So, we need a method that can receive as first parameter a collection, and the rest for fields
```
public static <T1, T2> SelectSelectStep<Record> select(Collection<? extends SelectFieldOrAsterisk> fields, 
         SelectField<T1> field1, SelectField<T2> field2)
```
May be projection builder, something like query builder.

**Comment by lukaseder** [comment]
Thank you very much for your report. I don't think jOOQ is missing any functionality here.

First off, of course you can manage any collection yourself prior to passing things to the jOOQ API. In more complex dynamic SQL setups, that's probably the best thing to do anyway - to delay the jOOQ query construction for as long as possible. One approach is to go functional:
https://blog.jooq.org/2017/01/16/a-functional-programming-approach-to-dynamic-sql-with-jooq

Instead of "storing your projection in a variable", why not just re-create it every time using a method?

If that doesn't suit you, do note that you can call `select()` several times on `SelectSelectStep`, passing additional columns to a query that you've started constructing.

If that still doesn't suit you, `DSLContext.selectQuery()` exposes the underlying "model API" (as opposed to the DSL API which you're referring to), which allows for a more imperative style query construction.

I hope this helps
