### ISSUE TITLE
Why are there so many empty lines?

### ISSUE THREAD

**Issue by bmintz** [jOOQ/jOOQ#8567]
So, I was looking through the code base, and I noticed that many classes have a ton of blank lines. And some of the commits only add blank lines! See 547f6dbf93c590eda43ddee63e5c206be7b0afe1, or #8560, where the only commit that referenced that issue did nothing but add 10 blank lines. Why is this?

Some more examples:
- https://github.com/jOOQ/jOOQ/commit/65ce24294c42134dd55307dade09c4f3016b3d9e
- https://github.com/jOOQ/jOOQ/commit/60d856075e6f17270c628b2e785490682203c59f
- https://github.com/jOOQ/jOOQ/commit/c7beac5ae3ec755e90c2ef0df68a804a88ade00f
- https://github.com/jOOQ/jOOQ/commit/a7215a91baa67988bd0b29d31d07eb832d1f2695
- https://github.com/jOOQ/jOOQ/commit/b7e6923f34b416860b5b34cc971ed0c10cd2ebdd
- https://github.com/jOOQ/jOOQ/commit/be6200e1ba87e50515951cbdbed94f1673f6a74c
- https://github.com/jOOQ/jOOQ/commit/927708b15ad1048719bd7e96c404ac2223ab9fc7

**Comment by CapnS** [comment]
This is very suspicious activity :suspect:

**Comment by lukaseder** [comment]
Thank you very much for your request. 

The jOOQ Open Source Edition is a copy of the commercial distributions, with the commercially licensed logic having been removed, and the resulting code base being re-licensed under ASL 2.0. What you're seeing are empty "placeholders" for removed code.

In order to improve the user experience, we try to maintain not only source and binary compatibility between the jOOQ Open Source Edition and the commercial distributions, but also identical line numbers to facilitate the community support of the jOOQ Open Source Edition, as we will be getting stack traces with line numbers on them.

Do note that we also have commercial distributions with some logic removed, including the Java 6 compatible distribution, and soon also the Java 8 compatible distribution, as jOOQ 3.12's main distribution will be based on Java 11.

Some insight into how this is all done using source code preprocessing in this blog post:
https://blog.jooq.org/2016/03/01/how-to-support-java-6-8-9-in-a-single-api/

I hope this helps.
