### ISSUE TITLE
Dropping a unique constraint on a column caused jooq to forget about foreign key constraints to that column

### ISSUE THREAD

**Issue by petedmarsh** [jOOQ/jOOQ#8568]
### Expected behavior and actual behavior:

Dropping a unique constraint on a column causes jOOQ to forget about foreign key constraints pointing to that column.
 
### Steps to reproduce the problem (if possible, create an MCVE: https://github.com/jOOQ/jOOQ-mcve):

Please not the following example is adapted from my real code and as such is illustrative (I can't share the real code unfortunately)!

I have previously created a table with a column with a unique constraint on it and a second table which foreign keys to that column. Like so:

```
CREATE TABLE users (
  user_id VARCHAR NOT NULL
  CONSTRAINT users__user_id__uni UNIQUE (user_id)
);

CREATE TABLE orders (
    user_id VARCHAR NOT NULL
    CONSTRAINT orders__user_id__fk FOREIGN KEY (user_id)
      REFERENCES users(user_id) ON DELETE CASCADE
);
```

In my code I use a reference to `myproject.model.Keys.ORDERS__USER_ID__FK` so I can identify the constraint that was violated (in realty there are several constraints).

I have recently decided to change my `users` table to drop the unique constraint on `user_id` (again, illustrative, not really having duplicate user_ids)  like so:

`ALTER TABLE users DROP CONSTRAINT users__user_id__uni`
 
But now jOOQ no longer generates `myproject.model.Keys.ORDERS__USER_ID__FK` - it seems dropping this particular constraint makes jOOQ forget about all other constraints related to this column.

### Versions:

- jOOQ: 3.11.10
- Java: 1.8.0_161
- Database (include vendor): Postgres 10
- OS: OSX
- JDBC Driver (include name if inofficial driver):

**Comment by lukaseder** [comment]
Thank you very much for your report.

> Please not the following example is adapted from my real code and as such is illustrative (I can't share the real code unfortunately)!

That's a very desirable feature of a bug report, in fact :) Part of what makes an MCVE "minimal"

> But now jOOQ no longer generates myproject.model.Keys.ORDERS__USER_ID__FK - it seems dropping this particular constraint makes jOOQ forget about all other constraints related to this column.

jOOQ's code generator just reflects what the database provides it with. Try running this:

```sql
CREATE TABLE users (
  user_id VARCHAR NOT NULL,
  CONSTRAINT users__user_id__uni UNIQUE (user_id)
);

CREATE TABLE orders (
    user_id VARCHAR NOT NULL,
    CONSTRAINT orders__user_id__fk FOREIGN KEY (user_id)
      REFERENCES users(user_id) ON DELETE CASCADE
);

SELECT constraint_name
FROM information_schema.table_constraints
WHERE table_name = 'orders';

-- You cannot drop this constraint without CASCADE, in fact
ALTER TABLE users DROP CONSTRAINT users__user_id__uni CASCADE;

SELECT constraint_name
FROM information_schema.table_constraints
WHERE table_name = 'orders';

DROP TABLE orders;
DROP TABLE users;
```

You'll get:

```
constraint_name       |
----------------------|
orders__user_id__fk   |
2200_368246_1_not_null|

..

constraint_name       |
----------------------|
2200_368246_1_not_null|
```

I'm assuming in your real world example, you actually used `CASCADE` to drop the unique constraint, because otherwise, it "obviously" cannot be dropped.

Why?

A foreign key guarantees that a record in a *referencing* table references *exactly one* record in the *referenced* table. This only works if there is a matching unique key in the referenced table. A foreign key without unique key doesn't make any sense.

For historic reasons, some RDBMS (e.g. MySQL) may allow for such foreign keys to exist, but it really makes no sense.

I hope this helps

**Comment by petedmarsh** [comment]
Thank you very much for the explanation!
