### ISSUE TITLE
Generator can fail picking up default values using SQLite 3.27.2.1 driver

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#8581]
When running the code generator for the SQLite sample database in `jOOQ-test` using the latest 3.27.2.1 driver the generator doesn't pick up the default value for `T_BOOK.TITLE`, but it works correctly for `T_BOOK.LANGUAGE_ID`. Switching back to version 3.25.2 everything works as expected.

No unexpected behavior was found when using DBeaver to connect to SQLite (using the new driver). I.e. both a `pragma table_info('t_book')` and `select * from pragma_table_info('t_book')` returned the expected default values for both columns.

**Comment by knutwannheden** [comment]
Same issue with the 3.27.2 driver version.

**Comment by lukaseder** [comment]
The problem is caused by this issue: https://github.com/jOOQ/jOOQ/issues/4359, which is not trivial to fix. We can work around this problem for the code generator only, preferrably by using the new `ResultQuery.coerce()` functionality: #4473, or alternatively, by running a non plain SQL query with ordinary fields and data types
