### ISSUE TITLE
How to use a custom type as a standalone bind variable?

### ISSUE THREAD

**Issue by ccjmne** [jOOQ/jOOQ#8594]
### Question

I don't understand how to use my custom type bindings to query the database...

I did set up my code generation to map Postgres' `json` (and `jsonb`) type to Jackson `JsonNode`.
It it working well!

I can do:

    final List<JsonNode> = ctx.select(TABLE.JSON_FIELD).from(TABLE).fetch(TABLE.JSON_FIELD);

... and I would get an actual `List<JsonNode>`, which is great!

I can also do:

    final JsonNode myJsonNodeInstance = ...;
    ctx.update(TABLE).set(TABLE.JSON_FIELD, myJsonNodeInstance).where(...).execute();

---

However, when I am not directly doing `.set(TABLE.JSON_FIELD, myJsonNodeInstance)` (which would work), but actually:

    final Field<jsonnode> jsonProperty = DSL.field("jsonb_set({0}, {1}, {2})", JsonNode.class, TABLE.JSON_FIELD, DSL.array("name"), myJsonNodeInstance);
    this.ctx.update(...).set(TABLE.JSON_FIELD, jsonProperty).where(...),execute();

... I run into:
> `org.jooq.exception.SQLDialectNotSupportedException: Type class com.fasterxml.jackson.databind.node.ObjectNode is not supported in dialect DEFAULT`
 
This `DSLContext` isn't aware of my custom binding... and I couldn't find anything related to registering "ForcedTypes" or "Bindings" or anything like that in `org.jooq.conf.Settings`.
I must either be looking at the wrong place or (most probably), be looking at the problem the wrong way.

What am I missing?

### Steps to reproduce the problem:

See MCVE at [ccjmne/jooq-mcve](https://github.com/ccjmne/jooq-mcve).

### Versions:

- jOOQ: `3.11.9`
- Java: `1.8.0-openjdk`
- Database (include vendor): postgres
- JDBC Driver (include name if inofficial driver): `42.2.5`

**Comment by ccjmne** [comment]
Following @lukaseder's answer to my question in the docs (http://disq.us/p/21jc2zg), I could get it to work!

I actually used a `DataType<JsonNode>`, built with the `Converter` that "powers" the `Binding` used by `TABLE.JSON_FIELD`, and `DSL#val(Object, DataType<T>)` takes care of applying my binding.

**Comment by lukaseder** [comment]
Thank you very much for documenting your findings here on Github. I'm sure this will be helpful to future visitors.

**Comment by mkurz** [comment]
@ccjmne In [your commit](https://github.com/ccjmne/jOOQ-mcve/commit/cac9129cc6acba5c76f6e1981cd350a2b6f8a0c2) that is referenced here, you use `DSL.val(value, JSON_TYPE)`, where `JSON_TYPE` is [defined as](https://github.com/ccjmne/jOOQ-mcve/blob/cac9129cc6acba5c76f6e1981cd350a2b6f8a0c2/src/test/java/org/jooq/mcve/test/MCVETest.java#L63)
```java
  public static final DataType<JsonNode> JSON_TYPE     = SQLDataType.VARCHAR.asConvertedDataType(new PostgresJSONJacksonJsonNodeConverter());
```
However, I see that the used converter is actually used in [a binder](https://github.com/ccjmne/jOOQ-mcve/blob/cac9129cc6acba5c76f6e1981cd350a2b6f8a0c2/src/main/java/org/jooq/mcve/jsonbinding/JsonBinder.java#L26) as well already, which is set as forced type in [the config](https://github.com/ccjmne/jOOQ-mcve/blob/cac9129cc6acba5c76f6e1981cd350a2b6f8a0c2/pom.xml#L114-L118).

Are you aware that you could just use `DSL.val(value, JsonNode.class)` instead - or was there a reason you didn't?
Just curious, because I just had the same use case...

**Comment by lukaseder** [comment]
> Are you aware that you could just use `DSL.val(value, JsonNode.class)` instead

Please don't do that. That works by accident, and while I'm trying to keep it working for now despite the many improvements to the `DataType` system, eventually it will stop working.

Also, even if that works today, if you have two converters or bindings map to user type `JsonNode`, whoever gets loaded statically first will "win", so it's already a slippery slope today (also, look for all deadlocks in static initialisers in this issue tracker to get an idea why this will be an important fix in the future.)

**Comment by mkurz** [comment]
Fully agree. After I found out how this worked (see edit in my comment from yesterday) I already changed my code because it seemed fishy too me...
