### ISSUE TITLE
Cannot properly extract ROW element data from ARRAYs

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#8613]
I was debugging the integration test case `PostgresTest.testPostgresArrayAggWithRowField()` where a query returns an ARRAY of ROW objects containing data of mixed types, trying to understand what is wrong there. It looks like the ARRAY of ROW objects returned by the query cannot be properly "unpacked" by jOOQ. Presumably because the elements are instances of `PGobject`, as they correspond to an "anonymous" composite type (row type). So the array elements end up as String objects and the user code could probably run into unexpected `ClassCastException`s as in the example `Integer` is expected.

For debugging it might help to set an exception breakpoint for `DataTypeException`.

**Comment by knutwannheden** [comment]
Might this work out of the box with PGJDBC-NG (https://impossibl.github.io/pgjdbc-ng/)? Would be interesting to run the integration tests with that.

**Comment by lukaseder** [comment]
I don't fully see the point of this pgjdbc-ng project. Why wouldn't the authors just fix the actual driver, rather than re-building one from scratch? I'm not a fan of supporting that driver. There are many others that will then want to be supported, all of which probably with their own little flaws, which we will need to work around, then.

**Comment by lukaseder** [comment]
This was fixed recently: https://github.com/jOOQ/jOOQ/issues/12706
