### ISSUE TITLE
Why make org.jooq.impl package private?

### ISSUE THREAD

**Issue by BreatherLeiYu** [jOOQ/jOOQ#8633]
### Your question:
Why make org.jooq.impl package private?
I want SelectQuery show all orderBy but I can't get SortFieldList in SelectQueryImpl, is there any option to achieve my goal?
### Versions:

- jOOQ:3.11.11

**Comment by lukaseder** [comment]
Thank you very much for your message. Your question isn't really about why the implementation is private. It is always a good idea to encapsulate implementations as this will guarantee that no one will "accidentally" depend on jOOQ's internals, which would make evolving them much more difficult.

What you're currently trying to do is not possible with public API. In a future jOOQ version, we will replace the internal model by a new public API for the expression tree model, which can then be more liberally manipulated by users.

Right now, in order to access your order by clause, you have two options:

- Maintain your own external model prior to passing order by elements to jOOQ
- Use a `VisitListener` to traverse the jOOQ expression tree and get callback calls whenever expression tree elements are visited.

I hope this helps.

I may be able to provide more specific help, in case you are interested. For that, I would need to know more about what you're really trying to achieve here.

**Comment by BreatherLeiYu** [comment]
> Thank you very much for your message. Your question isn't really about why the implementation is private. It is always a good idea to encapsulate implementations as this will guarantee that no one will "accidentally" depend on jOOQ's internals, which would make evolving them much more difficult.
> 
> What you're currently trying to do is not possible with public API. In a future jOOQ version, we will replace the internal model by a new public API for the expression tree model, which can then be more liberally manipulated by users.
> 
> Right now, in order to access your order by clause, you have two options:
> 
> * Maintain your own external model prior to passing order by elements to jOOQ
> * Use a `VisitListener` to traverse the jOOQ expression tree and get callback calls whenever expression tree elements are visited.
> 
> I hope this helps.
> 
> I may be able to provide more specific help, in case you are interested. For that, I would need to know more about what you're really trying to achieve here.

Thanks a lot，I’m trying to fetch all orderby clause in order to edit them again to resort some of fields，and I‘m doing this in the first option you given.

**Comment by lukaseder** [comment]
I see, so you're implementing dynamic SQL statements. The first option is definitely the way to go here. May I recommend these readings, too:

- https://blog.jooq.org/2017/01/16/a-functional-programming-approach-to-dynamic-sql-with-jooq/
- https://www.jooq.org/doc/latest/manual/sql-building/dynamic-sql/
