### ISSUE TITLE
New code generation from domain

### ISSUE THREAD

**Issue by cn-src** [jOOQ/jOOQ#8652]
### Use case:

I am looking forward to a way to generate code purely from the domain model.
1. Generate code does not need to run in the database
2. Provide all required custom metadata through annotations

Ps: Sometimes we don't necessarily need to generate code completely according to the database. For example: foreign key constraint, I hope there is no foreign key constraint in the database, I can still use `join().onKey()`, only need to configure through annotation be usable.

The benefits are:
1. Custom is simpler and safer
2. The domain model is shared by other frameworks, and customized

### Possible solution you'd like to see:

He looks like this:

```java
@Table("t_user")
public class User {

    @Id
    private UUID id;

    @Column("user_name")
    private String  username;

    @JsonbBinding
    private Map<String,String> jsonbBinding;

    @TypeBinding("com.demo.MyTypeBinding")
    private Name name;

    @Converter("com.demo.MyConverter")
    private Name name2;

    @FK
    private User createdBy;
}
```
### Possible workarounds:

It's a bit like JPADatabase, but it should be closer to jooq.

### Versions:

- jOOQ:
- Java:
- Database (include vendor):
- OS:
- JDBC Driver (include name if inofficial driver):

**Comment by lukaseder** [comment]
Thank you very much for your request. If I understand you correctly, you would like us to mirror JPA style annotations in our own API and reverse engineer those instead of the JPA annotations.

It seems obvious to note that this approach might eventually lead to re-implementing half of JPA, in a proprietary way. However, I can definitely see how this could be compelling. Especially the `@Converter` and `@Binding` annotations seem useful, even now as an extension to JPA, which could be picked up by the existing JPADatabase.

Having said so, the existing JPADatabase can already support the "synthetic" foreign key meta data that you want to use in your domain model, but do not have available in the actual database. Other code generation options that do not rely on an actual database connection are:

- `DDLDatabase`
- `XMLDatabase`

I'll leave this feature request open to see if there is more traction in the community for such a feature. It's a big project, so it needs to be designed carefully, but I don't oppose it at this point.

**Comment by lukaseder** [comment]
So far, I haven't seen any traction for this idea on any of our support channels.

We currently have a variety of sources, which can produce generated code:

- `jOOQ-meta`
- `jOOQ`'s `org.jooq.Meta` (via `JDBCDatabase`)
- `XMLDatabase`
- `DDLDatabase` (translation to H2 or some other in-memory database, or soon interpretation of DDL)
- `JPADatabase`

Adding a new annotation based format adds *a lot* of complexity both to the code generation process, as well as to the runtime (which would also need to be able to reverse engineer the format).

Without enough traction or viable use-cases for such a new format, I prefer not to engage in such a project for the near future, with our roadmap being full of other things.
