### ISSUE TITLE
Parsing of LOG() function

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#8682]
There are a number of issues regarding the parsing of `LOG` which need to be looked into:

* It is a bit unfortunate that `DSL#log()` has the `base` as its second argument, since in the SQL standard it is defined as `<general logarithm function> ::= LOG <left paren> <general logarithm base> <comma> <general logarithm argument> <right paren>` and also all SQL dialects I have encountered adhere to this convention.
* There also appears to be a `DSL#log()` overload missing accepting two `Field` objects. Most dialects would for instance allow `LOG(5+5, 100)` which would require this overload.
* Regardless of the parameter order or `DSL#log()` the parser currently gets this wrong in `ParserImpl#parseFieldLogIf()` as it doesn't "reverse" the parameters.
* PostgreSQL also has an overloaded `LOG` function only taking one argument. This corresponds to the logarithm with base 10. The parser should probably be able to handle this.
* H2 also has a `LOG` function, but only accepting one argument, and it corresponds to the natural logarithm. As such it is also a synonym for `LN` (which H2 also knows). Except in PostgreSQL mode, where `LOG` will "correctly" be mapped to the logarithm with base 10.
  * I don't think jOOQ needs to cater for H2's PostgreSQL mode.
  * `Ln#getFunction0()` currently generates `LOG(<field>)` for H2 when computing the natural logarithm. Given the above quirk I think it would make more sense to generate `LN(<field>)`.
  * I might report a bug against H2 since it doesn't support the standard two argument `LOG` function.

**Comment by lukaseder** [comment]
> It is a bit unfortunate that DSL#log() has the base as its second argument, since in the SQL standard it is defined as <general logarithm function> ::= LOG <left paren> <general logarithm base> <comma> <general logarithm argument> <right paren> and also all SQL dialects I have encountered adhere to this convention.

You're right. This can also be seen in the implementation. The rationale behind putting the base first is that this is closer to the mathematical notation: <code>log<sub>base</sub>(value)</code>. But in terms of API design, it would have been better to put the optional parameter second, not first (as jOOQ did).

Following SQL standards and implementations would have been clearly better. But this shouldn't affect the parser? We can still fix the parser (I think you already did?)

It's a backwards incompatible change, so I've added the relevant label here. We can do this because it is "safe" to assume that not too many people rely on this functionality yet.

> There also appears to be a DSL#log() overload missing accepting two Field objects. Most dialects would for instance allow LOG(5+5, 100) which would require this overload.

I'm fine with that addition under a new issue. I had probably not added it, because the first databases I tested this with didn't support expressions as a base. Perhaps they still don't if the expression is not a parse-time constant?

> PostgreSQL also has an overloaded LOG function only taking one argument. This corresponds to the logarithm with base 10. The parser should probably be able to handle this.

We probably need to make this dependant on the parser input dialect. Use `ParseContext.family()` to distinguish between the different meanings of `LOG` with only 1 parameter. In Access, H2, SQL Server, Sybase ASE `LOG` is the natural logarithm. See e.g.: http://h2database.com/html/functions.html#ln

> I don't think jOOQ needs to cater for H2's PostgreSQL mode.

No, we only support H2's "H2 mode". If H2 is run in PostgreSQL mode, then the jOOQ parser should also be set to PostgreSQL mode.

> Ln#getFunction0() currently generates LOG(<field>) for H2 when computing the natural logarithm. Given the above quirk I think it would make more sense to generate LN(<field>).

Yes, please do so in a new issue.

> I might report a bug against H2 since it doesn't support the standard two argument LOG function.

Indeed, many don't

**Comment by katzyn** [comment]
> and also all SQL dialects I have encountered adhere to this convention

You missed the SQL Server:
https://docs.microsoft.com/sql/t-sql/functions/log-transact-sql?view=sql-server-2017

BTW, jOOQ should really produce the standard `LN()` function for natural logarithms in H2. Single-argument `LOG()` function exists in H2 only for compatibility with historic versions and other databases and its behavior is different between compatibility modes.

The next version of H2 will accept the SQL:2016 `LOG()` function too. I don't remember why I didn't merge its implementation earlier, but you reminded me about it.

**Comment by knutwannheden** [comment]
@katzyn Thanks for the pointer. There might be even more others ☹️

**Comment by katzyn** [comment]
I noticed that online translate tool can't currently parse SQL:2016 `LOG10()` too.

**Comment by knutwannheden** [comment]
Nor H2's `LOG10()` 😂

**Comment by katzyn** [comment]
SQL Server 6.0 already had `LOG10()`, maybe older version too, I don't know. `LOG()` as a natural logarithm was introduced in 6.5 or 7.0, I guess. Of course, I can't test it. But H2 is definitely not the first database with `LOG10()` function, however, this functions exists in H2 since the beginning.

And `LOG10()` shouldn't conflict with anything.

**Comment by katzyn** [comment]
https://github.com/jOOQ/jOOQ/blob/9c18aa464e7483a2503937dd57f65537d9f2457a/jOOQ/src/main/java/org/jooq/impl/ParserImpl.java#L6072

Some databases accept floating point values as a base.

**Comment by lukaseder** [comment]
> You missed the SQL Server: https://docs.microsoft.com/sql/t-sql/functions/log-transact-sql?view=sql-server-2017

Aah, finally a database with "reasonable" API design, where the optional parameter is last, not first :)

> BTW, jOOQ should really produce the standard LN() function for natural logarithms in H2. Single-argument LOG() function exists in H2 only for compatibility with historic versions and other databases and its behavior is different between compatibility modes.

Thanks for the confirmation. We'll do this ASAP: https://github.com/jOOQ/jOOQ/issues/8689

**Comment by knutwannheden** [comment]
> You missed the SQL Server: https://docs.microsoft.com/sql/t-sql/functions/log-transact-sql?view=sql-server-2017

I will check that we generate the SQL properly in the `Ln` class. I don't remember seeing any exception for SQL Server there.

**Comment by katzyn** [comment]
I mean 2-argument version, it is different from the standard and needs special handling in parser and code generator.

**Comment by knutwannheden** [comment]
@katzyn Thanks for clarifying.

**Comment by knutwannheden** [comment]
Meanwhile all the issues discussed in this ticket pertaining to jOOQ have been addressed. The parser now correctly parses SQL Server's `LOG()` as well as the SQL standard `LOG()` function.

Note: ACCESS and ASE might also use the "reverse notation" of SQL Server, but I leave that for another issue.
