### ISSUE TITLE
Avoid generating unnecessary {@inheritDoc}

### ISSUE THREAD

**Issue by cowwoc** [jOOQ/jOOQ#8685]
Version 3.11.11

Currently, JOOQ generates the following Javadoc for most methods:
```
 /**
   * {@inheritDoc}
   */
```
This is unnecessary as Javadoc is inherited by default. The only time you would need to do this is if you want to inherit the superclass Javadoc and then override certain sections or throw exceptions that are subclasses of the existing signature.

Please omit this Javadoc unless you are actually augmenting the superclass Javadoc.

**Comment by lukaseder** [comment]
Thank you very much for your report. Yes indeed, they're not needed. I think there was more than just these `@inheritDoc` tags in the past (e.g. column comments and or name) where they appear, but the way they seem to be generated now, they can be removed.

**Comment by lukaseder** [comment]
The Javadoc tag was introduced with https://github.com/jOOQ/jOOQ/commit/b3cd1c5cdfaa7f474f3bce5ab1579182958b3ea6 as part of an issue that was otherwise rejected: https://github.com/jOOQ/jOOQ/issues/1931

I cannot reproduce the rationale anymore that lead to this introduction. The commit comment only says:

> - Moved Javadoc printing to JavaWriter
> - Separated Java writing (JavaWriter) from general writing (GeneratorWriter)
> - Rewrote some generation logic

... which is rather generic.

**Comment by lukaseder** [comment]
Implemented for jOOQ 3.12.

This is a rather cosmetic change but produces a very big diff in generated code (leading to distraction), which is why I won't backport the change to an earlier version

**Comment by lukaseder** [comment]
Thanks again for reporting!
