### ISSUE TITLE
ClassCastException on Record.get(...)?

### ISSUE THREAD

**Issue by mkari37** [jOOQ/jOOQ#8688]
I hope this doesn't expose my thundering ignorance, but why am I getting a ClassCastException when calling getClass() on a Record field? I'm expecting a String[], but apparently I'm being handed a String. Not exactly the same as  #5846?

```java
public class jOOQTest
{
	public static final Table<Record> _TABLE = table(name("users"));
	public static final Field<String[]> FOO = field(name("groups"),	String[].class);

	public static void main(String[] args) throws Exception
	{
		try (	Connection conn = DriverManager.getConnection("jdbc:postgresql://localhost:5432/postgres", "postgres", "postgres");	)
		{
			Configuration configuration = new DefaultConfiguration().set(conn).set(SQLDialect.POSTGRES_9_5);

			try (	DSLContext context = DSL.using(configuration);	)
			{
				context.createGlobalTemporaryTable(_TABLE)
					.column(FOO, SQLDataType.VARCHAR.getArrayDataType().length(1024))
					.execute();

				context.insertInto(_TABLE, FOO)
					.values(new String[] {"a"})
					.values(new String[] {"a", "z"})
					.execute();

				for (Record record : context.select().from(_TABLE).fetch())
					System.out.println(record.get(FOO).getClass());	// throws ClassCastException???
			}
		}
	}
}
```

- jOOQ: 3.11.11
- Java: 1.8.0_60
- Database : PostgreSQL 9.5
- OS: Windows 7, CentOS 7
- JDBC Driver: postgresql-9.4.1207

**Comment by mkari37** [comment]
Huh.

Removing the
```java
.length(1024)
```
from the
```java
context.create...column
```

Solved the issue. Expected String[], got String[].

**Comment by lukaseder** [comment]
Thank you very much for your report.

Notice that the `ClassCastException` is due to: https://github.com/jOOQ/jOOQ/issues/5846. To prevent it in the future, ideally, always explicitly list your columns in the `select()` clause, *especially*, when jOOQ cannot "guess" it at runtime, i.e. when you're operating on tables / columns that you have just created, and thus the meta model (generated code) does not know anything about the column.
