### ISSUE TITLE
Backporting a feature -- access to test suite

### ISSUE THREAD

**Issue by epkugelmass** [jOOQ/jOOQ#8763]
### Your question:

Hi! I'm so eager for 3.12.0 to be released that I looked into backporting https://github.com/jOOQ/jOOQ/issues/8746 to the 3.11.x branch for my own use. I quickly realized that the test suite for jOOQ is not open source. While I'm pretty confident that my backport is correct, it's a little too risky for me to use without running tests.

What options do I have?
1. Wait patiently for 3.12.0 (I know better than to ask when).
2. Buy a commercial license (does this include access to the test suite?)
3. Ask you to run the tests for me (gratis or paid?)
4. Lobby hard for an official upstream backport
5. Other?

### Versions:

- jOOQ: 3.11.8
- Java: 11.0.2 (Oracle OpenJDK)
- Database (include vendor): MySQL 5.6
- OS: Mac 10.14.5
- JDBC Driver (include name if inofficial driver): MySQL Connector 5.1.39

**Comment by epkugelmass** [comment]
Of course, I am happy to contribute the backport upstream.
https://github.com/epkugelmass/jOOQ/tree/backport-8746

**Comment by lukaseder** [comment]
Thanks a lot for your message and for your offers.

jOOQ 3.11 is now on a very stable version, seeing its 12th patch release soon - I am planning to release it this week. I would prefer not to backport such a significant change to 3.11 at this point, given:

- The regression risks
- The fact that XSDs need to be updated and that update needs to be tested
- API will change, and that needs to be documented (we could backport it and not document it in 3.11, of course)

However, thank you very much for offering your backport to the community. Surely, a few users will find this useful.

Regarding your questions:

> Wait patiently for 3.12.0 (I know better than to ask when).

That's the best option here. We'll release in June/July 2019. I'm currently moving all the issues to 3.13, keeping only he remaining important ones (and a few easy ones) in 3.12.

> Buy a commercial license (does this include access to the test suite?)

We don't give access to the test suite with ordinary licenses - only with OEM contracts, which is probably overkill for this particular use case. Of course, purchasing commercial licenses is still a plus because:

- You'll support our developments
- You'll get premium support
- You'll get commercial only features in the future. For example, in jOOQ 3.12, the new procedural language APIs are available only in the commercial distribution.

> Ask you to run the tests for me (gratis or paid?)

In this particular case, I'd really prefer not to backport the feature. jOOQ 3.12 is almost 12 months more recent than 3.11. A lot of things have changed. There is substantial risk of regressions in a very central piece of logic, 4 of the main SPIs.

There's a price for everything, of course, but in this case, I'd rather focus on getting 3.12 ready than backporting big features to 3.11

Besides, you always have the alternative to run on 3.12.0-SNAPSHOT, which we have already tested.

> Lobby hard for an official upstream backport

Well, you can try :-) Lobbying could mean you find a significant number of people upvoting this backport request, but then, still, I'd prefer pushing 3.12 to be released soon, rather than investing time in something that postpones 3.12.

Thanks a lot for your understanding, and thanks again for offering your help here.

**Comment by epkugelmass** [comment]
Thanks a lot for your thoughtful and comprehensive answer!
