### ISSUE TITLE
Methods on TableOuterJoinStep should for now only support ORACLE

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#8769]
The methods of the API `TableOuterJoinStep` (returned by `Table#partitionBy()`) should for now only support `ORACLE`. This also matches the `@Support` annotation of `Table#partitionBy()`.

**Comment by lukaseder** [comment]
Nice catch.

The reason must be the fact that `JoinTable` implements the same API via two interfaces:

- `TableOuterJoinStep` (which is indeed only reachable via Oracle API)
- `Table` (whose join operators are available to all dialects)

Previous integration tests were not able to distinguish between these multiple inheritance cases, which is why the "safe" approach was to annotate too many supported dialects in this case. Our new tests are more precise, I suspect, which is why this now works?

**Comment by knutwannheden** [comment]
The integration testing isn't really more precise now, as it will only verify that at least one of the matching method declarations lists the required dialect as supported. But with this approach it will at least work even when multiply inherited methods don't have identical `@Support` annotations.

**Comment by lukaseder** [comment]
Yes, that's what I meant. The previous implementation picked super type method declarations at random, and thus each method needed to be annotated like all the other ones, just because of this "accidental match".
