### ISSUE TITLE
serialize condition

### ISSUE THREAD

**Issue by z8756413** [jOOQ/jOOQ#8809]
### Your question:

in my rpc service, i try to use jooq as a sql builder, and i use org.jooq.Condition as a param in my service request, just like this
`

public class EsSqlBuilderRequest implements Serializable {

    private static final long serialVersionUID = -1184297323669255790L;

    Condition condition;

    List<SelectField> selectFieldList;

    MerchantIndexEnum index;

}
`

but when i try to call it , it throws a exception like above

`
No serializer found for class org.jooq.impl.CombinedCondition and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) 
`

my rpcserver serialize type is hessian2 , and i found that CombinedCondition implements Serializable already, Why is this throwing an exception?  Thank you for your answer！！ 

### Versions:

- jOOQ: 3.11.7
- Java:
- Database (include vendor):
- OS:
- JDBC Driver (include name if inofficial driver):

**Comment by lukaseder** [comment]
Thank you very much for your message.

I think this has much more to do with how you configure your serialisation library rather than with jOOQ directly. Perhaps we can still be of help here, but I'd need an MCVE (Minimal Complete Verifiable Example) to help reproduce the exact issue you're having. The advantage of an MCVE is that it is complete, including all the third party dependencies that you're using.

Here's a template to create such an MCVE: https://github.com/jOOQ/jOOQ-mcve

**Comment by lukaseder** [comment]
... of course, this might be resolved much more quickly if you ask the maintainers of your serialisation library about how to do this.
