### ISSUE TITLE
Loader does not work with binary data in JSON

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#8829]
When using the loader to load JSON (i.e. `LoaderSourceStep#loadJSON()`) then any binary data (where the field type in the JSON `fields` object is given as `BINARY` or `BLOB`) isn't handled properly. The expectation is that the data in JSON is Base64 encoded and should thus get decoded in the process. This doesn't appear to be working, whereas this does work in the case of CSV. In the case of JSON the data is loaded into the database in the Base64 encoded form.

**Comment by lukaseder** [comment]
Looking into this now. The problem is that in case of JSON loading, the decoding already happens in the `JSONReader` before the `LoaderImpl` logic is applied. `JSONReader` uses `Record.from(ArrayList)`, which delegates to `org.jooq.tools.Convert`, which uses `new String(byte[])` and `String.getBytes()` for binary/string conversions.

While we don't want to change `Record.from` or `Convert`, the `JSONReader` should definitely replicate the logic of `LoaderImpl`, when converting `String` data to `byte[]`

**Comment by lukaseder** [comment]
See also: https://github.com/jOOQ/jOOQ/issues/5858

**Comment by lukaseder** [comment]
While unlikely that someone depended on it, this is a somewhat incompatible change of behaviour, which is why I won't backport it.
