### ISSUE TITLE
Why fetchOne return more than one result

### ISSUE THREAD

**Issue by raderio** [jOOQ/jOOQ#8840]
Why `fetchOne` return more than one result?
Why it does not add automatically `LIMIT1` ?

**Comment by lukaseder** [comment]
Thank you very much for your request. What you're requesting might make sense in a limited number of use-cases, where limited might correspond to a majority number in your case, but not every use-case in every user's situation.

In general, jOOQ tries to avoid being "clever" about such optimisations, because it always goes wrong occasionally. For example:

- Can `LIMIT` be applied on every query in every RDBMS, when there's a `UNION` or other set operator involved?
- Can `LIMIT` be applied when there is no `ORDER BY` in every RDBMS?
- Does `LIMIT` perform equally well as just fetching only the first row in every RDBMS, and is that the expectation?
- How does `LIMIT` interact with `FOR UPDATE`? Does it also limit the number of locked rows (which is clearly not what the author of a query would have wanted)?
- Would `LIMIT`, by enforcing the `One` semantics of `fetchOne` hide potential errors in the query, which would have been detected otherwise, by throwing a `TooManyRowsException`? (This is also a reason why we couldn't change the behaviour, even if we thought it was a good idea).

As you can see, the minor inconvenience you're facing because jOOQ doesn't auto-generate such a `LIMIT` clause has to be weighed against several significant drawbacks that would manifest if we did.
