### ISSUE TITLE
Add org.jooq.InsertReturningStep::returningId safety/convenience method

### ISSUE THREAD

**Issue by epkugelmass** [jOOQ/jOOQ#8847]
### Use case:

jOOQ's INSERT ... RETURNING support is nifty. It also comes with a big caveat. If you're using a database like MySQL, jOOQ will (have to) execute two queries in order to return any column except identity. It's all too easy to forget or misunderstand this behavior (there are about a errors in a medium sized codebase I contribute to). Without a properly configured transaction, the two DML statements may be interleaved with other queries. Ideally, the jOOQ API would provide an alternative that:
1) Nudges the developer to return only the ID
2) Is resilient in the face of ID field changes

`insertStep.returning(TABLE.ID)` does not satisfy the second criterion. `insertStep.returning(TABLE.getIdentity().getField())` is exceptionally verbose (almost an anti-nudge)

### Possible solution you'd like to see:

Possible APIs:

`InsertResultStep<R> returningId()`
`InsertResultStep<Record> returningResultId()`

Both dynamically look up the table at execution time to emulate `insertStep.returning(TABLE.getIdentity().getField())`. Both throw a runtime exception if <R> does not correspond to a table with a known identity field.

Returning a Record1 would be challenging because we cannot know the type of the first record value (as a consequence of looking up the identity field at run-time). An alternative option would be to accept a `Field` but throw at runtime if it's not the identity field. This would allow return of Record1<$TYPE> while failing to satisfy requirement (2) above. 

### Possible workarounds:

I tried writing a static helper `MyHelper.returnId(InsertReturningStep<R>)` but didn't see a place to hook into jOOQ's internal understanding of whether the `<R>` (Record) corresponds to a table (and if so, which).

### Versions:

- jOOQ: 3.11.8
- Java: 11.0.2 (Oracle OpenJDK)
- Database (include vendor): MySQL 5.6
- OS: Mac 10.14.5
- JDBC Driver (include name if inofficial driver): MySQL Connector 5.1.39

**Comment by lukaseder** [comment]
Thank you very much for your suggestion. It is a pity that some dialects do not support the likes of DB2, Oracle, PostgreSQL's "full fledged" `RETURNING` clauses, as they are really useful.

I understand your concern, and indeed, this can be seen as a sore spot in jOOQ, as it is one of the few places where `execute()` or `fetch()` doesn't run 1 query, but 2-3. In order to better understand your use-case, I'd like to know when this can happen: *"Without a properly configured transaction"* - having never worked in an environment where data source provided connections might not be transactional. What's the reason to not always use transactions?

In this particular case, I'm afraid you probably cannot implement a `VisitListener` to sanity check your code at runtime to make sure this feature is not used in the wrong way. However, just adding additional methods will not make the problem go away entirely either, as developers might still accidentally use the "wrong" API.

I'm reluctant to go forward with any current suggestion. I'd like to first better understand the problem, and get more user feedback.

**Comment by epkugelmass** [comment]
> In order to better understand your use-case, I'd like to know when this can happen: "Without a properly configured transaction" - having never worked in an environment where data source provided connections might not be transactional. What's the reason to not always use transactions?

We're not looking to get rid of transactions (as far as I know, there is no way to use JDBC without using database transactions) but we are looking to change the way developers request transactions. We're currently building implicit transactions around each jOOQ `execute`/`fetch`. We were considering moving the transactions down to the JDBC `execute` layer for reasons better omitted here. It's not safe to do so without explicitly wrapping the `returning().fetch()` in a transaction _or_ using `returning(ID).fetch()`. Even if we fix the existing usages, I think the jOOQ API makes the non-transactional (e.g. two query) method too hard relative to the transactional (e.g. one query) method.

**Comment by lukaseder** [comment]
How about implementing an `ExecuteListener`, then? Because jOOQ will always have situations where a second query is necessary... Alternatively, you could implement your own `ConnectionProvider`.

The JDBC layer isn't going to help you here, because jOOQ interacts with it in various ways, and there will always be a new way that you might have overlooked. For example, a developer might choose to use the `Loader` API, which raises new questions. Or they may call the `Query.keepStatement()` method. Or, we might implement entirely new features.

The `ExecuteListener` and `ConnectionProvider` SPIs have contracts guaranteed by jOOQ, so those are much better suited.

In any case, I'm definitely not in favour of an API hack to work around an implementation detail. I'm still not fully understanding your request here, in a sufficient way to offer a thorough solution. But adding `returningId` that implies some transactional *guarantee* (for what dialect(s)? It might *still* not work in a single round trip!) is not going to work. Also, the `ID` is not a completely unambiguous concept:

- It may or may not represent the primary key
- It may or may not represent the identity (which may or may not coincide with the PK)
- It may or may not even be unique
- It may or may not be present on a given table X
- It may or may not be a single column. Composite primary keys are a thing
- We don't currently have a generic type in the `INSERT` DSL API that represents the ID type, so we cannot add type safety to it. The method would return a `Result<?>`, which is really not so helpful.

I will close this issue, as it is about adding `returningId`, a method which will not be added to the API.

**Comment by epkugelmass** [comment]
Got it! Thanks for your analysis. Much appreciated as always.
