### ISSUE TITLE
Investigate where we may have missing parenthesis around conditions

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#8848]
When jOOQ renders SQL it often needs to decide when to render parenthesis around an expression. Typically to get around potential operator precedence problems. We should investigate if this is being done correctly everywhere.

Possibly the operator precendences could be modeled (per dialect?) and the placing of parenthesis be handled automatically.

**Comment by lukaseder** [comment]
> Possibly the operator precendences could be modeled (per dialect?) and the placing of parenthesis be handled automatically.

Oof, that would require:

- A ton of configuration, similar to the configuration of keywords that need quoting, which I really don't want to include in jOOQ. Other products are doing this, and it's just busywork for the maintainers because the lists are never up to date.
- ... configuration that might be outdated every time a vendor updates their syntax rules (which is unlikely for most, but e.g. not for H2)
- It might not work for most cases, because the main reason we're doing the parentheses thing is plain SQL, and we don't want to parse that by default

I absolutely agree that we should have additional, explicit automated tests around the verification of having parens in many cases (there are already many implicit tests). But in this area, I'd really rather "stay safe than sorry" and risk generating one too many parentheses.

Note, there are some cases where we *know* that excess parentheses are being generated, and we can prove that they're unnecessary: https://github.com/jOOQ/jOOQ/issues/7362

**Comment by lukaseder** [comment]
Not sure if anything needs to be done at this point. If there is, we'll discover with new integration tests in the future.
