### ISSUE TITLE
Generate DAOs by interface or GraphQL schema

### ISSUE THREAD

**Issue by raderio** [jOOQ/jOOQ#9005]
At the moment it is possible to generate DAOs with some basic CRUD operations.

Will be great to be possible to generate DAOs based on some interface declaration, something similar to https://micronaut-projects.github.io/micronaut-data/snapshot/guide/
Or it could be code generation based on GraphQL schema https://graphql.org/

The goal is to have code generation for: we have `ProductsRepository` and filtering depends on what user will choose, so in frontend app we have a table with products, and user can sort them by title, price, category, can sort them ascending or descending.

**Comment by lukaseder** [comment]
Thank you very much for your request.

> Will be great to be possible to generate DAOs based on some interface declaration, something similar to https://micronaut-projects.github.io/micronaut-data/snapshot/guide/

DAOs are a very controversial feature in jOOQ, see e.g. #5984 and related discussions. It is extremely easy for a vendor to offer a DAO API, but that raises more questions than it solves for users. Spring Data, and later on also Micronaut, have extended on the DAO / Repository philosophy by supporting their own mini query language which translates English method names to actual SQL (or JPQL) queries. This is an abstraction that seems to add a lot of value when bootstrapping simple CRUD applications, while breaking apart very quickly when the least bit of query complexity arises.

In every single application I've seen so far that uses these APIs, there's an eternal discussion between developers whether a query should still be shoe horned into this simplification, or whether this is now finally a case for The SQL Language, with a surprising bias against The SQL Language.

Obviously, this is not in jOOQ's best interest, an API that embraces SQL. jOOQ's approach here will be solved once we know what to do with DAOs and how to replace them (if at all). Until then, we will probably not implement a very tempting (because quick win), "ugly" solution like an interface based contract that generates SQL queries from English method names.

Don't get me wrong. We do need more convenience for simple CRUD (for some reason, people seem to hardly use the various `DSLContext.fetch()` methods), but it is unlikely going to be a "me too" approach that is based on DAO, just because Spring Data and Micronaut have chosen this path. We don't know the ideal API yet.

> Or it could be code generation based on GraphQL schema https://graphql.org/

Would you mind elaborating on this idea a bit?

**Comment by raderio** [comment]
>Would you mind elaborating on this idea a bit?

I mean that we can have GraphQL schema, or something similar describing what is needed for DAO layer, and based on this schema to generate some DAO for CRUD.

**Comment by lukaseder** [comment]
> I mean that we can have GraphQL schema, or something similar describing what is needed for DAO layer, and based on this schema to generate some DAO for CRUD.

Thanks for these additional details. That sounds like an entirely new product, quite unrelated to jOOQ :) Surely, someone will do this and it will be quite useful for people who do decide to embrace GraphQL strategically - but our strong focus on the SQL language is a strength of jOOQ, which we want to continue maintaining.

I'm closing this issue for now. These are all very interesting ideas, but do not align well with our product strategy right now.

**Comment by raderio** [comment]
The main idea is not to get rid of SQL, but to remove the boilerplate/repetitive code, and this can be done by generating jOOQ code.

```
sealed class OrderedCriteria<T> {
    class Gt<T>(value: T) : OrderedCriteria // greater than this value
    class Gte<T>(value: T) : OrderedCriteria // greater than or equal to this value
    class Lt<T>(value: T) : OrderedCriteria // less than this value
    class Lte<T>(value: T) : OrderedCriteria // less than or equal to this value
    class Match<T>(value: T) : OrderedCriteria // match the value
    // ...
}
```
```
interface BooksRepository {
    findOne<T>(title: Criteria<String>,
               result: Class<T>) : T?
}
```
So, for this interface can be generated a method that in runtime will create the jOOQ query based on the parameters passed to the method.
And in case if generated code is not enough, we can create methods by ourselves.

**Comment by lukaseder** [comment]
How about:

```java
DSLContext dsl = ...
dsl.fetchOptional(BOOK, BOOK.TITLE.eq("jOOQ")).map(Book.class);
```

Is it really that bad? Do we really gain that much? By inventing the same API but different, we're adding a lot of cognitive load on new users, while not really adding that much value to experienced users. There's not much to gain from inventing a second `Criteria` API that does the same thing as our DSL API, but is not the DSL API. There's also not much to gain from inventing a set of conventions that works only for single table queries, when suddenly, you do need a left join or a union, the abstraction breaks.

In my example, the `fetchOptional` call can be transformed to an actual SQL query very easily, without changing the existing criteria. In your example, the whole mindset changes, just because we need one little `EXISTS()` predicate.

**Comment by raderio** [comment]
It looks pretty good. 
If this will select just the fields that are in Book class and not all the fields this is just what we needed.

**Comment by lukaseder** [comment]
No, why would it? :) It will select all the fields that are in the `BOOK` table. Deriving the SQL projection from a transformation step that happens "after SQL" would lead to many questions and inconsistencies, including what would happen if you added `DISTINCT` to your SQL statement?

However, I'm just wondering if we're missing out on a great use-case in general, where we could write something like `BOOK.project(Book.class)`, which would produce the necessary SQL (via a derived table, if needed) *and* take care of projecting the POJO.

This wouldn't be specific to this API usage, but would work throughout the API, including e.g.

```java
dsl.selectFrom(BOOK.project(Book.class)).where(BOOK.TITLE.eq("jOOQ")).fetchOne();
```

I'll think about this. There are probably caveats, as always.
```

**Comment by raderio** [comment]
>No, why would it?

Well, I think this will be better for performance :)

>```dsl.selectFrom(BOOK.project(Book.class)).where(BOOK.TITLE.eq("jOOQ")).fetchOne();```

This looks really good.

**Comment by lukaseder** [comment]
>> No, why would it?
>
> Well, I think this will be better for performance :)

Well, yes of course :) But I mean, the `map()` method you've mentioned is called on a `Result` object, which has already been materialised in the client. It may make perfect sense to fetch 5 columns, and then map only 3 in any given `map()` call (and maybe the other 2 in a separate call). So, it wouldn't make sense to derive any SQL projection from such a `map()` call.

Anyway, I understood the actual suggestion, which was to write the desired client projection only once. In principle, it would be possible to fundamentally change the API such that the SQL projection can be derived from the mapping to Java types that happens afterwards. I've created a feature request for this:
https://github.com/jOOQ/jOOQ/issues/9126

Even better than adding `Table.project(Class<?>)` (which was my idea to handle also edge cases with joins, etc.) would be this syntax:

```java
dsl.select(Book.class).from(BOOK).where(BOOK.TITLE.eq("jOOQ")).fetchOne();
```

From a user perspective, it is "obvious" what the intention of this statement is. This is also a feature Hibernate users value in Hibernate, when they write "projections", although with much less type safety than here in jOOQ. See #9126 for details.
