### ISSUE TITLE
How to add comment to the column by using JAVA

### ISSUE THREAD

**Issue by UCSBGauchos** [jOOQ/jOOQ#9012]
table.column("test", SQLDataType.VARCHAR(20).nullable(false))

Here is the code I am using to add column, but how to add comment to the column. Thanks!

**Comment by UCSBGauchos** [comment]
I try ctx.commentOnColumn(field).is("abc").execute(); but there is an issue:

Caused by: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'comment on column `local_test`.`policy_dimension`.`id` is 'abc'' at line 1

**Comment by knutwannheden** [comment]
Thank you for your request.

Using `DSLContext#commentOnColumn()` is indeed the correct approach. Unfortunately this method is not yet supported for MySQL (as should be visible from the method's `@Support` annotation), since MySQL has a weird syntax for this, which also requires (again) specifying the column's type. We already have an issue for this: #6995.

I will now close this issue as a duplicate of #6995. Please reopen if I missed something.

**Comment by lukaseder** [comment]
Hmm, we do support parsing the MySQL comment syntax in `CREATE TABLE` and `ALTER TABLE .. ADD` statements, but we don't really support the syntax when generating SQL. #6995 will fix this.
