### ISSUE TITLE
Render DROP TEMPORARY TABLE in MySQL

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#9019]
As discussed in #6371 the `TEMPORARY` keyword in `DROP TEMPORARY TABLE` actually has some semantics, and it would thus make sense if `DSL#dropTemporaryTable()` and `DSLContext#dropTemporaryTable()` would render this keyword for supporting dialects (like MySQL).

Let's see what the MySQL manual (https://dev.mysql.com/doc/refman/8.0/en/drop-table.html) has to say on this:

> The TEMPORARY keyword has the following effects:
>
> * The statement drops only TEMPORARY tables.
> * The statement does not cause an implicit commit.
> * No access rights are checked. A TEMPORARY table is visible only with the session that created it, so no check is necessary.
> 
> Including the TEMPORARY keyword is a good way to prevent accidentally dropping non-TEMPORARY tables.

**Comment by AnthonyKot** [comment]
https://github.com/jOOQ/jOOQ/pull/9042

**Comment by javolek** [comment]
This one should definitely be implemented, because, as stated above, without keyword `TEMPORARY` MySQL is going to silently commit the transaction. This makes a huge difference. 
I've spent several hours now to figure out, why my transactions are not properly rolled back, before I noticed in the log that the keyword `TEMPORARY` was missing.

**Comment by lukaseder** [comment]
MariaDB also supports the keyword. MemSQL doesn't

**Comment by lukaseder** [comment]
Fixed for 3.13.0. This improvement is of significant use and little risk, so we'll backport it to 3.12.2 (#9245)

**Comment by lukaseder** [comment]
Related improvement: #9244 (support for `DROP TEMPORARY TABLE IF EXISTS`)
