### ISSUE TITLE
Throw an exception when a Query is executed which returns Query.isExecutable() == false

### ISSUE THREAD

**Issue by fouadz** [jOOQ/jOOQ#9033]
### Use case:

Currently, Query objects that return Query.isExecutable() == false are not executed. The software doesn't know if the query was executed or not. Since Bug #3496 , JOOQ is logging an error. But that's not always enough. In some cases, you want the software to handle that case.

Example
```java
	Map<String, Object> accountUpdate = new HashMap<>();
	try {
        mDslContext = DSL.using( configuration );
        mDslContext.update( CLIENT_TABLE )
    		   .set( accountUpdate )
    		   .where( CLIENT_TABLE.CLIENT_ID.eq( clientId ) )
    		   .execute();
        } catch( Exception e) {
	 doSomething();
	}
```

In the above example, the update query will not get executed and the software has no easy way to know.

### Possible solution you'd like to see:

Add configuration to throw an exception like ExecuteWithoutWhere

### Possible workarounds:

We check if the query is executable before calling execute().

### Versions:

- jOOQ: 3.11
- Java: 11
- Database (include vendor): Postgres 11
- OS: Linux (rhel)
- JDBC Driver (include name if inofficial driver): Java

**Comment by lukaseder** [comment]
Thank you very much for your request. It does sound reasonable to add such a flag at first, given that we already have `ExecuteWithoutWhere` that allows for specifying a log level or even throw an exception. We might be tempted to think that in both cases, an accident would lead to the situation where you'd like a log message or an exception to indicate that the SQL statement was wrong.

However, in the case of a missing where clause in `DELETE` or `UPDATE`, the consequences are dire. In this case, it's a minor (perhaps obscure) bug. Also, it's just an inconvenience that the SQL language offers no such "NO-OP" `UPDATE` syntax, which jOOQ works around. We could just as well pick a random column and run this update instead:

```sql
UPDATE client_table
SET random_column = random_column
WHERE client_id = ?
```

Alternatively, a trigger could lead to the same effective "NO-OP", and it would not produce your exception.

In fact, I'm wondering right now if the whole concept of `Query.isExecutable()` is really viable. Your `WHERE` clause should produce an update count of 1 regardless of the number of modified columns, but you're getting 0, because no query gets executed. With the above emulation, you'd get an update count of 1.

So, the question remains: When would an exception really be the most desireable outcome here? Asked differently, what's currently the main problem with no query being executed?

**Comment by lukaseder** [comment]
I'm not convinced this flag is needed, as per the rationale given in my previous comment. Will close this as "won't fix".
