### ISSUE TITLE
Wrong SQL generated by DSL.countDistinct() without arguments

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#9110]
When parsing `COUNT(DISTINCT *)` the parser emits `select count(distinct )`.

**Comment by lukaseder** [comment]
I don't fully agree with this fix. While it is possible to use `DSL.countDistinct(asterisk())`, the real problem here (and possibly a significant regression!) is the fact that `DSL.countDistinct()` seems to render illegal SQL.

This functionality has worked for a long time, and must continue to work, also without passing `DSL.asterisk()`

**Comment by knutwannheden** [comment]
Yes, I should have thought about that.

**Comment by knutwannheden** [comment]
I just tested `ctx.select(countDistinct()).fetch()` with all major releases back to jOOQ 3.7.0 and it always resulted in the same wrong SQL: `select count(distinct )`.

**Comment by lukaseder** [comment]
Oh wow, thanks for doing that research. Well, that's good news on the regression part :-)

**Comment by lukaseder** [comment]
I'm trying to remember when I last needed `SELECT(DISTINCT *)`. It seems only useful when projecting *very* few columns, and without `GROUP BY`, and even then, I wouldn't trust it...

Anyway, we definitely have to generate valid SQL here.
