### ISSUE TITLE
Support Allow annotation to be applied recursively in packages

### ISSUE THREAD

**Issue by victornoel** [jOOQ/jOOQ#9115]
### Use case:

With a codebase where classes are declared in many packages, it can be useful to express once and for all what are the allowed dialect (and required too I suppose).

For example, I have this kind of packages hierarchy:
- domain
  - stuffs
- infrastructure
  - db
    - aaa
    - bbbb
    - ccc
  - collections

### Possible solution you'd like to see:

If I could add the `Allow` annotation directly on the `package-info.java` file of `db` package and it would apply to sub-package, I think it would make sense.

I don't think this introduce a problem to do so, I don't see why one would want not subpackages be covered by a package rule.

### Possible workarounds:

Use `Allow` everywhere.

### Versions:

- jOOQ: 3.12.0
- Java: 11

**Comment by lukaseder** [comment]
Thank you very much for your suggestion. While I agree that the concept of sub packages would be useful, the Java language has never treated sub packages as such! For example, when using package private visibility, there is no such notion of a subpackage. When applying an annotation to a package, reflecting over subpackages will not yield this annotation via standard means.

However, I do think in this case, it would be useful to be able to opt in to sub package application with a boolean flag that can be set to the annotation, e.g. 

```java
@Allow(value = { MYSQL }, applyToSubpackages = true)
```

**Comment by victornoel** [comment]
> Thank you very much for your suggestion. While I agree that the concept of sub packages would be useful, the Java language has never treated sub packages as such! For example, when using package private visibility, there is no such notion of a subpackage. When applying an annotation to a package, reflecting over subpackages will not yield this annotation via standard means.

Indeed, I didn't know that.

I took the idea from the `@DefaultQualifier` of the checker framework that applies to a package and all its subpackage, see https://checkerframework.org/manual/#default-qualifier:
> If @DefaultQualifier[s] is placed on a package (via the package-info.java file), then it applies to the given package and all subpackages.

**Comment by lukaseder** [comment]
Yes, JSR 305 also has "package-recursive" annotations if I'm not mistaken.

**Comment by remal** [comment]
@lukaseder We have a package-per-feature code structure in our project. So, our repositories are not located in one package but distributed among many packages. It's quite annoying to place `@Allow` on almost all packages in the project. Could you please implement this concept?

**Comment by lukaseder** [comment]
@remal Thanks for your feedback. I understand this may appear annoying to `@Allow` power users, but the correct solution is not yet clear, and I don't want to rush implementing something that isn't sound. Java doesn't have any notion of "package-and-subpackages". It does have a (new) notion of modules, to which an annotation could be applied.

Is "package-and-subpackages" really a sound concept in Java? The discussion hasn't been had yet, and the options haven't been explored yet.

Compared to other, more immediately useful and "obvious" features, this one here doesn't have a good cost/benefit ratio yet.

Of course, if you're putting the annotation in "almost all packages in the project", then why even use the feature?

**Comment by remal** [comment]
@lukaseder I agree that Java doesn't have any notion of "package-and-subpackages". The only thing that comes to my mind is Spring's `@ComponentScan`. However, I think it's worth implementing, as it'll simplify its usage a lot (at least in my case).

Why did I decide to use this feature? The answer would be quite simple: I'd like to statically check that only supported features for my dialect are used.

**Comment by lukaseder** [comment]
> However, I think it's worth implementing, as it'll simplify its usage a lot (at least in my case).

I understand the desire to simplify usage, but it's important to also understand the risk of getting things wrong and then having to support them forever (including fixing the wrong assumptions about what *you* might have expected, but we didn't deliver).

If there's ever a package-and-subpackages semantics to annotation processing in any existing processor, then that's only because we didn't have modules before Java 9. The correct way to increase the scope of an annotation is to put it in the `module-info.java`.

An example is what I've mentioned in https://github.com/jOOQ/jOOQ/issues/9115#issuecomment-526632282, regarding JSR 305. E.g. `@javax.annotation.ParametersAreNonnullByDefault` is an annotation that is "recursive", but it would really be much better to just annotate the module, rather than identify some  artificial "root" package.

> Why did I decide to use this feature? The answer would be quite simple: I'd like to statically check that only supported features for my dialect are used.

I see, for some reason, I had the `Allow.PlainSQL` annotation in mind, not the dialects one. In the former case, annotating every package wouldn't make much sense, but it's obviously useful for latter one.

But again, I think that in your case, supporting adding the annotation to the module would be much more useful than implementing a recursive package semantics. I'll prioritise the following feature request: https://github.com/jOOQ/jOOQ/issues/12770

Until that's implemented, as a workaround, you could perhaps implement a simple code generator that auto generates the `package-info.java` file in every package of your project...?

**Comment by remal** [comment]
First of all, thanks for the answers!

> I understand the desire to simplify usage, but it's important to also understand the risk of getting things wrong and then having to support them forever (including fixing the wrong assumptions about what you might have expected, but we didn't deliver).

I definitely understand your point here and how difficult it is to keep jOOQ backward compatible. Have you considered marking some parts of API as "experimental"? Is there anything that will help you to make a positive decision about implementing this request?

> But again, I think that in your case, supporting adding the annotation to the module would be much more useful than implementing a recursive package semantics.

The thing is we don't use JPMS, so we don't create `module-info.java` file(s). I understand that it's a good practice, but it brings too much pain in a Spring Boot app with a lot of dependencies (some of them have split-package issues, e.g. https://github.com/testcontainers/testcontainers-java/issues/1524).

> An example is what I've mentioned in #9115 (comment), regarding JSR 305. E.g. `@javax.annotation.ParametersAreNonnullByDefault` is an annotation that is "recursive".

I don't think this annotation is "recursive". We have our own `@NonNullByDefault` and we have to put it on every package and subpackages.

> Until that's implemented, as a workaround, you could perhaps implement a simple code generator that auto generates the package-info.java file in every package of your project...?

I'm afraid, it wouldn't be the best solution, as some of our packages are already annotated with some annotations.

**Comment by lukaseder** [comment]
> Have you considered marking some parts of API as "experimental"? 

Sure, there are many experimental features, but here, I don't see the point, because there's a better option: Annotate the module.

> Is there anything that will help you to make a positive decision about implementing this request?

Currently not too likely, given the cost/benefit ratio, and the very compelling alternative of #12770. The roadmap is full of very popular and more pressing feature requests, and this one here is a minor annoyance with a compelling alternative and a viable workaround (generating the `package-info.java` file), compared to a not too compelling, non-idiomatic feature description.

In fact, the whole jOOQ-checker annotation processor is just a few lines of code, so patching it on your end to meet this goal might be yet another option. Personally, I'd go with generating `package-info.java` files.

> The thing is we don't use JPMS, so we don't create `module-info.java` file(s). I understand that it's a good practice, but it brings too much pain in a Spring Boot app with a lot of dependencies (some of them have split-package issues, e.g. [testcontainers/testcontainers-java#1524](https://github.com/testcontainers/testcontainers-java/issues/1524)).

Yeah, I know the problem very well. It took jOOQ quite a while to upgrade. But the ecosystem will go there eventually, and as a library, it's better not to stick to the "past" for too long. jOOQ is ready for modular usage. Starting from 3.14 in the commercial distributions (https://github.com/jOOQ/jOOQ/issues/6612), and starting from 3.15 in the OSS distribution as well.

Again. What would you annotate if this were implemented as requested? A `com` package, to be sure to capture everything? Doesn't that just feel very wrong? What you really want is to annotate a *module*, not some random, accidental package name prefix (or rather a set of prefixes).

> I don't think this annotation is "recursive". We have our own `@NonNullByDefault` and we have to put it on every package and subpackages.

Well, annotations aren't "recursive", just like packages don't "contain" their subpackages. That's just a random thing some processors may or may not have implemented.

As I said. There aren't too many precedents, and it isn't really idiomatic to Java. If anyone has done it, it's a hack. Given the new notion of split packages being forbidden, it's even wrong to annotate package prefixes that you don't actually "own". No one owns `com` or `org`, so no one should add a `package-info.java` file in that "package", just to get some weird side effect of some clever annotation processor that pretends Java's packages are hierarachical.

I know you weren't going to annotate `com`, but rather something more specific, like `com.mycompany.mysystem.mymodule`, but the possibility of the above namespacing conflicts persists, and tells me that this feature request shouldn't be implemented.

> I'm afraid, it wouldn't be the best solution, as some of our packages are already annotated with some annotations.

I assumed (but did not spell it out) that with just a few extra lines of code, that code generator can amend `package-info.java` files, rather than generate them from scratch.

**Comment by lukaseder** [comment]
I won't close this issue here in favour of #12770 yet, but will have this discussion in public, elsewhere, first, e.g.
https://twitter.com/lukaseder/status/1476540309672800260

I think this feature request is a mistake, and the actual feature is #12770 (which I'll definitely implement, hopefully in 3.17). But maybe, someone can make a compelling, general case in favour of emulating hierarchical packages with a bit more data on other cases where this was done.

**Comment by victornoel** [comment]
I read the discussion you just had and as the origin dark requester, I just wanted to say that I totally agree with lukas that modules seems to clearly better match the need I originally had!

**Comment by remal** [comment]
Thanks for the suggestions. I ended up creating my own simple ErrorProne check.

**Comment by seanf** [comment]
> Again. What would you annotate if this were implemented as requested? A `com` package, to be sure to capture everything? Doesn't that just feel very wrong? What you really want is to annotate a _module_, not some random, accidental package name prefix (or rather a set of prefixes).

Instead of an annotation, what about a compiler argument which would apply to the whole compilation, regardless of package, eg all the .java files in a Maven module? 

Some projects, even new ones, may never use JPMS modules. And a decision regarding SQL dialect or possible injection may well be project-wide in scope, not really package-related at all.

**Comment by lukaseder** [comment]
Thanks for your suggestion, @seanf. I had thought about this too, and I was sure I had already created a feature request for this, but it appears I haven't. So here it is: https://github.com/jOOQ/jOOQ/issues/13399

With this in mind, there are two alternative approaches that will both much better solve the underlying problem discussed in this issue here, without resorting to un-idiomatic hacks:

- https://github.com/jOOQ/jOOQ/issues/12770
- https://github.com/jOOQ/jOOQ/issues/13399

As such, I'll reject this issue about making packages recursive, and look into the other two, soon.

**Comment by lukaseder** [comment]
For those interested in this issue and #13399, jOOQ 3.17 will ship with the following 2 supported system properties:

- `-J-Dorg.jooq.checker.dialects.allow=H2,POSTGRES`
- `-J-Dorg.jooq.checker.dialects.require=H2,POSTGRES`

Or

The properies contain comma separated lists of `SQLDialect` values, e.g. `H2,POSTGRES`
