### ISSUE TITLE
Support MySQL FOREIGN KEY [ index_name ] syntax

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#9130]
As documented in the [MySQL manual](https://dev.mysql.com/doc/refman/8.0/en/create-table-foreign-keys.html) the syntax for the `FOREIGN KEY` clause of `CREATE TABLE` and `ALTER TABLE` allows specifying the name of an already existing index:

```sql
[CONSTRAINT [symbol]] FOREIGN KEY
    [index_name] (col_name, ...)
    REFERENCES tbl_name (col_name,...)
    [ON DELETE reference_option]
    [ON UPDATE reference_option]

reference_option:
    RESTRICT | CASCADE | SET NULL | NO ACTION | SET DEFAULT
```

The rules for when `symbol` and `index_name` are used for what seem a bit complicated. But in jOOQ at least the parser should support this syntax.

This issue is related to #7268.

**Comment by lukaseder** [comment]
We should probably find out what databases generate indexes automatically for which type of constraint, and think about how we can generalise this behaviour.

If someone uses MySQL syntax to specify explicit constraint (`symbol`) and `index_name`, we should probably produce equivalent DDL in e.g. Oracle, which doesn't back all foreign keys with indexes automatically.

**Comment by lukaseder** [comment]
A quick test running this:

```sql
create table t (i int primary key);
create table u (
  a int,
  b int,
  c int,
  d int,
  
  constraint fk_a foreign key (a) references t (i),
  constraint fk_b foreign key idx_b (b) references t (i),
  foreign key (c) references t (i),
  foreign key idx_d (d) references t (i)
)

select index_name, column_name
from information_schema.statistics
where table_name = 'u';
```

Yields

| INDEX_NAME | COLUMN_NAME |
| ---------- | ----------- |
| fk_a       | a           |
| fk_b       | b           |
| c          | c           |
| idx_d      | d           |

And then:

```sql
select constraint_name, column_name
from information_schema.key_column_usage
where table_name = 'u';
```

Yielding

| constraint_name | column_name |
| --------------- | ----------- |
| fk_a            | a           |
| fk_b            | b           |
| u_ibfk_1        | c           |
| idx_d           | d           |

So, when parsing this syntax, we can derive the constraint name as follows:

- If explicit constraint name is given, use that as a constraint name
- Otherwise, if explicit index name is given, use that as a constraint name
- Otherwise, don't use a constraint name

The fact that MySQL (and some other dialects) auto-generate an index will be considered separately, eventually.
