### ISSUE TITLE
How do I generate JSON Schema?

### ISSUE THREAD

**Issue by bkuberek** [jOOQ/jOOQ#9176]
### Your question:

Hi,

We operate a system with multiple microservices, including a Rest API and a GraphQL API.

We currently have to manually create JSON Schema, OpenAPI Schema, GraphQL Schema and client side schemas in order to make everything work.

We would like to leverage JOOQ Codegen to generate JSON schema of all types that we can use as a basis for all other schemas. This would allow us to have a single source of truth for our data types.

Could you please point me in the right direction?

Thank you!

### Versions:

- jOOQ: 3.11
- Java: 11
- Database (include vendor): PostgreSQL 11
- OS: Ubuntu Bionic / OS X Mojave
- JDBC Driver (include name if inofficial driver): Official driver

**Comment by lukaseder** [comment]
Thank you very much for your question. Well, jOOQ's code generation is optimised for producing code that works with the jOOQ API to help you produce type safe, embedded SQL queries.

In your question, I don't see much SQL at all - so I'm not really sure what you're expecting here? Generate some JSON data structures from your relational model? You could probably use parts of jOOQ, but you'd be writing most of your generation logic yourself.

Since this doesn't sound like a use case for jOOQ, I doubt I can point you in a reasonable direction. Sorry...

**Comment by bkuberek** [comment]
I will likely be looking into tools that generate JSON Schema from the generate Pojos

[victools/jsonschema-generator](https://github.com/victools/jsonschema-generator) or [gravitee-io/json-schema-generator-maven-plugin](https://github.com/gravitee-io/json-schema-generator-maven-plugin)

Thanks for your answer.

**Comment by lukaseder** [comment]
Thanks for documenting these here. I hope this will help future visitors.
