### ISSUE TITLE
Support CREATE TABLE inline index specifications

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#9243]
Some dialects support specifying indexes inline in the `CREATE TABLE` statement. This is currently supported by the parser, but not by the DSL API nor by `DSLContext#ddl()`, AFAICT.

**Comment by lukaseder** [comment]
> not by the DSL API

We have `CreateTableIndexStep`. What's missing is a way to create complete `Index` types (including column specifications), regardless if they're being used with `CREATE TABLE` or elsewhere.

I was sure we already had an issue for that, but I cannot seem to find it.

> nor by DSLContext#ddl(), AFAICT

Is this really needed, separately? I personally prefer if `DSLContext#ddl()` (now moved to `Meta#ddl()`) produced separate `CREATE INDEX` statements, rather than the inline index specification syntax from MySQL.
