### ISSUE TITLE
SQL Translation Error

### ISSUE THREAD

**Issue by cariny0** [jOOQ/jOOQ#9300]
### SQL translator incorrectly translates this query:

mysql to sqlite:

```sql
update `table01` SET `hasta`=NOW() WHERE (`desde` in ?)
```

**Comment by lukaseder** [comment]
Thank you very much for your report. The error message I'm getting is:

```
Token '(' expected: [1:54] ...ate `table01` SET `hasta`=NOW() WHERE (`desde` in [*]?)
```

This is because in SQL, there is no way to create a bind variable for `IN` lists. Perhaps, some ORMs tweak their SQL statements in order to support that, but SQL itself doesn't know this syntax. The correct syntax would be

```sql
update `table01` SET `hasta`=NOW() WHERE (`desde` in (?, ?)) -- List the number of elements here.
```

Nevertheless, I think it will be helpful to support the synthetic array bind syntax. I've created a feature request for this: https://github.com/jOOQ/jOOQ/issues/9301

Thanks again for your report.
