### ISSUE TITLE
DDLDatabase not supporting JSONB, timestampz with default and parseIgnoreComments error

### ISSUE THREAD

**Issue by Globegitter** [jOOQ/jOOQ#9323]
### Expected behavior and actual behavior:

I expected the schema postgresql schema provided in the provided git repository to be parsed correctly and the jooq code to be generated accordingly. But it failed with some parsing errors.

### Steps to reproduce the problem:

Look at: https://github.com/Globegitter/jOOQ-mcve/tree/markus-psql-error

### Versions:

- jOOQ: 3.12.1
- Java: 11.0.4
- Database (include vendor): postgres script, but error is with DDLDatabase
- OS: Ubuntu 19.10
- JDBC Driver (include name if inofficial driver): Not sure if relevant here.

**Comment by lukaseder** [comment]
Thanks a lot for your report. 

I've seen three problems:

- We're currently not supporting `AT TIME ZONE` yet, see: https://github.com/jOOQ/jOOQ/issues/7238
- H2 (which we're currently using behind the scenes to simulate DDL statements to produce a meta model we can introspect) does not support indexes on `CLOB` columns. The `UNIQUE` constraint on your `IDEMPOTENCY_ID` column doesn't work this way. A workaround would be to use `varchar` in PostgreSQL, or at least in the file that you're passing to `DDLDatabase`. I've created an issue for this: https://github.com/jOOQ/jOOQ/issues/9336
- JSON[B] types cause similar issues because of our simulation on H2: https://github.com/jOOQ/jOOQ/issues/9337
- The parse ignore comment problem is weird - it seems to depend on the number of newlines after the stop comment: https://github.com/jOOQ/jOOQ/issues/9338

Thanks again for your report. I'll close this one, fixing the various other ones separately - although there's probably only an easy fix for the last one. Workarounds include regex-replacing the SQL file's content prior to passing it to `DDLDatabase`, to produce something that our parser, or H2 understands.
