### ISSUE TITLE
Inconsistent field name quoting causes issues in H2 database

### ISSUE THREAD

**Issue by rage-shadowman** [jOOQ/jOOQ#9333]
### Expected behavior and actual behavior:

Expected: createTable command works.
Actual: createTable command fails due to inconsistent quoting of field names.

### Steps to reproduce the problem (if possible, create an MCVE: https://github.com/jOOQ/jOOQ-mcve):

Given a `DSLContext` connected to an H2 database...
```
dslContext.createTable("foo")
        .column(DSL.field("bar", String.class)) // will not be quoted
        .column(DSL.field("baz", String.class)) // will not be quoted
        .constraint(DSL.constraint("foo_PK").primaryKey("bar")) // will be quoted
        .execute();
```
...will fail with the following error:
> org.jooq.exception.DataAccessException: SQL [create table "foo"(bar varchar null, baz varchar null, constraint "foo_PK" primary key ("bar"))]; Column "bar" not found; SQL statement:
create table "foo"(bar varchar null, baz varchar null, constraint "foo_PK" primary key ("bar")) [42122-199]

Replacing `.primaryKey("bar")` with `.primaryKey("BAR")` makes everything work fine since H2 automagically upper-cases the field names (which were not quoted in the generated SQL command).

Replacing all instances of `"bar"` with `DSL.name("bar")` also makes it work fine.

### Versions:

- jOOQ: `org.jooq:jooq:3.12.0`
- Java: 8
- Database (include vendor): `com.h2database:h2:1.4.199`
- OS: Linux
- JDBC Driver (include name if inofficial driver): `com.h2database:h2:1.4.199` (`org.h2.Driver`)

**Comment by rage-shadowman** [comment]
This one seems similar to #8347 but in a different context.

**Comment by lukaseder** [comment]
Thank you very much for your report. This works as designed and can mostly be explained with historic context. You've already  found the correct solution, to use `DSL.name("bar")` when using `DSL.field(Name)`, instead of `DSL.field(String)`.

What *is* a `String`, after all, in jOOQ? It can be mostly two things:

- `org.jooq.Name` (an identifier)
- `org.jooq.SQL` (a "plain SQL" fragment)

Historically, jOOQ only had the plain SQL fragments in its API. `DSL.field("bar")` was as useful as `DSL.field("some_function(bar)")`, or `DSL.field("(bar + 5)")`. All of these are "plain SQL" fragments, but only the first one also appears to be a column identifier.

Eventually, we introduced `org.jooq.Name`, as a means to abstract over qualified / unqualified names, as well as quoted / unquoted names. Then, we added support for DDL, where "plain SQL" is hardly ever useful, which is why `String` maps to `org.jooq.Name` in the DDL API, not `org.jooq.SQL`.

This now leads to the problem you're seeing, which is indeed inconvenient when using jOOQ's DDL API, but we cannot fix this easily without breaking everything.

There are various ways of configuring the quoting in jOOQ as well. You could use the `Settings.renderQuotedNames` flag, for example, to turn off quoting.

I hope this helps
