### ISSUE TITLE
jOOQ generates wrong sql when emulate left anti join with table alias

### ISSUE THREAD

**Issue by alex-lx** [jOOQ/jOOQ#9357]
### Expected behavior and actual behavior:
see the mcve.
### Steps to reproduce the problem (if possible, create an MCVE: https://github.com/jOOQ/jOOQ-mcve):
https://github.com/alex-lx/jOOQ-mcve
### Versions:

- jOOQ: 3.12.0
- Java: 8
- Database (include vendor): mysql
- OS: mac
- JDBC Driver (include name if inofficial driver): mysql

**Comment by lukaseder** [comment]
Thank you very much for your report. We'll look into this soon.

**Comment by knutwannheden** [comment]
This is a tricky one, which I am not sure what we can do about. The problem is that you are using jOOQ's `LEFT ANTI JOIN` and then in your query's `WHERE` clause also refer to columns from the right-hand-side of that join:

```sql
select t1.member_id
from   task t1
left anti join completed_task t2
  on (t1.member_id = t2.member_id)
where t1.group_id = :groupId
  and t2.group_id = :groupId
```
While this looks fine in this form, when rendered, the `t2` table is only referred to inside a `NOT EXISTS` predicate:

```sql
select t1.member_id
from task t1
where not exists (
    select null
    from completed_task t2
    where t1.member_id = t2.member_id
  )
  and t1.group_id = :groupId
  and t2.group_id = :groupId
```

However, in this case (and in many other cases) you can incorporate the `t2.group_id = :groupId` predicate in the join's `ON` clause. So instead of:

```java
        List<Integer> todoTasks = ctx.select(t1.MEMBER_ID)
                .from(
                        t1.leftAntiJoin(t2)
                                .on(t1.MEMBER_ID.eq(t2.MEMBER_ID))
                )
                .where(t1.GROUP_ID.eq(groupId))
                .and(t2.GROUP_ID.eq(groupId))
                .fetch(t1.MEMBER_ID);
```
you would write your query as:

```java
        List<Integer> todoTasks = ctx.select(t1.MEMBER_ID)
                .from(
                        t1.leftAntiJoin(t2)
                                .on(t1.MEMBER_ID.eq(t2.MEMBER_ID)
                                		.and(t1.GROUP_ID.eq(t2.GROUP_ID)))
                )
                .where(t1.GROUP_ID.eq(groupId))
                .fetch(t1.MEMBER_ID);
```
you may now even want to get rid of the `t2` alias, so you don't accidentally introduce this problem again.

**Comment by alex-lx** [comment]
I totally agree with your solution(and it's similar to what I did in our real project, which used a `not in` clause).

However, it still confuses people who use this feature for the first time like me. I understand how hard this problem is and I hope you guys could find out a perfect solution. 👍

**Comment by knutwannheden** [comment]
According to the formal semantics of `ANTI JOIN` it seems clear that the columns of the right table (in the case of an `LEFT ANTI JOIN`) are not available outside the join itself: https://en.wikipedia.org/wiki/Relational_algebra#Antijoin_(%E2%96%B7).

We will look into making this clear in the manual and the Javadoc. Thanks again for the report (and the MCVE!).

**Comment by lukaseder** [comment]
We'll improve the manual and Javadoc through https://github.com/jOOQ/jOOQ/issues/9372

**Comment by lukaseder** [comment]
> @alex-lx I totally agree with your solution(and it's similar to what I did in our real project, which used a not in clause).

Notice, I generally recommend not using `NOT IN` with subqueries because of SQL's three valued logic. If there's a single `NULL` value produced from the subquery, the entire predicate yields `NULL` / `UNKNOWN`, which is unlikely what you want. Always use `NOT EXISTS`, if possible.

See also: https://blog.jooq.org/2012/01/27/sql-incompatibilities-not-in-and-null-values/

**Comment by alex-lx** [comment]
Get it. Good job👍
