### ISSUE TITLE
Add Settings.interpreterDialect

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#9362]
jOOQ 3.13 will introduce a new DDL interpreter, which replaces H2, in order to support syntax that jOOQ supports e.g. for PostgreSQL, but H2 cannot emulate (#8528).

The existing H2 implementation will continue to be shipped by jOOQ, and this new setting will allow for switching the interpreter implementation. The setting is an enum supporting at least these values:

- `H2`
- `DEFAULT` ("jOOQ")

It remains to be seen if we also want to support all the other dialects, with reasonable defaults with respect to "where" the dialects are running. Possibly, we could evolve this into an entire SPI.

**Comment by lukaseder** [comment]
After additional consideration, I'm happy (for now) with a reference to a `SQLDialect` enum that represents the interpreter:

- `H2`
- `DEFAULT` ("jOOQ")

With this approach, we can immediately start supporting other in-memory databases, if we find the JDBC drivers on the class path, as well as test containers provided databases, if we find that on the class path.

**Comment by lukaseder** [comment]
In fact, if the `parseDialect` and the `interpreterDialect` are the same, then we probably don't even need to parse and translate the SQL, but can run it directly. Let's discuss this tomorrow, @knutwannheden.

**Comment by lukaseder** [comment]
Further work will be done in a separate issue: https://github.com/jOOQ/jOOQ/issues/9460

**Comment by petromir** [comment]
Can I assume that this is not supposed to be used in Maven code generator plugin when working with `org.jooq.meta.extensions.ddl.DDLDatabase`?

**Comment by petromir** [comment]
### Context 
I'm at the beginning of setting up a new project (Spring Boot based) which uses jOOQ for database access and Flyway for database migration. In addition, I'm using the Docker-Compose integration of Spring Boot 3 which makes the flow of running and testing the application pretty smooth by initializing the database and Flyway before the application context is initialized.
### "Problem"
I would like to use jOOQ's code generation with Maven and integrate it with Flyway and Docker-Compose. I've reached the following 3 options:
- Using `org.jooq.meta.extensions.ddl.DDLDatabase`, which doesn't work as H2 is not compatible with some MySQL specifics, e.g. inline `KEY/INDEX` definition when creating a table. This is how I found this ticket 🙂. I see that there is an [option to pass](https://stackoverflow.com/a/30654814) `mysql` mode to H2, but I don't think this was planned to be controlled by jOOQ's Maven plugin.
- Using jOOQ, Flyway and TestContainers following this [guide](https://testcontainers.com/guides/working-with-jooq-flyway-using-testcontainers/#_implementing_basic_database_operations_using_jooq). While this might work, I'm trying to keep the tooling minimal and taking into account that I already have docker-compose file, adding TestContainers to the mix is not desirable. Yes I know, I can completely switch to TestContainers by using SB 3 support, but so far my experience with TestContainers is mostly negative, especially when running it in GitLab pipelines.
- [Using jOOQ and Flyway plugins](https://github.com/jOOQ/jOOQ/blob/main/jOOQ-examples/jOOQ-flyway-example/pom.xml), and running manually database defined in the docker-compose file before the code generation. I might further optimize this if I find a reliable Maven plugin to manage Docker Compose with profiles, volumes and networks.

All of the above options will be hidden behind a Maven profile, so I don't execute them on each local/ci build or test.

To be honest, the first option is the cleanest one, but due to the issue that I hit, I'm looking at option 3.

P.S. The documentation of jOOQ rocks!

**Comment by lukaseder** [comment]
Thanks for the additional details

> * This is how I found this ticket 🙂. I see that there is an [option to pass](https://stackoverflow.com/a/30654814) `mysql` mode to H2, but I don't think this was planned to be controlled by jOOQ's Maven plugin.

I see, so this is what most people run into when using the `DDLDatabase`. Numerous issues are on the roadmap. The `interpreterDialect` will solve a few caveats, probably introducing new ones. You were probably looking for this issue, instead:

- https://github.com/jOOQ/jOOQ/issues/7034

> To be honest, the first option is the cleanest one, but due to the issue that I hit, I'm looking at option 3.

The "cleanest" one is to use testcontainers, because:

- It uses an actual MySQL database
- It doesn't depend on any pre-installed environment

That makes it very suitable for reproducible builds on any machine, and you can profit from this setup also for your integration tests. You can use testcontainer's own experimental plugin, or just use groovy/etc to start/terminate your container:
https://blog.jooq.org/using-testcontainers-to-generate-jooq-code/

The `DDLDatabase` is definitely not the "cleanest" option here. It's just the fastest, but it requires *emualting* (with H2) or *simulating* (with the interpreter) an entire database. This means that the option will only ever get you so far. Say bye to your triggers / stored procedures / etc. (for now, until we support interpreting them).

To give you some context, the *main* reason why `DDLDatabase` was implemented was to allow for integration testing the jOOQ code generator, in case the tests don't test RDBMS specific things. It turned out that it would be useful for numerous use-cases also in user code, but it will always fail at some point for non-trivial database schemas.

In any case, the main issue users have with it (currently) is case sensitivity of identifiers. That part has been recognised and will be addressed eventually. It's just not that easy, nor is it the highest priority.

**Comment by petromir** [comment]
Thanks for the answer!

> The "cleanest" one is to use testcontainers, because:
It uses an actual MySQL database
It doesn't depend on any pre-installed environment

I don't completely agree as testcontainers depend on Docker, which makes it equal to Docker-Compose option, at least for me.

> That makes it very suitable for reproducible builds on any machine

Until it breaks in GitLab and DevOps team tell you that they not gonna support it 😄 

> The DDLDatabase is definitely not the "cleanest" option here. It's just the fastest, but it requires emualting (with H2) or simulating (with the interpreter) an entire database. This means that the option will only ever get you so far. Say bye to your triggers / stored procedures / etc. (for now, until we support interpreting them).

I think I realised this the hard way 🙂
