### ISSUE TITLE
Deprecate remaining Field.xyz() convenience API

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#9407]
The `[lr]trim()` methods in `AbstractField` are already `@Deprecated`. The API methods in `Field` should probably also be.

----
See also: https://github.com/jOOQ/jOOQ/issues/7538

**Comment by lukaseder** [comment]
There is historic redundancy between *some* `DSL.func(A, B)` and `A.func(B)` methods, which can be explained in their historic context. The infix "method" notation was introduced at some point for convenience, and I trust that some of these are actively used, such as e.g.:

- `Field.abs()`
- `Field.count()`
- `Field.trim()`

However, only functions that have been made available historically using their infix notation on `Field.func()` are there. No new functions have been added this way. And some API deprecations were more recent: https://github.com/jOOQ/jOOQ/issues/7538

I had once thought of removing them all in 2011, but reverted that move in jOOQ 2.0 again:
https://github.com/jOOQ/jOOQ/commit/5d2b412dde893e674cfc59baab09a18775122ba8

Given that there has not been any feedback about #7538 yet, which deprecated the majority of these (see https://github.com/jOOQ/jOOQ/commit/3e6ea7ff79948f7a28ac83043f5726cee23ea51d), I agree that we can deprecate the remaining ones.

**Comment by lukaseder** [comment]
Removing some paragraphs from the manual, too...

**Comment by ams-tschoening** [comment]
Obviously I've missed something in this whole topic, so what is the benefit of deprecating those functions? I just upgraded to 3.13.0 and wonder why the following is bad style:

	.select(COLLECTOR.ID,
			COLLECTOR.MAC_ADDRESS)
	.from(COLLECTOR)
	.where(COLLECTOR.MAC_ADDRESS.lower().in([...]));

While the following is not:

	.select(COLLECTOR.ID,
			COLLECTOR.MAC_ADDRESS)
	.from(COLLECTOR)
	.where(DSL.lower(COLLECTOR.MAC_ADDRESS).in([...]));

> This post-fix notation is counter intuive, and not really very useful.

How can it be counter intuive if all those functions are applied the same style in the end, the IDE suggests functions when typing column names etc.? In the above example, I mostly need to write the columns instead of beginning with `DSL`. Thinking of when to use function on the columns and when I need to use `DSL` make things more difficult, not easier.

I don't seem to get the point here.

**Comment by lukaseder** [comment]
> Obviously I've missed something in this whole topic

Most of this is explained in this comment:
https://github.com/jOOQ/jOOQ/issues/9407#issuecomment-544386567

> I just upgraded to 3.13.0 and wonder why the following is bad style [ ... ] while the following is not [ ... ]

You can call `Field.lower()` on any `Field<T>` type, including e.g. `Field<Date>`, whereas `DSL.lower()` exprects a `Field<String>`. The latter is always correct, the former might just be wrong. This rationale applies to all of these functions that have been deprecated. E.g. what is the use of being able to call `METER_ENC_KEY.KEY.abs()`?

That's one reason. It applies mostly to functions, because of the other reasons mentioned. Note, it also applies to operators (e.g. `Field.plus()`), but in case of SQL infix operators, the placement on `Field.op(Field)` is much more natural than with functions. In your example, `Field.in(Select)` is such an example. There's a type safety tradeoff here. With infix operators, the tradeoff is in favour of going ahead, because of SQL alikeness (it would be very surprising to use `DSL.in(T, Select)`, for example). With prefix functions, the tradeoff is less favourable.

> How can it be counter intuive if all those functions are applied the same style in the end

1. SQL doesn't support this post-fix or in-fix notation, so why should jOOQ?
2. From my comment: *"No new functions have been added this way"*. The API is very inconsistent the way it is right now, and we'll gradually clean this up.

You have vastly more functions available in `DSL.xyz(a, b)` than `a.xyz(b)`. For consistency reasons, it's a good idea to move towards a single vision of how to do things. Yes, this will cause friction with existing users who like some of the existing API, but for example, no one has ever requested we add `Field.unique()` or `Field.primaryKey()` to turn a field expression into a constraint for usage in DDL (which we should, if we wanted to keep things the way they are, for consistency reasons). Maybe, that's a bit esoteric. So, how about `Field.year()`, `Field.month()`, `Field.day()`, `Field.hour()`, `Field.minute()`, `Field.second()`, `Field.millisecond()`, `Field.microsecond()`, `Field.nanosecond()`, `Field.epoch()`, `Field....()`. You get the point. No one has requested we add these. If this infix notation was such a great feature, I would have expected more such requests.

Notice that we're always deprecating things strategically. We've already deprecated similar `Field.xyz()` API before: https://github.com/jOOQ/jOOQ/issues/7538. That was 1.5 years before in jOOQ 3.11, and we didn't get any feedback from the community about it, at all. This is a good sign in favour of deprecating more such API, and again, this is the first feedback in 0.5 years about this particular deprecation. It is understandable, because it works just like Java's `String.toLowerCase()`.

If we had gotten more feedback (as with my planned deprecation about DAOs: https://github.com/jOOQ/jOOQ/issues/5984. Only *planned*, not even executed!), then we could still reconsider. But in this case, the ratio between *benefit for us as API maintainers* and *number of feedback about this deprecation* is very much in favour of going ahead as planned.

The status quo is arbitrary and not clean. We want to achieve a cleaner API eventually. There are two choices:

- Deprecate (as planned)
- Duplicate *everything* (a ton of work, it must really be justified!)

> In the above example, I mostly need to write the columns instead of beginning with `DSL`. Thinking of when to use function on the columns and when I need to use `DSL` make things more difficult, not easier.

I'm aware of the benefits of object orientation and the notation that comes with it. But this isn't merely about making things just a little bit more convenient *in this case*. Because we're not going to add *all* the functions from `DSL` to `Field`, `Row[N]`, `Select`, and all the other types that might correspond to the first argument type of such a function. As I mentioned above, you're only mentioning the inconvenience you're experiencing in the case of `lower()`, which I perfectly understand. You've grown used to it.

But, again, in 11 years of doing jOOQ, I don't recall anyone requesting more functions from `DSL` be duplicated also on `Field`. This is a strong sign in favour of this deprecation, and against maintaining the status quo. In other words, while people have grown used to the existing convenience, they would not miss it, if it had never been here in the first place. They will miss it only because it's being taken away from them, which is a natural effect of deprecation and feature removal.

jOOQ is first and foremost a SQL DSL and the place where most people expect functions to be located in jOOQ is `DSL`. Throughout the manual and in all Stack Overflow answers, there is an implied static import `import static org.jooq.impl.DSL.*;` which allows to produce jOOQ SQL that looks almost like actual SQL. From that perspective, using `DSL.xyz(a, b)` is better than using `a.xyz(b)`.

Note that some languages allow for defining `infix` or `extension` methods outside of the API, e.g. Kotlin. I very much prefer that approach, which would allow people to maintain their own "extensions" on top of jOOQ to achieve this particular goal.
