### ISSUE TITLE
table.field(name, type) returns Coerce instead of TableField when type matches

### ISSUE THREAD

**Issue by josephlbarnett** [jOOQ/jOOQ#9423]
### Expected behavior and actual behavior:
We have code that looks at fields and attempts to group them by Table by doing:
```
if (field instanceof TableField) {
    return ((TableField)field).getTable();
} else {
    return null;
}
```
In jooq 3.11.12, that works fine, but in 3.12.2, we're getting fields that are `Coerce` wrappers around `TableField`s, and losing an accessible link to the Table.  This is happening when we get a field by name and type, for example: `table.field(otherTableField.getName(), otherTableField.getType())` (where generally the field on `table` is a foreign key to `otherTableField`)

If we were able to get the underlying field out of the Coerce, we'd be ok checking something like `((Coerce)field).getField() instanceof TableField)`; alternatively if `table.field(name, datatype)` only did the coerce if datatype did not equal the table's datatype, it would solve our issue as well.  Open to other suggestions as well.  We can somewhat work around this by just doing `table.field(otherTableField.getName())` (and casting to a `Field<T>` or losing the type information), but would prefer to maintain the generic type information without doing an unsafe cast.

### Steps to reproduce the problem (if possible, create an MCVE: https://github.com/jOOQ/jOOQ-mcve):

MVCE passes with jOOQ 3.11.12, but fails with 3.12.2:

https://github.com/josephlbarnett/jOOQ-mcve/tree/tablefield-coerce-issue

### Versions:

- jOOQ: 3.12.2
- Java: 11
- Database (include vendor): postgres from https://github.com/opentable/otj-pg-embedded/
- OS: linux
- JDBC Driver (include name if inofficial driver): postgres driver

**Comment by josephlbarnett** [comment]
ok, this looks like the coerce behavior was intentionally changed per https://github.com/jOOQ/jOOQ/issues/8234.  Should `table.field(name, type)` just defer to coerce or does the type equality logic make sense to have there?  Seems weird to not get something that implements TableField back from that method.

**Comment by lukaseder** [comment]
Thank you very much for your detailed report, and for following up with some research. Indeed, the "regression" has been introduced with #8234, which fixed a variety of problems, including the fact that before fixing #8234, the behaviour was inconsistent when the data type *didn't* match. For example, your test fails also on 3.11.12, when writing:

```java
@Test
public void mcveTest() {
    // Instead of:
    // Field field = Tables.TEST.field("VALUE", Integer.class);
    // Write:
    Field field = Tables.TEST.field("VALUE", Long.class);
    assertTrue(field instanceof TableField);
    assertEquals(Tables.TEST, ((TableField)field).getTable());
}
```

However, it would be interesting to think about whether we should change `Table.field(String, Class<?>)` and related overloads to return an actual `TableField` (and guarantee this through API) rather than returning an arbitrary `Field` expression as we do now. I have created a feature request for this: https://github.com/jOOQ/jOOQ/issues/9456

Given that the behaviour was already inconsistent in version 3.11, and you could have run into this problem before, e.g. when modifying your database type from `INT` to `BIGINT`, I prefer not "fixing" this in a patch release of version 3.12.

I wonder, however, why you pass the `Integer.class` argument in the first place. If grouping things by table is your use-case, then I suspect it would be sufficient to just use `field(String)`, which does produce the `TableField` reference directly (although this as well is not currently documented).

**Comment by lukaseder** [comment]
I'm closing this as I don't think we've introduced a regression here. I do think we should address this more thoroughly though, possibly in jOOQ 3.13, via #9456

**Comment by josephlbarnett** [comment]
Thanks, will follow #9456.  For just grouping by tables, `field(String)` would be sufficient.  We have other use cases as well (mostly dynamically building filters and join conditions, sometimes on raw tables, sometimes on CTEs that we also build dynamically) where we use a generic `Field<T>` to build the filters/conditions in a type safe manner.  For those, the `Field<?>` that `field(String)` returns is not ideal.  In some cases, we still have access to an equivalent field and can use `field(Field<T>)`, which solves some of the "issue" we see here, but I think there might still be cases where we hit problems.

**Comment by lukaseder** [comment]
I understand the limitations of having to work with `Field<?>`, but unfortunately, that's really the only appropriate type we can provide on `field(String)`. And when you call `field(String, Class<T>)` or `field(String, DataType<T>)`, we have to provide some type that really guarantees the type semantics of `T`. This cannot be the original `TableField<R, U>`, where `U = T` might just coincide by accident.

However, in those cases where you do need to create predicates, you probably don't need a `TableField` type, so you can continue calling `field(String, Class<T>)` in those cases.

**Comment by vryzhuk** [comment]
I have reported one more bug, related to `field(String, Class<T>)` and `coerce`, which returns wrong `DataType` during coerce: #9485 . Returning actual fields if types are the same could fix some cases in specified issue too.

**Comment by lukaseder** [comment]
@vryzhuk Thanks for your reference. #9485 is not strictly the same issue. Returning actual fields would have further delayed the actual problem that you're running into: The implied dependency on some internal behaviour, which should not exist in the first place: https://github.com/jOOQ/jOOQ/issues/9492
