### ISSUE TITLE
JSON type unmapping broken since 3.12

### ISSUE THREAD

**Issue by hank-cp** [jOOQ/jOOQ#9474]
### My question:

Since Jooq start to support `json/jsonb` database type from v3.12, I have to update my custom Json type bindings from
```
public class PostgresJSONGsonBinding implements Binding<Object, JsonElement> { ... }
```
to 
```
public class PostgresJSONGsonBinding implements Binding<JSONB, JsonElement> { ... }
```
because the codegen `Tables` changed from
```
public final TableField<BookRecord, JsonNode> EXTRA = createField("extra", org.jooq.impl.DefaultDataType.getDefaultDataType("\"pg_catalog\".\"jsonb\""), this, "", new JsonbBinding());
```
to 
```
public final TableField<BookRecord, JsonNode> EXTRA = createField(DSL.name("extra"), org.jooq.impl.SQLDataType.JSONB, this, "", new JsonbBinding());
```

In pre-3.12 way my custom Bindings could accept any type of object and convert it to `JsonNode`, but now it accept `JSONB` type only. It causes all of my previous `Type` to `Record` conversions broken.

Is there any way to tell jooq codegen accept `Object` type but not just `JSONB` type since v3.12?

My codegen config:
```
                        forcedTypes {
                            forcedType {
                                userType = 'com.fasterxml.jackson.databind.JsonNode'
                                binding = 'com.laxture.lolth.jooq.binding.JsonbBinding'
                                types = 'jsonb'
                            }
                        }
```

### Versions:

- jOOQ: 3.12.1

___

BTW, the document custom binding demonstrations ([here](https://www.jooq.org/doc/3.12/manual-single-page/#custom-bindings) and [here](https://www.jooq.org/doc/3.12/manual-single-page/#custom-data-type-bindings)) are still using `Object`, it should need to be updated accordingly I guest:)

**Comment by lukaseder** [comment]
I'm sorry for the delay in this. This issue seems to have slipped through our email notification filters.

Why do you need to map any arbitrary `Object` type in your binding? Do note that you don't *have* to make use of the `JSONB` class in your binding implementation. You can bind any JDBC value you like.

**Comment by lukaseder** [comment]
Thanks for the pointer to the manual pages. Indeed, those need updating. I've created a separate issue for this: https://github.com/jOOQ/jOOQ/issues/9623

**Comment by hank-cp** [comment]
Hi @lukaseder, I have created a simple project to reproduce this issue. You could switch between jooq `v3.11` and `v3.12` to see the different test result.

However, I have walked around this issue by introducing a `RecordUnmapper` which is provided by [SimpleFlatMapper](https://github.com/arnaudroger/SimpleFlatMapper). If you think it's OK to leave it as, feel free to close this issue :)

**Comment by knutwannheden** [comment]
@hank-cp From what I can tell:

* As the model you have a `Book` POJO which has a `filter` property which is of custom POJO type `FilterCondition`. This latter POJO in turn only has three plain `String` properties.
* In the database you have a `BOOK` table which has a corresponding `FILTER JSONB` column to represent the POJOs.
* In your record class you want to use Jackson's `JsonNode` to represent the `filter` property. This has been configured using a forced type.

Your `Book` POJO also has an `extra` property of type `JsonNode` and now you want to use the `RecordUnmapper` to map the POJOs to a record type, so you want the binding / converter both to be able to convert a `JsonNode` as well as a `FilterCondition` object to a `JSONB` value.

Additionally your `Book` POJO also has a `filters` property of type `List<FilterCondition>` which you in the database also represent as a `JSONB` value (i.e. `FILTERS JSONB`), which you also want to be handled by the binding when doing the record unmapping.

I think this would require https://github.com/jOOQ/jOOQ/issues/6159 to be implemented, but possibly some workaround can be derived in the meantime. I will have to discuss this with @lukaseder.

**Comment by lukaseder** [comment]
I don't have much to add to this discussion. I'm not sure why this would have worked in previous releases and no longer works now - there are many features interacting here, and indeed #6159 would need to be implemented first, I think, for this to work.

One confusion that is involved when a `Binding<T, U>` no longer works because we have added out-of-the-box support for `T` is that `Binding<T, U>` currently has a `Converter<T, U>` reference, which isn't strictly needed, but is confusing for users: https://github.com/jOOQ/jOOQ/issues/4819

In the future, we might introduce a replacement `Binding2<U>` type, which no longer has a `<T>` type reference, because it really isn't relevant.

Since you have found a workaround using SimpleFlatMapper, I'm closing this now.
