### ISSUE TITLE
Invalid SQL rendered for PostgreSQL CTE

### ISSUE THREAD

**Issue by XhstormR** [jOOQ/jOOQ#9521]
### Expected behavior and actual behavior:
I have the following JOOQ code to perform PostgreSQL recursive queries, written in kotlin:
```kotlin
create.withRecursive(NodeTree.TREE)
    .`as`(
        create
            .select(
                NODE.ID.`as`(NodeTree.N_ID),
                NODE.PARENT_ID.`as`(NodeTree.N_PID),
                NODE.NAME.`as`(NodeTree.N_NAME),
                DSL.zero().`as`(NodeTree.N_LEVEL)
            )
            .from(NODE)
            .where(NODE.ID.eq(1))
            .unionAll(
                create
                    .select(
                        NODE.ID,
                        NODE.PARENT_ID,
                        NODE.NAME,
                        DSL.one().plus(NodeTree.LEVEL)
                    )
                    .from(NODE)
                    .innerJoin(NodeTree.TREE).on(NodeTree.ID.eq(NODE.PARENT_ID))
            )
    )
    .select()
    .from(NodeTree.TREE)
    .fetch()
```
```kotlin
object NodeTree {
    const val TREE = "tree"

    val N_ID: Name = DSL.name(TREE, "id")
    val N_PID: Name = DSL.name(TREE, "pid")
    val N_NAME: Name = DSL.name(TREE, "name")
    val N_PATH: Name = DSL.name(TREE, "path")
    val N_LEVEL: Name = DSL.name(TREE, "level")

    val ID: Field<Any> = DSL.field(N_ID)
    val PID: Field<Any> = DSL.field(N_PID)
    val NAME: Field<Any> = DSL.field(N_NAME)
    val PATH: Field<String> = DSL.field(N_PATH).cast(String::class.java)
    val LEVEL: Field<Any> = DSL.field(N_LEVEL)
}
```

The above code is in spring boot 2.2.0, using spring boot default jooq 3.12.1 version works fine, the generated SQL statement is:
```sql
WITH RECURSIVE "tree" AS ((
		SELECT
			"erp_test"."node"."id" AS "id",
			"erp_test"."node"."parent_id" AS "pid",
			"erp_test"."node"."name" AS "name",
			0 AS "level" 
		FROM
			"erp_test"."node" 
		WHERE
			"erp_test"."node"."id" = 24 
			) UNION ALL
		(
		SELECT
			"erp_test"."node"."id",
			"erp_test"."node"."parent_id",
			"erp_test"."node"."name",
			( 1 + "tree"."level" ) 
		FROM
			"erp_test"."node"
			JOIN tree ON "tree"."id" = "erp_test"."node"."parent_id" 
		)) SELECT
	* 
FROM
	tree
```
![1](https://user-images.githubusercontent.com/10527522/68528929-e3e6f180-0333-11ea-9d1c-e5a72a2b9eff.jpg)

But when I upgrade the spring boot version to 2.2.1, the default jooq version is 3.12.3, SQL query failed, the generated SQL statement is:
```
WITH RECURSIVE "tree" AS ((
		SELECT
			"erp_test"."node"."id" AS "id",
			"erp_test"."node"."parent_id" AS "pid",
			"erp_test"."node"."name" AS "name",
			0 AS "level" 
		FROM
			"erp_test"."node" 
		WHERE
			"erp_test"."node"."id" = 24 
			) UNION ALL
		(
		SELECT
			"erp_test"."node"."id",
			"erp_test"."node"."parent_id",
			"erp_test"."node"."name",
			( 1 + "erp_test"."tree"."level" ) 
		FROM
			"erp_test"."node"
			JOIN tree ON "erp_test"."tree"."id" = "erp_test"."node"."parent_id" 
		)) SELECT
	* 
FROM
	tree
```
![2](https://user-images.githubusercontent.com/10527522/68528995-cbc3a200-0334-11ea-894b-a0476df2004b.png)

Translate the error message into english:
```
> Error: Invalid reference to FROM clause of table "tree"
LINE 20: JOIN tree ON "erp_test"."tree"."id" = "erp_test"."node"."...
                                      ^
HINT: There is an entry for the table "tree", but it cannot be referenced from this part of the query.
```

I compared it and found that all the `tree` temporary tables have schema added. 
eg `"tree"."id"` -> `"erp_test"."tree"."id"`
After I removed all `"erp_test"` in `"erp_test"."tree"`, become `"tree"`, the sql query succeeded.

### Versions:

- jOOQ: 3.12.3
- Java: java 12.0.1 2019-04-16
- Database (include vendor): PostgreSQL 11.1, compiled by Visual C++ build 1914, 64-bit
- OS: Microsoft Windows [版本 10.0.14393]
- JDBC Driver (include name if inofficial driver): org.postgresql:postgresql:42.2.8 (org.postgresql.Driver)

**Comment by lukaseder** [comment]
Thank you very much for your report. This is probably because of one of these fixes, which got backported to 3.12.3 or 3.12.2 respectively:

- https://github.com/jOOQ/jOOQ/issues/9457
- https://github.com/jOOQ/jOOQ/issues/9386
- https://github.com/jOOQ/jOOQ/issues/8991

I'm not sure if this is really a bug / regression. Since I'm not seeing where the `erp_test` schema is produced, I'm assuming you're using runtime schema mapping, and you're mapping *all* unqualified table references to become tables of the `erp_test` schema. There isn't really a way for jOOQ to distinguish between tables that belong to your actual schema, and other table expressions, if you apply this mapping.

I think there are two reasonable solutions:

1. Don't use the schema mapping, and use a PostgreSQL search_path instead
2. Don't use the schema mapping, but fully qualify the tables from your schema instead (e.g. `NODE`)

If you're using schema mapping, I'd say this works as designed (and the fact that it worked for you before was a bug). If there's a different reason why you're getting this `erp_test` qualification, please do let me know and I'll reopen this issue as there might be some other bug. I'd need more information on how you get that `erp_test` qualification in that case.

**Comment by XhstormR** [comment]
Yes, we have to use the schema mapping function.
We have three schemas, prod, dev, and test. We use JPA to generate the dev schema, and then specify JOOQ to use the dev schema to generate the class files. Then dynamically set the schema used by the current jooq via spring's environment class.

**Comment by lukaseder** [comment]
Thanks for the clarification. In that case, I do recommend you explicitly fully qualify all your table definitions with a schema where appropriate
