### ISSUE TITLE
Need for overload-free methods in cases where generics are used.

### ISSUE THREAD

**Issue by jakubgwozdz** [jOOQ/jOOQ#9563]
### Problem:
Kotlin language cannot resolve ambiguity when generics are combined with overloaded methods and with varargs. We need some better way to handle edge cases when the Field Type is `Object` / `Any`:

### Working *JAVA* code:

```
package test.generics;

import java.util.List;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Table;

public class GenericsJava {
  public static Condition testJooqGenerics(Table<?> table, List<Object> list) {
    Field<Object> myColumn = table.field("MY_COLUMN", Object.class);
    return myColumn.in(list);
  }
}

```

### Failing Kotlin counterpart:
```
package test.generics

import org.jooq.Condition
import org.jooq.Field
import org.jooq.Table

object GenericsKotlin {
    fun testJooqGenerics(table: Table<*>, list: List<Any>): Condition {
        val myColumn: Field<Any> = table.field("MY_COLUMN", Any::class.java)
        return myColumn.`in`(list as Collection<Any>)
    }
}
```

The code above yields this error:
```
e: /Users/jakub.gwozdz/myProject/src/test/kotlin/test/generics/GenericsKotlin.kt: (10, 25): Overload resolution ambiguity: 
@Support public abstract fun `in`(vararg p0: Any!): Condition! defined in org.jooq.Field
@Support public abstract fun `in`(p0: (Mutable)Collection<*>!): Condition! defined in org.jooq.Field
```
Obviously it all works if we're using anything but `Any`, e.g. strings or ints.

### Root cause:

The parametrized `Field` class sports methods that have same names and same number of parameters, and provides no way to select specific one when the parameter type matches more than one possibility.

### Possible workarounds:

Reified generics seems to help here:
```
object GenericsKotlin {
    inline fun <reified T> testJooqGenericsInline(table: Table<*>, list: List<T>): Condition {
        val myColumn: Field<T> = table.field("MY_COLUMN", T::class.java)
        return myColumn.`in`(list)
    }

    fun testJooqGenerics(table: Table<*>, list: List<Any>): Condition {
        return testJooqGenericsInline(table, list)
    }
}
```

### Versions:

- jOOQ: 3.12.3
- Java: OpenJDK 11.0.2
- Kotlin: 1.3.50

**Comment by lukaseder** [comment]
Thank you very much for your report.

This reminds me of a similar issue in Java:
https://stackoverflow.com/q/5361513/521799

Type inference is a complex topic. Trying to find a solution that works across languages is even harder. We're mainly focusing on Java. While we do want to offer an as-flawless-as-possible Kotlin experience, some edge cases are difficult to handle. This seems to be one of them.

We can't possibly think of this combination of types throughout the entire jOOQ API, just to be able to handle this `<Any>` edge case with overloads, without re-designing the *entire* API.

The use of this `Any` type (or `java.lang.Object`) is generally not recommended, as jOOQ will occasionally need the *correct* class reference to correctly bind a value to a `PreparedStatement`. This is especially true for `null` values.

So, I'm sure there's a better solution in your client code. The reified generic solution is one such possibility. Another would be to look at the list's first element, and take its type, rather than `Any`. A third would be to use code generation or another way of defining your `"COLUMN"` meta data.
