### ISSUE TITLE
Prevent duplicate joins

### ISSUE THREAD

**Issue by cdalexndr** [jOOQ/jOOQ#9638]
### Use case:
I have multiple filters that may require additional table joins to filter data. Each filter decorates a `SelectJoinStep<R>` object. If two filters require the same join, only one join should be registered.

### Possible solution you'd like to see:
Duplicate joins should be eliminated.
Alternative, a method to query if the join is already registered will allow the user to check and skip that join.

### Possible workarounds:
Join all possible tables and expect the database planner to eliminate joins.
Or, additional user code to handle unique join registration, such as a Set of helper classes for each join required, that will be applied to the query.

### Versions:

- jOOQ: 3.11.10
- Java: 11.0.5
- Database (include vendor): Postgres
- OS: Windows 10
- JDBC Driver (include name if inofficial driver):

**Comment by lukaseder** [comment]
Thank you very much for your suggestion. Very interesting coincidence with this other suggestion: #9635.

Good commercial optimisers will recognise duplicate joins, see some examples in this article: https://blog.jooq.org/2017/09/28/10-cool-sql-optimisations-that-do-not-depend-on-the-cost-model/, but to prove that two joins are strictly equivalent, we'd have to traverse the entire expression tree with all the join expressions and predicates, and that cost is not worth the trouble in my opinion, given that client code can easily track the objects already added to a join graph itself.

Also, this rationale only applies to to-one joins, not to to-many joins (with some exceptions when `DISTINCT` is used). If there are duplicate to-many joins, there's a cartesian product between all the duplicated joins, which would be avoided if the duplicates were avoided. So the resulting query would no longer be the same.

> Alternative, a method to query if the join is already registered will allow the user to check and skip that join.

This, again, suffers from the same problem of recognising if "the join" is already registered. Whether two joins are equivalent depends on at least the table expression *and* the predicates involved with the join, and these predicates can reside in both `ON` and `WHERE` clauses, or worse, in lateral derived tables and other correlated subqueries, so we don't want to do this work in jOOQ.

> Or, additional user code to handle unique join registration, such as a Set of helper classes for each join required, that will be applied to the query.

This should definitely be the approach here.

Notice that if we're discussing to-one joins, then you can always use jOOQ's implicit join syntax, which will never join the same table twice behind the scenes. It does exactly what you want, because it fully controls how implicit joins are created, so there's no risk of having to traverse any correlated subqueries to search for join equivalence.

More info here:
https://blog.jooq.org/2018/02/20/type-safe-implicit-join-through-path-navigation-in-jooq-3-11/

**Comment by cdalexndr** [comment]
@lukaseder 
>  jOOQ's implicit join syntax, which will never join the same table twice behind the scenes

The following code:
```
dsl.select( PRODUCT.ID)
        .from( PRODUCT )
        .leftJoin( PRODUCT_INFO).on( PRODUCT_INFO.PRODUCT_ID.eq( PRODUCT.ID ) )
        .leftJoin( PRODUCT_INFO).on( PRODUCT_INFO.PRODUCT_ID.eq( PRODUCT.ID ) )
        .getQuery().getSQL()
```
Results in duplicate join:
```
SELECT "product"."id"
FROM "product"
LEFT OUTER JOIN "product_info" ON "product_info"."product_id" = "product"."id"
LEFT OUTER JOIN "product_info" ON "product_info"."product_id" = "product"."id"
```

**Comment by lukaseder** [comment]
There was another comment with an example, which has now been deleted. Just to be sure my point is understood. These are "duplicate joins" as well:

```sql
SELECT * FROM t, t, t;
SELECT * FROM t CROSS JOIN t CROSS JOIN t;

-- Some dialects (like Oracle) do not require aliasing derived tables:
SELECT * FROM (VALUES (1, 2)), (VALUES (1, 2)), (VALUES (1, 2));
```


All of these duplications may be desired. The exact rules which constitute an "accidental, undesired duplicate join" are really hard to define. It's *much* easier to just revert to executing *exactly* what a jOOQ user tells jOOQ to execute.

Hope this helps.
