### ISSUE TITLE
`org.jooq.DataType[Object]` is invariant, which causes problems for Scala generation 

### ISSUE THREAD

**Issue by toddobryan** [jOOQ/jOOQ#9649]
### Expected behavior and actual behavior:
I have a couple of columns that use Postgres's `interval hour to second` type. When I run the Scala code generator on those tables, I get this in the two versions of JOOQ:

3.11.12
`val START_OFFSET : TableField[ReleaseWorkRecord, PGInterval] = createField("start_offset", org.jooq.impl.DefaultDataType.getDefaultDataType("\"pg_catalog\".\"interval\""), "", new PgIntervalBinding())`

3.12.3:
`  val START_OFFSET : TableField[ReleaseWorkRecord, PGInterval] = createField(DSL.name("start_offset"), org.jooq.impl.SQLDataType.INTERVAL, "", new PgIntervalBinding())`

Unfortunately, the second one causes an error.
```
type mismatch;
[error]  found   : org.jooq.DataType[org.jooq.types.YearToSecond]
[error]  required: org.jooq.DataType[Object]
[error] Note: org.jooq.types.YearToSecond <: Object, but Java-defined trait DataType is invariant in type T.
[error] You may wish to investigate a wildcard type such as `_ <: Object`. (SLS 3.2.10)
[error]   val START_OFFSET : TableField[ReleaseWorkRecord, PGInterval] = createField(DSL.name("start_offset"), org.jooq.impl.SQLDataType.INTERVAL, "", new PgIntervalBinding())
```
I checked both in Scala 2.12.8 and 2.13.1, and the error happens in both. My guess is that `PgIntervalBinding` has to somehow be more specific about what type it converts to or has to use one of those wacky `<? extends Object>` kinds of type declarations. Didn't discover it early enough in the night to actually take a look.

My workaround for the moment is to stay on JOOQ 3.11, but if there's some way to fix this, I'd love to upgrade. 

### Versions:

- jOOQ: 3.11.12 and 3.12.3
- Java: 8
- Database (include vendor): Postgres 10.10
- OS: Ubuntu
- JDBC Driver (include name if inofficial driver): org.postgres:postgresql:42.2.9

**Comment by lukaseder** [comment]
Thank you very much for your report.

I'm not sure if this is a bug - it happens every time we add native support for a new data type in `SQLDataType`, as in this case, for `SQLDataType.INTERVAL` (#8077). Similar cases have been reported for our new native `JSON` and `JSONB` support. We should think of defining these changes as backwards incompatible, in the future, as existing data type bindings that use `Binding<Object, UserType>` no longer work - both in Java and in Scala.

The solution is to fix the binding to bind the jOOQ type `YearToSecond` to your custom type. Since your custom type is `PGInterval`, you might not even need any binding anymore. Alternatively, you can just switch the types in your binding, and leave the implementation as it is, as you can safely ignore the jOOQ type if you're using your own binding.

I hope this helps.
