### ISSUE TITLE
Sql serialization of boolean type field in Azure sql datawarehouse is in correct

### ISSUE THREAD

**Issue by souravjha77** [jOOQ/jOOQ#9655]
E.g. 

```java
Field<?> field = DSL.val(Boolean.TRUE);
field = field.coerce(SQLDataType.BOOLEAN);
Assert.assertEquals("select cast(1 as bit) from Date",
  DSL.using(SQLDialect.SQLDATAWAREHOUSE)
    .select(field)  
    .from(DSL.table("DATE"))
    .getSQL(ParamType.INLINED));
```

**Comment by lukaseder** [comment]
Thank you very much for your message.

Please use `DSL.cast(Field, DataType)`, or `Field.cast(DataType)`, not `coerce()`. The `coerce()` method is used to "coerce" the type of an expression on the client side, without any effect on generated SQL, whenever this is desireable.

I hope this helps

**Comment by souravjha77** [comment]
```
Field<?> field = DSL.val(Boolean.TRUE);
Assert.assertEquals("select cast(1 as bit) from Date",
  DSL.using(SQLDialect.SQLDATAWAREHOUSE)
    .select(field)  
    .from(DSL.table("DATE"))
    .getSQL(ParamType.INLINED));
```
Do i need to cast in above scenario explictly? The excpected behaviour should be sql serialization should take care of it.

**Comment by lukaseder** [comment]
The default T-SQL implementation of Java's boolean type in jOOQ is `BIT`, so I would say you don't need to cast explicitly. However:

1. Often, such examples are simplified and the real world example is more complex, so I can't tell if you have to cast in your real world example
2. I'm not sure what your assertion is trying to do. The exact SQL produced by jOOQ may subtly change depending on what jOOQ features you're using. Again, there's no guarantee for such a cast, even if in some cases, it may arise because jOOQ finds it's necessary.

I'll be happy to help you with more specific questions you may have. Curious about your real-world use-case...
