### ISSUE TITLE
Methods for interface FieldLike

### ISSUE THREAD

**Issue by kevinarpe** [jOOQ/jOOQ#9701]
First, I am relatively new user to jOOQ (~6 months), but I am very impressed.  Keep up the great work!  I wish you success on your journey.  :-)

### Your question:

Before asking your question, please check out the FAQ too: https://www.jooq.org/faq -> Done!

I noticed your API is very "rich" -- you always make an effort to support multiple calling conventions and types in method signatures.  For me, this makes it easier to learn the API through exploration and discovery in an advanced Java IDE -- IntelliJ, Eclipse, NetBeans, etc.  Simple example: `.and(), .andExists(), .andNotExists(), DSL.exists(), DSL.not()...` etc.

Regarding `interface FieldLike`, it is "missing" this method: `<T> Field<T> asField(Name name)`

If this is an intentional design decision, could you share why?  Else, it might be a nice, small API addition.

It seems possible to call `Field.as(Name)` on the result, but I am not an expert for this API, so it may have unintended consequences.

### Versions:

- jOOQ: 3.12.3
- Java: 11+ (w/ Apache Maven 3.6+)
- Database (include vendor): SQLite (in-memory and file-on-disk)
- OS: Linux, Windows
- JDBC Driver (include name if inofficial driver): Maven Central -> org.xerial:sqlite-jdbc:3.30.1

**Comment by lukaseder** [comment]
Thank you very much for your report, and for your nice words.

Indeed, `FieldLike.asField(Name)` is missing, and currently cannot be added easily, because the overload taking a `Function` currently binds the function result type to `String`. Unable to have to `asField(Function)` overloads with different generic type bounds (due to erasure), we cannot consistently add an `asField(Name)` method right now.

This has not been addressed yet, because the `FieldLike.asField()` and `TableLike.asTable()` methods are historic artefacts from an earlier jOOQ version. These methods allowed for aliasing correlated subqueries. Today, correlated subqueries should be wrapped using `DSL.field(Select)`, and if aliasing is desired, then `DSL.field(Select).as(name)` can be used.

Having said so, right now, I recommend you use `Field.as(Name)` if the type you're calling this method on is really a `Field`, and not "just" a `FieldLike`.
