### ISSUE TITLE
RenderMapping case sensitive?

### ISSUE THREAD

**Issue by luckfamousa** [jOOQ/jOOQ#9706]
### Your question:

I was using JOOQ to select from partitioned tables (like here https://blog.jooq.org/tag/table-inheritance/) and only got it to work when explicitly making all strings in RenderMapping lowercase. All other combinations did not work. Is this intended? I would have expected it to be case insensitive. Or is it because I am using JOOQ from Scala (I don't see why)?

```scala
val settings = new Settings()
  .withRenderMapping(new RenderMapping()
    .withSchemata(new MappedSchema()
        .withInput("public")
        .withOutput("public")
        .withTables(
          new MappedTable()
            .withInput("my_resources")
            .withOutput(("my_"+resource).toLowerCase))))
```

### Versions:

- jOOQ: 3.12.3
- Scala: 2.12.8
- Database (include vendor): PostgreSQL 12
- OS: MacOS
- JDBC Driver (include name if inofficial driver): org.postgresql.Driver

**Comment by lukaseder** [comment]
Thank you very much for your message.

Most of jOOQ's name / identifier management is case sensitive, regardless if the database identifier is case sensitive or not. There are good historic reasons for defaulting to this:

- Vendors differ largely with respect to how they treat case sensitivity. Some RDBMS are always case insensitive (e.g. the T-SQL family including SQL Server, Sybase SQL Anywhere, or SQLite). Some RDBMS are mostly case insensitive (e.g. MySQL, with some weird exceptions). Some RDBMS are case insensitive by default, but case sensitive when identifiers are quoted (e.g. Oracle, PostgreSQL). And some RDBMS are always case sensitive (e.g. Sybase, depending on the installation configuration). A full list can be seen here: https://github.com/jOOQ/jOOQ/issues/9633
- jOOQ has a few features that do not have access to a `Configuration` object, especially when using static methods, and as such, it is not always possible to access the `SQLDialect` that would govern the default behaviour per database product, or the `Settings`, which would allow for overriding the default behaviour (including the `Locale`, which defines edge cases in languages like Turkish)

Following the above, the default in jOOQ is to treat identifiers as case sensitive. While this can be inconvenient, it is guaranteed to allow for correct code in all cases, including when someone decides to have a table named `"Aa"`, and another table named `"aA"` in PostgreSQL or Oracle.

We're working on improving this wherever it makes sense in the future, including the settings. For this, we'll have to re-design the `Settings` first, we'd have to allow for using `org.jooq.Name` instead of `String` to define identifiers in the `RenderMapping`. We're planning on doing this as part of jOOQ 3.14's re-design of the query object model: https://github.com/jOOQ/jOOQ/issues/9167

For the time being, notice that instead of using an `input` of type `String`, you can provide a `Pattern` as `inputExpression`, and use the `(?i:...)` syntax to make your regular expression case insensitive: https://www.jooq.org/javadoc/latest/org.jooq/org/jooq/conf/MappedSchema.html#inputExpression

```java
val settings = new Settings()
  .withRenderMapping(new RenderMapping()
    .withSchemata(new MappedSchema()
        .withInputExpression(Pattern.compile("(?i:public)"))
        .withOutput("public")
        .withTables(
          new MappedTable()
            .withInputExpression(Pattern.compile("(?i:my_resources"))
            .withOutput(("my_"+resource).toLowerCase))))
```
