### ISSUE TITLE
Mapping schema with RegEx generates invalid output name after upgrade to 3.12

### ISSUE THREAD

**Issue by vicmosin** [jOOQ/jOOQ#9708]
### Expected behavior and actual behavior:

Assuming we have the following code applied:

```
private static final Pattern INPUT_PATTERN = Pattern.compile("^(.*)");
Configuration configuration = baseConfig.derive();
return configuration.derive(new Settings()
            .withRenderMapping(new RenderMapping()
                .withSchemata(new MappedSchema()
                    .withInputExpression(INPUT_PATTERN)
                    .withOutput(tenantId + "-$1"))));
```

**Actual:**
Error while accessing the database: 
```
org.springframework.jdbc.BadSqlGrammarException: jOOQ; bad SQL grammar [select `test-test-events`.`room`.`id` ...  from `test-test-events`.`room`
```
Catalog name contains extra prefix i.e. `test-test-events`.

**Expected:**
Catalog name is `test-events`.

**The issue appears after upgrade from 3.11.12 to 3.12.3**

### Versions:

- jOOQ: 3.12.3
- Java: 10
- Database (include vendor): MariaDB (also happens on `org.testcontainers.mariadb:1.10.5`) 
- OS: MacOS Mojave 10.14.6
- JDBC Driver (include name if inofficial driver): `org.mariadb.jdbc:mariadb-java-client:2.4.4`

**Comment by knutwannheden** [comment]
I can confirm this issue. The problem was introduced with the commit https://github.com/jOOQ/jOOQ/commit/b991cf58a5217d937bc6c9a36b3f66bdde591392 which leads to the schema mapping being applied twice.

Once in `TableImpl#accept0()`: https://github.com/jOOQ/jOOQ/blob/680cd20d0829f1ec3bb345d3e70e4e1eb3d31705/jOOQ/src/main/java/org/jooq/impl/TableImpl.java#L250-L255

And once in `SchemaImpl#accept()`, which ends up getting called by line 253 above): https://github.com/jOOQ/jOOQ/blob/680cd20d0829f1ec3bb345d3e70e4e1eb3d31705/jOOQ/src/main/java/org/jooq/impl/SchemaImpl.java#L120-L121

**Comment by knutwannheden** [comment]
The fix to this issue will be backported to the upcoming 3.12.4 maintenance release.

Customers paying for a jOOQ commercial edition will be able to download and test a 3.12.4 SNAPSHOT release from https://www.jooq.org/download/versions including this fix.
