### ISSUE TITLE
DefaultRecordMapper should skip @Transient annotated members

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#9714]
In addition to #4586, which is about also considering members without `@Column` annotation for mapping, any `@Transient` annotated members should be skipped.

**Comment by lukaseder** [comment]
The Javadoc is not very clear to me: https://docs.oracle.com/javaee/7/api/javax/persistence/Transient.html

> Specifies that the property or field is not persistent

What I'm reading into this is that the properties are not *stored*, but can they be loaded / mapped, when present in a result set, or should they be ignored completely?

**Comment by lukaseder** [comment]
Side-note: Personally, I've grown a bit "bored" with the JPA annotation support in `DefaultRecordMapper`. When I added the current basic support, I thought it would be better to support pre-existing, popular annotations, rather than implement `org.jooq.mapping.Column` annotations, and the like.

But let's be honest, we will never go far beyond a half-assed JPA "implementation", no matter how many of these little things we'll fix. We also do not want to spend the time to pass the TCK (let alone license it). So, not strictly related to this particular issue, or to #4586, it might be worth thinking about whether we should continue supporting JPA annotations in the `DefaultRecordMapper` in the first place.

Alternatively, we could create an "abandoned", independent Open Source project that implements the status quo for those people that depend on it, while removing the feature from the core library. Related to: https://github.com/jOOQ/jOOQ/issues/8599

**Comment by knutwannheden** [comment]
> it might be worth thinking about whether we should continue supporting JPA annotations in the `DefaultRecordMapper` in the first place.

See also #4263.

**Comment by lukaseder** [comment]
> See also #4263.

Yes, I remember this discussion.

Still, I think we should move this logic out of core jOOQ. The dependency on JPA API has always bothered me. Also, while I understand the migration use-case explained in #4263 by several people, I would not want new users to think they should use this feature for new, jOOQ-only applications.

Having this as an extension with a clear notion of being for migration purposes only will better communicate our own intent.

**Comment by knutwannheden** [comment]
Yes, adding `jOOQ-extensions` back in sounds like a good solution.

**Comment by lukaseder** [comment]
The `DefaultRecordMapper` support for JPA annotations may have been added prematurely a very long time ago. It's not the most idiomatic approach to mapping things in jOOQ, especially since jOOQ 3.15's ad-hoc converter APIs, which are all type safe.

We won't add more complexity to the reflective mappings anymore, see also: https://github.com/jOOQ/jOOQ/issues/4263
