### ISSUE TITLE
Would closing a DSLContext cancel running executions?

### ISSUE THREAD

**Issue by encodeering** [jOOQ/jOOQ#9735]
### Your question:

Would like to know if a closed context would lead to a cancellation of e.g 
* a query or other executions `org.jooq.Query#cancel` 
* subsequent executions that would follow up in the same same context

Background: 

Kotlin provides a way to cancel coroutines and it would be, looking at the current situation, easier to interact with this context (higher abstraction) instead of knowing what actually needs to be cancelled inside of the context.

Example:

Free resources on request timeouts or connection resets.

### Versions:

- jOOQ: 3.12.1
- Java: 11.0.4
- Database (include vendor): Postgres 10.x
- OS: Debian
- JDBC Driver (include name if inofficial driver): postgresql 42.2.6

**Comment by lukaseder** [comment]
`DSLContext` implements `AutoCloseable`, because there exist some ways of constructing a `DSLContext` where it is the user's responsibility to close it again, as the underlying JDBC connection is managed by jOOQ. Such construction methods include:

- `DSL.using(String)`
- `DSL.using(String, Properties)`
- `DSL.using(String, String, String)`

It's unlikely that you're using these, so I doubt that you will get your desired effect from calling `close()`.

Notice that calling `close()` just closes the underlying, jOOQ-managed JDBC connection in those cases. It does not call `Statement.cancel()` explicitly on any such statement.

I suspect that you will need to implement your own `ConnectionProvider` in order to inject this behaviour into jOOQ.

I hope this helps.
