### ISSUE TITLE
Generating empty IN lists in H2

### ISSUE THREAD

**Issue by sam-step** [jOOQ/jOOQ#9739]
### Your question:

In version [3.12 jOOQ added support](https://github.com/jOOQ/jOOQ/issues/8856) for generating empty lists in `IN` conditions for H2. However, all of the H2 compatibility modes [do not support empty lists](https://github.com/h2database/h2database/blob/master/h2/src/main/org/h2/engine/Mode.java).

Is there an advantage to generating the empty list opposed to the false condition like jOOQ does for databases that do not support this syntax? And, if not, would it make sense to revert this behavior for H2?
### Versions:

- jOOQ: 3.12.3
- Database (include vendor): H2 1.4.200

**Comment by lukaseder** [comment]
Thank you very much for your message.

### Regarding your questions

> Is there an advantage to generating the empty list opposed to the false condition like jOOQ does for databases that do not support this syntax? 

Yes there is an advantage. jOOQ tries to avoid all sorts of emulations if a target dialect supports a syntax natively. If someone writes `FIELD.in()`, the expectation might actually be for jOOQ to generate `FIELD in ()`, in SQL. It just happens to be the case that almost no dialect supports this.

Imagine we have support for `CONNECT BY` in our API, which is only supported by Informix and Oracle (and the deprecated CUBRID). Your line of thoughts, if taken to the extreme, would suggest we emulate this to generate a recursive `WITH` query, even on Informix and Oracle (it is far more difficult to emulate, but you get the point).

The first and foremost strategy of jOOQ is to generate exactly the SQL users intended for jOOQ to generate. Only if that particular syntax is not natively supported, we emulate.

> And, if not, would it make sense to revert this behavior for H2?

It would not make sense to revert this by default. We could discuss if jOOQ should, instead of hard-wiring behaviour on a per-dialect basis, expose a set of feature flags that would allow for overriding the behaviour of each individual syntax, irrespective of the target dialect.

That would be a ton of maintenance with little benefit for most users, and has been rejected several times in the past.

### The actual problem

However, this particular syntax is not the actual problem you're trying to solve. The actual problem seems to be that you're using H2 as an emulation of some other dialect, *and* jOOQ as an emulation of some other dialect.

So, let me return the question. Is there an advantage of running jOOQ with `SQLDialect.H2` on H2 in a compatibility mode? My suggestion here would be to either:

- Avoid using that compatibility mode in H2 and generate H2 SQL from jOOQ against native H2 syntax
- Use the compatibility mode for dialect X in H2 and generate X SQL in jOOQ as well

Of course, there's always the option of using something like testcontainers.org instead of H2 to run integration tests, and thus remove the risk of having dialect specific issues like these...

**Comment by katzyn** [comment]
Empty `IN` predicate is currently disallowed in all compatibility modes of H2 with exception for Regular one, it can be enabled or disabled explicitly in all these modes by the end user, but whether it should be allowed by default or not is an open question; the final decision is not taken yet. Documentation of H2 also requires a subquery or at least one expression. So I'm not sure that generation of an empty `IN()` for H2 is a good idea.

H2 replaces `something IN()` with `FALSE` immediately; the expression on the left side is not fully verified for non-parsing errors and is not preserved.

**Comment by lukaseder** [comment]
> So I'm not sure that generation of an empty `IN()` for H2 is a good idea.

I vaguely remember having discussed this with you before. SQLite also supports the syntax and documents it:

![image](https://user-images.githubusercontent.com/734593/72540352-fc6a0f80-3880-11ea-8f10-d659789d4d1c.png)

https://www.sqlite.org/syntax/expr.html

I was not aware that your implementation was still up for debate, or that it was not yet documented.

In any case, I rest my case about the distinction between what is being discussed here (the empty `IN` list), and what should be discussed here (the mix of dialects and libraries)...

**Comment by katzyn** [comment]
Maybe we discussed this, but I don't remember.

Documentation of H2 clearly does not allow empty IN predicate. So H2 does not “support” it, H2 only silently accepts it for historic reasons. I also don't remember why such behavior wasn't disabled by default for Regular mode too in 1.4.200, but it still can be disabled by default in the future.

From the JDBC perspective H2 officially supports `= ANY(?)` and with `Object[]` parameter and the specified array may be empty.
