### ISSUE TITLE
Alternative to deprecated createUniqueKey

### ISSUE THREAD

**Issue by redhead** [jOOQ/jOOQ#9765]
`AbstractKeys.createUniqueKey()` was deprecated, but no docs mention what to use instead of it.
We create dynamic tables in Java, and some tables have unique keys as part of their definition, and then they are returned by `getKeys()` method so DDL can create them.

I was looking for another "factory" methods, but no luck. `UniqueKeyImpl` is package-private.

- jOOQ: 3.12.3

**Comment by lukaseder** [comment]
Thank you very much for your message. The replacement is in `org.jooq.impl.Internal`, the `AbstractKeys.createUniqueKey()` method delegates to the `Internal` method.

Do note that these methods are "internal" (both before and after deprecation), meaning that we do not guarantee backwards compatibility. They are meant to be called by code generated by the code generator.

I hope this helps.

**Comment by redhead** [comment]
Ok, I didn't notice that `AbstractKeys` was internal API too.

So question from the other end. Shouldn't there be public API available that is not internal for these cases (e.g. create indexes).

**Comment by lukaseder** [comment]
> Ok, I didn't notice that `AbstractKeys` was internal API too.

One reason why we moved the method was because the new type makes this much more clear than the Javadoc on `AbstractKeys`.

> So question from the other end. Shouldn't there be public API available that is not internal for these cases (e.g. create indexes).

Yes: https://github.com/jOOQ/jOOQ/issues/7444. But public API is *much* more difficult to design and maintain than internal API, and in most cases, you don't need these APIs. The main exception is when for some reason you don't want to use code generation (which we almost always recommend to use).

**Comment by redhead** [comment]
Ok, thanks.

We can't use code generation, as the tables are dynamic in runtime.
