### ISSUE TITLE
Is onDuplicateKeyUpdate() supported in postgresql

### ISSUE THREAD

**Issue by selckin** [jOOQ/jOOQ#9847]
Hello,

Was trying to figure out if onDuplicateKeyUpdate() is supported on postgresql.
The method is annotated with @Support POSTGRES, but from the docs https://www.jooq.org/doc/latest/manual/sql-building/sql-statements/insert-statement/insert-on-duplicate-key/#N5F1F7 I believed it wasn't. From that i conclude this is mysql specific, jooq can emulate it with MERGE on other databases.

https://www.jooq.org/doc/3.13/manual/sql-building/sql-statements/merge-statement/ does not list postgres as supported (as does the first (2year) old comment)

Many comments on the onDuplicateKeyUpdate page suggest using onConflict(), which also resulted from a few google searches. (maybe all outdated)

Which let me to believe maybe the @Support annotation was wrong, and i tweeted lukas, who asked me to post here in more detail

Thanks

**Comment by lukaseder** [comment]
> from the docs https://www.jooq.org/doc/latest/manual/sql-building/sql-statements/insert-statement/insert-on-duplicate-key/#N5F1F7 I believed it wasn't

What made you think it wasn't? The fact that we didn't list the emulation? Or because we wrote *"i.e. if they support the SQL standard MERGE statement"* instead of *"e.g. if they..."*?

I can see that this documentation can be confusing because we list *some* emulations, but certainly not *all*.

We never list all emulations in the docs, because

1) Such exhaustive docs would hardly ever be up to date (there is a pending feature request to generate some docs from executed code)
2) Such exhaustive docs would be quite distractive

> The method is annotated with @Support POSTGRES

In fact, in almost all cases, you can trust these annotations. We use the annotations in our integration tests as well to validate their correctness, and to govern what tests should be run on what dialect.

Caveats:

- Something might work on dialect X, and we haven't annotated the method *yet*
- Something might be annotated, and we are not covering the method by integration tests *yet* (so a latent bug might have remained undiscovered)

> https://www.jooq.org/doc/3.13/manual/sql-building/sql-statements/merge-statement/ does not list postgres as supported (as does the first (2year) old comment)

Indeed, very unfortunately, PostgreSQL decided to implement a vendor specific feature called `ON CONFLICT` instead of supporting the standard `MERGE` statement. It is not possible to emulate `MERGE`, as it is much too powerful.

> Many comments on the onDuplicateKeyUpdate page suggest using onConflict(), which also resulted from a few google searches. (maybe all outdated)

The reason for this suggestion is: `ON CONFLICT` is what's supported natively by PostgreSQL. If you're not also trying to support MySQL, you shouldn't use `ON DUPLICATE KEY UPDATE`.

I hope this helps.

**Comment by lukaseder** [comment]
We'll replace "i.e." by "e.g." for avoidance of doubt.

**Comment by selckin** [comment]
The fact that it states, if they support MERGE, and then the MERGE page says

 'The MERGE statement is one of the most advanced standardised SQL constructs, which is supported by DB2, HSQLDB, Oracle, SQL Server and Sybase (MySQL has the similar INSERT .. ON DUPLICATE KEY UPDATE construct)"

which does not include postgres, and in the comments has

> Does this work for PostgreSQL?
>> Nope


There must be some implicit postgres supports all standard sql that is not obvious to me

**Comment by selckin** [comment]
Ah yeah, so i read it as merge is required to support it, which is not the case, that makes more sense.

Guess i'm bad at reading, sorry for wasting your time :(
