### ISSUE TITLE
JDBCDatabase not identifying BIGINT or TIMESTAMP columns for Snowflake

### ISSUE THREAD

**Issue by jvelonis** [jOOQ/jOOQ#9850]
### Expected behavior and actual behavior:
Generating code for a table with BIGINT and TIMESTAMP columns, I expect the generated Record class to use type Long or BigInteger or BigDecimal for the former, and java.sql.Timestamp or java.time.LocalDateTime for the latter.  Instead, it uses type Object and marks the accessors @Deprecated with a comment "Unknown data type".

### Steps to reproduce the problem (if possible, create an MCVE: https://github.com/jOOQ/jOOQ-mcve):

```java
Configuration config = new Configuration()
    .withJdbc(new Jdbc()
        .withDriver(...)
        .withUrl(...)
        .withUser(...)
        .withPassword(...)
    )
    .withGenerator(new Generator()
        .withDatabase(new Database()
            .withName("org.jooq.meta.jdbc.JDBCDatabase")
            .withInputSchema("MY_SCHEMA")
            .withIncludeTables(true)
            .withIncludeSequences(true)
            .withIncludePrimaryKeys(true)
            .withRecordVersionFields("UPDATE_COUNT")
        )
        .withGenerate(new Generate()
            .withJavaTimeTypes(true)
        )
        .withTarget(new Target()
            .withPackageName(...)
            .withDirectory(...)
        )
    );
GenerationTool.generate(config);
```

I wrote a little code to dump the relevant JDBC DatabaseMetaData:

```java
Map<Integer, String> sqlTypeNames = Arrays.stream(JDBCType.values())
    .collect(Collectors.toMap(JDBCType::getVendorTypeNumber, JDBCType::getName));

DataSource dataSource = ...  // set up data source

try (Connection conn = dataSource.getConnection()) {
    DatabaseMetaData metaData = conn.getMetaData();
    try (ResultSet rs = metaData.getColumns("MY_CATALOG", "MY_SCHEMA", "MY_TABLE", null)) {
        while (rs.next()) {
            int type = rs.getInt("DATA_TYPE");
            System.out.println(String.format("%s %s %d (%s)",
                rs.getString("COLUMN_NAME"),
                rs.getString("TYPE_NAME"),
                type,
                sqlTypeNames.getOrDefault(type, "???")
            ));
        }
    }
}
```

This outputs

```
ID NUMBER -5 (BIGINT)
NAME VARCHAR 12 (VARCHAR)
DESCRIPTION VARCHAR 12 (VARCHAR)
STATUS VARCHAR 12 (VARCHAR)
CREATED_AT TIMESTAMPTZ 93 (TIMESTAMP)
UPDATED_AT TIMESTAMPTZ 93 (TIMESTAMP)
UPDATE_COUNT NUMBER -5 (BIGINT)
```

Maybe the code generator is looking at TYPE_NAME in the metadata instead of DATA_TYPE?

### Versions:

- jOOQ: 3.13.0
- Java: OpenJDK 13.0.1
- Database (include vendor): Snowflake
- OS: Mac OSX
- JDBC Driver (include name if unofficial driver): net.snowflake.client.jdbc.SnowflakeDriver version 3.6.25

**Comment by lukaseder** [comment]
Thank you very much for your message. We currently do not officially support Snowflake yet (nor do we run integration tests), so I can't tell for sure what we should be doing here.

In all dialects, we read the `TYPE_NAME` value (JDBC column number 6), because it contains more complete type information, which is generally much more useful than the JDBC types. Of course, this does not prevent dialects from sending non-standard information as `TYPE_NAME`, which we might not recognise if the dialect is not supported yet.

However, we might indeed consider reading the JDBC type value in case we do not recognise the `TYPE_NAME`. I've created a feature request for this: https://github.com/jOOQ/jOOQ/issues/9852

You can work around this in a few ways:

- Use data type rewriting in the code generator: https://www.jooq.org/doc/latest/manual/code-generation/data-type-rewrites/
- Implement your own `org.jooq.meta.Database` for Snowflake, taking inspiration from the existing ones
- Use the `DDLDatabase`: https://www.jooq.org/doc/latest/manual/code-generation/codegen-ddl

**Comment by jvelonis** [comment]
Thanks, the DDLDatabase worked for me, specifying types BIGINT and TIMESTAMP WITH TIME ZONE, which both Snowflake and H2 recognize.
