### ISSUE TITLE
Error binding OffsetDateTime [Throws error: operator does not exist: timestamp with time zone <= character varying]

### ISSUE THREAD

**Issue by brsanthu** [jOOQ/jOOQ#9886]
### Your question:
We are trying to execute dml which deletes records based on ZonedDateTime. We are using following code but running into an error.
```
dsl.execute ("delete from fieldhistory where createddate <= ? and object = ?", beforeDate.toOffsetDateTime(), objName)
Where beforeDate is ZonedDateTime and objectName is string
```
We are getting following error from postgres.
```
org.jooq.exception.DataAccessException: SQL [delete from fieldhistory where createddate <= ? and object = ?]; ERROR: operator does not exist: timestamp with time zone <= character varying
  Hint: No operator matches the given name and argument types. You might need to add explicit type casts.
  Position: 56
    at org.jooq_3.13.1.POSTGRES.debug(Unknown Source)
    at org.jooq.impl.Tools.translate(Tools.java:2751)
    at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:755)
    at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:385)
    at org.jooq.impl.DefaultDSLContext.execute(DefaultDSLContext.java:1144)
```

Questions is, how do we bind datetime value in Jooq?

PS: Created this issue in SO but no response so asking here hoping to get some responses. https://stackoverflow.com/questions/60367257/error-binding-offsetdatetime-operator-does-not-exist-timestamp-with-time-zone

### Versions:

- jOOQ: 3.13.1
- Java: Java 11
- Database (include vendor): Postgres
- OS: Linux
- JDBC Driver (include name if inofficial driver): Postgres driver

**Comment by lukaseder** [comment]
For historic reasons, jOOQ binds all JSR-310 times as strings, not as the relevant object type. This is because until recently, JDBC drivers did not support the JSR-310 types natively, and as such, using a string was not a bad default.

Unfortunately, this leads to type ambiguities, which you would not have if either:

- jOOQ didn't bind a string
- you were using the code generator and thus type safe DSL API methods

As a workaround, you can do a few things, including:

**Casting your bind variable explicitly**

```java
dsl.execute ("delete from fieldhistory where createddate <= ?::timestamptz and object = ?", beforeDate.toOffsetDateTime(), objName)
```

**Using the DSL API**

```java
dsl.deleteFrom(FIELDHISTORY)
   .where(FIELDHISTORY.CREATEDDATE.lt(beforeDate.toOffsetDateTime()))
   .and(FIELDHISTORY.OBJECT.eq(objName))
   .execute();
```

**By writing your own binding**

You can write your own data type binding and attach that to generated code, or to your plain SQL query, in case of which you would be in control of how the bind variable is sent to the JDBC driver. See:
https://www.jooq.org/doc/latest/manual/sql-building/queryparts/custom-bindings/

For example:

```java
DataType<OffsetDateTime> myType = SQLDataType.OFFSETDATETIME.asConvertedDataType(new MyBinding());
dsl.execute ("delete from fieldhistory where createddate <= {0} and object = {1}", val(beforeDate.toOffsetDateTime(), myType), val(objName))
```

We'll fix this eventually. I thought we already had a feature request but I couldn't find one, so I created one: https://github.com/jOOQ/jOOQ/issues/9902
