### ISSUE TITLE
Is it possible to get and modify table aliases from Query object?

### ISSUE THREAD

**Issue by susaiarul** [jOOQ/jOOQ#9963]
We are writing a query builder to construct the query from the user input using jOOQ. The user will provide the required fields, conditions, no.of records required and etc., In this process, we would like to provide short alias for all the tables involved in the query after the Query construction. So, is it possible to get and modify table aliases from Query object?

##### Note:

It is possible for us to provide short alias while constructing the query itself, but we need to maintain the mapping of actual alias and short alias till completion of processing all the select columns and conditions. 

### Versions:

- jOOQ: 3.12.3
- Java: 1.8
- Database (include vendor): MySQL 8.0.18
- OS: Ubuntu 16.4
- JDBC Driver (include name if inofficial driver): com.mysql.cj.jdbc.Driver

**Comment by lukaseder** [comment]
Thank you very much for your request. We currently do not offer opening up the query object model. A future implementation (see https://github.com/jOOQ/jOOQ/issues/9047 and related issues), will offer this, but we're not there yet.

In any case, we would still recommend a more functional approach where you construct query parts lazily. This way, you could postpone what to name your table / column aliases until the moment when you add them to the query, instead of adding them first, and then patching them later. We've described this approach in a blog post here:
https://blog.jooq.org/2017/01/16/a-functional-programming-approach-to-dynamic-sql-with-jooq

I hope this helps
