### ISSUE TITLE
Concat and replace

### ISSUE THREAD

**Issue by raderio** [jOOQ/jOOQ#9982]
We have in some places concat and replace methods combination.
```
author.FIRST_NAME.concat(author.LAST_NAME).replace("_", "-")
```
And we have a warning that `replace` is deprecated and instead we need to use `DSL#replace(Field, String, String)`
But we do not have a field, we have a combination(concat) of the fields.
How to handle this?

**Comment by lukaseder** [comment]
But you *do* have a field. Every column expression is a `Field`. You can try assigning your expression to a local variable (e.g. using your IDE's refactoring capabilities), and you'll see:

```java
Field<String> field = author.FIRST_NAME.concat(author.LAST_NAME);
```

I think it's important to understand that when using jOOQ, *everything* is dynamic SQL, even if it does not look like it. Here's some further reading on this topic:

- https://blog.jooq.org/2020/03/06/create-empty-optional-sql-clauses-with-jooq/
- https://blog.jooq.org/2017/01/16/a-functional-programming-approach-to-dynamic-sql-with-jooq/
- https://www.jooq.org/doc/latest/manual/sql-building/dynamic-sql/

Note that in order to take action regarding API deprecations in jOOQ, you can use the new jOOQ-refaster files to help you refactor this API usage automatically:

- https://blog.jooq.org/2020/02/25/use-the-jooq-refaster-module-for-automatic-migration-off-of-deprecated-jooq-api/

I hope this helps

**Comment by raderio** [comment]
Thank you.
Can you please advise how to change
`author.FIRST_NAME.concat(author.LAST_NAME).replace("_", "-")` to not use deprecated methods?

As `dsl.replace(author.FIRST_NAME.concat(author.LAST_NAME), "_", "-")` such method can not be found.

**Comment by lukaseder** [comment]
> Can you please advise how to change
> `author.FIRST_NAME.concat(author.LAST_NAME).replace("_", "-")` to not use deprecated methods?

My suggestion here would be to follow the instructions of this blog post for an automated migration:
https://blog.jooq.org/2020/02/25/use-the-jooq-refaster-module-for-automatic-migration-off-of-deprecated-jooq-api/

> As `dsl.replace(author.FIRST_NAME.concat(author.LAST_NAME), "_", "-")` such method can not be found.

The method is in `org.jooq.impl.DSL`
